### ISSUE TITLE
Suggestion: allow casting to texture/buffer resource types

### ISSUE THREAD

**Issue by TheRealMJP** [microsoft/DirectXShaderCompiler#1067]
Hey guys! I hope that this is okay to post here, but I wanted to suggest a new HLSL language feature just in case someone else hasn't already brought it up. In both my home and work codebases we make heavy use of "bindless" descriptors, where we use integer handles to index into unbounded texture/buffer arrays in order to access these resources in our shader code. This is very flexible since it essentially gives you global access to all of your SRV descriptors, but it's currently a bit awkward to express in HLSL since your texture/buffer arrays are strongly-typed. So you end up having to declare something like this in your shader code:

```
// Some common file shared among all shader code
Texture2D Tex2DTable[] : register(t0, space0);
Texture2DArray Tex2DArrayTable[] : register(t0, space1);
TextureCube TexCubeTable[] : register(t0, space2);
Texture3D Tex3DTable[] : register(t0, space3);
Texture2DMS<float4> Tex2DMSTable[] : register(t0, space4);
ByteAddressBuffer RawBufferTable[] : register(t0, space5);
Buffer<uint> BufferUintTable[] : register(t0, space6);

// When you want to access a resource
Texture2D myTexture = Tex2DTable[descriptorHandle];
```

You then you have to overlap these arrays onto the same global descriptor table by creating separate descriptor ranges in the root signature. This list obviously isn't exhaustive...there are many more possible combinations of texture or buffer types (we have many more in our version of this file in our codebase). And there's really infinite possibilities for StructuredBuffer types, so for those we end up having to reserve additional descriptor ranges and declare the arrays locally on a per-shader basis.

It would be great if a future version of HLSL allowed us to do something like this instead:

```
SRVDescriptor GlobalSRVTable[] : register(t0, space0);

Texture2D<float2> myTexture = Texture2D<float2>(GlobalSRVTable[descriptorHandle]);
```

That way we would only need one unbounded array in our shader code, and one unbounded descriptor range in the root signature.

Either way it's not super-critical since the current situation is workable, but I thought I would suggest this so that future code can be cleaner.

**Comment by marcelolr** [comment]
@TheRealMJP thanks for the suggestion! We don't have any immediate plans, but we've definitely been thinking about doing something to better align how the language expresses and uses bindings with D3D12's resource model.

The separate root signature model works nicely to allow you to have HLSL for D3D12 and prior versions at the same time, but like you mention, it makes it clumsy to use with some descriptor layout schemes.

Oh, and this is a perfectly fine way to start up a design / discussion thread. Thanks!

**Comment by TheRealMJP** [comment]
@marcelolr Sounds good, thank you for the response! You can go ahead and close this if it's something that's already on your radar.

**Comment by gkaerts-sbl** [comment]
Wanted to check in on this thread to see if this discussions has gotten any further internally with the team. This feature would greatly improve bindless workflows.

**Comment by zigguratvertigo** [comment]
+1 on this as well!

**Comment by stonelance** [comment]
Something like this would be incredibly useful.

**Comment by gwihlidal** [comment]
+10000!

**Comment by MrTrillian** [comment]
Hi guys, thanks for showing your interest in this! Right now, the team is focusing on hardware-related features and will likely be for the coming 6+ months, but afterwards we'll be looking into bigger improvements to the HLSL language. We certainly hear your feedback, just give us a bit of time :)

**Comment by gabadie** [comment]
+1

Even, why do we need make difference between Texture2D or Texture2D<uint>. Would be so much more convenient if we could do:

Texture2D MyTexture;
uint Texel = MyTexture.Load<uint>(...);

**Comment by python3kgae** [comment]
With https://github.com/microsoft/DirectXShaderCompiler/pull/2691
We introduced GetResourceFromHeap which could create a resource from Descriptor heap.

Simple example:

uint heapIndex;
float main(uint i:I): SV_Target {
  Buffer<float> buf = GetResourceFromHeap(heapIndex);
  return buf[i];
}

It will be a shader model 6.6 feature if everything works fine.

Thanks
Xiang

**Comment by TheRealMJP** [comment]
Thank you Xiang, this looks even better than what I proposed! I'm looking forward to trying it out once all of the necessary bits are in place.

**Comment by xoofx** [comment]
This issue can be closed now that this lovely feature is part of [Shader Model 6.6 - HLSL Dynamic Resources](https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_6_DynamicResources.html)

**Comment by TheRealMJP** [comment]
I'm going to go ahead and close this since dynamic resources are now a thing, and completely address the issues that I brought up. Thanks to everyone that helped make that happen!
