### ISSUE TITLE
Support for sampler2D, tex2D()

### ISSUE THREAD

**Issue by JesusGumbauConffx** [Microsoft/DirectXShaderCompiler#107]
The current DirectXShaderCompiler code contains references and definitions for the legacy texture sampling syntax using sampler2D, tex2D, etc.

However, the shader fails to compile if we use sampler2D / tex2D methods. Is this functionality intentionally  unplugged? Can we expect this syntax to be supported by the new compiler?

**Comment by tex3d** [comment]
Some legacy syntax, such as this, is supported by the front end, but not supported for full compilation purposes.  This is largely for tooling and file compatibility - seeing unsupported legacy constructs may not prevent you from compiling an entry point that does not use those unsupported constructs.

I do not know of a plan to increase support of legacy features such as these in the future unless a strong customer need comes to our attention.

**Comment by marcelolr** [comment]
Please open another issue with more specifics if you feel this needs further work to address. To restate what @tex3d mentioned, these aren't really there for compilation proper.
