### ISSUE TITLE
dxc does not generate debug info for entry parameters with -Zi -Od

### ISSUE THREAD

**Issue by gchak** [Microsoft/DirectXShaderCompiler#1072]
For the simple shader:
```hlsl
float4 main11(float4 inp : COLOR) : SV_TARGET0 {
    float4 a = inp;
    return a;
}
```

when compiled using "-T ps_6_0 -Zi -Od", I do not see any dbg info for the input argument "inp". There is a single llvm.dbg.declare call for "a".

**Comment by python3kgae** [comment]
Fixed by https://github.com/Microsoft/DirectXShaderCompiler/pull/1087

Thanks
Xiang

**Comment by gchak** [comment]
Thanks! Looks good! Closing.
