### ISSUE TITLE
Incorrect macro expansion

### ISSUE THREAD

**Issue by turanszkij** [Microsoft/DirectXShaderCompiler#1089]
Hi, I am experiencing an incorrect behaviour with my macros. I define macros like this for example:

`#define CBUFFER(name, slot) cbuffer name : register(b ## slot)`

If I place macros this way:

```
#define CBSLOT_WHATEVER 6
// ...
CBUFFER(myBuffer, CBSLOT_WHATEVER)
```

It will exapnd as such:

`cbuffer myBuffer : register(bCBSLOT_WHATEVER)`

Which is a syntax error. Now I could introduce helper macros for expansion, but fxc compiled this and code is nicer. Any chance there will be a fix for this? :)

**Comment by antiagainst** [comment]
Hey @turanszkij, you may want to try `-flegacy-macro-expansion`, which was introduced in #1065.

**Comment by antiagainst** [comment]
See also #1005.

**Comment by turanszkij** [comment]
Thank you, this solves it, really helpful!
