### ISSUE TITLE
[spirv]  Variable of matrix type occupies single Location.

### ISSUE THREAD

**Issue by kennyalive** [Microsoft/DirectXShaderCompiler#1096]
When I compile the vertex shader of this form:

`void main(out float3x3 colors : TEXCOORD0, out float4 tail : TEXCOORD5)
{
  ...
}
`

in the produced SPIRV we have the following:

```
OpDecorate %out_var_TEXCOORD0 Location 0
OpDecorate %out_var_TEXCOORD5 Location 1

```

It seems that from SPIRV specification standpoint it is a correct assignment of Location numbers.  But this SPIRV  forms an invalid input for Vulkan app. Vulkan specification (14.1.4. Location Assignment) adds additional restrictions on how Location numbers are distributed. For, exampe, float3x3 matrix should occupy 3 locations.

In out test app if we use `colors[1]` value as final color in the fragment shader then the actual color corresponds to the value stored in `tail` variable, since both `colors[1]` and `tail` have the same Location = 1 (from Vulkan driver standpoint) and the latter is just more lucky to be selected.

It would be nice to take into account additional graphics API requirements since it's a common use scenario. glslang compiler takes into account variable type so the location for variable `tail` for above hlsl code will be 3 (and for glsl version of the shader it assigns location as 5).

**Comment by antiagainst** [comment]
Confirmed. This is a bug that we will fix.

**Comment by antiagainst** [comment]
I've uploaded #1098 to fix this.

**Comment by kennyalive** [comment]
Thanks for the quick fix.

**Comment by antiagainst** [comment]
#1098 is merged. I'll close this. Let me know if there are still issues to fix. Thanks!
