### ISSUE TITLE
if-condition not restricted to scalar

### ISSUE THREAD

**Issue by LukasBanana** [Microsoft/DirectXShaderCompiler#110]
I'm not sure if this is already fixed, but it seems that **dxc** allows vector and matrix expressions in if-conditions.
However, in the old **fxc** this is only allowed within the ternary operator '?:' like this:
```hlsl
float4 PS() : SV_Target
{
    float2 a = float2(1, 2);
    float2 b = float2(2, 1);

    // Returns 'float4(3, 9, 3, 9)'
    return (a < b ? 3 : 9).xyxy;
}
```
For the ternary operator this seems quite reasonable, but for a standard if-condition it doesn't make much sense and is rather confusing:
```hlsl
float4 PS() : SV_Target
{
    float2 a = float2(1, 2);
    float2 b = float2(2, 1);

    // This should be rejected, but is silently evaluated to 'true'
    if (a < b)
        return 3;
    else
        return 9;
}
```

Greetings,
Lukas

**Comment by python3kgae** [comment]
Thanks for the feedback.
Should be fixed by https://github.com/Microsoft/DirectXShaderCompiler/pull/113

Xiang

**Comment by marcelolr** [comment]
@LukasBanana, I believe this is fixed - please file a new issue if you're still hitting this or some variation thereof. Thanks!
