### ISSUE TITLE
DXC compiler does not set depth bit of Texture2D when converted to spir-v code

### ISSUE THREAD

**Issue by aurolou** [Microsoft/DirectXShaderCompiler#1108]
When using the DXC compiler to convert HLSL to spir-v code, Texture2D<float> is always translated to an OpTypeImage with the depth bit set to 0 (e.g. %24 = OpTypeImage %float 2D 0 0 0 1 Unknown).
However, if using the glslangvalidator, the depth bit gets set to 1 (%24 = OpTypeImage %float 2D 1 0 0 1 Unknown). If a following operation calls OpImageSampleDrefExplicitLod, this results in different output.

I think the DXC compiler should also set the depth bit to 1 in this case to produce an equivalent spir-v output as glslang.

**Comment by antiagainst** [comment]
Hey @aurolou, I think this issue is a duplicate of #1107. I've replied there.

**Comment by antiagainst** [comment]
Discussion can happen in #1107. Will close this. Thanks for reporting! :)
