### ISSUE TITLE
SPIR-V: Compile error when using static const assignment

### ISSUE THREAD

**Issue by tafuri** [Microsoft/DirectXShaderCompiler#1112]
Compiling the following hlsl code

```hlsl
struct SData {
	float3x4 matrices[4];
};

cbuffer SBufferData {
	SData BufferData;
};

static const SData Data = BufferData;

RWStructuredBuffer<float4> Out;

[numthreads(4, 4, 4)]
void main()
{
	Out[0] = Data.matrices[0][0];
}
```

Generates the following error: `fatal error: generated SPIR-V is invalid: OpCompositeExtract result type (OpTypeArray) does not match the type that results from indexing into the composite (OpTypeArray).`

Removing the `static` before `const SData` fixes the error.

**Comment by antiagainst** [comment]
Hey @tafuri, thanks for the bug report! However, the above source code compiles fine for me with the current master and `dxc.exe  -spirv -T cs_6_0`. Could you provide the commit you are using and the command line also? Thanks!

**Comment by tafuri** [comment]
You need to compile with the `-Zpr` option to get the error. Sorry for the omission!

**Comment by antiagainst** [comment]
Confirmed. I can reproduce this issue right now.

Working on a fix.

**Comment by antiagainst** [comment]
#1116 to fix this.
