### ISSUE TITLE
PIX won't open PDBs if they are LLD files store in separate folders and not embedded in the DXIL container

### ISSUE THREAD

**Issue by galop1n** [Microsoft/DirectXShaderCompiler#1133]
I have been told the issue is fixed for the next release of PIX, keeping an issue open here in case someone else run into the problem too.

Also, i first figure it out after realizing CompileWithDebug still add the PDB information in the resulting DXIL blob. I would have assume it would skip that part as the main feature of this call is to get it in a separate blob.

**Comment by hekota** [comment]
Please use the Feedback button in PIX for reporting PIX issues. This repo is for DirectX Shader Compiler only.

About the second issue - yes, we are including the debug information into the DXIL container when using CompileWithDebug. If you don't want the debug info in DXIL please use the /Qstrip_debug compile option. 
We are aware that this is not ideal - we are considering changing the default to not include debug info in DXIL.
