### ISSUE TITLE
SPIR-V: DXC creates OpTypeBool in blocks

### ISSUE THREAD

**Issue by amddb** [Microsoft/DirectXShaderCompiler#1136]
Using a struct with a `bool` member in blocks creates invalid SPIR-V.
According to the spec abstract types such as OpTypeBool don't have a physical size.

> OpTypeBool: Declare the Boolean type. Values of this type can only be either true or false. There is *no physical size or bit pattern* defined for these values.

So in my understanding it is not valid to use them in buffer objects.
Glslang uses `uint` in that case and does a compare on load.

Repro:
Compare _dxc-bool-issue.hlsl.spv-txt_ (line 43) and _glslang-bool-issue.hlsl.spv-txt_ (line 53) in [here](https://github.com/Microsoft/DirectXShaderCompiler/files/1806466/bool-issue.zip) and observe that SPIRV-Cross is not able to disassemble the DXC generated SPIR-V due to not being able to retrieve a size for OpTypeBool.

Also, see here: https://github.com/KhronosGroup/SPIRV-Cross/issues/504

**Comment by antiagainst** [comment]
Confirmed. This is a bug that we should fix.

**Comment by antiagainst** [comment]
#1140 is landed, which addresses this.
