### ISSUE TITLE
Suffix for half literals?

### ISSUE THREAD

**Issue by JesusGumbauConffx** [Microsoft/DirectXShaderCompiler#114]
Using 'h' character as suffix for half literals produces this error:

`error: invalid suffix 'h' on floating constant`
         
Is this a bug or half precision suffix is not going to be officially supported?

Cheers.

**Comment by repi** [comment]
This is something we will need for Frostbite as well, and that current HLSL does support so some clarity here would be great

**Comment by youngkim93** [comment]
This is fixed in #92 . Just for reference, half types are implicitly converted to float. Thanks!

**Comment by repi** [comment]
Thanks @youngkim93 , I hadn't checked the dxil 1.0 branch and that fix solved it. Cheers!

**Comment by marcelolr** [comment]
Thanks for the report @repi.
