### ISSUE TITLE
SPIR-V: Compile error when using static const assignment for array

### ISSUE THREAD

**Issue by tafuri** [Microsoft/DirectXShaderCompiler#1141]
(This is a continuation of issue #1112 but I can not re-open it)

I found another case which fails. Compiling the following with `dxc.exe -spirv -T cs_5_1 -Zpr` generates a slightly different error:
`fatal error: generated SPIR-V is invalid: OpAccessChain result type (OpTypeArray) does not match the type that results from indexing into the base <id> (OpTypeArray).`

```hlsl
struct SData {
	float3x4 matrices[4];
};

cbuffer SBufferData {
	SData BufferData;
};

static const float3x4 Matrices[4] = BufferData.matrices;

RWStructuredBuffer<float4> Out;

[numthreads(4, 4, 4)]
void main()
{
	float3x4 mat = Matrices[0];
	Out[0] = mul(mat[0], float4(1, 2, 3, 4));
}
```

**Comment by antiagainst** [comment]
Thanks for the bug report! I can reproduce it and will fix.

**Comment by antiagainst** [comment]
#1144  to fix this.

**Comment by tafuri** [comment]
Thanks!
