### ISSUE TITLE
Feature Request: packoffset in cbuffer support for HLSL to SPIR-V compiler

### ISSUE THREAD

**Issue by Cry-Mory** [Microsoft/DirectXShaderCompiler#1142]
**Title**
packoffset is used in our complex shaders. To extend our support of Microsoft DirectX compiler in our code, we need this feature to be supported by the HLSL to SPIR-V compiler. We would be very appreciated if you can help us with it.

If I can help with providing sample shaders, please let me know.

**Comment by antiagainst** [comment]
We hear you. We'll discuss internally to see what we can do with this feature. In the meantime, would you mind to provide some examples that you'd specifically like to be supported? With thoughts on the desired SPIR-V CodeGen would be even awesome. :)

**Comment by Cry-Mory** [comment]
[Illum_DebugPassPS.hlsl.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/1824674/Illum_DebugPassPS.hlsl.txt) is a shader containing a constant buffer called _PER_MATERIAL_ that is using _packoffset_ in its definition.

**Comment by Cry-Mory** [comment]
Since the shaders using this feature are pretty complicated I wrote a simple one for testing. 
I tried [packOffsetSample.hlsl.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/1824742/packOffsetSample.hlsl.txt) with the following dxc command to compile:

_**.\dxc -spirv -fvk-use-glsl-layout -Od -Zpr .\packOffsetSample.hlsl -Fo .\packOffsetSample.spv -T ps_5_0 -E packOffsetSamplePS -Fc packOffsetSample_currentOutput.txt**_

[packOffsetSample_currentOutput.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/1824743/packOffsetSample_currentOutput.txt) is the resulting file. Everything in the shader seems to be fine. Only the _type_PER_MATERIAL_ definition needs to be adjusted to reflect packoffset keywords. In the results file we have the following decoration definition block:

**OpMemberDecorate %type_PER_MATERIAL 0 Offset 0
OpMemberDecorate %type_PER_MATERIAL 1 Offset 4
OpMemberDecorate %type_PER_MATERIAL 2 Offset 8
OpMemberDecorate %type_PER_MATERIAL 3 Offset 12**
 
According to packoffset keywords, this needs to change to the following block:

**OpMemberDecorate %type_PER_MATERIAL 0 Offset 576
OpMemberDecorate %type_PER_MATERIAL 1 Offset 608
OpMemberDecorate %type_PER_MATERIAL 2 Offset 672
OpMemberDecorate %type_PER_MATERIAL 3 Offset 768**

Because of the following PER_MATERIAL struct definition:

cbuffer PER_MATERIAL:register(b0, space1)
{
  float tilingAndAlpha:packoffset(c36);      // ======> 36 * sizeof(float4) offset which is 576
  float Amplitude:packoffset(c38);             // ======> 38 * sizeof(float4) offset which is 608
  float Emittance:packoffset(c42);              // ======> 38 * sizeof(float4) offset which is 672
  float SSSIndex:packoffset(c48);               // ======> 38 * sizeof(float4) offset which is 768
};

Thanks again for replying to our feature request. Please let me know if I can help with anything.

**Comment by antiagainst** [comment]
#1156 should address your needs. Please take a look. Thanks! :)

**Comment by Cry-Mory** [comment]
@antiagainst Thanks a lot. I will try it and let you know.

**Comment by antiagainst** [comment]
Hey @Cry-Mory, I'll close this now since #1156 is merged. But please don't hesitate to re-open if something is still missing/wrong. Thanks!

**Comment by Cry-Mory** [comment]
@antiagainst Sorry! I forgot to let you know. I tried it. So far it is working fine. Thanks again 👍
