### ISSUE TITLE
Support for DXR (DirectX raytracing) new HLSL stages & builtins?

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectXShaderCompiler#1153]
In MSDN blog post I see “set of new HLSL shader types including ray-generation, closest-hit, any-hit, and miss shaders.  These specify what the DXR workload actually does computationally.  When DispatchRays is called, the ray-generation shader runs.  Using the new TraceRay intrinsic function in HLSL” ..
So just asking..

**Comment by mlrdevgit** [comment]
It's coming! It's really a matter of timing and lining things up at this point. Stay tuned!

**Comment by elviras9t** [comment]
Also, suggest for compilation to SPIR-V 1.3 fallback shaders compiling.

**Comment by oscarbg** [comment]
Hi,
just read about Nsight graphics update at Siggraph with Vulkan raytracing support (altough no drivers yet).. so seems VK extension and drivers a coming soon.. possibly before end of the month..
so just asking if can provide some update (hopefully ETA) on open sourcing support..
so possibly somebody can add Vulkan SPIR-V output (using NV Vulkan RT extension) support of DXR shaders..
that would be nice, as seeing a lot more DXR tutorials by now maybe good having DXC produce Vulkan SPIR-V output from that tutorials HLSL shaders..
note I'm seeing there are two kinds of DXR SDK one targeted at RS5 and one for RS4..
maybe you are waiting for RS5 to arrive in October and open source the final/stable DXR bits then,  which can wait anyway..
thanks..

**Comment by oscarbg** [comment]
seems there is a pull request posted!
https://github.com/Microsoft/DirectXShaderCompiler/pull/1547

**Comment by hekota** [comment]
Yes, this pull request has all of our raytracing code corresponding to RS5. :)

**Comment by oscarbg** [comment]
thanks!
closing as it's now merged
