### ISSUE TITLE
Trouble Finding DIASDK during build

### ISSUE THREAD

**Issue by LunaLovecraft** [Microsoft/DirectXShaderCompiler#1176]
When attempting to build I get errors saying it could not find DIASDK.  I checked and both DIASDK's library and include folders are present in visual studio, and my visual studio 2017 desktop development features are installed.  Any idea what is happening?

[cmake-log.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/1845371/cmake-log.txt)

**Comment by marcelolr** [comment]
I don't think we've seen this in a while.

The logic to go find the DIA headers / libraries is at https://github.com/Microsoft/DirectXShaderCompiler/blob/master/cmake/modules/FindDiaSDK.cmake.

Did you install somewhere other than the C:\ drive, or perhaps have a named edition different than those provided? There's a TODO in the comments indicating that we've a bit more work to do to update this and have it execute properly, this might be what you're running into.

Please let me know about your VS installation and we'll look into getting you unblocked. Thanks!

**Comment by antiagainst** [comment]
@marcelolr: to piggyback a little bit, how would you think if we enable Release build in Appveyor so that developers can just download the binaries for the latest `master` branch from https://ci.appveyor.com/project/marcelolr/directxshadercompiler/branch/master/artifacts? (We only have Debug there right now, which runs much slowly.) It increases the build time for each PR/commit, but saves developers the time to build the compiler themselves.

**Comment by LunaLovecraft** [comment]
My DIA SDK location is:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\DIA SDK

Also to add on to that discussion, it would be helpful for me as a developer if I could just download the release binaries.  I'd also make it more clear for -spirv dev that you need to build the external spirv headers and spirv tools-- that took me a bit to notice (though it made sense after the fact).

**Comment by LunaLovecraft** [comment]
I'm not very clever.  I had a partially installed VS2017 build for some reason in my C drive and the actually installed version elsewhere.  It was able to find VS2017 on my external but couldn't find DIA SDK on the D drive.

Thanks for your assistance anyhow, I appreciate it very much!

**Comment by jeremyong-az** [comment]
I believe this issue should be reopened with VS2022 now having been released. VS is now installed in `Program Files`, not `Program Files (x86)` so the `FindDiaSDK.cmake` file is broken when using the VS 2022 generator.
