### ISSUE TITLE
Enable release builds in appveyor

### ISSUE THREAD

**Issue by dmpots** [Microsoft/DirectXShaderCompiler#1182]
Based on feedback in issue #1176 it sounds like it would be useful for users to have appveyor produce release builds as part of the build process.

I think we should enable release builds, but given that it will slow build times we should also invest in increasing our build capacity in appveyor: https://www.appveyor.com/pricing. They have a 50% discount for open source projects 🥇

**Comment by dmpots** [comment]
@marcelolr @antiagainst

**Comment by ehsannas** [comment]
Given the runtime benefits of release builds, adding appveyor release builds would be wonderful. It'd be much appreciated! 👍 🥇

**Comment by antiagainst** [comment]
+1 to enable release build. Another thing is that I think there still exist devs that cannot migrate to use VS2017 ATM due to various reasons. Having VS2017-generated-and-optimized binaries would also be nice for them, potentially with performance boosts.

**Comment by antiagainst** [comment]
Done via https://github.com/Microsoft/DirectXShaderCompiler/pull/1200.
