### ISSUE TITLE
SPIR-V: Missing DescriptorSet and Binding information on resources consumed by atomic operations

### ISSUE THREAD

**Issue by amddb** [Microsoft/DirectXShaderCompiler#1194]
Seems like the binding information is not propagated when accessing a resource aliased via a static variable which is only consumed by an atomic operation.

For example, the SPIR-V compiled from the following code misses DescriptorSet and Binding information:
```HLSL
[[vk::binding(0, 0)]]
RWTexture2D<uint> the_source_texture;

static RWTexture2D<uint> texture = the_source_texture;

[numthreads(1, 1, 1)]
void main()
{
    InterlockedAdd(texture[uint2(0, 0)], 1);
}
```

Changing the last line to 
```HLSL
texture[uint2(0, 0)] += 1;
```
properly adds:
```SPIR-V
OpDecorate %the_source_texture DescriptorSet 0
OpDecorate %the_source_texture Binding 0
```

The same holds true, when changing it to:
```HLSL
InterlockedAdd(the_source_texture[uint2(0, 0)], 1);
```

So it's the combination of using `static` and `InterlockedAdd` that breaks compilation.

**Comment by s-perron** [comment]
The changes needed to fix this are part of https://github.com/KhronosGroup/SPIRV-Tools/issues/1445.

**Comment by antiagainst** [comment]
Yep, this is a known issue that we are fixing right now. The fix will be in SPIRV-Tools and I'll keep this open util the fix is incorporated in DXC.

**Comment by s-perron** [comment]
The spirv-tools changes have been merged.

**Comment by antiagainst** [comment]
#1197 should fix this.

**Comment by amddb** [comment]
Fixed, thank you very much!
