### ISSUE TITLE
Interactive Samples

### ISSUE THREAD

**Issue by PeterSikachev** [Microsoft/DirectXShaderCompiler#121]
Are there any samples available that not only compile the shaders, using the experimental compiler, but also run them (e.g., a simple 'Hello Triangle ps_6_0' would suffice). It's a little bit hard to make it through the LLVM code and scarce docs.

**Comment by marcelolr** [comment]
There are a handful of resources available:

1. The tests available include some [execution tests](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/unittests/HLSL/ExecutionTest.cpp), which for the 'basic triangle' test should be a (relatively) straightforward usage.

2. We'll be adding support for the [MiniEngine](https://github.com/Microsoft/DirectX-Graphics-Samples) sample soon; some bits and pieces are there, but there are some additional instructions to actually put the pieces together; stay tuned. This gives you an app that lets you fly through a model with various effects.

3. If you build the compiler sources then go to the output bin directory and run 'dndxc', a little UI for playing with the compiler pops up. You can select File | New to get a quick sample, then View | Render, and if all goes well, you should see a triangle pop up (the default is for shader models 5_1 in the sample, but you can change the references to 6_0 to use the new compiler instead). If you can't get rendering to work, you might want to run dxexp to make sure you have a driver that will support shader model 6.

Now, I'd love to ask a few questions so we can make things better.

1. Are these kind of what you had in mind, or were you looking for something else?

2. Where did you look for samples/how did you look for samples? That'd be a great place for us to link to more information.

Thanks,
Marcelo

**Comment by PeterSikachev** [comment]
How do I launch execution tests? I tried setting clang-hlsl-tests (where the file belongs) as a start-up project, but it still launch compilation unit tests.

Yup, mini-engine integration would be nice indeed!

Dndxc fails to run a sample (crashes). When I run dxexp, it just exits straight away, no errors are shown. I got GTX970M with the latest drivers.

I was looking for smth like DX11 SDK/MiniEngine-style samples. I am not interested in compiling my own version of dxc, I'd rather have a standalone rendering sample with a precompiled shader compiler.

I was googling, and then read the docs - which are really scattered all other the place and cross-reference.

What would be nice:
1. Standalone rendering sample (e.g., simple samples with lane instructions etc)
2. Web-based docs (wiki format or just DX11-style documentation would be fine, too)

**Comment by marcelolr** [comment]
Revisiting ...

A simple sample with the wave instructions in now available at https://github.com/Microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12SM6WaveIntrinsics - hopefully this covers your case.

Wave intrinsics are covered in the Wiki now, and we're adding more features to this. We can do better at cross-referencing in general, but if there's something specific you'd like to see done sooner rather than later, please file an issue describing that and we'll bump the priority - thanks!
