### ISSUE TITLE
Casting vs. Calling Constructor

### ISSUE THREAD

**Issue by Cry-Mory** [Microsoft/DirectXShaderCompiler#1214]
I have a test HLSL shader which fails to be compiled with DXC because of casting from one struct to the other one. While this is valid in fxc. You can find the shader here: [test.hlsl.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/1902686/test.hlsl.txt)

It worths to point out that switching from casting to calling the constructor fixes the problem with dxc ([test_constructor.hlsl.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/1902699/test_constructor.hlsl.txt)) but fxc complains that constructors are only valid for basic types so I have to define a constructor for this type.

**Comment by tex3d** [comment]
Thanks for pointing this out, we're looking into it.  Be aware that this is not likely to be high on the priority list at the moment.

If struct casting is unavoidable and you need a solution that works with both fxc and dxc now, consider wrapping the cast in a macro that can be defined differently for fxc or dxc compiles.

`#define CAST_STRUCT(value, to_type) (to_type(value))  // or for fxc: ((to_type)(value))`

**Comment by vcsharma** [comment]
@MrTrillian while this is similar to #1560 and it does fail in SROA_Parameter_HLSL pass, but it fails during lower memcpy unlike #1560 which fails during RewriteBitCast operation. So I would suggest reactivating this bug and keep it as a separate bug for now.

>	dxcompiler.dll!llvm_assert(const char * _Message, const char * _File, unsigned int _Line, const char * _Function) Line 23	C++
 	dxcompiler.dll!llvm::Value::replaceAllUsesWith(llvm::Value * New) Line 355	C++
 	dxcompiler.dll!ReplaceUnboundedArrayUses(llvm::Value * V, llvm::Value * Src, llvm::IRBuilder<1,llvm::ConstantFolder,llvm::IRBuilderDefaultInserter<1> > & Builder) Line 3920	C++
 	dxcompiler.dll!ReplaceMemcpy(llvm::Value * V, llvm::Value * Src, llvm::MemCpyInst * MC) Line 3956	C++
 	dxcompiler.dll!`anonymous namespace'::SROA_Helper::LowerMemcpy(llvm::Value * V, hlsl::DxilFieldAnnotation * annotation, hlsl::DxilTypeSystem & typeSys, const llvm::DataLayout & DL, bool bAllowReplace) Line 4158	C++
 	dxcompiler.dll!`anonymous namespace'::SROA_Parameter_HLSL::flattenArgument(llvm::Function * F, llvm::Value * Arg, bool bForParam, hlsl::DxilParameterAnnotation & paramAnnotation, std::vector<llvm::Value *,std::allocator<llvm::Value *> > & FlatParamList, std::vector<hlsl::DxilParameterAnnotation,std::allocator<hlsl::DxilParameterAnnotation> > & FlatAnnotationList, llvm::IRBuilder<1,llvm::ConstantFolder,llvm::IRBuilderDefaultInserter<1> > & Builder, llvm::DbgDeclareInst * DDI) Line 5313	C++
 	dxcompiler.dll!`anonymous namespace'::SROA_Parameter_HLSL::createFlattenedFunction(llvm::Function * F) Line 5989	C++
 	dxcompiler.dll!`anonymous namespace'::SROA_Parameter_HLSL::runOnModule(llvm::Module & M) Line 4282	C++
 	dxcompiler.dll!`anonymous namespace'::MPPassManager::runOnModule(llvm::Module & M) Line 1624	C++
 	dxcompiler.dll!llvm::legacy::PassManagerImpl::run(llvm::Module & M) Line 1726	C++
 	dxcompiler.dll!llvm::legacy::PassManager::run(llvm::Module & M) Line 1766	C++
 	dxcompiler.dll!`anonymous namespace'::EmitAssemblyHelper::EmitAssembly(clang::BackendAction Action, llvm::raw_pwrite_stream * OS) Line 721	C++
 	dxcompiler.dll!clang::EmitBackendOutput(clang::DiagnosticsEngine & Diags, const clang::CodeGenOptions & CGOpts, const clang::TargetOptions & TOpts, const clang::LangOptions & LOpts, llvm::StringRef TDesc, llvm::Module * M, clang::BackendAction Action, llvm::raw_pwrite_stream * OS) Line 742	C++
 	dxcompiler.dll!clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext & C) Line 194	C++
 	dxcompiler.dll!clang::ParseAST(clang::Sema & S, bool PrintStats, bool SkipFunctionBodies) Line 162	C++
 	dxcompiler.dll!clang::ASTFrontendAction::ExecuteAction() Line 556	C++
 	dxcompiler.dll!clang::CodeGenAction::ExecuteAction() Line 755	C++
 	dxcompiler.dll!clang::FrontendAction::Execute() Line 468	C++
 	dxcompiler.dll!DxcCompiler::CompileWithDebug(IDxcBlob * pSource, const wchar_t * pSourceName, const wchar_t * pEntryPoint, const wchar_t * pTargetProfile, const wchar_t * * pArguments, unsigned int argCount, const DxcDefine * pDefines, unsigned int defineCount, IDxcIncludeHandler * pIncludeHandler, IDxcOperationResult * * ppResult, wchar_t * * ppDebugBlobName, IDxcBlob * * ppDebugBlob) Line 552	C++
 	dxcompiler.dll!DxcCompiler::Compile(IDxcBlob * pSource, const wchar_t * pSourceName, const wchar_t * pEntryPoint, const wchar_t * pTargetProfile, const wchar_t * * pArguments, unsigned int argCount, const DxcDefine * pDefines, unsigned int defineCount, IDxcIncludeHandler * pIncludeHandler, IDxcOperationResult * * ppResult) Line 300	C++
 	dxc.exe!DxcContext::Compile() Line 822	C++
 	dxc.exe!wmain(int argc, const wchar_t * * argv_) Line 1200	C++
 	[External Code]

**Comment by MrTrillian** [comment]
I just tested this on the latest master and it does not repro, the two provided shader compile correctly and yield the same code.

@vcsharma: FYI this was probably a dupe indeed

**Comment by vcsharma** [comment]
Cool! IIRC, this was not getting fixed by my fix for #1560. But if it no longer repros then that's great!
