### ISSUE TITLE
[SPIR-V, Vulkan-API] Counters in dedicated binding and offset

### ISSUE THREAD

**Issue by unit-404** [microsoft/DirectXShaderCompiler#1216]
I have buffer binding with few number (few counters in same binding). I suggest to make in addition for `vk::counter_binding(N)`, add possible solution with non-zero indexed counter value. 

1. `vk::counter_offset(B)` i.e. byte offset where will operating atomic. 
2. `vk::counter_array_element(I)` i.e. index from buffer array element.

**Comment by antiagainst** [comment]
Thanks for the suggestions, @elviras9t! To make sure I understand it correctly, behind these proposed attributes, you actually want a fine-grained way to pack the counters for several structured buffers into an array behind a single descriptor?

**Comment by antiagainst** [comment]
Okay. We'll see what we can do with this. Thanks!

**Comment by sudonatalie** [comment]
Requests for new language features (including Vulkan-specific attributes) now fall under the scope of the [microsoft/hlsl-specs](https://github.com/microsoft/hlsl-specs) repository. If you are still interested in this feature being considered, please submit a proposal there.
