### ISSUE TITLE
SPIR-V fatal error: pointer storage class in OpAccessChain mismatch

### ISSUE THREAD

**Issue by turanszkij** [Microsoft/DirectXShaderCompiler#1222]
Hi,
I am trying to build my HLSL shaders with the DXC SPIR-V compiler. Most of it works well, but I am having a problem with a shader trying to access a structured buffer and unpack a uint. I am providing a simple HLSL shader to reproduce the issue:

```
struct ShaderEntityType
{
	uint type;
	float3 positionVS;
	float range;
	float3 directionVS;
	float3 positionWS;
	float energy;
	uint color;
	float3 directionWS;
	float coneAngleCos;
	float shadowKernel;
	float shadowBias;
	int additionalData_index;
	float4 texMulAdd;

	// Load uncompressed color:
	inline float4 GetColor()
	{
		float4 fColor;

		fColor.x = (float)((color >> 0) & 0x000000FF) / 255.0f;
		fColor.y = (float)((color >> 8) & 0x000000FF) / 255.0f;
		fColor.z = (float)((color >> 16) & 0x000000FF) / 255.0f;
		fColor.w = (float)((color >> 24) & 0x000000FF) / 255.0f;

		return fColor;
	}
}; 

StructuredBuffer<ShaderEntityType> EntityArray;

// comment this to build successfully:
#define REPRODUCE_COMPILE_ERROR

float4 main() : SV_Target
{

#ifdef REPRODUCE_COMPILE_ERROR

	return EntityArray[0].GetColor();

#else

	uint color = EntityArray[0].color;

	float4 fColor;

	fColor.x = (float)((color >> 0) & 0x000000FF) / 255.0f;
	fColor.y = (float)((color >> 8) & 0x000000FF) / 255.0f;
	fColor.z = (float)((color >> 16) & 0x000000FF) / 255.0f;
	fColor.w = (float)((color >> 24) & 0x000000FF) / 255.0f;

	return fColor;

#endif

}

```

When I leave the definition REPRODUCE_COMPILE_ERROR, then the compilation fails with the following error:

> fatal error: generated SPIR-V is invalid: The result pointer storage class and base pointer storage class in OpAccessChain do not match.
note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible

When that is not defined, the compilation succeeds without errors when it should be doing the same thing. 
Note that I am not on the very latest iteration of the compiler, but a fairly recent one. Apologies if it was fixed in the meantime, but I didn't build the compiler for myself at this time (I can only build on an other machine).

Can you take a look at this? Not urgent because I can do a workaround for now.

Kind Regards,
Janos

**Comment by ehsannas** [comment]
Thanks for reporting! I am looking into this.

**Comment by ehsannas** [comment]
The type mismatch seems to be due to layout decorations (offset).
