### ISSUE TITLE
HLSL's atan2(0.0f, 0.0f)

### ISSUE THREAD

**Issue by matt77hias** [Microsoft/DirectXShaderCompiler#1245]
The mathematical [`atan2`](https://en.wikipedia.org/wiki/Atan2) function is undefined if both arguments are equal to zero. HLSL's [`atan2`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb509575(v=vs.85).aspx) is well-defined for every point other than the origin (i.e. both arguments are equal to zero). Though, I wonder if their is a guarentee that `0.0f == atan2(0.0f, 0.0f)`? (For C++'s [`atan2`](http://en.cppreference.com/w/cpp/numeric/math/atan2), this seems to be the case when IEEE floating-point arithmetic is supported. Although, it is never formally documented.)

Concretely, all spherical ($\phi$, $\cos\theta$) coordinate encoding/decoding snippets for unit vectors I found, look something like:

    float2 Encode_Spherical(float3 n) { // (0.0f, 0.0f, 1.0f)
        const float phi       = atan2(n.y, n.x); // 0.0f hopefully
        const float cos_theta = n.z; // 1.0f
        return SNORMtoUNORM(float2(phi * g_inv_pi, cos_theta)); // SNORMtoUNORM (0.0f, 1.0f)
    }
    
    
    float3 Decode_Spherical(float2 n_unorm) {
        const float2 n_snorm = UNORMtoSNORM(n_unorm); // (0.0f, 1.0f)
    
        const float phi = n_snorm.x * g_pi; // 0.0f
        float sin_phi; // 0.0f
        float cos_phi; // 1.0f
        sincos(phi, sin_phi, cos_phi);
    
        const float cos_theta = n_snorm.y; // 1.0f
        const float sin_theta = CosToSin(cos_theta); // 0.0f
    
        return float3(cos_phi * sin_theta, // 0.0f
                      sin_phi * sin_theta, // 0.0f
                      cos_theta); // 1.0f
    }

The code will be correct if `0.0f == atan2(0.0f, 0.0f)`. Otherwise, an extra check needs to be added.

**Comment by python3kgae** [comment]
Hi Matt, 
There's no guarantee that 0.0f == atan2(0.0f, 0.0f). 
Add the guarantee means extra check when expand atan2, which will generate more instructions all the time even your code does not require the guarantee.
If the code do need 0.0f == atan2(0.0f, 0.0f), you can add the check in hlsl.

Thanks
Xiang

**Comment by matt77hias** [comment]
Thanks for the clarification!
