### ISSUE TITLE
[SPIR-V] Shader does not pass spirv validation (OpPhi's result type does not match incoming value)

### ISSUE THREAD

**Issue by Gaspard--** [Microsoft/DirectXShaderCompiler#1248]
I encountered this problem while compiling many shaders, it seems this issue is quite rare.

### Minimal repro steps
```
Texture2D<float4> ro_texture2d;
uint i;

void MainFp (out float4 rw_sv_target : SV_TARGET) {
    int x = 0;
    int y = 0;
    if( i > 0 )
    {
      ro_texture2d.GetDimensions(x, y);
    }
    rw_sv_target = float4(x, 0, 0, 1);
}
```
Compile the above with:
`dxc.exe -spirv -T ps_6_0 -E MainFp <filename>`

### Expected result
Succesful compilation.

### Actual result
The shader fails to compile with the following output:
```
fatal error: generated SPIR-V is invalid: OpPhi's result type <id> 15 does not match incoming value <id> 31 type <id> 9.
note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

### Further technical details

If the condition `i > 0` isn't present, the bug disapears. It also dissapears if we replace `getDimension()` by something else.

**Comment by ehsannas** [comment]
I appreciate the clear statement of the issue. Thanks for reporting! :)
I will take a look.

**Comment by ehsannas** [comment]
The root cause of the issue is signed vs unsigned integer type mismatch.
The  ``GetDimensions`` method should not accept signed integers as argument according to the [spec](https://msdn.microsoft.com/en-us/library/windows/desktop/ff471559(v=vs.85).aspx).

It seems that the frontend doesn't disallow that in DXC.

**Comment by ehsannas** [comment]
I will fix the SPIR-V codegen

**Comment by Gaspard--** [comment]
Thanks for the prompt fix!
