### ISSUE TITLE
CComPtr versus std::shared_ptr: a fight to the death (when recount == 0)

### ISSUE THREAD

**Issue by pow2clk** [Microsoft/DirectXShaderCompiler#1275]
For selfish and petty reasons, I would like to convert all the refcounted smart pointers currently implemented as CComPtr to std::shared_ptr. I would like to know if there would be pushback, vetoes, or partially concealed resentment if I were to go to the effort. It would help greatly with cross compatibility.

Even MSDN throws shade on CComPtrs calling them "classic" and std::shared_ptrs "modern" https://msdn.microsoft.com/en-us/library/hh279674.aspx We want to be modern don't we? 😸

**Comment by mlrdevgit** [comment]
CComPtr is there in support for IUnknown, which is different in important ways - it's a stable ABI, it gives control of the lifetime to the concrete T implementation, and it provides QueryInterface which we use as an ABI-stable dynamic casting mechanism (which is a thing we actually leverage in a few places).

Functionally, any smart pointer will do - there's ComPtr in other libraries which is similar-but-different, and I've come across others at some point or another. It's the tie to the underlying base interface that's a thing worth preserving.

**Comment by pow2clk** [comment]
You make a good point, but sadly that means this fight to the death might not be as entertaining as I hoped. For that reason or in case someone else can come up with a reasonable counterargument, I'll leave this open a little longer, but I suspect that's that.

**Comment by mlrdevgit** [comment]
Hahaha... if you want a fight to the death, I'm sure there's plenty of out-of-memory hardening to do. It took forever to get the basic path resilient, and I'm sure I can find more cases if I step outside the basic case.

**Comment by pow2clk** [comment]
std::shared_ptr goes down in the first round. Poor thing never had a chance. The winner and reigning champion is CComPtr!  And the crowd goes wild!  :clap: :clap: :clap:
