### ISSUE TITLE
[spirv] [Question] How to remove unused resources from shader interface? (-fvk-ignore-unused-resources ?)

### ISSUE THREAD

**Issue by Gaspard--** [Microsoft/DirectXShaderCompiler#1282]
Hello,

I'm currently trying to compile a series of shaders whose content is controlled by preprocessing directives.

Under DirectX, we only bind the shader resources that are actually used by the shader, and we'd like to do the same for vulkan. For spir-v we query what resources are used using spirv-cross.

However It seems that unused but declared resources must be bound under vulkan (which we'd like to avoid).
We'd therefor like to remove their declaration. This doesn't seem to be possible without a sizeable compilation-time cost using spirv-cross (decompiling and recompiling the shader).

The removed compilation option `-fvk-ignore-unused-resources` seems to resemble what we need (although I haven't tested it yet).
Is there or would it be possible to have a way to do this in dxc?

Example (suppose this is obtained after preoprocessing):
```
[[vk::binding(5)]]
cbuffer UsedConstants 
{
    float val1;
};

cbuffer UnusedConstants 
{
    float val2;
};

void Main(out float rw_sv_target : SV_TARGET)
{
    rw_sv_target = val1;
#ifdef SOME_DEFINE
    rw_sv_target+= val2;
#endif
}
```

Is there a way to get rid of `UnusedConstants` ?

**Comment by antiagainst** [comment]
We removed `-fvk-ignore-unused-resources` because the dead code elimination (DCE) optimization is better than it right now. So you can rely on DCE to remove not referenced resources. I think you did not turn on optimizations when compiling the above source code? With the default setting (`-O3`), `UnusedConstants` will be removed. You can try the above source code with `dxc -spirv -T ps_6_0 -E Main`.

**Comment by Gaspard--** [comment]
Thanks. I will do some tests and report back.

**Comment by Gaspard--** [comment]
After looking into it some more, it seems something is wrong with our shader reflection.  
My apologies for wasting your time.
