### ISSUE TITLE
Support for sizeof and offsetof

### ISSUE THREAD

**Issue by wallisc** [microsoft/DirectXShaderCompiler#1291]
Supporting the use of sizeof and offsetof in HLSL would be a huge help in readable and maintainable shader code and remove the need for hard-coded sizeof/offsetof defines.

A painful pattern that I've had to adopt make sure struct updates don't introduce subtle sizeof bugs due to hard-coded struct sizes is to make sure shader headers are compiled both by HLSL and C, doing something like the below with static asserts to cause compile time breaks when a struct is updated

struct Triangle
{
    float3 v0;
    float3 v1;
    float3 v2;
};
#define SizeOfTriangle (9 * 4)
#ifndef HLSL
static_assert(sizeof(Triangle) == SizeOfTriangle, L"Incorrect sizeof for Triangle");
#endif

This pattern is common in compute projects where byteaddressbuffers are used to store multiple different types of objects. A concrete example is something like the D3D12RaytracingFallbackLayer where an acceleration structure is one large byteaddressbuffer that's made up of arrays varying types. There's a frequent conversion from bytes to structs and calculating strides based on structure sizes.

**Comment by tex3d** [comment]
Offsetof has been split off into its own issue #2181.

**Comment by MrTrillian** [comment]
Closing since we implemented sizeof and are tracking offsetof separately.
