### ISSUE TITLE
Appveyor zip distribution versioning

### ISSUE THREAD

**Issue by kennyalive** [Microsoft/DirectXShaderCompiler#1300]
Would it be possible to add version to filename? Something like dxc-artifacts-1.0.152.zip. Just playing with different versions of compiler trying to figure out which one introduces a bug and it would be really nice to have a version in such use case.

**Comment by antiagainst** [comment]
In the tarball, there is a `GIT-COMMIT.txt` file containing the commit from which the artifacts are built. This partially addresses the need. We are considering better approaches for discovering the corresponding commit of a rolling build, like letting `dxc.exe --help` to print the commit SHA1.

**Comment by kennyalive** [comment]
Thanks for the update. Any plans to provide version numbers that are not based on commit hashes, so they can be compared easily?

**Comment by antiagainst** [comment]
I've opened #1302, which contains a proposal to handle this issue. We can discuss there. Thanks!
