### ISSUE TITLE
Versioning rolling releases

### ISSUE THREAD

**Issue by antiagainst** [Microsoft/DirectXShaderCompiler#1302]
I'd suggest that we add a mechanism to version rolling releases.
### Purpose
The purpose is to track DXC libraries/binaries back to the corresponding commit from which they are built. This faciliates users who build DXC out of the `master` branch by themselves or download from Appveyor to compare different binaries and report bugs.
### Existing versioning scheme
Based on my understanding, we have two versioning schemes in place for blessed releases: https://github.com/Microsoft/DirectXShaderCompiler/wiki/Releases

* DLL file version: starting with `10.0.`. It is related to Windows OS version, and it can be queried via [GetFileVersionInfo()](https://msdn.microsoft.com/en-us/library/windows/desktop/ms647003(v=vs.85).aspx).
* IDXC version: this one seems to be coupled with DXIL version. It is exposed via `IDXCVersionInfo` interface:
https://github.com/Microsoft/DirectXShaderCompiler/blob/6a7f99cf5f31b3c13e8fa8e8d2bdaa037237be17/include/dxc/dxcapi.h#L292-L295
`GetVersion()` returns the major and minor version of DXIL.
### Proposed solution
DLL file version is well established. We should avoid messing it up. We also don't want to break back compatibility for `IDXCVersionInfo`. I think we can add another method in `IDXCVersionInfo` to return the number of commits in history and the current commit hash. Something like
```
  virtual HRESULT STDMETHODCALLTYPE GetCommitInfo(_Out_ UINT32 *numCommits, _Out_ const char** commitHash) = 0;
```

The commit hash gives users an easy way to map the pre-built library/binary to a point in Git history. The number of commits seems redundant; but it provides an easy way for users to *compare* two pre-built library/binary to know which one is newer, etc.

Number of commits and the current commit hash should be possible to get using CMake + Python + Git magic during build time.

**Comment by antiagainst** [comment]
I've uploaded #1304 as a tentative implementation of this.

**Comment by marcelolr** [comment]
This should help customers & is goodness. There are a couple of issues with the implementation, but I'm leaving comments over in the PR - thanks!

**Comment by antiagainst** [comment]
This is done via #1304.
