### ISSUE TITLE
Whither dxil.dll?

### ISSUE THREAD

**Issue by pow2clk** [Microsoft/DirectXShaderCompiler#1330]
I have been confused by the attempts in dxc.cpp and dxillib.cpp to load the library dxil.dll. It doesn't seem to be generated by any build variant I've made thus far. Is it a relic of a bygone era? Should these attempts be removed? Everything that might have been in that library seems to be in dxcompiler.dll if I'm reading things right.

Its absence doesn't seem to be hindering anything, but there are a couple matters in the Linux port that might be simplified if we can eliminate this. It might have some performance improvement all around to remove the unnecessary and always unsuccessful attempt to load a nonexistent library too.

**Comment by marcelolr** [comment]
dxil.dll isn't publicly built; it's part of the formal/supported DXIL validation story - see https://blogs.msdn.microsoft.com/marcelolr/2018/03/06/using-the-github-dxcompiler-dll/

**Comment by pow2clk** [comment]
Thanks Marcelo! That was very informative. Under the circumstances. I guess we have no reason to include dxillib in the Linux paths unless Microsoft plans to produce a libdxil.so library. I guess you never know! 😏
