### ISSUE TITLE
[SPIR-V] Feature request: automatically assigned binding locations with explicit descriptor set indices

### ISSUE THREAD

**Issue by nsubtil** [Microsoft/DirectXShaderCompiler#1340]
The `vk::location` and `vk::binding` attributes allow specifying either the binding location only (leaving the descriptor set index implicitly at 0) or both the binding location and set index together.

However, there seems to be no way to specify the descriptor set index explicitly while allowing the compiler to automatically assign binding locations within that descriptor set. This would be useful for shader pipelines that rely on reflection data to extract binding locations: the specific location values don't matter too much at that point, but descriptor set indices are still useful to assign explicitly (when grouping descriptors based on expected update frequency, for instance).

**Comment by chaoticbob** [comment]
Hey, Nuno. Thanks for the request. We need to review this to make sure it's a right step for DXC/SPIR-V. AFAIK, there hasn't been any ISV request this. There may be some impact on cross API usage patterns with respect to this feature.

**Comment by pow2clk** [comment]
For what it's worth, the implementation is pretty simple and has minimal impact on other features. I welcome feedback on it! #1343

**Comment by antiagainst** [comment]
We've uploaded #1503 to address this need.

**Comment by nsubtil** [comment]
#1503 does help address this need. There's a catch, however: it introduces compilation errors for DX12. Even if we can solve that, it's still undesirable to cause the DX12 resource layout to change when trying to adjust the resource bindings for VK.

I still think having a VK-specific attribute would make sense, especially taking into account the binding model differences between the two APIs: a space in DX12 is mostly a semantic construct, whereas in VK it has much stronger implications in terms of how the hardware will execute a shader. I'm not sure I understand why the register syntax was chosen to implement this.

**Comment by antiagainst** [comment]
#1503 is landed now. This need should be addressed. Yup, `:register(spaceX)` is not supported by DXIL at the moment. But Microsoft agrees that it's a feature that can be useful to DXIL, too; the auto-assign behavior can also happen to DXIL.  So instead of introducing VK specific way, we went to a unified way. I'll look into implement it for DXIL if I get time for it.
