### ISSUE TITLE
zero initialised structure gets warning from SPVRemapper

### ISSUE THREAD

**Issue by MichelVachon** [Microsoft/DirectXShaderCompiler#1356]
Hi, the following compilable pixel shader snippet :

```
struct SVertexToPixel
{
    float4 projectedPosition    : POSITION;
};

struct SOutputPixel
{
    float4 a : SV_Target0;
};

SOutputPixel main(in SVertexToPixel input, in float2 vpos : VPOS)
{
    SOutputPixel output = (SOutputPixel)0;

    return output;
}
```
when compiled into spirv, DXSC will generate OpConstantNull instructions that are not supported by SPVRemapper.
Is it possible to generate something else like OpConstant instead ?

thanks
Mike

**Comment by antiagainst** [comment]
I think OpConstantNull is supported now by spv-remap? https://github.com/KhronosGroup/glslang/pull/1409

**Comment by MichelVachon** [comment]
oh wow, since yesterday, will try right away, thanks!

**Comment by MichelVachon** [comment]
The new glslang fixes my issue, thanks!
