### ISSUE TITLE
[SPIRV] Can't seem to find unused output variables through reflection

### ISSUE THREAD

**Issue by Gaspard--** [Microsoft/DirectXShaderCompiler#1362]
I can't seem to find a way to identify usused output variables.
I have tried to verify this is caused by dxc but I'm having a very hard time knowing if this is either expected (or unfixable) behavior, spirv-cross not handling output vars properly or a potential missing feature.
Not sure if this is a bug or not. It would be a desired improvement at least.
I'm using spirv-cross in cli for the repro steps, but the behavior is present using the API too.

### Minimal repro steps
```hlsl
void MainVp(in float3 used_in_var : USED_IN_VAR,
	    in float3 unused_in_var : UNUSED_IN_VAR,
	    out float3 used_out_var : USED_OUT_VAR,
	    out float3 unused_out_var : UNUSED_OUT_VAR)
{
	used_out_var = used_in_var;
}
```
Compiled with `-spirv -E MainVp -T vs_6_3`, then decompiled using spirv-cross with the flag `--remove-unused-variables`.

### Expected result
Ouput and input both removed, something like this:
```glsl
#version 450

layout(location = 0) in vec3 in_var_USED_IN_VAR;
layout(location = 0) out vec3 out_var_USED_OUT_VAR;

void main()
{
    out_var_USED_OUT_VAR = in_var_USED_IN_VAR;
}
```
### Actual result
Unused input variables are not present, but output vars remain:
```glsl
#version 450

layout(location = 0) in vec3 in_var_USED_IN_VAR;
layout(location = 0) out vec3 out_var_USED_OUT_VAR;
layout(location = 1) out vec3 out_var_UNUSED_OUT_VAR;

vec3 _19;

void main()
{
    out_var_USED_OUT_VAR = in_var_USED_IN_VAR;
    out_var_UNUSED_OUT_VAR = _19;
}
```

### Further technical details
Looking, at the spirv disassembly, it seems all output are always targets of OpStore, which may explain why spirv-cross always considers these output variables as used:
```[...]
         %19 = OpUndef %v3float
     %MainVp = OpFunction %void None %9
         %20 = OpLabel
         %21 = OpLoad %v3float %in_var_USED_IN_VAR
               OpStore %out_var_USED_OUT_VAR %21
               OpStore %out_var_UNUSED_OUT_VAR %19
```

**Comment by antiagainst** [comment]
Thanks for the report, @Gaspard--! I'm not familiar with spirv-cross. Does eliminating the `OpStore %out_var_UNUSED_OUT_VAR %19` instruction solves your problem?

**Comment by Gaspard--** [comment]
I haven't found a way to verify if that's the case, but if there's any easy way to not emit them, I'm willing to try!
From what I've dug into the spirv-cross, when checking for used variables it seems they follow the execution graph and record all referenced ressources in the encountered instructions.
If writes to unused outputs aren't necessary, I think it would make sense not to have them, but I don't know enough about spirv to see the drawbacks.

**Comment by antiagainst** [comment]
You can just remove the line from the assembly, and then reassemble using spirv-as. It will then be gone in the binary. I'm just not sure how easily you can substitute a shader in your pipeline, though.

**Comment by Gaspard--** [comment]
I followed you're instructions and removed the store to `out_var_UNUSED_OUT_VAR`.
Reflection seems right:
```glsl
#version 450

layout(location = 0) in vec3 in_var_USED_IN_VAR;
layout(location = 0) out vec3 out_var_USED_OUT_VAR;

vec3 _19;

void main()
{
    out_var_USED_OUT_VAR = in_var_USED_IN_VAR;
}
```
 `spirv-val` doesn't complain either.

**Comment by Gaspard--** [comment]
I haven't tested what happens if it's used in a `VkPipeline`, that's quite a bit harder.

**Comment by antiagainst** [comment]
Okay, we are writing to an `OpUndef` into `%out_var_UNUSED_OUT_VAR` anyway. I think it makes sense to avoid the `OpStore` when the source is `OpUndef`. I'll create an issue for SPIRV-Tools to have this transformation.

**Comment by antiagainst** [comment]
https://github.com/KhronosGroup/SPIRV-Tools/issues/1631 for it.

**Comment by s-perron** [comment]
@antiagainst Why do you generate the store of an OpUndef in the first place?

**Comment by antiagainst** [comment]
We generate a entry point wrapper to satisfy Vulkan's need of `void(void)` entry functions. The wrapper writes out all stage output variables after calling the real entry function:

```llvm
       %main = OpFunction %void None %3
          %5 = OpLabel
%param_var_used_in_var = OpVariable %_ptr_Function_v3float Function
%param_var_unused_in_var = OpVariable %_ptr_Function_v3float Function
%param_var_used_out_var = OpVariable %_ptr_Function_v3float Function
%param_var_unused_out_var = OpVariable %_ptr_Function_v3float Function
         %12 = OpLoad %v3float %in_var_USED_IN_VAR
               OpStore %param_var_used_in_var %12
         %15 = OpLoad %v3float %in_var_UNUSED_IN_VAR
               OpStore %param_var_unused_in_var %15
         %18 = OpFunctionCall %void %src_main %param_var_used_in_var %param_var_unused_in_var %param_var_used_out_var %param_var_unused_out_var
         %19 = OpLoad %v3float %param_var_used_out_var
               OpStore %out_var_USED_OUT_VAR %19
         %22 = OpLoad %v3float %param_var_unused_out_var
               OpStore %out_var_UNUSED_OUT_VAR %22
               OpReturn
               OpFunctionEnd

   %src_main = OpFunction %void None %24
%used_in_var = OpFunctionParameter %_ptr_Function_v3float
%unused_in_var = OpFunctionParameter %_ptr_Function_v3float
%used_out_var = OpFunctionParameter %_ptr_Function_v3float
%unused_out_var = OpFunctionParameter %_ptr_Function_v3float
   %bb_entry = OpLabel
         %30 = OpLoad %v3float %used_in_var
               OpStore %used_out_var %30
               OpReturn
               OpFunctionEnd
```

**Comment by antiagainst** [comment]
OpUndef is generated in spirv-opt during translating the above code.

**Comment by antiagainst** [comment]
Actually it suddenly occurs to me this morning that I can rely on the `isUsed` info from the AST to avoid writing back the output variable in the wrapper function. That is, kill
```llvm
         %22 = OpLoad %v3float %param_var_unused_out_var
               OpStore %out_var_UNUSED_OUT_VAR %22
```
entirely.

I've uploaded #1373 to implement this idea. With it, the case raised here should be solved.

With that said, for me, KhronosGroup/SPIRV-Tools#1631 is still a legit optimization.

**Comment by antiagainst** [comment]
#1373 is merged. @Gaspard-- please check and reopen if it does not open your issue.

**Comment by Gaspard--** [comment]
I tested with the build on appveyor: everything works (my workaround is never called, even for the more exotic case in the linked issue).
Thanks a lot!
