### ISSUE TITLE
[spirv] invalid SPIR-V generation returning struct with array from function

### ISSUE THREAD

**Issue by simontaylor81** [Microsoft/DirectXShaderCompiler#1387]
Found an instance of "generated SPIR-V is invalid" which seems to be related to returning a struct containing an array from a function. I was able to reduce the repro case to the following (compile with `-T vs_6_0 -E main -spirv`):

```
struct S
{
    float4 a[1];
};

S fn()
{
    S s;
    s.a[0] = 0;
    return s;
}

float4 main() : SV_Position
{
    return fn().a[0];
}
```

Full error text:
```
fatal error: generated SPIR-V is invalid: The Base <id> '18' in OpAccessChain instruction must be a pointer.
  %18 = OpConstantComposite %S %17
```

If you manually inline `fn` into `main`, the problem goes away, strangely (in the real case there are many levels of nesting, so this is not a workaround, unfortunately).

Also, if you change `float4 a[1];` to `float a[1];`, the compiler crashes. Not sure if this is related or not.

(Both float4 and float versions compile cleanly in DXIL mode).

**Comment by antiagainst** [comment]
This issue should be fixed now. Please double check.

**Comment by simontaylor81** [comment]
Works a charm, thanks for the super-fast response!
