### ISSUE TITLE
[spirv] Specifying push constant offsets?

### ISSUE THREAD

**Issue by nsubtil** [Microsoft/DirectXShaderCompiler#1393]
If two stages in the same PSO use push constant offsets, their bindings need to be explicitly offset. However, I haven't been able to figure out how to do this in HLSL.

This would look something like the following in GLSL:

Vertex:
```
layout(push_constant) uniform vertexPushConstants {
    float test;
} pc;
```

Fragment:
```
layout(push_constant) uniform fragmentPushConstants {
    layout(offset = 4) float test2;
} pc;
```

Is there an equivalent to the `layout(offset = 4)` declaration in HLSL?

**Comment by pow2clk** [comment]
`[[vk::offset(4)]]` is officially undocumented, but it might work.

**Comment by antiagainst** [comment]
Thanks @pow2clk for pointing out! Yes, `[[vk::offset]]` is the way to manually control the layout of struct members. It was added initially for this use case: https://github.com/Microsoft/DirectXShaderCompiler/issues/903. The reason it is undocumented right now is that https://github.com/Microsoft/DirectXShaderCompiler/pull/922 is good enough to support flat structs, but the story with nested structs are not fully fleshed out yet. We expect to complete that soon and then properly document it.

**Comment by antiagainst** [comment]
#1399 completes the support for `vk::offset`. Closing this.
