### ISSUE TITLE
SPIRV: DXC does not emit any decorations when `precise` keyword is used

### ISSUE THREAD

**Issue by zeux** [Microsoft/DirectXShaderCompiler#1396]
Here's an example of a shader where output position is tagged as precise. In DXIL output (and FXC), the compiler emits the necessary attributes. However, SPIRV output doesn't have any decorations, which as far as I understand are required in this case to make sure the shader works correctly.

http://shader-playground.timjones.io/f48da6b5e25850867d87a035f08e63bc

**Comment by antiagainst** [comment]
Update on this: we have started the rearchitecting in a Google fork branch: https://github.com/google/DirectXShaderCompiler/tree/v2

**Comment by ehsannas** [comment]
Landed.
