### ISSUE TITLE
DXC: Specifying an include path for the preprocessor does not work

### ISSUE THREAD

**Issue by acoget** [Microsoft/DirectXShaderCompiler#1405]
I'm trying to invoke just the DXC preprocessor as part of a larger shader processing pipeline. The logic looks something like this:
- custom first pass, written into a temporary file in the working folder
- run the DXC preprocessor on that file, outputting another temporary file
- do some more processing on that second file

The problem is that I can't seem to run the preprocessor and specify the source data folder as an include path. Specifying both /P and /I ignores /I.
I compared the behavior with FXC from the Windows 8.1 SDK, and couldn't reproduce the issue there.
My workaround is going to be writing the temporary files in the source data folder, but that's obviously not ideal.
I've attached a repro case, with a readme detailing the different tests : [DXC_preprocessor_include_repro.zip](https://github.com/Microsoft/DirectXShaderCompiler/files/2167941/DXC_preprocessor_include_repro.zip)

**Comment by tex3d** [comment]
This was fixed by #1666, Thanks!
