### ISSUE TITLE
Failing to generate FMA

### ISSUE THREAD

**Issue by giordi91** [microsoft/DirectXShaderCompiler#1408]
Hi, lately I have been investigating a weird behavior on shader compilers not generating FMA. I have noticed the same behavior here, but I am not 100% sure if I need to force a specific flag or not.
Currently compiling with /O3. 
Am I doing anything wrong?

Here the code I am running :
![image](https://user-images.githubusercontent.com/2525797/42451267-982dd82a-837e-11e8-883f-6161fec57b34.png)

Shader code:
```
struct PixelInputType
{
    float4 position : SV_POSITION;
    float4 color : COLOR;
};

float2 main(PixelInputType input) : SV_TARGET
{
	float2 result;
	result.xy = (input.position.xy * 0.5f) + 0.5f;
    return result;
}

```

I was able to generate FMA with this exact code on Nvidia card IR and on AMD card both IR and actual machine code.  I also tried with float4 aswell, both partially initialized and fully initialized output value, did not get any FMA.

Environment:
Windows 10 (up to date)
Compiler version : 1.0.355
Nvidia GTX 1080

**Comment by giordi91** [comment]
Any news on this?

**Comment by python3kgae** [comment]
Sorry for later response.
For DXIL, fma only support double type, not float.
To generate fma on your example, we need to cast float into double first.
struct PixelInputType
{
    float4 position : SV_POSITION;
    float4 color : COLOR;
};

float2 main(PixelInputType input) : SV_TARGET
{
	float2 result;
	result.xy = fma((double2)input.position.xy , 0.5f,  0.5f);
    return result;
}

And we don't have optimization to transform  a*b+c -> fma/mad yet.
Is that what you need?

Thanks
Xiang

**Comment by python3kgae** [comment]
No particular limitation here.
It was planed for shader model 6.3, but delayed for other high priority features.
It will be in shader model 6.4.

Thanks
Xiang

**Comment by chrvoss** [comment]
Hey Xiang,

is there any update around this or an ETA when this optimization can be expected?

We're seeing a perf difference > 10% at runtime between DXBC and DXIL when compiling the same shader, with the lack of automatic mad detection being the most obvious difference in code gen. Losing 10% of performance isn't acceptable for our application, so this effectively prevents us from using DXIL altogether.

Thanks,
Christian

**Comment by llvm-beanz** [comment]
I don't think this is a bug for us to resolve. You will note in your example the floating point operations are marked `fast` this instructs the driver that it is safe to perform floating-point optimizations (like FMA-fusion).

We don't perform that optimization in the front end to keep DXIL more generic and widely portable. Vendor driver compilers can and do perform this optimization when appropriate.

As @python3kgae noted, the DXIL FMA only operates on double-precision floating point values and not vectors. As a result, this optimization would require changes to the DXIL specification, and a new shader model. This requires working with hardware vendors to design the feature, implement it, and ship updated drivers. Keeping the DXIL representation simpler and allowing vendors to optimize the code themselves simplifies the process.

If you're experiencing significant performance degradation I suspect there is likely more at play than FMA fusion failing at the DXIL level.

We do have a related proposal up on the HLSL specifications repo to add [math modes](https://github.com/microsoft/hlsl-specs/blob/main/proposals/0009-math-modes.md), to HLSL. Part of that proposal will encompass expanding math overrides to cover a more complete matrix of floating point and vector sizes, but we still likely won't expose FMA operations at the DXIL level.
