### ISSUE TITLE
Changes introduced in PR# 1298 fails to compile in x86 mode

### ISSUE THREAD

**Issue by vcsharma** [Microsoft/DirectXShaderCompiler#1434]
PR: https://github.com/Microsoft/DirectXShaderCompiler/pull/1298/files

The below code fails to compile in x86 mode:

raw_ostream &raw_ostream::
operator<<(std::ios_base &(*iomanip)(std::ios_base &)) {
#ifdef _WIN64
// FIXME: This fails to compile in x86.
// This was introduced in: https://github.com/Microsoft/DirectXShaderCompiler/pull/1298/files
  if (iomanip == std::hex)
    writeBase = 16;
  else if (iomanip == std::oct)
    writeBase = 8;
  else
#endif
    writeBase = 10;

  return *this;
}

**Comment by ehsannas** [comment]
Thanks for reporting. I will investigate immediately.

**Comment by vcsharma** [comment]
@ehsannas this was fixed in our internal build.

**Comment by ehsannas** [comment]
Glad to hear that. Thanks.
