### ISSUE TITLE
Question: How are we suppose to read shader reflections when DXIL is used?

### ISSUE THREAD

**Issue by Cry-Mory** [Microsoft/DirectXShaderCompiler#1454]
I found this unclear in the documentation. My question is how should we get the shader reflections in the Cpp code?

Normally with DX11 and DX12, we use D3DReflect functions and get a reflection blob. Is that still working? or we need to get the reflections using DXC library? 

If yes, is there a sample for it?

**Comment by marcelolr** [comment]
You can create an object to support IDxcContainerReflection, then go look for the DXIL part and ask the shader reflection interface off of that. It's a bit more involved than before, but it allows us to expose more APIs, and over more parts of the blob.

There's a `CreateContainerReflectionFromBlob` helper function in the tests that should help out.

https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/unittests/HLSL/DxilContainerTest.cpp#L397
