### ISSUE TITLE
Expand DXIL/DXBC format documentation

### ISSUE THREAD

**Issue by morganbr** [Microsoft/DirectXShaderCompiler#1458]
I recently tried to build a tool that would emit a DXIL compute shader (to compile it from a different language). While the format [documentation](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/DXIL.rst) was a good start, there were quite a few important details missing, mostly about the DXBC format:
* The value of any of the FourCCs
* The hash algorithm for the digest
* What parts other than DXIL are required and what the format of those parts are
    * It turned out I needed the SFI0, ISG1, OSG1, and PSV0 parts. None of those are documented and PSV0 is particularly tricky to make work (I'm not even sure I got it right for some resources)
* What in the PSV0 part is required to make resource binding work
* Value values for versions
* When typeAnnotations are required

**Comment by hekota** [comment]
Sorry, we don't have any plans to do this. We are currently focusing on improving the compiler correctness and stability.
