### ISSUE TITLE
Failed test on Windows 10 after running hcttest on fresh enlistment with git clone and hctbuilld

### ISSUE THREAD

**Issue by test2020dev2020** [Microsoft/DirectXShaderCompiler#1464]
Tested on two systems with different OS, both failed with same error during hcttest.
Repro steps: (following the build document at: https://github.com/Microsoft/DirectXShaderCompiler)
1.  On a new system, installed Windows 10 Pro version 10.0.16299 or  10.0.17134 (RS4 Windows 10 version 1803: https://changewindows.org/milestone/redstone4)
2. Installed Git for Windows from https://git-scm.com/download/win (64bit Git-2.18.0-64-bit.exe)
3. Installed Visual Studio 2017 community edition from https://visualstudio.microsoft.com/downloads/
4. Installed Python 2.7.15 from https://www.python.org/downloads/release/python-2715/
5. On the system, did: git clone https://github.com/Microsoft/DirectXShaderCompiler.git
6. After clone, set up a build environment shortcut by double-clicking the utils\hct\hctshortcut.js file, which created a shortcut on my desktop with a default configuration.
7. click that shortcut on my desktop, it started a HLSL console
8. From the HLSL console, ran the script at utils\hct\hctgettaef.py as python hctgettaef.py, it works fine
9. From the HLSL console, ran: hctbuild, build successful
10. From the HLSL console, ran: hcttest, encountered following error:

![shadertestfailure](https://user-images.githubusercontent.com/20567581/43369058-03dff66e-931c-11e8-884d-a059e83c4fad.png)

11. Tried clicking "Retry" or "Ignore", there were no effects, the build continues, and here is the output:

![shadertestoutput](https://user-images.githubusercontent.com/20567581/43369111-13a02dde-931d-11e8-8977-948ad99e7083.png)

12. Here is the failed test error:

FileName: C:\Users\admin\AppData\Local\Temp\Tfm-13068-0\te.processhost.exe-20180729-084148.dmp
Error: TAEF: [HRESULT 0x800706BE] A failure occurred while running a test operation: 'CompilerTest::CompileWhenNoMemThenOOM'. (The process hosting the test code dropped the connection with the TAEF engine while invoking a test operation. It terminated with an exit code of 0x80000003.)

Command Line Usage Warnings:

    The /labMode switch is being ignored as this setting is no longer supported.
EndGroup: CompilerTest::CompileWhenNoMemThenOOM [Failed]
TestSkipped: TAEF: The cleanup method 'TestModuleCleanup' will not be run as TAEF has stopped communicating with the test host process due to a previous failure.

Non-passing Tests:

    CompilerTest::CompileWhenNoMemThenOOM [Failed]

Summary: Total=1203, Passed=1202, Failed=1, Blocked=0, Not Run=0, Skipped=0
You can debug the test with the following command line.
start devenv /debugexe TE.exe /inproc C:\github\hlsl.bin\Debug\test\clang-hlsl-tests.dll /p:"HlslDataDir=C:\github\DirectXShaderCompiler\tools\clang\test\HLSL" /select: "@Priority<1"

Use this te.exe for out-of-proc, or pick the correct one for the target arch, currently x64.
C:\Program Files (x86)\windows kits\10\Testing\Runtimes\TAEF\TE.exe
C:\github\DirectXShaderCompiler\external\taef\build\Binaries\amd64\TE.exe

Use /name:TestClass* or /name:TestClass::MethodName to filter and /breakOnError to catch the failure.
        1 file(s) copied.
Testing command line programs at C:\github\hlsl.bin\Debug\test ...
Smoke test for dxr command line program ...
warning: DXIL.dll not found.  Resulting DXIL will not be signed for use in release environments.

![shadertesterror](https://user-images.githubusercontent.com/20567581/43369128-5f5e50ca-931d-11e8-9c17-da51c0686f96.png)

13. Tried using above repro command to debug, changed little bit according to my system settings: 
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe" /debugexe "C:\github\DirectXShaderCompiler\external\taef\build\Binaries\amd64\TE.exe" /inproc "C:\github\hlsl.bin\Debug\test\clang-hlsl-tests.dll" /p:"HlslDataDir=C:\github\DirectXShaderCompiler\tools\clang\test\HLSL" /select: "@Priority<1"

![shadertestdebugcommand](https://user-images.githubusercontent.com/20567581/43369249-8bc7aa56-931f-11e8-9b84-54407dc66c93.png)

14.  Te.exe triggers a breakpoint, and it is because of ptr is null pointer (looks like allocation error, my dev system has 16GB memory, so it should not be an memory issue, but DXC issue).

void * ptr = DxcGetThreadMallocNoRef()->Alloc(size);

![shadertestdebug](https://user-images.githubusercontent.com/20567581/43369269-1114e764-9320-11e8-81e5-e3c727996764.png)

This is a blocking bug,

**Comment by hekota** [comment]
Hello,

Thank you for the detailed report. I was able to reproduce the problem and we'll definitelly need to fix this.

FYI the CompileWhenNoMemThenOOM test is testing the compiler behavior in low memory situation by creating an artificial out-of-memory state during compilation & making sure it fails nicely. In reality this rarely happens. The test is by no means affected by the amount of memory on your system. 

So you case safely ignore the failure for now. Or if the assert bothers you the test can be disabled by editing the last line of tools\clang\unittests\HLSL\DxcTestUtils.cpp to return true:

```bool VersionSupportInfo::SkipOutOfMemoryTest() { return true; }```

**Comment by antiagainst** [comment]
Related: this particular test is disabled on Appveyor CI by https://github.com/Microsoft/DirectXShaderCompiler/pull/1295. It would be nice to revert it after fixing the issue.
