### ISSUE TITLE
Comparison with an enum causes compiler to crash

### ISSUE THREAD

**Issue by TheRealMJP** [Microsoft/DirectXShaderCompiler#1476]
Hello,

I've been trying out enums using the latest version of dxc compiled from the master branch, and the compiler seems to be crashing for me when performing a comparison of a variable whose type is an enum. This simple pixel shader repros the crash:

```
enum MyEnum
{
    Alpha = 0,
    Bravo = 1,
};

float4 PSMain() : SV_Target0
{
    float4 output = 0.0f;

    MyEnum x = Alpha;

    if(x == Alpha)
        output = 1.0f;

    return output;
}
```

It looks like if I do `if(x == uint(Alpha))` it doesn't crash, so I can use that as workaround for now.

**Comment by hekota** [comment]
Fixed in PR #1508
