### ISSUE TITLE
[Spir-V] Generated spirv is invalid accroding to validation layers

### ISSUE THREAD

**Issue by Gaspard--** [Microsoft/DirectXShaderCompiler#1498]
Hello.
I recently updated the validation layers to version 1.1.82.0, and a validation error now appears when we try to load spirv generated by dxc:
```
[ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: Structure id 29 decorated as Block must follow standard uniform buffer layout rules: member 19 at offset 300 overlaps previous member ending at offset 303
  OpFunctionEnd
```
This error appears both in used and unused uniforms. I can't see the overlap in the few shaders I inspected.
I sadly don't really have the means to provide a proper repro.
For what it's worth, a structure like this seems to cause the error:

```hlsl
cbuffer CB
{
	float4		test0;
	float4		test4;
	float4		test8;
	float4		test12; 
	float4		test16; 
	float4		test20; 
	float4		test24; 
	float4		test28; 
	float4		test32; 
	float4		test36; 
	float4		test40; 
	float4		test44; 
	float4		test48; 
	float4		test52; 
	float4		test56; 
	float4		test60; 
	uint4		test64; 
	float4		test68; 
	float4		test72; 
	float3		test76; 
	float		test79; 
	float2		test80; 
	uint2		test82; 
	float		test84; 
	uint		test85; 
	float		test86; 
	float		test87; 
	float		test88; 
	uint		test89; 
	float		test90; 
	float		test91; <- Validation layers complain about this field (word offset 91 == byte offset 316)
	float		test92; 
	float		test93; 
	float		test94; 
	float		test95; 
}
```

The message should be something like:

*"SPIR-V module not valid: Structure id **X** decorated as Block must follow standard uniform buffer layout rules: member 20 at offset 316 overlaps previous member ending at offset 319 OpFunctionEnd"*

With '**X**' being the ID of the struct.
The relevent compiled spirv looks like this:
```
[...]
OpMemberDecorate %type_CB 19 Offset 304
OpMemberDecorate %type_CB 20 Offset 316
OpMemberDecorate %type_CB 21 Offset 320
[...]
```
I tried to find any realtion in the compiled spirv, but didn't find anything worth mentioning.

I hope this can be of use.

**Comment by antiagainst** [comment]
Hi @Gaspard--, quick question first. Are you using `-fvk-use-dx-layout`?

**Comment by antiagainst** [comment]
Probably related to this: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/275

**Comment by Gaspard--** [comment]
Sorry for the late reply.
We don't use `-fxc-use-dk-layout`. The flags we use are `-spirv`, `-fvk-stage-io-order=alpha`,  and `-fvk-invert-y` (on vertex shaders only).

**Comment by antiagainst** [comment]
As discussed in KhronosGroup/Vulkan-ValidationLayers#275, I think this is an issue rooted in SPIRV-Tools validator. The layout check was broken but later got fixed: https://github.com/KhronosGroup/SPIRV-Tools/issues/1666. It seems the SDK did not pull in the fix when cutting the release. Hopefully it will be fixed by the next release of SDK.

**Comment by karl-lunarg** [comment]
There is a new SDK (1.1.82.1) released today with a fix for this problem.

**Comment by antiagainst** [comment]
Thanks @karl-lunarg!
