### ISSUE TITLE
Support for signing DXIL post-compilation

### ISSUE THREAD

**Issue by gwihlidal** [microsoft/DirectXShaderCompiler#1500]
Is there an update on dxil validation in dxc, and allowing for validation/signing post-compile?

Right now you only get signed dxil if you happen to have dxil.dll in your compiler path, otherwise you just get unsigned dxil code.
https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/tools/dxcompiler/dxcutil.cpp#L143
https://blogs.msdn.microsoft.com/marcelolr/2018/03/06/using-the-github-dxcompiler-dll/

Post-compile would be nice to keep shader compile toolchains flexible on Windows, but also allow us to leverage dxc running on linux machines (i.e. cloud/cluster), and the results could signed on demand (or by some other Windows environment) prior to usage on a machine without experimental features enabled. This is a pretty huge request from us (we are doing tons of linux-based cloud scaling of our pipelines, etc.. which includes shader compilation).

A linux binary that supports signing/validation would be superior, but I understand if that needs to remain as-is. However, since the compiler itself is open source, and the dxil.dll binary is loaded during compilation, it seems reasonable allow this decoupling. This way unsigned dxil could be produced on linux or windows, and then some windows-based approach can ensure dxil is properly signed when appropriate.

**Comment by gwihlidal** [comment]
Please see: https://www.wihlidal.com/blog/pipeline/2018-09-16-dxil-signing-post-compile/

**Comment by gwihlidal** [comment]
Follow up: https://www.wihlidal.com/blog/pipeline/2018-12-28-containerized_shader_compilers/

**Comment by seanbaxter** [comment]
I'm generating DXIL modules from Linux, and the process as-is is very awkward. A linux .a file with the validator would help a lot.

**Comment by chloekek** [comment]
For anyone coming across this issue who was surprised to find libdxil.so was not generated when building from source, if you wish to build from source and not use the proprietary library, I found that [hassle-rs] can “sign” (lol) the shaders as well (they took the implementation from [RenderDoc]).

[hassle-rs]: https://docs.rs/hassle-rs/0.11.0/hassle_rs/fake_sign/fn.fake_sign_dxil_in_place.html
[RenderDoc]: https://github.com/baldurk/renderdoc/blob/4a620bb5a16b4de4e2e184b1264ce3fc4198357e/renderdoc/driver/shaders/dxbc/dxbc_container.cpp#L840
