### ISSUE TITLE
Textures inside structs

### ISSUE THREAD

**Issue by kaplanyan** [Microsoft/DirectXShaderCompiler#151]
The new compiler doesn't support textures declared in structs (the stock DX one used to):

// Search defined structure for resource objects and fail
  if (IsResourceInType(CGM.getContext(), constDecl->getType())) {
    DiagnosticsEngine &Diags = CGM.getDiags();
    unsigned DiagID = Diags.getCustomDiagID(
        DiagnosticsEngine::Error,
        "object types not supported in global aggregate instances, cbuffers, or tbuffers.");
    Diags.Report(constDecl->getLocation(), DiagID);
    return;
  }

I wonder if you can roll out a change for this either into the dxil or into a separate branch?

**Comment by python3kgae** [comment]
Thanks for the feedback.
Working on remove this error message and support resources inside cbuffers.
It will be a big change to cover all possible cases though, need more time to get it done.

**Comment by kaplanyan** [comment]
Sounds great, thank you!

**Comment by python3kgae** [comment]
Done by https://github.com/Microsoft/DirectXShaderCompiler/pull/175
Most cases should be covered.
Let me know if it still not work for your shader.

Thanks
Xiang

**Comment by marcelolr** [comment]
@kaplanyan I'll be closing this for now, please open a new issue if you find another case that's failing for you. Thanks!
