### ISSUE TITLE
Warnings for float -> (u)int conversions

### ISSUE THREAD

**Issue by matt77hias** [microsoft/DirectXShaderCompiler#1514]
How do you configure the DirectXShaderCompiler to output warnings for float -> (u)int conversions? Apparently, the compiler does not complain at all when using the default project options. Furthermore, while looking at the project options in Visual Studio, I do not see any warning level related options (as is the case for C++ code).

**Comment by gracejennings** [comment]
Hi @matt77hias, thanks for reaching out! 

The `-Wconversion` flag enables warnings for conversions and will turn on the float -> int conversion like with C++. Please respond if this doesn't answer your questions or if this doesn't work for you
