### ISSUE TITLE
[SPIRV] gl_FragCoord's w component is not behaving the same as SV_Position semantic  

### ISSUE THREAD

**Issue by Cry-Mory** [Microsoft/DirectXShaderCompiler#1520]
We have some cases where DXC's generated fragment shaders using w-component of the input variable marked with SV_Position semantics does not work the same way as they work on dx11/12. Therefore, I tried to investigate what is the difference between FragCoord decorated input variables and  DirectX's input marked with SV_Position. According to [SPIRV documentation](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.pdf):

> **FragCoord** 
> Coordinates (x, y, z, 1/w) of the current fragment, input to the Fragment Execution Model. See Vulkan or OpenGL API specifications for more detail.

and also according to [GLSL documentation](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_FragCoord.xhtml):

> **gl_FragCoord**
> Available only in the fragment language, gl_FragCoord is an input variable that contains the window relative coordinate (x, y, z, 1/w) values for the fragment. 

Unfortunately, we could not find any specification for SV_Position on DirectX but my experiments indicate that w-component in DirectX is not inverted.

I took a quick a look inside [HLSLCrossCompiler repository](https://github.com/James-Jones/HLSLCrossCompiler/) and it is also inverting the w component of gl_FragCoord to get the same behavior as DirectX.

Update: The problem exists on AMD, NVIDIA, and Mali on android. I checked glslangValidator, it behaves the same as DXC.

**Comment by antiagainst** [comment]
I think `-fvk-use-dx-position-w` can solve your problem: http://khr.io/hlsl2spirv#vulkan-specific-options

**Comment by Cry-Mory** [comment]
Great, Thanks. I tried it. It works 👍 

Good Job, guys
