### ISSUE TITLE
dxcapi.use.h should not require llvm headers/libs to use - linux port regression

### ISSUE THREAD

**Issue by tex3d** [Microsoft/DirectXShaderCompiler#1525]
The `DxcDllSupport` class defined in `dxcapi.use.h` used to be something usable from outside the llvm project to help with dynamic loading and instance creation.  With change https://github.com/Microsoft/DirectXShaderCompiler/pull/1380 to make it cross-platform, the file now requires a bunch of llvm headers, and at least one llvm lib.  This isn't acceptable for users outside the project, who just want to use the dynamic library.

We need a different multi-platform solution that only depends on standard headers/libs on each platform, and doesn't depend on llvm headers and libs.  Perhaps a multi-platform dynamic library class that is fully inlined in a header without additional llvm dependencies?  Or just do the #ifdef work in this header?  It may be ugly, but it's not as ugly as including llvm headers/libs in a non-llvm project.

Additionally, since the llvm::DynamicLibrary class uses char strings and the DxcDllSupport uses wide strings, there's a CW2A use in the header that doesn't track to any header included directly, which causes a build break unless the required header is already included before this one (and this adds another needless dependency).  For the Windows implementation, this is an extraneous string conversion, since it's going to be wide under the hood again anyways.  I also don't know if this code path guarantees support for Unicode paths properly on Windows (would need investigation, but moot if changed to eliminate conversion).

Also note that the implementation of DxcDllSupport is fully inlined in this header, and as such, does not require function implementations in dxcapi.use.cpp unless you use those additional functions towards the end of the header.

This issue is impacting a number of projects already, with the work around being to use the old version of the header.

@pow2clk / @ehsannas / @antiagainst what do you think?

**Comment by ehsannas** [comment]
Thanks for reporting @tex3d. I'll take a look.

**Comment by ehsannas** [comment]
I understand the need for removing the dependency, and we certainly don't want a workaround of using the old version of the header! I will put up a PR for you and @antiagainst to review.
