### ISSUE TITLE
[spirv] fatal error: generated SPIR-V is invalid: The following forward referenced IDs have not been defined

### ISSUE THREAD

**Issue by xxxbxxx** [Microsoft/DirectXShaderCompiler#1528]
Hello,

Compiling with reflection infos:
[SortCS.hlsl.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/2362534/SortCS.hlsl.txt)

```dxc /Tcs_5_0 -EcsMain SortCS.hlsl -spirv  -fspv-reflect```
yields 
>fatal error: generated SPIR-V is invalid: The following forward referenced IDs have not been defined:
13

(whereas ```dxc /Tcs_5_0 -EcsMain SortCS.hlsl -spirv``` works)

**Comment by antiagainst** [comment]
This is an issue in SPIRV-Tools. I've created an issue there: https://github.com/KhronosGroup/SPIRV-Tools/issues/1885
