### ISSUE TITLE
dxc implements mul(float3x3, float3) as mul(transpose(float3x3), float3)

### ISSUE THREAD

**Issue by jholewinski** [Microsoft/DirectXShaderCompiler#153]
Take the following simple repro case as an example:

```c++
static const float3x3 g_mat1 = {
    1, 2, 3,
    4, 5, 6,
    7, 8, 9,
};

void ps_main(float3 tex : TEXCOORD0, out float4 color : SV_Target) {
    color = float4(mul(g_mat1, tex), 0);
}
```

`color.x` should be computed as `(1*tex.x + 2*tex.y + 3*tex.z)`. And this is exactly what `fxc` does:

```
dp3 o0.x, l(1.000000, 2.000000, 3.000000, 0.000000), v0.xyzx
```

Dxc, on the other hand, appears to transpose g_mat1 and then multiply:

```llvm
  %0 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 0, i32 undef)  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %1 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 1, i32 undef)  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %2 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 2, i32 undef)  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %3 = fmul fast float %1, 4.000000e+00
  %4 = fadd fast float %3, %0
  %5 = fmul fast float %2, 7.000000e+00
  %6 = fadd fast float %4, %5
```

This computes `(tex.y*4 + tex.x + tex.z*7)`.

**Comment by jholewinski** [comment]
Interestingly, this appears to only happen with constant matrices. If the matrix is loaded from a cbuffer, the correct computation is performed.

For example:

```c++
cbuffer Globals : register(b0) {
    float3x3 g_mat2;
};

void ps_main2(float3 tex : TEXCOORD0, out float4 color : SV_Target) {
    color = float4(mul(g_mat2, tex), 0);
}
```

I get `cb0[0]*tex.x + cb0[1]*tex.y + cb0[2].tex.z` when compiled with `-Zpr`, and `cb0[0]*tex.x + cb0[4]*tex.y + cb0[5]*tex.z` when compiled with `-Zpc`, as I would expect. That probably explains why I haven't seen any geometry corruption from this issue.

**Comment by python3kgae** [comment]
Fixed by https://github.com/Microsoft/DirectXShaderCompiler/commit/df5f52024b3ab8cf99a1acd5379ae11f6c17a466

Thanks
Xiang

**Comment by jholewinski** [comment]
Verified fixed. Thanks Xiang!
