### ISSUE TITLE
Rewriter changes [unroll] to [unroll(1)]

### ISSUE THREAD

**Issue by tex3d** [Microsoft/DirectXShaderCompiler#1533]
Unroll attribute isn't preserved by rewriter: [unroll] changes to [unroll(1)], which in HLSL means that the maximum loop count is assumed to be 1 when unrolling.

**Comment by MrTrillian** [comment]
Test case | fxc | dxc
----------|-----|----
[loop] to literal n | rolled loop | rolled loop
[loop] to cbuffer n | rolled loop | rolled loop with !"llvm.loop.unroll.disable"
[unroll] to literal n | n unrolled loop bodies, unconditional | n unrolled loop bodies, unconditional
[unroll] to cbuffer n | error X3511 | **rolled loop, !"llvm.loop.unroll.full"**
[unroll(1)] to literal n | 1 unrolled loop bodies, unconditional | **n unrolled loop bodies, unconditional**
[unroll(x)] to literal n, where x divides n | x unrolled loop bodies, unconditional | **x-unrolled loop, conditional**
[unroll(x)] to literal n, where x relative prime to n | x unrolled loop bodies, unconditional | **rolled loop**
[unroll(x)] to literal n, where x > n | n unrolled loop bodies, unconditional | n unrolled loop bodies, unconditional
[unroll(x)] to cbuffer n | x unrolled loop bodies, conditional through masking | rolled loop, !"llvm.loop.unroll.disable"
