### ISSUE TITLE
The [unroll(count)] attribute has a different meaning than in D3DCompiler (HLSL)

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#1534]
In HLSL, the unroll count is the upper limit of number of loops, not the number of unrolled iterations per loop in output IR, as it means in LLVM.  The HLSL definition means that using the [unroll(count)] can cut off loop iterations before the loop condition would have stopped iteration, and the loop is guaranteed to be completely unrolled.  We don't respect this definition in DxCompiler.

**Comment by MrTrillian** [comment]
Test case | fxc | dxc
----------|-----|----
[loop] to literal n | rolled loop | rolled loop
[loop] to cbuffer n | rolled loop | rolled loop with !"llvm.loop.unroll.disable"
[unroll] to literal n | n unrolled loop bodies, unconditional | n unrolled loop bodies, unconditional
[unroll] to cbuffer n | error X3511 | **rolled loop, !"llvm.loop.unroll.full"**
[unroll(1)] to literal n | 1 unrolled loop bodies, unconditional | **n unrolled loop bodies, unconditional**
[unroll(x)] to literal n, where x divides n | x unrolled loop bodies, unconditional | **x-unrolled loop, conditional**
[unroll(x)] to literal n, where x relative prime to n | x unrolled loop bodies, unconditional | **rolled loop**
[unroll(x)] to literal n, where x > n | n unrolled loop bodies, unconditional | n unrolled loop bodies, unconditional
[unroll(x)] to cbuffer n | x unrolled loop bodies, conditional through masking | rolled loop, !"llvm.loop.unroll.disable"

**Comment by MrTrillian** [comment]
@adam-yang  will be taking care of this one.

**Comment by pow2clk** [comment]
Fixed by #1783
