### ISSUE TITLE
out of memory during linking when pdb file generation for dxcompiler is enabled

### ISSUE THREAD

**Issue by Cry-Mory** [Microsoft/DirectXShaderCompiler#1548]
I get out of memory error during linking if I compile **dxcompiler** on x64-release with visual studio 2017 (15.6.2). Are you aware of it? Is there any way to fix it?

**Comment by hekota** [comment]
Sorry, I have not seen this. Are you compiling the whole project as is or are you making any changes?
It might be a VS compiler/linker bug. I would try updating VS to the latest version.

**Comment by Cry-Mory** [comment]
I am compiling the project as it is.

ok, I will try to update and see if that fixes the issue or not.

**Comment by marcelolr** [comment]
I think I've seen this in the past when using the 32-bit linker. The 64-bit linker should do better. MSDN has reasonable docs on how to pick the 64-bit tools from the command line, and there's an SO thread over at https://stackoverflow.com/questions/19820718/how-to-make-visual-studio-use-the-native-amd64-toolchain where there's a discussion on how to touch up the IDE projects.

**Comment by Cry-Mory** [comment]
@hekota @marcelolr  Thanks for your quick replies.

I actually checked the page @marcelolr suggested and setting the `PreferredToolArchitecture` to `x64` and then running visual studio fixes the problem.
