### ISSUE TITLE
[spirv] Request for support for DXR to VK_NV_raytracing!

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectXShaderCompiler#1554]
Hi,
now that DXR support has been merged (implies also open sourced!) & all VK_NV_raytracing bits are also published in various Khronos GitHub projects (SPIRV-Tools, SPIRV-Headers, glslang, Docs) etc..
seems nice if someone can implement SPIR-V output support of DXR HLSL shaders using SPV NV raytracing extensions..
@antiagainst @ehsannas no pressure but just wanted to know if you are interested on working on this?
thanks..

**Comment by DsoTsin** [comment]
Refer to [here](https://github.com/sparmarNV/DirectXShaderCompiler/tree/NV_ray_tracing)

**Comment by oscarbg** [comment]
Thanks @DsoTsin for pointing out..
Incredible work by @

**Comment by mmostajab** [comment]
Incredible work by @sparmarNV. I was testing the compiler with some simple shaders and the recent NVIDIA vulkan developer driver. It is working. Though the new target profiles are not in the options you see when I typed -h, and I needed to look them up in the code but it is working fine so far.

Looking forward to this solution being integrated into the main branch.

**Comment by sparmarNV** [comment]
Thank you for the feedback. We are actively working on getting the changes ready for a PR.
On a side note, I have updated the help text to emit the new profile options.

**Comment by ehsannas** [comment]
Thanks everyone for your patience. Support for this feature has landed today via #1920 .
