### ISSUE TITLE
Overriding intrinsic crashes DXIL generation

### ISSUE THREAD

**Issue by ehsannas** [Microsoft/DirectXShaderCompiler#1559]
In FXC, it is legal/valid for users to override intrinsic functions and use their own implementation. In such cases FXC gives precedence to the user-defined method.

I have attached a shader that overrides the 'mul' intrinsic method, and causes a crash in DXC.

[test.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/2405990/test.txt)

to reproduce: 
```
dxc.exe -T vs_6_0 test.txt
```

Also important to note that the AST generated for this shader by DXC is not correct (uses intrinsic mul, rather than the user-defined mul).

**Comment by hekota** [comment]
Currently we don't have any plans to support this.
