### ISSUE TITLE
Validation error with dynamic loops, array access and swizzling

### ISSUE THREAD

**Issue by simontaylor81** [Microsoft/DirectXShaderCompiler#158]
I'm hitting validation errors with a somewhat-obscure combination of dynamic looping, vector swizzles and dynamic array indexing. I managed to reduce the repro to the following:

```
float4 main() : SV_Target
{
    float array[2];
    float4 vec = 0;

    for (uint i = 0; i < 1; ++i)
    {
        array[i] = vec.xyzw[i];
    }

    return array[0];
}
```

Compile with `/T ps_6_0 /Gfp`. The `/Gfp` (prefer flow control) is essential -- it compiles fine without. Error is:

```
error: validation errors
Vector type '<4 x float>' is not allowed

Validation failed.
```

**Comment by python3kgae** [comment]
Fixed by https://github.com/Microsoft/DirectXShaderCompiler/pull/165

Thanks
Xiang

**Comment by simontaylor81** [comment]
Perfect! Thanks for the super-quick fix!
