### ISSUE TITLE
dxce.exe exited with code -1073741571

### ISSUE THREAD

**Issue by space928** [microsoft/DirectXShaderCompiler#1587]
It's hard to pinpoint this issue to anything in particular, but fiddling with the DirectX samples I noticed that if I did something too many times, then the shader would not compile giving me this error.
Let me elaborate:
I modified the [ProceduralGeometrySample](https://github.com/Microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12Raytracing/src/D3D12RaytracingProceduralGeometry) to add better shadows and (naive) Global Illumination I noticed though that if I had Global Illumination on both sdf based geometry and polygonal geometry it wouldn't compile, the same would happen if I used reflections on either types of geometry.
I'm sorry this explanation isn't the best please do follow up with me and I can explain in more detail.

I have attached the modified files of the sample linked to above.
[ModifiedFiles.zip](https://github.com/Microsoft/DirectXShaderCompiler/files/2454087/ModifiedFiles.zip)

**Comment by thekitchensink** [comment]
I'm getting the exact same error with this modified shader: 
[changed.zip](https://github.com/Microsoft/DirectXShaderCompiler/files/2454598/changed.zip)

**Comment by thekitchensink** [comment]
It's very consistently happening whenever I try to do any significant modifications to any of the dxr stuff. It seems to be related to overall code complexity in the shader.

**Comment by thekitchensink** [comment]
I've found that it's related to the overall complexity shared between all of the shaders - so, a potential temporary workaround might be to split the shaders into mutliple files.

**Comment by MrTrillian** [comment]
Hey guys, it seems like your attachment do not include all of the modified files? I am unable to build them.

@space928 I'm getting errors due to new fields in RayPayload and a missing Attributes type:
```
1>In file included from Raytracing.hlsl:17:
1>In file included from ./ProceduralPrimitivesLibrary.hlsli:23:
1>./RaytracingShaderHelper.hlsli(207,26): error GA6D86673: too many elements in vector initialization (expected 5 elements, have 7)
1>        RayPayload rayPayload = { float4(0, 0, 0, 0), currentRayRecursionDepth + 1, float2(0,0) };
1>                                ^
1>Raytracing.hlsl(294,64): error G58EA42A4: unknown type name 'Attributes'
1>void MyMissShader_ShadowRay(inout ShadowRayPayload rayPayload, Attributes attrib)
```

@thekitchensink I'm getting errors due to missing SceneConstantBuffer.halfplane1, halfplane2 and squishPlaneTform :
```
1>Raytracing.hlsl(170,55): error G1A4676F8: no member named 'halfplane1' in 'SceneConstantBuffer'
1>    float dot1 = dot(float4(ray.origin, 1), g_sceneCB.halfplane1);
1>                                            ~~~~~~~~~ ^
1>Raytracing.hlsl(171,55): error G1A4676F8: no member named 'halfplane2' in 'SceneConstantBuffer'
1>    float dot2 = dot(float4(ray.origin, 1), g_sceneCB.halfplane2);
1>                                            ~~~~~~~~~ ^
1>Raytracing.hlsl(176,49): error G1A4676F8: no member named 'squishPlaneTform' in 'SceneConstantBuffer'
1>        ray.direction = normalize(mul(g_sceneCB.squishPlaneTform, float4(ray.direction, 0))).xyz;
1>                                      ~~~~~~~~~ ^
```

**Comment by space928** [comment]
Ah yes, I forgot to include a file, I'm not very organised, sorry. I had a look through my files and I seem to have modified the files again so I can't guarantee that the project will work the same way it used to but here's a zip of the files you are missing:
[ExtraFilesD3DRaytracing.zip](https://github.com/Microsoft/DirectXShaderCompiler/files/2541180/ExtraFilesD3DRaytracing.zip)
I'm sure you'll need RaytracingHLSLCompat.h which is untouched since I reported this, but the functionality of the other files might have changed should you need them, specifically the project now loads obj files as models and displays them. Good luck anyway.

**Comment by MrTrillian** [comment]
Unfortunately I can't look into this due to having hardware that's incompatible with the sample.

**Comment by MrTrillian** [comment]
@space928 Actually, although I can't run the sample due to my GPU not being supported (and I'm still missing a `scene.obj`), I am able to compile the project fine with your changes and can see the produced `Raytracing.hlsl.h` generated by DXC. As it is, I don't have enough info to further investigate.

**Comment by MrTrillian** [comment]
I'm closing this as not repro until we get more info.

**Comment by SlartyB52** [comment]
Can we re-open this?
I have exactly the same problem. There is definitely a code-complexity issue.
I used the MS Procedural Geometry sample as a basis for my own ray-tracing program. Adding complexity to the AnyHit shaders caused this error. Simply #if 0-ing out parts of the code (doesn't really matter what) caused the compile to proceed to completion.
This effectively means that I can't write any more code.

**Comment by SlartyB52** [comment]
A clarification on my last post: It was the ClosestHIt shaders I was adding the bulk of the code to, not the AnyHit shaders. However - I don't think it matters. The issues seems to be related to the total lines of code in the file ( Raytracing.hlsi ).

**Comment by SlartyB52** [comment]
Just made some progress:
If you turn off disable optimisations ( /Od -Od ) in the MSVS project properties, the code compiles.
I'm going to open up a new issue with this work-around.

**Comment by MrTrillian** [comment]
Let's rather reopen this issue. The workaround issue is not actionable. I'll copy your text here for reference:

> Workaround:
> When using Microsoft Visual Studio to compile DXR programs, change the following setting:
> Project -> Properties -> HLSL Compiler -> Disable Optimisations
> If the option is set to "Yes (/Od)", then dxc.exe fails.
> If the option is set to "No", then the shaders are compiled successfully.

**Comment by MrTrillian** [comment]
@SlartyB52 In order for us to investigate this, we'll need to have better repro steps. You say that the compilation start failing after adding some amount of code. Can you provide the exact repo / commit you checked out and your code modifications? If you have a github fork with your changes and can create a branch pointing to exactly the project state in which you observe the crash when using /Od, that would be ideal. Thanks

**Comment by hekota** [comment]
@SlartyB52 - is this still an issue on the latest bits? If yes, can you please send us a repro we can investigate? Thanks!
