### ISSUE TITLE
[spirv]  Optimization bug

### ISSUE THREAD

**Issue by kennyalive** [Microsoft/DirectXShaderCompiler#1588]
When compiling this shader with -O3 the condition at the beginning of the `main` is eliminated, it works fine with -O0.

```
// -T cs_6_0 -spirv -O3
[[vk::binding(0, 0)]]
StructuredBuffer<uint> buffer;

[[vk::binding(1, 0)]]
RWStructuredBuffer<uint> buffer2;

groupshared int offset;

[numthreads(512, 1, 1)]
void main(uint3 group_thread_id : SV_GroupThreadID, uint3 group_id : SV_GroupID)
{
    if (group_thread_id.x == 0)
        offset = buffer[group_id.x];

    GroupMemoryBarrierWithGroupSync();

    uint current_offset;
    InterlockedAdd(offset, 1, current_offset);
    buffer2[current_offset] = current_offset;
}
```
It's probably spirv-tools bug as reported here https://github.com/KhronosGroup/SPIRV-Tools/issues/1956. DXC is affected by this issue since revision f1a032e946589350206ad36577bbe3b2f73d2977 (May 14, 2018).

**Comment by antiagainst** [comment]
Thanks for the bug report! We'll look into this.
