### ISSUE TITLE
Validation error: Pointer type bitcast must be have same size

### ISSUE THREAD

**Issue by simontaylor81** [Microsoft/DirectXShaderCompiler#159]
I'm hitting a validation error with one of our shaders. Seems to be related to `asfloat` and dynamic branching. I reduced the repro to the the following. Compile with `/T ps_6_0`

```
uint uintConstant;

float4 main() : SV_Target
{
    float a[2];

    a[0] = asfloat(uintConstant);
    a[1] = 0;

    float b[2];

    [loop]  // Essential to repro
    for (int i = 0; i < 2; ++i)
    {
        b[i] = a[i];
    }

    return b[0];
}
```

Note that I don't have a workaround for this currently, so suggestions would be welcome (obviously in this case I can remove the `[loop]` but the actual shader uses "prefer flow control" and removing that would be highly invasive).

**Comment by dmpots** [comment]
Thanks for the report! You can disable validation with the `/Vd` command line switch. We will look into the bug, but hopefully that will unblock you for now.

**Comment by python3kgae** [comment]
Fixed by disable optimization at https://github.com/Microsoft/DirectXShaderCompiler/pull/164

Thanks
Xiang

**Comment by simontaylor81** [comment]
Works perfectly. Thanks for the fast response!
