### ISSUE TITLE
Dxil documentation updates

### ISSUE THREAD

**Issue by dmpots** [Microsoft/DirectXShaderCompiler#160]
Three updates to the docs that would be useful:

1. The `FMad` intrinsics is not a "fused" instruction (i.e. there is a rounding step between the multiply and the add). Only the `Fma` instruction is a fused operation.
2. The `Log` intrinsic is log base 2 unlike the hlsl log function which is log base e.
3. The `Exp` intrinsic is base 2 (i.e. 2^x) unlike the hlsl log function which is base e.

**Comment by youngkim93** [comment]
These updates are addressed in #207 . Let me know if there still is an error or other suggestions for the documentation. Thanks!
