### ISSUE TITLE
CompilerTest::QuickTest on lib_hs_shaders_only.hlsl is randomly failing in AppVeyor runs

### ISSUE THREAD

**Issue by hekota** [Microsoft/DirectXShaderCompiler#1603]
Test disabled by #1604.

**Comment by tex3d** [comment]
The other QuickTest that randomly fails for what I suspect is the same reason is d3dreflect/lib_hs_export1.hlsl.

**Comment by tex3d** [comment]
Changing label to bug, since this issue indicates some flaky bug in the compiler, and not a build/setup issue.  Both of these tests should pass if the compiler behaves properly.  They were removed temporarily since the bug wasn't easy to isolate and appears to have limited impact for now.
