### ISSUE TITLE
Constant folding and division by zero and fxc

### ISSUE THREAD

**Issue by kingofthebongo2008** [Microsoft/DirectXShaderCompiler#1607]
Constant folding does not behave the same way as fxc

Hello, 

If you enable on a cpu fpu division by zero exception and compile a shader with 
pow(0) then you get it division by zero.

I do not get the same exception when compiling with fxc.

What are the rules in this case?

**Comment by tex3d** [comment]
Fxc sets, then restores the FPU mode flags for compilation.  We need to do the same with Dxc.
