### ISSUE TITLE
`Version Info` is missing

### ISSUE THREAD

**Issue by stef-levesque** [microsoft/DirectXShaderCompiler#1617]
see include/llvm/Option/OptTable.h#L167
/* HLSL Change - version info */ const char *VersionInfo

https://github.com/Microsoft/DirectXShaderCompiler/blob/285490211f2cbb44444a23d5f1c329881b96a43b/tools/clang/tools/driver/cc1as_main.cpp#L464

**Comment by pow2clk** [comment]
This was fixed a while ago. Thanks for the report!
