### ISSUE TITLE
Crash when returning 64-bit types

### ISSUE THREAD

**Issue by dmpots** [Microsoft/DirectXShaderCompiler#162]
Compile with `/Tps_6_0`
```
[RootSignature("")]
double main() : SV_Target {
    return 1;
}
```
Crash exists for `int64_t` as well. We should emit an error message about an illegal return type like fxc does.

**Comment by python3kgae** [comment]
Fixed by https://github.com/Microsoft/DirectXShaderCompiler/pull/176
