### ISSUE TITLE
pack_matrix pragma seems to be ignored

### ISSUE THREAD

**Issue by tfoleyNV** [Microsoft/DirectXShaderCompiler#1635]
Given this HLSL code:

```hlsl
#pragma pack_matrix(row_major)

cbuffer C
{
    int3x4 m;
}

RWStructuredBuffer<int> output;

[shader("compute")]
[numthreads(4,1,1)]
void main(uint3 tid : SV_DispatchThreadID)
{
    uint i = tid.x;
    
    output[i] = m[0][i];
}
```

The header comment generated by fxc shows that both `m` is given `row_major` layout:

```
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.0.10011.16384
//
//
// Buffer Definitions: 
//
// cbuffer C
// {
//
//   row_major int3x4 m;                // Offset:    0 Size:    48
//
// }
```

Feeding the same shader into dxc yields:

```
; Buffer Definitions:
;
; cbuffer C
; {
;
;   struct dx.alignment.legacy.C
;   {
;
;       column_major int3x4 m;                        ; Offset:    0
;   
;   } C                                               ; Offset:    0 Size:    60
;
; }
```

It does not appear that the `#pragma` is respected, although `row_major` modifiers on individual variable declarations are.

**Comment by TheRealMJP** [comment]
It looks like they just committed a [fix](https://github.com/Microsoft/DirectXShaderCompiler/commit/536240b3b8786851bf2d4d751f498fac50c5100d) for this 2 days ago.

**Comment by tfoleyNV** [comment]
Awesome. I saw some of that code when I was searching around, but I didn't realize it had been added recently.

**Comment by hekota** [comment]
Thanks @TheRealMJP !
