### ISSUE TITLE
Build error when using CMake from within VS2017 Community ver. 15.8.8

### ISSUE THREAD

**Issue by cgraphics** [Microsoft/DirectXShaderCompiler#1638]
When using the CMAKE tool from within VS2017 I receive this error:

"Error	MSB6006	"cmd.exe" exited with code 1. 	C:\hlsl.bin\tools\clang\lib\Basic\clangBasic.vcxproj	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	209	
Error	C2220	warning treated as error - no 'object' file generated 	C:\hlsl.bin\lib\HLSL\LLVMHLSL.vcxproj	c:\directxshadercompiler\lib\hlsl\hloperationlower.cpp"

I followed the build instructions from /wiki/Building-Sources:
https://github.com/Microsoft/DirectXShaderCompiler/wiki/Building-Sources

Perhaps I am missing something.
Any feedback or insight would be greatly appreciated.
Thanks.

**Comment by hekota** [comment]
Sorry, I could not repro this. What version of cmake do you have?
(run `cmake --version` in the cmd window set up with `utils\hct\hctstart.cmd`)

**Comment by cgraphics** [comment]
cmake version 3.11.18040201-MSVC_2

**Comment by cgraphics** [comment]
Does this code work with WARP? I have to use WARP because my current machine only has a hardware feature level of 10_0.

**Comment by cgraphics** [comment]
![build_failure](https://user-images.githubusercontent.com/44477762/47756913-925c4f00-dc69-11e8-853a-3dfdf8d006b1.png)

**Comment by cgraphics** [comment]
I synced to the latest sources and built again. Same problem.

**Comment by hekota** [comment]
Do you see the same warnings as before? Take a look at the current lib\HLSL\HLOperationLower.cpp source code, lines 4570 and 4603, there is no srcTy on these lines. Can you please check if you have the same? Sorry, the build break did exist, but it's not there anymore. Maybe try running hctclean before hctbuild to ensure a clean build.
https://github.com/Microsoft/DirectXShaderCompiler/blob/master/lib/HLSL/HLOperationLower.cpp#L4570
