### ISSUE TITLE
hctgettaef.py failure

### ISSUE THREAD

**Issue by cgraphics** [microsoft/DirectXShaderCompiler#1668]
When building with the HLSL console, I receive this error:

"ERRORUnable to find TAEF binaries under Windows 10 SDK."

When executing hctgettaef.py I receive this error:

"File "C:\DirectXShaderCompiler\utils\hct\hctgettaef.py", line 8, in <module>
    src_dir = os.environ['HLSL_SRC_DIR']
  File "C:\Python\Python37-32\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'HLSL_SRC_DIR'"

I am using Windows 10 Pro version 1803 build 17134.345 in developer mode.

**Comment by cgraphics** [comment]
CMakeError.log has this:

"cl : Command line error D8021: invalid numeric argument '/Wno-variadic-macros' [C:\hlsl.bin\CMakeFiles\CMakeTmp\cmTC_d69f6.vcxproj]"

**Comment by tex3d** [comment]
Unfortunately, the package we were referencing was removed due to some project quota or something.  So, until we can find a new minimal package to reference, you'll have to get TAEF by installing the [WDK](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk) for now.

**Comment by tex3d** [comment]
Also, it doesn't appear you are running from the HLSL Console prompt with the appropriate environment variables set.  Did you follow the instructions [here](https://github.com/Microsoft/DirectXShaderCompiler/wiki/Building-Sources)?

**Comment by cgraphics** [comment]
Thanks for the reply.
I installed the latest WDK. Looks like I was missing the spectre libraries. I will add those to Visual Studio and try again.

**Comment by cgraphics** [comment]
The build made significantly more progress. However, after about 30 minutes into the build, I get this:

"
Done Building Project "C:\hlsl.bin\tools\clang\tools\dotnetc\dndxc.csproj" (default targets).

Done Building Project "C:\hlsl.bin\ALL_BUILD.vcxproj" (default targets) -- FAILED.


Build FAILED.

"C:\hlsl.bin\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\hlsl.bin\tools\clang\unittests\HLSLHost\HLSLHost.vcxproj" (default target) (4) ->
"C:\hlsl.bin\tools\clang\unittests\HLSL\clang-hlsl-tests.vcxproj" (default target) (43) ->
"C:\hlsl.bin\tools\clang\tools\dxcompiler\dxcompiler.vcxproj" (default target) (60) ->
"C:\hlsl.bin\tools\clang\lib\Basic\clangBasic.vcxproj" (default target) (75) ->
(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(20
9,5): error MSB6006: "cmd.exe" exited with code 1. [C:\hlsl.bin\tools\clang\lib\Basic\clangBasic.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:31:39.10
Failed to build projects.
After fixing, run 'cmake --build --config Debug .' in x64
Failed to build binaries, stopping hctcheckin.
"

![build_failure](https://user-images.githubusercontent.com/44477762/48086574-718c8000-e1ba-11e8-8581-14a03a122ddf.jpg)

**Comment by BitMD** [comment]
I can't get a repro of this build failure so I am closing it.  Please reopen or file a new bug if needed.

**Comment by klateralus** [comment]
Hello guys!
I had the same problem that cgraphics described and to fix it I had to add environment variables "HLSL_SRC_DIR" by myself
