### ISSUE TITLE
Add feature requirement testing for system values to SystemValueTest

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#1670]
Some system values trigger optional feature bits when used in certain locations.  These don't have good testing.  We could make a table in the SystemValueTest of feature bits that should be seen when certain system values are used at certain SigPoints and check for the flag in the success branch.

**Comment by tex3d** [comment]
Note: this would help test the nuances of the code that this PR fixes: #1664

**Comment by llvm-beanz** [comment]
This task is almost 6 years old, we've gotten this far without doing this so we'll just implement better testing in Clang.
