### ISSUE TITLE
Rounding results differ for round(0.5) vs round(x) where x=0.5f

### ISSUE THREAD

**Issue by fdwr** [microsoft/DirectXShaderCompiler#1671]
It appears that FXC/DXC are applying a compile time optimization to numeric literals and using round-away-from-zero whereas the actual HLSL intrinsic at runtime on the GPU uses round-halves-to-nearest-even (round_ne asm). The two should be consistent, as a compile time optimization isn't intended to change the results.

    float2 main(float f : INPUT) : OUTPUT
    {
      // if input f == 0.5
      return float2(round(f), round(0.5));
      // returns float2(0.0, 1.0)
    }

`round(0.5)` -> 1
`round(1.5)` -> 2
`round(x)` -> 0 // where x = 0.5f
`round(x)` -> 2 // where x = 1.5f

(Technically the round-away-from-zero is what I actually wanted, but I'm fine with either and can work around it, so long as the two agree with each other.)

**Comment by tex3d** [comment]
Note this example, which might be a good test case:
```
float main(float f : INPUT) : OUTPUT {
  if (f == 0.5)
    return round(f);
  else
    return round(0.5f);
}
```
results in:
```
%cmp = fcmp fast oeq float %0, 5.000000e-01
%retval.0 = select i1 %cmp, float 0.000000e+00, float 1.000000e+00
```
When it should just return 0.0.  FXC also shows the same problem here.
