### ISSUE TITLE
generated SPIR-V is invalid: Expected both objects to be of Result Type: Select

### ISSUE THREAD

**Issue by Jumbo3000** [Microsoft/DirectXShaderCompiler#1674]
When compiling for Spirv:
With:

RW_TEXTURE2D_ARRAY<float4>  a;
    
void func(in uint3 p1, in float4 p2)
{
    a[p1.xyz] = p2;
}

Gives the error:
generated SPIR-V is invalid: Expected both objects to be of Result Type: Select
%435 = OpSelect %double %434 %double_1 %float_0

Compiles fine in glslc

**Comment by antiagainst** [comment]
Hey @Jumbo3000, thanks for the report! But I'm unable to reproduce the issue locally. Would you mind to provide a more complete shader? Thanks!

**Comment by ehsannas** [comment]
I think fixing this in the current CodeGen is difficult. The good news is that our new design handles this case correctly. I just tested that Pull #1851 compiles the given TypeSelect.hlsl shader successfully.

So, stay tuned for Spiregg 2.0 to land.

**Comment by ehsannas** [comment]
Spiregg 2.0 has landed, and the issue has been fixed.
