### ISSUE TITLE
Assert indexing vector in input struct

### ISSUE THREAD

**Issue by simontaylor81** [Microsoft/DirectXShaderCompiler#168]
I'm getting an assert "Calling a function with a bad signature!" that is very confusing, but seems to be related to indexing into a vector that's inside a struct that's passed as input to the shader. I managed to boil it down to the following repro (compile with `/T ps_6_0`):

```
struct Input
{
    float2 v : TEXCOORD0;
};

float4 main(Input input) : SV_Target
{
    return input.v[0];
}
```

**Comment by python3kgae** [comment]
Fixed by https://github.com/Microsoft/DirectXShaderCompiler/pull/170

Thanks
Xiang
