### ISSUE TITLE
Interfaces should not require IDxcBlob for input, use void* and size_t instead.

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#1683]
We have interfaces that require IDxcBlob inputs, but to get a IDxcBlob if you don't already have one requires you to either implement it yourself, or use IDxcLibrary.  IDxcLibrary is only implemented in DxCompiler.dll, meaning the easy path to a blob requires DxCompiler.dll.  If one wants to use the IDxcValidator interface on DXIL.dll, for instance, they shouldn't require DxCompiler.dll just to create a blob wrapper for their memory.

We should consider changing interfaces so they don't require IDxcBlob as input, particularly for IDxcValidator, not only because it has an implementation outside of DxCompiler, but also because it optionally modifies the contents with DxcValidatorFlags_InPlaceEdit (for signing).

**Comment by LautrecOfCarim** [comment]
:+1: to this as it appears as the top result for searching 'IDxcBlob'

**Comment by llvm-beanz** [comment]
We're redesigning the compiler library interface in Clang and we will address this there.
