### ISSUE TITLE
DXC rejects zero-sized resource arrays while FXC/docs allow it

### ISSUE THREAD

**Issue by MrTrillian** [microsoft/DirectXShaderCompiler#1685]
See docs: https://docs.microsoft.com/en-us/windows/desktop/direct3d12/resource-binding-in-hlsl (emphasis added)

> An array resource may have an unbounded size, which is declared by specifying the very first dimension to be empty **or 0**:
> `Texture2D<float4> tex1[]       : register(t0)`

Test case:
```
Texture2D<float> tex[0]; // Unbounded per docs
float4 main(int3 a : A) : SV_TARGET { return tex[3].Load(a); }
```

`fxc /T ps_5_1 /enable_unbounded_descriptor_tables` compiles fine.
`dxc /T ps_5_1` outputs: `error: array dimension must be between 1 and 65536`

**Comment by pow2clk** [comment]
This is intended behavior. Years later no one has complained. So we're letting it be.
