### ISSUE TITLE
Add built-in macros for dxc

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#1686]
We should add some built-in macros for dxc for things like shader model major and minor, compilation target profile, maybe even optimization level, and others.  The shader model macros could be used to detect whether you're being compiled with dxc, as well.

**Comment by galop1n** [comment]
I was looking for something similar to to workaround a mistake the legacy fxc did not catch :
`#define Foo(a) #error Foo not implemented for PC platform`.

I actually found that __clang__ is defined with DXC, i think this should not be in the first place, but for the moment, it will do it.

**Comment by tex3d** [comment]
Consider this fixed by #2665.
