### ISSUE TITLE
-spirv error: input semantic 'SV_Position' used more than once

### ISSUE THREAD

**Issue by olegviz** [Microsoft/DirectXShaderCompiler#1690]
I have HLSL shaders with

struct PS_IN
{
float4 ProjPos  : SV_Position;
float4 UV0 : SV_Position;
.....

But this was working with DX11/DX12 and glslang , why this is problem now ?

**Comment by antiagainst** [comment]
It's just that we didn't implement support for it. Uploaded #1691 for it.
