### ISSUE TITLE
Crash when using weird bool swizzling syntax

### ISSUE THREAD

**Issue by JPMMaia** [Microsoft/DirectXShaderCompiler#1701]
### Minimal repro steps

Given the following shader (vs_example_2.hlsl):

```
struct VertexShaderInput
{
    float3 position : POSITION;
};

struct VertexShaderOutput
{
    float4 position : SV_POSITION;
};

VertexShaderOutput main(VertexShaderInput input)
{
    bool2 extra = bool(false).xx;

    VertexShaderOutput output;
    output.position = float4(input.position, 1.0f);
    return output;
}
```

Compile with: dxc /T vs_6_0 vs_example_2.hlsl

### Expected result

The shader should be compiled successfully as if it was compiled with FXC using: fxc /T vs_5_1 vs_example_2.hlsl

### Actual result

DXC doesn't show any output. It seems to crash.

**Comment by MrTrillian** [comment]
Which version of the compiler are you using? The off-the-shelf one has no problem with your code, nor does my more recently built version:

```
"C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\dxc.exe" /T vs_6_0 C:\Users\trlabell\Desktop\hlsl\bool_swizzling.hlsl
;
; Input signature:
;
; Name                 Index   Mask Register SysValue  Format   Used
; -------------------- ----- ------ -------- -------- ------- ------
; POSITION                 0   xyz         0     NONE   float
;
[...]
```

Also, in all likelihood we'll track this issue with the other one you reported, since both are caused by bool vector swizzling.

**Comment by JPMMaia** [comment]
It seems that I was using DXC from 10.0.16299.0. When trying to compile the same example with the version from 10.0.17763.0, it no longer crashes. However, issue #1700 was not fixed.
