### ISSUE TITLE
globallycoherent paired with arrays of UAV surfaces causes error

### ISSUE THREAD

**Issue by darrelpalkeINTEL** [microsoft/DirectXShaderCompiler#1715]
Shader compilation fails when combining UAV arrays and globally coherent.  I tried to compile the following shader:
https://gist.github.com/sebbbi/6cfbec7ab343924dad9b7ee48ef3ba6c
error: unknown type name 'globally coherent'
Need to fix the GroupSync typo to get it to compile on fxc.

The compilation seems to generate the error in SemaHLSL.cpp on line 11604, DiagnoseHLSLDecl.  It isn't classifying the UAV array as an object.  I believe the fix is to add bIsObject = true; to the object check (which succeeds) on line 11497.

However, that doesn't properly address the concern of the error.  glc can't be paried with non-UAV types which doesn't seem to be checked anywhere in this code and it's unclear to me how to best do that or if this should be addressed.

**Comment by aurolou** [comment]
Is there any update on this issue? When I try to compile globallycoherent on an array of UAVs, I get the following error:

error: 'globallycoherent' is not a valid modifier for a non-UAV type
globallycoherent RWTexture2D<float4>                    outputTex[12]           : register(u1);

it works when the UAV is not an array.

**Comment by python3kgae** [comment]
pull request at https://github.com/microsoft/DirectXShaderCompiler/pull/2460
