### ISSUE TITLE
DXC crashes on linux with local build

### ISSUE THREAD

**Issue by tafuri** [Microsoft/DirectXShaderCompiler#1732]
When I try to run a locally built DXC with just `dxc -help` I get this surprising assert:
```
else InitThreadMalloc already calleddxc: /hom/tafuri/DirectXShaderCompiler/modified/src/lib/DxcSupport/dxcmem.cpp:30: HRESULT DxcInitThreadMalloc(): Assertion `false && "else InitThreadMalloc already called"' failed.
```

I built DXC using gcc 7.3.0 on ubuntu 14.04

**Comment by ehsannas** [comment]
Please see our [Linux buildbot](https://travis-ci.org/Microsoft/DirectXShaderCompiler/builds/458010169?utm_source=github_status&utm_medium=notification) . The gcc and clang (Release and Debug) builds are passing on Linux.

Maybe you have misconfigured your build? Did you follow these [instructions](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/DxcOnUnix.rst)?

**Comment by ehsannas** [comment]
from the bot's gcc build log:
```
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
Cookbooks Version
git version 2.15.1
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
```

**Comment by tafuri** [comment]
Yes, I looked through and replicated the buildsteps from the buildbots. Which is why I think this bug was surprising. Just running `dxc` or `dxc -foobar` will correctly print out message/error.

If I build without asserts I get a segfault instead in a similar place.

**Comment by tafuri** [comment]
Turned out it was an issue with symbolic links turning into copies of files causing the .so library to be loaded mulitple times
