### ISSUE TITLE
macOS compiling fails

### ISSUE THREAD

**Issue by janinurminen** [Microsoft/DirectXShaderCompiler#1734]
../tools/clang/lib/SPIRV/SPIRVEmitter.cpp:4715:29: error: conditional expression is ambiguous; 'clang::spirv::SpirvEvalInfo' can be converted to 'uint32_t' (aka 'unsigned int') and vice versa

**Comment by pow2clk** [comment]
While I was the primary contributor to the MacOS build, both my macbooks have since died different horrible deaths. Even so, you might try casting ``subValue`` in the existing line 4715 of SPIRVEmitter.cpp to ``uint32_t`` to see if that alleviates the compiler's confusion.
```
    const uint32_t originValue =
        subValue.isRValue() ? uint32_t(subValue)
                            : theBuilder.createLoad(subTypeId, subValue);
```

**Comment by ehsannas** [comment]
This was caused by the very last commit I mad. Sorry about that. The bots reported the failures, but I somehow missed it. I'll post the fix.
