### ISSUE TITLE
DXC ignores VS output

### ISSUE THREAD

**Issue by jdeligiannis** [Microsoft/DirectXShaderCompiler#1739]
**Bug description**
When converting our current shaders to DXC I found an issue with VS output being stripped:

```
struct VsPackedOutput
{
           sample float4 interpolators[2] : TEXCOORD0;
};

VsPackedOutput main()
{
           VsPackedOutput packedOutput;
           packedOutput.interpolators[0] = 0;
           packedOutput.interpolators[1] = 0;
           return packedOutput;
}
```
Dissasembly:

```
!0 = !{!"clang version 3.7 (tags/RELEASE_370/final)"}
!1 = !{i32 1, i32 0}
!2 = !{i32 1, i32 4}
!3 = !{!"vs", i32 6, i32 0}
!4 = !{i32 0, %struct.VsPackedOutput undef, !5}
!5 = !{i32 32, !6}
!6 = !{i32 6, !"interpolators", i32 3, i32 0, i32 4, !"TEXCOORD0", i32 5, i32 6, i32 7, i32 9}
!7 = !{i32 1, void ()* @main, !8}
!8 = !{!9}
!9 = !{i32 0, !10, !10}
!10 = !{}
!11 = !{[2 x i32] [i32 0, i32 8]}
!12 = !{void ()* @main, !"main", !13, null, null}
!13 = !{null, !14, null}
!14 = !{!15}
!15 = !{i32 0, !"TEXCOORD", i8 9, i8 0, !16, i8 6, i32 2, i8 4, i32 0, i8 0, null}
!16 = !{i32 0, i32 1}
```
Notice that only TEXCOORD0 is written to

**Expected result**

If I rewrite our shaders to the following format (That I expect should result in the same dissasembly):
```
struct VsPackedOutput
{
           sample float4 interpolators_0 : TEXCOORD0;
           sample float4 interpolators_1 : TEXCOORD1;
};

VsPackedOutput main()
{
           VsPackedOutput packedOutput;
           packedOutput.interpolators_0 = 0;
           packedOutput.interpolators_1 = 0;
           return packedOutput;
}
```
```
!0 = !{!"clang version 3.7 (tags/RELEASE_370/final)"}
!1 = !{i32 1, i32 0}
!2 = !{i32 1, i32 4}
!3 = !{!"vs", i32 6, i32 0}
!4 = !{i32 0, %struct.VsPackedOutput undef, !5}
!5 = !{i32 32, !6, !7}
!6 = !{i32 6, !"interpolators_0", i32 3, i32 0, i32 4, !"TEXCOORD0", i32 5, i32 6, i32 7, i32 9}
!7 = !{i32 6, !"interpolators_1", i32 3, i32 16, i32 4, !"TEXCOORD1", i32 5, i32 6, i32 7, i32 9}
!8 = !{i32 1, void ()* @main, !9}
!9 = !{!10}
!10 = !{i32 0, !11, !11}
!11 = !{}
!12 = !{[2 x i32] [i32 0, i32 8]}
!13 = !{void ()* @main, !"main", !14, null, null}
!14 = !{null, !15, null}
!15 = !{!16, !18}
!16 = !{i32 0, !"TEXCOORD", i8 9, i8 0, !17, i8 6, i32 1, i8 4, i32 0, i8 0, null}
!17 = !{i32 0}
!18 = !{i32 1, !"TEXCOORD", i8 9, i8 0, !19, i8 6, i32 1, i8 4, i32 1, i8 0, null}
!19 = !{i32 1}
```
Notice that both TEXCOORD0 and TEXCOORD1 is written to.

**Comment by MrTrillian** [comment]
The compiler is actually correct here, but you have to refer to the DXIL documentation to understand its output: https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/DXIL.rst

In your first output, the struct annotation `!5` has a single field, `!6` for `interpolators`, which properly reports `TEXCOORD0` as the applied attribute. This data is used for reflection so it should map one-to-one to your struct fields, which it does. Likewise, in your second output, there are two fields with their individual annotations as expected.

Now if we look at `!13` in your first output, this says that your shader only has a signature for outputs, `!14`, which has a single element, `!15`. This element has the semantic `TEXCOORD` and indices given by `!16`, which is a list of two indices: 0 and 1, hence these properly represent the two `TEXCOORD0` and `TEXCOORD1` semantics. Your second output rather has two output signature elements, individually representing `TEXCOORD0` and `TEXCOORD1`.

The generated code itself correctly writes to both outputs:
```
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 0, float 0.000000e+00)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 1, float 0.000000e+00)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 2, float 0.000000e+00)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 3, float 0.000000e+00)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 1, i8 0, float 0.000000e+00)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 1, i8 1, float 0.000000e+00)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 1, i8 2, float 0.000000e+00)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 1, i8 3, float 0.000000e+00)
```

However, I don't see how the type annotations distinguish an array from a single element for reflection purposes, I'll follow up with people who know better than I do to see if something is amiss.

**Comment by MrTrillian** [comment]
Ah, it looks like we resolve `%struct.VsPackedOutput` to `%struct.VsPackedOutput = type { [2 x <4 x float>] }` and so we can tell that it's an array, so everything looks fine to me. Let me know if I overlooked anything!
