### ISSUE TITLE
[SPIRV] ignores register(c#)

### ISSUE THREAD

**Issue by TiemoJung** [Microsoft/DirectXShaderCompiler#1743]
The spir-v backend ignores register(c#) commands.
Each entry of the c register is one 32 bit by 4 component vector (e.g. float4).
So c# translates to # * sizeof(float4).

```
float4 a;
float4 b;
float4 c;
float4 d : register(c0);
float4 e;

float4 main() : SV_Target {
    return a + c;
}
```
Currently results in this:
```
[....]
OpMemberName %type__Globals 0 "a"
OpMemberName %type__Globals 1 "b"
OpMemberName %type__Globals 2 "c"
OpMemberName %type__Globals 3 "d"
OpMemberName %type__Globals 4 "e"
[....]
OpMemberDecorate %type__Globals 0 Offset 0
OpMemberDecorate %type__Globals 1 Offset 16
OpMemberDecorate %type__Globals 2 Offset 32
OpMemberDecorate %type__Globals 3 Offset 48
OpMemberDecorate %type__Globals 4 Offset 64
[....]
```
The expected result would be that d is at offset 0 and all others are put after the variables with explicit register index.
The DXIL output does the correct thing (by accessing the right location instead of setting offset).

**Comment by ehsannas** [comment]
Thanks for reporting. Will investigate.

**Comment by ehsannas** [comment]
@TiemoJung , I've started to look into this issue. It is not simple :)

Consider interactions between `[[vk::offset]]` and `register(c#)`, as well as mix of cases when these attributes and annotations are used (and not used) together.

I've also filed issue #1900 to better understand how the offsets should be correctly calculated for `register(c#)` usages.

**Comment by TiemoJung** [comment]
For our use case we always specify the register, basically what packoffset requires, but for historical reasons register(c#) is used.

**Comment by ehsannas** [comment]
This is now supported.
