### ISSUE TITLE
Upgrading from 5_1 to 6_0, dealing with unused shader resources

### ISSUE THREAD

**Issue by JaapSuter** [microsoft/DirectXShaderCompiler#1749]
*Edit, there's a follow-up reply to this where I have a minimal repro scenario.*

Apologies if this has been asked and answered before, but I wasn't able to find an issue for it.

I'm trying to upgrade our HLSL to leverage shader model 6.0, which means compiling with DXC instead of FXC. Using 5_1, all our shaders compile in both debug and release with warnings as errors `-WX`, strict mode `Ges`, and `all_resources_bound`.

When compiling with 6_0, I get similar errors on a variety of shaders. We'll stick with one of our simplest compute shaders.

```
error: validation errors
Shader CBV descriptor range (RegisterSpace=0, NumDescriptors=1, BaseShaderRegister=1) is not fully bound in root signature.
Root Signature in DXIL container is not compatible with shader.
```

So this compute shader itself doesn't use any CBVs. It's root signature looks like this:

```
#include "Common.hlsli"

RWTexture3D<unorm float> s_volumeLowUav: register(u0);

#define COMPUTE_RS \
    "DescriptorTable(SRV(t20, numDescriptors = 1, flags = DATA_STATIC_WHILE_SET_AT_EXECUTE), visibility = SHADER_VISIBILITY_ALL)," \
    "DescriptorTable(UAV(u0, numDescriptors = 1, flags = DATA_STATIC_WHILE_SET_AT_EXECUTE), visibility = SHADER_VISIBILITY_ALL)," \
    "StaticSampler(s4, visibility = SHADER_VISIBILITY_ALL, filter=FILTER_MIN_MAG_LINEAR_MIP_POINT, addressU=TEXTURE_ADDRESS_BORDER, addressV=TEXTURE_ADDRESS_WRAP,  addressW=TEXTURE_ADDRESS_BORDER, borderColor = STATIC_BORDER_COLOR_OPAQUE_BLACK)," \
```

Note the UAV resource is declared in this file itself, and the SRV that is used is declared in `Common.hlsli`.

And it's this `Common.hlsli` where I think the problem lies. It essentially declares a whole pile of resources that depending on the shader, different subsets are used from. In other words, our `Common.hlsli` contains:

```
ConstantBuffer<MARCH_CONST_BUFFER> s_marchConst : register(b0);                                                            ConstantBuffer<PIPE_CONST_BUFFER> s_pipeConst: register(b1);                                                               ConstantBuffer<CAMERA_CONST_BUFFER> s_cameraConst: register(b2);                                                           ConstantBuffer<SCHEMATIC_CONST_BUFFER> s_schematicConst: register(b3);                                                     ConstantBuffer<CROSS_SECTION_CONST_BUFFER> s_crossConst: register(b4);                                                                                                                                                                                

Texture2D<unorm float4> s_schematicTexture : register(ps, t0);                                                                                                                                                                                        
Texture1D<float3> s_wellPosTexture : register(vs, t10);                                    
Texture1D<float3> s_wellTanTexture : register(vs, t11);                                                                    
Texture1D<float3> s_wellNorTexture : register(vs, t12);                                                                    
                                                                                                                           
Texture3D<unorm float> s_volumeTexture : register(t20);                                

// ...etc...
```

Notice how register `t20` is declared, which is the SRV the above mentioned compute shader root signature refers to.

But also notice how this `Common.hlsli` declares so many other resources that aren't actually used by this particular compute shader. With the `5_1` shader, in the final compilation, the compiler would simply see that these resources aren't used, that the root signature didn't refer to them, and that subsequently there was no need for them. It would just ignore them (if I output the shader disassembly, there'd be no reference to these resources). It would even do this if they were in fact used in a function, as long as that particular function wasn't ever called directly or indirectly by the shader's entry point.

But it appears that as soon as I compile with 6_0, just having the declaration of this resource, or a function that uses this resource that actually isn't ever called from this particular shader, the compile insists of it being available in the root signature somehow.

Is that assumption correct? Is there a way for me to get the old behaviour with the 6_0 compiler? Where I'm allowed to declare a shader resource bound to a register, but if it's never used directly or indirectly, then it doesn't have to be referenced in the root signature?

Our `Common.hlsli` declares about 30 different resources, and numerous shaders use very different subsets of these shaders. So having to avoid mentioning different shader resources depending on what shader is being compiled would result in a combinatorial explosion of shader include files or odd preprocessor definitions.

I can't imagine that being necessary, and I imagine my use-case is a typical way to do shaders. So I'm hoping I missed something obvious that'll make my upgrade from 5_1 to 6_0 a bit easier.

If more information is needed, I'd be happy to provide it.

Thanks so much,

Jaap Suter

**Comment by JaapSuter** [comment]
```

RWTexture3D<unorm float> s_uav: register(u0);

#define COMPUTE_RS "DescriptorTable(UAV(u0, numDescriptors = 1, flags = DATA_STATIC_WHILE_SET_AT_EXECUTE), visibility = SHADER_VISIBILITY_ALL)"

struct SOME_CONST_BUFFER { float m_someFloat; };
ConstantBuffer<SOME_CONST_BUFFER> s_constBuffer: register(b0);

float someFunction() { return s_constBuffer.m_someFloat; }

// static const float UNUSED_CONSTANT = someFunction();

[RootSignature(COMPUTE_RS)]
[numthreads(32, 32, 1)]
void cs_main(uint3 dispatchThreadID : SV_DispatchThreadID)
{  
    s_uav[dispatchThreadID] = 0;
}
```

**Comment by BitMD** [comment]
Sweeping through bugs today and I noted that this no longer repros.  We must have fixed it while resolving other issues.  Thanks!
