### ISSUE TITLE
Decide on allowing phi on struct type

### ISSUE THREAD

**Issue by vcsharma** [microsoft/DirectXShaderCompiler#1753]
We had a recent bug #1745 where we encountered phi on struct type (cbufferloadlegacy) which may cause issues in the backend during lowering. It seems we may have had similar issues reported in the past. While the bug #1745 is fixed, it is possible that phi on struct type can get inserted in different cases. Furthermore, the current dxil spec doesn't specifically mention if it is allowed to have phi node on struct type. 

In future, if we decide not to allow it, then we would likely have to add a new module pass (before finalizing a module) which would ensure that no phi on struct type are present. In addition we also need to update our validator to check for this scenario and fail the validation in case it gets violated.

**Comment by llvm-beanz** [comment]
Closing since we are unlikely to do this and there isn't enough information for an external contributor to do it.
