### ISSUE TITLE
[SPIRV] Feature Request: An option to decorate all the floating points values and operations with RelaxedPrecision

### ISSUE THREAD

**Issue by Cry-Mory** [microsoft/DirectXShaderCompiler#1758]
In GLSL, it is possible to write "precision mediump float;"at the beginning of the shader and ask the compiler to consider all the floating point values as RelaxedPrecision. It would be great if we get similar functionality in HLSL or maybe an option in DXC to force all the floating point values and operations being decorated with the RelaxedPrecision decorator.

**Comment by ehsannas** [comment]
There exists an optimization pass in spirv-opt that does this:
```
  --relax-float-ops
               Decorate all float operations with RelaxedPrecision if not already
```

So, we don't need to add a new option to DXC. You can get this feature using the `-Oconfig` [option](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#optimization) of DXC. This option allows you to specify a custom set of spirv-opt passes that you'd like to run. e.g: you can compile your shader using:
```
dxc.exe -T <target> -E <entry> -Fo <output_file> -Oconfig=-O,--relax-float-ops
```
