### ISSUE TITLE
Validation failed for DXIL bitcode which is dumped inside driver.

### ISSUE THREAD

**Issue by guwangfeng** [Microsoft/DirectXShaderCompiler#1759]
Hi,

I'm debugging an application issue inside driver, I dumped the shader's bitcode to a vs.bc file, which is sent by D3D runtime, in the driver. I want to reproduce the issue by writing a small application and use the dumped bitcode in the small application.

First, because D3D runtime only accepts a DXIL container, I use the command "dxa.exe vs.bc" to assemble the bitcode to a DXIL container, the output file is vs.dxbc. I then used "dxc.exe -dumpbin vs.dxbc" to verify if it's correct, the disassembly could be shown correctly.

Second, I tried to use the method in the link
https://www.wihlidal.com/blog/pipeline/2018-09-16-dxil-signing-post-compile/
to sign dxil container so that it can be accepted by D3D runtime, but I encountered the following validation error:

_The dxil container failed validation
Error:
Unknown target triple ''
Cannot find function annotation for main
External function 'dx.op.tempRegStore.i32' is unused
External function 'dx.op.tempRegStore.f32' is unused
External function 'dx.op.tempRegLoad.f32' is unused
Flags must match usage
Flags declared=0, actual=16

Validation failed._

Because vs.bc is the data from runtime, I do think that it should pass validation.

Any solution to solve the validation error?

The following the file vs.dxbc disassembly:

[vs.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/2656492/vs.txt)

**Comment by python3kgae** [comment]
Hi guwangfeng,
The dxil in the attachment is converted from dxbc which already validated. To reproduce your issue, you can save the dxbc instead dxil.

Thanks
Xiang

**Comment by guwangfeng** [comment]
Hi Xiang,

What I wanted to do is how to let D3D runtime accept the shader bitcode which is sent by D3D runtime. For some reason, I may not get application's source code (including shader source), so I expect to dump the shader bitcode inside driver and then use it in a manually written D3D12 test application to do testing. But seems the way I mentioned above doesn't work. That is, "wrapping the dxil code into a dxil container via dxa.exe, then sign the dxil container" doesn't work.

 So is "write a slim layer to dump dxbc from D3D12 API directly" the only solution?

Thanks,
Wangfeng

**Comment by python3kgae** [comment]
Maybe you can capture your app with pix (https://blogs.msdn.microsoft.com/pix/download/), then get dxbc from the pix capture file.

**Comment by guwangfeng** [comment]
OK, I'll have a try.

Thanks!
Wangfeng
