### ISSUE TITLE
Remove usages of `bDefaultRowMajor` in favor of always attributing matrix types

### ISSUE THREAD

**Issue by tristanlabelle** [microsoft/DirectXShaderCompiler#1773]
Pull request #1770 adds row/column-major attributes on matrices at the time they are declared, taking the current pragma state into account. We should go further and ensure all matrices are always attributed, and the rest of the codebase never has to take the `bDefaultRowMajor` flag into account. See `DefaultMatrixOrientationColumnMajor` flag.

**Comment by llvm-beanz** [comment]
Closing since this is an implementation detail that we're unlikely to invest in resolving. We'll be reimplementing matrices in Clang and will address orientation differently there.
