### ISSUE TITLE
Investigate when to use ordered vs. unordered compare instruction

### ISSUE THREAD

**Issue by vcsharma** [microsoft/DirectXShaderCompiler#1784]
There are a few places/passes in dxcompiler where we use ordered or unordered version of floating-point comparison without providing very clear reason for choosing one over other. 

For example in `HLMatrixLowerPass.cpp` we use ordered compare (as shown below):

```
  case HLBinaryOpcode::LT:
    if (isFloat)
      Result = CmpInst::Create(Instruction::FCmp, CmpInst::FCMP_OLT, tmp, tmp);
```

In another example in `CGHLSLMS.cpp`, we use unordered compare:

```
static Value *CreateCastforBoolDestType(CGBuilderTy &Builder, Value *srcVal) {
  llvm::Type *srcTy = srcVal->getType();
  if (srcTy->isFloatingPointTy()) {
    return Builder.CreateFCmp(FCmpInst::FCMP_UNE, srcVal,
                              ConstantFP::get(srcTy, 0));
  }
```

Depending on a particular backend, an ordered compare could lead to a different behavior than unordered one in presence of NaN. For example, as mentioned in the [article](https://stackoverflow.com/questions/8627331/what-does-ordered-unordered-comparison-mean), on x86 arch, the two versions of compare instruction could fetch different results in the presence of NaN.

So except for the special cases, we should probably use a global flag to choose between ordered vs. unordered comparison. It may also make sense to compare the behavior with fxc.

**Comment by MrTrillian** [comment]
For float to bool conversions, clang uses unordered, so I think it closes that part of the issue. See change in PR #1885. For regular comparisons between floats, I haven't checked.
