### ISSUE TITLE
Bad error message when using RWByteAddressBuffer.Load<matrix>

### ISSUE THREAD

**Issue by MrTrillian** [Microsoft/DirectXShaderCompiler#1789]
Repro:

```
RWByteAddressBuffer buf;
void main() { buf.Load<int1x1>(0); }
```

Compile with

`dxc -T vs_6_0 -HV 2018 repro.hlsl`

Result:

`repro.hlsl:2:24: error: Explicit template arguments on intrinsic Load requires HLSL version 2018 or above.`

But the problem is the template argument being a matrix, since we are using HLSL 2018 and replacing `int1x1` by `int` fixes this.

**Comment by hekota** [comment]
This should be just fixed by #1786.

**Comment by hekota** [comment]
The new error message:

```
d:\Repro\test.hlsl:5:12: error: Explicit template arguments on intrinsic Load are limited one to scalar or vector type.
  buf.Load<int1x1>(0);
```

**Comment by MrTrillian** [comment]
Haha, sweet!
