### ISSUE TITLE
Bool to float conversion

### ISSUE THREAD

**Issue by kingofthebongo2008** [Microsoft/DirectXShaderCompiler#1819]
Hello,

We have encountered in issue in a function which looks like this:

```
float4 FuncWrong(float value)
{
    float4 f0 = SampleFromTexture();
    return ( f0 >= value);
}

float4 FuncCorrect(float value)
{
    float4 f0 = SampleFromTexture();
    float a = f0.x >= value? 1.0f : 0.0f;
    float b = f0.y >= value? 1.0f : 0.0f;
    float c = f0.z >= value? 1.0f : 0.0f;
    float d = f0.w >= value? 1.0f : 0.0f;
    return float4( a,b,c,d );
}
```

On my GCN3 card the correct function produces patterns like this:

```
v_cndmask_b32  v23, 0, 1.0, s[24:25]                  // 0000000006B4: D1000017 0061E480
v_cndmask_b32  v29, 0, 1.0, s[26:27]                  // 0000000006BC: D100001D 0069E480
v_cndmask_b32  v30, 0, 1.0, s[28:29]    
```

The wrong function produces patterns like this:

```
 v_mov_b32     v14, 0x4f800000  
 v_cndmask_b32  v29, 0, v14, s[24:25]                  // 0000000006B0: D100001D 00621C80
 v_cndmask_b32  v30, 0, v14, s[26:27]                  // 0000000006B8: D100001E 006A1C80
 v_cndmask_b32  v31, 0, v14, s[28:29]
```

I have tracked down in the code 0x4f800000 
to ExpandLegalINT_TO_FP, so definitely there is a problem when converting bools to floats.

Do you need more information about the bug? Please respond to me if needed.

All the best

**Comment by MrTrillian** [comment]
Thanks for reporting! I turned your snippet into this pixel shader:

```
Texture2D<float4> tex;
SamplerState samp;
float _zcompare;

float4 SampleFromTexture() { return tex.Sample(samp, float2(0, 0)); }

float4 FuncWrong(float value)
{
	float4 f0 = SampleFromTexture();
	return ( f0 >= value);
}

float4 FuncCorrect(float value)
{
	float4 f0 = SampleFromTexture();
	float a = f0.x >= value ? 1.0f : 0.0f;
	float b = f0.y >= value ? 1.0f : 0.0f;
	float c = f0.z >= value ? 1.0f : 0.0f;
	float d = f0.w >= value ? 1.0f : 0.0f;
	return float4( a,b,c,d );
}

float4 main() : SV_Target
{
	return FuncCorrect(_zcompare);
}
```

For `FuncCorrect`, we generate:

```
  %cmp.i = fcmp fast oge float %3, %1
  %cond.i = select i1 %cmp.i, float 1.000000e+00, float 0.000000e+00
  %cmp2.i = fcmp fast oge float %4, %1
  %cond5.i = select i1 %cmp2.i, float 1.000000e+00, float 0.000000e+00
  %cmp6.i = fcmp fast oge float %5, %1
  %cond9.i = select i1 %cmp6.i, float 1.000000e+00, float 0.000000e+00
  %cmp10.i = fcmp fast oge float %6, %1
  %cond13.i = select i1 %cmp10.i, float 1.000000e+00, float 0.000000e+00
```

Whereas for `FuncWrong`, we generate:

```
  %cmp.i.i0 = fcmp fast oge float %3, %1
  %cmp.i.i1 = fcmp fast oge float %4, %1
  %cmp.i.i2 = fcmp fast oge float %5, %1
  %cmp.i.i3 = fcmp fast oge float %6, %1
  %conv.i.i0 = uitofp i1 %cmp.i.i0 to float
  %conv.i.i1 = uitofp i1 %cmp.i.i1 to float
  %conv.i.i2 = uitofp i1 %cmp.i.i2 to float
  %conv.i.i3 = uitofp i1 %cmp.i.i3 to float
```

Those look different as they respect the HLSL code patterns, but they should be semantically equivalent. DXC does not compile to GCN3 assembly itself, so if you can confirm that your DXIL looks like what I have here, then the problem lies in the backend compiler you're using and the bug should be reported through a more appropriate channel.

**Comment by MrTrillian** [comment]
This issue is external to DXC. Please report to your backend provider. Thanks!

**Comment by kingofthebongo2008** [comment]
So for the wrong code:

  %.i0 = fcmp fast oge float %4, %2
  %.i01 = uitofp i1 %.i0 to float
  %5 = bitcast float %.i01 to i32

gcn3:
  image_gather4_lz  v0, v0, s[4:11], s[12:15] da        // 000000000040: F11C4100 00610000
  s_load_dwordx4  s[4:7], s[0:1], 0x00                  // 000000000048: C00A0100 00000000
  s_waitcnt     lgkmcnt(0)                              // 000000000050: BF8C007F
  s_andn2_b32   s5, s5, 0x3fff0000                      // 000000000054: 8905FF05 3FFF0000
  s_buffer_load_dword  s2, s[4:7], 0x00                 // 00000000005C: C0220082 00000000
  s_load_dwordx8  s[4:11], s[0:1], 0x2e0                // 000000000064: C00E0100 000002E0
  s_waitcnt     vmcnt(0) & lgkmcnt(0)                   // 00000000006C: BF8C0070
  v_cmp_le_f32  vcc, s2, v0                             // 000000000070: 7C860002
  v_mov_b32     v2, 0x4f800000                          // 000000000074: 7E0402FF 4F800000
  v_lshlrev_b64  v[0:1], 0, 0                           // 00000000007C: D28F0000 00010080
  v_cndmask_b32  v2, 0, v2, vcc

**Comment by kingofthebongo2008** [comment]
Good code:
  %4 = extractvalue %dx.types.ResRet.f32 %3, 0
  %5 = fcmp fast oge float %4, %2
  %6 = select i1 %5, i32 1065353216, i32 0

  image_gather4_lz  v0, v0, s[4:11], s[12:15] da        // 000000000040: F11C4100 00610000
  s_load_dwordx4  s[4:7], s[0:1], 0x00                  // 000000000048: C00A0100 00000000
  s_waitcnt     lgkmcnt(0)                              // 000000000050: BF8C007F
  s_andn2_b32   s5, s5, 0x3fff0000                      // 000000000054: 8905FF05 3FFF0000
  s_buffer_load_dword  s2, s[4:7], 0x00                 // 00000000005C: C0220082 00000000
  s_load_dwordx8  s[4:11], s[0:1], 0x2e0                // 000000000064: C00E0100 000002E0
  s_waitcnt     vmcnt(0) & lgkmcnt(0)                   // 00000000006C: BF8C0070
  v_cmp_le_f32  vcc, s2, v0                             // 000000000070: 7C860002
  v_lshlrev_b64  v[0:1], 0, 0                           // 000000000074: D28F0000 00010080
  v_cndmask_b32  v2, 0, 1.0, vcc                        // 00000000007C: D1000002 01A9E480
  v_mov_b32     v3, v2                                  // 000000000084: 7E060302
  v_mov_b32     v4, v2                                  // 000000000088: 7E080302
  v_mov_b32     v5, v2                                  // 00000000008C: 7E0A0302
  image_store   v[2:5], v[0:3], s[4:11] dmask:0xf unorm //

**Comment by MrTrillian** [comment]
If you can say what tool you're using to generate this GCN3 assembly, I can see whether we have contacts with those people and if we can forward the bug.

**Comment by kingofthebongo2008** [comment]
I just use pix

In pix you can see the dxil and the assembly.

nvidia sadly do not offert the same functionality.
