### ISSUE TITLE
Linux version is 100% broken

### ISSUE THREAD

**Issue by gwihlidal** [Microsoft/DirectXShaderCompiler#1821]
A change after https://github.com/Microsoft/DirectXShaderCompiler/commit/cd237f5c3f7e8390fafff122333423afe55bc6c7 causes a 100% failure when using DXC on Linux (either for DXIL or for SPIR-V), even for the simplest of shaders.

```
root@c00dd9ab3a54:/app/signing# cat simple.hlsl
float4 main() : SV_TARGET0
{
    return float4(0, 1, 0, 1);
}

root@c00dd9ab3a54:/app/signing# $DXC_PATH -T ps_6_0 simple.hlsl
dxc failed : error code 0x80004005.


```

It would be great to get this fixed. Thank you very much!

**Comment by gwihlidal** [comment]
I think this may be an issue in my environment; will close for now and do more testing

**Comment by michael-nischt** [comment]
did you the cause?

I have the same error with a 100% failure from the dxc from the vulkan linux tarball on Arch...

**Comment by h3r2tic** [comment]
If anyone else runs into this, make sure that `libdxcompiler.so` can be found in your `LD_LIBRARY_PATH`.
