### ISSUE TITLE
[spirv] -fvk-*-shift should affect all types of bindings

### ISSUE THREAD

**Issue by pmichniewski** [Microsoft/DirectXShaderCompiler#1826]
At the moment, -fvk-*-shift options only affects resource bindings that were provided explicitly by :register(x). This not only is inconsistent with glslang, but it also makes these options much less useful.

In my case, an app I'm porting from D3D does not use explicit register allocations and relies on implicit placement and reflection. With the current behavior, there can be collisions between shaders at different stages (e.g. vertex and fragment), which makes it impossible to compile a pipeline.

In glslang this was easy to solve by providing different offsets depending on register type and shader stage, but glslang has other issues that made me look into dxc.

**Comment by ehsannas** [comment]
Hi @pmichniewski 
Please see our documentation about these options [here](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#hlsl-register-and-vulkan-binding).

In general when it comes to bindings, there is no one solution that can satisfy everyone. That's why we've had to implement multiple mechanisms. The interaction between these mechanisms, and the number of developers already adapting to the current behavior is some of the  reasons we are reluctant to add/change these behaviors.

Would you elaborate what is your suggested behavior? and why the current compiler doesn't satisfy your needs?

**Comment by pmichniewski** [comment]
Thank you for your answer. To elaborate, I'll use a modified example from the docs:

```
struct S { ... };

ConstantBuffer<S> cbuffer1 : register(b0);
Texture2D<float4> texture1 : register(t0);
SamplerState      sampler1 : register(s0);
SamplerState      sampler2;
```

If we use `-fvk-b-shift 10 0 -fvk-t-shift 20 0 -fvk-s-shift 30 0`, as expected, `cbuffer1` will be placed at \# 10, `texture1` at \# 20, `sampler1` at \# 30, but `sampler2` will be at \# 0.

This is in contrast to how glslc would place things - it would place `sampler2` at \# 31 and I find this behavior much more consistent and useful.

This isn't a problem in case of compute shaders - I can easily perform a reflection and map everything. The problem starts when we have e.g. vertex and fragment shaders:

vert.hlsl:
```
uint param1;
uint param2;

Texture2D<float4> texture1;
```

frag.hlsl:
```
uint param3;
uint param4;

Texture2D<float4> texture2;
```

In this case, the compiler would place `param1` and `param2` in a global cbuffer `$Globals` placed at \# 0 and `texture1` at \# 1. Since these files are compiled separately, it would also place `param3` and `param4` in another cbuffer `$Globals` also placed at \# 0, and `texture2` at \# 1. This isn't a problem in D3D - there are separate namespaces for each stage, but in Vulkan everything is placed into a single pipeline and we get duplicated bindings.

In glslc I would just add `-f*-binding-base` with different offsets for each stage and be done with it. Unfortunately, I can't use glslc because of structure alignment issues (it only supports std140 and std430). I also can't really change the shaders to provide explicit `:register()` annotations - there are 500+ shader files, with 100k+ permutations based on `#if` statements and the sources are shared between multiple platforms.

Don't get me wrong - I can hack dxc into submission myself but I think there are use cases for this outside of my company. Especially since glslc (which is probably where the idea for `-fvk-*-shift` came from) already does this.

**Comment by pmichniewski** [comment]
After actually implementing this I came to the conclusion that this isn't really that beneficial, since it performs remapping before the optimization pass, which means that there can be unused slots in the middle. It's better to do remapping manually using e.g. SPIRV-Reflect, in which case the current behavior is actually beneficial - it's easy to detect if a resource was manually placed using :register(), which would otherwise be impossible to do. I guess it would be nice if the compiler provided some other way of detecting manual placement of resources using :register() via some decorations.
