### ISSUE TITLE
It would be nice if preprocessor pragmas control compilation

### ISSUE THREAD

**Issue by kingofthebongo2008** [microsoft/DirectXShaderCompiler#1849]
Hey,

Quite useful might be, if a #pragma or a #define can control the compilation,
example.

#__DXC__ENABLE_UNBOUND_DESCRIPTORS

**Comment by llvm-beanz** [comment]
This bug has been languishing for a while. From a general standpoint, I don't think we're opposed to adding more robust `#pragma` support, but there are some design challenges around it. Historically we've done some things with magic preprocessor defines, and I don't think we'll do that again in the future. 

If there are specific features you want to be able to control in source we can take a more specific request, but we're not going to go and add support for exposing all the compiler flags via `#pragma` directives.
