### ISSUE TITLE
Crash: assinging function object to integer value

### ISSUE THREAD

**Issue by LukasBanana** [Microsoft/DirectXShaderCompiler#187]
The following HLSL code is obviously invalid, but the compiler should of course output a comprehensive error report. However, it seems that the new compiler crashes but the old fxc reports the simple error message `error X3005: 'f': identifier represents a function, not a variable`:
```
int f() {
    return 1;
}
void main() {
    int x = f; // CRASH
}
```
I found this issue by testing how the new compiler parses function call expressions.
So I used the following code example, which is compiled successfully with the new compiler, but the old fxc reports the same error message like in the example above:
```
int f() {
    return 1;
}
void main() {
    ((f))();
}
```
So I assume that the new compiler handles call expressions by a separation of its function object (here `f` or `((f))`) _and_ the call itself with optional arguments (here `()`).

Am I right with this assumption? Because I guess this comes from clang where function objects can be passed around without being used as call expressions.

**Comment by python3kgae** [comment]
Thanks for the feedback.
The crash should be fixed with https://github.com/Microsoft/DirectXShaderCompiler/pull/190

For function objects, both 
         using func_type = int (); 
and 
         int (*func)() 
are illegal for hlsl currently.
So it's hard to pass function around.

**Comment by marcelolr** [comment]
@LukasBanana please feel free to open a new issue or reopen this one if you're still having trouble with this - thanks!
