### ISSUE TITLE
Path for IDxcIncludeHandler callback

### ISSUE THREAD

**Issue by SakibSaikia** [Microsoft/DirectXShaderCompiler#1871]
Hi!

I'm using the custom include handler during preprocessing. I've noticed that in LoadResource() callback, the includes are all prepended with the (relative) path to the base shader being compiled. If the includes include other files then this process is nested. This becomes problematic since there is no parent data unlike fxc, and we are using the fully qualified include file names to look into a table where the shaders have already been loaded into memory.

Is there a way to skip prepending the path and just return what is specified in the shader's #include?

**Comment by SakibSaikia** [comment]
After working with this for sometime, I was able to understand that this callback needs to be fault-tolerant. I'm now specifying the include directories as a "-I" argument in the command line params and looking for a match. Otherwise, I skip that include.

**Comment by MrTrillian** [comment]
Great that you found a workaround. Could you give an example of your original problem with your compiler arguments, the `#include` directive and the string you were getting in your handler callback to see if we should consider this as a potential future feature?

**Comment by KuribohG** [comment]
The same problem here.

If we have two shaders, like a.hlsl and b.hlsl. They are both in path C:\shader. If we specify the include path as C:\, then we must include the other file as:
`#include <shader/b.hlsl>`
But if in b.hlsl, it includes another file, say c.hlsl:
`#include <shader/c.hlsl>`
then in LoadResource() callback, when we compile a.hlsl, we get a path like shader\shader\c.hlsl.

When we compile in command line, we only specify the include path and all work. If there is a way to specify this path in DXC API  ?
