### ISSUE TITLE
namespaces and normalize function errors

### ISSUE THREAD

**Issue by kingofthebongo2008** [Microsoft/DirectXShaderCompiler#1884]
Hello we have discovered issues with namespaces:

```
Texture2D<float4> texture;
RWTexture2D<float3> textureOut : register(u0);

namespace safe1
{
  static const float SAFE_EPSILON = 2.4414e-4;
  float3 normalize(float3 _x) { return _x * rsqrt(max(SAFE_EPSILON, dot(_x, _x))); }
  float2 normalize(float2 _x) { return _x * rsqrt(max(SAFE_EPSILON, dot(_x, _x))); }
  float3 Normalize(float3 _x) { return _x * rsqrt(max(SAFE_EPSILON, dot(_x, _x))); }
}

[numthreads(16,16,1)]
void CS_Main(uint3 groupId : SV_GroupID,
    uint3 dispatchThreadId : SV_DispatchThreadID,
    uint3 groupThreadId : SV_GroupThreadID
)
{
	float4 l = texture.Load(0); 
	float3 n = safe1::normalize(float3(l.x,l.y,l.z));
	textureOut[uint2(0,0)] =float3(n);
}

```
This code outputs equivalent to a call to default hlsl normalize when you have two normalize functions in the namespace as pointed out.

If you have only 1 it calls it correctly.

Here is the command line

`dxc.exe shader_preprocessed.hlsl /O3 /E CS_Main /T cs_6_0 -Fc shader_preprocessed.asm`

To recap.

safe1::normalize calls is equivalent to ::normalize
safe1::Normalize is correct.

**Comment by MrTrillian** [comment]
Thanks for reporting! We'll look into it.
