### ISSUE TITLE
[SPIR-V] 'SPV_NV_shader_subgroup_partitioned' Intrinsic Support

### ISSUE THREAD

**Issue by unit-404** [microsoft/DirectXShaderCompiler#1889]
We want to port our shading code into HLSL, but still not enough vendor extensions for HLSL->SPIR-V compilation (intrinsic), such as `SPV_NV_shader_subgroup_partitioned`. Need SPIR-V extension intrinsic headers or extensions itself support.

**Comment by helixd-2k18** [comment]
That now match with `WaveMatch` intrinsic from `HLSL_ShaderModel6_5`...

**Comment by sudonatalie** [comment]
Although there are no explicit Vulkan intrinsic functions available for `SPV_NV_shader_subgroup_partitioned` in DXC, we do now support [inline SPIR-V](https://github.com/microsoft/DirectXShaderCompiler/wiki/GL_EXT_spirv_intrinsics-for-SPIR-V-code-gen) through `vk::ext_instruction`, `vk::ext_extension`, etc. attributes. I know this is a very old issue but if you do still have a use case where `SPV_NV_shader_subgroup_partitioned` is needed and it cannot be accomplished with inline SPIR-V, please add a comment with more context and we'll be happy to re-open.
