### ISSUE TITLE
Test implicit conversions as part of inout/out parameters

### ISSUE THREAD

**Issue by tristanlabelle** [microsoft/DirectXShaderCompiler#1890]
HLSL allows:
```
void foo(out int2 x) {}
float2 x;
foo(x);
```
… and will generate conversions to/from the types in question. This is an area that needs coverage. Specifically, there are suspicious matrix bitcasts in `CGHLSLMS.cpp` which are probably wrong.

**Comment by llvm-beanz** [comment]
> This is an area that needs coverage. Specifically, there are suspicious matrix bitcasts in `CGHLSLMS.cpp` which are probably wrong.

This is a completely terrifying and accurate statement...

That said, I'm going to close this issue because it is broad and not really actionable. We are putting a lot of focus on cleaning up the code around argument passing over the next few months, so hopefully we'll get there.

**Comment by llvm-beanz** [comment]
Closing as not planned but we are addressing this and related issues in Clang.
