### ISSUE TITLE
llvm_assert creating bitcast due to mismatched address space when accessing base class member of groupshared derived instance

### ISSUE THREAD

**Issue by tex3d** [Microsoft/DirectXShaderCompiler#1896]
The following causes an llvm_assert when trying to create a bitcast from `Derived*` to `Base*` in order to access the member `Base::foo`.  This is because `gs_derived` is `groupshared`, which makes it `addrspace(3)`, and we skip the normal address space cast in `CodeGenModule::GetOrCreateLLVMGlobal` for HLSL, expecting to do a copy in the appropriate place instead, such as when converting input for a function argument.
```
// -T cs_6_0 -E main

class Base { uint foo; };
class Derived : Base { };
groupshared Derived gs_derived;
RWByteAddressBuffer RWBuf;

[numthreads(2, 1, 1)]
void main(uint3 groupThreadID: SV_GroupThreadID) {
  if (groupThreadID.x == 0)
    gs_derived.foo = 1;
  GroupMemoryBarrierWithGroupSync();
  RWBuf.Store(groupThreadID.x * 4, gs_derived.foo);
}
```

**Comment by MrTrillian** [comment]
There are more things broken with derived-to-base conversions, see #1843. Also note that FXC didn't even support that type of conversion.
