### ISSUE TITLE
Test reads/writes of matrix subscripts

### ISSUE THREAD

**Issue by tristanlabelle** [microsoft/DirectXShaderCompiler#1898]
From code inspection, this looks like an area that needs more testing. I'm thinking of combinations of:

Matrix value location:
- Matrix in local variable
- Matrix in static variable
- Matrix as return value
- Matrix returned by intrinsic (WorldToObject)
- Matrix rvalue (such as after an operator)
- Matrix in constant buffer
- Matrix in structured buffer

Matrix type:
- Direct matrix
- Matrix array
- Bool matrices

Matrix subscript operation:
- Subscript [0]
- Element ._11

Subscript usage:
- Assignment
- Arithmetic-assignment operators
- Inc/dec operators
- inout/out parameter
- intrinsic out parameter (frexp, sincos)

**Comment by MrTrillian** [comment]
Related: #1881

**Comment by llvm-beanz** [comment]
We'll test all of this extensively in Clang as we implement matrices there.
