### ISSUE TITLE
[HLSL] Feature Request: struct syntax for ByteAddressBuffers

### ISSUE THREAD

**Issue by procedural** [microsoft/DirectXShaderCompiler#1901]
Based on ideas and challenges of using ByteAddressBuffers described by Joshua Barczak in this blog post: http://www.joshbarczak.com/blog/?p=1260

If you want to interpret and read memory as a struct in HLSL, here is how you can do that today using typed buffers (SRV buffers or texel buffers):

```hlsl
tbuffer foo : register(t0) {
  float4 other_thing;
  float4x3 mBones[43];
};
 
float4 TBuffer(float3 P : pos, uint bone_idx : idx) : SV_POSITION {
  return mul(mBones[bone_idx], P); 
}
```

And here is (currently) the only way to read the same data using ByteAddressBuffer:

```hlsl
ByteAddressBuffer b : register(t0);
 
float4 ByteAddress(float3 P : pos, uint bone_idx : idx) : SV_POSITION {
  float4x3 mTransform = {
    asfloat(b.Load4(16 + 48 * bone_idx)),
    asfloat(b.Load4(32 + 48 * bone_idx)),
    asfloat(b.Load4(48 + 48 * bone_idx)),
  };
  return mul(mTransform, P);
}
```

There are many problems with loading dwords manually like this, here are a few major ones: it requires more code to type, if struct's layout changes all the offsets must be updated everywhere manually and the correctness of these offsets only depends on programmer's attention. If one offset is wrong, the whole code may read and operate on incorrect values and produce unexpected results. Finding wrong offsets is challenging in big codebases due to no visual correlation between offset numbers and struct members these offsets represent.

The proposed solution to these issues is to allow interpreting ByteAddressBuffers as structs, so the code could look and work like this:

```hlsl
ByteAddressBuffer b : register(t0) {
  float4 other_thing;
  float4x3 mBones[43];
};
 
float4 ByteAddress(float3 P : pos, uint bone_idx : idx) : SV_POSITION {
  return mul(mBones[bone_idx], P); 
}
```

Given ByteAddressBuffer's 4 byte alignment restriction, a compiler can throw errors if user will specify invalid struct layout or will try to use smaller than 4 byte types like 8-bit integers or 16-bit floats.

Any modifications or suggestions are welcome, this is just a proposal without strict syntax requirements.

**Comment by procedural** [comment]
Same question from 8 years ago: https://www.gamedev.net/forums/topic/614728-dx11-is-it-possible-to-34cast34-from-byte-address-buffer-to-a-structure-in-hlsl/

**Comment by procedural** [comment]
@sebbbi's proposal: https://twitter.com/SebAaltonen/status/1100811356431884294

**Comment by MrTrillian** [comment]
While we didn't implement the suggested syntax, I think your scenario is addressed by the new `ByteAddressBuffer.Load<T>/Store<T>` methods.

**Comment by procedural** [comment]
@MrTrillian Thank you so much!

**Comment by thatname** [comment]
@MrTrillian I think an optional offset may be added to Load<T>(), will increase usability of this feature.
consider the following GLSL shader:
```
GLSL
layout(std430, binding = 0) buffer SMyBuffer
{
    int header;
    float data[];
} MyBuffer;

void main()
{
   MyBuffer.data[100] = 0.0f;
}
```
The GLSL SSBO 'SMyBuffer' has a 'header' field, address of 'data' should be offseted by 4 bytes.
To archive the same effect with HLSL's ByteAddressBuffer.Load<T>(), there should be an optional offset parameter added to calculate the actual address.

**Comment by MrTrillian** [comment]
Hi @thatname , thanks for your suggestion but please @-mention a current member of the team for a response as I have moved to a different team.

**Comment by thatname** [comment]
> Hi @thatname , thanks for your suggestion but please @-mention a current member of the team for a response as I have moved to a different team.

OK, I will post a new issue.
