### ISSUE TITLE
Validator version needs option override for seperate validation scenario

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#1906]
Due to these facts:
1. Validator version metadata "!dx.valver" for DxilModule is initialized based on the version of the validator that will run after the compilation step.
2. When running without DXIL.dll present, this version will be the internal version (1.4 currently)
3. The validator fails if "!dx.valver" has major version != current major and minor > current minor.

Validation with DXIL.dll of a container compiled separately will fail unless DXIL.dll has a version equal or greater than the validator version from the DxCompiler.dll used to compile the shader.  This will happen in-between releases, when DxCompiler.dll built from GitHub source is newer than the current released SDK with DXIL.dll.

A workaround is to build custom version of DxCompiler that sets up a different minor validator version, such as `std::min((UINT)3, minorVer)` instead of `minorVer` here:
https://github.com/Microsoft/DirectXShaderCompiler/blob/27a7bf4b0b38d4e2ccc3be46459381cc6ef5dae6/tools/clang/tools/dxcompiler/dxcompilerobj.cpp#L477
Or, you can change the validator version after compilation and before validation, but that requires something to load/modify/store the module, and may not always work perfectly, since the validator version can have an impact on certain decisions the compiler makes for compatibility reasons.

The proper solution is to add a compilation option to override the validator version, so it may be set to the version of DXIL.dll that will be used later in a toolchain.  This should be used in DxcLinker as well.

Implementation guide, plus a couple fixes for issues I noticed along the way:
- Add option `-validator-version <Major>.<Minor>` to `include/dxc/Support/HLSLOptions.td`
  - `Group<hlslcomp_Group>, Flags<[CoreOption, DriverOption]>`
- Add option variables `unsigned long ValVerMajor, ValVerMinor` to `include/dxc/Support/HLSLOptions.h`.
  - Use `(uint32_t)-1` as default to signify no setting by user.
- Add parsing code to `lib/DxcSupport/HLSLOptions.cpp` to parse two uints separated by `.` and store into `ValVerMajor`, `ValVerMinor`.  Don't parse number as float.
  - If `ValVerMajor == 0` set `DisableValidation = true`
- Add override to `tools/clang/tools/dxcompiler/dxcompilerobj.cpp` in that same area to just set the version is specified on the command line, else do the existing if block that sets it based on `GetValidatorVersion`.
  - usage of `-validator-version` together with `-Vd` should still allow validator version to be set as requested, and validation to be skipped for this invocation of the compiler.
- Add support to DxilLinker/DxcLinker:
  - Create new `DxilLinkOpts` structure and copy options from `DxilLinker::Link` parameters to this structure.
  - Add `ValMajor` and `ValMinor` to link options, default to `(uint32_t)-1`: meaning use version from create method.
  - Add new method `DxilLinker::Link(const DxilLinkOpts& opts)`
  - `DxilLinkerImpl::Link`: Change old method to just wrap the new method
  - `DxilLinkerImpl`: Handle special case of `pSM->GetMinValidatorVersion` setting `minValMajor == 0`:
    - This should set the major/minor versions passed to `DxilLinkJob` to `0` to indicate shader model not fit for validation.
  - `DxcLinker`: Use new `Link` method, detecting new `DxcOpts` options and setting `DxilLinkOpts`
  - `DxcLinker`: Verify behavior for `-Vd` skips validation while still allowing version override options
  - `DxcLinker`: Fix validation skip for all lib_* targets!  Skip only on `DisableValidation`.
- Add unit test to `DxilModuleTest`, setting option to 1.3 (since current is 1.4) and verify `GetValidatorVersion` returns 1.3.  Also verify `-Vd` plus `-validator-version` scenario.
- Add unit test to `LinkerTest`

Note: If selected validator version is less than required by the chosen shader model, the validator version will be changed to the minimum required by the target during compilation.  If this is the case for `DxilLinker`, it will fail the `Link()`.

**Comment by gwihlidal** [comment]
Hi @tex3d - is there an update on getting such an option added officially to DXC? Because of just this one issue, we have a custom fork of DXC we've been keeping merged with master, and it would be nice to go back to pulling master directly.

**Comment by pow2clk** [comment]
Fixed!
