### ISSUE TITLE
#line directives seem to be completely ignored

### ISSUE THREAD

**Issue by Ashalah** [Microsoft/DirectXShaderCompiler#1922]
What the title says, I can't get them to have any effect on error reporting at all. I'm not using `-ignore-line-directives`

I've tried both of these forms:
`#line 1`
`#line 1 "C:/some/path.hlsl"`

I'm using the x64 version of dxc from the 10.0.17763.0 Windows SDK

**Comment by MrTrillian** [comment]
Thanks. This was found and fixed a few months back. You can either build the latest version from source or wait for the next official release.

**Comment by MrTrillian** [comment]
For reference: #1665

**Comment by Ashalah** [comment]
@MrTrillian thank you!
