### ISSUE TITLE
What is register 'i' ?

### ISSUE THREAD

**Issue by ehsannas** [Microsoft/DirectXShaderCompiler#1923]
According to the [reference](https://docs.microsoft.com/en-us/windows/desktop/direct3dhlsl/dx-graphics-hlsl-variable-register), the available register types are: b,t,c,s,u.

But the error message I get in DXC is:

`error: register type is unsupported - available types are 'b', 'c', 'i', 's', 't', 'u'`
Which comes from [here](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/include/clang/Basic/DiagnosticParseKinds.td#L1004)

I'm wondering if this is a mistake? if not, what is register `i` ?

Thanks

**Comment by tex3d** [comment]
'i' refers to a special DX9 constant register mapping for uniform loop boundaries.  It is ignored for DX10+ targets, but the compile will not fail if you use it.

In fact, 'b', 'c', and 'i' are all DX9 constant register bindings for bool, float, and int registers.  'b' has been reused for constant **buffer** bindings in DX10+, but in DX9, when placed on a global variable used in an if statement, it would direct uniform flow control with a constant bool register (in SM 2+).  'c' has carried forward in the most direct way from DX9 to DX10 by specifying a vector-aligned index into the constant buffer.  But 'i' doesn't have any active use in DX10+ shaders.

In DX9, you could use multiple register mappings on a single global variable.  For instance, if you used an int in two different ways, such as a for loop bound and in some numeric expression elsewhere.  In that case, it would use the value from the int 'i' register for the loop, and the value from the float 'c' register for the numeric expression.

**Comment by ehsannas** [comment]
Awesome. Thanks a lot for the explanation @tex3d !
