### ISSUE TITLE
Generate error for unsized arrays as function params

### ISSUE THREAD

**Issue by ehsannas** [microsoft/DirectXShaderCompiler#1938]
Hi,

I believe using unsized arrays as function parameter is illegal in HLSL. Example:
```hlsl
void foo(out uint value[]) {
  value[100] = 1;
}

float4 main() : SV_Position {
  uint Mem[2];
  foo(Mem);
  return float4(Mem[0], Mem[1], 0, 0);
}
```

FXC generates the following error:
```
error X3072: 'value': array dimensions of function parameters must be explicit
```

While DXC lets it through.

**Comment by MrTrillian** [comment]
We were talking about that in @tex3d 's pull request #1899 . I don't think it makes sense to have unsized arrays as parameters due to (intended but not currently correctly implemented) pass-by-value semantics, but Tex is the one to have looked into this and might have some more insights.

**Comment by tex3d** [comment]
And yet, it works with resources, but only on SM 5.1:
```
// fxc /T vs_5_1 /enable_unbounded_descriptor_tables
Buffer<uint> T2[2];
Buffer<uint> T[];

uint foo(Buffer<uint> t[]) {
  return t[0].Load(1);
}

float4 main() : SV_Position {
  return float4(foo(T), foo(T2), 0, 0);
}
```

We do have to sort out what should actually be supported here and whether we should deprecate cases fxc supports, such as this one.

**Comment by MrTrillian** [comment]
Another case of this issue was recently reported through an internal channel. Copying here for tracking.

> Currently this shader is allowed to compile with /Od even though the array argument is of unknown size. At higher optimisation levels the shader fails to compile but gives a strange error unrelated to the argument:

```
#define RootSig "RootFlags(0), UAV(u0)"
RWStructuredBuffer<uint> output;
uint SumArray(uint arraySize, uint array[])
{
    uint sum = 0;
    for(int i = 0; i < arraySize; i++)
    {
        sum += array[i];
    }
    return sum;
}

[RootSignature(RootSig)]
[numthreads(1,1,1)]
void main()
{
    uint array[3] = { 3, 5, 8 };
    output[0] = SumArray(3, array);
}
```

**Comment by pow2clk** [comment]
Godbolt link for original repro: https://godbolt.org/z/P5bMEreGr

and for the additional CS with -Od: https://godbolt.org/z/xfEPY49bx

**Comment by damyanp** [comment]
We're not planning on fixing this in DXC, although we are going to revisit the behavior of unbounded arrays in HLSL 202x (microsoft/hlsl-specs#141).
