### ISSUE TITLE
Crash compiling lib with recursive function in struct

### ISSUE THREAD

**Issue by simontaylor81** [Microsoft/DirectXShaderCompiler#1943]
Not the most critical bug this one, but might as well report it! I see a crash compiling a struct with a recursive member function. Obviously that's not allowed, but it didn't used to crash, and it doesn't crash building for PS, just lib. (Note that I found this in one of my weird-corner-case shaders designed to stress the compiler, not production code!)

Anyway, you should be able to repro by compiling the following with `-T lib_6_3 -exports main`:

```
struct S
{
	float func() { return func(); }
};

float main()
{
	S s;
	return s.func();
}
```

Tested at commit 32fe0936

**Comment by MrTrillian** [comment]
Thanks! It's good to get those issues reported, even with illegal code.

**Comment by MrTrillian** [comment]
This stopped repro'ing in a build not much more recent than the one you tried it on. I'm not sure exactly which change fixed it. I will submit a test and close as no repro.
