### ISSUE TITLE
Updated AMD,NV,Intel drivers info?

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectXShaderCompiler#195]
Hi,
both AMD and Nvidia released new branch drivers..
NV 381 drivers: support DXIL 1.0 instead of 0.7?
AMD 17.4.1 (17.10 branch) have "A later driver should have fixes for the wave routines"?

also installed recent Intel drivers on HD530 and no one has Shader Model 6.0 (DXIL) support and WDDM2.2..
can post info about Intel GPU drivers with DXIL support? coming soon?

Thanks..

**Comment by jholewinski** [comment]
The NV r381 driver branch supports DXIL 1.0, yes. We'll update the driver info here.

**Comment by marcelolr** [comment]
We've moved to updating regularly on the main README.md file. Intel info is up there now. Thanks!
