### ISSUE TITLE
DXC doesn't implement FXC's lvalue flat cast semantics

### ISSUE THREAD

**Issue by MrTrillian** [microsoft/DirectXShaderCompiler#1963]
I spent some time looking into the madness that are FXC's flat casting semantics and my conclusions is that the following flat cast scenarios are valid LValues for FXC (you can assign them, use as `out` params, etc):

- Any elementwise-matching pair of vector/matrix/array/structure types: `((int2[2])myint2x2)[0] = 42;`
- Truncation casts: `((int2)i4).x = 42;`
- Extending casts??? - this is getting really messed up: `((int4)myint).zy = int2(1, 2);` (semantics: assigns `2` ???)
- Vector/Matrix to array (but not struct) with numerical conversions and potential truncation/extension = oh, the humanity: `((float[2])myint4)[1] = 1.5f;` (assigns `myint4.y = 1`)

**Comment by pow2clk** [comment]
There is insufficient interest in bringing forward the madness of FXC into the modern era since no one has clamored for this. Won't fix.
