### ISSUE TITLE
[SPIRV] Invalid composite constants in some cases

### ISSUE THREAD

**Issue by TiemoJung** [Microsoft/DirectXShaderCompiler#1980]
Hi,

in some cases the spir-v output produces invalid OpConstantComposite commands.
See this spir-v snipped:
```
%float = OpTypeFloat 32
...
%v3float = OpTypeVector %float 3
....
%double = OpTypeFloat 64
%double_0_5 = OpConstant %double 0.5
%120 = OpConstantComposite %v3float %double_0_5 %double_0_5 %double_0_5
%double_0 = OpConstant %double 0
%122 = OpConstantComposite %v3float %double_0 %double_0 %double_0
....
%747 = OpSelect %v3float %746 %120 %122
```
The example shows that each time a double is used to create a float vector constant, wich is invalid.

I was not yet able to nail it down, but it seems the root cause of this might be something like this:
```
void a_function(float3 in);
...
a_function(a_test ? 0.5 : 0);
```

**Comment by ehsannas** [comment]
Thanks for reporting. Are you using a build that contains the fix for PR #1934 ?

You can find out the hash commit that was used to build your DXC executable by running 
`dxc.exe -help`.

You'll see something like:
**Version: dxcompiler.dll: 1.4(dev;1976-7f7a2f1c)**

The hash commit in this case would be **7f7a2f1c**.

Would you be able to provide a shader to reproduce the issue?
Thanks.

**Comment by TiemoJung** [comment]
Hi,

i tested it with  1.4(dev;1980-e58ecd4c) -> e58ecd4c2f04fb8457693676c05e75545b06d226

I am working on getting a minimal code to reproduce this behavior.

**Comment by ehsannas** [comment]
Thank you

**Comment by TiemoJung** [comment]
Hi,

this seems to trigger this (tested with 05ba6aa8f9f08845d342ad8e7ccf061fae37425f):
```
float func(float3 i) { return i.x; }
float4 main(float1 i : TEXCOORD0) : SV_Target {
  return func((float3(1,2,3) * i) > 0 ? 0.5 : 0);
}
```

Also if you change
`func((float3(1,2,3) * i) > 0 ? 0.5 : 0);`

to 
`func(float3(1,2,3) * (i > 0 ? 0.5 : 0));`

Then it produces an invalid vector times scalar (float vec times double scalar).

**Comment by ehsannas** [comment]
Thanks @TiemoJung ! We will work on a fix.
