### ISSUE TITLE
[SPIRV] Unused literal values turns 64 bit types on

### ISSUE THREAD

**Issue by TiemoJung** [Microsoft/DirectXShaderCompiler#1982]
Hi,

consider this example:

```
float4 main() : SV_Target {
0; // creates 64 bit int constant
0.0; // creates 64 bit float constant
return 0;
}
```

Regardless of optimization level 64 bit types are always turned on in the resulting spirv.

Tested with e58ecd4c2f04fb8457693676c05e75545b06d226

**Comment by ehsannas** [comment]
Thanks for reporting.
