### ISSUE TITLE
[SPIRV] Codegen with 16 bit floats results in odd and invalid spirv

### ISSUE THREAD

**Issue by TiemoJung** [microsoft/DirectXShaderCompiler#1996]
Hi,

we started some experimenting with 16 bit float support turned on and found some issues:
* Never enables Float16 cap, instead SPV_AMD_gpu_shader_half_float is enabled, which is incorrect:
  * fp16 cap has to be turned on to be able to create fp16 types
  * SPV_AMD_gpu_shader_half_float  extends GLSLstd450 to be used with fp16 types (since rev3 of GLSLstd450 fp16 is allowed too, so ext is obsolete?)
* Odd constructs like `load a fp32, convert it to fp16, compose vector with fp16, convert to fp32 vector, do something with the fp32 vector` instead of just `load a fp32, compose vector with fp32, doe something with fp32 vector`

**Comment by ehsannas** [comment]
The first point has already been fixed.
We can only address the second point with a sample shader. Please reopen the issue with an example shader if possible. Thanks!
