### ISSUE TITLE
DXC doesn't allow duplicate SV_VertexID shader inputs

### ISSUE THREAD

**Issue by MrTrillian** [microsoft/DirectXShaderCompiler#1999]
Repro: `uint main(uint a : SV_VertexID, uint b : SV_VertexID) : OUT { return a + b; }`
DXC: `error: Parameter with semantic SV_VertexID has overlapping semantic index at 0`
FXC: 
```
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_input_sgv v0.x, vertex_id
dcl_output o0.x
ishl o0.x, v0.x, l(1)
ret
```

**Comment by tex3d** [comment]
This is by design for DXC.
