### ISSUE TITLE
Unbound arrays inside structures

### ISSUE THREAD

**Issue by tiago-rodrigues** [microsoft/DirectXShaderCompiler#2015]
Hi,

in order to support our shader parameters system with the same interface across all platforms, we have the need to have unbound arrays inside structures, like in the following example:

```
// testbindless.hlsl
#define BindlessLayout_RootSignatureString "RootFlags(0),"\
"DescriptorTable("\
"SRV(t0, space=0, numDescriptors = unbounded, offset = 0),"\
"visibility = SHADER_VISIBILITY_ALL),"

Texture2D<float4> TestBindlessTable_tex2ds[] : register(t0 , space0 ); 

struct TestBindlessTable
{
    Texture2D<float4> tex2ds[];
    Texture2D<float4> GetTex2dsAt(uint index) { return tex2ds[index]; }
};

TestBindlessTable CreateTestBindlessTable()
{
    TestBindlessTable instance;
    instance.tex2ds = TestBindlessTable_tex2ds;
    return instance;
}
static const TestBindlessTable g_Test = CreateTestBindlessTable();

[ RootSignature ( BindlessLayout_RootSignatureString ) ]
float4 main() : SV_TARGET
{	
    return g_Test.GetTex2dsAt(100)[float2(0.0f, 0.0f)];
}
```
[compile with: dxc.exe /enable_unbounded_descriptor_tables -Fo test_dxc.dxbc -E main -T ps_6_0 testbindless.hlsl]

Right now we get "error: array dimensions of struct/class members must be explicit".
FXC appeared to support the unbound array syntax, however internally it would store arrays[1] and issued an error when indexing above 0.

thanks,
Tiago

**Comment by MrTrillian** [comment]
Hi Tiago,

We're giving boundless resource arrays some thinking, but there are complications with them. Mostly, HLSL has copy in/copy out semantics for calls, and we can't copy an unbounded array. Thanks for sharing your scenario.

**Comment by pow2clk** [comment]
Won't fix. So sorry.
