### ISSUE TITLE
static const causes compiler infinite loop

### ISSUE THREAD

**Issue by tiago-rodrigues** [Microsoft/DirectXShaderCompiler#2016]
Hi,

The following code produces an infinite loop in the compiler:

```
Texture2D<float4> bindless_tex2ds[] : register(t0 , space0 ); 
static const Texture2D<float4> alias_tex2ds[] = bindless_tex2ds;

[ RootSignature ( "RootFlags(0),DescriptorTable(SRV(t0, space=0, numDescriptors = unbounded, offset = 0),visibility = SHADER_VISIBILITY_ALL)" ) ]
float4 main() : SV_TARGET
{	
    return alias_tex2ds[0][float2(0, 0)];
}
```
Removing the 'const' from 'alias_tex2ds' makes the problem go away.

thanks,
Tiago

**Comment by MrTrillian** [comment]
Thanks for reporting! I could reproduce the bug with older versions of the compiler, but it is fixed in more recent builds from the master branch.
