### ISSUE TITLE
Write to function returned, temporay UAV header

### ISSUE THREAD

**Issue by tiago-rodrigues** [microsoft/DirectXShaderCompiler#2017]
Hi,

would it be possible to be able to write to UAV memory through temporary RW Objects returned from functions? The returned header might be const temporary object, but the UAV memory that it points to isn't.
For example:

```
RWBuffer<uint> global_uav : register(u0 , space0 ); 
RWBuffer<uint> GetUAV()
{
    return global_uav;
}

[ RootSignature ( "RootFlags(0),DescriptorTable(UAV(u0, space=0, numDescriptors = 1),visibility = SHADER_VISIBILITY_ALL)" ) ]
[numthreads(1,1,1)]
void main()
{	
    // error: expression is not assignable
    GetUAV()[0] = 1;

    // works
    const RWBuffer<uint> tex = GetUAV();
    tex[0] = 1;  
}
```

Thanks,
Tiago

**Comment by MrTrillian** [comment]
Thanks for reporting. This is probably a consequence of the fact that the same code with a normal array wouldn't make sense.

**Comment by pow2clk** [comment]
We are triaging older bugs and we've decided to won't fix this. Let us know on this and the others if it is urgent.
