### ISSUE TITLE
[SPIRV] StructuredBuffer<int3>[] is broken

### ISSUE THREAD

**Issue by Jasper-Bekkers** [Microsoft/DirectXShaderCompiler#2022]
I think this may be an issue with the SPIR-V spec, but since it's allowed in HLSL I think in part this belongs here:

I'm trying to access an index buffer in a bindless way:
`StructuredBuffer<uint3> g_indices[] : register(t0, space1);`

However this generates the following error message:

> fatal error: generated SPIR-V is invalid: Structure id 9 decorated as BufferBlock for variable in Uniform storage class must follow relaxed storage buffer layout rules: member 0 contains an array with stride 12 not satisfying alignment to 16 `
> %type_StructuredBuffer_v3uint = OpTypeStruct %_runtimearr_v3uint` 
> note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible

Obviously changing it to `uint4` and padding the index buffer works around this for now.

**Comment by ehsannas** [comment]
Thanks for reporting @Jasper-Bekkers

**Comment by ehsannas** [comment]
Hi @Jasper-Bekkers 

If you compile using `-fvk-use-dx-layout`, you'll get ArrayStride of 12 without a compilation error. Is this what you want? 
Please take a look at the documentation about [memory layout rules](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#memory-layout-rules).
Let me know if I've misunderstood the issue.
Thanks!

**Comment by Jasper-Bekkers** [comment]
Thanks! That seems to have worked.
