### ISSUE TITLE
Type cast error in Debug mode

### ISSUE THREAD

**Issue by jaebaek** [microsoft/DirectXShaderCompiler#2031]
The following code showed an error in Debug mode:

```
// Run: %dxc -T cs_6_0 -E main

struct foo {
  int elem_int;
};

#if 1
ConsumeStructuredBuffer<foo> bar;

void main() {
  float baz = bar.Consume().elem_int; // Error
}
#else
ConsumeStructuredBuffer<int> bar;

void main() {
  float baz = bar.Consume(); // Ok
}
#endif
```

It said
```
can't implicitly cast lvalue to rvalue with this cast kind
UNREACHABLE executed at ../../tools/clang/lib/Sema/Sema.cpp:351!
```

The error is from
https://github.com/Microsoft/DirectXShaderCompiler/blob/8501710c9f32193d3ad2b7b723de644dfcb7cea5/tools/clang/lib/Sema/Sema.cpp#L346-L360

**Comment by MrTrillian** [comment]
Thanks for reporting. We have a number of LValue/RValue-related issues we want to look into, I'll add this to the list.

**Comment by pow2clk** [comment]
No longer repros. Fixed!
