### ISSUE TITLE
generic vector and matrix underspecified

### ISSUE THREAD

**Issue by siliconvoodoo** [microsoft/DirectXShaderCompiler#2034]
This is not necessarily a bug. Just the doc doesn't say why these expressions are allowed, so we don't know what they do:

`vector v;`
that stuff builds on both DXC and FXC. Please write clearly in the doc what this is.

`matrix m;`
same.

`vector<half> v;`
This builds in DXC, but it was not building in FXC. Clear spec required.
According to:
https://docs.microsoft.com/en-us/windows/desktop/direct3dhlsl/dx-graphics-hlsl-vector
This is not supposed to be legal.

`matrix<half> m;`
Same, refused by FXC but ok for DXC. What is this ? according to tests it appears to be a full 4x4 matrix.

`matrix<half, 3> m;`
This appears to be a matrix of 3 rows and 4 columns. why ? why not square ?
FXC refuses this.

bests.

**Comment by MrTrillian** [comment]
The docs are indeed lackluster here. Informally you can understand the behavior of DXC as:
```
template<typename T = float, int R = 4, int C = 4> class matrix {};
template<typename T = float, int E = 4> class vector {};
```
So anything not filled out gets the default values.

**Comment by siliconvoodoo** [comment]
I'm good as long as somehow people google-ing this behavior can end up here...

**Comment by pow2clk** [comment]
Fixed by https://github.com/MicrosoftDocs/win32/pull/1878
