### ISSUE TITLE
[spirv] Crash on some implicit type conversion copies

### ISSUE THREAD

**Issue by TiemoJung** [Microsoft/DirectXShaderCompiler#2035]
Hi,

in HLSL types with the same format layout can be converted implicitly, even for complex types like structs.
The spirv target crashes for such copies of structure types. Consider this:

```
struct FirstStruct
{
float3 anArray[4];
};
struct SecondStruct
{
float3 anArray[4];
};

RWStructuredBuffer<FirstStruct> rwBuf : register(u0);
[ numthreads ( 16 , 16 , 1 ) ]
void compute_kernel()
{
  SecondStruct values;
  for (int i = 0; i < 4; ++i)
    values.anArray[i] = i;
  rwBuf[0] = values; // crashes compiler with spirv target - fine with dxil
}
```
Tested with 4e9a01f6315cc4b0318702d0b2feff7cc4c3eb37

**Comment by ehsannas** [comment]
Thanks for reporting @TiemoJung . We'll investigate immediately.
