### ISSUE TITLE
[spirv] Invalid spirv for certain lvalue constructs

### ISSUE THREAD

**Issue by TiemoJung** [Microsoft/DirectXShaderCompiler#2036]
Hi,

consider this shader:

```
RWStructuredBuffer<float4> buf : register(u0);

[ numthreads ( 1, 1 , 1 ) ]
void compute_kernel()
{
   float4 value(1,2,3,4);
   (value.xy).x = 5; // triggers invalid spir-v - but is valid HLSL
  buf = value;
}
```
First it composite extracts x from value then it tries to store to that float object.

Tested with 52c6c0f668617b3f51529d3bc4cd6ca834e0f040

**Comment by ehsannas** [comment]
Thanks for reporting @TiemoJung

**Comment by ehsannas** [comment]
Use 
```hlsl
RWStructuredBuffer<float4> buf : register(u0);

[ numthreads ( 1, 1 , 1 ) ]
void main()
{
  float4 value;
  (value.xy).x = 5; // triggers invalid spir-v - but is valid HLSL
}
```
to reproduce.

**Comment by ehsannas** [comment]
hmm... I wonder if `(value.xy)` is considered a temporary or not. Meaning, I wonder whether `(1,2,3,4)` will be written to buf, or `(5,2,3,4)`.

**Comment by ehsannas** [comment]
Also seems like we handle `value.xy.x = 5;` properly.

**Comment by ehsannas** [comment]
Verified that the DX side doesn't consider `(value.xy)` a temporary. So, the expected output is `(5,2,3,4)`.
