### ISSUE TITLE
[spirv] invalid spirv "Expected input to have different bit width from Result Type: SConvert"

### ISSUE THREAD

**Issue by xxxbxxx** [Microsoft/DirectXShaderCompiler#2045]
hello,

this hlsl code fails with:
```
fatal error: generated SPIR-V is invalid: Expected input to have different bit width from Result Type: SConvert
  %17 = OpSConvert %v4int %15
```

```hlsl
struct PS_INPUT	{
	float4 RasterPos	: SV_Position;
};
struct PS_OUTPUT		{
	float4 Color0		: SV_Target0;
};

PS_OUTPUT main(PS_INPUT v)
{
//	PS_OUTPUT	Output = { float4(0,0,0,0) };		// WORKS
//	PS_OUTPUT	Output; Output.Color0 = (0).xxxx;	// WORKS
	PS_OUTPUT	Output = { (0).xxxx };				// FAILS
    return Output;
}
```

looks very much like #2036 " [spirv] Invalid spirv for certain lvalue constructs"
but it looks like a rvalue more than a lvalue.

**Comment by xxxbxxx** [comment]
bisected to:

f9fc460a54db55365695ddbfdaad19431617a1bb is the first bad commit
commit f9fc460a54db55365695ddbfdaad19431617a1bb
Author: Ehsan <ehsann@google.com>
Date:   Wed Mar 6 16:48:48 2019 -0500

    [spirv] Fix handling of literals for constants. (#2000)

**Comment by ehsannas** [comment]
Thanks for reporting @xxxbxxx ! Will take a look.

**Comment by foofur** [comment]
Good found @xxxbxxx,

@ehsannas I'm suffering from same issue.

**Comment by ehsannas** [comment]
This is not related to #2036 .

**Comment by ehsannas** [comment]
Fix pull-request posted for review.

**Comment by foofur** [comment]
Thanks work like a charm.

**Comment by ehsannas** [comment]
Awesome!
