### ISSUE TITLE
[SPIR-V] [Android] Separate texture/sampler not working

### ISSUE THREAD

**Issue by akioCL** [microsoft/DirectXShaderCompiler#2049]
I tried running the following simple shader that just samples a texture on a Pixel device but I I'm getting black returned.

```
struct VSInput
{
     float4 m_position : POSITION;
     float2 m_uv : UV0;
};

struct VSOutput
{
     float4 m_position : SV_Position;
     float2 m_uv : UV0;
};

struct PSOutput
{
     float4 m_color : SV_Target0;
};

Texture2D<float4>  TexturePerInstance__m_albedoMap : register(t0, space0);
SamplerState  TexturePerInstance__m_sampler : register(s0, space0);

VSOutput MainVS(VSInput vsInput)
{
    VSOutput OUT;
    OUT.m_position = vsInput.m_position;
    OUT.m_uv = vsInput.m_uv;
    return OUT;
}

PSOutput MainPS(VSOutput psInput)
{
    PSOutput OUT;
    float3 albedo = TexturePerInstance__m_albedoMap.Sample(TexturePerInstance__m_sampler, psInput.m_uv).rgb;
    OUT.m_color = float4(albedo, 1.0);
    return OUT;
}
```

I'm using the following command line to compile:
```
$ .\dxc.exe -T vs_6_2 -spirv -Zpr -fvk-invert-y -fvk-s-shift 1 all -E MainVS -Fo c:/temp/vert.spirv c:/temp/shader.hlsl
 .\dxc.exe -T ps_6_2 -spirv -Zpr -fvk-s-shift 1 all -E MainPS -Fo c:/temp/ps.spirv c:/temp/shader.hlsl
```

If I compile the same shaders with glslang I have no problem sampling the texture.
The device I'm running is a Pixel 3 running Android 9, Build Number PQ2A.190305.002

Is there an argument that maybe I'm missing when compiling with DXC?

**Comment by jaebaek** [comment]
Could you please share the sample app you used, if possible?

**Comment by tim4864** [comment]
Same problem on Nexus 6P.
The texture could not be sampled correctly on Android but rendered very well on PC.
If you use RenderDoc to see what happened,
an error of "Invalid Image View Object 0xffffffff" from vk_core would be warned every frame update.

**Comment by tim4864** [comment]
@akioCL 
Not sure if the above solve the problem you met,
but according to [https://github.com/Microsoft/DirectXShaderCompiler/issues/1460]
I solved the problem by applying the older version of DXC, which will generate OpTypeImage depth value with 0 or 1, to get well-rendered result on Nexus 6P.

**Comment by ehsannas** [comment]
Thanks for sharing your experience @tim4864 . I suspect @akioCL is having the same problem.

As pointer out in issue #1460  this is a driver bug, not a DXC bug, so we will not modify DXC's behavior.

**Comment by akioCL** [comment]
Sorry for the late response. Thanks @tim4864 . You were right, the problem was related to the depth hint for the OpImageType. I forced DXC to generate all OpImageType with a depth hint of 0 and it fixed the issue.
