### ISSUE TITLE
[SPIRV] Ray tracing shader profiles

### ISSUE THREAD

**Issue by Cry-Mory** [Microsoft/DirectXShaderCompiler#2056]
Hey Guys,

I am having troubles to understand how should I compile DXR HLSL shaders to SPIR-V. I don't find the profiles for different shader types that are needed for ray tracing. Are we supposed to do it with lib_6_x profiles?

**Comment by ehsannas** [comment]
Please see the documentation [here](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#raytracing-shader-stages).
There are also sample shaders used in our tests:
[raytracing.nv.anyhit.hlsl](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/test/CodeGenSPIRV/raytracing.nv.anyhit.hlsl)
[raytracing.nv.callable.hlsl](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/test/CodeGenSPIRV/raytracing.nv.callable.hlsl)
[raytracing.nv.closesthit.hlsl](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/test/CodeGenSPIRV/raytracing.nv.closesthit.hlsl)
[raytracing.nv.intersection.hlsl](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/test/CodeGenSPIRV/raytracing.nv.intersection.hlsl)
[raytracing.nv.miss.hlsl](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/test/CodeGenSPIRV/raytracing.nv.miss.hlsl)
[raytracing.nv.raygen.hlsl](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/test/CodeGenSPIRV/raytracing.nv.raygen.hlsl)
[raytracing.nv.library.hlsl](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/test/CodeGenSPIRV/raytracing.nv.library.hlsl) --> Notice that this one includes shaders for different raytracing stages.

Notice the use of `-T lib_6_3`
