### ISSUE TITLE
Dxil Validation Error: Rows for system value semantic SV_ClipDistance must be 1

### ISSUE THREAD

**Issue by vcsharma** [microsoft/DirectXShaderCompiler#2057]
This was found by @jpporto . Reporting on his behalf. One of our internal test captures failing due to this bug.

--

This is a minified HLSL that repros the failure:
struct VS_OUTPUT {
    float4 clips[2] : SV_ClipDistance;
};

VS_OUTPUT main() {
    return (VS_OUTPUT) 0;
}

Compiling with dxc, we have:
dxc d:\temp\clip.hlsl /Tvs_6_0 /Fo d:\temp\clip.hlsl.dxbc
error: validation errors
rows for system value semantic SV_ClipDistance must be 1

Validation failed.

Fxc happily compiles it:
fxc d:\temp\clip.hlsl /Tvs_5_0 /Fo d:\temp\clip.hlsl.dxbc
Microsoft (R) Direct3D Shader Compiler 10.1 (using C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\x64\D3DCOMPILER_47.dll)
Copyright (C) 2013 Microsoft. All rights reserved.

compilation object save succeeded; see d:\temp\clip.hlsl.dxbc

**Comment by hekota** [comment]
According to @tex3d this is fixed. Tex- please reactivate if not.

**Comment by vcsharma** [comment]
Yup, it compiles now.
