### ISSUE TITLE
[DXIL] Automatic resource binding with only spaceN specified for conditional compilation

### ISSUE THREAD

**Issue by obhi-d** [microsoft/DirectXShaderCompiler#2059]
Hello,

I would like to use the DXC reflection layer to obtain the descriptor binding assignment (by not manually assigning them in the shader), so that conditional compilation can eliminate dead resource bindings.
My use case is as follows:
```hlsl
#ifdef _RESOURCE_REQUIRED
Texture2D MyTexture : register(space0);
#else
cbuffer ColorCB : register(space0) {
  float4 MyColor ;
};
#endif

```
My intention is not to specify the binding (register(b0) or register(t0)), but provide the spaceN number so that at-least on the engine level on the Vulkan side, I would need to bind an unchanging (or depending upon the frequency of change) descriptor set once for a frame. More precisely I am reserving slots (N) depending upon the frequency of change of resources (where the layout is matching), and use the reflection layer to get the individual resource binding slots.

The code example actually compiles fine if I use DXC with SPIRV codegen, and the generated assembly is also valid. However, this does not compile fine with DXC and DXIL code gen.
I have also tried with glslang and it throws an error on the register keyword usage.
So for me the grammar I am using is incorrect, although it works for DXC-SPIRV.

With glsl, I can do something like layout(set = N), and let the binding be specified automatically.
Would it be possible to provide this mechanism using a vulkan annotation? Something like:
`[[vk::binding_set(N)]] Texture2D MyTexture`

Thanks for any help.

**Comment by ehsannas** [comment]
Thanks for reporting @obhi-d 

Let me take a closer look, and I'll give an update. Thanks!

**Comment by ehsannas** [comment]
I'm glad to hear that the DXC-SPIRV flow works as expected.

I think it'd be best to avoid adding more `[[vk::]]` attributes as much as possible, especially if we can get equivalent behavior in DXIL (having a unified frontend and implementation for both backends).

@tex3d Would it be possible for you to add the implementation for the DXIL backend?
(the support for the frontend and the SPIR-V backend were added via https://github.com/Microsoft/DirectXShaderCompiler/pull/1503)

Thanks!

**Comment by obhi-d** [comment]
Thank you for the response, much appreciated.

**Comment by thatname** [comment]
It's useful to group global variables by space registers.
Consider two global variables with different update frequency:
```
//Global scope
float3 sunColor : register(space0);
float4 materialColor : register(space1);//This variable changes more often.
```
DXC puts both variables in the global cbuffer in space0. But the second variable is updated more often than the first variable. Generating global cbuffer for each space is more reasonable.

**Comment by obhi-d** [comment]
> It's useful to group global variables by space registers.
> Consider two global variables with different update frequency:
> 
> ```
> //Global scope
> float3 sunColor : register(space0);
> float4 materialColor : register(space1);//This variable changes more often.
> ```
> DXC puts both variables in the global cbuffer in space0. But the second variable is updated more often than the first variable. Generating global cbuffer for each space is more reasonable.

Of-course, my question (and as answered by @ehsannas that this support was added via issue: #1503 for SPIRV codegen) was if:
`float3 sunColor : register(space0);`
is valid grammar . It appears to be incorrect with DXIL codegen, but hopefully will be supported in the future :)

**Comment by ehsannas** [comment]
Awesome! Thanks for implementing this feature 👍
