### ISSUE TITLE
InterlockedAdd for 64bit integer

### ISSUE THREAD

**Issue by jaebaek** [microsoft/DirectXShaderCompiler#2067]
I am curious whether HLSL will support atomic operations for 64bit integer or not.

It seems that [InterlockedAdd](https://docs.microsoft.com/en-us/windows/desktop/direct3dhlsl/interlockedadd) does not have specific parameter types but when I tested the following code with `-T cs_6_0 -E main -fcgl` option

```
groupshared int64_t dest;

void main()
{
    int64_t delta;
    int64_t original_dest;
    InterlockedAdd(dest, delta, original_dest);
}
```

It generates type casting all of `dest, delta, original_dest` to 32 bit integers before calling `InterlockedAdd()`.

Is there any plan to make HLSL support atomic operations for 64bit integers?

Vulkan enabled it as described [here](https://github.com/KhronosGroup/Vulkan-Docs/issues/796) and the following two issues suggest supporting it in HLSL:

- GLSLang: KhronosGroup/glslang#1562
- DXC: Microsoft/DirectXShaderCompiler#1653

**Comment by MrTrillian** [comment]
@tex3d might know better. I did try this and found out that we crash during codegen, at least in debug builds, in non-int cases. Filed #2077.

**Comment by pow2clk** [comment]
Completed as part of Shader Model 6.6 #3293
