### ISSUE TITLE
Precise keyword has no effect on static variables

### ISSUE THREAD

**Issue by tristanlabelle** [microsoft/DirectXShaderCompiler#2078]
Repro:
```
static precise float g;
float main(float i : IN) : OUT {
    g = i;
    return g * g;
}
```
DXC output:
```
  %0 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 0, i32 undef)
  %mul = fmul fast float %0, %0
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 0, float %mul)
  ret void
```
FXC output:
```
dcl_input v0.x
dcl_output o0.x
mul [precise(x)] o0.x, v0.x, v0.x
ret
```
This might have to do with LLVM 3.7's lack of metadata support for global variables.

**Comment by llvm-beanz** [comment]
It is unclear to me whether FXC or DXC does the right thing here. If HLSL's `precise` matches GLSL, DXC is doing the right thing and FXC is not.

We're not going to change this behavior in DXC, but we'll fully specify `precise` for implementation in Clang when we get there.

**Comment by pow2clk** [comment]
Existing XFAIL test: https://github.com/microsoft/DirectXShaderCompiler/blob/main/tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/precise/static_variable.hlsl
