### ISSUE TITLE
"should not read uninitialized value" validation error when unrolling loops

### ISSUE THREAD

**Issue by TheRealMJP** [Microsoft/DirectXShaderCompiler#2098]
Hey everyone,

Earlier today I re-compiled DXC from source (#2088 from the master branch) to use in our engine, and a few shader that previously compiled without error now fail due to validation errors. This is the output that I get when compiling:

```
D:\Dev\DXC_Build\Release\bin>dxc -T cs_6_0 -E CSMain D:\Temp\DXC\unroll_uninitialized.hlsl
warning: DXIL.dll not found.  Resulting DXIL will not be signed for use in release environments.

error: validation errors
at 0x2c9a7bcdea8 inside block .preheader.33 of function CSMain Instructions should not read uninitialized value
at 0x2c9a7bcda28 inside block .preheader.26 of function CSMain Instructions should not read uninitialized value
at 0x2c9a7bce148 inside block .preheader.40.preheader of function CSMain Instructions should not read uninitialized value
at 0x2c9a7bcdba8 inside block .loopexit4456 of function CSMain Instructions should not read uninitialized value

Validation failed.
```

I don't think there are any uninitialized variables being read from in these cases, and if there are it doesn't seem obvious how to correlate the error message back to the code that caused it. I was able to trim down one of the shaders to a much simpler form that still produces the validation errors, which I've attached below:

[unroll_uninitialized.hlsl.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/3035926/unroll_uninitialized.hlsl.txt)

You can compile it yourself with the following command line:

`dxc -T cs_6_0 -E CSMain unroll_uninitialized.hlsl`

The validation error doesn't happen if I remove the unroll attributes or disable optimizations, which makes me a bit suspicious. Either way if someone could help me figure it if this is a compiler bug or an issue in our code, I would really appreciate it!

-Matt

**Comment by MrTrillian** [comment]
Hi Matt! Thanks for reporting! I was able to further reduce your repro and find out that our loop unrolling pass is introducing undefined values in this case. We'll look into it!

```
float bilinearWeights;
float2 main() : OUT {
    float2 output = 0.0f;
    for(uint sampleIdx = 0; sampleIdx < 1; ++sampleIdx) {
        float totalWeight = 0.0f;

        [unroll]
        for(uint i = 0; i < 1; ++i) {
            totalWeight += bilinearWeights;
        }

        float2 occlusion = 1.0f;
        if(totalWeight > 0.0f)
            occlusion = 1 / totalWeight;

        output += occlusion;
    }

    return output;
}
```

**Comment by zigguratvertigo** [comment]
We've also hit this one internally as well. Looking forward to the fix!

**Comment by MrTrillian** [comment]
This has been fixed for a little while now.
