### ISSUE TITLE
DXC allows assigning a Buffer<snorm float> to a Buffer<unorm float>

### ISSUE THREAD

**Issue by tristanlabelle** [microsoft/DirectXShaderCompiler#2106]
This operation is not well-defined since the snorm/unorm metadata is associated with the resource handle rather than with the load operations.

Repro:
```
Buffer<snorm float> buf_snorm;
float main() : OUT
{
  Buffer<unorm float> buf_unorm = buf_snorm;
  return buf_unorm.Load(0);
}
```
FXC output: `error X3017: cannot implicitly convert from 'const Buffer<snorm float>' to 'Buffer<unorm float>'`

**Comment by llvm-beanz** [comment]
This is clearly a bug in DXC, however we're unlikely to fix it in DXC so we're going to close it. We'll get this behavior right when we implement it in Clang.

**Comment by pow2clk** [comment]
Existing XFAIL test: https://github.com/microsoft/DirectXShaderCompiler/blob/main/tools/clang/test/HLSLFileCheck/hlsl/types/modifiers/unorm_snorm/assign_different_error.hlsl
