### ISSUE TITLE
[SPIRV] Feature Request: Ability to set binding/set for implicit global uniform buffer

### ISSUE THREAD

**Issue by TiemoJung** [Microsoft/DirectXShaderCompiler#2110]
Hi,

is it possible to add a option to control on which set and binding pair the implicitly created globals uniform buffer is set to?

I could not find any way to do this right now, glslang has `[[vk::global_cbuffer_binding]]` but it seems DXC has not.

It would also be nice to have a command line option to do the same thing, so we do not need to insert this into the source before passing it to DXC.

Right now without this we need to inspect all uniform buffers in a shader and check if they are named `$Globals` to ensure it is bound to the expected location (most of the time it is set to slot 0 but sometimes not and then things start to break apart)

**Comment by ehsannas** [comment]
Thanks for sharing @TiemoJung 

I see that glslang has `[[vk::global_cbuffer_binding]]`, but we are reluctant to add that to DXC. It is not clear which global variable this should be applied to, what should be done if it is applied more than once with different values, and it becomes more complicated if a shader does `#include` of other shaders.

I think a command line option makes much more sense.

**Comment by thatname** [comment]
It's useful to generate multiple global constant buffer.
If DXC do so, we can group global variables by space registers.
Consider two global variables with different update frequency:

```
//Global scope
float3 sunColor : register(space0);
float4 materialColor : register(space1);//This variable changes more often.

```
DXC ignores specified register space for global variables, it put both variables in the global cbuffer in space0. But the second variable is updated more often than the first variable. Generating global cbuffer for each space is more reasonable.

**Comment by ehsannas** [comment]
Hi @thatname, We strive to keep the SPIR-V backend behavior consistent with the DXC/DXIL behavior - which groups all globals into the one `$Globals` cbuffer. Therefore, we're not going to create a separate global cbuffer per `space` in the SPIR-V backend unless this is a feature supported by DXC/DXIL.

**Comment by ehsannas** [comment]
@TiemoJung I've put up a PR to add a command line option for setting descriptor set and binding for `$Globals`

**Comment by TiemoJung** [comment]
@ehsannas Works nicely and exactly what we need.

**Comment by tomjohnstone** [comment]
> @TiemoJung I've put up a PR to add a command line option for setting descriptor set and binding for `$Globals`

What is the recommended way of doing this in DXC?

Thanks.
