### ISSUE TITLE
HLModule/DxilModule don't correctly track patch constant functions

### ISSUE THREAD

**Issue by tristanlabelle** [microsoft/DirectXShaderCompiler#2115]
These classes use a set of functions to identify patch constant functions, but this suffers from two issues:
- The set is not kept up-to-date in all code paths where the set of entry point functions are updated.
- A set is incorrect because multiple hull shaders can have the same patch constant functions. We would need a counted set, aka `map<Func*,uint>`.

**Comment by llvm-beanz** [comment]
The related PR is closed, this issue is fixed as far as we can tell.
