### ISSUE TITLE
hlsl::IsHLSLResourceType/IsHLSLNumericUserDefinedType do not match all resource types

### ISSUE THREAD

**Issue by tristanlabelle** [microsoft/DirectXShaderCompiler#2119]
They will not match `RasterizerOrderedByteAddressBuffer` for example. We need to stop comparing strings. I suggest creating an attribute that we tag all HLSL object types with.

**Comment by llvm-beanz** [comment]
Closing as not planned. We are using an attribute to identify resource types in Clang.
