### ISSUE TITLE
Crash when calling EvaluateAttributeAtSample in a loop (with optimization on)

### ISSUE THREAD

**Issue by mrahm** [Microsoft/DirectXShaderCompiler#2129]
I've narrowed down an issue with dxc to this small sample app below.

If you call EvaluateAttributeAtSample in any loop, the compiler crashes. I also noticed if you use dxc with -O0 it also compiles. It's only with -O1+ that the compiler crashes. This is a regression from fxc, which compiled fine.

The production code this sample app is based on has the loop end variable coming from a constant buffer, but an immediate value also causes the crash (even an immediate value of 1 in the for loop). Using [unroll] doesn't help. I'm working on getting a large shader codebase compiling using dxc and targeting shader model 6. This is the first major issue I've run into.

I've been compiling the sample app with:
`dxc.exe -T ps_6_0 -E "main" mySample.hlsl -O3`
```hlsl
Texture2D t_map0 : register(t0);
SamplerState s_map0 : register(s0);

struct PS_INPUT
{
	float4 pos : SV_POSITION;
	float2 tc0 : TEXCOORD0;
};

float4 main(in PS_INPUT I) : SV_TARGET
{
	float4 dummy = float4(0,0,0,0);
	for (int i = 0; i < 4; ++i)	// this line will make the compiler blow up
	//int i = 0; 			// using this line instead compiles fine
	{
		float2 coord = EvaluateAttributeAtSample(I.tc0, i);
		dummy += t_map0.Sample(s_map0, coord);
	}
	return dummy;
}

**Comment by mrahm** [comment]
I tested this fix and it appears to resolve my issue. Our MSAA code path is working fine with shader model 6 shaders now. Thanks for the quick fix!

**Comment by MrTrillian** [comment]
Closing as fixed
