### ISSUE TITLE
d3dcompiler_dxc_bridge doesn't support D3DCreateBlob

### ISSUE THREAD

**Issue by gortega56** [Microsoft/DirectXShaderCompiler#2135]

**Comment by gortega56** [comment]
In the meantime, I'm looking at the dxc api. It doesn't look like IDxcLibrary supports creating an IDxcBlob instance directly from memory either. In our use case we save all compiled shader output to one file. At run time we load the entire file and create ID3DBlob instances from the offsets in memory.

**Comment by MrTrillian** [comment]
It's not ideal but on the DXC side, you can use `CreateBlobWithEncodingFromPinned` to create a non-owning `IDxcBlob` over an arbitrary range of memory. The encoding won't be used if it's binary data.

**Comment by MrTrillian** [comment]
Which API are you trying to call and need an `ID3DBlob` for? None of the functions we bridge accept one as an input.

**Comment by gortega56** [comment]
Hey thanks for the reply. Looking at this a bit more closely, I thought there was a dependency on ID3DBlob. Using fxc we would create ID3DBlob instances from cached file data and pass to a routine that calls D3DReflect, however that function only requires a pointer and size. I was hoping to get away with using the bridge as a drop in replacement, however this isn't a blocker for me as the change in minimal.
