### ISSUE TITLE
dxc.exe exited with code -1073741571 : Workaround

### ISSUE THREAD

**Issue by SlartyB52** [Microsoft/DirectXShaderCompiler#2146]
This relates to the closed issue #1587

Issue:
When writing ray tracing shaders for DXR applications, the dxc.exe compiler can exit with the above error code, once a certain complexity of shader has been reached. A few users have reported this issue (see issue #1587 )

Workaround:
When using Microsoft Visual Studio to compile DXR programs, change the following setting:
Project -> Properties -> HLSL Compiler -> Disable Optimisations
If the option is set to "Yes (/Od)", then dxc.exe fails.
If the option is set to "No", then the shaders are compiled successfully.

I hope this helps to un-block people.

**Comment by MrTrillian** [comment]
Thanks! I copied your workaround to the original issue and reopened it because this one isn't actionable for us.
