### ISSUE TITLE
-flegacy-macro-expansion doesn't expand non-arguments as fxc does

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#2158]
`-flegacy-macro-expansion` is useful for fxc preprocessor compatibility when using the token-pasting operator, but doesn't help for cases where the tokens are not macro arguments, though fxc still expands these (!!!)

Here's an example:
```
#define C 4
#define A4 float4
#define TYPE A##C

#define FUNC(ty) ty main() : OUT { return 0; }
FUNC(TYPE)
```

As long as this remains an issue, and for future code, the following change will bring the HLSL into compatibility with standard preprocessor rules, no longer requiring the `-flegacy-macro-expansion` option.

This will work with both dxc and fxc:
```
#define C 4
#define A4 float4
#define PASTE1(a, b) a##b
#define PASTE(a, b) PASTE1(a, b)
#define TYPE PASTE(A, C)

#define FUNC(ty) ty main() : OUT { return 0; }
FUNC(TYPE)
```

**Comment by BitMD** [comment]
We will add a note to the FXC to DXC port guide.
