### ISSUE TITLE
ByteAddressBuffer.Load<T> generates invalid SPIR-V (composite type extraction)

### ISSUE THREAD

**Issue by gwihlidal** [microsoft/DirectXShaderCompiler#2183]
The recent merge of https://github.com/microsoft/DirectXShaderCompiler/pull/2176 (which is awesome, btw!) seems to work for DXIL, but the generated SPIR-V is invalid. It is very important to get both DXIL and SPIR-V working so we can use this great new feature.

The error I get is:

```
fatal error: generated SPIR-V is invalid: Reached non-composite type while indexes still remain to be traversed.
   %23 = OpCompositeExtract %v2uint %22 1
```

Repro shader:
```
ByteAddressBuffer g_test: register(t0, space13);

struct Test
{
    float4 a;
    uint2 b;
};

struct VertexInput
{
    float3 position : POSITION;
};

struct VertexOutput
{
    uint drawId : DRAW_ID;
};

VertexOutput main(in VertexInput input)
{
    Test test = g_test.Load<Test>(123);
    VertexOutput output;
    output.drawId = test.b.x;
    return output;
}
```

Thank you,
Graham

**Comment by ehsannas** [comment]
Thanks for reporting @gwihlidal . The SPIR-V backend does not have support this feature yet as it is fairly new. I'll take a closer look at #2176

**Comment by sebbbi** [comment]
Shader Playground support for SM 6.2 templated raw loads was added today. 

Here's a Shader Playground SPIR-V repro case: http://shader-playground.timjones.io/fc7b48af43060a80072c7dff9a404f8b

**Comment by gwihlidal** [comment]
Hi @ehsannas, is there an update on this?

This is still a 100% show stopper for SPIR-V, and this feature is quite important to us.

Thanks!
Graham

**Comment by ehsannas** [comment]
@gwihlidal Hi Graham!
I've landed #2309 to support templated `Load` (forgot to reference this issue in the PR). Please give it a try and let me know if run into any issues. Unfortunately I haven't had the chance to work on templated `Store`.

**Comment by gwihlidal** [comment]
Thanks!

The shader playground trunk is old, but I'll update my shader compiler docker image and give it a shot there.

Do you have any idea when you'll find some time to work on templated `Store`?

Cheers,
Graham

**Comment by ehsannas** [comment]
I hope I can start working on it in a week or so.

**Comment by gwihlidal** [comment]
Hi @ehsannas - is there any update on this? Thank you!

**Comment by ehsannas** [comment]
I have landed https://github.com/microsoft/DirectXShaderCompiler/pull/2428 which should address the Store side. I haven't run any tests on hardware yet. Please feel free to give it a try and provide feedback. Thanks!
