### ISSUE TITLE
Linux build should not export symbols across shared object boundary by default

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#2203]
Linux build needs options: `-fvisibility=hidden` and `-fvisibility-inlines-hidden` to prevent things such as class methods from being exported across module boundaries by default.  This caused unexpected things to happen with PR #2196 on linux only.  The potential for this to happen elsewhere is very worrying.  PR #1760 adds the default visibility attributes to the explicitly exported APIs (and should be merged), but doesn't appear to add the build flag required to change the default visibility to hidden.

While I see usage of `#pragma GCC visibility push(hidden)` in at least `dxcmem.cpp`, this does not apply to class methods (see: https://gcc.gnu.org/onlinedocs/gcc/Visibility-Pragmas.html), and it doesn't seem sufficient to prevent accidentally exporting symbols not meant for export from elsewhere.  Nothing but the explicitly marked public functions should be exported across the shared library boundary.  Changing the default globally in build settings appears to be the more sensible way to handle this issue.

@ehsannas, what are your thoughts on this?

**Comment by pow2clk** [comment]
I will need to consult my notes to give you all the details, but I can tell you right now that I tried what you suggest nearly a year ago now and it did not go well at all. It is related to complications with the fact that there are multiple redundant versions of certain symbols built into DXC because of how the linking and loading works. I guess I should say there were issues when we were first creating the linux build. It's possible that there have been changes, but I've been lurking for a while and I haven't seen anything along those lines.

I'm not saying it's impossible, I'm saying it's tougher than this description makes it sound and there's a good chance you'll lose the Mac build in the process where the linking is subtly different.

**Comment by ehsannas** [comment]
In principle I agree with your thinking @tex3d . Not exporting anything by default, and specifically marking the ones we do want to export sounds like the right direction to me. In practice, I haven't tried it out. So I'm not sure what load of issues we'll run into (I trust @pow2clk 's comment on hitting a number of issues). I think it might be quite a bit of work? but I'm not sure.

@pow2clk do you have anything you can share from your work in the past? do you want to give it a try?

**Comment by pow2clk** [comment]
I am willing to commit to looking up my old notes and looking into the old branch where I started down this path for a day or so and backed away thinking I could never get approval for such a massive  change when something simpler would suffice. I have long felt that this is a sword of Damocles dangling over the project and . . . emitting. . . metal. . . shaving now and then? Okay that metaphor fell apart.

I'm supremely confident that my old branch is not going to "just work" in any sense of the term, but maybe I'll be able to give more detail than an ominous warning while waving my hands in scary fashion.

**Comment by pow2clk** [comment]
Sadly, my earlier attempt to work out the problems with `-fvisibility=hidden` (`-fvisibility-inlines-hidden` is already enabled) went down with my previous macbook. But my notes indicate the problems with it originated there and not in the Linux build. The changes that hide as much as they do were made to get MacOS working. See https://github.com/google/DirectXShaderCompiler/issues/199 and the conversation about the corresponding changes for some details.

I have a shiny new macbook. I'm still invested enough to whip up a change and see how it fares there. It will likely jog some memories.

**Comment by ehsannas** [comment]
Awesome! Thanks for your time @pow2clk !
