### ISSUE TITLE
DXC doesn't compile if you only have VS 2019 installed

### ISSUE THREAD

**Issue by ehsannas** [microsoft/DirectXShaderCompiler#2205]
DXC doesn't compile if you **only** have VS 2019 installed on your machine (I know VS 2019 is fairly new). The reason seems to be related to when it tries to look for DIA SDK. The following has hard-coded paths for VS 2015 and 2017. We should add the path for 2019 as well:

https://github.com/microsoft/DirectXShaderCompiler/blob/a56693ee05284147a7a69c5af586ca84cbcb29ec/cmake/modules/FindDiaSDK.cmake#L2-L24

I have both VS 2017 and VS 2019 on my machine, and compiling using VS 2019 works (because it's quietly using the 2017 DIA SDK!).

Thanks

**Comment by MrTrillian** [comment]
Yikes, we have a pending pull request for this, I hadn't realized the submitter didn't have merge rights. Does this look like it does what you need? #2136

**Comment by ehsannas** [comment]
Yeah! I think that should do it! Thanks

**Comment by MrTrillian** [comment]
Pull request merged!

**Comment by ehsannas** [comment]
Awesome Thanks
