### ISSUE TITLE
(spirv) compiler crash with 'float1'

### ISSUE THREAD

**Issue by xxxbxxx** [microsoft/DirectXShaderCompiler#2223]
hi,

this shader compiled with `dxc.exe  /Tps_5_0 -spirv` crashes the compiler:
```hlsl
float4 main(const float4 v : SV_Position) : SV_Target0
{
	float1 f = v.x;
	return float4(1.0*saturate(f*1.0), 0, 0, 1);
}
```

whereas it works fine when either: 
 - changing `float1` -> `float`
 - or not not targetting spirv.

**Comment by jaebaek** [comment]
Thank you for reporting it. I will take a look :)

**Comment by xxxbxxx** [comment]
thanks.
