### ISSUE TITLE
flat conversion of struct containing resource asserts in codegen

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#2229]
When performing a `CK_FlatConversion` of a struct containing a resource, CodeGen asserts, since it doesn't expect to be handling a resource.

Assert here:
https://github.com/microsoft/DirectXShaderCompiler/blob/cc175db5c1c41f66fb020946a70af1d3b4ebfecf/tools/clang/lib/CodeGen/CGHLSLMS.cpp#L6628

Repro:
```
// RUN: %dxc -E main -T ps_6_0 %s | FileCheck %s

Texture2D g_T;
struct Base { Texture2D T; };
struct Derived : Base {};

Derived New() {
  Base b;   // Base type
  b.T = g_T;
  return b; // FlatConversion to Derived, containing resource
}

float4 main(uint3 coord : COORD) : SV_Target {
  Derived d = New();
  return d.T.Load(coord);
}
```

**Comment by llvm-beanz** [comment]
Does not reproduce on godbolt: https://godbolt.org/z/E7bqEKzhc
