### ISSUE TITLE
[SPIRV] Can't use specialization constant as array bound

### ISSUE THREAD

**Issue by PazerOP** [microsoft/DirectXShaderCompiler#2230]
I'm attempting to compile the following shader:

```HLSL
[[vk::constant_id(1)]] const uint MY_ARRAY_BOUND = 1;
Texture2D g_MySpecConstArray[MY_ARRAY_BOUND];

struct VS_INPUT
{
	float4 pos : POSITION;
};

struct VS_OUTPUT
{
	float4 pos : SV_POSITION;
};

VS_OUTPUT main( const VS_INPUT input )
{
	VS_OUTPUT output;
	output.pos = input.pos;
	return output;
}
```

In glslangvalidator this compiles fine. However with `dxc.exe -spirv -T vs_6_0 -fspv-reflect -E main test.vert.hlsl -Fo test_dxc.vert.spv`, I get the following error:
```
test.vert.hlsl:2:29: error: variable length arrays are not supported in HLSL
Texture2D g_MySpecConstArray[MY_ARRAY_BOUND];
                            ^
```

I'm pretty sure this should be valid, but I could be wrong.

**Comment by ehsannas** [comment]
Thanks for reporting @PazerOP .

**Comment by ehsannas** [comment]
The error is generated by the HLSL frontend (also occurs for compiling to DXIL), and looks like an intended behavior.
