### ISSUE TITLE
Audit intellisense interfaces for memory mismanagement

### ISSUE THREAD

**Issue by MrTrillian** [microsoft/DirectXShaderCompiler#2234]
These interfaces have several dangerous patterns:

- LPSTR outparams that must be freed using `CoTaskMemFree` (see `CXStringToAnsiAndDispose`).
- `Tokenize` mixes `CoTaskMemAllocZeroElems` and `delete[]`
- `SetupUnsavedFiles` is not always paired with `CleanupUnsavedFiles` in error paths
- Some throwing new uses / wishful absence of try/catch
- Missing `clang_disposeString` in failure conditions

**Comment by pow2clk** [comment]
WNF
