### ISSUE TITLE
[spirv] Support D3D12 ROV (raster order view) HLSL to new SPV_EXT_fragment_shader_interlock..

### ISSUE THREAD

**Issue by oscarbg** [microsoft/DirectXShaderCompiler#2235]
Hi,
hopefully title says it all. 
Anyway for context: at last Vulkan 1.1.110 got released with VK_EXT_fragment_shader_interlock support and associated SPIR-V ext.: SPV_EXT_fragment_shader_interlock..
right now SPIR-V ext is here:
KhronosGroup/SPIRV-Registry@065daf4
this should allow to translate HLSL code using ROVs like:
"RasterizerOrderedTexture3D" etc..
to be translated to SPIR-V code..
in my request for ROV Vulkan support you can find some projects&samples using D3D11.3/12 ROV functionality (like notably Amazon Lumberyard uses for OIT and Xenia (Xbox emulator) for better EDRAM emulation:
https://github.com/KhronosGroup/Vulkan-Ecosystem/issues/27

EDIT: forgot to note we have drv support from NV (0-day) and even Mesa Anvil patches for Intel: https://gitlab.freedesktop.org/mesa/mesa/merge_requests/989

**Comment by ehsannas** [comment]
Thanks for reporting @oscarbg and thanks for the useful links.

**Comment by oscarbg** [comment]
Hi,
can provide any update on this?
would like to test this jointly with new SPIRV-Cross support for it on Metal:
https://github.com/KhronosGroup/SPIRV-Cross/pull/1138

**Comment by sudonatalie** [comment]
This is now being looked at in Issue #5124
