### ISSUE TITLE
[SPIRV] No output being generated for the shader which contains float3 tmp = (x, x, x)

### ISSUE THREAD

**Issue by mmostajab** [microsoft/DirectXShaderCompiler#2237]
I am using DXC to compile [This Shader](https://github.com/microsoft/DirectXShaderCompiler/files/3253662/Shader.in.txt) but it neither generates any output file nor reports any errors/warnings. It is not clear if `float sum;`, `float4 tmp = (sum, sum, sum, sum);` is a valid construct or not, but fxc/dxc (dxil generation) can compile it and it works.

I am using the following command line to compile the shader:

> .\dxc -spirv -O3 -Zpr Shader.in.txt -Fo PS.spv -Fc PS.h_spv -T ps_5_0 -E "TerrainLayerPS"

**Comment by ehsannas** [comment]
Thanks for reporting @mmostajab

**Comment by ehsannas** [comment]
```
struct pixout
{
  half4 Color:SV_Target0;
};

struct vert2fragTerrain
{
  float4 WPos:SV_POSITION;
  float4 basesectorTC:TEXCOORD0;
  float4 normal:TEXCOORD1;
  float4 worldPos:TEXCOORD2;
  float4 baseTC:TEXCOORD3;
  float4 tangent:TEXCOORD4;
  float4 bitangent:TEXCOORD5;
  float4 screenProj:TEXCOORD6_centroid;
};

float4 DoSomething(vert2fragTerrain IN)
{
	float4 ret = (IN.normal.x, IN.baseTC.x, IN.tangent.x, IN.bitangent.x);
	return ret;
}

pixout TerrainLayerPS(vert2fragTerrain IN)
{
  pixout OUT=(pixout)0;
  OUT.Color = DoSomething(IN);
  return OUT;
}
```
