### ISSUE TITLE
[linux-port] Request: Support downloading artifacts of travis-ci builds (for recent MacOS and Linux binaries)

### ISSUE THREAD

**Issue by oscarbg** [microsoft/DirectXShaderCompiler#2242]
Hi,
title says it all..
For example as of today lastest master (Appveyor) Windows build is downloadable at:
https://ci.appveyor.com/project/antiagainst/directxshadercompiler/builds/25045930/artifacts
equivalent Mac and Linux builds have been successfully done:
https://travis-ci.org/microsoft/DirectXShaderCompiler/builds/541476073
but are not downloadable..
would be nice if possible to be downloadable..
thanks..

**Comment by ehsannas** [comment]
The main reason this is not done so far is that Travis does not provide free storage of build artifacts. It requires an AWS/Azure/GCP bucket (with secure API calls) to store the artifacts I believe.

**Comment by ehsannas** [comment]
I also think this would be useful for the Linux and macOS users, as building DXC takes quite a bit of CPU and RAM.

**Comment by antiagainst** [comment]
I think the idiomatic way of distributing binaries on Linux is via package management system. Instead of downloading from a CI, we probably should consider to have .deb packages. On macOS, a homebrew formula would be nice.

**Comment by oscarbg** [comment]
thanks @ehsannas , now makes sense why not included..
still curious as Khronos glslang and spirv-tools provide simulataneous Mac and Linux "Master branch" builds:
https://github.com/KhronosGroup/glslang/releases/tag/master-tot
https://github.com/KhronosGroup/SPIRV-Tools/blob/master/downloads.md
so they are using Travis and paying some money?
also don't know anything about Travis or Appveyor, but seems Appveyor has Linux support for a year now(https://www.appveyor.com/blog/2018/05/15/appveyor-for-linux-is-generally-available/)
so at least using AppVeyor for Linux builds would be possible for storing Linux artifacts for free?

@antiagainst good ideas both deb and brew formula.. altough for me even simple zip or tgz compressed file is enough.. much like the referenced glslang and SPIRV-Tools Linux and Mac builds..

**Comment by ehsannas** [comment]
> so they are using Travis and paying some money?

No
* SPIRV-Tools is not using Travis. It uses "kokoro" (Google bots) and stores in GCP.
* glslang is getting Travis to upload artifacts as Tagged Releases to GitHub (storage on GitHub). We're not allowed to make Releases for this repository.

**Comment by oscarbg** [comment]
Hi @ehsannas,
seems the Linux part of this issue has been addressed recently! by:
https://github.com/microsoft/DirectXShaderCompiler/commit/e656f6ec01a7bd8b9c1ac9fd6a21c22ae21ad612
for me is the most interesting so thankyou! but anyway asking do you still interested on providing similar support for MacOS artifacts as requested here?

**Comment by ehsannas** [comment]
No problem! Glad to hear that.
I haven't looked into macOS yet. Will provide updates if/when it become available.

**Comment by ehsannas** [comment]
Unless there is overwhelming request for macOS artifacts, we're not going to pursue it for the time being.
