### ISSUE TITLE
NonUniformResourceIndex can misbehave due to optimizations

### ISSUE THREAD

**Issue by MrTrillian** [microsoft/DirectXShaderCompiler#2251]
Repro (see comment):
```
Buffer<float> Tuniform[16];
Buffer<float> Tnonuniform[16];

float main(int i : IN) : SV_Target
{
    if (i >= 8)
    {
        int j = i + 1; // Change to + 0 and it becomes nonuniform
        return Tuniform[j].Load(0);
    }
    else
    {
        return Tnonuniform[NonUniformResourceIndex(i)].Load(0);
    }
}
```

Changing as per the comment will cause either:
`call %dx.types.Handle @dx.op.createHandle(i32 57, i8 0, i32 0, i32 %1, i1 true)`
or
`call %dx.types.Handle @dx.op.createHandle(i32 57, i8 0, i32 0, i32 %1, i1 false)`

It looks like NonUniformResourceIndex tags the value `i` retroactively as being nonuniform, in a way that is dependent on optimizations.

**Comment by python3kgae** [comment]
Fixed with https://github.com/microsoft/DirectXShaderCompiler/commit/81af620244a99653b43ea34c80199c0169c6f61a
