### ISSUE TITLE
How to use the #175 "Support resource inside cbuffer" feature with D3D12 ?

### ISSUE THREAD

**Issue by thatname** [microsoft/DirectXShaderCompiler#2254]
Hi there. I saw that the pull request    #175 "Support resource inside cbuffer" makes it legal to have resource inside a CBuffer. But I'm confused on how to use this feature with D3D API. I can't find how to use it in any D3D12 documentation. What I can think of, is writing resource's GPU handle to a mapped constant buffer, will this work ?

**Comment by tex3d** [comment]
What's meant here by "inside cbuffer" is in HLSL syntax only, since fxc supported this.  It will not contribute to the layout of the cbuffer at all.  Resource binding space will be allocated separately, just like with any other global resource declaration.
