### ISSUE TITLE
llvm error with dxc produced debug info "!dbg attachment points at wrong subprogram for function"

### ISSUE THREAD

**Issue by paigeale** [microsoft/DirectXShaderCompiler#2255]
Hello,

I am compiling a samples shader with debug info turned on with shader model 6 .... (https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12nBodyGravity/src/nBodyGravityCS.hlsl)

Command Line: "dxc.exe nBodyGravityCS.hlsl /ECSMain /Tcs_6_0 /Zi /Fo test.bc"

I am getting the following error when trying to parse this debug info with llvm::parseBitcodeFile...

“””
!dbg attachment points at wrong subprogram for function
!87 = distinct !DISubprogram(name: "CSMain", scope: !3, file: !3, line: 56, type: !88, isLocal: false, isDefinition: true, scopeLine: 57, flags: DIFlagPrototyped, isOptimized: false, unit: !2)
void ()* @CSMain
  %newPosVelo_UAV_structbuf = call %dx.types.Handle @dx.op.createHandle(i32 57, i8 1, i32 0, i32 0, i1 false), !dbg !108
!108 = !DILocation(line: 14, column: 32, scope: !109)
!109 = distinct !DISubprogram(name: "??__Eg_fParticleMass@@YAXXZ", scope: !3, file: !3, line: 14, type: !110, isLocal: true, isDefinition: true, scopeLine: 14, flags: DIFlagPrototyped, isOptimized: false, unit: !2)
!109 = distinct !DISubprogram(name: "??__Eg_fParticleMass@@YAXXZ", scope: !3, file: !3, line: 14, type: !110, isLocal: true, isDefinition: true, scopeLine: 14, flags: DIFlagPrototyped, isOptimized: false, unit: !2)
warning: ignoring invalid debug info in
“””

After some investigation on my own I noticed that the issue has to do with these two lines in the .hlsl kernel that is causing the error.

float4 pos = oldPosVelo[DTid.x].pos;
float4 vel = oldPosVelo[DTid.x].velo;

I would assume that there may be a bug in how the debug info is being generated for the above lines. Please let me know if there is any additional info you need. I appreciate the help 

-Alex

**Comment by paigeale** [comment]
Closing issue for it was root caused that the BitcodeReader from llvm 4.0+ cannot handle the above debug info. I tried compiling with llvm 3.7 (used by dxc) and it was able to be handled correctly. Looks to be some major changes is debug info between llvm 3.7 and 4.

**Comment by MrTrillian** [comment]
Yes, LLVM has had several debug info improvements since 3.7, although they do a best effort to keep the bitcode reader backwards compatible.
