### ISSUE TITLE
InterlockedMax/Min with a constant resolves to the unsigned version

### ISSUE THREAD

**Issue by MrTrillian** [microsoft/DirectXShaderCompiler#2283]
Repro:
```
groupshared int sharedInt[1];

[numthreads(8, 8, 1)]
void main()
{
  // CHECK: atomicrmw max
  InterlockedMax(sharedInt[0], 1);
}
```
Output: `atomicrmw umax i32 addrspace(3)* getelementptr inbounds ([1 x i32], [1 x i32] addrspace(3)* @"\01?sharedInt@@3PAHA", i32 0, i32 0), i32 1 seq_cst`
This works: `InterlockedMax(sharedInt[0], (int)1);` or `InterlockedMax(sharedInt[0], -1);`

**Comment by vcsharma** [comment]
This is fixed.
