### ISSUE TITLE
bool values in the output signature trigger a validation error

### ISSUE THREAD

**Issue by galop1n** [microsoft/DirectXShaderCompiler#2288]
This is a minimal code snippet to repro the problem, the workaround for the moment is simply to use `uint` instead of `bool`. 

It is worth noting that it was use in front of a geometry shader, so we did not try to interpolate the `bool` in a pixel shader, i wonder what should be the behavior. and `nointerpolate` is of no use anyhow because it is vertex/geometry stage anyhow.

## Shader
```
struct IN
{
  float4 p : P;
  uint v : V ;
};

struct OUT
{
  float4 pos : SV_Position;
  bool boom : BOOM;
};
[RootSignature("")]
OUT main( IN i)
{
  OUT o;
  o. pos = i.p;
  o.boom = i.v > 10;
  return o;
}
```

## Output:
```
Container part 'Program Output Signature' does not match expected for module.
Container part 'Pipeline State Validation' does not match expected for module.
```

**Comment by MrTrillian** [comment]
Hi @galop1n. I am unable to reproduce the error you're seeing with various older or newer versions of the compiler. Could you provide the version you're using using `dxc -help | findstr Version` as well as the exact command line? Thanks!

**Comment by galop1n** [comment]
@MrTrillian `Version: dxcompiler.dll: 1.5 - 1.5.0.2255 (master, 5edbabb2-dirty); dxil.dll: 1.4(10.0.18362.1)`

This seems to be a `dxil.dll` issue, i can compile just fine with `-Vd` and on the xbox build of the compiler.

**Comment by MrTrillian** [comment]
Good catch, and thanks for reporting! We've done some fixes to validation and will to release an updated version of `dxil.dll` soon. It should show up in newer Windows SDKs within a few weeks.
