### ISSUE TITLE
Question: default arguments can now be non-constant

### ISSUE THREAD

**Issue by siliconvoodoo** [microsoft/DirectXShaderCompiler#2294]
_(**EDIT**: more or less self answered below)_
Consider this source:

```java
struct PSInput
{
    float4 color : COLOR;
};

// resource
extern float3 g_f;
static const float3 fone = float3(1,1,1);

void SomeFunc(float3 f3 = g_f)
{
    // ...
}

float2 VSMain(float3 position : POSITION) : TEXCOORD
{
    SomeFunc(position); // will use g_f or not ?
    return float2(1,1);
}

float4 PSMain(PSInput input) : SV_TARGET
{
    SomeFunc();  // will definitely use g_f
    return input.color;
}
```

I think you see where I'm going.
FXC stops here with this message:

> (10,22-29): error X3011: 'f3': (null) must be a literal expression

_(Which is a misnomer for constant-expression since it works with `fone`.)_

But, in DXC, anything goes. So what is the result on the asbtract machine binding model ?
In other words, what is the shader stage mask we need to set on the CPU side for such a case ?
`VS | PS` or just `PS` ?
Is it considered an active binding when the default argument is used, and NOT an active binding when the default is not used ?

Because some platforms like vulkan/metal don't let you bind extern resource that is not used in the high level source by a specific stage.

**Comment by siliconvoodoo** [comment]
So I wrote an experiment with a fake shader, and fake input data.
And my conclusion is basically, a function with a default argument is actually 2 functions, and the 0-ary version overloads the 1-ary version.

Therefore there is no dependency resulting from the use sites which pass an argument and therefore don't make use of the defaulted argument.

http://shader-playground.timjones.io/dbdd1bc6291b21a6e2df6cd1b1e49bb4
```
struct SomeStruct{float a;};
StructuredBuffer<SomeStruct> g_extendedMaterials;

float AccessSeed()
{
    return g_extendedMaterials[0].a.x;
}

float WaveNoise(float seed = AccessSeed())
{
    return seed * 356;
}

void ApplyDisplacement(inout float3 pos)
{
    pos += WaveNoise();  // adds a dependency on g_extendedMaterials
}

void ApplyDisplacementManualSeed(inout float3 pos, float seed)
{
    pos += WaveNoise(seed);  // but here no.
}

// PIXEL ENTRY
float4 MainPS(float3 fromVS : POSITION) : SV_Target0
{
    float3 pos = fromVS;
    //ApplyDisplacement(pos);
    ApplyDisplacementManualSeed(pos, 0.0);
    return float4(0,0,0,0);
}
```

results in:

```
; Resource Bindings:
;
; Name                                 Type  Format         Dim      ID      HLSL Bind  Count
; ------------------------------ ---------- ------- ----------- ------- -------------- ------
;
```

While if you reverse the last comment to activate `ApplyDisplacement()` call. You get:

```
; Resource Bindings:
;
; Name                                 Type  Format         Dim      ID      HLSL Bind  Count
; ------------------------------ ---------- ------- ----------- ------- -------------- ------
; g_extendedMaterials               texture  struct         r/o      T0             t1     1
;
```

Which seems to answer my question.

But it raises a new question, what is this ID that doesn't respect the HLSL binding point ? is this because the driver reall really wants to avoid holes in the register space ?

**Comment by MrTrillian** [comment]
The determination of what resources are used or not is based on the code that is generated and the optimizations that run on it. If the `= AccessSeed()` is never used because you always provide a value, then it won't exist in the final code and neither will the resource access, so we will eliminate the resource.

As for the binding points, HLSL did respect it, as you can see with `HLSL Bind` = `t1`. The `ID` is more of an internal value and is used to look up metadata. In your example:

```
!dx.resources = !{!4}
!4 = !{!5, null, null, null} ; First entry are SRVs or "T"
!5 = !{!6} ; Index 0 is "T0"
!6 = !{i32 0, %"class.StructuredBuffer<SomeStruct>"* undef, !"g_extendedMaterials", i32 0, i32 1, i32 1, i32 12, i32 0, !7} ; Here's our metadata.
```

The Direct3D API still uses the `t1` bind point in root signatures.
