### ISSUE TITLE
DXC crashes on float input with SV_DispatchThreadID semantic

### ISSUE THREAD

**Issue by tristanlabelle** [microsoft/DirectXShaderCompiler#2299]
Repro:
```
[numthreads(1, 1, 1)]
void main(float3 tid : SV_DispatchThreadID) {}
```

We should also validate bools and structs, any non-int types.

**Comment by pow2clk** [comment]
Reopened because fix was reverted
https://godbolt.org/z/h59x74rxz

Seeing some weird discrepancies between godbolt and my local windows install. Linux vs windows maybe.
Godbolt compiles successfully, which is wrong. 
Windows crashes, which is wronger.

**Comment by llvm-beanz** [comment]
Closing since we're not going to address this in DXC.
