### ISSUE TITLE
[SPIRV] -auto-binding-space command line option ignored for spirv build

### ISSUE THREAD

**Issue by thedavidperkins** [microsoft/DirectXShaderCompiler#2304]
The `-auto-binding-space <index>` command line option should set the default descriptor set index for spirv builds, but appears to be ignored in all cases I have tried.

I am running a `47e31c...` dxc build attempting to use functionality added in [this commit](https://github.com/microsoft/DirectXShaderCompiler/commit/101730c57be391d461576df17619cf98892c82c9). In both custom shaders of my own design and the shaders from unit tests introduced in that commit, I've passed the option `-auto-binding-space 77` (as in the unit tests) and the resulting set indices that are not explicitly specified remain zero.

An example command line call (optimization disabled to ensure unused declarations aren't omitted from the opcode):
```
<dxcpath>\dxc.exe -T ps_6_0 -E main -spirv -auto-binding-space 77 -O0 -Fh explicit.txt vk.binding.default-space.explicit.hlsl
```
The source shader is [this one](https://github.com/microsoft/DirectXShaderCompiler/blob/101730c57be391d461576df17619cf98892c82c9/tools/clang/test/CodeGenSPIRV/vk.binding.default-space.explicit.hlsl) and contains the following declarations:
```
[[vk::binding(5,6)]]
SamplerState sampler1 : register(s1, space2);
[[vk::binding(8)]]
SamplerState sampler2 : register(s4);
SamplerState sampler3 : register(s1, space9);
SamplerState sampler4 : register(s3);
```
The out file `explicit.txt` contains the following decorations:
```
OpDecorate %sampler1 DescriptorSet 6
OpDecorate %sampler1 Binding 5
OpDecorate %sampler2 DescriptorSet 0     // << This should be 77
OpDecorate %sampler2 Binding 8
OpDecorate %sampler3 DescriptorSet 
OpDecorate %sampler3 Binding 1
OpDecorate %sampler4 DescriptorSet 0     // << This should be 77
OpDecorate %sampler4 Binding 3
```

I first came across this issue based on inspecting spriv reflection data after compilation. I am running off of the built binaries from Appveyor if that makes a difference.

**Comment by ehsannas** [comment]
This is surprising, because the unit test has no magic. It is run using Appveyor's binaries. It compiles the shader with the command line options specified at the top of the file ([example](https://github.com/microsoft/DirectXShaderCompiler/blob/101730c57be391d461576df17619cf98892c82c9/tools/clang/test/CodeGenSPIRV/vk.binding.default-space.explicit.hlsl#L1)).

**Comment by thedavidperkins** [comment]
Yeah, I was looking that over and I noticed that the command line options you're talking about don't actually have the `-spirv` option explicitly stated with them. I don't know how the testing framework is set up, but does that get appended somewhere in the unit test call?

I might clone the repo and investigate this weekend.

**Comment by ehsannas** [comment]
Yeah, we manually add `-spirv`, and (in some cases) `-fcgl` (disable legalization and optimization) and `-Vd` (disable validation). It is done here:

https://github.com/microsoft/DirectXShaderCompiler/blob/47e31c8a4ca0a8750fa69ce0dd736498971c3c83/tools/clang/unittests/SPIRV/FileTestUtils.cpp#L169-L179

**Comment by thedavidperkins** [comment]
On my personal machine I've attempted to reproduce the error without success. I thought I had done my due diligence to verify it wasn't my mistake when I reported the error, but clearly the code functions as intended.
