### ISSUE TITLE
utils\hct\hctgettaef.py requires Python3

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/DirectXShaderCompiler#2306]
According to Readme:

> Version 2.7.x is required, 3.x might work but it's not officially supported.

However, if you attempt to use Python2 to execute `utils\hct\hctgettaef.py` then you get the following error:

> C:\Code\Microsoft\DirectXShaderCompiler>py -2 utils\hct\hctgettaef.py
> Traceback (most recent call last):
>  File "utils\hct\hctgettaef.py", line 1, in <module>
>    import urllib.request
> ImportError: No module named request

If you use Python3, then the download succeeds.

Should the readme be updated, or the script fixed?

**Comment by ehsannas** [comment]
The readme should be updated. Sorry we missed that before. I've made a PR to update the README.md. Thanks for reporting.
