### ISSUE TITLE
[SPIRV] Type enum is unimplemented

### ISSUE THREAD

**Issue by sunillnaik** [microsoft/DirectXShaderCompiler#2317]
Very interesting issue! 
While compiling HLSL to SPIRV shader, The DXC fails to compile enum types, though it compiles fine for DXIL output format. Do you think this is a quick fix and, we can expect in coming weeks? or it's gonna take long time to fix it?
Here is the Permalink : http://shader-playground.timjones.io/0cf75398d6e0928e2494ee92f432781c

**Comment by ehsannas** [comment]
Thanks for reporting @sunillnaik :)

 @jaebaek will take a look. I suspect it will not take a long time.

**Comment by sunillnaik** [comment]
Thank you! expecting the fix soon :)
