### ISSUE TITLE
File system handle has scaling limitations and other problems

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#2319]
`DxcArgsFileSystemImpl` implementation with `DxcArgsHandle` has a number of limitations that need addressing, for reliability and efficiency.

1. `DxcArgsHandle` uses union of `HANDLE` (typedef'd to `void*`) and `HandleBits` as file handle.  `HANDLE` is pointer sized, but is frequently cast to/from `int` by file system APIs, since this is used as the `int fd` file descriptor.
2. `struct HandleBits` is defined as three `unsigned` bitfields.  The first is `unsigned Offset : 8;` which is used for the index into a single vector of all files and directories ever opened/added.  At one point, the code wouldn't add more than 200 due to the value of `MaxIncludedFiles`, but that value was upped to 1000 without changing the code that couldn't handle more than 256 values due to this 8-bit field.  This will result in silent wrap-around of this index in the file handle, causing who-knows-what undefined behavior later.
3. The second field of `HandleBits` is `unsigned Length : 8`.  This 8-bit field holds directory path lengths.  8-bits seems too small for this as well.  Even through it may seem rare to see paths this long, it's not out of spec and certainly could happen, and once again we have a silent overflow that could result in who-knows-what behavior.
4. Casing and path separators are not being normalized, so we don't match paths or filenames that are the same like we should if these differ - leading to additional handle space usage.
5. Linear searches abound here, and need to be replaced with a better system using DenseMap or something.
6. File handles are 1:1 with a `ReadOnlyBlobStream` instance, and the handle returned for `CreateFileW` will be the same for the same filename (on the same thread), even though different calls should return different handles.  Handles should not be a single value tied to a single stream, but each file handle should be tied to a different stream instance, even if it's the same file (they could both ref the same underlying file contents blob though).

In general, this system needs some real attention/refactor work.

**Comment by otanter-at-ubi** [comment]
Hi,
regarding point 2, I could indeed experiment the wrap around, as described in issue #2731 (where you can find an easy repro). The end result is that the shader compilation fails and returns rather unclear errors.
