### ISSUE TITLE
[spirv] Add rvalue/lvalue test cases to templated byteaddress buffer load

### ISSUE THREAD

**Issue by ehsannas** [microsoft/DirectXShaderCompiler#2326]
As suggested in code review here: https://github.com/microsoft/DirectXShaderCompiler/pull/2309, we should add test cases that check rvalue/lvalues are properly done with templated byteaddressbuffer load.

**Comment by MrTrillian** [comment]
Feel free to file general DXC bugs if you find lvalue/rvalue handling oddities, since those will be shared AST-level issues. I'm aware the codebase is often badly behaved in that respect (in part because FXC had weird semantics itself) and it's something I'd like to improve.

**Comment by ehsannas** [comment]
@MrTrillian  Sure! I think we have some hacks in the SPIR-V backend to counter the AST issues. I'll try to find them and file general DXC bugs as needed. Thanks
