### ISSUE TITLE
DXIL linker is nondeterministic

### ISSUE THREAD

**Issue by MrTrillian** [microsoft/DirectXShaderCompiler#2329]
It iterates over pointer-keyed maps in `DxilLinker.cpp`:
`for (Function *UsedF : linkInfo->usedFunctions) {`
`for (Function *F : linkPair.first->usedFunctions) {`
`for (GlobalVariable *GV : linkInfo->usedGVs) {` (x2)
see
`std::unordered_set<llvm::Function *> usedFunctions;`
`std::unordered_set<llvm::GlobalVariable *> usedGVs;`

**Comment by octopusprime314** [comment]
Hi, I am experiencing non deterministic builds as well, are you still looking at this issue?
