### ISSUE TITLE
[DXIL] D3DCOLORtoUBYTE4 implementation incorrect

### ISSUE THREAD

**Issue by TiemoJung** [microsoft/DirectXShaderCompiler#2343]
Hi, we just seen invalid results when using D3DCOLORtoUBYTE4.
The expected implementation would look like `int4((var.zyxw) * 255.001953)` but the translation is
`int4(round_ne(var.zyxw * 255)) `which yields different results.
We temporarily fixed this by adding a macro with the suggested implementation it fixed our results.

**Comment by vcsharma** [comment]
Thanks for reporting this bug!

In addition to using `round_ne`, dxc also appears to not swizzle the input to D3DCOLORtoUBYTE4 unlike fxc.

**HLSL**
```
int4 main (float4 f : IN): OUT
{
    return D3DCOLORtoUBYTE4(float4(1,2,3,4));
 }

```

**FXC Output**

```
dcl_globalFlags refactoringAllowed
dcl_output o0.xyzw
mov o0.xyzw, l(765,510,255,1020)
ret

```
**DXC Output**

```
define void @main() {
  call void @dx.op.storeOutput.i32(i32 5, i32 0, i32 0, i8 0, i32 255)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  call void @dx.op.storeOutput.i32(i32 5, i32 0, i32 0, i8 1, i32 510)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  call void @dx.op.storeOutput.i32(i32 5, i32 0, i32 0, i8 2, i32 765)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  call void @dx.op.storeOutput.i32(i32 5, i32 0, i32 0, i8 3, i32 1020)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  ret void
}
```

**Comment by vcsharma** [comment]
@TiemoJung, this should be fixed. Please give it a try.

**Comment by TiemoJung** [comment]
@vcsharma Its now working as expected, thanks!
