### ISSUE TITLE
struct functions

### ISSUE THREAD

**Issue by GregSlazinski** [microsoft/DirectXShaderCompiler#2348]
https://github.com/microsoft/DirectXShaderCompiler/wiki/Breaking-Changes-from-FXC
mentions:
`struct Foo {} func() {}`
I think it should be instead something like:
`struct Foo { func() {} }`

BTW. are struct functions going to get added in the future? That would simplify some codes greatly.

**Comment by MrTrillian** [comment]
The wiki entry is actually correct, although that is a super obscure feature.
`struct Foo { int i; } func() { return 0; }`
Declares a struct named Foo and a function that returns a value of that type.

By struct functions, do you mean member functions? Those are already supported. For example the following returns 43:

```
struct Foo
{
  int x;
  void inc() { x++; }
  int getX() { return x; }
};

int main() : OUT
{
  Foo foo = (Foo)42;
  foo.inc();
  return foo.getX();
}
```

**Comment by GregSlazinski** [comment]
Oh cool, thanks for the clarification. Originally I just thought the syntax on wiki is incorrect because I've never encountered this kind of writing.
Glad to know regular struct functions are working.
