### ISSUE TITLE
ExecutionTest::UnaryFloatOpTest#atan expects non-NaN result for NaN input

### ISSUE THREAD

**Issue by jholewinski** [Microsoft/DirectXShaderCompiler#235]
The reference values for ExecutionTest::UnaryFloatOpTest#atan expects a NaN input to produce a non-NaN output:

[ShaderOpArithTable.xml]
```xml
        <Parameter Name="Validation.Input">
          <Value>NaN</Value>
          ...
        </Parameter>
        <Parameter Name="Validation.Expected">
          <Value>0.785410</Value>
          ...
        </Parameter>
```

According to the DXIL spec, Atan of NaN should produce NaN.

**Comment by youngkim93** [comment]
Thank you for the report. This was the behavior of fxc and I mistakenly used this as a reference. Should be fixed with #240
