### ISSUE TITLE
Using custom cbuffer indexes does not set D3D_SIF_USERPACKED

### ISSUE THREAD

**Issue by GregSlazinski** [microsoft/DirectXShaderCompiler#2356]
I have a shader that uses my own bind index for a constant buffer:
`#define BUFFER_I(name, index) cbuffer name : register(CONCAT(b,index)) {`
However when parsing the reflection:
```
                  FREP(desc.BoundResources)
                  {
                     D3D12_SHADER_INPUT_BIND_DESC desc; if(!OK(reflection->GetResourceBindingDesc(i, &desc))){error.line()+="'GetResourceBindingDesc' failed."; goto error;}
                     switch(desc.Type)
                     {
                        case D3D_SIT_CBUFFER:
                        {
                           buffer.bind_explicit=FlagTest(desc.uFlags, D3D_SIF_USERPACKED); // THIS IS ALWAYS FALSE
```
desc.uFlags never has D3D_SIF_USERPACKED enabled
https://docs.microsoft.com/en-us/windows/win32/api/d3d12shader/ns-d3d12shader-d3d12_shader_input_bind_desc

**Comment by damyanp** [comment]
We're unable to investigate this further at the moment.  If you feel this is still an issue can you please provide a complete repro shader.

Thanks!
