### ISSUE TITLE
Using custom cbuffer indexes should prevent other cbuffers from reusing the same indexes

### ISSUE THREAD

**Issue by GregSlazinski** [microsoft/DirectXShaderCompiler#2357]
I have a shader that defines 3 cbuffers:

```
cbuffer A : register(b1) {} // bound to index 1
cbuffer B  {} // bound to any index
cbuffer C  {} // bound to any index
```

if I compile a function that does not use cbuffer A, but only use B and C, then the problem is one of those buffers may get assigned to index # 1.

However this overlaps with the A cbuffer. Even though I'm not using A cbuffer in this shader, the index should still be avoided.

This behavior was working correctly in the old FXC, however the new DXC is not OK.

Example:
I have an optimization that some cbuffers are assigned only to 1..8 indexes and it never changes throughout the entire application, so I can assign them only one time at the app startup.
And the remaining 9..+ indexes are assigned dynamically depending on what other cbuffer a shader needs.

The solution is to adjust the compiler, to never assign other cbuffers to the indexes of cbuffers which have explicitly specified bind index.

In this case:
```
cbuffer A : register(b1) {} // bound to index 1
cbuffer B  {} // bound to any index
cbuffer C  {} // bound to any index
```

When shader uses only B and C, then it should assign indexes # 0 and # 2 but never # 1

**Comment by MrTrillian** [comment]
Hi Greg! We have a compiler flag for backcompatibility with this behavior. Off the top of my head, it's called `-legacy-resource-reservation`. It's listed in the DXC help and DXC will automatically apply ot when compiling shader model 5.1. Let me know if this fixes your problem.

**Comment by GregSlazinski** [comment]
Excellent! thanks a lot, it worked.
The name is "-flegacy-resource-reservation", with 'f' at the start.

BTW. I think it's more sensible to pass flags as UINT / Bit Masks using stuff like:
```
enum OPTIONS
{
   OPTION_1=1<<0,
   OPTION_2=1<<1,
   OPTION_3=1<<2,
  ..
```
Only command line arguments should be text based IMO.

**Comment by MrTrillian** [comment]
I'm glad it helped! As for the API shape, it's a tradeoff but we decided that keeping it closer to the command-line made it more self-documenting and easily extendable.
