### ISSUE TITLE
Mac build fails to compile std::make_unique in DxilContainerReflection.cpp

### ISSUE THREAD

**Issue by sunillnaik** [microsoft/DirectXShaderCompiler#2365]
I'm trying to build DXC for Mac and the build fails at DxilContainerReflection.cpp with 
`error: no member named 'make_unique' in namespace`

Note: I have modified DxilContainerReflection.cpp for some internal requirement.
source code  
`std::unique_ptr<char[]> pUpperStr = std::make_unique<char[]>(strlen(pValue) + 1);`

I added -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ to specify compiler
is there anything Im missing? I use same version of cmake and python as on windows. windows build is fine. 

Thanks,
Sunil Naik

**Comment by pow2clk** [comment]
Does it build without your changes to DxilContainerReflection.cpp? There are regular automated tests for the mac build and the latest show it completing successfully.

std::make_unique is a feature of c++14, which has been supported since clang 3.4. What version of clang are you using?

**Comment by sunillnaik** [comment]
I'm not so familiar with mac version, but below is the clang --version on the mac probably c++ version is older let me figure out. I assume the clang is higher version than mentioned in build instruction. 
```
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by pow2clk** [comment]
Apple makes it difficult to get a useful version, but that should be adequate and it shouldn't differ for clang++. 

The changes you made for the internal requirement. Is there a chance they changed what headers get included? Regardless, you might try explicitly including `<memory>`

**Comment by MrTrillian** [comment]
Thanks for reporting. I believe `llvm::make_unique` from `#include <llvm\ADT\STLExtras.h>` exists for this reason. I'll have a PR to fix it shortly.

**Comment by sunillnaik** [comment]
Interesting! thanks for the quick fix, I will get my mac book soon and I will build it again.

**Comment by sunillnaik** [comment]
I have new erros after updating xcode and mac os with latest version or brand new mac book.

```
src/lib/HLSL/DxilCondenseResources.cpp:1722:33: error: lambda capture 'LLVMUsed' is not used
      [-Werror,-Wunused-lambda-capture]
  auto UpdateResourceSymbol = [&LLVMUsed, this](DxilResourceBase *res) {
                               ~^~~~~~~~~
src/lib/HLSL/DxilCondenseResources.cpp:1722:43: error: lambda capture 'this' is not used
      [-Werror,-Wunused-lambda-capture]
  auto UpdateResourceSymbol = [&LLVMUsed, this](DxilResourceBase *res) {
                                        ~~^~~~
2 errors generated.
```

**Comment by sunillnaik** [comment]
Could be issue with latest xcode downloaded for new mac, Im downgrading to Xcode 10 Sep 12, 2018

**Comment by sunillnaik** [comment]
Well, downgrading and removing flag which treats warning as error succeeded build. Thanks
