### ISSUE TITLE
IsFinite and NaN

### ISSUE THREAD

**Issue by jholewinski** [Microsoft/DirectXShaderCompiler#237]
ExecutionTest::UnaryFloatOpTest#Isfinite is expecting an NaN input to produce "1" (e.g. value is finite):

```xml
        <Parameter Name="Validation.Input">
          <Value>NaN</Value>
          ...
        </Parameter>
        <Parameter Name="Validation.Expected">
          <Value>1</Value>
          ...
        </Parameter>
```

The DXIL spec does not state explicitly whether NaN is finite or not, though NaN is traditionally not a finite value: [cmath reference](http://www.cplusplus.com/reference/cmath/isfinite/).

**Comment by youngkim93** [comment]
Thank you for the report. This should be fixed in #239
