### ISSUE TITLE
Recursion cycles improperly reported

### ISSUE THREAD

**Issue by siliconvoodoo** [microsoft/DirectXShaderCompiler#2370]
Where FXC is giving out a nice:

> error X3500: 'Random::Init': recursive functions not allowed in vs_5_0

DXC gives no output at all. Just process code not 0 if you look for it.
If you change to SPIRV you get a somewhat concerning:

> generated SPIR-V is invalid: Entry points may not have a call graph with cycles.
>   %MainVS = OpFunction %void None %24
> note: please file a bug report...

Here some code to reproduce it:

```
struct Vertex
{
     float3 m_position : POSITION;
};

class Random
{
    float cur;
    void Next();
    void Init()
    {
	cur = 1.f;
    	Next ( ) ;
    }
};

void ::Random::Next()
{
	Init ( ) ;
	cur += 1 ;
} 

::Vertex MainVS(  ::Vertex input)
{
	Random r ;
	r . Init ( ) ;
	return input ;
} 
```

**Comment by MrTrillian** [comment]
Thanks for reporting! This is an oversight in the cycle detection code that didn't include member functions. Fix coming soon.
