### ISSUE TITLE
D3DStripShader

### ISSUE THREAD

**Issue by GregSlazinski** [microsoft/DirectXShaderCompiler#2374]
What would be the equivalent of FXC's 'D3DStripShader' ?
`ID3DBlob *stripped=null; D3DStripShader(buffer->GetBufferPointer(), buffer->GetBufferSize(), ~0, &stripped);`
FXC had a function to remove useless stuff to reduce the shader size.
Is there any function like that in DXC?

I looked here in the bridge section, but couldn't find anything: https://github.com/microsoft/DirectXShaderCompiler/blob/master/tools/clang/tools/d3dcomp/d3dcomp.cpp

**Comment by MrTrillian** [comment]
@tex3d That's one for you!

**Comment by tex3d** [comment]
You want the IDxcContainerBuilder interface defined in dxcapi.h.

**Comment by GregSlazinski** [comment]
Do you have any tutorial on how to use it to achieve the same functionality as in my first post?

**Comment by tex3d** [comment]
I don't think there's a tutorial on this, though there should be, and we'll be working on better docs.

In brief, you:
- use DxcCreateInstance to create the interface
- call Load() method to load the container
- call RemovePart() for each part you wish to remove, use FourCC code to identify part (see below)
- call SerializeContainer to reconstruct container without these parts.

FourCC codes are defined in this header:
https://github.com/microsoft/DirectXShaderCompiler/blob/fd4c08a10e732b0906cbd01a381785b9bdd1fb99/include/dxc/DxilContainer/DxilContainer.h#L82-L98

The parts you can remove with this API are: DFCC_ShaderDebugInfoDXIL, DFCC_ShaderDebugName, DFCC_RootSignature, and DFCC_PrivateData.  An additional part for reflection is coming and will be removable with DFCC_ShaderStatistics.

Note: The debug part can be left out of the original shader container returned by the compiler, making it unnecessary to remove later, while still acquiring it with the API by using IDxcCompiler2::CompilerWithDebug.

Note 2: You can strip reflection today by passing -Qstrip_reflect to the compile API, but you cannot currently preserve reflection and strip it later with the container builder.

**Comment by GregSlazinski** [comment]
Thank you very much!

**Comment by GregSlazinski** [comment]
my code ended up looking like this, however as soon as I call `RemovePart`, then I'm getting an exception thrown.
```
                              IDxcContainerBuilder *container_builder=null; CreateContainerBuilder(&container_builder); if(container_builder)
                              {
                                 if(OK(container_builder->Load(buffer)))
                                 {
                                    container_builder->RemovePart(hlsl::DFCC_ShaderDebugInfoDXIL);
                                    container_builder->RemovePart(hlsl::DFCC_ShaderDebugName);
                                    container_builder->RemovePart(hlsl::DFCC_RootSignature);
                                    container_builder->RemovePart(hlsl::DFCC_PrivateData);
                                    container_builder->RemovePart(hlsl::DFCC_ShaderStatistics);
                                    IDxcOperationResult *result=null; container_builder->SerializeContainer(&result); if(result)
                                    {
                                       HRESULT hr; if(OK(result->GetStatus(&hr)))if(OK(hr))
                                       {
                                          IDxcBlob *stripped=null; result->GetResult(&stripped);
                                          if(stripped){buffer->Release(); buffer=stripped;} // swap 'stripped' with 'buffer'
                                       }
                                       result->Release();
                                    }
                                 }
                                 container_builder->Release();
                              }
```

**Comment by Geoffrey91** [comment]
I'm also trying to write an implementation of `D3DStripShader` using the new DXC api. Unfortunately, whenever I enable my shader stripping code, I get this error: `D3D12 ERROR: [0x8C149AEE] ID3D12Device::CreateGraphicsPipelineState: Input Signature in bytecode could not be parsed.  Data may be corrupt or in an unrecognizable format. [ STATE_CREATION ERROR #63 ]`

My code is similar to the one above and goes as follows:
```
    void
    DxcStripShader(
        const D3D12_SHADER_BYTECODE&    lShaderModule,
        sUInt32                         laStripParts[],
        sUInt32                         luStripPartsNum,
        IDxcUtils*                      lpDxcUtils,
        IDxcBlob**                      lppDxcStrippedBlob )
    {
        *lppDxcStrippedBlob = nullptr;

        IDxcBlob*             lpDxcBlob               = nullptr;
        IDxcBlobEncoding*     lpDxcBlobEnc            = nullptr;
        IDxcOperationResult*  lpDxcStrippingResult    = nullptr;
        IDxcContainerBuilder* lpDxcContainerBuilder   = nullptr;

        lpDxcUtils->CreateBlobFromPinned( lShaderModule.pShaderBytecode, (UINT32)lShaderModule.BytecodeLength, 0, &lpDxcBlobEnc );
        lpDxcBlobEnc->QueryInterface( &lpDxcBlob );
        DxcCreateInstance( CLSID_DxcContainerBuilder, IID_PPV_ARGS( &lpDxcContainerBuilder ) );
        lpDxcContainerBuilder->Load( lpDxcBlob );
        for ( sUInt32 ii = 0; ii < luStripPartsNum; ++ii )
        {
            lpDxcContainerBuilder->RemovePart( laStripParts[ ii ] );
        }
        lpDxcContainerBuilder->SerializeContainer( &lpDxcStrippingResult );
        lpDxcStrippingResult->GetResult( lppDxcStrippedBlob );
    }
```
(note: that's actually a simplified version of my code; I've omitted all error handling and `Release` calls on resources for brevity).

I've tried commenting out the for loop, and I still get the same error, suggesting that probably I'm doing something wrong in creating the `DxcContainerBuilder` or when I serialise it. I'd be wonderful to get some documentation on this topic, but for the time being I'd be very grateful if you could help me out and point out what is that I'm doing wrong. Thanks!

**Comment by aras-p** [comment]
Any guidance in how to "strip" the debug/reflection information would be appreciated indeed!
