### ISSUE TITLE
D3D12_SHADER_VARIABLE_DESC has incorrect 'Size' for Half's

### ISSUE THREAD

**Issue by GregSlazinski** [microsoft/DirectXShaderCompiler#2376]
D3D12_SHADER_VARIABLE_DESC has incorrect 'Size' for Half's
I use SM 6.2, -enable-16bit-types
yet for 
```
cbuffer
{
  min16float a;
  half b;
  float16_t c;
}
```
I keep getting `Size` 4 for each of a,b,c
However `StartOffset` are correct, {0, 2, 4} for a,b,c

**Comment by pow2clk** [comment]
I can no longer repro this. I suspect https://github.com/microsoft/DirectXShaderCompiler/pull/2416/commits/892765cc4b348ff0342b87608b203a40549a4058 by @tex3d may have fixed it.
