### ISSUE TITLE
Missing warning on cbuffer field initializer.

### ISSUE THREAD

**Issue by tristanlabelle** [microsoft/DirectXShaderCompiler#2384]
No warnings:
```
cbuffer cb { int x = 42; }
int main() : OUT { return x; }
```
Warning (Initializer of external global will be ignored):
```
int x = 42;
int main() : OUT { return x; }
```
In the former case, the value is also ignored.

**Comment by GregSlazinski** [comment]
Can my original issue be please restored due to:
https://github.com/microsoft/DirectXShaderCompiler/issues/2380#issuecomment-516209353
