### ISSUE TITLE
Fix include paths

### ISSUE THREAD

**Issue by GregSlazinski** [microsoft/DirectXShaderCompiler#2385]
I download the builds from: https://ci.appveyor.com/project/antiagainst/directxshadercompiler/build/artifacts
Trying to include the headers, gives me errors:
`C:\Esenthel\ThirdPartyLibs\DirectXShaderCompiler\include\dxc\DxilContainer\DxilContainer.h(19,10): error C1083:  Cannot open include file: 'dxc/DXIL/DxilConstants.h': No such file or directory`
Which has:
```
#include "dxc/DXIL/DxilConstants.h"
#include "dxc/Support/WinAdapter.h"
```
Which looks like you want to setup "Include Directories" option in the project settings.
However this can be problematic, for example if you have a lot of projects, or trying to build on another platforms, tools, or whatever..
This is an unnecessary obstacle for programmers.

There's a simple fix that will solve the problems, just replace the code with:
```
#include "../DXIL/DxilConstants.h"
#include "../Support/WinAdapter.h"
```

And it will really make life easier.
Thank you

**Comment by tex3d** [comment]
There are several problems to fix here, but I don't think we will be changing all the includes to use the above relative paths generally.

Problems:
1. dxc artifacts should not contain all the headers under the include/dxc path.  These should just be the top-level public `dxc*.h` headers directly under `dxc/`.
2. Headers in this set including other headers in this set should include them without any directory prefix.
3. These top-level headers should not include other headers that are not in this set.  This means that WinAdapter.h needs to be included in some other way outside of these headers before including these headers, when _WIN32 is not defined.
4. Outside projects should not be including any of the other headers (except for some advanced, unsupported scenarios, where they can copy/modify headers locally or something).

**Comment by pow2clk** [comment]
Per Tex, we're not going to change the include paths. Filed a bug for Tex's suggestions.
