### ISSUE TITLE
DXIR documentation

### ISSUE THREAD

**Issue by AIOOB** [microsoft/DirectXShaderCompiler#2389]
Hi, I'm helping to write a compiler that takes in SPIR-V and produces something consumable by DirectX drivers, according to your diagram in [docs/DXIL.rst](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/DXIL.rst#Introduction) a possible target is DXIR.
Is there any documentation of DXIR and the process that takes it to DXIL? I was unable to find any in this repo.

**Comment by tex3d** [comment]
Unfortunately, documentation on the lowering process is mostly non-existent.  I would recommend using the dndxc tool to see the initial IR from CodeGen, and the steps applied afterwards for some representative examples.  Try to determine where in that process the SPIR-V might most closely map (perhaps close to CodeGen?).  Then try to get the IR into that form so you can utilize the remaining passes for lowering to DXIL.

**Comment by tex3d** [comment]
Oh, and DXIR isn't anything official, but just the first LLVM IR after CodeGen.

**Comment by AIOOB** [comment]
Thanks, I'll see where this gets us!
