### ISSUE TITLE
[SPIRV] Texture2D<min16float4> gets converted to uniform highp sampler2D

### ISSUE THREAD

**Issue by GregSlazinski** [microsoft/DirectXShaderCompiler#2399]
In all cases, declaring textures as `min16float` (example: `Texture2D<min16float4>` )gets converted to `highp sampler2D` in pixel shaders, but `min16float` should be `mediump`.

**Comment by ehsannas** [comment]
@GregSlazinski Are you using the `-enable-16bit-types` option?

**Comment by ehsannas** [comment]
see https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#minimal-precision-scalar-types

**Comment by GregSlazinski** [comment]
I think this is not needed in this case, because for example using min16float for constant buffer variables or temporary variables inside functions does generate properly mediump variables in glsl, however textures are still stuck at highp. So in short: everything gets converted to mediump properly, except textures.

**Comment by ehsannas** [comment]
It is odd that the behavior is different for textures vs standalone variables. @jaebaek please investigate.

**Comment by GregSlazinski** [comment]
I'm using `spvc_compiler_build_combined_image_samplers` (if that matters).

**Comment by GregSlazinski** [comment]
Thank you, I've posted an issue in SPIRV-Cross project about this problem.

**Comment by GregSlazinski** [comment]
looks like this was fixed in SPIRV-Cross
