### ISSUE TITLE
[spirv] Derived structs generate invalid SPIR-V

### ISSUE THREAD

**Issue by LiamTyler** [microsoft/DirectXShaderCompiler#2403]
Hello,

I have this issue where structs that inherit from other structs dont generate valid spirv. Here is the smallest reproducible shader source I could make:

```
struct VertexInput 
{ 
    float4 position : POSITION;
};

struct PixelOutput
{
    float4 position : SV_POSITION;
};

struct Base1
{ 
    float4 foo1;
};

struct Base2 : Base1 
{ 
    float4 foo2;
};

struct Derived : Base2
{
    float4 foo3;
    float4 foo4;
};

cbuffer constantData : register ( b0 )
{
    Derived derivedData;
    float4x4 MVP;
}

PixelOutput vs_main ( const VertexInput vertex )
{
    PixelOutput pixel;
    pixel.position = mul( vertex.position, MVP );
    
    return pixel;
}
```

Here is the command I am running:
```
dxc.exe -T vs_6_0 -E vs_main -fvk-use-dx-layout -spirv repro.hlsl -Fo repro.spv
```

I am using `-fvk-use-dx-layout` because I ran into some other issues and saw this post: https://github.com/microsoft/DirectXShaderCompiler/issues/2022

DXC compiles the shader with no complaints. When I run the spirv validator from SPIRV-Tools however, I get this:

```
error: line 39: Structure id 5 decorated as Block for variable in Uniform storage class must follow standard uniform buffer layout rules: member 1 at offset 16 overlaps previous member ending at offset 31
  %Derived = OpTypeStruct %Base2 %v4float %v4float
```

I noticed that if I get rid of the inheritance (something I can't do with the actual shaders), the problem goes away. Attached are the invalid hlsl, spirv, and disassembled spirv: repro_derived.* 
[repro_derived.zip](https://github.com/microsoft/DirectXShaderCompiler/files/3493539/repro_derived.zip)

I also attached the versions of those three files without the inheritance for reference: repro_not_derived.*
[repro_not_derived.zip](https://github.com/microsoft/DirectXShaderCompiler/files/3493540/repro_not_derived.zip)

Please take a look and let me know if I am missing something, or if this is a bug.

Thanks

**Comment by ehsannas** [comment]
Thanks for reporting @LiamTyler 

`-fvk-use-dx-layout` is used often when porting a DX application to Vulkan. When you run DXC, it always runs spirv-val under the hood before delivering the SPIR-V binary to you (and if it doesn't validate, it'll show the validation error and asks you to file a bug). So, you don't need to manually run spirv-val yourself.

In this case, since the code is following the dx memory layout, the struct member offsets does not match what the validator expects. I believe in this case you should run the validator with the `--skip-block-layout` option.

Please close if this resolves your issue. Thanks!

**Comment by LiamTyler** [comment]
Thank you for the reply.

Whether DXC runs spirv-val, or I run it manually isn't the issue. The issue is that either way (with or without `-fvk-use-dx-layout`) the spirv is invalid.

If we look at the source struct layouts:
```
struct Base1
{ 
    float4 foo1;
};

struct Base2 : Base1 
{ 
    float4 foo2;
};

struct Derived : Base2
{
    float4 foo3;
    float4 foo4;
};

cbuffer constantData : register ( b0 )
{
    Derived derivedData;
    float4x4 MVP;
}
```

Then "Derived" should have 4 float4s in it, making it 64 bytes in size. If we look at the disassembled spirv though, we get this:

```
...
OpMemberDecorate %Derived 0 Offset 0
OpMemberDecorate %Derived 1 Offset 16 ; <---
OpMemberDecorate %Derived 2 Offset 32 ; <---
OpMemberDecorate %type_constantData 0 Offset 0
OpMemberDecorate %type_constantData 1 Offset 32 ; <---
OpMemberDecorate %type_constantData 1 MatrixStride 16
OpMemberDecorate %type_constantData 1 RowMajor
OpDecorate %type_constantData Block
...
```

`%Base2` is member 0 of `%Derived` and is 2 float4s, making its size 32 bytes. This means that the offsets should not be 16 and 32, but 32 and 48 instead. Similarly in the `%type_constantData`, the `%Derived` struct is 64 bytes in size, so the MVP matrix offset should be 64, not 32. When I change this disassembled text accordingly, and use spirv-as to re-assemble it, it passes the validator.

Correct me if I am wrong, but I think regardless of what flags are used, the generated spirv should have the correct offsets for structs with inheritance, but it currently does not.

**Comment by ehsannas** [comment]
Oh, sorry I misunderstood the issue initially. I'll take a closer look. Thanks.

**Comment by ehsannas** [comment]
Although the type translation pass does recognize the base structs, it seems that the code that calculates the memory layout missed it. I have put up a fix for review. Thanks for reporting :)

**Comment by LiamTyler** [comment]
I grabbed the artifacts and tried it out. Seems to be working now. Thanks!
