### ISSUE TITLE
[spirv] Padding for buffer of uint3 incorrect

### ISSUE THREAD

**Issue by LiamTyler** [microsoft/DirectXShaderCompiler#2408]
Hello,

When I try to compile this shader:
```hlsl
StructuredBuffer < uint3 > buffer1 : register ( t1 ) ; 
StructuredBuffer < uint > buffer2 : register ( t0 ) ; 
RWTexture2D < float3 > outputBuffer : register ( u0 ) ; 

[numthreads (8, 8, 1)] 
void cs_main(uint2 id : SV_DispatchThreadID)
{
    uint linearIndex = id . y * 160 + id.x;
    uint bytePos = linearIndex % 4;

    uint frameBufferData = buffer2[linearIndex / 4];
    uint shiftedData = frameBufferData >> (bytePos * 8);
    shiftedData &= 0x0000007F;

    outputBuffer[id] = float3(buffer1[linearIndex]) / 255.0f;
} 
```

I get this error:
```
dxc.exe -E cs_main -T cs_6_0 -fvk-use-gl-layout -spirv -Fo repro.spv Q:\repro.hlsl
fatal error: generated SPIR-V is invalid: Structure id 3 decorated as BufferBlock for variable in Uniform storage class must follow relaxed storage buffer layout rules: member 0 contains an array with stride 12 not satisfying alignment to 16
  %type_StructuredBuffer_v3uint = OpTypeStruct %_runtimearr_v3uint
```

I think this issue is already known: https://github.com/Microsoft/DirectXShaderCompiler/issues/2022

But I can't use the `-fvk-use-dx-layout` flag here. Im assuming that the output should still be valid spirv without this. Especially when I use the `-fvk-use-gl-layout`, but with or without it, it fails.

I am using the DXC from this fix btw: https://github.com/microsoft/DirectXShaderCompiler/issues/2403, but I dont think that has been merged in yet

**Comment by ehsannas** [comment]
Thanks for reporting @LiamTyler . We'll investigate.

**Comment by LiamTyler** [comment]
Turns out I actually do want the `-fvk-use-dx-layout` for this. I still am wondering why not using any flag or using the `-fvk-use-gl-layout` flag results in invalid spirv though

**Comment by ehsannas** [comment]
Yeah I would like to understand the failure as well.

**Comment by jaebaek** [comment]
@LiamTyler Thank you for reporting this. This is one of very important issue for DXC and Vulkan users. Let me quickly check many related issues one by one.

**Comment by jaebaek** [comment]
@LiamTyler I just sent the first PR for handling this issue.
In terms of #2403 , I think the PR was properly merged.

I compiled the example HLSL you gave and it generates:
```
               OpMemberDecorate %Base1 0 Offset 0
               OpMemberDecorate %Base2 0 Offset 0
               OpMemberDecorate %Base2 1 Offset 16
               OpMemberDecorate %Derived 0 Offset 0
               OpMemberDecorate %Derived 1 Offset 32
               OpMemberDecorate %Derived 2 Offset 48
               OpMemberDecorate %type_constantData 0 Offset 0
               OpMemberDecorate %type_constantData 1 Offset 64
               OpMemberDecorate %type_constantData 1 MatrixStride 16
               OpMemberDecorate %type_constantData 1 RowMajor
```

As far as I understand, this is the expect result.
Please correct me if I am wrong.
