### ISSUE TITLE
Bool handling in WaveReadLaneAt()

### ISSUE THREAD

**Issue by yuralsky** [microsoft/DirectXShaderCompiler#2410]
A bool variable used as a parameter to WaveReadLaneAt(), results in the compiler converting it to double before calling the intrinsic. E.g. the following code:

float4 main(int i : TEXCOORD) : SV_Target
{
	bool b = i != 666;
	return float4(WaveReadLaneAt(b, 31), 0, 0, 0);
}

Generates the following DXIL output:

define void @main() {
  %1 = call i32 @dx.op.loadInput.i32(i32 4, i32 0, i32 0, i8 0, i32 undef)  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %2 = icmp ne i32 %1, 666
  **%3 = uitofp i1 %2 to double**
  %WaveReadLaneAt = call **double** @dx.op.waveReadLaneAt.f64(i32 117, **double %3**, i32 31)  ; WaveReadLaneAt(value,lane)
  %4 = fptrunc double %WaveReadLaneAt to float
<...>
}

**Comment by vcsharma** [comment]
This is also likely related to #2432.
