### ISSUE TITLE
Parameter limit not propagated

### ISSUE THREAD

**Issue by Slagh** [microsoft/DirectXShaderCompiler#2415]
The title could be a bit confusing 😬 but essentially, with the following HLSL, the function `getAorB` is passed a parameter that cannot be `1` thanks to the use of `min`. Due to this, cbuffer `B` is untouched, which is a good thing since both `A` and `B` both use register `b1`.

FXC.exe recognises this, but DXC does not, and produces the error:

`error: resource B at register 1 overlaps with resource A at register 1, space 0`.

The HLSL:

```
cbuffer Params : register(b0)
{
    int index;
}

cbuffer A : register(b1)
{
    float a;
};

cbuffer B : register(b1)
{
    float b;
};

float getAorB(int which)
{
    switch(which)
    {
        default:
        case 0: return a;
        case 1: return b;
    }
}

float4 main() : SV_Target0
{
    return getAorB(min(0, index));
}
```

The command line: `-E main -T ps_6_0`.

Version: `dxcompiler.dll: 1.5 - 1.4.0.2338 (master, f8d0271d)`

**Comment by siliconvoodoo** [comment]
I wouldn't want to accept that if we have library profiles now. the clients are not as immediatley clear as in fxc era.

**Comment by pow2clk** [comment]
Won't fix
