### ISSUE TITLE
Question: IDxcCompiler instance reuse, threads

### ISSUE THREAD

**Issue by Slagh** [microsoft/DirectXShaderCompiler#2418]
Hi, I am wondering what the expectation is for users to reuse an instance of the `IDxcCompiler` to `Compile`, `Preprocess` or `Dissasemble` many shaders in succession, _and/or_ to use the same instance across multiple threads?

I am seeing some unreliable results from both multiple compiles and multiple threads _at the same time_ that suggests that the preprocessor is producing different results from one "session" to the next.

I have the same questions regarding `IDxcContainerReflection` as well.

**Comment by Slagh** [comment]
I will suggest from my own experience that sharing some of these instances across threads is not reliable at all. I don't intend to nail down which ones are shareable - I just create new instances for each invocation I need.

**Comment by BitMD** [comment]
The call to DxcCreateInstance is thread safe, but objects created by DxcCreateInstance are not thread-safe.  Compiler objects should be created and then used on the same thread.

Its ok to use the same compiler objects on the same thread to compile multiple shaders.
