### ISSUE TITLE
exception when calling IDxcContainerBuilder::RemovePart

### ISSUE THREAD

**Issue by GregSlazinski** [microsoft/DirectXShaderCompiler#2422]
https://github.com/microsoft/DirectXShaderCompiler/issues/2374#issuecomment-522225969

**Comment by tafuri** [comment]
I ran into the issue and for me the crash seems to occur whenever I try to remove `DFCC_ShaderStatistics` using a relatively new version of `dxcompiler.dll`.

The crash seems to occur in `dxil.dll` and my guess is that it needs to be updated as well. I am wondering though why the actual stripping takes place in `dxil.dll` and not `dxcompiler.dll`?

**Comment by mkgski** [comment]
Same problem for me as well.  I hit this using the pre-built binaries referenced here : https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.4.1907 which appears to include the newest available dxil.dll.

**Comment by pow2clk** [comment]
Fixed in newest version of the validator. dxil.dll will take a while to propagate out.
