### ISSUE TITLE
Inconsistent behaviour with integers and interpolation type

### ISSUE THREAD

**Issue by tafuri** [microsoft/DirectXShaderCompiler#2426]
There seems to be a bug in DXC when compiling shaders using ´int´/´uint´ in interpolated structs.

So if I compile a domain shader, for example, using this output definition. The generated dxil will look slightly different depending on whether `integerValue` is explicitly marked as `nointerpolation` or not, causing issues in my specific usecase.

```hlsl
#ifdef BROKEN_OUTPUT
struct DS_OUTPUT
{
	float4 position : SV_Position;
	uint integerValue : TEXCOORD0;
};
#else
struct DS_OUTPUT
{
	float4 position : SV_Position;
	nointerpolation uint integerValue : TEXCOORD0;
};
#endif
```
So toggling the `BROKEN_OUTPUT` define I end up with a single dxil statement difference.

This is with `BROKEN_OUTPUT` defined
```
!22 = !{i32 6, !"integerValue", i32 3, i32 16, i32 4, !"TEXCOORD0", i32 7, i32 5}
```

and this is without
```
!22 = !{i32 6, !"integerValue", i32 3, i32 16, i32 4, !"TEXCOORD0", i32 5, i32 1, i32 7, i32 5}
```

In both of these cases `integerValue` is marked as `nointerpolation` in the debug information.
FXC is consistent and generates the same code for both cases.

**Comment by tafuri** [comment]
I have also noticed strange behavior when the `sample` interpolation type is used on any stage other than fragment.

**Comment by tex3d** [comment]
Not observing behavior.  Are there any additional details you could provide (full repro shader)?

**Comment by tafuri** [comment]
Yes, this seems to have been resolved in the later versions of DXC.
