### ISSUE TITLE
Unintentional conversion to double precision

### ISSUE THREAD

**Issue by JohnGierach** [microsoft/DirectXShaderCompiler#2432]
I have run into a problem where the following example code is converting all of the intermediate variables going into "sum" are converted to double precision.

float sum = (samples.x ? 1.0 : 0.0)
        + (samples.y ? 1.0 : 0.0)
        + (samples.z ? 1.0 : 0.0)
        + (samples.w ? 1.0 : 0.0);

Historically the fxc compiler was more forgiving and would keep such values as floating point precision.  

This behavior will unintentionally make shaders use double precision which will be slower and may lack support from all hardware vendors.

When I changed the code to:

float sum = (samples.x ? 1.0f : 0.0f)
        + (samples.y ? 1.0f : 0.0f)
        + (samples.z ? 1.0f : 0.0f)
        + (samples.w ? 1.0f : 0.0f);

I was able to run the application on the desired hardware.

Ideally the dxc compiler would be smart enough to keep this data in floating point format.

**Comment by vcsharma** [comment]
Thanks for reporting!

Minimal repro below:

**HLSL**
```
float main (bool2 i : IN) : OUT
{
	return (i.x ? 1.0 : 0.0) + (i.y ? 1.0 : 0.0) ;	
}
```

**DXIL**

```
define void @main() {
  %1 = call i32 @dx.op.loadInput.i32(i32 4, i32 0, i32 0, i8 0, i32 undef)  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %2 = icmp ne i32 %1, 0
  %3 = call i32 @dx.op.loadInput.i32(i32 4, i32 0, i32 0, i8 1, i32 undef)  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %4 = icmp ne i32 %3, 0
  %5 = select i1 %2, double 1.000000e+00, double 0.000000e+00
  %6 = select i1 %4, double 1.000000e+00, double 0.000000e+00
  %7 = fadd fast double %6, %5
  %8 = fptrunc double %7 to float
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 0, float %8)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  ret void
}
```

However, the below seems to work.

**HLSL**

```
float main (bool i : IN) : OUT
{
	return (i ? 1.0 : 0.0);	
}
```

**DXIL**

```
define void @main() {
  %1 = call i32 @dx.op.loadInput.i32(i32 4, i32 0, i32 0, i8 0, i32 undef)  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %2 = icmp ne i32 %1, 0
  %3 = select i1 %2, float 1.000000e+00, float 0.000000e+00
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 0, float %3)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  ret void
}
```

**Comment by JohnGierach** [comment]
Thanks for taking the time to reproduce the issue!

The original problem shader comes from 3DMark Port Royal.

Please let me know if there is any additional information needed and if there is a fix I can test.

-John

**Comment by JohnGierach** [comment]
Any progress on this?

Thanks,
John

**Comment by vcsharma** [comment]
FYI, we have an open pr #2636 to fix this issue.

**Comment by pow2clk** [comment]
Related to #2202

**Comment by mkarigan** [comment]
One more example , this is case where fabs gets promoted to Fp64 

float main(float4 pos : SV_POSITION) : SV_TARGET
{
  return abs(pos.z > 0.99);
}

"C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\dxc.exe" /Tps_5_0  testIn.hlsl

define void @main() {
  %1 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 2, i32 undef)  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %2 = fcmp fast ogt float %1, 0x3FEFAE1480000000
  %3 = uitofp i1 %2 to double
  %4 = call double @dx.op.unary.f64(i32 6, double %3)  ; FAbs(value)
  %5 = fptrunc double %4 to float
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 0, float %5)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  ret void
}

"C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\fxc.exe" /Tps_5_0  testIn.hlsl

ps_5_0
dcl_globalFlags refactoringAllowed
dcl_input_ps_siv linear noperspective v0.z, position
dcl_output o0.x
dcl_temps 1
lt r0.x, l(0.990000), v0.z
and o0.x, r0.x, l(0x3f800000)
ret


Requires a explicit cast to avoid generating fp64 fabs on some Platforms where fp64 is not supported

float main(float4 pos : SV_POSITION) : SV_TARGET
{
  //return abs(pos.z > 0.99);
  return abs((float)(pos.z > 0.99)); // avoid fp64 casting
}


define void @main() {
  %1 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 2, i32 undef)  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %2 = fcmp fast ogt float %1, 0x3FEFAE1480000000
  %3 = uitofp i1 %2 to float
  %4 = call float @dx.op.unary.f32(i32 6, float %3)  ; FAbs(value)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 0, float %4)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  ret void
}

**Comment by mkarigan** [comment]
looks like its fixed in @ https://github.com/microsoft/DirectXShaderCompiler/releases 
[dxc_2021_12_08.zip](https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.6.2112/dxc_2021_12_08.zip)
Sorry about the thrash

**Comment by damyanp** [comment]
This is fixed in HLSL 202x.
