### ISSUE TITLE
DXC crashes when calling InterlockedAdd

### ISSUE THREAD

**Issue by ehsannas** [microsoft/DirectXShaderCompiler#2434]
The shader provided by @Slagh in issue #2409 carshes DXC (when generating DXIL).

Shader:
```hlsl
RWTexture3D<uint> target			: register(u1);

struct VS_OUTPUT
{ 
    float4	Pos				: SV_Position;
};

void main(VS_OUTPUT input)
{
	uint3 index = uint3(0,0,0);
	InterlockedAdd(target[index].r, 1);
}
```

Command:
```
dxc.exe -T vs_6_0 shader.hlsl
```

**Comment by jaebaek** [comment]
It also reports an error when changing `RWTexture3D<uint> target			: register(u1);` to `RWTexture3D<uint3> target			: register(u1);`. I am curious this is intended or not.

**Comment by galop1n** [comment]
Hi, something similar with a silent crash/exit with the piece of code below. I was curious to see if the atomic on integer only limitation was lifted. nVidia and AMD technically have the hardware support for that.

```hlsl
RWBuffer<float> test;
[numthreads(8,8,1)]
void main() {
  InterlockedAdd(test[0],1.f);
}
```

**Comment by vcsharma** [comment]
@ehsannas Thanks for reporting this issue! I am working on a fix.

@galop1n Currently we don't have immediate plans to support atomic intrinsics for data types other than uint and int, but the sample test that you shared shouldn't crash on DXC. We'll be adding some diagnostics to notify unsupported data types (like FXC).

**Comment by vcsharma** [comment]
Filed a separate issue to track unsupported types: #2483
