### ISSUE TITLE
[spirv] SPIRV compile doesn't eliminate lerped saturated zero.

### ISSUE THREAD

**Issue by Slagh** [microsoft/DirectXShaderCompiler#2437]
With the following code:

```
Texture2D<float4> unused : register(t0);
SamplerState samplerstate : register(s0);

float4 main() : SV_Target0
{
    float a = 0;
    float unusedvalue = unused.Sample(samplerstate, float2(0,0)).x;
    float b = lerp(a, unusedvalue, saturate(a));
//    float b = lerp(a, unusedvalue, a);
    return b;
}
```

and compiling with `-T ps_6_0 -spirv`, the Texture2D `unused` is listed as a resource. Swapping the `lerp` with the commented one correctly removes the unreferenced resource.

The emitted DXIL removes `unused` in both cases.

Version: `dxcompiler.dll: 1.5 - 1.4.0.2338 (master, f8d0271d)`

**Comment by ehsannas** [comment]
Thanks for reporting @Slagh.

**Comment by ehsannas** [comment]
This requires the SPIR-V optimizer (spirv-opt) to know that `saturate(a)` is in fact going to be zero.
in other words, spirv-opt should know that the result of 
```
      %26 = OpExtInst %float %1 FClamp %float_0 %float_0 %float_1
```
is going to be `%float_0`.

I'll file an issue in SPIRV-Tools repository.
