### ISSUE TITLE
Include SPIR-V backend in official releases

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/DirectXShaderCompiler#2443]
The release that came out yesterday doesn't include the SPIR-V backend making the release kind of useless for me. It fails with `SPIR-V CodeGen not available. Please recompile with -DENABLE_SPIRV_CODEGEN=ON.`.

For future releases can we enable the SPIR-V backend?

**Comment by Niteip** [comment]
I have encountered the same problem.
How do I resolve it?

**Comment by Jasper-Bekkers** [comment]
@ChasBoyd Has there been any traction on this?

**Comment by garrynewman** [comment]
Is there a good reason for it to be left out of official releases? Seems like it's opt-in so should do no harm?

**Comment by turanszkij** [comment]
Is there any plan to enable SPIRV in Windows SDK release? It would make it easier to maintain the build for SPIRV shaders in Visual Studio projects.

**Comment by pow2clk** [comment]
With everything going on, I'm afraid I can't tell you exactly when the next release will be. I can assure you that when that day comes, the -spirv flag will be enabled!

**Comment by procedural** [comment]
> With everything going on,

What do you mean?

**Comment by pow2clk** [comment]
> What do you mean?
I mean we're busy! 😫

**Comment by pow2clk** [comment]
The day has come! https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.5.2010 

If issues are found with this build, please file new issues with the [SPIR-V] tag in the title.

**Comment by pow2clk** [comment]
Thanks to @hekota for all her work on this!

**Comment by ehsannas** [comment]
Thanks @hekota for making this happen!

**Comment by Jasper-Bekkers** [comment]
Thanks, this is great news!
