### ISSUE TITLE
unroll / constant expression propagation failure

### ISSUE THREAD

**Issue by fungos** [microsoft/DirectXShaderCompiler#2446]
```glsl
// dxc.exe test.hlsl -T cs_5_0 -Zi // Fail
// fxc.exe test.hlsl -T cs_5_0 -Zi // Pass

RWStructuredBuffer<uint> x:register(u0);
[numthreads(64,1,1)] 
void main(uint3 dtid : SV_DispatchThreadID) 
{
	[unroll] 
	for (uint i = 0; i < min(10, 5); ++i) 
	{
		x[i] = i;
	}
}
```

`fxc` is able to resolve `min(10, 5)` into a compile time constant used to unroll the loop, where `dxc` is unable to do so, giving the error `Could not unroll loop. Loop bound could not be deduced at compile time. Use [unroll(n)] to give an explicit count. Use '-HV 2016' to treat this as warning.`

**Comment by hekota** [comment]
This should no longer repro on the latest bits.
