### ISSUE TITLE
missing semantic verification or implicit casting leads to invalid dxil overloads during system value lowering

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#2448]
System value inputs (or outputs?) translated to intrinsics in `replaceInputOutputWithIntrinsic`, and possibly in other places, can generate invalid DXIL overloads because they use the declared component type of the input as the overload type, and no verification or implicit casting has been performed to ensure the user-defined type for the system value input (or output) matches the native intrinsic type.

Example:
```
// RUN: %dxc -T ps_6_0 %s
// SV_Coverage should be uint, but generates invalid overload (or asserts in CHK build)
// Note: fxc silently reinterprets the uint input as a float (not good).
float main(float cov : SV_Coverage) : SV_Target {
  return cov;
}
```

**Comment by pow2clk** [comment]
The result is very different, but the way to trigger the flaw is very similar to #2299

**Comment by damyanp** [comment]
We'll not be tackling this in DXC.  This issue tracks making sure we get it right for clang: https://github.com/llvm/llvm-project/issues/95150
