### ISSUE TITLE
64k array limit from fxc should not apply to resources in dxc

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#2455]
Fxc has an arbitrary array dimension size limitation of 64k, but it doesn't apply to resource arrays in SM 5.1.  Dxc mirrored this limitation, even though dxc does not need it, but didn't exempt resource arrays.  We should just get rid of the specific limitation, since it's not useful.

Side note: the same code limiting the size to 64k also prevents 0-sized arrays.  But 0-sized arrays are essentially unbounded arrays, which we should support in certain cases, including for resources.  We should remove this general limit as well, and add specific restrictions as needed instead.

The following is allowed with fxc (ps_5_1), but not with dxc:
```
Texture2D<float4> tex[99999];

float4 main(uint i : I) : SV_TARGET
{
  return tex[i][uint2(0,0)];
}
```

**Comment by vcsharma** [comment]
This is fixed with #2461.
