### ISSUE TITLE
[spirv] Vulkan option fspv-flatten-resource-arrays seems to break fvk-*-shift

### ISSUE THREAD

**Issue by jamiehayes** [microsoft/DirectXShaderCompiler#2459]
Given the following compute HLSL:
```
Texture2D<float> tex1 : register(t0);
SamplerState samp : register(s0);
RWBuffer<float> output : register(u0);

[numthreads(32, 32, 1)]
void csmain(uint3 dispid : SV_DispatchThreadID) {
    float val = tex1.SampleLevel(samp, (float2)dispid.xy, 0.0f);
    output[dispid.y * 32 + dispid.x] = val;
}
```
and the following cmd line options: 
```
-spirv -fspv-flatten-resource-arrays -fvk-b-shift 0 0 -fvk-t-shift 0 1 -fvk-s-shift 0 2 -fvk-u-shift 0 3 -T cs_6_0 -E csmain
```
The following error occurs:
```
error: ran into binding number conflict when assigning binding number 0 in set 0
error: ran into binding number conflict when assigning binding number 0 in set 0
```
If I run again without `fspv-flatten-resource-arrays`, it succeeds.
I expect this is a bug because `fspv-flatten-resource-arrays` should *not* preclude space shifting, should it?

**Comment by ehsannas** [comment]
Hey @jamiehayes 
a couple of points:

* `-fspv-flatten-resource-arrays` should be used if you want to flatten the binding numbers used for an array of resources. For example, if you have `RWTexture2D<float> myTextureArray[3]`, then normally you'd only get binding number 0 for the whole array, but **with this option**, you would get binding numbers 0, 1, and 2 (one binding number for each element of the array). In your shader there's no array, so this option is not going to do anything (except some additional error checking).

* The error is actually a legitimate one. The `-fvk-{X}-shift N M` Shifts by `N` the inferred binding numbers for all resources in X-type registers of space `M` ([doc](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#vulkan-specific-options)). So I think the options you intended to use were in fact:
`-fvk-b-shift 0 0 -fvk-t-shift 1 0 -fvk-s-shift 2 0 -fvk-u-shift 3 0`
which will result in 
```
               OpDecorate %tex1 DescriptorSet 0
               OpDecorate %tex1 Binding 1
               OpDecorate %samp DescriptorSet 0
               OpDecorate %samp Binding 2
               OpDecorate %output DescriptorSet 0
               OpDecorate %output Binding 3
```
Adding `-fspv-flatten-resource-arrays` to the mix does not change the result (i.e. using 
`-fspv-flatten-resource-arrays -fvk-b-shift 0 0 -fvk-t-shift 1 0 -fvk-s-shift 2 0 -fvk-u-shift 3 0` results in the same output)

**Comment by ehsannas** [comment]
I'll close this issue. Feel free to reopen if you have further questions. Thanks
