### ISSUE TITLE
DXC silently fails when trying to compile a shader

### ISSUE THREAD

**Issue by jirzynek** [microsoft/DirectXShaderCompiler#2471]
Hi,

DXC silently fails (compiler crash) when trying to compile the following shader. 
```

// dxc.exe test.hlsl -Tps_5_1 -Emain_ps -Fotest.bin

struct S
{
    float foo;
};

ConstantBuffer<S> : register(b0);

float4 main_ps() : SV_TARGET0
{
    return 0.0f;
}
```

FXC produces meaningful error when processing the same shader, and this is the behavior I expect.

**Comment by vcsharma** [comment]
Thanks for reporting this!

Note that this crash is only specific to `ConstantBuffer`. For other object types, if no identifier name is declared, dxc successfully generates error message. Specifically, in below scenarios, dxc generates error message as expected.

```

struct S
{
    float foo;
};

Buffer<float4> : register(b0);
ByteAddressBuffer : register(b0);
Texture2D<float4> : register(t0);
StructuredBuffer<S> : register(b0);
RWTexture1D<float4> : register(b0);
RWBuffer<float2> : register(b0);
TextureCube<float4> : register(b0);
TextureCubeArray<float4> : register(b0);
RWStructuredBuffer<int1x1> : register(b0);

void main() {}

```
