### ISSUE TITLE
line_directive.hlsl fails when running dxc from 17763

### ISSUE THREAD

**Issue by henning-semler** [microsoft/DirectXShaderCompiler#2490]
Version: dxcompiler.dll: 1.3(10.0.17763.132); dxil.dll: 1.3(10.0.17763.132)

Command:

dxc -E main -T ps_6_0 line_directive.hlsl

Result:

line_directive.hlsl:9:10: error: use of undeclared identifier 'foo'; did you mean 'for'?
  return foo; // Undeclared identifier
         ^~~
         for
line_directive.hlsl:9:10: error: expected expression

Henning

**Comment by vcsharma** [comment]
Thanks for reporting this issue. Could you share the failing shader `"line_directive.hlsl"`?

**Comment by henning-semler** [comment]
https://github.com/microsoft/DirectXShaderCompiler/blob/master/tools/clang/test/HLSLFileCheck/hlsl/preprocessor/line_directive/line_directive.hlsl

Just tried with the latest compiler from the latest SDK 10.0.18362.0 and there it works fine (should have checked that first..).

So I'll close the case.
Thanks
