### ISSUE TITLE
[SPIR-V] fatal error: generated SPIR-V is invalid:

### ISSUE THREAD

**Issue by rocketz** [microsoft/DirectXShaderCompiler#2506]
Hi! I got this error:

> fatal error: generated SPIR-V is invalid: Indexes passed to OpAccessChain must be of type integer.
  %241 = OpAccessChain %_ptr_Workgroup_uint %anPassIndices %240 %76

.. and I was able to isolate it to this:

```
#define CALC_THREADS 64
groupshared uint anPassIndices[2][CALC_THREADS];

void Stuff(uint nLaneIdx, out uint nTotal)
{
	uint idx = 0;
	for(uint nOffset = 1; nOffset < CALC_THREADS; nOffset <<= 1)
	{
		idx = 1 - idx;
        anPassIndices[idx][nLaneIdx] = anPassIndices[!idx][nLaneIdx] + (nLaneIdx >= nOffset ? anPassIndices[!idx][nLaneIdx - nOffset] : 0);
	}
	nTotal = anPassIndices[idx][CALC_THREADS - 1];
}

RWStructuredBuffer<uint> uav : register(u0);

[numthreads( 64, 1, 1 )]
void Blah(uint dtid : SV_DispatchThreadID)
{
	uint t;
	Stuff(dtid, t);
	uav[dtid] = t;
}
```

The bug goes away if I replace "!idx" with "1 - idx" like this:
anPassIndices[idx][nLaneIdx] = anPassIndices[1-idx][nLaneIdx] + (nLaneIdx >= nOffset ? anPassIndices[1-idx][nLaneIdx - nOffset] : 0);

**Comment by ehsannas** [comment]
Thanks for reporting @rocketz

**Comment by ehsannas** [comment]
Using the `!` operator on a unsigned int when indexing is somewhat peculiar. For example, if `idx` is `5`, then `!idx` would be:

a) cast `idx` from `uint` to `bool` (5 --> true)
b) perform `!` (true --> false)
c) cast `bool` back to `uint` for indexing into array (false --> 0).

**Comment by ehsannas** [comment]
I see that in your case idx is either 0 or 1. so it's less odd :)

either way, we should be able to handle this correctly.
