### ISSUE TITLE
Confusing error message when intrinsic called with wrong number of arguments

### ISSUE THREAD

**Issue by dmpots** [microsoft/DirectXShaderCompiler#2507]
t.hlsl
```
typedef uint T;

RWStructuredBuffer<T> buf;
[RootSignature("DescriptorTable(UAV(u0, numDescriptors=1))")]
[numthreads(64,1,1)]
void main(uint idx : SV_GroupIndex)
{
    T a = buf[idx];
    T b = buf[idx+1];
    T c = WaveActiveSum(a, b);
    buf[idx]  =  c;
}
```

Compiling gives an error (as it should), but is a confusing error.
```
λ dxc /Tcs_6_0 t.hlsl  /noprecompile
t.hlsl:10:11: error: use of undeclared identifier 'WaveActiveSum'
    T c = WaveActiveSum(a, b);
          ^
```

Would be better if the error said something about calling the function with the wrong number of arguments.

**Comment by pow2clk** [comment]
We need to change how we retrieve intrinsics. Currently, they are searched linearly with number of args being the first rejection criteria. This doesn't allow detecting usage of one that matches by name, but differs by number

**Comment by damyanp** [comment]
We're not planning on addressing this in DXC. In clang we use standard overload resolution for builtin functions and so nothing special needs to be done here.
