### ISSUE TITLE
[SPIR-V] Compiler crashes when encountering integer "mad" and generating SPIRV

### ISSUE THREAD

**Issue by rocketz** [microsoft/DirectXShaderCompiler#2511]
Hi!

There seems to be something weird going on with the "mad" intrinsic and integers. Sometimes I get this error:

```
error: mad intrinsic function unimplemented
                uint nCacheIdx = mad(groupThreadID.y, BLUR_SIZE_X, uint(u));
```

And with this small example the compiler simply crashes:
```
dxc.exe -T cs_6_0 -spirv -E Test_CS madbug.hlsl

Version: dxcompiler.dll: 1.5 - 1.5.0.2428 (HEAD, bd57c441)

RWTexture2D<float> g_Output : register(u0);
[numthreads(8, 8, 1)]
void Test_CS(uint2 DTid : SV_DispatchThreadID)
{
	int k = mad(DTid.y, 3, 4);
	g_Output[DTid] = k;
}
```

**Comment by ehsannas** [comment]
It looks like there are two enums for the intrinsic `mad`: `hlsl::IntrinsicOp::IOP_mad` and `hlsl::IntrinsicOp::IOP_umad`. We had missed the latter in the SPIR-V backend.
Fix is coming up shortly.
