### ISSUE TITLE
[SPIRV] Matrices' number of Location is wrong

### ISSUE THREAD

**Issue by Vincent-P** [microsoft/DirectXShaderCompiler#2522]
In this example, the `float4x3` matrice has a correct size of 48 in the cbuffer but still takes 4 Locations in the SPIRV. In the DXIL output the matrice takes 3 registers as expected.

```hlsl
struct PSInput
{
	float4x3 matrice : TEXCOORD0;
	float4 color : COLOR;
};

cbuffer bob
{
	float4x3 cmatrice;
	float4 ccolor;
};

float4 PSMain(PSInput input) : SV_TARGET
{
	return input.color + ccolor;
}
```

**Comment by jaebaek** [comment]
Based on [this spec](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#interfaces-iointerfaces-locations), if `float4x3` means "4 of `float3`", it must consume 4 locations.

If `float4x3` means "3 of `float4`", it must consume 3 locations.

Based on the generated SPIR-V,
```
      %float = OpTypeFloat 32
    %v3float = OpTypeVector %float 3
%mat4v3float = OpTypeMatrix %v3float 4
```
we interpret `float4x3` as "4 of `float3`".
As far as I understand, this interpretation is correct because the DXIL generated from this HLSL also contains `%class.matrix.float.4.3 = type { [4 x <3 x float>] }`.
```
%class.matrix.float.4.3 = type { [4 x <3 x float>] }
%ConstantBuffer = type opaque
%bob = type { %class.matrix.float.4.3, <4 x float> }
%struct.PSInput = type { %class.matrix.float.4.3, <4 x float> }
%dx.types.Handle = type { i8* }
```

Could you please point the exact DXIL output specify that it takes 3 registers?

**Comment by Vincent-P** [comment]
DXIL
http://shader-playground.timjones.io/c42b16aaa7bedf00c6f2c03893ccd64c
```
; Name                 Index   Mask Register SysValue  Format   Used
; -------------------- ----- ------ -------- -------- ------- ------
; TEXCOORD                 0   xyzw        0     NONE   float       
; TEXCOORD                 1   xyzw        1     NONE   float       
; TEXCOORD                 2   xyzw        2     NONE   float       
; COLOR                    0   xyzw        3     NONE   float       
```

SPIR-V
http://shader-playground.timjones.io/c54800194b1c8d1380c53511d7293fe1
```
               OpDecorate %in_var_TEXCOORD0 Location 0
               OpDecorate %in_var_COLOR Location 4
```

**Comment by jaebaek** [comment]
Thanks. We realize that this is a bug of `OpDecorate` for `Location`. Let me handle this issue.

**Comment by Vincent-P** [comment]
Awesome!

**Comment by jaebaek** [comment]
We considered this issue more and concluded that the current behavior does not violate the Vulkan spec even though it is different from the input/output interface of the generated DXIL.
If you change this as what DXC generates for DXIL, it will violate the Vulkan spec.

Vulkan spec says
```
If a declared input or output is an array of size n and each element takes m locations, it will be assigned m × n consecutive locations starting with the location specified.

If the declared input or output is an n × m 16-, 32- or 64-bit matrix, it will be assigned multiple locations starting with the location specified. The number of locations assigned for each matrix will be the same as for an n-element array of m-component vectors.
```

The generated SPIR-V for `float4x3 matrice : TEXCOORD0;` has `%mat4v3float` type.

```
%v3float = OpTypeVector %float 3
%mat4v3float = OpTypeMatrix %v3float 4
```

It means it must consume 4 locations based on the Vulkan spec.
Note that `%mat4v3float` must consume 4 locations regardless of its majorness.

What it means is that all `a, b, c` in the following HLSL must consume 4 locations when we generate SPIR-V:
```
column_major float4x3 a;
row_major float4x3 b;
float4x3 c;
```

**Comment by Vincent-P** [comment]
I would expect that `column_major` (or `row_major`? I am a bit confused with these), stores the columns one after the other, so it should be considered a 3-elements array of 4 component vectors.

But if it should not work like this then it is okay I guess,
Do you have a better workaround than splitting the `float4x3` in 3 `float4` to maintain compatibility with the DirectX layout?

**Comment by jaebaek** [comment]
Good question. I am sure this is one of the most confusing part of SPIR-V backend in DXC.

Please note that the majorness and the matrix shape (e.g., shape of float4x3 is 4 of float3) are independent.
We always translate `float4x3` into "4 float vectors whose number of elements is 3" regardless of its majorness.
The majorness only affect how a matrix keeps the data given by user.

For example, assuming that user gives 12 floats 1, 2, ..., 12 as a buffer,
- if it is `column_major float4x3`, it will be 4 vectors whose values are [1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12], respectively.
- if it is `row_major float4x3`, it will be 4 vectors whose values are [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], respectively.
However, for both cases, the meaning of `float4x3` is "4 of `float3`".

One of the thing may make you confused is that `OpTypeVector` in SPIR-V denotes a column major vector while `float3` in HLSL is a row major vector.

[SPIR-V.rst: Appendix A. Matrix Representation](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#appendix-a-matrix-representation) may be helpful.
Note that the notation I use for a vector "[1, 2, 3]" is different from the denotation this document uses.
I used "[1, 2, 3]" for "a vector (for both col- and row- major)" while the document use it for "a row".

**Comment by Vincent-P** [comment]
Thanks for your answer.
Am I missing something here or your buffer should be 1, 2, 3, 0, 4, 5, 6, 0, .., 12, 0.
With 0 being the padding of each location?

**Comment by jaebaek** [comment]
Ah maybe you are right. I did not check the detail but wanted to explain the concept.
Definitely, we must consider the padding (or alignment) when we pass values to vkbuffer.

Let me close this issue. I think we discuss it enough. Please let me know (by reopening this or opening a new bug) if there is other issues.
