### ISSUE TITLE
lld file as the input for dxc.exe invocations

### ISSUE THREAD

**Issue by galop1n** [microsoft/DirectXShaderCompiler#2531]
I thought it was possible already, so i may just miss the proper command line, maybe i just get confused with PIX able to do so. But if not, it can be a nice addition to the command line tool for debugging purposes. 

I guess it could be implemented as some sort of special include handler that could be even reusable in code.

**Comment by tex3d** [comment]
Yes, we should make it easy/possible to load from PDB with dxc.

**Comment by damyanp** [comment]
As this is 5 years old, and we're not exactly sure what is being request, closing this as not planned.  Feel free to reopen with more details about what the issue / request is.
