### ISSUE TITLE
Better error messages for SM 6.1 features

### ISSUE THREAD

**Issue by jholewinski** [Microsoft/DirectXShaderCompiler#255]
When I try to use the new Barycentrics functions in SM 6.0, I see:

```
error: validation errors
at 0x1f27aaae1c8 inside block entry of function ps_main Opcode BarycentricsCentroid not valid in shader model ps_6_0
at 0x1f27aaaec48 inside block entry of function ps_main Opcode BarycentricsCentroid not valid in shader model ps_6_0
at 0x1f27aaae008 inside block entry of function ps_main Opcode BarycentricsCentroid not valid in shader model ps_6_0
at 0x1f27aaae548 inside block entry of function ps_main Opcode Barycentrics not valid in shader model ps_6_0
at 0x1f27aaae468 inside block entry of function ps_main Opcode Barycentrics not valid in shader model ps_6_0
at 0x1f27aaae388 inside block entry of function ps_main Opcode Barycentrics not valid in shader model ps_6_0
at 0x1f27aaa4188 inside block entry of function ps_main Opcode BarycentricsSnapped not valid in shader model ps_6_0
at 0x1f27aaa47e8 inside block entry of function ps_main Opcode BarycentricsSnapped not valid in shader model ps_6_0
at 0x1f27aaa3b28 inside block entry of function ps_main Opcode BarycentricsSnapped not valid in shader model ps_6_0
at 0x1f27c304580 inside block entry of function ps_main Opcode BarycentricsSampleIndex not valid in shader model ps_6_0
at 0x1f27aaa5250 inside block entry of function ps_main Opcode BarycentricsSampleIndex not valid in shader model ps_6_0
at 0x1f27aaaf0b0 inside block entry of function ps_main Opcode BarycentricsSampleIndex not valid in shader model ps_6_0
```

While correct, it would be more helpful from a user perspective to catch these errors before validation and print an error referring to the original source location instead of printing errors about opcodes and what looks like LLVM Value* pointer values.

**Comment by marcelolr** [comment]
Agreed. You should get somewhat better error messages if we have debug information, FYI.

**Comment by jholewinski** [comment]
I don't see how compiler errors relate to debug symbol generation. I would expect dxc to catch this early in the compilation process, and report a helpful error with the line and column number of the error, similar to other clang errors.

**Comment by marcelolr** [comment]
Revisiting. I've started & stopped playing around with some potential fixes a number of times, should probably leave notes here as well.

The validation issue is more general than just Barycentrics - we generally allow constructs to exist that are potentially invalid in the front-end, because they may get cleaned up or removed by dead code removal later on.

That's why we do less aggressive validation in the front-end and we do one more strict validation pass when the final IR is emitted. At that stage, debug information helps in producing proper error messages.
