### ISSUE TITLE
PSO creation crashes with shaders compiled with -Vd "Disable validation" switch

### ISSUE THREAD

**Issue by fstrugar** [microsoft/DirectXShaderCompiler#2550]
Using "-Vd" with any shader causes

```
D3D12 ERROR: ID3D12Device::CreateInputLayout: Input Signature in bytecode could not be parsed.  Data may be corrupt or in an unrecognizable format. [ STATE_CREATION ERROR #63: CREATEINPUTLAYOUT_UNPARSEABLEINPUTSIGNATURE]
D3D12 ERROR: ID3D12Device::CreateVertexShader: Vertex Shader is corrupt or in an unrecognized format. [ STATE_CREATION ERROR #67: CREATEVERTEXSHADER_INVALIDSHADERBYTECODE]
D3D12 ERROR: ID3D12Device::CreatePixelShader: Pixel Shader is corrupt or in an unrecognized format. [ STATE_CREATION ERROR #93: CREATEPIXELSHADER_INVALIDSHADERBYTECODE]
```

(or similar)

Not sure if related to https://github.com/microsoft/DirectXShaderCompiler/issues/6

Repro code: https://github.com/fstrugar/D3D12HelloTriangle
(https://github.com/fstrugar/D3D12HelloTriangle/blob/master/HelloTriangle/D3D12HelloTriangle.cpp#L223)

Included are the dxc binaries from v1.4.1907 tag but I've recompiled the latest and it still happens.

**Comment by tex3d** [comment]
This is by-design.  `-Vd` disables validation and signing of shaders.  The D3D12 runtime expects only signed shaders at PSO create.  Shaders are signed as part of validation in dxil.dll from the Windows SDK, when this dxil.dll can be loaded by dxcompiler.dll.

For development purposes, you can create PSO with unsigned shaders.

To do this:
  1. Enable developer mode in control panel on the PC that will be running the shader
  2. Enable D3D12ExperimentalShaderModels feature **before creating a device** according to the instructions here:
https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-d3d12enableexperimentalfeatures

**Comment by fstrugar** [comment]
Fantastic, many thanks for the quick response! It'd be nice if either the 'dxc -help' or the error message at PSO creation time had a reference to this :)
