### ISSUE TITLE
question: d3dcompiler_43.dll shipped with which version of dx

### ISSUE THREAD

**Issue by mjkkirschner** [microsoft/DirectXShaderCompiler#2554]
Hello - apologies if this is not the correct place for such a query - 
My other searches failed to turn up anything concrete.

I am looking to find out what version of directX shipped the d3dcompiler_43.dll - it is part of the june2010 dx redistributable package - but that ships multiple dx versions.

I figured this community might know some of the history here.

**Comment by tex3d** [comment]
That June 2010 DirectX SDK and redistributable **was** the ship vehicle for this binary.  The compiler supports targeting multiple versions of DirectX that were available at that time as well (up to DirectX 11).  So there isn't a particular version of DirectX that shipped this dll.

The answer you're probably looking for is the **up to DirectX 11** part.

**Comment by mjkkirschner** [comment]
thanks!
