### ISSUE TITLE
[SPIRV] Invalid semantic reflection with -fspv-reflect/OpDecorateStringGOOGLE

### ISSUE THREAD

**Issue by Vincent-P** [microsoft/DirectXShaderCompiler#2557]
Hello,
There is a small problem with semantics when an input/output contains nested structs.
Here is a small example:
```hlsl
struct SInstanceData
{
    float4x3  VisualToWorld;
    float4    Output;
};

struct VS_INPUT  {
    float3         Position      : POSITION;
    SInstanceData  InstanceData  : TEXCOORD4;
};

float4 VSMain(const VS_INPUT v) : SV_Position
{
    const SInstanceData	I = v.InstanceData;
    return I.Output;
}

```

DXIL: http://shader-playground.timjones.io/8c56e64171eafb535ad44f2525e25888

SPIRV: http://shader-playground.timjones.io/a0ac29f7242867fa2bf253cf637c9d83

```
OpDecorateStringGOOGLE %in_var_POSITION HlslSemanticGOOGLE "POSITION"
OpDecorateStringGOOGLE %in_var_TEXCOORD4 HlslSemanticGOOGLE "TEXCOORD4"
OpDecorateStringGOOGLE %in_var_TEXCOORD5 HlslSemanticGOOGLE "TEXCOORD4"
```

I am expecting the last semantic to be `TEXCOORD5` but it is `TEXCOORD4` because that's what is indicated next to the struct in the input declaration.

The weird thing is that the name of the variable is correct so I guess it shouldn't be too hard to fix this?

**Comment by jaebaek** [comment]
Thank you for reporting this issue. I will quickly check it and get back here.

**Comment by Vincent-P** [comment]
Hi, any updates on this?
