### ISSUE TITLE
"Instruction does not dominate all uses!" validation error

### ISSUE THREAD

**Issue by simontaylor81** [microsoft/DirectXShaderCompiler#2561]
We're hitting "Instruction does not dominate all uses!" validation errors with one of our shaders. I manage to cut it down to a fairly minimal repro case, reproduced with the head of master (binaries from appveyor). Compile with `-E psMain -T ps_6_3`.

```
Texture2D<float4> g_texture;
float g_floatConst1;
float g_floatConst2;

float4 psMain() : SV_Target0
{
    if (!(g_floatConst2 == 0)) // ! is required, != without the ! does not fail
    {
        return g_floatConst1;
    }
    else
    {
        return g_texture.Load(0).x * g_floatConst1;
    }
}
```

Note the oddity around the `!` in the conditional provides an obvious workaround -- flip the `==` to `!=` and remove the `!`.

**Comment by vcsharma** [comment]
This no longer repros. So looks like it's fixed.
