### ISSUE TITLE
[SPIRV] OpImageFetch Offset/ConstOffset

### ISSUE THREAD

**Issue by Vincent-P** [microsoft/DirectXShaderCompiler#2562]
Hi,
Im having a weird issue when using `Texture.Load` with offsets in SPIRV.

Here is an example:
```hlsl
struct PS_INPUT
{
    float4 RasterPos : SV_Position;
};

struct PS_OUTPUT
{
    float4 Color0  : SV_Target0;
};

Texture2D Texture;

static const float2 TapTexelOffsets[8] = {
    {-1,-1},{+0,-1},{+1,-1}, {-1,+0},{+1,+0}, {-1,+1},{+0,+1},{+1,+1}
};

PS_OUTPUT psMain(PS_INPUT v)
{
    const int2 i2Center = (int2)v.RasterPos.xy;
    const int2 i2Offset = TapTexelOffsets[0];

    PS_OUTPUT Output2;
    Output2.Color0 = Texture.Load(int3(i2Center, 0/*iMip*/), i2Offset);
    return Output2;
}
```
http://shader-playground.timjones.io/1ae553060193dc59882cf144162958f6

When using a variable as an Offset, dxc generates an `Offset` image operand, even when the variable is const.
When the Offset is a litteral expression, dxc correctly uses `ConstOffset`.

The difference may be subtle but Im having weird random glitches when using variable as offset, but everything works fine when using a litteral expression or adding the offset to the texel position like so:
```hlsl
Output2.Color0 = Texture.Load(int3(i2Center + i2Offset, 0/*iMip*/));
```

I don't know if using `ConstOffset` makes sense when specifying a const variable, but editing the SPIRV manually to replace `Offset` with `ConstOffset` works.

So is it possible to generate `ConstOffset` when using const variable?

**Comment by ehsannas** [comment]
Thanks for reporting @Vincent-P . Interesting observation.

**Comment by ehsannas** [comment]
This is something that has to fixed in spirv-opt. I've posted https://github.com/KhronosGroup/SPIRV-Tools/pull/3024 to address it.

**Comment by ehsannas** [comment]
Fix landed in SPIRV-Tools and picked up in DXC via https://github.com/microsoft/DirectXShaderCompiler/pull/2585
