### ISSUE TITLE
Pl. Add compile support for 2019

### ISSUE THREAD

**Issue by chege011** [microsoft/DirectXShaderCompiler#2567]
Also, please support cmake whose version is above 3.4(for me, cmake version is 3.12)

**Comment by chege011** [comment]
Also, need dxc.exe and dxcAPI document

**Comment by Zingam** [comment]
You probably need to file a separate issue for CMAKE. Why aren't newer versions working for you?

**Comment by chege011** [comment]
o, I figure it out by changing hctbuild.bat, but there is a lot of code error in llvm in vs2019.
