### ISSUE TITLE
Fully qualified name in a constant buffer's type inhibits diagnostics

### ISSUE THREAD

**Issue by siliconvoodoo** [microsoft/DirectXShaderCompiler#2570]
consider this code:

```
struct SomeStruct
{
     bool abool;
};

ConstantBuffer<::SomeStruct> mycb;

float4 MainPS() :SV_Target0 
{
	::mycb.abool = true ;
	return (float4)0;
}
```
http://shader-playground.timjones.io/df4edec70af2e7f83d0c3805dd96e4b3

this result in a blank output. no diagnostic, no emission.
but if you would just remove the two-colon `::` in front of `::SomeStruct` line 6, you see the message:

> error: cannot assign to variable 'mycb' with const-qualified type 'const SomeStruct'

same semantic -> different result.

**Comment by pow2clk** [comment]
The error message is now the same with or without the `::` operator
