### ISSUE TITLE
Semantics not being exposed to DXIL

### ISSUE THREAD

**Issue by Nielsbishere** [microsoft/DirectXShaderCompiler#2576]
Hi, I've noticed that for DXIL, semantics are only outputted for structs and not for variables in cbuffers and resources (textures/sbuffers/etc.).
The current system I'm working on is totally dependent on these semantics to be available; it would be great if they could be available for reflection purposes only (like an annotation). 
Thanks.

**Comment by damyanp** [comment]
We're not planning on adding this functionality to DXC.
