### ISSUE TITLE
Defaults not being exposed to DXIL

### ISSUE THREAD

**Issue by Nielsbishere** [microsoft/DirectXShaderCompiler#2577]
Hi, when a cbuffer constant is defined, it compiles fine but the value isn't included in the DXIL. It would be great if this could be added as a reflection annotation.
Thank you.

**Comment by pow2clk** [comment]
Not a priority, won't fix.

**Comment by paulbartrum** [comment]
If this feature is not going to be supported, the docs should probably be updated to reflect that: https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-variable-syntax#Initial_Value
