### ISSUE TITLE
Crash in DxilAnnotateWithVirtualRegister for ray tracing (library) targets

### ISSUE THREAD

**Issue by kayru** [microsoft/DirectXShaderCompiler#2584]
DxilAnnotateWithVirtualRegister::runOnModule crashes when used on ray tracing shaders as it uses `m_DM->GetEntryFunction()`, which is null for `lib_6_x` targets. Issue can be easily reproduced like so.

**shader.hlsl**:

    RWStructuredBuffer<uint> Output;
    [numthreads(1,1,1)] void MainCS() { Output[0] = Output[Output[2]]; }
    [shader("raygeneration")] void MainRGS() { Output[0] = Output[Output[2]]; }

**compile_rgs.bat**:

    dxc /Odump /Od /T lib_6_5 shader.hlsl > passes.txt
    echo -dxil-annotate-with-virtual-regs>>passes.txt
    echo -print-module>>passes.txt
    dxc /fcgl /Od /T lib_6_5 shader.hlsl > output.hl.txt
    dxopt -pf passes.txt -o=output.opt.ll output.hl.txt > output.opt.hl.txt

Running similar steps for compute shader target works fine

**compile_cs.bat**:

    dxc /Odump /Od /E MainCS /T cs_6_5 shader.hlsl > passes.txt
    echo -dxil-annotate-with-virtual-regs>>passes.txt
    echo -print-module>>passes.txt
    dxc /fcgl /Od /E MainCS /T cs_6_5 shader.hlsl > output.hl.txt
    dxopt -pf passes.txt -o=output.opt.ll output.hl.txt > output.opt.hl.txt

Presumably `DxilAnnotateWithVirtualRegister` needs to run on all exported symbols in the library.

**Comment by jeffnn** [comment]
This is fixed with a not-so-recent PR to support libraries in PIX passes in general.
