### ISSUE TITLE
Better error message needed when /Fd is used for shader model <= 6.0

### ISSUE THREAD

**Issue by hekota** [microsoft/DirectXShaderCompiler#2593]
The /Fd flag is not supported for shader models below 6.1 since the validator version is bound to shader model version. However the error it gives is not very helpful:

```
dxc.exe /T ps_6_0 "d:\dxc\utils\hct\cmdtestfiles\smoke.hlsl" /Zi /Fd .\ /Fo smoke.hlsl.strip
```
Fails:

```
The system cannot find the path specified. .\
```

Works for shader model 6.1 and up.

**Comment by pow2clk** [comment]
This seems to work for me now. Is that worse? 😟

**Comment by pow2clk** [comment]
Fixed
