### ISSUE TITLE
Pre-release binaries vs appveyor artifacts vs Windows Kit: which one is right? 

### ISSUE THREAD

**Issue by jaykumarark** [microsoft/DirectXShaderCompiler#2599]
I am trying to use DXC in my project and I am having trouble deciding which are the official binaries for use? 

1. There is the pre-release binaries from the [release tab](https://github.com/microsoft/DirectXShaderCompiler/releases)  
2. There is the [Appveyor Artifacts](https://ci.appveyor.com/project/antiagainst/directxshadercompiler/branch/master/artifacts) which is what I am currently using but they are nightly builds if I understand correctly. But these essentially have all the dlls, libs and more importantly all the necessary headers. 
3. Then there are the dlls/.libs (dxcompiler, dxil) as part of the Windows Development Kit. 

If I want to use the reflection interfaces/compiler/validator/disassembler in my project, it seems like I would need more headers (if not all atleast some of them such as DXILContainers/DXILconstants.h) apart from just `dxcapi.h`. So I am at a loss here trying to figure out what is the best way to use the library.

**Comment by hekota** [comment]
The Appveyor Artifacts are build for each commit, so it's always going to be the latest version, but it is not signed and might be less stable than the official releases.
I would suggest using the binaries under the release tab. That is an official signed release and has a zip file with matching source code where you can get the header you need. 
The compiler in Windows Development Kits works too and although it might not be the newest version, it contains dxil.dll which you can use to validate and sign your compiled shaders. 
The dxil.dll can also be used with the newer compiler bits.

**Comment by jaykumarark** [comment]
The binaries from the release tab do not have all the headers I need to use the reflection API. For e.g., at the bare minimum if I need to get a `ID3D12ShaderReflection` interface, I need to write the following lines: 

`VERIFY_SUCCEEDED(pReflection->FindFirstPartKind(hlsl::DFCC_DXIL, &shaderIdx));
    VERIFY_SUCCEEDED(pReflection->GetPartReflection(shaderIdx, __uuidof(ID3D12ShaderReflection), (void**)ppReflection));`

But `hlsl::DFCC_DXIL` is defined `include\dxc\DxilContainer\DxilContainer.h` and that is not included along with the signed binaries in the releases tab.

**Comment by jaykumarark** [comment]
Also, I noticed that building from source doesn't output `dxil.dll`. Is it because that part of the code is not open sourced?

**Comment by hekota** [comment]
Correct, `dxil.dll` is not open sourced as it is used for official validation and signing of compiled shaders. We'll look into the missing header issue.

**Comment by tex3d** [comment]
`dxcapi.h` is intended to be all that's necessary to use the external API.  The missing fourcc values used with reflection API have been added to the dxcapi.h header in GitHub (see `DXC_PART_` defines).  Unfortunately, the Windows Kit contents have been frozen for a while and didn't get this update, or other API updates, but you still can use a newer version of the header from the GitHub source or artifacts.

You can use this newer header with the DxCompiler.dll binary in the Windows Kit, but the newer interfaces will not be implemented in that version.

Or you can use a newer DxCompiler.dll from AppVeyor artifacts, or really any version you want, with a newer header to get newer functionality and fixes.  Just make sure you put a copy of DXIL.dll from the SDK beside the dxc.exe/dxcompiler.dll you're using and you should be fine.

Soon, we should be making a new package under the release tab that will contain updated binaries and dxcapi.h, along with a DXIL.dll from the Windows Kit so you have one package with the latest updates and everything you should need.

**Comment by jaykumarark** [comment]
Thanks for that information. Are the binaries from the release tab same as the ones that get shipped with Windows updates?

**Comment by hekota** [comment]
While the binaries are built from the same code base the ones from the release tab will be typically newer.

**Comment by jaykumarark** [comment]
Thanks for clearing that up. Looking forward to updated release binaries with latest headers.  :)

**Comment by pow2clk** [comment]
Here is the new release: https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.5.2003
