### ISSUE TITLE
D3D12 Error: Hash check failed for DXILibrary

### ISSUE THREAD

**Issue by SakibSaikia** [microsoft/DirectXShaderCompiler#2601]
I am getting the following error from the D3D debug layer when trying to create a PSO. The shader compilation itself succeeds, and I can see that the library is signed. 

`D3D12 ERROR: ID3D12Device::CreateStateObject: Hash check failed for DXILibrary.pShaderBytecode: 0x0000020A8D0CFA10 [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]`

I am using `lib_6_3` and latest pre-built binary release of DXC/DXIL. What could cause errors like this and where should I start debugging? Any help will be greatly appreciated!

**Comment by tex3d** [comment]
Can you try the DxCompiler.dll from the latest 1910 release branch in the zip file here?
https://ci.appveyor.com/project/antiagainst/directxshadercompiler/builds/29059673/artifacts

Please let us know if the issue occurs with this version of the compiler, or if you have any other problems using it.

**Comment by SakibSaikia** [comment]
Hi Tex,

Thanks for the response. I got the latest and I still get the error although the reporting has changed.

**Comment by SakibSaikia** [comment]
I've attached the bytecode binary and the full list of PSO errors here. The exports looked like they were correct, so my plan was to work from the top.

[rtpso-error.zip](https://github.com/microsoft/DirectXShaderCompiler/files/3889716/rtpso-error.zip)

**Comment by SakibSaikia** [comment]
Hi Tex, I figured out the issue. The object holding the shader blob was going out of scope by the time the PSO was created. 😞

**Comment by VigneshMohan1698** [comment]
Hi SakibSaikia. I understand this is an old thread, But I am running into this issue and my shader blob is fine. Did you find any solutions to the error folder which you uploaded previously.
