### ISSUE TITLE
Crash compiling with -O0

### ISSUE THREAD

**Issue by simontaylor81** [microsoft/DirectXShaderCompiler#2608]
Hi there,

We're getting a crash compiling one of our shaders with -O0. Behaviour is very strange, seems related to arrays. I was able to confirm that it was introduced in commit f4965b71dd878c42c219ec00d31c406c483fd045.

 To repro, compile the following with `-E main -T ps_6_0 -O0`.

```
Texture2D<float4> g_textures[1];

float4 main() : SV_Target
{
	Texture2D<float4> textures[1];

	[unroll]
	for (uint i = 0; i < 1; ++i)
	{
		textures[0] = g_textures[0];
	}

	float4 c[1];
	c[0] = textures[0].Load(0);

	return c[0];
}
```

That's about as minimal as I can get it. Remove any of the arrays (replacing them with scalars) and it doesn't crash. Obviously the real shader looks nothing like this, so it's a bit harder to do that there :).

**Comment by pow2clk** [comment]
No longer repros. Fixed!
