### ISSUE TITLE
inconsistent ConstantBuffer syntax

### ISSUE THREAD

**Issue by Kamayuq** [microsoft/DirectXShaderCompiler#2610]
The ConstantBuffer types can neither be used with typedefs nor as struct members, but StructuredBuffers can, this is an inconsistency in the grammar. See:
http://shader-playground.timjones.io/070c4c9ef7ce96cfdf742209d09d4ab5

**Comment by tex3d** [comment]
Note: fxc also fails these cases (on use), so if fixed, errors should persist with `-HV 2015`.

**Comment by llvm-beanz** [comment]
Since this is the behavior of FXC and DXC, I think we're unlikely to change this without a strong motivator.
