### ISSUE TITLE
[Documentation/Wiki] mention Variable Rate Shading (VRS) support on Shader Model 6 overview page in SM6.4 section

### ISSUE THREAD

**Issue by didito** [microsoft/DirectXShaderCompiler#2617]
I think this [overview page ](https://github.com/microsoft/DirectXShaderCompiler/wiki/Shader-Model) should mention that **Shader Model 6.4** integrates support for Variable Rate Shading (`SV_ShadingRate`).

It gets mentioned in the [SM6.4 sub page](https://github.com/microsoft/DirectXShaderCompiler/wiki/Shader-Model-6.4), but I think it would be useful to have in the overview as well.

**Comment by pow2clk** [comment]
Done!
