### ISSUE TITLE
[spirv] Interpolator (shader stage output location) packing for SPIR-V target?

### ISSUE THREAD

**Issue by scottkircher** [microsoft/DirectXShaderCompiler#2618]
We are using dxc to compile HLSL to SPIR-V for the Vulkan port of our current project. Recently we have encountered a serious issue related to vertex shader outputs. In particular, it appears that no packing of interpolators is performed by the compiler. A declaration like this:

	float particle_user_Fire_Light_Scatter_Intensity : ATTR_FIRE_LIGHT_SCATTER_INTENSITY;
	float particle_user_Tempature_Crush : ATTR_TEMPATURE_CRUSH;
	float particle_user_ParticleOpacity : ATTR_PARTICLEOPACITY;

Turns into SPIR-V like this:

OpDecorate %out_var_ATTR_FIRE_LIGHT_SCATTER_INTENSITY Location 10
OpDecorate %out_var_ATTR_TEMPATURE_CRUSH Location 11
OpDecorate %out_var_ATTR_PARTICLEOPACITY Location 12

So, each single float is taking an entire float4 output location.

Therefore, we exceed the maximum number of vertex shader outputs far faster with Vulkan shaders than we do with our current DX SM5.0 shaders (which we are still compiling with fxc). We have a somewhat large number of shaders where this will be an issue. Manual packing is a possibility, but it makes the code less readable and is labor intensive, so we'd like to avoid it if possible.

Am I missing something? Is there a way to enable interpolator packing akin to what we have gotten for years with HLSL? If not, is this in the plans for dxc when targeting SPIR-V?

Thanks!

**Comment by ehsannas** [comment]
Thanks for reporting @scottkircher 

As you know `Location` numbers are used in Vulkan for interface matching. And dealing with them is complex (for instance if/when you have nested structs). I *think* the reason for the current design has been for simplicity of the logic. So far we hadn't heard complaints about users hitting the maximum limit of input/output locations. But looks like the time has come that we should support packing these interface variables.

**Comment by ehsannas** [comment]
HLSL uses string semantic assignments to achieve interface matching between different shader stages, but Vulkan doesn't have this concept and instead uses the Location assignments. So this has to be done quite carefully, and has to be done in a consistent way such that different stages compiled to SPIR-V using DXC result in matching (location,component) pairs for the same IO variables.

**Comment by ehsannas** [comment]
The current code only uses `Location` decorations (and doesn't use the `Component` decoration).

> Component
Must only be used on a memory object declaration or a member of a structure type. Indicates which component within a Location will be taken by the decorated entity. Only valid for the Input and Output Storage Classes.

We need to take advantage of this decoration to pack the locations more tightly.

**Comment by scottkircher** [comment]
Thanks, this does sound like it would do the trick. For now, we were able to keep moving forward by doing manual packing on the shaders that needed it, but I expect we'll bump up against this limit more frequently in the future, especially for tessellation shaders (Doing things like crack-free displacement and PN triangles balloons the number of tessellation control shader outputs real fast).

**Comment by scottkircher** [comment]
Has there been any movement on this? The aforementioned tessellation case is biting us now. We're exceeding the hardware max outputs per tessellation control vertex by quite a bit. Would be nice to have auto-packing in the SPIR-V backend, as is available in the DXIL backend.

**Comment by scottkircher** [comment]
Didn't receive a reply last week, so bumping this again. :) Trying to work around this with manual packing in all cases is likely to be difficult. Thanks!

**Comment by sudonatalie** [comment]
I'm not sure why this was reopened after being closed, since I believe that the signature packing work by @jaebaek should satisfy this use case. However, if I've missed any context and this is still an issue please feel free to comment and I'll reopen.
