### ISSUE TITLE
[SPIR-V] Compiler ignores the groupshared variable parameter from included files

### ISSUE THREAD

**Issue by dendron2000** [microsoft/DirectXShaderCompiler#2623]
The compiler would spit out not very helpful error messages like:

> fatal error: generated SPIR-V is invalid: In the Vulkan environment, cannot store to Uniform Blocks                                                                                                                                                                                        OpStore %61 %float_0 

It doesn't even mention the source line. By trial and error I found out that it seems to loose the "groupshared" property **when it comes from an included file** and therefore assumed the variable to be uniform. Moving the variable declaration directly into the compiled file fixed the problem.

**Comment by ehsannas** [comment]
Thanks for reporting @dendron2000

**Comment by jaebaek** [comment]
Hi @dendron2000 , I just tested

1. simple.hlsl with `dxc -Tps_6_0 -spirv -fcgl simple.hlsl -Fc simple.spv`
```
groupshared float4 gs;

float4 main(float4 color : COLOR) : SV_TARGET {
  if (color.a == 1.0f)
    gs = color;
  return color + gs;
}
```

2. simple2.hlsl
```
#include "header.hlsl"

float4 main(float4 color : COLOR) : SV_TARGET {
  if (color.a == 1.0f)
    gs = color;
  return color + gs;
}
```
and header.hlsl with `dxc -Tps_6_0 -spirv -fcgl simple2.hlsl -Fc simple.spv`
```
groupshared float4 gs;
```

They have the same result.
I tested them with the top-of-tree DXC (git hash: 925a79f8a883012957d46e738847449e5b18bb06).

Could you please give me sample code to reproduce your problem?
