### ISSUE TITLE
dxcapi.use.h is not compatible with C++20 / VS2019

### ISSUE THREAD

**Issue by baesky** [microsoft/DirectXShaderCompiler#2635]
when I use "dxcapi.use.h", I got a error:

> ThirdParty\DXC\include\dxc\Support\dxcapi.use.h(149,1): error C2059: syntax error: 'module'

winsdk:18362, HMODULE defined in minwindef.h and wtypes.h was different. I use vs2019 16.4.2. 
How can I bypass it?

**Comment by tex3d** [comment]
This looks like an incompatibility between these headers when STRICT is defined (by default).

In wtypes.h:
```
typedef void *HMODULE;
```

In minwindef.h:

```
#ifndef NO_STRICT
#ifndef STRICT
#define STRICT 1
#endif
#endif /* NO_STRICT */
```
then:
```
DECLARE_HANDLE(HINSTANCE);
typedef HINSTANCE HMODULE;      /* HMODULEs can be used in place of HINSTANCEs */
```

See `DECLARE_HANDLE` in winnt.h:
```
#ifdef STRICT
typedef void *HANDLE;
#if 0 && (_MSC_VER > 1000)
#define DECLARE_HANDLE(name) struct name##__; typedef struct name##__ *name
#else
#define DECLARE_HANDLE(name) struct name##__{int unused;}; typedef struct name##__ *name
#endif
#else
typedef PVOID HANDLE;
#define DECLARE_HANDLE(name) typedef HANDLE name
#endif
```

So try defining NO_STRICT and see if that fixes it.

**Comment by tex3d** [comment]
Alternatively, you could avoid including wtypes.h, which appears to be incompatible with STRICT.

**Comment by tex3d** [comment]
Hang on, I just realized that the incompatible HMODULE definition in wtypes.h is only included `if !defined (_WIN32) && !defined(_MPPC_)`, so could that be your problem?

**Comment by baesky** [comment]
> Hang on, I just realized that the incompatible HMODULE definition in wtypes.h is only included `if !defined (_WIN32) && !defined(_MPPC_)`, so could that be your problem?

_WIN32 is defined(by compiler?!), _MPPC_ is not defined. I try to define NO_STRICT/STRICT , still the same issue.

**Comment by baesky** [comment]
I think I find out why this happened.
In c++20 , **module** is a [key words](https://en.cppreference.com/w/cpp/keyword). If I change the variable name to anything else, every thing goes fine. Looks like vs2019 default c++ Language Standard is c++20. Suggest rename "module" to something else.

**Comment by tex3d** [comment]
@baesky, does PR #2667 fix the issue for you?
