### ISSUE TITLE
[spirv] if block inside while loop produces an invalid SPIR-V module

### ISSUE THREAD

**Issue by Cry-Mory** [microsoft/DirectXShaderCompiler#2643]
Compiling [illum2.frag.txt](https://github.com/microsoft/DirectXShaderCompiler/files/4046877/illum2.frag.txt) with latest DXC seems to produce invalid SPIR-V code. Vulkan validation layer complains about it with the following message:

>  [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: Header block 52[%52] is contained in the loop construct headed by 44[%44], but it's merge block 47[%47] is not
  %52 = OpLabel

The command used to compile the shader with DXC is as follows:

> dxc.exe  -fvk-use-dx-position-w -O3 -Zpr -spirv -no-warnings -E IlluminationPS -T ps_5_0 -Fo illum2.spirv illum2.frag.txt

The compiled SPIR-V is [illum2.spirv.txt](https://github.com/microsoft/DirectXShaderCompiler/files/4046894/illum2.spirv.txt) and human readable version is [illum2.spirv.h.txt](https://github.com/microsoft/DirectXShaderCompiler/files/4046892/illum2.spirv.h.txt).

**Comment by jaebaek** [comment]
@Cry-Mory Thank you for reporting this issue. I will take a look!

**Comment by jkunstwald** [comment]
I can confirm this bug, it also occurs on if blocks inside for loops, and is unchanged by omitting any of the non-essential flags listed above (`-Zpr -no-warnings -O3 -fvk-use-dx-position-w`). In my case the target is `cs_6_3`

**Comment by jaebaek** [comment]
Hmm ... @Cry-Mory could you please share the application with me? I cannot reproduce it ..
Based on the up-to-date spirv-val, it does not report validation error. I guess if the Vulkan validation layer checked the shader module, it might use spirv-val. In my opinion, SPIRV-Tools fixed this issue at some point and maybe LunarG SDK is a little bit old.

**Comment by jkunstwald** [comment]
To update: This warnings still appears in SDK 1.2.131.1, i didn't try the latest spirv-val as a standalone however.

**Comment by jkunstwald** [comment]
@jaebaek any updates on this? What is the output of `spirv-val.exe --version` on the version you tested with? Would it help if i provided the HLSL and SPIR-V?

**Comment by zhaijialong** [comment]
@jaebaek We have the same issue here.

**Comment by ClemensRoegner** [comment]
Running into the same issue (SDK 1.2.131.2)

**Comment by zhaijialong** [comment]
@jaebaek The issue still exists with lastest SDK 1.2.135. And if I compile the same shaders with shaderc(glslang), there aren't any validation errors.

**Comment by ehsannas** [comment]
Sorry for the delay on this folks. @jkunstwald would you please share your HLSL shader? Thanks

**Comment by jkunstwald** [comment]
@ehsannas yes, this one is it:
[specular_map_filter.hlsl.txt](https://github.com/microsoft/DirectXShaderCompiler/files/4457748/specular_map_filter.hlsl.txt)

**Comment by ehsannas** [comment]
Thanks

**Comment by ehsannas** [comment]
This was an issue in SPIRV-Tools that has been fixed. 
See: 
https://github.com/KhronosGroup/SPIRV-Tools/pull/3068
https://github.com/KhronosGroup/SPIRV-Tools/issues/3260

You might be getting the issue because you are using an older DXC version that hadn't picked up the SPIRV-Tools fix.

Please recompile your HLSL shader using the tip-of-tree DXC. That should fix it. Feel free to reopen the issue if you still get the error in latest DXC. Thanks.
