### ISSUE TITLE
Building Sources page needs to be updated

### ISSUE THREAD

**Issue by 44DA133A8B** [microsoft/DirectXShaderCompiler#2646]
I can not build the compiler using build steps from here: https://github.com/Microsoft/DirectXShaderCompiler/wiki/Building-Sources

Here's what I did:
1. installed Git, VS 2017, Python 3.8, CMake 3.11.2, WDK
2. cloned the project: "git clone https://github.com/microsoft/DirectXShaderCompiler.git"
3. launched "utils\hct\hctshortcut.js"
4. launched the HLSL console shortcut
5. executed "hctbuild" in the console

hctbuild fails with the following error:
```
CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "3" (found
  C:/Users/x/AppData/Local/Microsoft/WindowsApps/python3.exe)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindPythonInterp.cmake:155 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:413 (find_package)
```
It seems that Python 3.8 is not supported, but there is no build older than 3.7 on "python.org".

According to the following issue, Python 3.7 also does not work: https://github.com/microsoft/DirectXShaderCompiler/issues/2616

Also, hctbuild writes the following message to the console window at the end of the log, when an error is detected:
`CMake 3.4 is the currently supported version - your installed cmake may be out of date.`

I tried using the latest version of CMake (3.16.0), but it fails with a different error:
```
-- Constructing LLVMBuild project information
CMake Error at CMakeLists.txt:465 (message):
  Unexpected failure executing llvm-build:
```
I'm attaching CMake log files:
[CMakeError.log](https://github.com/microsoft/DirectXShaderCompiler/files/4054566/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/DirectXShaderCompiler/files/4054567/CMakeOutput.log)

Issues:
1. The list of required software does not contain CMake
2. "utils\hct\hctgettaef.py" does not work, I had to install WDK to solve the issue with missing TAEF
3. "hctbuild" fails because the required version of CMake is incompatible with modern Python builds

**Comment by hekota** [comment]
Hello,

Thank you for reporting this is. You are right, the instructions need to be updated.

Python:
Please delete `C:/Users/x/AppData/Local/Microsoft/WindowsApps/python3.exe`, run hctclean and restart the console window. It is just an empty placeholder or a link to install python, not an actual python installation.

CMake:
I should be ok to use a slightly different version of cmake, the script just lists the versions that we tested with. Although if you are having issues with the latest one after working out the python issue I would try an older version. 

utils/hct/hctgetatef.py:
The script works intermitently based on the availibility of the TAEF nugget that it is accesing. I've been trying to find a more reliable source for the nuget but could not find one. The most reliable way of getting the TAEF is to install Windows Driver Kit as you did.

I hope this helps.

**Comment by llvm-beanz** [comment]
I've updated the wiki page to refer to the documentation that lives in the source tree which we keep up to date.
