### ISSUE TITLE
DXC compile crash when creating a static Texture2D[] from srvs

### ISSUE THREAD

**Issue by Nielsbishere** [microsoft/DirectXShaderCompiler#2651]
I can't forward the entire source, but it crashes when this HLSL is added.
```cpp
static Texture2D texArray[6] = {
	tex0, tex1, tex2, tex3, tex4, tex5
};

//Read from pixel shader texArray[0] somewhere down here
```
When tex0-tex5 are defined as SRV slots, dxc crashes internally with a read access violation (New was 0xFFFFFFFFFFFFFFEF). This is the callstack:
![image](https://user-images.githubusercontent.com/28758736/72516588-340d9300-3852-11ea-86f1-5151a5e74940.png)
This version is an older version of DXC since it is modified, however; this is still present in the latest revision (trunk on 2019-05-15). As inputting this into Tim Jones's shader playground crashes the compiler too.

**Comment by Nielsbishere** [comment]
@tex3d

**Comment by Nielsbishere** [comment]
Still present.

**Comment by pow2clk** [comment]
While I recognize and respect that you can't share the full code, a simple repro would go a long way toward facilitating our ability to look at this and making sure we're on the same page. I took a crack at writing up a shader that met the criteria you laid out and I couldn't reproduce the crash. Here it is:

```hlsl
Texture2D<float4> tex0 : register(t0);
Texture2D<float4> tex1 : register(t1);
Texture2D<float4> tex2 : register(t2);
Texture2D<float4> tex3 : register(t3);
Texture2D<float4> tex4 : register(t4);
Texture2D<float4> tex5 : register(t5);
SamplerState g_samp : register(s0);

static Texture2D texArray[6] = {
	tex0, tex1, tex2, tex3, tex4, tex5
};

[RootSignature("RootFlags(ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT), DescriptorTable(SRV(t0), SRV(t1), SRV(t2), SRV(t3), SRV(t4), SRV(t5)), StaticSampler(s0, addressU = TEXTURE_ADDRESS_WRAP, addressV = TEXTURE_ADDRESS_WRAP, filter = FILTER_MIN_MAG_LINEAR_MIP_POINT)")]
float4 main() : SV_Target
{
  return texArray[0].Sample(g_samp, float2(0.0, 0.0));
}
```

Could you suggest what this might be missing from this or else provide one of your own?

**Comment by Nielsbishere** [comment]
It might be fixed in a newer version of dxc due to various commits since that time. I will get back to you on monday if I'm unable to reproduce this issue with the shader we encountered it in.
The example you stated seems fine, except we didn't specify the texture's format. Which to my knowledge does not matter, but might signal something internally if that can help you.
That's the minimal test case, I am not able to provide you with the closed source code unfortunately.

**Comment by pow2clk** [comment]
I was working under the assumption that the texture's format wouldn't matter. Again, I completely understand that you can't just dump your shaders here.

Monday will be fine. Thanks!

**Comment by Nielsbishere** [comment]
Seems like it's fixed in the current version. 👍
