### ISSUE TITLE
StripResourcesReflection() sets all to null

### ISSUE THREAD

**Issue by sunillnaik** [microsoft/DirectXShaderCompiler#2653]
I dont understand below code which is setting all the resource names to null.
https://github.com/microsoft/DirectXShaderCompiler/blob/0532d8cd08c9535af2ca5407a3c6289766312f53/lib/DXIL/DxilModule.cpp#L1566

I wasn't able to get a resource name for CBuffer. Commenting this fixed my issue.

**Comment by BitMD** [comment]
Resource information is preserved in separate reflection part.  This is by design.
