### ISSUE TITLE
Unused private field *Keyword is warned as error

### ISSUE THREAD

**Issue by sunillnaik** [microsoft/DirectXShaderCompiler#2654]
Since I compile DXC with flag treat warning as error. below field is unused. maybe good to cleanup.
https://github.com/microsoft/DirectXShaderCompiler/blob/0532d8cd08c9535af2ca5407a3c6289766312f53/tools/clang/include/clang/Sema/Sema.h#L1507

**Comment by pow2clk** [comment]
@gongminmin fixed this. Thanks!
