### ISSUE TITLE
MeshShader, ViewInstancing, "Primitive Outputs dependent"

### ISSUE THREAD

**Issue by Jay-Jiewu-Lu** [microsoft/DirectXShaderCompiler#2661]
if I change below shader a little to test primitive viewid,
test/CodeGenHLSL/mesh-val/multipleSetMeshOutputCounts.hlsl
with below change:
      //op.layer[0] = mpl.layer[0];
      op.layer[0] = vid;
is below correct? I thought "**_Primitive Outputs dependent_**" shouldn't be empty?
thanks!

==================*.ll file=================
; Number of inputs: 0, outputs: 17, primitive outputs: 15
; Outputs dependent on ViewId: { 0, 1, 2, 3, 4, 8, 12, 16 }
**; Primitive Outputs dependent on ViewId: {  }**

**Comment by pow2clk** [comment]
I made the edits to the best of my ability [here](https://godbolt.org/z/Krne6cx3b) and I don't see the indicated output. Given that and the age, I'm going to close this out, but if you can give some additional information, ideally with a godbolt link, we can look at this again.
