### ISSUE TITLE
[SPIR-V] Texture Sampling Without LOD  Allowed in Vertex Shader

### ISSUE THREAD

**Issue by nicebyte** [microsoft/DirectXShaderCompiler#2663]
Calls like `someTexture.Sample(sampler, uv)` in the vertex shader aren't rejected when using the SPIR-V backend. 

### Functional Impact

The emitted SPIR-V  does not contain any instructions for sampling the image; instead the result of the texture read is replaced with random values. This behavior can be very unexpected for the shader programmer.

### Minimal repro steps

Feed the following code into dxc while turning spir-v codegen on:

```
[[vk::binding(2, 0)]] uniform sampler s;
[[vk::binding(3, 0)]] uniform Texture2D<float4> t;

struct PSInput
{
	float4 position : SV_Position;
    float4 color : COLOR0;
};

PSInput VSMain(float2 uv : TEXCOORD) {
	PSInput res = { float4(0.0, 0.0, 0.0, 0.0), t.Sample(s, uv) };
    return res;
}
```

### Expected result
Above code is rejected (the same way that it would have been if the dxil codegen was in use)

### Actual result
The code is not rejected.

**Comment by jaebaek** [comment]
@nicebyte Thank you for reporting this issue! I will take a look

**Comment by luckyxxl** [comment]
I just had the same issue in a compute shader, so I suppose any stages aside from the fragment stage are affected.

Thank you for looking into it!

**Comment by luckyxxl** [comment]
fixed by https://github.com/microsoft/DirectXShaderCompiler/pull/3128
