### ISSUE TITLE
Only native filesystem paths can be added to include search paths (-I)

### ISSUE THREAD

**Issue by robbiesri** [microsoft/DirectXShaderCompiler#2669]
I was having trouble including some headers in my shader. When I started to mess around with the CLI, I realized it was because of the format of the path I was handing off to dxc.exe

```
> dxc.exe -I c:/temp -T vs_6_0 -spirv -E vsmain -Fo c:/temp/draw.vs.spv c:/temp/draw.hlsl
draw.hlsl:18:10: fatal error: 'ConstantBufferStructs.h' file not found
```

But if I use a Windows-style path for the include, it works?
```
> dxc.exe -I c:\temp -T vs_6_0 -spirv -E vsmain -Fo c:/temp/draw.vs.spv c:/temp/draw.hlsl
<print money>
```
It's weird that the input file and -Fo accept paths with forward slashes, but not -I?

I use CMake to generate the custom build rules, so I can convert the paths to the 'native' Windows stile with `file(TO_NATIVEPATH ...)`. But...I'm still surprised by this behavior.

I reproduced this on Windows 10, with DirectXShaderCompiler commit 9c89a1c2.

**Comment by pow2clk** [comment]
From https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#paths :

> File I/O functions in the Windows API convert "/" to "\" as part of converting the name to an NT-style name, except when using the "\\?\" prefix as detailed in the following sections.

That explains why the -Fo and other paths accept slashes.  I agree this means the include directory should follow the same rules. I have a one line fix ready to go.

In my testing, relative include paths with forward slashes were successful. Let me know @robbiesri if that's not the case for you.
