### ISSUE TITLE
[SPIR-V] HLSL to SPIR-V with subgroup extensions

### ISSUE THREAD

**Issue by bzm3r** [microsoft/DirectXShaderCompiler#2692]
In GLSL, there are many subgroup instrinsics available via Vulkan extensions for GLSL. To some extent, this is true for HLSL, but many intrinsics are not available, as DX12/DXIL does not support them. For example, there is no way to write something in HLSL so that it compiles to the SPIR-V instruction [`GroupNonUniformShuffleXor`](http://shader-playground.timjones.io/21977c71ea7e69d253b28a7426fb92e2). 

Is there a way (possibly experimental?) to write HLSL which compiles to subgroup related SPIR-V extensions not supported by DX12?

**Comment by jaebaek** [comment]
@bzm3r Thank you for your question. We have something like `[[vk::...]]` but I am not sure. Let me check it.
