### ISSUE TITLE
[SPIR-V] Implement printf()

### ISSUE THREAD

**Issue by jaebaek** [microsoft/DirectXShaderCompiler#2707]
HLSL has [printf](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/printf?redirectedfrom=MSDN).
SPIR-V also has printf in [OpenCL Extended Instruction Set Specification](https://www.khronos.org/registry/spir-v/specs/unified1/OpenCL.ExtendedInstructionSet.100.html#printf).
We can support `printf()` for SPIR-V codegen.

**Comment by dneto0** [comment]
The SPIR-V backend on DXC targets Vulkan (maybe OpenGL) shaders, and none of those drivers support the OpenCL extended instruction sets.

**Comment by ehsannas** [comment]
Done via #2829
