### ISSUE TITLE
[SPIR-V] FP16 texture objects result in invalid SPIR-V

### ISSUE THREAD

**Issue by aras-p** [microsoft/DirectXShaderCompiler#2711]
Trying to evaluate how well DXC deals with "low precision" texture types. Using a shader like:
```
Texture2D<half> MyTex;
SamplerState MySampler;
half4 PSMain(float2 uv : TEXCOORD0) : SV_TARGET
{
    return MyTex.Sample(MySampler, uv);
}
```
and compiling it to ps_6_2 with enabled 16-bit types works fine for DXIL, but trying to target SPIR-V says
```
fatal error: generated SPIR-V is invalid: Expected Sampled Type to be a 32-bit int or float scalar type for Vulkan environment
  %type_2d_image = OpTypeImage %half 2D 2 0 0 1 Unknown

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

Shader Playground link: http://shader-playground.timjones.io/e5f6af598102c89a811379d9cf599a8d

**Comment by ehsannas** [comment]
Thanks for reporting @aras-p

**Comment by ehsannas** [comment]
Sadly this is a limitation of Vulkan itself at the moment.
See [Vulkan Specifications document](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html):

> OpTypeImage must declare a scalar 32-bit float or 32-bit integer type for the “Sampled Type”. (RelaxedPrecision can be applied to a sampling instruction and to the variable holding the result of a sampling instruction.)

So we can't support it in the tools until it is accepted by the Vulkan spec.

Thanks for bringing this up.

**Comment by ehsannas** [comment]
It is possible for DXC's SPIR-V backend to generate an OpTypeImage with a 32-bit type under the hood, and then convert to/from the 16-bit type before/after reads and writes. While this will make things work, I wonder if it'll bring the benefits that the developer is looking for (and the conversions will add some overhead).

If Vulkan doesn't support it natively and it is a highly sought-after feature, we can do this in the future.

**Comment by jaebaek** [comment]
@sindney recommended us to decorate the image type with `RelaxedPrecision` instead of using the 16-bits float.
We can do it in [LowerTypeVisitor for image type](https://github.com/microsoft/DirectXShaderCompiler/blob/master/tools/clang/lib/SPIRV/LowerTypeVisitor.cpp#L558).

**Comment by sindney** [comment]
Hi @jaebaek, I'm trying to support this conversion, but it seems even harder to implement in dxc.
What we need is this:
```
OpDecorate %14 RelaxedPrecision
OpDecorate %46 RelaxedPrecision
OpDecorate %49 RelaxedPrecision
[add relaxed percision for modified]

%float = OpTypeFloat 32
[Insert OpTypeFloat to the top of types]

%14 = OpTypeImage %float 2D 0 0 0 1 Unknown
[Change half to float to bypass vulkan spec.]

%v4float = OpTypeVector %float 4
[New v4float type]

%46 = OpImageSampleImplicitLod %v4float %43 %45
%49 = OpFConvert %v4half %46
[Add convert op to convert sample back to half.]
OpStore %OutColor %49
```

1. With enable16BitTypes=true, and OpTypeImage elementType is half/short.
2. Set OpTypeImage's elementType to 32-bit float/int/uint types, mark relaxed.
3. Set OpImage's result type to the same 32-bit types, mark relaxed.
_Because the spec says:
Result Type must be a vector of four components of floating-point type or integer type. Its components must be the same as Sampled Type of the underlying OpTypeImage (unless that underlying Sampled Type is OpTypeVoid)._
4. Then we need to add a FConvert op to convert OpImage's new result type to half type.
So following instructions like 'OpCompositeExtract %half' will work.
And hopefully this extra relaxed 32-bit type to 16-bit convert op will be killed in glsl/msl backend.

I'm currently stuck in this final step, i couldn't find a place or easy way to insert the convert instruction. 😞 
Maybe it's easier to do this in spirv-tools?

These are the changes I've done so far:

```bash
--- a/tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
+++ b/tools/clang/lib/SPIRV/LowerTypeVisitor.cpp
@@ -112,11 +112,64 @@ bool LowerTypeVisitor::visitInstruction(SpirvInstruction *instr) {
     // Wrap the image type in sampled image type if necessary.
     if (!isa<SampledImageType>(resultType)) {
       assert(isa<ImageType>(resultType));
       instr->setResultType(
           spvContext.getSampledImageType(cast<ImageType>(resultType)));
     }
     break;
   }
+  // Result Type must be a scalar of integer type or floating-point type. It
+  // must be the same as Sampled Type of the underlying OpTypeImage.
+  case spv::Op::OpImageSampleDrefImplicitLod:
+  case spv::Op::OpImageSampleDrefExplicitLod:
+  case spv::Op::OpImageSampleProjDrefImplicitLod:
+  case spv::Op::OpImageSampleProjDrefExplicitLod:
+  // Result Type must be a scalar or vector of floating-point type or integer
+  // type. It must be a scalar or vector with component type the same as Sampled
+  // Type of the OpTypeImage (unless that Sampled Type is OpTypeVoid).
+  case spv::Op::OpImageSampleImplicitLod:
+  case spv::Op::OpImageSampleExplicitLod:
+  case spv::Op::OpImageSampleProjImplicitLod:
+  case spv::Op::OpImageSampleProjExplicitLod:
+  case spv::Op::OpImageFetch:
+  case spv::Op::OpImageGather:
+  case spv::Op::OpImageDrefGather:
+  case spv::Op::OpImageRead: {
+    if (!spvOptions.enable16BitTypes)
+      break;
+
+    const SpirvType *elementType = resultType;
+    uint32_t elementCount = 1;
+    if (auto vector = dyn_cast<VectorType>(resultType)) {
+      elementType = vector->getElementType();
+      elementCount = vector->getElementCount();
+    }
+    auto numerical = dyn_cast<NumericalType>(elementType);
+    if (numerical && numerical->getBitwidth() == 16) {
+      instr->setRelaxedPrecision();
+      if (auto integer = dyn_cast<IntegerType>(resultType)) {
+        auto isSigned = integer->isSignedInt();
+        if (elementCount == 1) {
+          instr->setResultType(isSigned ? spvContext.getSIntType(32)
+                                        : spvContext.getSIntType(32));
+        } else {
+          elementType = isSigned ? spvContext.getSIntType(32)
+                                 : spvContext.getSIntType(32);
+          instr->setResultType(
+              spvContext.getVectorType(elementType, elementCount));
+        }
+      } else {
+        if (elementCount == 1) {
+          instr->setResultType(spvContext.getFloatType(32));
+        } else {
+          elementType = spvContext.getFloatType(32);
+          instr->setResultType(
+              spvContext.getVectorType(elementType, elementCount));
+        }
+      }
+    }
+    break;
+  }
   // Variables and function parameters must have a pointer type.
   case spv::Op::OpFunctionParameter:
   case spv::Op::OpVariable: {
@@ -554,6 +607,18 @@ const SpirvType *LowerTypeVisitor::lowerResourceType(QualType type,
       const auto sampledType = hlsl::GetHLSLResourceResultType(type);
       auto loweredType = lowerType(getElementType(astContext, sampledType), rule,
                     /*isRowMajor*/ llvm::None, srcLoc);
+
+      // OpTypeImage must declare a scalar 32-bit float, 64-bit integer, or
+      // 32-bit integer type for the <A1><B0>Sampled Type<A1><B1>
+      // So we convert half/short to 32-bit float/32-bit integer.
+      if (loweredType->getKind() == SpirvType::Kind::TK_Float ||
+          loweredType->getKind() == SpirvType::Kind::TK_Integer) {
+        if (static_cast<const spirv::NumericalType *>(loweredType)
+                ->getBitwidth() == 16) {
+          loweredType = spvContext.getFloatType(32);
+        }
+      }
+
       // Treat bool textures as uint for compatibility with OpTypeImage.
       if (loweredType == spvContext.getBoolType()) {
         loweredType = spvContext.getUIntType(32);
diff --git a/tools/clang/lib/SPIRV/RelaxedPrecisionVisitor.cpp b/tools/clang/lib/SPIRV/RelaxedPrecisionVisitor.cpp
index f64a5e6fb..c0c58e0d9 100644
--- a/tools/clang/lib/SPIRV/RelaxedPrecisionVisitor.cpp
+++ b/tools/clang/lib/SPIRV/RelaxedPrecisionVisitor.cpp
+          if (const auto *builtinType = ty->getAs<BuiltinType>()) {
+            switch (builtinType->getKind()) {
+            case BuiltinType::Half:
+            case BuiltinType::HalfFloat:
+            case BuiltinType::Short:
+            case BuiltinType::UShort:
+              if (!inst->getImage()->isRelaxedPrecision()) {
+                inst->getImage()->setRelaxedPrecision();
+                inst->setRelaxedPrecision();
+                return true;
+              }
+            default:
+              break;
+            }
+          }
+        }
+      }
+    }
+  }
+
   // If the operation result type or the underlying image type is relaxed
   // precision, the instruction can be considered relaxed precision.
   if (isRelaxedPrecisionType(inst->getAstResultType(), spvOptions) ||
```

**Comment by jaebaek** [comment]
@sindney Before going further, please test a manually updated shader first because updating the compiler will need not-small engineering effort.

I think we can use "[convert-relaxed-to-half](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/optimizer.cpp#L440)" pass for the step 4, but you have to check what is the input the convert-relaxed-to-half pass requires. Based on [this unittest](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/test/opt/convert_relaxed_to_half_test.cpp#L193), I guess it will convert the value read from an image instruction with the relaxed precision to half, which is what we need.

After implementing step 1 ~ 3, you can generate a SPIR-V file with `-fcgl` option to disable the optimization including the legalization and `-Vd` option to turn off spirv-val check. You can run spirv-opt with `--convert-relaxed-to-half` option on your SPIR-V file. Finally, you can run spirv-opt with `--legalize-hlsl` option to legalize the SPIR-V file. I recommend you using `--skip-validation` option to run spirv-opt to avoid the validation check. Running spirv-val separately after the legalization would be better to avoid validation errors that will be solved by the legalization.

**Comment by sindney** [comment]
Actually, in order to use mediump for sampler in glsl. I created a spirv-opt pass, which checks if texture sample's result is stored to relaxed precesion type, and if so, i'll mark the sampler as relaxed. This approach works fine in our case. And we only enable this opt pass when cross compiling to glsl target.

**Comment by s-perron** [comment]
> Please don't hack RelaxedPrecision to fix this in Vulkan.

I agree. If we start treating an FP16 texture object as an FP32 texture object with relaxed precision, then we will not be able to change it if Vulkan starts to support FP16 texture objects because it will break backwards compatibility.

I will reiterate what Ehsan said 

> So we can't support it in the tools until it is accepted by the Vulkan spec.
