### ISSUE TITLE
[SPIR-V] Make sure that we properly stop compilation when we meet error

### ISSUE THREAD

**Issue by jaebaek** [microsoft/DirectXShaderCompiler#2714]
Currently, SPIR-V backend does not stop compilation when we meet error, which sometimes results in a segmentation fault.
Segmentation faults do not give users any information even when we know the reason of failure.
Even when we report an error and it will be supposed to be printed at the end of compilation, SPIR-V backend just keeps processing SPIR-V emission which can meet a nullptr and dereference it.
As a result, it fails without useful information such as uninitialized special constant.

We handle this issue in #2710, but it would be a better approach adding a flag that an error was found so that individual passes or handlers can query it and decide whether to return early.

**Comment by ehsannas** [comment]
This issue should be fixed for the major part by https://github.com/microsoft/DirectXShaderCompiler/pull/2756
