### ISSUE TITLE
dndxc fails to build unless TargetFrameworkVersion v4.5 --> v4.5.1

### ISSUE THREAD

**Issue by joobei** [microsoft/DirectXShaderCompiler#2724]
dndxc.exe doesn't seem to build unless I change the .net TargetFrameworkVersion to 4.5.1
I can't find any .net sdk specifically for 4.5 and having 4.5.1 sdk installed doesn't seem to satisfy the requirements. Am I missing something?

Windows 10 Enterprise 
version 1903 
OS Build 18362.657

I am trying to build using the command line tool hctbuild.

**Comment by joobei** [comment]
it's been a while now but I guess I might have been missing some SDK install.

**Comment by seanbaxter** [comment]
I have the same problem.
```

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targe
ts(1180,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, ins
tall the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download
.NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\Users\sean\projects\hlsl.bin\tools\clang\to
ols\dotnetc\dndxc.csproj]
```

If I change dndxc.csproj to v4.5.1, hctbuild just changes it right back.
