### ISSUE TITLE
[Question] Root signature validation errors

### ISSUE THREAD

**Issue by onovytskyi** [microsoft/DirectXShaderCompiler#2747]
Hi everyone.

I'm using DXC version from Appveyor (b053bfbaae0d4d14e7d715ebe5592ade82388637 ).
And trying to compile this simple code
```
struct Constants
{
    int Param;
};

ConstantBuffer<Constants> ConstantsBuf : register(b0, space0);

[ RootSignature ("RootFlags(ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT), CBV(b0, space = 0, visibility = SHADER_VISIBILITY_ALL)") ]
void main()
{

}
```
Compilation failed with this output
```
error: root signature validation errors
Validation failed.
```
Command line 
```
dxc.exe /Tvs_6_0 /Emain /Fo "vert.bin" "vert.hlsl"
```
Is there any way to get more info about validation that is failing?
Thanks.

**Comment by TheRealMJP** [comment]
I seem to be getting the same issue with our shaders after updating to the latest build.
