### ISSUE TITLE
Invalid Semantic SV_Depth

### ISSUE THREAD

**Issue by sixjac** [microsoft/DirectXShaderCompiler#2748]
Tried heaps of different DXC compilers, it still errors on SV_Depth saying it is an invalid semantic, backwards compatibility is enabled and I am just using the basic compiler flags, see below:

error: invalid semantic 'SV_Depth' for ps 6.0
    void PS_BlitDepth(float depth : SV_Depth)

Grabbed compiler from here:
https://ci.appveyor.com/project/antiagainst/directxshadercompiler/branch/master/artifacts

but dxcompiler.dll fails to load in C++, I guess this is an x86 build?

Thanks

**Comment by aras-p** [comment]
My guess is that `SV_Depth` has to be returned from the function, or have an `out` modifier. Seems to work with `out`, e.g. see in shader playground: http://shader-playground.timjones.io/c6b517727b683a48874df34f54ad7f65
