### ISSUE TITLE
How to compile with reflection info, but strip it post-compilation?

### ISSUE THREAD

**Issue by aras-p** [microsoft/DirectXShaderCompiler#2749]
Kinda the same issue as #2374 except that one is closed.

Situation is this: we want to 1) compile shader with reflection info, 2) get reflection data and feed that into our own data structures, 3) strip the (now unneeded anymore) reflection info, to save on shader binary data size.

Looks like right now you can't call `IDxcContainerBuilder` `RemovePart` with `DFCC_ShaderStatistics` at all. We tried hacking around it, by not calling into `dxil.dll` and using code from DXC github, to strip away the statistics blob. That almost works, except the resulting shader can't be loaded by the runtime (wrong signature? same as [on that other issue](https://github.com/microsoft/DirectXShaderCompiler/issues/2374#issuecomment-556088143)).

Currently we resort to compiling the shader twice, 1) normally, use reflection info to get the info, and 2) with `-Qstrip_reflect`. But that pretty much doubles shader compile time, which is not great.

**Comment by tex3d** [comment]
The version of DXIL.dll in the upcoming SDK will fix this issue with `IDxcContainerBuilder`.  However, there is a better way available now.

Using the new `IDxcCompiler3` and `IDxcResult` interfaces, you can get the reflection data out as a separate blob, even when supplying `/Qstrip_reflect` to the API.  So the container will not have reflection, and you will have the reflection blob you want, separately.

You can do this with the dxc command line by using the `-Fre <file>` option to write the reflection blob to a separate file, while supplying the `/Qstrip_reflect` to keep it out of the main shader output (`/Fo`).

**Comment by aras-p** [comment]
Thanks, we'll try it out!

**Comment by kayru** [comment]
Hey Aras, would you be able to share the average size difference between default and stripped DXIL shaders?

**Comment by aras-p** [comment]
@kayru varies from shader to shader, but some rough numbers (tests done a while ago):

- DXIL without reflection stripping is roughly 3x the size of DXBC,
- DXIL with reflection stripped out is roughly 2x the size of DXBC
(so reflection is like 30% of the shader size)

However! DXIL is also way less _compressible_ than DXBC. We compress with LZ4HC (so not a "strong" compressor), but anyway the numbers after LZ4HC compression are:

- DXIL without reflection stripping is 12x the size of DXBC,
- DXIL with reflection stripped out is 4x the size of DXBC.

I'm thinking that Someone :tm: needs to do SMOL-V equivalent, but for DXIL :)

**Comment by inoshishikuma** [comment]
Does that work correctly? I tried -Fre <file>, but reflection file was not created.
dxc version : pre-release for March 2020

**Comment by pow2clk** [comment]
@aras-p did @tex3d's suggestion work for you? Can we close this issue?

**Comment by aras-p** [comment]
Yeah the `IDxcCompiler3` interface to get to reflection works.
