### ISSUE TITLE
HLSL 5.1, 6.0 specs?

### ISSUE THREAD

**Issue by procedural** [microsoft/DirectXShaderCompiler#2752]
Now that this HLSL compiler is open source, it would be cool to see the HLSL specs it targets, at least 5.1. I mean, if desperate, one can read the source code of DXC and reverse all the HLSL rules out of it, but that would be mildly painful... :)

Thanks!

**Comment by pow2clk** [comment]
Hello @procedural! I realize now I've watched some of your youtube videos!

What specs there are can be found at https://microsoft.github.io/DirectX-Specs/

We are endeavoring to improve them with a focus on new features. Of particular interest might be https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm which covers a wide range and pertains to the 5.1 era.

This paragraph from the link above summarizes it best: 

> These D3D12 specs were written as incremental deltas, with a separate spec per feature area. Baseline information about rendering pipeline behaviors that are common between D3D11 and D3D12 was inherited from the D3D11 spec rather than being duplicated into the 12 documentation. We have an ambition of refactoring this material to present more of a unified how-things-are-now view, rather than a historical what-changed-to-get-here, and to merge in foundational information from the D3D11 spec. Contributions welcome if you’d like to help with that!

> This is not yet a complete set of D3D12 specs: we’ll be adding more as time permits. Please let us know if there are particular areas you’d like to see prioritized.

If you'd like to contribute to the spec work, or further discuss deficiencies, this is the place to do it! https://github.com/microsoft/DirectX-Specs/

P.S. Snakes don't blink 🐍 😆
