### ISSUE TITLE
MSVC warnings as errors issue

### ISSUE THREAD

**Issue by ghost** [microsoft/DirectXShaderCompiler#2753]
A project I'm working on is currently using DirectXShaderCompiler. However DirectXShaderCompiler's **headers** don't compile with the following flags on msvc.

```
            # /W4 displays level 1, level 2, and level 3 warnings, and all level 4 (informational) warnings that aren't off by default.
            # https://docs.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=vs-2019
            /W4
            # Treats all compiler warnings as errors.
            # https://docs.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=vs-2019
            /WX
```

This really hurts our projects code quality and limits us.

Could the project add these flags to the CI?

Or use warning pragma?
https://docs.microsoft.com/en-us/cpp/preprocessor/warning?view=vs-2019

**Comment by pow2clk** [comment]
Looks like @gongminmin fixed this. Thanks!

I'd ask the reporter to verify, but they've turned into a ghost 😕
