### ISSUE TITLE
Compute shader accessing groupshared array generates arcane validation error

### ISSUE THREAD

**Issue by ALEXMORF** [microsoft/DirectXShaderCompiler#2768]
I wrote a BVH traversal compute shader, and placed my traversal stack in LDS using the groupshared attribute. However, dxc generates the following validation errors:

"error: validation errors
at 0x2765fd48c28 inside block #0 of function CS TGSM pointers must originate from an unambiguous TGSM global variable.

Validation failed."

I have put together a minimal shader that reproduces this validation error: https://gist.github.com/ALEXMORF/11af1b1ca059f8028c945c900ef16611

Compiling the above shader with this command generates the error:
dxc -nologo -T cs_6_0 -E CS ..\..\code\reproduce.hlsl -Fo reproduce_cs.dxil

This is confusing as to I can't tell what's wrong with my shader. Plus I don't think there is an issue with my shader. Please take a look at it.

**Comment by clandrew** [comment]
Tried reproing this with the shader compiler distributed through the latest VS 2019 update (16.5.0) and it compiled successfully. Small thing, I changed your repro commandline to point to rayTrace.hlsl.

Which version of the compiler are you using?

**Comment by tex3d** [comment]
This appears to compile for me without a validation error.
Can you try with the compiler and DXIL.dll released here:
https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.5.2003

**Comment by pow2clk** [comment]
Without a response since March, We're going to assume that Tex's guidance resolved the issue.
