### ISSUE TITLE
[SPIR-V] New ray-tracing mapping for SPIR-V and Vulkan (include model 6.5) 

### ISSUE THREAD

**Issue by helixd-2k18** [microsoft/DirectXShaderCompiler#2769]
Khronos Group already released new ray-tracing extensions. I asking for new DXC/HLSL mappins for SPIR-V, include shader model 6.5. 

- https://www.khronos.org/news/press/khronos-group-releases-vulkan-ray-tracing (request)
- https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-DXR-To-Vulkan (past)

Update for **23.03.2020**, WIP by someone...

- https://github.com/microsoft/DirectXShaderCompiler/pull/2780

**Comment by ehsannas** [comment]
I think this is addressed by PR #2780 #2834 #2877
