### ISSUE TITLE
Is there a way to query the reflection data for clip instruction ?

### ISSUE THREAD

**Issue by galop1n** [microsoft/DirectXShaderCompiler#2798]
Hi,

This is something that seems impossible to find out, did i miss something ?

Could the recently added pix debug info interface help with that if nothing is possible with the existing`ID3D12ShaderReflection` ?

**Comment by damyanp** [comment]
@galop1n - can you explain a bit more about what sort of reflection data you'd be looking for here please?

**Comment by damyanp** [comment]
Closing as not planned.  Will reconsider if more information is provided about the request.
