### ISSUE TITLE
Problem building VS Solution Files

### ISSUE THREAD

**Issue by fred26** [microsoft/DirectXShaderCompiler#2801]
I have followed the instructions for building the VS2017 sln files.

Installed

Git
Python - version 3.7 installed
Visual Studio 2017
Windows SDK - version 10.0.18362.0
Windows Driver Kit - version 10.0.18362.1

I receive the following error:

Creating solution files for x64, logging to C:\Users\feder\Desktop\Code\Tools\hlsl.bin\cmake-log.txt
Failed to configure cmake projects.

===== begin cmake-log.txt =====
Running cmake -DHLSL_OPTIONAL_PROJS_IN_DEFAULT:BOOL=OFF -DHLSL_ENABLE_ANALYZE:BOOL=OFF -DHLSL_OFFICIAL_BUILD:BOOL=OFF -DHLSL_ENABLE_FIXED_VER:BOOL=OFF -DHLSL_ENABLE_FIXED_VER:BOOL=OFF -DHLSL_FIXED_VERSION_LOCATION:STRING= -DHLSL_BUILD_DXILCONV:BOOL=ON -DCLANG_VENDOR:STRING= -DENABLE_SPIRV_CODEGEN:BOOL=OFF -DSPIRV_BUILD_TESTS:BOOL=OFF -DCLANG_ENABLE_ARCMT:BOOL=OFF -DCLANG_ENABLE_STATIC_ANALYZER:BOOL=OFF -DCLANG_INCLUDE_TESTS:BOOL=OFF -DLLVM_INCLUDE_TESTS:BOOL=OFF -DHLSL_INCLUDE_TESTS:BOOL=ON -DLLVM_TARGETS_TO_BUILD:STRING=None -DLLVM_INCLUDE_DOCS:BOOL=OFF -DLLVM_INCLUDE_EXAMPLES:BOOL=OFF -DLIBCLANG_BUILD_STATIC:BOOL=ON -DLLVM_OPTIMIZED_TABLEGEN:BOOL=OFF -DLLVM_REQUIRES_EH:BOOL=ON -DLLVM_APPEND_VC_REV:BOOL=ON -DLLVM_ENABLE_RTTI:BOOL=ON -DLLVM_ENABLE_EH:BOOL=ON -DLLVM_DEFAULT_TARGET_TRIPLE:STRING=dxil-ms-dx -DCLANG_BUILD_EXAMPLES:BOOL=OFF -DLLVM_REQUIRES_RTTI:BOOL=ON -DCLANG_CL:BOOL=OFF -DCMAKE_SYSTEM_VERSION=10.0.14393.0 -DDXC_BUILD_ARCH=x64 -G "Visual Studio 15 2017 Win64" C:\Users\feder\Desktop\Code\Tools\DirectXShaderCompiler-master
CMake Deprecation Warning at CMakeLists.txt:19 (cmake_policy):
  The OLD behavior for policy CMP0051 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.14393.0.
CMake Error at CMakeLists.txt:28 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    The system cannot find the file specified

-- Configuring incomplete, errors occurred!
See also "C:/Users/feder/Desktop/Code/Tools/hlsl.bin/CMakeFiles/CMakeOutput.log".
===== end cmake-log.txt =====

This started after installing the WDK.

Any insights are appreciated.

Thanks

**Comment by fred26** [comment]
I did a workaround running this on the Command Prompt for VS2017.

Now I have the following errors: 

CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "3" (found
  C:/Users/feder/AppData/Local/Microsoft/WindowsApps/python3.exe)

Appreciate any help on this.

**Comment by ehsannas** [comment]
If you have multiple python versions, make sure that version 3.x is your default (check order in your PATH).
Alternatively, you can add the `-DPYTHON_EXECUTABLE=<path>` to your cmake command. 

e.g. `-DPYTHON_EXECUTABLE=C:\Python34\python.exe`

Hope this helps.

**Comment by hekota** [comment]
Please delete C:/Users/feder/AppData/Local/Microsoft/WindowsApps/python3.exe, that is just a hook for windows store or something like that. Then run hctclean, restart your command prompt and try to build again.

**Comment by pow2clk** [comment]
I'm afraid this is a result of installing the WDK and gamely accepting the default checkbox that enables a plugin for Visual Studio. Unfortunately, this results in this problem. We should probably highlight it more in the Readme.md. There is mention of it in the wiki [Building-Sources](https://github.com/microsoft/DirectXShaderCompiler/wiki/Building-Sources#using-sdk-and-wdk-installations), but I don't think that's enough.

**Comment by pow2clk** [comment]
If you reinstall WDK and don't select that VS plugin, you should be able to use the HLSL console again.

**Comment by fred26** [comment]
Also, if you I try to follow how to build through the integrated VS2017 Cmake support, I receive the same error:

> Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "3" (found
  C:/Users/feder/AppData/Local/Microsoft/WindowsApps/python3.exe)		C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake	137

**Comment by hekota** [comment]
Delete C:/Users/feder/AppData/Local/Microsoft/WindowsApps/python3.exe, clean build folder & restart VS.
