### ISSUE TITLE
[SPIR-V] SPIR-V backend doesn't support sizeof(...)

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/DirectXShaderCompiler#2814]
```
struct PSInput
{
	int4 color : COLOR;
};
ByteAddressBuffer g_meshData[] : register(t0, space3);

int3 PSMain(PSInput input) : SV_TARGET
{
	return g_meshData[input.color.x].Load3(input.color.y * sizeof(float3));
    // this line works: return g_meshData[input.color.x].Load3(input.color.y * 12);
}
```

This is with today's AppVeyor build.

![image](https://user-images.githubusercontent.com/49594/78554976-6d7bec00-780c-11ea-98e7-28ad01c62b80.png)

**Comment by kuhar** [comment]
Thanks for reporting, @Jasper-Bekkers.
Looping in spir-v folks.

**Comment by Jasper-Bekkers** [comment]
Did this end up getting any traction?

**Comment by ehsannas** [comment]
Yeah, it's on our todo list. Sorry for the delay. Hopefully we'll have something in the next few weeks.

**Comment by jaebaek** [comment]
I am working on it now. Let me check what happens.

**Comment by aschrein** [comment]
I'm experiencing a crash when sizeof is used for SPIRV build. Can someone take a look?
Here's the snippet:
http://shader-playground.timjones.io/1be982abbc266d0a9938b8217619b907

**Comment by ehsannas** [comment]
@jaebaek please take a look.

**Comment by jaebaek** [comment]
Sure, I will get back to you soon.

**Comment by jaebaek** [comment]
Sent a PR: #3379
