### ISSUE TITLE
Dynamic indexing into arrays

### ISSUE THREAD

**Issue by jrs-araxis** [microsoft/DirectXShaderCompiler#2817]
Hi.

I think there may be a problem with array indexing using a variable rather than a literal integer value. I have included a cut-down anyhit shader (Type: library, Model: Shader Model 6.4) below to demonstrate.

The #if/#endif section contains two contrived code alternatives that should do the same thing. In practice, the top #if alternative stores the correct values into the payload, and the bottom alternative does not appear to store anything. The intermediate code looks reasonable.

The problem applies to both debug and optimized builds. If dynamic indexing into the array isn't allowed in this context, perhaps a compiler warning could be added?

This appears to be a problem with both the DXC in VS2019 16.5.2 and also the dxc_2020_03-25 preview.

anyhit.hlsl:

```
#define MAX_ANYHIT_RECORDS 4

struct AnyHitRecord {
  float4 m_diffuseTextureRGBA;    
  float3 m_worldNormal;           
  float m_depth;                  
  uint32_t m_materialInstanceID;  
  float m_pad1;
  float m_pad2;
  float m_pad3;
};

struct NormalPayload {
  AnyHitRecord m_anyHitRecord[MAX_ANYHIT_RECORDS];
  uint32_t m_anyHitRecordCount;
  uint32_t m_flags;
  float m_hitDistance;
  float m_pad;
  float4 m_RGBL;
  float4 m_ssao;
};

struct Attributes {
  float2 m_bary;
};

[shader("anyhit")] void AnyHit(inout NormalPayload payload, Attributes attrib) {
  uint32_t hitCount = payload.m_anyHitRecordCount;

#if 1
  // This works
  if (hitCount == 0)
    payload.m_anyHitRecord[0].m_depth = 123;
  if (hitCount == 1)
    payload.m_anyHitRecord[1].m_depth = 123;
#else
   // This should be equivalent to the above, but fails to store anything.
   if (hitCount == 0 || hitCount == 1)
    payload.m_anyHitRecord[hitCount].m_depth = 123;
#endif

  IgnoreHit();
}

```
An extract from the .hlsl.h for the working alternative #if 1 (optimizer on):

```
; Function Attrs: noreturn nounwind
define void @"\01?AnyHit@@YAXUNormalPayload@@UAttributes@@@Z"(%struct.NormalPayload* noalias nocapture %payload, %struct.Attributes* nocapture readnone %attrib) #0 {
  %1 = getelementptr inbounds %struct.NormalPayload, %struct.NormalPayload* %payload, i32 0, i32 1
  %2 = load i32, i32* %1, align 4, !tbaa !9
  %3 = icmp eq i32 %2, 0
  br i1 %3, label %4, label %6

; <label>:4                                       ; preds = %0
  %5 = getelementptr inbounds %struct.NormalPayload, %struct.NormalPayload* %payload, i32 0, i32 0, i32 0, i32 2
  store float 1.230000e+02, float* %5, align 4, !tbaa !13
  br label %6

; <label>:6                                       ; preds = %4, %0
  %7 = icmp eq i32 %2, 1
  br i1 %7, label %8, label %10

; <label>:8                                       ; preds = %6
  %9 = getelementptr inbounds %struct.NormalPayload, %struct.NormalPayload* %payload, i32 0, i32 0, i32 1, i32 2
  store float 1.230000e+02, float* %9, align 4, !tbaa !13
  br label %10

; <label>:10                                      ; preds = %8, %6
  call void @dx.op.ignoreHit(i32 155)  ; IgnoreHit()
  unreachable
}

```
An extract from the .hlsl.h for the non-working alternative #if 0 (optimizer on):

```
; Function Attrs: noreturn nounwind
define void @"\01?AnyHit@@YAXUNormalPayload@@UAttributes@@@Z"(%struct.NormalPayload* noalias nocapture %payload, %struct.Attributes* nocapture readnone %attrib) #0 {
  %1 = getelementptr inbounds %struct.NormalPayload, %struct.NormalPayload* %payload, i32 0, i32 1
  %2 = load i32, i32* %1, align 4, !tbaa !9
  %3 = icmp ult i32 %2, 2
  br i1 %3, label %4, label %6

; <label>:4                                       ; preds = %0
  %5 = getelementptr inbounds %struct.NormalPayload, %struct.NormalPayload* %payload, i32 0, i32 0, i32 %2, i32 2
  store float 1.230000e+02, float* %5, align 4, !tbaa !13
  br label %6

; <label>:6                                       ; preds = %4, %0
  call void @dx.op.ignoreHit(i32 155)  ; IgnoreHit()
  unreachable
}

```

**Comment by pow2clk** [comment]
This is such a good bug report that I really wish I could be more helpful.

There is no such restriction on dynamic array indexing in this context. The output code in both cases look to be correct. It's possible there's some error in the driver consuming the DXIL. Is there any other information you can provide?

**Comment by jrs-araxis** [comment]
Hi. Thanks for responding.

My current best guess about this is that the payload was too large for the driver/hardware to cope with. The payload size was accepted by CreateStateObject via D3D12_RAYTRACING_PIPELINE_CONFIG though, so I can't be sure.

If it was a payload size problem, maybe the memory store in the indexed case causes a slightly different type/extent of overrun, the effects of which are more apparent. I thought I'd check anyway in case there was a known issue/limitation with indexing. I have more confidence in the compiler being correct than I do in the hardware, so feel free to close this issue.

I've ended-up moving the array and some other things out of the payload into a per-pixel r/w buffer until the inline raytracing feature is available. It will work out for now, although it's a huge waste of memory (and presumably performance), for something that really wants to be per-ray or per-thread data.

Thanks for looking into this.
