### ISSUE TITLE
D3D12 Shader Reflection InstructionCount et al.

### ISSUE THREAD

**Issue by scottkircher** [microsoft/DirectXShaderCompiler#2830]
I am on a fairly recent dxcompiler.dll (downloaded 4/2/2020)

When I use ID3D12ShaderReflection with a DXIL shader compiled via dxcompiler.dll, it works for getting information about shader resources, but all the shader-complexity related fields in D3D12_SHADER_DESC (such as InstructionCount) are zero.

Is this a missing feature of dxcompiler? Or, is it a problem elsewhere?

Thanks,
-Scott

**Comment by pow2clk** [comment]
Hi @scottkircher!

Thanks for the bug report. I'm afraid this is a known issue. We are working on a fix.

**Comment by pow2clk** [comment]
I think @tex3d fixed this with #2930

**Comment by pow2clk** [comment]
Lacking any response, we will assume this is resolved. Open a new issue if there is a problem with it.
