### ISSUE TITLE
[spirv] Input Attachment Crash on Adreno GPU

### ISSUE THREAD

**Issue by congyue1977** [microsoft/DirectXShaderCompiler#2842]
Use the input attachment in fragment shader，via DXC compile to SPIR-V，crash on Adreno GPU，the error is 

> AdrenoVK: Shader compilation failed for shaderType: 1

, but works well on the Mali GPU. 
Below is my shader code, very simple:

```
[[vk::input_attachment_index(0)]]
[[vk::binding(0)]]
SubpassInput input;

float4 main(float4 position : SV_Position, float2 uv : TexCoord0) : SV_Target0
{
        return input.SubpassLoad();
}
```
I use glslangValidator to compile the above shader code, and there is no problem on Adreno GPU.

**Comment by ehsannas** [comment]
Thanks for reporting @congyue1977

**Comment by ehsannas** [comment]
Thanks for your contribution for fixing the issue. This specific case is not a bug in DXC, but a wrong behavior in some drivers. You can hack your own DXC or your SPIR-V shaders to modify the `depth` to please your driver.

Please see a detailed discussion here https://github.com/microsoft/DirectXShaderCompiler/issues/1107

**Comment by ehsannas** [comment]
Thanks

**Comment by congyue1977** [comment]
@ehsannas Thanks for your reply,
I use the glslangvalidator to compile this code, SPIR-V code is:
`OpTypeImage %float SubpassData 0 0 0 2 Unknown`
Use DXC, the SPIR-V code is:
`OpTypeImage %float SubpassData 2 0 0 2 Unknown`
Only the “Depth“ is different. If it's not a bug, why is it different?

**Comment by ehsannas** [comment]
> the spec is quite clear here that the "Depth" operand is just a kind of "hint" to the driver. The real semantics should come from the opcode, no matter what the "Depth" value we put in OpTypeImage

Please read the full detailed discussion here #1107. Thanks.

**Comment by congyue1977** [comment]
@ehsannas Thanks for your reply,
I have read the full discussion, including the related issue, and I agree with what you said, "Depth" is just a hint, but for the special case of SubpassData,  based on my reading of the spec:
[OpImageRead](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpImageRead)

> Read a texel from an image without a sampler.

Correct me if I'm wrong, but I think it is impossible to use instructions like OpImageDrefGather, so depth-comparison sample functions will not be used, so it can be set to 0 here.
