### ISSUE TITLE
[spirv] Move KHR ray tracing to use SPIRV 1.4

### ISSUE THREAD

**Issue by alelenv** [microsoft/DirectXShaderCompiler#2851]
As per issue : https://gitlab.khronos.org/vulkan/vulkan/issues/2096
We have decided to enforce SPIRV 1.4 for KHR_ray_tracing

1) Need to enforce vulkan env 1.2 for raytracing stages
2) Compute interface variables used in entry points static call tree (Currently code assumes only single entry point and adds all global variables)

cc @ehsannas 
I plan to look into this

**Comment by ehsannas** [comment]
Sounds good. Thanks for the heads up @alelenv

**Comment by dgkoch** [comment]
> Need to enforce vulkan env 1.2 for raytracing stages

SPIR-V 1.4 can actually be used prior to Vulkan 1.2 if VK_KHR_spirv_1_4  is supported.

**Comment by alelenv** [comment]
Getting back to this 

@dgkoch : spiregg selects spirv version based of -fspv-target-env which is either vulkan1.0/1.1/1.2. So selecting 1.2 to satisfy the > 1.4 SPIRV requirement

Question for @ehsanas

For something like
void func() { = gloVar2; }
void entry1() { = gloVar1;}
void entry2() { func() }

We currently add gloVar1 and gloVar2 to both entry1() and entry2() but as per " _The set of Interface <id> must be equal to or a superset of the global OpVariable Result <id> referenced by the entry point’s static call tree, within the interface’s storage classes_." it is not accurate

Initially I was planning on keeping track of global variables accessed in each function (By modifying getDeclEvalInfo) and functions reachable from given function in FunctionInfo

Then at time of entry point creation, walk over all reachable functions from entry and maintain a set of accessed global variables to satisfy requirement for above

However I am unsure this is the right approach and instead maybe this should be one of the legalization passes in spirv-opt

Any thoughts/suggestions?
