### ISSUE TITLE
Desktop Crash when running this Compute Shader on D3D12

### ISSUE THREAD

**Issue by ghostplant** [microsoft/DirectXShaderCompiler#2852]
```cpp
RWStructuredBuffer<float> output0: register(u0); // sizeof(output0) = sizeof(float) * 4096 * 4096

// Launch Blocks for CSMain: (bx = 4, by = 4096, bz = 1)
[numthreads(1024, 1, 1)]
void CSMain(uint3 threadIdx: SV_GroupThreadID, uint3 blockIdx: SV_GroupID) {
  output0[blockIdx.x * 4194304 + threadIdx.x * 4096 + blockIdx.y] = 1.0f;
  for (int k = 0; k < 4096; ++k) {
    output0[blockIdx.x * 4194304 + threadIdx.x * 4096 + blockIdx.y] = output0[blockIdx.x * 4194304 + threadIdx.x * 4096 + blockIdx.y];
  }
}
```

The size of buffer `output0` is sizeof(float[4096][4096]), and the launch blocks for shader `CSMain` is (4, 4096, 1).
The shader is expected to end with compute results: `output[all] = 1.0f`.
However, the actual result is `output[all] = 0.0f`. and when running multiple times of this kernel, the whole Win10 Desktop is possible to **crash and blue screen**.

So do you know what the problem is for this shader on Win10? 1) result is incorrect; 2) system might become blue screen.

(OS: Win10 + DirectX 12 + AMD Radeon VII)

**Comment by tex3d** [comment]
I suspect the reason would be TDR, taking more than 3 seconds (IIRC) before returning from Dispatch will reset the device, repeated resets will blue screen.

Why the loop that just reads and writes the same UAV element 1024 times?  Are you trying to TDR the device?  Are you asking for how to override TDR setting?  Are you looking for a specific optimization that detects this `output[index] = output[index]` and eliminates the UAV read and write?

**Comment by ghostplant** [comment]
@tex3d 
**Why the loop that just reads and writes the same UAV element 1024 times?**
A1: The code is just a simplest example that can trigger the crash. Actually, more cases for meaningful purpose are just at least as simple as this example. You can consider trying
`output0[blockIdx.x * 4194304 + threadIdx.x * 4096 + blockIdx.y] = (output0[blockIdx.x * 4194304 + threadIdx.x * 4096 + blockIdx.y] + K) % P;`
or
`output0[blockIdx.x * 4194304 + threadIdx.x * 4096 + blockIdx.y] = (output0[blockIdx.x * 4194304 + threadIdx.x * 4096 + blockIdx.y] * K) + (input0[blockIdx.x * 4194304 + threadIdx.x * 4096 + blockIdx.y] * (1 - K));`
which also crash the system.

**Are you trying to TDR the device?**
A2: I am not aware of TDR, so I am not trying to trigger it.

**Are you asking for how to override TDR setting?**
A3: Maybe yes since I didn't know TDR, and how to do this? The most important question is how to avoid blue screen which completely destory all current unsave sessions, while I also expect this timeout setting which is to avoid a program running into an infinitive loop.

**Are you looking for a specific optimization that detects this output[index] = output[index] and eliminates the UAV read and write?**
A4: As `A1` descriped, the purpose is mostly caused by the long loop even if I change the computation inside the loop, not for this optimization you pointed.

**Comment by ghostplant** [comment]
@tex3d 
I just tried the following settings, but still not able to prevent the system crash issue:
```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers]
"TdrLevel"=dword:00000003
"TdrDelay"=dword:0000003c
"TdrDdiDelay"=dword:0000003c
"TdrTestMode"=dword:00000000
"TdrDebugMode"=dword:00000002
"TdrLimitTime"=dword:0000003c
"TdrLimitCount"=dword:00000005
```
