### ISSUE TITLE
Will dxc support symbolic differentiation?

### ISSUE THREAD

**Issue by nlguillemot** [Microsoft/DirectXShaderCompiler#286]
Hi,

I recently learned about fxc's [symbolic differentiation feature](https://blogs.msdn.microsoft.com/chuckw/2011/03/08/hlsl-compiler-support-for-symbolic-derivatives/), and I'm wondering if this feature will be supported in dxc. When I try it on https://tryhlsl.azurewebsites.net/, I get a parser error, despite it working with fxc.

Here's a sample program that can be tested on tryhlsl:

```
RWByteAddressBuffer output : register(u0);

[numthreads(1,1,1)]
void main(uint3 tid : SV_DispatchThreadID)
{
    float x = float(tid.x);
    float test = cos(x);
    float dtestdx = test`(x);
    
    output.Store(0, asuint(dtestdx));
}
```

Output with fxc in cs_5_1, which correctly differentiates to the expected `d/dx cos(x) = -sin(x)`.

(subtle detail: it actually computes `sin(-x)`, but it turns out that `-sin(x) = sin(-x)`)

```
cs_5_1
dcl_globalFlags refactoringAllowed
dcl_uav_raw U0[0:0], space=0
dcl_input vThreadID.x
dcl_temps 1
dcl_thread_group 1, 1, 1
utof r0.x, vThreadID.x
sincos r0.x, null, -r0.x
store_raw U0[0].x, l(0), r0.x
ret
```

Output with dxc in cs_6_0, doesn't parse.

```
hlsl.hlsl:8:25: error: expected ';' at end of declaration
    float dtestdx = test`(x);
                        ^
                        ;
```

**Comment by marcelolr** [comment]
@nlguillemot , we're not planning on implementing the backtick operator in dxc. We announced the removal for the new compiler a long time ago and have found there's very little adoption in practice (as in - this is the first time someone has brought this up), and so we're choosing to spend time on improving other areas of the language/compiler.
