### ISSUE TITLE
DXC_E_GENERAL_INTERNAL_ERROR compiling a Hull Shader

### ISSUE THREAD

**Issue by vfxNEXT** [microsoft/DirectXShaderCompiler#2863]
**Versions**
dxil: 10.0.19587.1001
dxcompiler: 1.5.2003.22

**Problem**
Compiling the attached HLSL source using the IDxcCompiler3::Compile() method results to DXC_E_GENERAL_INTERNAL_ERROR. With the prior D3DCompile2() function it will be compiled successful.

**Source**
[StandardMaterialHS.txt](https://github.com/microsoft/DirectXShaderCompiler/files/4567362/StandardMaterialHS.txt)

**Arguments**
-E hs_main
-T hs_6_4
-all_resources_bound
-WX
-Zi
-Od
-D HAS_UV_CHANNEL=1
-D HAS_NORMALS=1
-D HAS_TANGENTS=1
-D HAS_INSTANCE_DATA=1

**Attempts**
I took a look into the wiki if something changed with Hull Shaders, but found no information.

Thanks in advance!

**Comment by tex3d** [comment]
It turns out this was fixed in this PR: #3065
