### ISSUE TITLE
How about DX9 DXBC support?

### ISSUE THREAD

**Issue by hustcslhb** [microsoft/DirectXShaderCompiler#2865]
Currently DX9 DXBC could not convert to DXIL successfully, is any plan to support DX9? Thank you.

**Comment by pow2clk** [comment]
I'm afraid this is not a priority. If you'd like support for DX9 shaders on DX12, you might try [D3D9On12](https://devblogs.microsoft.com/directx/coming-to-directx-12-d3d9on12-and-d3d11on12-resource-interop-apis/)
