### ISSUE TITLE
Missing IUnknown include

### ISSUE THREAD

**Issue by matt77hias** [microsoft/DirectXShaderCompiler#2873]
`dxcapi.h` misses an include (`<unknwn.h>`) for `IUnknown`

**Comment by tex3d** [comment]
There are a number of definitions that this header needs that are supplied by a number of windows headers consisting of tens or maybe hundreds of thousands of lines of code.  If this header included those directly, it would be less flexible for use with different, and possibly possibly more minimal, definitions.

**Comment by matt77hias** [comment]
```c++
#define WIN32_LEAN_AND_MEAN
#define NOBITMAP
#define NODRAWTEXT
#define NOGDI
#define NOHELP
#define NOMCX
#define NOMINMAX
#define NOSERVICE

#include <SDKDDKVer.h>
#include <windows.h>

#include <unknwn.h> // was still needed
#include <DirectXShaderCompiler/dxcapi.h>
```

I already included the Windows SDK before including `DirectXShaderCompiler`, but still needed the separate `unknwn.h`. Note that `IUnknown` is used as a base class in `dxcapi.h`, and can thus not be forwarded.

But if this is by design, I close the issue. ¯\_(ツ)_/¯
