### ISSUE TITLE
CreateGraphicsPipelineState: Encoded Input Signature size doesn't match specified size

### ISSUE THREAD

**Issue by sixjac** [microsoft/DirectXShaderCompiler#2889]
Hi, seem to be having issues Creating PSO from precompiled shaders, only happening with Dxc, following error output:

    023c:0380 @ 00447734 - LdrpAllocateTls - INFO: TlsVector 000001C94575B380 Index 0 : 5112 
    bytes copied from 00007FF7066B2000 to 000001C945758100
    023c:0380 @ 00447734 - LdrpAllocateTls - INFO: TlsVector 000001C94575B380 Index 1 : 8 bytes 
    copied from 00007FFF5F9727D8 to 000001C94575F3B0
    023c:0380 @ 00447734 - LdrpAllocateTls - INFO: TlsVector 000001C94575B380 Index 2 : 8 bytes 
    copied from 00007FFF5D95FF34 to 000001C94575F3F0
    D3D12 ERROR: Error messages can be filtered using the ID3D12Device::SetDebugErrorFilterX API. 
    The error identifier for each error message is the hexadecimal code in square brackets.
    023c:0380 @ 00447734 - LdrpAllocateTls - INFO: TlsVector 000001C94575B380 Index 3 : 8 bytes 
    copied from 00007FFF5D9AE0C8 to 000001C94575F410
    023c:0380 @ 00447734 - LdrpAllocateTls - INFO: TlsVector 000001C94575B380 Index 4 : 8 bytes 
    copied from 00007FFF5F5C9AC8 to 000001C94575F070
    D3D12 ERROR: [0x0FB36A89] ID3D12Device::CreateGraphicsPipelineState: Encoded Input 
    Signature size doesn't match specified size. [ STATE_CREATION ERROR #63 ]
    023c:0380 @ 00447734 - LdrpAllocateTls - INFO: TlsVector 000001C94575B380 Index 5 : 8 bytes 
    copied from 00007FFF5F2F0698 to 000001C94575F090

Shaders were compiled with Xbox GDK, cant see issues immediately in the D3D12_PIPELINE_STATE_STREAM_DESC object, not sure what is making the size mismatch.

FYI .fx file has no root signature and therefore compiling with /D __XBOX_DISABLE_PRECOMPILE flag to skip DXIL validation

So hard to find good info on D3D12 SM6 on the net unlike FXC and older shader models.

I am stumped 

Thanks

**Comment by tex3d** [comment]
Closing:
1. Xbox GDK specific scenario
2. Though not indicated here, this was using two contradictory options together when compiling the shader: `/D __XBOX_STRIP_DXIL /D __XBOX_DISABLE_PRECOMPILE`.
