### ISSUE TITLE
ARM64 binaries

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/DirectXShaderCompiler#2890]
Our application can't perform off-line compilation of shaders, which means we need to link against dxcompiler.lib and ship dxcompiler.dll. The 10.0.18362.0 SDK does include an ARM64 dxc.exe, but no dxil.dll or dxcompiler.dll. Are ARM64 DLL binaries planned for release either here or in the SDK?

**Comment by oscarbg** [comment]
+1

**Comment by Gerdya** [comment]
Our development is currently stuck with the same issue: no dxil.dll or dxcompiler.dll in the Windows SDK. Any updates on this?

Thanks!

**Comment by MarkIngramUK** [comment]
> Arm64 dlls are not getting officially released. We are working on improving our test infrastructure, it should be included in the next release.

From https://github.com/microsoft/DirectXShaderCompiler/issues/4435#issuecomment-1121380749

**Comment by Sergio0694** [comment]
If it helps, you can just grab the ARM64 binaries from an ARM64 build of Windows, those work fine.
I don't think they're officially supported, but at least they can get you unblocked for now.
Eg. I'm using them in ComputeSharp, had no problems so far. See [link here](https://github.com/Sergio0694/ComputeSharp/tree/main/src/ComputeSharp.Dynamic/Libraries/arm64)).

**Comment by MarkIngramUK** [comment]
Thanks @Sergio0694 - that's great, I didn't realise they shipped with Windows. I wonder how up to date they are... I'm using December 2021 on x64 (`-HV 2021`).

**Comment by MarkIngramUK** [comment]
Excellent news, thanks @hekota and the rest of the team.
