### ISSUE TITLE
Build scripts misbehave when relative paths are used in hctstart

### ISSUE THREAD

**Issue by jbarczak** [Microsoft/DirectXShaderCompiler#29]
Running hctstart with relative paths, for example:
<pre>
hctstart  .  .\bin
</pre>

Has put my environment into a state which causes the hctbuild script to exit immediately with no output.  Some quick printf debugging shows it failing in line 10, during the check for missing source directory.  Using absolute paths works as intended.

**Comment by marcelolr** [comment]
Gotcha, issue understood.
