### ISSUE TITLE
Add SV_BaseVertexLocation and SV_StartInstanceLocation to VSIn

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#2907]
These would return the index start offsets passed to `DrawIndexedInstanced` in the corresponding `BaseVertexLocation` and `StartInstanceLocation` arguments.  GLSL has the equivalent values: `gl_BaseVertex` and `gl_BaseInstance`.  While the names are long, they match the API, and consistency is important.

These have been an ongoing request, and can save extra root argument overhead required to get these without built-in support.

_edited to fix BaseVertexLocation name (StartVertexLocation is from DrawInstanced, not DrawIndexedInstanced)._

**Comment by AdamJMiles** [comment]
While we do have StartInstanceLocation in the API, the other one I think corresponds to BaseVertexLocation? There's no 'StartVertexLocation' in the Draw command API.

**Comment by sebbbi** [comment]
DrawIndexedInstanced arguments and the indirect argument struct has these:

```
  UINT IndexCountPerInstance,
  UINT InstanceCount,
  UINT StartIndexLocation,
  INT  BaseVertexLocation,
  UINT StartInstanceLocation
```

gl_BaseInstance = StartInstanceLocation
gl_BaseVertex = BaseVertexLocation

**Comment by otanter-at-ubi** [comment]
I second all of these. We've asked for them a few years ago at the xfest.

**Comment by lijianwen13** [comment]
I think it's very important for us to build cross-platform game engines.

**Comment by yuriy-odonnell-epic** [comment]
+1e9 to this. Implementing advanced cross-platform GPU-driven rendering techniques is extremely inconvenient without automatic SV_StartInstanceLocation. Workarounds exist, but they're very yucky.

**Comment by kingofthebongo2008** [comment]
something about this?
if someone wants to help, where one can look?
