### ISSUE TITLE
'd3d12TokenizedProgramFormat.hpp' Not found

### ISSUE THREAD

**Issue by friesofdoom** [microsoft/DirectXShaderCompiler#2910]
Apparently Microsoft removed this header after version 10.0.14393.0 of the SDK/WDK, but the build instructions require you to install 10.0.18362.0 or newer.

**Comment by pow2clk** [comment]
Hi fries!

It was not removed (But I suspect I found the misleading blog post that lead you to this conclusion). Usually lacking this file is an indication that the WDK isn't installed. Mine is found in `C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um` 

FWIW, we're working on a better solution to providing this file than having to install the WDK

**Comment by pow2clk** [comment]
Lacking any response, I'm closing under the assumption that my previous comment resolved the issue.
