### ISSUE TITLE
Plans to support DXIL reflection on non-windows platforms?

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#2912]
Hi, looking at the source it seems that DXIL reflection won't work on Linux/Mac as the API is only implemented when LLVM_ON_WIN32 is defined https://github.com/microsoft/DirectXShaderCompiler/blob/713c80ce4ec80dc83a34c8179d2c037c26c5e9e8/lib/HLSL/DxilContainerReflection.cpp#L38 Are there plans for adding DXIL reflection support for non-Windows platforms soon? We need this at Unity.

**Comment by llvm-beanz** [comment]
@pow2clk IIRC you fixed this. Is that correct?

**Comment by pow2clk** [comment]
Yes I did! #4810
