### ISSUE TITLE
[Spirv] How to specify descriptor set for all registers?

### ISSUE THREAD

**Issue by andrejnau** [microsoft/DirectXShaderCompiler#2917]
I would know how to set the same descriptor set for all registers?

**Comment by ehsannas** [comment]
Please see https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#descriptors

**Comment by andrejnau** [comment]
I mean without modify the source code.

**Comment by andrejnau** [comment]
I can't use `-fvk-bind-register` because you need to know what registers are in the shader. I don't want to compile shader 2 time. At first for getting reflection and then for compile with args based on reflection. It will work but this is a bad way.

**Comment by andrejnau** [comment]
I found what I need. `-auto-binding-space` works for my purpose. Thanks! It was useful to re-read the article.

**Comment by andrejnau** [comment]
But I had a bit trouble with it. I have to pass it as {"-auto-binding-space", "set"} instead of {"-auto-binding-space=set". I use IDxcCompiler::Compile from latest binaries from artifacts. It was a little strange. Shall I create separate bug for it. Or it is not a bug?

**Comment by ehsannas** [comment]
It's not a bug. if you were running on the command line,  you'd also use `-auto-binding-space N`, and not `-auto-binding-space=N`. Thanks!
