### ISSUE TITLE
texture2d-getdimensions crashes with indexed parameters

### ISSUE THREAD

**Issue by TerisGH** [microsoft/DirectXShaderCompiler#2935]
The following crashes dxc:
`` uint2 dims; Source.GetDimensions(dim[0], dim[1]); ``
whereas this compiles:
`` uint2 dims; Source.GetDimensions(dim.x, dim.y); ``
happened on dxc_2020_03-25 release.

**Comment by pow2clk** [comment]
thanks for the report!

Including a complete reproducing  shader here for reference:
```hlsl
Texture2D<float> Source : register (t1);

float4 main() : SV_Target
{
        uint2 dims;
        Source.GetDimensions(dims[0], dims[1]);
        return 1;
}
```

**Comment by pow2clk** [comment]
With the latest build, this no longer crashes for me
