### ISSUE TITLE
[SPIR-V] SV_InstanceID behavior different than in DX12

### ISSUE THREAD

**Issue by pmichniewski** [microsoft/DirectXShaderCompiler#2946]
When using SV_InstanceID, the SPIR-V codegen emits gl_InstanceIndex, which is not correct. The DX12 InstanceID always counts from 0, even if the StartInstanceLocation parameter is non-zero. gl_InstanceIndex however starts from firstInstance. Thus it doesn't emulate actual DX12 shader behavior. To make it equivalent, SPIR-V codegen should emit (gl_InstanceIndex - gl_BaseInstance).

**Comment by ehsannas** [comment]
Interesting find... Will investigate. Thanks for reporting @pmichniewski

**Comment by ehsannas** [comment]
Hi @pmichniewski , I have made a pull-request waiting for review
