### ISSUE TITLE
[SPIR-V] Crash when result of dot4add_u8packed or dot4add_i8packed is operated on by a literal

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#2953]
### Title
 Compiler crash when the result of dot4add_u8packed or dot4add_i8packed is operated on by a literal e.g when performing multiplication/division/addition/subtraction.

### Functional impact
Compiler crashes, no result gets printed to stdout.

### Minimal repro steps

1. Compile [repro_shader.txt](https://github.com/microsoft/DirectXShaderCompiler/files/4746158/repro_shader.txt) with `dxc.exe -E frag -T ps_6_4 repro_shader.txt -spirv -fspv-target-env=vulkan1.1`
```
uint frag(float4 vertex : SV_POSITION) : SV_Target
{
    uint acc = 0;
    
	acc += 1+dot4add_u8packed(vertex.x, vertex.y, uint(vertex.y));
        acc += 2+dot4add_i8packed(vertex.z, vertex.w, int(vertex.x));
	
	//The following does not cause a crash
	
	//uint tempVar = 2;
	//acc += tempVar*dot4add_u8packed(vertex.x, vertex.y, uint(vertex.y));
        //acc += tempVar*dot4add_i8packed(vertex.z, vertex.w, int(vertex.x));
    
	return acc;
}
```

### Expected result
The compiler outputs correct SPIR-V or prints an informative error message.

### Actual result
DXC crashes on assertion `assert(Val && "isa<> used on a null pointer");` (see
[call_stack.txt](https://github.com/microsoft/DirectXShaderCompiler/files/4746146/call_stack.txt))

### Further technical details
DXC bult from changeset 5ebc67c618d7061407cca039573108078f601ee6

**Comment by sudonatalie** [comment]
Since the crash is now fixed, I've opened a separate issue to track actually implementing the missing intrinsics in the SPIR-V backend: https://github.com/microsoft/DirectXShaderCompiler/issues/4528
