### ISSUE TITLE
[SPIR-V] Apply binding shifts to resources without register assignments?

### ISSUE THREAD

**Issue by ehsannas** [microsoft/DirectXShaderCompiler#2956]
_Copying from https://github.com/google/DirectXShaderCompiler/issues/316. All issues should be filed in the Microsoft repository_

<hr/>

From what I have understood (and experimenting with dxc), the -fvk-*-shift arguments provide binding shifts only for those resources that have explicit register assignments.

From https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#implicit-binding-number-assignment it appears that one can provide a descriptor set and otherwise it auto generates a binding:

"If there is no register specification, the corresponding resource will be assigned to the next available binding number, starting from 0, in descriptor set #0 (If -auto-binding-space N command line option is used, then descriptor set #N will be used instead of descriptor set #0)."

In glslang, we use the --auto-map-bindings option which behaves a bit differently in that it auto numbers bindings, but it applies the binding shifts.  So basically what I am looking for is a way to do this:

SamplerState sampler0 : register( s2 );
SamplerState sampler1;
SamplerState sampler2;

I'd like to pass -fvk-s-shift 10 0 and have 

sampler0 <- descriptor set 0, binding 12
sampler1 <- descriptor set 0, binding 10
sampler2 <- descriptor set 0, binding 11

This is what glslang would do.  Is it possible to do this with dxc?

**Comment by ehsannas** [comment]
The glslang behavior you described is not supported in DXC. The register assignment is needed in order to shift the bindings.

**Comment by danginsburg** [comment]
I've looked a bit at the dxc code, and I'll summarize what I have in mind, but I could use a bit of help figuring out how to do it.

In glslang, the categorization of each resource type into register spaces is given here: https://github.com/KhronosGroup/glslang/wiki/HLSL-FAQ#auto-mapped-binding-numbers

Currently, dxc applied the binding shifts only to those resources for which getRegister() is non-NULL:

https://github.com/microsoft/DirectXShaderCompiler/blob/355c4fb6a313a402ec108a0742073abb7e8f00ac/tools/clang/lib/SPIRV/DeclResultIdMapper.cpp#L1688

The idea would be to also apply the shifts (avoiding stomping on explicit assignments) around here: https://github.com/microsoft/DirectXShaderCompiler/blob/355c4fb6a313a402ec108a0742073abb7e8f00ac/tools/clang/lib/SPIRV/DeclResultIdMapper.cpp#L1749

If I could figure out how to get at the ArBasicKind (or equivalent info) of the resource at this point I think it would be straightforward to figure out which binding shift to apply.  Is there a way to do that at this point in the code?

**Comment by ehsannas** [comment]
I believe `var.getSpirvInstr()->getAstResultType()` should give you the type of the resource in the AST (`QualType`).

You should then be able to pass this QualType to a helper function [such as these](https://github.com/microsoft/DirectXShaderCompiler/blob/760e1cf8f1f1cf959495adf0af30195582cc1bba/tools/clang/lib/SPIRV/AstTypeProbe.cpp#L745-L837).
