### ISSUE TITLE
WDK requirement forced spectre mitigation on the project

### ISSUE THREAD

**Issue by galop1n** [microsoft/DirectXShaderCompiler#2965]
Right now, a WDK will add a property for Spectre mitigation that is on by default. If you do not have the libraries installed, DXC will fail to build and I could no find a way to force it back to disabled within the cmake files.

I ended up disabling it by removing the property that one installed as describe here: https://developercommunity.visualstudio.com/content/problem/348985/installing-wdk-1809-enabled-spectre-mitigation-fla.html

**Comment by pow2clk** [comment]
The WDK requirement is a source of some consternation for us. We'd like to remove it as a requirement. That is likely the solution we'd prefer here. It requires getting a particular header from somewhere else or convincing those responsible for it to let us include it here, which is a whole deal. 🙄
