### ISSUE TITLE
[SPIRV] Adding [[vk::intrinsic()]] for vulkan specific intrinsic

### ISSUE THREAD

**Issue by chaocNV** [microsoft/DirectXShaderCompiler#2966]
When doing HLSL->SPIRV translation, we always use the native language constructs when possible. However, sometimes the feature is missing in DX. To resolve this, we already have Vulkan specific attribute `[[vk::builtin()]]` to describe a Vulkan specific builtin. 

However, we currently do not have a Vulkan specific attribute for intrinsic. I propose we add a `[[vk::intrinsic()]]` for that purpose. Similar to builtin attribute, a function definition attributed with `[[vk::intrinsic()]]` will be mapped to the appropriate SPIRV instruction on spiregg path while being ignored on DXIL path. Also similarly, all intrinsic allowed should be listed under a new section in [https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#vulkan-specific-features](url) so we can keep track.

Following is a sample usecase:
To support  VK_KHR_shader_clock(
[https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_shader_clock.html](url)):

```
[[vk::intrinsic(ReadClockKHR)]]
 uint2 readclock() {};

void main() : SV_TARGET
{
  uint2 currentTime = readclock();
   ...
}
```

This will translate to 

`%currentTime = OpReadClockKHR`

**Comment by sudonatalie** [comment]
[ReadClock](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#readclock) has been supported for a while now as a Vulkan intrinsic function, and we now also allow a number of arbitrary "inline SPIR-V" instructions through [`vk::ext_*`](https://github.com/microsoft/DirectXShaderCompiler/wiki/GL_EXT_spirv_intrinsics-for-SPIR-V-code-gen) attributes, so I'm going to close this issue as resolved. If there were other missing intrinsics not covered by these features that you're interested in, feel free to open new issues and they'll be evaluated on a case-by-case basis.
