### ISSUE TITLE
DXC internal compile crash: function without return value

### ISSUE THREAD

**Issue by Nielsbishere** [microsoft/DirectXShaderCompiler#2975]
When compiling a raytracing hit shader with return type, if the return value isn't returned from the function but it is used, DXC crashes internally; this is very problematic for programs putting DXC into their program space (as it crashes the entire process; causing lost process for example). It doesn't happen with all functions without return value, only seems to be if the return value is used. For me this happens with a hit shader, I can send you a repro via DM.

Code for compiling:
```cpp
args = { L"/O3", L"/Zpc", L"-auto-binding-space", L"0" };
target = L"lib_6_4";
entry = L"";

hr = dxc->Compile(
	/*source blob in DM*/, nullptr, entry.c_str(),
	target.c_str(),
	args.data(), args.size(),
	nullptr, 0,
	defaultIncludeHandler,
	&out
);
```

Built with commit: b59671accf984327f471832dcb90c3002001be95

**Comment by Nielsbishere** [comment]
Thank you! One of the PRs mentions that it is a warning now? I guess I can manually parse that warning and raise it to an error?

**Comment by tex3d** [comment]
> Thank you! One of the PRs mentions that it is a warning now? I guess I can manually parse that warning and raise it to an error?

This change makes the existing warning emitted from missing return from non-void function default to error instead.  So this will cause compilation to fail by default.  No need to manually parse.
