### ISSUE TITLE
Build system requires Visual Studio to be installed on C:

### ISSUE THREAD

**Issue by jeffnn** [microsoft/DirectXShaderCompiler#2976]
(At least) two issues:

In several files, use of the %ProgramFilesx86% and %ProgramFiles% which map to c: even if VS is on d:

Use of [HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\VisualStudio\\14.0;InstallDir] in cmake\modules\FindDiaSDK.cmake, which isn't populated by VS2019 install.

**Comment by hekota** [comment]
Jeff, if you have VS installed on the d: is there `vswhere.exe` in `c:\Program Files (x86)\Microsoft Visual Studio\Installer`? I am not sure how else to detect the VS install location since VS2019 does not populate the registry entry.

**Comment by jeffnn** [comment]
I do have vswhere in that directory on my machine. TBH I can't remember, but i may originally have had VS on c:, then uninstalled it and re-installed it on d: in order to make space on c:
(So it's possible it wouldn't be there on c: if I had only ever installed on d:)

**Comment by pow2clk** [comment]
@hekota Did your recent changes to hctbuild.cmd resolve this?

**Comment by hekota** [comment]
Yes, I believe this should be resolved by #3138.
