### ISSUE TITLE
MeshShader ms6_5 - compiler failures passing indices/vertices out buffers to functions

### ISSUE THREAD

**Issue by CodedByATool** [microsoft/DirectXShaderCompiler#2977]
Results from dxcompiler.dll of 19041 sdk with File Version: 10.0.19041.1

Is there a way to have helper functions write to the shared output buffers?
(ie. vertices/indices passed as out argument to function?)

My attempts to do this have resulted in compiler crashes or shaders that run be do not do the correct thing.

Details...

I have been porting old Mesh Shaders written on NVAPI to DX12-Ultimate and in the process have hit several unhelpful compiler crashes or incorrect runtime behavior related to shared output buffers.

The code I started with would use a function to write **1 or more values** into the shared outputs for vertices and indices. This crashed the compiler and is best shown by TEST == 3 attached below.

Changing from use of _inout_ parameters to _out_ parameters resolved the compiler crash. But the runtime behavior was as if the shared output buffers were not being written to. Demonstrated by TEST == 2 attached below. Unexpected/Incorrect behavior.

When I finally stopped trying to pass the shared output buffers to any functions, which is very inconvenient from a code-design standpoint, I got the correct behavior. Demonstrated by TEST == 1 attached below. Though technically calling SetMeshOutputCounts _after_ writing the shared output buffers is incorrect.

[mesh_issue.txt](https://github.com/microsoft/DirectXShaderCompiler/files/4788620/mesh_issue.txt)

**Comment by pow2clk** [comment]
Hi @CodedByATool 

Thanks for the repro shader. though I had to move the `MAX_MESHLET_SIZE` up a few lines to get it to work for me, it was very helpful.

However, I cannot reproduce the issue with the latest DXC compiler. Can you confirm?

**Comment by pow2clk** [comment]
Assuming this is resolved. If not, please let us know.
