### ISSUE TITLE
[SPIR-V] "Block is already a merge block for another header" error

### ISSUE THREAD

**Issue by simontaylor81** [microsoft/DirectXShaderCompiler#2982]
I get the following error compiling one of our shaders with spir-v generation enabled:

```
fatal error: generated SPIR-V is invalid: Block 31[%31] is already a merge block for another header
  %main = OpFunction %void None %21

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

This looks very similar to #2932, but I'm not using `-fspv-flatten-resource-arrays` so I figured I'd create a new issue.

I manged to determine that this was not occurring prior to commit e0cde072b09b51506c0460697b2695d6cccca59d. But whether that introduced the problem, or just updated the validation so it now catches a pre-existing problem I do not know. For now the only workaround we have is to revert to a version prior to that change.

I spent some time breaking down the shader, removing all the bits that don't seem to be relevant to the repro, hoping to get a clue into what's breaking, and this is what I ended up with. As you can see, it looks pretty bonkers, so I don't really know what's going on! Of course this doesn't look much like the real shader any more, but this is a lot smaller and more suitable for posting on a public place :). I've marked a few places with comments that seem pointless but are actually required for the repro. Perhaps they will provide some clues.

Compile this with `-E main -T cs_6_0 -spirv`

```
RWStructuredBuffer<float> output;
uint varyingInput;

struct Data
{
	uint flags;
	float4 extended;	// Must be a vector -- scalar float does not repro
};

// This function looks completely pointless, but without it there is no repro
// (obviously it does something in the actual shader!)
void emptyFunction(inout float4 param)
{
}

bool boolFunction(Data data)
{
	// This must be a if-else, conditional expression, cast or just if (without else) does not repro
	if (data.flags)
	{
		return true;
	}
	else
	{
		return false;
	}
}

Data getData()
{
	Data data;
	data.flags = varyingInput;
	data.extended = 0;

	emptyFunction(data.extended);

	if (boolFunction(data))
	{
		// This must be a single component, setting the whole vector does not repro
		data.extended.x = 0;
	}

	return data;
}

// Must be >= 2, 1 does not repro
#define LOOP_COUNT 2

[numthreads(64, 1, 1)]
void main()
{
	// Must be unroll, [loop] does not repro
	[unroll]
	for(uint i = 0; i < LOOP_COUNT; ++i)
	{
		output[0] = getData().extended.x;
	}
}
```

**Comment by ehsannas** [comment]
Thanks for reporting @simontaylor81 and for the detailed investigation. We'll take a look.

**Comment by ehsannas** [comment]
This might be because loop-unrolling has been added to default performance passes in spirv-opt.
