### ISSUE TITLE
DXC.exe silently crashes instead of reporting errors

### ISSUE THREAD

**Issue by kayru** [microsoft/DirectXShaderCompiler#2988]
When dxc.exe crashes (which sadly is still a common occurrence), it does not report any errors to the console. Ideally, it should at least report that an ICE has occurred and possibly (optionally) even report crash details that could be used to easily report bugs here.

**Comment by simontaylor81** [comment]
As an addendum to this, it appears that when not run through the debugger, asserts cause compilation to hang, both when run through dxc.exe or the dll. This is particularly annoying as it causes our build farm to sit there for 9 hours until it eventually times out :). So it would be great if we could get some kind of ICE error in that scenario as well.

**Comment by kayru** [comment]
Wanted to bump and clarify the "ask" a little: I would simply like to have an "internal compiler error" message written to stdout/stderr on dxc crash. I am not after any call stack dumps, just a clear indication that something went wrong. Simply want dxc.exe to follow the well established convention of success=silent error=log.

**Comment by pow2clk** [comment]
Completed with #3636, #3691

**Comment by yuriy-odonnell-epic** [comment]
Excellent news! Thank you for doing this.
