### ISSUE TITLE
mesh shaders: dxc hangs when I pass in the payload as argument to a function

### ISSUE THREAD

**Issue by rpsathe** [microsoft/DirectXShaderCompiler#2992]
Please see the attached file. dxc hangs when Payload is passed in arguments to one of the functions. 

[test.txt](https://github.com/microsoft/DirectXShaderCompiler/files/4811121/test.txt)

Change #if 1 on line 126 to #if 0 and see the dxc succeed.

ms_body2 does a similar thing as ms_body but without the payload argument and that works !

Command line used 
"c:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\dxc.exe"  -T ms_6_5 -E ms_main test.txt
[test.txt](https://github.com/microsoft/DirectXShaderCompiler/files/4811122/test.txt)

**Comment by pow2clk** [comment]
Hi @rpsathe!

Using the latest DXC, I cannot reproduce this issue. Can you confirm?

**Comment by pow2clk** [comment]
Assuming this is resolved. Let us know if it isn't.
