### ISSUE TITLE
[SPIR-V] Unable to store buffers in shader_record_nv

### ISSUE THREAD

**Issue by mattruschnv** [microsoft/DirectXShaderCompiler#2995]
```
struct meshData
{
    ByteAddressBuffer Vertices;
    ByteAddressBuffer Indices;
};

[[vk::shader_record_nv]]
ConstantBuffer<meshData> meshDataBuf;
```

Results in shader error: A Block or Buffer Block cannot be nested within another Block or Buffer Block

Is there a workaround to passing pointers to shaders by way of an SBT shader record? GLSL has buffer references, but I can't find anything similar in HLSL.

**Comment by ehsannas** [comment]
AFAIK There are no equivalents to GLSL buffer references in HLSL

**Comment by natevm** [comment]
I have this working in my code by using raw buffer device addresses. In the shader records, I store the VkDeviceAddress to a uint64_t value in the SBT record rather than a ByteAddressBuffer. Then, I use the vk::RawBufferLoad command to load from that address.

**Comment by natevm** [comment]
Fwiw, I use these templates to make the loads and stores to pointer addressing math for me:

template<typename T> 
  T load(uint64_t bufferaddr, uint64_t index) {
    return vk::RawBufferLoad<T>(bufferaddr + index * sizeof(T));
  }
  template<typename T> 
  void store(in uint64_t bufferaddr, uint64_t index, in T value) {
    vk::RawBufferStore<T>(bufferaddr + index * sizeof(T), value);
  }

**Comment by sudonatalie** [comment]
Thanks for the comments @natevm! I believe the `vk::RawBufferLoad` and `vk::RawBufferStore` intrinsics do satisfy this use case as well as possible right now so closing this issue.
