### ISSUE TITLE
[SPIR-V] Memory Leak

### ISSUE THREAD

**Issue by Bizzarrus** [microsoft/DirectXShaderCompiler#3002]
Hi,

We in our company noticed DXC to have a memory leak when compiling shaders to SPIR-V. We are compiling over 200.000 shaders on our build server (yeah, the game uses a lot of shaders...), and the program regularly crashes due to running out of memory. (We could track the problem down to DXC and the -spriv argument). 

If it's important: We are compiling shaders on all available HW threads in parallel (obviously, it would take ages compiling that many shaders single threaded), and we also tried the most recent release (the one with the IDxcCompiler3 interface).

**Comment by ehsannas** [comment]
Hi @Bizarrus ! Thanks for bringing this to our attention. This is an important area to invest our time in.

**Comment by ehsannas** [comment]
Hi @Bizzarrus, I have landed a change that should fix all memory leaks in the SPIR-V backend. (https://github.com/microsoft/DirectXShaderCompiler/pull/3091)
