### ISSUE TITLE
[SPIR-V] Some Input or Output variables in mesh shaders and amplification shaders don't have Location assignments

### ISSUE THREAD

**Issue by ehsannas** [microsoft/DirectXShaderCompiler#3006]
Hi @sparmarNV 

It looks like some mesh payload variables that are `Input` or `Output` variables to the SPIR-V module do not have a `Location` assignment. As a result, the [recent update](https://github.com/KhronosGroup/SPIRV-Tools/commit/a1fb255a2a6856bba1e5a8486469ac93fca518c2) to SPIRV-Tools validator causes test failures in DXC.

These are the test failures:
```
[  FAILED  ] FileTest.MeshShadingNVMeshTriangle
[  FAILED  ] FileTest.MeshShadingNVMeshBuffer
[  FAILED  ] FileTest.MeshShadingNVAmplification
[  FAILED  ] FileTest.MeshShadingNVAmplificationFunCall
```

In all of these cases, we have an `OpVariable` with storage class of `Input` or `Output` without a `Location` assignment.

I need go ahead with updating the SPIRV-Tools version inside DXC in order to address several other issues. In the meantime, I will disable running the validator on the above tests. Once this issue is resolved, we can restore running the validator for these tests.

**Comment by ehsannas** [comment]
I have temporarily disabled running spirv-val on the above tests via https://github.com/microsoft/DirectXShaderCompiler/pull/3007

**Comment by ehsannas** [comment]
@sparmarNV Please let me know your thoughts on this issue. Thanks

**Comment by ehsannas** [comment]
@alelenv @chaocnv Please take a look

**Comment by alelenv** [comment]
sparmarNV is no longer with NV, please redirect future queries to me/chaocNV
@chaocNV can you take a look?

**Comment by chaocNV** [comment]
Thanks for bringing this up. I'll work on it.
