### ISSUE TITLE
Dxc considers includes relative to the root shader file valid

### ISSUE THREAD

**Issue by Skylark13** [microsoft/DirectXShaderCompiler#3021]
Hello,

This may be a bit hard to explain, so I made a simple repro example.
[hlsl.zip](https://github.com/microsoft/DirectXShaderCompiler/files/4864389/hlsl.zip)

In this example, there are 2 hlsl files and 2 headers in a specific directory structure.
```
A/a.hsh         <-- includes "B/b.hsh"
B/b.hsh
C/test2.hlsl    <-- includes "../A/a.hsh"
test1.hlsl      <-- includes "A/a.hsh"
```

You will see that even though the include in A/a.hsh is wrong (there is no subdirectory B inside A, the include should be "../B/b.hsh"), test1.hlsl will compile fine, while test2.hsh will not compile.

I believe this is a bug in the path handling of indirect includes. Dxc seems to consider the path of the include starting at the path where the root hlsl file being compiled (test1.hlsl) is located, instead of where the file that has the include in it (A/a.hsh) is located.

I would expect test1.hlsl to fail to compile with an error like "`A\a.hsh:1:10: fatal error: 'B/b.hsh' file not found`". The same error as you get when you compile test2.hlsl. Otherwise, it's possible for users to write include files that can be included without error from some files but not from others.

Thanks in advance.

**Comment by llvm-beanz** [comment]
DXC follows the common convention of C compilers where the current working directory of the compiler process and the source directory of the current translation unit are both considered as include search paths for user headers. This is expected and correct behavior. FXC got this wrong.
