### ISSUE TITLE
Reflection stripping for shader lib target appears to be broken/regressed from 2019 version

### ISSUE THREAD

**Issue by matthewjnv** [microsoft/DirectXShaderCompiler#3058]
Observe this simple shader, compiling with /Qstrip_reflect works for the compute shader target but not as a library target. Interestingly it's not specific to raygen, as I can select export for compute shader as well.

This appears to be a regression from 2019 release which strips reflection data as expected.

Repro:

dxc /auto-binding-space 1 /Qstrip_debug /Qstrip_reflect /Qstrip_private /E ShaderCompute /Zpr /O3 /T cs_6_3 /FcShaderReflectionTest.compute.d3dasm ShaderReflectionTest.shader

dxc /auto-binding-space 1 /Qstrip_debug /Qstrip_reflect /Qstrip_private /exports ShaderRGS /Zpr /O3 /T lib_6_3 /FcShaderReflectionTest.raygen.d3dasm ShaderReflectionTest.shader

Shader:

Texture2D DummyTexture;

[shader("compute")]
[numthreads(1, 1, 1)] 
void ShaderCompute()
{
	return;
}

[shader("raygeneration")] void ShaderRGS()
{
	return;
}

Attached output generated: 

[ShaderReflectionTest.compute.d3dasm.txt](https://github.com/microsoft/DirectXShaderCompiler/files/5003779/ShaderReflectionTest.compute.d3dasm.txt)
[ShaderReflectionTest.raygen.d3dasm.txt](https://github.com/microsoft/DirectXShaderCompiler/files/5003780/ShaderReflectionTest.raygen.d3dasm.txt)

**Comment by matthewjnv** [comment]
I actually tracked down two issues that seem to prevent stripping from happening.

Both is in DxilModule::StripReflection() and related to library targets

The big culprit is the min precision code, in this one test shader it adds over 40% to binary size, because of all the structures using matrix types. This happens despite the shader not actually using half types at all in the matrices.

The other (which is what this bug was filed against) has to do with not being able to strip the globals if global constructors are used for libraries. In this case though there is no global constructor?

**Comment by pow2clk** [comment]
Hi @matthewjnv!

This is a known issue that I'm working on. Unfortunately, the fix isn't trivial.

In the meantime and even after, we strongly recommend using `-enable-16bit-types` unless you have a good reason not to.
