### ISSUE TITLE
[SPIR-V] Negative of a matrix fails 

### ISSUE THREAD

**Issue by cpt-max** [microsoft/DirectXShaderCompiler#3069]
It looks like the unary negate operator for matrices is not supported when compiling to SPIRV.
This simple vertex shader will cause a crash during optimization:
```
float4 VS() : SV_Position
{
    float4x4 mat = 0;
    float4 vec = 0;
    return mul(-mat, vec);
}
```
With optimizations disabled it will compile without crashing, but the generated SPIRV is probably invalid.

**Comment by ehsannas** [comment]
Thanks for reporting @cpt-max
