### ISSUE TITLE
Access to AST

### ISSUE THREAD

**Issue by vaspoul** [microsoft/DirectXShaderCompiler#3071]
I'd like to use dxc's AST dump to build metadata about a shader. Can I rely on the -ast-dump command line parameter being available and maintained for the foreseable future? I've noticed it's not listed in the list of available command line params (dxc /?) and I'd be wary of building a framework around an undocumented feature.

I've also seen a post where IDxcCursor is mentioned as an available option to iterating through the AST. Is that something that's only accessible through dxc's internal headers? I ask because IDxcCursor is not available through dxcapi.h. I assume it's something similar to libclang's CXCursor?

Thank you!

**Comment by ehsannas** [comment]
The SPIR-V backend of the compiler relies on the AST to generate the SPIR-V binary. So I think you can count on the AST being a valid tree to work off of.

(I don't know anything about IDxcCursor.)

**Comment by vaspoul** [comment]
Leaving this here in case it's useful to someone else.
IDxcCursor is available in dxc-artifacts\include\dxc\dxcisense.h, which you can get from either building from source or by downloading the Appveyor artifacts.
