### ISSUE TITLE
do-while loops produce invalid code

### ISSUE THREAD

**Issue by crazydef** [microsoft/DirectXShaderCompiler#3072]
It appears do-while loops produce invalid code (in just about every way possible).

The generated output from the following function is horribly broken:

```
float FindHeader( float pos, float pixelsize, inout int3 uv )
{
	int	iterations = 5;

	do
	{
		float4	texel = gTex.Load( uv );

		if( texel.x > 0.0f )
		{
			if( pos < ( texel.y - pixelsize ))
			{
				return 0.0f;
			}
		}
		if( pos <= texel.z )
		{
			return texel.x;
		}
		uv.x += int( max( 0.0f, texel.x )) + 1;
	}
	while( --iterations );

	return -1.0f;
}
```

And the compiler issues two warnings on the braces following the inner return statements:

`warning X4000: use of potentially uninitialized variable (FindHeader)`
`warning X4000: use of potentially uninitialized variable (FindHeader)`

Changing the loop to a standard `while` loop works just fine:

```
float FindHeader( float pos, float pixelsize, inout int3 uv )
{
	int	iterations = 5;

	while( --iterations )
	{
		float4	texel = gTex.Load( uv );

		if( texel.x > 0.0f )
		{
			if( pos < ( texel.y - pixelsize ))
			{
				return 0.0f;
			}
		}
		if( pos <= texel.z )
		{
			return texel.x;
		}
		uv.x += int( max( 0.0f, texel.x )) + 1;
	}
	return -1.0f;
}
```

(Slightly contrived example, but it illustrates the point.)

This bug might have been the cause for this issue too:  https://developercommunity.visualstudio.com/content/problem/1145221/graphics-debugger-shows-different-values-when-hove.html

(I figured out this after I created the above.)

**Comment by pow2clk** [comment]
Can you go into more detail about what aspects of the output are "horribly broken"?

The warnings you list suggest you are using FXC. Is that correct? 

FXC is not in active development and this is not where issues pertaining to it should be reported. Please see https://github.com/microsoft/DirectXShaderCompiler/wiki/FAQ#what-happens-to-the-old-compiler-fxc

**Comment by crazydef** [comment]
The shader code produced was pretty much garbage.  Insofar as it just didn't work.  I didn't step through the compiled code to work out exactly what was broken (well, I tried, but the shader debugger couldn't understand what was going on either, hence my other bug report about that), but suffice to say the generated code from the two different types of loop wasn't comparable.

Here's a complete shader you can use for testing:
```
struct PSInput
{
	float4	mPosition	: SV_POSITION;
	float3	mCoords0	: TEXCOORD0;
};

Texture2D		gFont : register( t4 );

int FindHeader( float pos, inout int3 uv )
{
	int	iterations = 5;


#if 0		// Change to 1 to compile buggy version.
	do
	{
		float4	texel = gFont.Load( uv );

		if( pos < texel.y )
		{
			return 0;
		}
		if( pos <= texel.z )
		{
			return texel.x;
		}
		uv.x += int( texel.x ) + 1;
	}
	while( --iterations );
#else
	while( iterations-- )
	{
		float4	texel = gFont.Load( uv );

		if( pos < texel.y )
		{
			return 0;
		}
		if( pos <= texel.z )
		{
			return texel.x;
		}
		uv.x += int( texel.x ) + 1;
	}
#endif
	return 0;
}

float4 main( PSInput input ) : SV_TARGET
{
	int3	uv = int3( 0, 0, 1 );

	return float4( FindHeader( input.mCoords0.x, uv ), 0.0f, 0.0f, 1.0f );
}
```

The number of differences between the two compiled versions goes way beyond what I would expect from a simple loop semantic change.

The hlsl files are part of a Visual Studio 2019 project and compiled with whatever that uses in the background.  Could be FXC.  Could be something else.  (I don't know.)

**Comment by pow2clk** [comment]
Thanks for the complete shader. It's good to ensure we're using the same code.

Using the latest DXC compiler and also the version that ships with VS 2019, I see sensible minimal differences or no differences at all between the output.

Using the FXC that ships with VS 2019, I see large differences. I think it's clear that you are using FXC. I believe if you target a shader model < 6.0, visual studio will use FXC. If you use 6.0 or higher, you should get DXC.

**Comment by crazydef** [comment]
Ah, makes sense.  I'm targeting shader model 5.0.

**Comment by pow2clk** [comment]
In that case, given that there's a workaround for FXC, I'm afraid this is a won't fix. 

Thanks for reporting and for your prompt responses!
