### ISSUE TITLE
Fix unintended includes in artifacts

### ISSUE THREAD

**Issue by pow2clk** [microsoft/DirectXShaderCompiler#3084]
Problems:

1. dxc artifacts should not contain all the headers under the include/dxc path. These should just be the top-level public dxc*.h headers directly under dxc/.
2. Headers in this set including other headers in this set should include them without any directory prefix.
3. These top-level headers should not include other headers that are not in this set. This means that WinAdapter.h needs to be included in some other way outside of these headers before including these headers, when _WIN32 is not defined.
4. Outside projects should not be including any of the other headers (except for some advanced, unsupported scenarios, where they can copy/modify headers locally or something).

stolen from # 2385

**Comment by jenatali** [comment]
+1

Specifically painful is the use of WinAdapter.h directly from the public API header.

**Comment by pow2clk** [comment]
As appveyor builds are no more and ADO builds will do this right, there's nothing to do here in addition to enabling artifacts for ADO builds. Closing.
