### ISSUE TITLE
[SPIR-V] Global struct variables containing only resources fail validation with '-O0' optimization level

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#3100]
Hi, it seems that the fix to https://github.com/microsoft/DirectXShaderCompiler/issues/2695 doesn't work when optimization is disabled.

### Functional impact
The shader doesn't compile. Cannot use the unoptimized version of the shader for debugging purposes when shader uses the legacy combined texture sampler emulation workaround mentioned in https://github.com/microsoft/DirectXShaderCompiler/issues/2695

### Minimal repro steps
The repro source is the same:

```
struct sampler2D {
  Texture2D t;
  SamplerState s;
};
float4 tex2D(sampler2D x, float2 v) { return x.t.Sample(x.s, v); }

struct v2f {
  float4 vertex : SV_POSITION;
  float2 uv : TEXCOORD0;
};

sampler2D g_CombinedTextureSampler;

float4 PSMain(v2f i) : SV_Target {
  return tex2D(g_CombinedTextureSampler, i.uv);
}
```
Compiling with opt. level 0: `dxc.exe -T ps_6_0 -E PSMain repro_shader.txt -spirv -O0` results in error:

```
fatal error: generated SPIR-V is invalid: UniformConstant OpVariable <id> '8[%g_CombinedTextureSampler]' has illegal type.
From Vulkan spec, section 14.5.2: 
Variables identified with the UniformConstant storage class are used only as handles to refer to opaque resources. Such variables must be typed as OpTypeImage, OpTypeSampler, OpTypeSampledImage, OpTypeAccelerationStructureNV, OpTypeAccelerationStructureKHR, OpTypeRayQueryProvisionalKHR, or an array of one of these types.
  %g_CombinedTextureSampler = OpVariable %_ptr_UniformConstant_sampler2D UniformConstant

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

### Further technical details
Used latest DXC on Windows built from 530958e4b7a2c198f012c8f1dc1656c9dbc02148

**Comment by ehsannas** [comment]
This is expected I'm afraid. DXC relies on SPIRV-Tools (`spirv-opt` in particular) to properly handle these structures. What essentially happens is that spirv-opt "flattens" these structures and resolves all references to their members as standalone resources with their own dset/binding. So, sadly as it stands today, disabling spirv-opt will prevent this from working.

**Comment by ehsannas** [comment]
I just realized that we can modify the interaction between DXC and `spirv-opt` such that we run the necessary spirv-opt pass for such cases as part of "legalization" rather than "optimization" (which sounds like a better fit anyway, as without this the result is not valid/legal). 

I've been thinking about whether moving this pass earlier in the flow could have any unforeseen consequences, but I can't think of any. Our testing is with pretty lightweight shaders, and they all pass. So I'm going to post a PR for it.

**Comment by ehsannas** [comment]
Posted the PR. @Dredhog Please let me know if you face any issues with this. Thanks!

**Comment by Dredhog** [comment]
Great news @ehsannas, I'll try it out!

**Comment by Dredhog** [comment]
Seems to be fixed, didn't find any regressions!

**Comment by ehsannas** [comment]
Awesome! Thanks for checking 👍
