### ISSUE TITLE
[SPIR-V] - BaseInstance not supported in ES profile

### ISSUE THREAD

**Issue by GregSlazinski** [microsoft/DirectXShaderCompiler#3106]
Hello,

Since updating DirectXShaderCompiler to the latest version, now every time I'm trying to compile for SPIRV GLSL ES 300 I'm getting the following error under SPIRV-Cross
         spvc_compiler_options_set_bool(options, SPVC_COMPILER_OPTION_GLSL_ES, SPVC_TRUE);
         spvc_compiler_options_set_uint(options, SPVC_COMPILER_OPTION_GLSL_VERSION, 300);
Error: "BaseInstance not supported in ES profile"

This is perhaps related to this change?
https://github.com/microsoft/DirectXShaderCompiler/issues/2946
https://github.com/microsoft/DirectXShaderCompiler/pull/3011

What I'm using is "SV_InstanceID", which is for HW Instancing, and it is supported in GL ES.
I'm not using any "base instance".

If you need "base instance" for something, then can you at least make it optional via compiler option instead of forced? So that I can use GLSL ES as before the update.

SpirvCross has something related to the base instance:
spvc_compiler_options_set_bool(options, SPVC_COMPILER_OPTION_GLSL_SUPPORT_NONZERO_BASE_INSTANCE, SPVC_FALSE);
I've tried setting it to SPVC_TRUE and SPVC_FALSE but still getting that error.

So maybe, instead of processing base instance on the DX Compiler side, one can just enable the SPVC_COMPILER_OPTION_GLSL_SUPPORT_NONZERO_BASE_INSTANCE for spirv-cross?

Now my shader compilation toolchain is broken, and my work is at a halt because of this issue.

**Comment by kuhar** [comment]
Thanks for reporting, @GregSlazinski. Assigning to Ehsan, since made the mentioned changes.

**Comment by ehsannas** [comment]
SPIR-V codegen is generating gl_BaseInstance to address #2946

**Comment by ehsannas** [comment]
We might need to add a command line option for this (e.g. `-fspv-support-nonzero-base-instance`), and have the default behavior to assume base instance is zero.

**Comment by ehsannas** [comment]
I'll try to reprioritize.

**Comment by jaebaek** [comment]
Fixed by #3478
