### ISSUE TITLE
Using DXC from C#

### ISSUE THREAD

**Issue by QuantumDeveloper** [microsoft/DirectXShaderCompiler#3107]
Can you please point me in right direction.

**Does DXC has C style public interface to use it from C# via p/invoke?**
If not, then how I can call DXC functions from DLL in cross-platform way.
Because I know that C++/CLI for .Net core is not supporting on Mac or Linux, so C++/CLI is not an option here unfortunately.

Can you please help me with this?

**Comment by pow2clk** [comment]
I am not sufficiently familiar with C# to answer your direct question, but perhaps the example presented by dndxc would help: https://github.com/microsoft/DirectXShaderCompiler/tree/master/tools/clang/tools/dotnetc 

I don't know how cross platform it is I'm afraid.

**Comment by QuantumDeveloper** [comment]
Is there some manual how to use it correctly? and Also is there some nuget package wit this code or I need to manually link it to my project somehow?

**Comment by pow2clk** [comment]
There is no manual. C# is not the primary path for using the DLL interface. I pointed to dndxc not as something to link to, but as an example of how the existing C++ compiler libraries can be linked to and used by a C# executable.

dndxc is a bit of a misnomer. It is not *the* dotnet version of dxc, it's just a utility app useful mostly to compiler developers that happens to use C# and links dxcompiler.dll. Nevertheless, it might be helpful as an example to you.

All the code involved is in the subdirectory I linked. That is the primary way to get it, but there's nothing special about it as it's just an example of how a C# application might go about using the compiler.

**Comment by QuantumDeveloper** [comment]
Ah... Ok, now I see. Thanks for the hint. Will look into it in more details

**Comment by pow2clk** [comment]
We are going to work on improving this interface. We plan to be using IDL to generate the header which should facilitate this interface. 

Thanks for bringing this up! let us know if you have other issues.

**Comment by QuantumDeveloper** [comment]
@pow2clk Could you please say when do you plan to do this header generation? At least approximately.
