### ISSUE TITLE
Compile Error: No newline at end of file

### ISSUE THREAD

**Issue by Ravbug** [microsoft/DirectXShaderCompiler#3108]
When compiling on Mac with Xcode, the compile fails with "No newline at end of file" in many .inc files.

**Steps to reproduce:**
1) `git clone --depth=1 --recurse-submodules https://github.com/microsoft/DirectXShaderCompiler`
2) `cd DirectXShaderCompiler && mkdir build && cd build`
3) `cmake -G "Xcode" -DCMAKE_BUILD_TYPE=Release $(cat ../utils/cmake-predefined-config-params) ..`
4) Open the created `LLVM.xcodeproj`, select the `SPIRV-Tools-static` target, and press Build
5) Compile error

**Screenshot:** 
<img width="271" alt="image" src="https://user-images.githubusercontent.com/22283943/91767514-1ac31800-eb91-11ea-8305-f654a66af928.png">
<img width="481" alt="image" src="https://user-images.githubusercontent.com/22283943/91767568-2d3d5180-eb91-11ea-8506-226483c71d6c.png">

**Potential Fix:**
Adding newlines as recommended by the Fix suggestion fixes the error.

**Computer information**
OS: macOS 10.15.6
Xcode version: 11.6 (11E708)

**Comment by ehsannas** [comment]
closing this for two reasons: 
a) This sounds like a quirk of Xcode. Compiles fine with `-GNinja`. See our CI buildbot [script](https://github.com/microsoft/DirectXShaderCompiler/blob/master/.travis.yml#L80) and [results](https://travis-ci.org/github/microsoft/DirectXShaderCompiler). 
b) SPIRV-Tools is an [external dependency](https://github.com/KhronosGroup/SPIRV-Tools). The change will have to be made in the upstream repository.
