### ISSUE TITLE
[SPIR-V] Compiler crash when using mul on float4x1 and float1x4

### ISSUE THREAD

**Issue by nickyc95** [microsoft/DirectXShaderCompiler#3109]
Hi,

We are experiencing a DXC compiler crash when running the following snippet of HLSL.
(This is a cut down version of a bigger shader which reproduces the crash)

```
struct PSInput
{
	float4 color : COLOR;
    float4x4 a : TEXCOORD0;
};

void update( inout float4x4 p, in float3 z )
{
    float4x1 x = float4x1( 1, z );
    float1x4 xT = transpose( x );
    float4x1 delta = mul( p, x );
    
    float4x4 a = mul( delta, xT );
    p	    = mul( a, p );
}

float4 PSMain(PSInput input) : SV_TARGET
{
    update(input.a, float3(0,0,1));
    input.color.r = input.a[0][0];
    
	return input.color;
}
```

The cause of the issue appears to be the `mul(delta, xT)` 
Crash occurs at `IDxcCompiler::Compile`

**Compiles fine on:**

- FXC

- DXC (DXIL)

**Fails on:**

- DXC (SPIR-V)

Tested on ShaderPlayground DXC from trunk on 2020-02-16.

**Comment by ehsannas** [comment]
Thanks for reporting @nickyc95. I'll take a look.
