### ISSUE TITLE
[SPIR-V] store value of type 'RayQuery<0>' is unsupported

### ISSUE THREAD

**Issue by turanszkij** [microsoft/DirectXShaderCompiler#3119]
Hi,
I am trying to compile shaders that use inline raytracing, but getting errors like:
`EXEC : error : store value of type 'RayQuery<0>' is unsupported`
Originally, I had some ray flags in there, but removed them to see if it helps, but no. Am I missing something?

I am using shader code like this:

```
RayQuery<
	RAY_FLAG_FORCE_OPAQUE |
	RAY_FLAG_SKIP_PROCEDURAL_PRIMITIVES |
	RAY_FLAG_ACCEPT_FIRST_HIT_AND_END_SEARCH
> q;

RayDesc ray;
ray.TMin = 0.001;
ray.TMax = dist;
ray.Origin = P + N * 0.01;
ray.Direction = L;

q.TraceRayInline(scene_acceleration_structure, 0, 0xFF, ray);
q.Proceed();

if (q.CommittedStatus() == COMMITTED_TRIANGLE_HIT)
{
	return 0;
}
```
(Which is part of a large forward rendering shader)

Thanks

**Comment by turanszkij** [comment]
I forgot to mention that this is only a problem when compiling SPIRV

**Comment by ehsannas** [comment]
Thanks for reporting @turanszkij

**Comment by turanszkij** [comment]
Hi,

Sorry to bump this, but this is still a problem with the latest compiler. Actually, I successfully compiled RayQuery in some shaders, but my use case is executing RayQuery inside a pixel shader inside a deep loop (forward+ rendering). I have put together a repro case, hopefully it will help you uncover something. 

The repro case contains a repro.bat that will call DXC compiler to compile objectPS.hlsl. There are many included files in this shader and all of them are included in the zip.

PS. I also tried moving out the RayQuery outside of the loop, but that causes some other random shaders to fail compilation without even an error message. Also, I can't use that version with DX12 because if I move out the RayQuery to a bigger scope, it will produce GPU hang.

[repro.zip](https://github.com/microsoft/DirectXShaderCompiler/files/5706030/repro.zip)

**Comment by turanszkij** [comment]
More info about the repro case:
The RayQuery is called in lightingHF.hlsli, line 107, and it is doing raytraced shadow inside a light iteration loop.
I will gladly provide any more details you should require.

Thanks,
Janos

**Comment by westlicht** [comment]
I'm running into the same issue, are there any insights into this? Even just a WAR would be fine.

**Comment by apanteleev** [comment]
> I'm running into the same issue, are there any insights into this? Even just a WAR would be fine.

I ran into this issue a few months ago. In my case, this issue could be worked around by not using any member functions in structs in HLSL. Seems unrelated, but it worked.

**Comment by westlicht** [comment]
> I ran into this issue a few months ago. In my case, this issue could be worked around by not using any member functions in structs in HLSL. Seems unrelated, but it worked.

Hah, that's one of the main reasons I chose HLSL over GLSL for my project :) I will try. Thanks a lot for the hint!!

**Comment by yuriy-odonnell-epic** [comment]
We also hit this in our production shaders. I have spent a bit of time to make a minimal repro. It's quite amazing:
```
// dxc -T cs_6_3 -spirv -fspv-target-env=vulkan1.2 shader.hlsl

void Fun() { 
  RayQuery<0> RayQ;  
}

struct SomeStruct {
  void DummyMethod() {};
};

[numthreads(1, 1, 1)]
void main() {
  SomeStruct Payload;
  Payload.DummyMethod();
  //RayQuery<0> RayQ; // works
  Fun(); // borks
}
```
As per @apanteleev's hint, removing member function calls from the basic block that has a call to a function with a ray query also works around the problem for us. However, it's not an amazingly practical workaround for us, as we use member functions quite extensively in Unreal Engine shaders.

**Comment by jaebaek** [comment]
Let me take a look. I will get back after checking the details.
