### ISSUE TITLE
Slow compilation when inlining code without debug infos

### ISSUE THREAD

**Issue by mkroll-nv** [microsoft/DirectXShaderCompiler#3130]
For some 4 MB generated HLSL code (which I'm not allowed to share :( ), involving quite a deep call graph with lots of calls, the compilation with the DirectXShaderCompiler (commit e3a83447474) is very slow.
Using the profiler of Visual Studio on a RelWithDebInfo build of dxc with "-T lib_6_5 <HLSL file>" as command line, I got this result (aborting after two minutes of compilation):

![image](https://user-images.githubusercontent.com/29729967/93182498-0c046580-f73a-11ea-96f7-8ed645a48eb8.png)

When a call is inlined in llvm::InlineFunction(), the inliner tries to update the line number information using fixupLineNumbers().
If the call itself doesn't have a debug location, it looks up the debug information for the function containing the inlined call with getDISubprogram().

![image](https://user-images.githubusercontent.com/29729967/93182813-6dc4cf80-f73a-11ea-8109-c7f4fd68bbbe.png)
https://github.com/microsoft/DirectXShaderCompiler/blob/3811872f2f8e17838ca877ee1721fe2aa2927326/lib/Transforms/Utils/InlineFunction.cpp#L884
This function iterates over all instructions of the function until it finds debug information or the end of the function.

![image](https://user-images.githubusercontent.com/29729967/93182625-35bd8c80-f73a-11ea-92ee-6bed38b92715.png)

When we compile without debug information, have a lot of functions to inline and produce more and more code by all the inlining, this takes quite a significant amount of time, without adding anything to the result, as there is no debug info to be found.
Also the assumption in the comment in fixupLineNumbers() is wrong, that the inlined calls are from global variable initialization. These are normal functions calls.
Calling getDISubprogram() was introduced with https://github.com/microsoft/DirectXShaderCompiler/commit/3811872f2f8e17838ca877ee1721fe2aa2927326.

**Comment by pow2clk** [comment]
Hi @mkroll-nv!

The submitted fix is just a bit speculative, so I'd appreciate confirmation that it resolves your issue.
