### ISSUE TITLE
[SPIR-V] Loading element from constant buffer arrays into variables produces invalid SPIR-V

### ISSUE THREAD

**Issue by Piratkopia13** [microsoft/DirectXShaderCompiler#3131]
### Functional impact
Not allowing storing an element of a constant buffer array as a local variable forces array indexing to be used everywhere, causing messy code.

### Minimal repro steps
Compile the following test shader with `dxc.exe -T ps_6_0 -E main test.hlsl -spirv`
```hlsl
struct S {
    float4 f;
};

ConstantBuffer<S> myCBuffer[];

float4 doStuff(S buffer) {
    return buffer.f;
}

float4 main(in float4 pos : SV_Position) : SV_Target0
{
    S buffer = myCBuffer[0];
    return doStuff(buffer);
}
```

### Expected result
No error.

### Actual result
We get the following output:
```
fatal error: generated SPIR-V is invalid: OpAccessChain result type (OpTypeStruct) does not match the type that results from indexing into the base <id> (OpTypeStruct).
  %19 = OpAccessChain %_ptr_Uniform_S %myCBuffer %int_0

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

### Further technical details
This issue seems similar to #838

**Comment by ehsannas** [comment]
Thanks for reporting @Piratkopia13
