### ISSUE TITLE
[spirv] support "Type Qualifiers" for OpenCL.DebugInfo.100 instructions

### ISSUE THREAD

**Issue by jaebaek** [microsoft/DirectXShaderCompiler#3135]
This issue is related to the debug information generation of SPIR-V backend (related PR: #3125).
See [Type Qualifiers](https://www.khronos.org/registry/spir-v/specs/unified1/OpenCL.DebugInfo.100.html#_type_qualifiers_a_id_typequalifiers_a).

**Comment by s-perron** [comment]
@SteveUrquhart The same for this one. The maintainers will not be fixing this. Let us know if you think you will want to fix it. If not, we will close the issue.
