### ISSUE TITLE
[spirv] support enum types for OpenCL.DebugInfo.100 instructions

### ISSUE THREAD

**Issue by jaebaek** [microsoft/DirectXShaderCompiler#3137]
This issue is related to the debug information generation of SPIR-V backend (related PR: #3125).

**Comment by s-perron** [comment]
The maintainers do not have any plans to fix this. @SteveUrquhart  I know you are interested in debug related issues. Let me know if this is something you might want to eventually fix.

**Comment by s-perron** [comment]
The problem can be see at https://godbolt.org/z/vvzacPGba. There is no DebugGlobalVariable instruction for `enum_value`.

**Comment by SteveUrquhart** [comment]
@s-perron, I appreciate you pointing these three bugs out to me.  I don't see a real impact on the user's debugging experience from leaving these unfixed.  It sounds like the 3 of them should be closed.
