### ISSUE TITLE
std::iterator in DxilContainer.h

### ISSUE THREAD

**Issue by MapleDropBear** [microsoft/DirectXShaderCompiler#3143]
In VS 16.7.3 DxilContainer.h has the error 

`error C4996: 'std::iterator<std::input_iterator_tag,const hlsl::DxilContainerHeader *,ptrdiff_t,const hlsl::DxilContainerHeader **,const hlsl::DxilContainerHeader *&>': warning STL4015: The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17. (The <iterator> header is NOT deprecated.) The C++ Standard has never required user-defined iterators to derive from std::iterator. To fix this warning, stop deriving from std::iterator and start providing publicly accessible typedefs named iterator_category, value_type, difference_type, pointer, and reference. Note that value_type is required to be non-const, even for constant iterators. You can define _SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.`

Any chance there is a planned update?

**Comment by pow2clk** [comment]
We build with VS 2019 regularly and I've never seen this error. It looks like it's a warning that is being reported as an error?

That said, while it would be nice to fix this use of deprecated behavior, it's not currently a priority. If you'd like to submit a PR, we'll happily accept it.
