### ISSUE TITLE
Invalid Pixel Shader generated

### ISSUE THREAD

**Issue by kingofthebongo2008** [microsoft/DirectXShaderCompiler#3146]
Hello, 

I get this message on create pipeline,

D3D12 ERROR: ID3D12Device::CreatePixelShader: Encoded Pixel Shader size doesn't match specified size. [ STATE_CREATION ERROR #93: CREATEPIXELSHADER_INVALIDSHADERBYTECODE]

float4 main()
{
    return float4(1,0,0,1);
}

when i change the shader to:

float4 main() : SV_TARGET0
{
    return float4(1,0,0,1);
}

everything is fine

Here is the generated file

[1CF600447AEE94BB.pc.dxo.zip](https://github.com/microsoft/DirectXShaderCompiler/files/5246004/1CF600447AEE94BB.pc.dxo.zip)

**Comment by pow2clk** [comment]
Without the semantic, this shader shouldn't compile: 
```hlsl
float4 main()
{
return float4(1,0,0,1);
}
```
Are you sure there isn't a compile failure occurring somewhere that is being ignored resulting in trying to create the pipeline with an empty pixel shader?

**Comment by kingofthebongo2008** [comment]
Yes, I am.
However later i have discovered that i have not enabled the experimental options.
I think that it is just a new syntax, that works only with experimental options on

**Comment by pow2clk** [comment]
I'm glad that you have gotten things working, but experimental options wouldn't alter how this shader is parsed. I don't know how the shader I referenced could be compiled successfully under any circumstances except maybe if you were compiling it as a library, but that wouldn't produce any executable output, just metadata.

Anyway, can this issue be considered resolved?

If not, perhaps you could provide the compiler arguments that allowed you to compile the shader without the semantic successfully.
