### ISSUE TITLE
hctbuild failed when Visual Studio 2019 installed in the different place

### ISSUE THREAD

**Issue by Goshido** [microsoft/DirectXShaderCompiler#3151]
Recently I discovered than this [deploy instruction](https://github.com/microsoft/DirectXShaderCompiler/wiki/SPIR%E2%80%90V-CodeGen) doesn't work any more.

My target is:
- _Visual Studio 2019_ builder `v16.7.3`
- `x64` platform
- official release
- no `dxilconv`
- _SPIR-V_ support
- commit bf5d5854925a4d994d48e5ca8d5ac6bd6e636213

I'm working with _DXC_ about 6 month and did not have any problems with building the product until today.

I quickly discovered that bf5d5854925a4d994d48e5ca8d5ac6bd6e636213 commit slightly changed `.\utils\hct\hctbuild.cmd` script to force the user to install _Visual Studio 2019_ to the default location only (`C:\Program Files (x86)\Microsoft Visual Studio\2019`).

My instance of _Visual Studio 2019_ is installed here `D:\Programs\Microsoft Visual Studio\2019`.

Point is that before bf5d5854925a4d994d48e5ca8d5ac6bd6e636213 commit the _DXC_ build system worked fine for my environment.

Would you kindly fix the issue?

---
### Full command which I triggered

```txt
git submodule update --init

.\utils\hct\hctstart.cmd D:\Development\DirectXShaderCompiler D:\Development\DirectXShaderCompiler\build.x64

.\utils\hct\hctbuild.cmd -official -rel -x64 -vs2019 -no-dxilconv -spirv
```

---
### Full console output
![image](https://user-images.githubusercontent.com/6526711/93661152-3cac0e00-fa5e-11ea-8c7e-107a6c679b1a.png)

**Comment by hekota** [comment]
Hello Goshido, thanks for reporting! I'll take a look.
