### ISSUE TITLE
dxc fails to run with error code 0x80004002 on linux

### ISSUE THREAD

**Issue by udnaan** [microsoft/DirectXShaderCompiler#3152]
## What

dxc fails with the following error

`dxc failed : error code 0x80004002.`

## Where
Debian 10.5 X86_64

## Why

The debugging leads to line 111 in `dxcapi.use.h`:
`HRESULT hr = m_createFn(clsid, riid, (LPVOID*)pResult);`

Which fails and throws an unknown exception.

## Workaround
Investigation lead to it being caused due to LD_LIBRARY_PATH containing `$VULKAN_SDK/lib` directory. Still not sure why that would be or should be, still, taking out the `$VULKAN_SDK/lib` path fixes it. 

Leaving it here in case someone else on linux runs into it.

**Comment by ehsannas** [comment]
Thanks for reporting @udnaan

**Comment by MarijnS95** [comment]
This might have been a GCC-compiled `libdxcompiler.so` included in the Vulkan SDK? Either way that's solved now and IIDs are compared properly regardless of the compiler since #3062. I think/hope this is fixed and can be closed now from the DXC side :slightly_smiling_face:.

**Comment by pow2clk** [comment]
Closing with the belief this is fixed. Please reopen or refile if it is not
