### ISSUE TITLE
[spirv] -fvk-invert-y not available for Mesh Shader

### ISSUE THREAD

**Issue by turanszkij** [microsoft/DirectXShaderCompiler#3154]
Hi,

Are mesh shaders planned to support `-fvk-invert-y` compiler switch? It would be useful in keeping the shaders identical between Vulkan and DX12. Currently it is only supported for VS, DS and GS.

Best regards,
Janos

**Comment by ehsannas** [comment]
Yes, I don't see why it should be limited to VS/DS/GS. Thanks for reporting @turanszkij
