### ISSUE TITLE
[SPIR-V] noinline attribute does not prevent function from being inlined during SPIR-V generation

### ISSUE THREAD

**Issue by LLJJDD** [microsoft/DirectXShaderCompiler#3158]
I notice there is a `[noinline]` attribute in HLSL to hint that the function should not be inlined, but DXC will always inline all functions in SPIR-V.
Do we have a way to prevent specified function from being inlined in the final SPIR-V?

**Comment by ehsannas** [comment]
Thanks for reporting @lljjdd

**Comment by LLJJDD** [comment]
Issue fixed.
