### ISSUE TITLE
C99 support

### ISSUE THREAD

**Issue by rdunnington** [microsoft/DirectXShaderCompiler#3162]
Hi,

The old D3D compiler was a pure C-style interface, so interop between C and C++ wasn't an issue. The D3D11 and D3D12 APIs are C++, but they support the COBJMACRO interface, which allows for compatibility with C as well. 

The new DXC interface is C++ but does not have any C support. It would be great to get the same level of parity for C as the rest of the D3D interfaces, using a similar COBJMACRO approach. The only option for using DXC in pure C projects is to wrap behind a C-only interface.

**Comment by TonChat** [comment]
+1 That would be great to have a C style interface, similar to what provide COBJMACRO.

**Comment by TonChat** [comment]
![image](https://github.com/microsoft/DirectXShaderCompiler/assets/297246/17ef4fc7-884f-4e53-8582-517b3876d454)
It seems to be possible without much change of the c++ code.

**Comment by llvm-beanz** [comment]
I have good news and bad news for you.

Starting with the bad: We're not going to build a C interface for DXC to replace the COM interface. That's just a lot of work to get right and we have other priorities.

The good news: We will introduce a cross-platform C interface for compiling HLSL with Clang, when we get there. I've filed this issue on the LLVM upstream work to track this request:
https://github.com/llvm/llvm-project/issues/63631

**Comment by rdunnington** [comment]
Thanks for following up on this!

**Comment by ratchetfreak** [comment]
You wouldn't have needed to *replace* the COM interface, COM is C compatible. 

So the only thing that would have needed to be done is create an idl file that defines the IInterfaces and generate the headers from those files and you would have C interop for free. And apparently that was the [plan back in 2020](https://github.com/microsoft/DirectXShaderCompiler/issues/3107#issuecomment-703948044). What happened to that?
