### ISSUE TITLE
[SPIR-V] Support arrays of RW/append/consume structured buffers

### ISSUE THREAD

**Issue by mattruschnv** [microsoft/DirectXShaderCompiler#3164]
Currently I'm trying to port a shader which uses the following to Vulkan:
RWStructuredBuffer<TLASInstance>                  VisTLASInstances[]        : register(u0, space3); 

It would be awesome if this were supported for spirv as well as dxil.

**Comment by jaebaek** [comment]
@mattruschnv thank you for reporting this issue. First of all, we want to understand exactly what you want. Could you please share a full shader that I can compile?

In addition, if this is not supported for DXIL, then I recommend you not specifying it as "SPIRV" issue.
If it is in that case, we need a dicussion with DXIL developers to understand what we are missing (I guess probably AST parser does not support it) and it is possible (or reasonable) to support it.

**Comment by mattruschnv** [comment]
To clarify, it IS supported for DXIL.

**Comment by d11mshepcar** [comment]
We'd very much like to see support for this too to enable a bindless model for RWStructuredBuffers in vulkan as well as dx.

**Comment by s-perron** [comment]
With will be handled under #5440. I want all of the issues in a central place with a fresh conversation.
