### ISSUE TITLE
[SPIR-V] Line directives with filenames fail to compile for spirv-target with debug info

### ISSUE THREAD

**Issue by jkoenen** [microsoft/DirectXShaderCompiler#3165]
The following code fails to compile when targeting spirv + enabled debug information:

```HLSL
#line 1 "non_existing_file.txt"

struct PSInput
{
	float4 color : COLOR;
};

float4 PSMain(PSInput input) : SV_TARGET
{
	return input.color;
}
```

Command line:
```
dxc -E PSMain -T ps_6_0 -Zi -spirv test.hlsl
```

The output is:
```
dxc failed : error code 0x80004005.
```

We currently use paths to non-existing files in the line directives in our content pipeline. I assume that the content of the file shouldn't be read by the compiler.

It does compile fine without the spirv target.

**Comment by jaebaek** [comment]
Hi @jkoenen Thank you for reporting this issue. I will take a look.
