### ISSUE TITLE
[SPIR-V] Crash when compiling faulty shader to SPIRV

### ISSUE THREAD

**Issue by cpt-max** [microsoft/DirectXShaderCompiler#3166]
Compiling this shader to SPIRV causes a crash, instead of outputting an error:
```
sampler Sampler;

float4 PS(float2 texCoord : TEXCOORD0) : SV_TARGET0
{
    return tex2D(Sampler, texCoord) * 1;
}
``` 
Removing the *1 at the end of the return statement will prevent the crash, and generate the appropriate error message (tex2D not supported).

Command line:
```
dxc.exe -spirv -T ps_4_0 -E PS shader.hlsl -Fo spirv.txt
```

**Comment by jaebaek** [comment]
@cpt-max, thank you for reporting this issue. I will take a look.

**Comment by jaebaek** [comment]
Just for note:
It happens because we do not support `tex2D`. See `tools/clang/lib/SPIRV/SpirvEmitter.cpp:7143`.

**Comment by jaebaek** [comment]
Do you think this code works for DXIL? I tested it in the [shader playground](http://shader-playground.timjones.io/4fdbc76154ac220e07f4ad966c53c3b3) but I cannot get the result ..
It says "error: Unsupported intrinsic".

**Comment by cpt-max** [comment]
Thanks for looking into this.
No, this code won't work for DXIL because of tex2D.
Just to be clear, I don't expect the shader to compile. The problem is solely that DXC crashes, instead of generating an error message.
