### ISSUE TITLE
[SPIR-V] Support ShaderRecordBufferKHR blocks

### ISSUE THREAD

**Issue by seppala2** [microsoft/DirectXShaderCompiler#3177]
Hello,

I see that ShaderRecordBufferNV is supported with [[vk::shader_record_nv]], but there is no option for the KHR version. A simple search and replace directly in SPIR-V seems to work although I haven't tested actually using the pipeline. However, a cleaner solution would be nice.

Also, somewhat related: support for buffer references, even if only for SPIR-V, would be useful specially with shader record buffer blocks. With that one could emulate something similar to constant buffers in local root signatures in DX12. For example, unless I've misunderstood, you could use the same constant data for materials that is used in a g-buffer pass quite easily. There seems to be an issue for this already though: #2995

**Comment by sudonatalie** [comment]
It looks like this issue was fixed with #3426.
