### ISSUE TITLE
[SPIR-V] Signed integer min/max atomics generate invalid SPIR-V

### ISSUE THREAD

**Issue by bqqbarbhg** [microsoft/DirectXShaderCompiler#3196]
Using `InterlockedMin()` or `InterlockedMax()` with signed integers fails with the following error:

```
generated SPIR-V is invalid: AtomicSMin: expected Value to be of type Result Type
%589 = OpAtomicSMin %uint %588 %uint_1 %uint_0 %int_1
```

In the actual code the argument to `InterlockedMin()` is loaded from a `groupshared` buffer but it seems to happen with only local constant value as well. Here's a simplified example code causing the issue:

```hlsl
[[vk::binding(2, 1)]]  RWByteAddressBuffer myBuffer : register(u7);

struct MyInput { };
struct MyOutput { };

[numthreads(8,8,1)]
MyOutput main(MyInput myInput) {
    int val = 1; 
    myBuffer.InterlockedMin(0u, val);
}
```

Using a signed offset to `InterlockedMin()` does not resolve the issue nor does using the overload that returns the old value.

**Comment by ehsannas** [comment]
Thanks for reporting @bqqbarbhg
