### ISSUE TITLE
Target Android/iOS?

### ISSUE THREAD

**Issue by rex-remind101** [Microsoft/DirectXShaderCompiler#32]
Seems like this is focused on targeting Windows platforms, but since it uses LLVM to generate the IR  so is it possible to configure the compiler to target other platforms?

P.S. New to shaders but lots of mobile app development experience. Please forgive me if I'm missing something conceptually.

**Comment by ChasBoyd** [comment]
From the DirectX Blog:
"Because the source is available, developers can check to see how the compiler works at the smallest level of detail. You can download it, modify it, and make it a part of any system you are building. You can port it to other platforms. You can also contribute your ideas and code to the project directly, or collaborate with other partners (including hardware vendors) on new contributions."

**Comment by rex-remind101** [comment]
👍

**Comment by salamanderrake** [comment]
Besides I don't think DirectX runs on android, its an opengl/Vulkan platform.

**Comment by rex-remind101** [comment]
@salamanderrake This is a shader compiler though right? Which means it compiles shader programs to instructions for a GPU? LLVM can target Android and iOS CPUs so I figured why not GPUs as well?

**Comment by marcelolr** [comment]
The compiler targets an intermediate representation we refer to as DXIL. App/game authors can distribute this DXIL with their programs and, via the Direct3D runtime, request that whatever GPU the customer has run the shader.

The GPU provides a driver that will do the back-end of the compilation from DXIL to an ISA appropriate for the specific hardware available (along with some additional information the app can provide to create a pipeline state object, but that's getting more into the details of how Direct3D 12 works).

**Comment by TsinStudio** [comment]
We can provide a DXIL-SPIRV/MetalIR bytecode translator to support Android or iOS

**Comment by rex-remind101** [comment]
@marcelolr thanks for the clarity!

@TsinStudio sounds fancy. Are there any cross-compilers already available that you know of to do that kind of translation?
