### ISSUE TITLE
[SPIR-V] Using RWTexture2D or RWBuffer with min precision types crashes the compiler

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#3209]
### Title
Using RWTexture2D or RWBuffer with min precision types crashes the compiler

### Functional impact
SPIR-V backend crashes during compilation and produces errors not present with the DXIL backend when using `min16` typed resources. FXC also compiles successfully.

### Minimal repro steps

1. Compile [repro_shader.txt](https://github.com/microsoft/DirectXShaderCompiler/files/5400216/repro_shader.txt) with `dxc.exe -T cs_6_0 -E CSMain -spirv repro_shader.txt` (seen below) with DXC built from source and a debugger attached:
```
RWTexture2D<min16uint4> texout;

[numthreads(1, 1, 1)]
void CSMain(uint2 id : SV_DispatchThreadID) 
{
	texout[id] = min16uint4(id.xyxy);
}
```

### Expected result
Shader compiles successfully as it does with the DXIL backend.

### Actual result
Crash on assertion in `def_use_manager.cpp`:
```
  for (uint32_t i = 0; i < inst->NumOperands(); ++i) {
    switch (inst->GetOperand(i).type) {
      // For any id type but result id type
      case SPV_OPERAND_TYPE_ID:
      case SPV_OPERAND_TYPE_TYPE_ID:
      case SPV_OPERAND_TYPE_MEMORY_SEMANTICS_ID:
      case SPV_OPERAND_TYPE_SCOPE_ID: {
        uint32_t use_id = inst->GetSingleWordOperand(i);
        Instruction* def = GetDef(use_id);
        assert(def && "Definition is not registered.");          //<--- ASSERTION FAILS
        id_to_users_.insert(UserEntry(def, inst));
        used_ids->push_back(use_id);
      } break;
      default:
        break;
    }
  }
```
Also see [crash_stack.txt](https://github.com/microsoft/DirectXShaderCompiler/files/5399947/crash_stack.txt).

### Further technical details
Note, if explicit 16bit types is used (as opposed to the default behaviour) i.e. when the compilation arguments are changed to `dxc.exe -E CSMain -T cs_6_2 -enable-16bit-types -fspv-target-env=vulkan1.1 -spirv repro_shader.txt` then the following message asking to report an issue is produced:

```
repro_shader.txt:1:13: warning: min16uint is promoted to uint16_t [-Wconversion]
RWTexture2D<min16uint4> texout;
            ^
repro_shader.txt:6:15: warning: min16uint is promoted to uint16_t [-Wconversion]
        texout[id] = min16uint4(id.xyxy);
                     ^
repro_shader.txt:1:25: error: cannot translate resource type parameter 'min16uint4' to proper image format
RWTexture2D<min16uint4> texout;
                        ^
repro_shader.txt:6:2: error: cannot translate resource type parameter 'vector<min16uint, 4>' to proper image format
        texout[id] = min16uint4(id.xyxy);
        ^
repro_shader.txt:6:2: error: cannot translate resource type parameter 'vector<min16uint, 4>' to proper image format
fatal error: generated SPIR-V is invalid: Expected Sampled Type to be a 32-bit int or float scalar type for Vulkan environment
  %type_2d_image = OpTypeImage %ushort 2D 2 0 0 2 Unknown

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

Using `min16float4` instead of `min16uint4` with the above arguments does not fix this error message (only the appropriate types change).

Also, if the compute shader's entry point is left blank (no write to the UAV) only the following message is visible (arguments same as in `Minimal repro steps` `dxc.exe -T cs_6_0 -E CSMain -spirv repro_shader.txt`):
```
repro_shader.txt:1:25: error: cannot translate resource type parameter 'min16uint4' to proper image format
RWTexture2D<min16uint4> texout;
                        ^
```

Is there a valid reason why this error is only present with the SPIR-V and not the DXIL backend?

**Comment by ehsannas** [comment]
Thanks for reporting @dredhog

**Comment by jaebaek** [comment]
#3758 fixed this issue. Please let me know if it does not work as expected.
