### ISSUE TITLE
Feature request: non-wchar/wstring interface

### ISSUE THREAD

**Issue by jeremyong** [microsoft/DirectXShaderCompiler#3210]
Certainly for fixed arguments and options (`-Zi`, `-Qstrip=reflection`, etc), wide strings don't make a lot of sense. In particular, I imagine the reason wide strings are used are for filenames for things like shader debug names, pdb paths, etc. However, even with the Win32 API, the `*A` variants exist for cases where "wide-unicode" isn't needed.

Urgent? No, not at all, but it would be appreciated for the situations where DXC is being integrated in codebases that traditionally were not built with wchars.

Cheers,
Jeremy

**Comment by MarkIngramUK** [comment]
I agree, it'd be nice to see all the parameters be of type `const char*` (or some alias, to enable `const char8_t*` at some point in the future) so we can use UTF-8 strings without conversion at the API surface (our internal strings are all UTF-8).

**Comment by llvm-beanz** [comment]
I think we would accept changes in this area, but we're not going to do this work in the DXC codebase. We are planning a C API in the Clang implementation which will support UTF-8 interfaces (see [LLVM-project #63631](https://github.com/llvm/llvm-project/issues/63631)).

Being honest that we're not going to tackle this I'm going to close the issue.
