### ISSUE TITLE
[SPIR-V] Reading or writing a struct's member from a derived struct's method causes SPIR-V codegen errors

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#3213]
### Title
 Reading or writing a struct's member from a derived struct's method causes SPIR-V codegen errors which ask to report a bug

### Functional impact
Compilation fails with the SPIR-V backend. Does not fail with the DXIL backend or FXC.

### Minimal repro steps

1.1. Compile [read_issue.txt](https://github.com/microsoft/DirectXShaderCompiler/files/5414931/read_issue.txt)  (seen below) with `dxc.exe -T ps_6_0 -E PSMain -spirv read_issue.txt`:
```
struct A {
  float4 base;
};

struct B : A {
  float4 derived;
  float4 GetBase() {return base;}
  float4 GetDerived() {return derived;}
};

#define REPRODUCE_ISSUE 1

float4 PSMain() : SV_Target {
  B b;
  b.base = float4(1, 1, 0, 1);
  b.derived = float4(1, 0, 1, 1);
    
#if REPRODUCE_ISSUE
  return b.GetBase();
#else
  return b.GetDerived();
#endif
}
```
1.2. Observe compiler output:
```
fatal error: generated SPIR-V is invalid: Expected number of constituents to be at least 2
  %12 = OpCompositeConstruct %v4float %7

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```
2.1.  Compile [write_issue.txt](https://github.com/microsoft/DirectXShaderCompiler/files/5414929/write_issue.txt)  (seen below) with `dxc.exe -T ps_6_0 -E PSMain -spirv write_issue.txt`:
```
struct A {
  float4 base;
};

struct B : A {
  float4 derived;
  void SetBase(float4 v) { base = v;}
  void SetDerived(float4 v) { derived = v; }
};

#define REPRODUCE_ISSUE 1

float4 PSMain() : SV_Target {
  B b;
    
#if REPRODUCE_ISSUE
  b.SetBase(float4(1, 0, 1, 1));    
  return b.base;
#else
  b.SetDerived(float4(1, 0, 1, 1));    
  return b.derived;
#endif
}

```
2.2. Observe compiler output:
```
fatal error: generated SPIR-V is invalid: Type Id 4 is not a scalar numeric type
note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

### Expected result
Compilation succeeds when a base struct's member is read or written from a derived struct's method

### Actual result
The generated SPIR-V generates validation errors. Compilation fails and messages asking to report a bug are printed.

### Further technical details
The [read](http://shader-playground.timjones.io/0f04d9b0ca49abf96ffbd0989fdd9e89) and [write](http://shader-playground.timjones.io/391b05af7ecbb1429f826e1110c1f4f2) shaders on shader-playground for convenience.

**Comment by ehsannas** [comment]
I'll look into this soon.
