### ISSUE TITLE
Using Texture2D<bool*>.Load results in validation errors with both DXIL backends (not with FXC)

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#3218]
### Title
Using Texture2D<bool*>.Load results in validation errors with both DXIL and SPIR-V backends (not with FXC)

### Functional impact
Cannot use bool typed textures. Breaks compatibility with FXC.

### Minimal repro steps

1. Compile the following shader with `dxc.exe -T ps_6_0 -E PSMain issue_shader.txt`:
```
Texture2D<bool> myTex;
float4 PSMain() : SV_Target0 {
    bool temp = myTex.Load(int3(0,0,0)).r;
    
    if(temp)
        return float4(1, 1, 1, 1);
    else
    	return float4(0, 0, 0, 0);
}

```
2. Observe compiler output for the DXIL backend:
```
error: validation errors
Invalid resource return type''

Validation failed.
```
3. Compile the same shader for the SPIR-V by adding the `-spirv` flag `dxc.exe -T ps_6_0 -E PSMain -spirv issue_shader.txt` and observe the compiler output:
```
fatal error: generated SPIR-V is invalid: Expected Sampled Type to be a 32-bit int or float scalar type for Vulkan environment
  %type_2d_image = OpTypeImage %bool 2D 2 0 0 1 Unknown

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

### Expected result
Validation/compilation succeeds.

### Actual result
Validation/compilation fails when targeting either DXIL or SPIR-V

### Further technical details
Note: the same happens when using `bool2`, `bool3` or `bool4` as the Texture2D template argument. For convenience, here's the link to the original [example](http://shader-playground.timjones.io/66977987f3461fa47b199d6f796fb6cf) on shader-playground.

**Comment by ehsannas** [comment]
To track progress of DXIL and SPIR-V separately, I have filed https://github.com/microsoft/DirectXShaderCompiler/issues/3236 for the SPIR-V side.

This issue can track the fix for DXIL.

**Comment by damyanp** [comment]
Changing the element type type `int` could be a workaround for this, so we're not planning on addressing this in DXC.  We'll be working on better suport for bools in clang.
