### ISSUE TITLE
[SPIR-V] FMin/FMax/FClamp NaN handling contradicts HLSL specification

### ISSUE THREAD

**Issue by Triang3l** [microsoft/DirectXShaderCompiler#3221]
Currently the SPIR-V emitter generates FMin, FMax and FClamp instructions for min, max, clamp and saturate. The [specification of the GLSL.std.450 instruction set](https://www.khronos.org/registry/spir-v/specs/1.0/GLSL.std.450.html) states that "which operand is the result is undefined if one of the operands is a NaN". This is in contrast with the [DXIL](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/DXIL.rst#fmax), [DXBC](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/max--sm4---asm-) and [HLSL](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-max) specification of those instructions, which, if one of the operands is NaN, give the other operand as the result (and clamp/saturate gives the lower bound, as if max was performed first).

While HLSL is normally optimized as if there were no special floating-point values at all, with the `precise` qualifier or the "force IEEE strictness" compiler option, the compiler must honor the defined behavior for specials. Clamping operations may also be used with the implication of sanitizing the input, making sure the resulting value is strictly in the bounds and not NaN.

The correct implementation, which maps 1:1 to the DXIL/DXBC behavior, is NMax/NMin/NClamp from the GLSL.std.450 instruction set. Are those safe to use in DXC (such as, can we assume that NClamp to 0 and 1, on existing drivers or in the near future, will surely map to the hardware saturation modifier in all the same cases as when FClamp to 0 and 1 is used; and whether they're compatible with wave reduction)?

**Comment by sudonatalie** [comment]
From what I see in the HLSL spec, [`min`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-min) and [`max`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-max) would be correctly represented by the GLSL.std.450 instructions [`NMin`](https://www.khronos.org/registry/SPIR-V/specs/1.0/GLSL.std.450.html#:~:text=%3Cid%3E%0Aoffset-,NMin,-Result%20is%20y) and [`NMax`](https://www.khronos.org/registry/SPIR-V/specs/1.0/GLSL.std.450.html#:~:text=%3Cid%3E%0Ay-,NMax,-Result%20is%20y), respectively, so I'll submit a fix for those. However, the [`clamp`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-clamp) (and by extension, [`saturate`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-saturate)) documentation states that "for values of NaN, the results are undefined." As far as I can see, this correctly matches the semantics of [`FClamp`](https://www.khronos.org/registry/SPIR-V/specs/1.0/GLSL.std.450.html#:~:text=%3Cid%3E%0Ay-,FClamp,-Result%20is%20min), so it will remain as-is.

**Comment by sudonatalie** [comment]
Thanks for reporting this @Triang3l !

**Comment by Triang3l** [comment]
Ooooh, didn't notice that property of `clamp`, thanks for telling me about it so I'll keep that in mind and recheck all the usages of it in my existing code @sudonatalie! :D And thank you for the fix!!!

**Comment by Triang3l** [comment]
> However, the [`clamp`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-clamp) (and by extension, [`saturate`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-saturate)) documentation states that "for values of NaN, the results are undefined."

@sudonatalie While this is not specified in the HLSL documentation directly, however, the [`_sat` modifier in Shader Model 4 assembly/bytecode is defined](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/saturate) to return 0.0 for NaN according to the rules of the `max` DXBC instruction. Would it be reasonable to extend this logic to HLSL, or would that be just an excess optimization and maintenance constraint considering that the HLSL specification doesn't seem to directly link the `saturate` intrinsic to the `_sat` modifier (but at the same time, it doesn't connect `saturate` to `clamp` either — but neither does it to `max` and `min`, nor does it provide any info about NaN handling)?
