### ISSUE TITLE
[SPIR-V] Using Texture2D<bool*>.Load results in validation errors

### ISSUE THREAD

**Issue by ehsannas** [microsoft/DirectXShaderCompiler#3236]
### Title
Using Texture2D<bool*>.Load results in validation errors with both DXIL and SPIR-V backends (not with FXC)

### Functional impact
Cannot use bool typed textures. Breaks compatibility with FXC.

### Minimal repro steps

1. Compile the following shader with `dxc.exe -T ps_6_0 -E PSMain issue_shader.txt`:
```
Texture2D<bool> myTex;
float4 PSMain() : SV_Target0 {
    bool temp = myTex.Load(int3(0,0,0)).r;
    
    if(temp)
        return float4(1, 1, 1, 1);
    else
    	return float4(0, 0, 0, 0);
}

```
2. Observe compiler output for the DXIL backend:
```
error: validation errors
Invalid resource return type''

Validation failed.
```
3. Compile the same shader for the SPIR-V by adding the `-spirv` flag `dxc.exe -T ps_6_0 -E PSMain -spirv issue_shader.txt` and observe the compiler output:
```
fatal error: generated SPIR-V is invalid: Expected Sampled Type to be a 32-bit int or float scalar type for Vulkan environment
  %type_2d_image = OpTypeImage %bool 2D 2 0 0 1 Unknown

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

### Expected result
Validation/compilation succeeds.

### Actual result
Validation/compilation fails when targeting either DXIL or SPIR-V

### Further technical details
Note: the same happens when using `bool2`, `bool3` or `bool4` as the Texture2D template argument. For convenience, here's the link to the original [example](http://shader-playground.timjones.io/66977987f3461fa47b199d6f796fb6cf) on shader-playground.

**Comment by ehsannas** [comment]
This issue is also reported for the DXIL backend (tracked by https://github.com/microsoft/DirectXShaderCompiler/issues/3218)

**Comment by sudonatalie** [comment]
Looking at FXC's output in shader playground, the bool element type is replaced by uint in DXBC:

```
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// myTex                             texture    uint          2d             t0      1 
```

This is probably also what we want to do in the generated SPIR-V, since the sampled type of a SPIR-V [`OpTypeImage`](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpTypeImage) must be a scalar numerical type (cannot be bool). We could do this in the SPIR-V backend, but it would take some special casing to transform both `OpTypeImage` and `OpImageFetch`. If we want to address #3218 in the same way then it seems like fixing on the frontend would be cleaner, if possible.

**Comment by sudonatalie** [comment]
> If we want to address #3218 in the same way then it seems like fixing on the frontend would be cleaner, if possible.

We discussed this and determined it was likely to be too difficult to implement this way and would be more straightforward to handle separately in each backend (PR #3925 is for the SPIR-V backend).
