### ISSUE TITLE
Generated SPIR-V is invalid

### ISSUE THREAD

**Issue by Pursche** [microsoft/DirectXShaderCompiler#3247]
Hello, I am trying to compile this compute shader implementation of bitonic sorting into SPIR-V and it is giving me this error: 

```
[Error] : fatal error : generated SPIR-V is invalid: OpReturnValue Value <id> '297[%297]'s type does not match OpFunction's return type.
1>  OpReturnValue %297
```

Here is the shader I am trying to compile: https://pastebin.com/Zr4hamJa
I am using the DX Compiler release for October 2020, I invoke the shader compiler in ShaderModel 6.5 with these flags (using the library if that matters):

`
-spirv
-fvk-use-gl-layout
-Zpr
-WX
-enable-16bit-types
-Zi
-0d
`

**Comment by ehsannas** [comment]
Thanks for reporting @pursche.

**Comment by ehsannas** [comment]
@jaebaek  this seems to be related to debug info codegen.
