### ISSUE TITLE
[SPIR-V] Workgroup memory not allowed in tessellation-control shader

### ISSUE THREAD

**Issue by LukasBanana** [microsoft/DirectXShaderCompiler#3248]
According to the SPIR-V specification, workgroup memory (`shared` in GLSL) is only allowed in the compute shader stage (as well as the new mesh and task shader stages). However, DXC generates this to communicate patch constant data in a tessellation control shader as intermediate storage. The SPIRV-Tools validation does not catch this error and causes a triangle soup on NVIDIA hardware and a crash in the Vulkan implementation on AMD hardware.

The solution presented in [PR3059](https://github.com/microsoft/DirectXShaderCompiler/pull/3059) doesn't work in UE4 with most of our tessellation shaders. Our old shader compiler pipeline used the output attribute slots that were already allocated. I submitted a workaround in our P4V repository that creates another output attribute slot as intermediate storage. The problem with that is it allocates a lot of output slots when large structures are involved and easily exceeds the Vulkan limits with certain configurations in our material system.

This is the line where I hook in another output variable with a custom `createStageOutputVar` function:
https://github.com/microsoft/DirectXShaderCompiler/blob/6008113f6023f3ffd955855a6a9aae50480ea1a9/tools/clang/lib/SPIRV/DeclResultIdMapper.cpp#L3668

**Comment by ehsannas** [comment]
Thanks for reporting @LukasBanana

**Comment by ehsannas** [comment]
@jaebaek this is related to PR #3059 . I can't remember exactly why the switch to Workgroup happened? Is it because of sharing memory among different invocations? IIUC the patch constant function is called only once for each patch, so theoretically there shouldn't be a need to share data among threads.

**Comment by LukasBanana** [comment]
PR #3059 introduced shared memory because DXC previously declared a local function array and assumed it is shared across invocations. Maybe a typo when the code was initially submitted. But we definitely need to share data across invocations for certain tessellation shaders such as PN-triangles. It would be optimal to utilize the output attributes that are already allocated. The single invocation for the patch-constant data would then read the output attributes that were written by all invocations, hence the `barrier()`.

**Comment by ehsannas** [comment]
Ah makes sense. Thanks for the clarification.

**Comment by jaebaek** [comment]
@LukasBanana Thank you for reporting this issue. Yes, I considered reverting the change (#3059 ) because the `Workgroup` storage class is not allowed in the tessellation shader.

Just I do not clearly understand what would be the correct implementation because I am not versed on the tessellation shaders.
I just sent a PR to revert the commit: #3252.
Could you please test the PR for your tessellation shaders?
Let me know some generated SPIR-V code is wrong.

**Comment by LukasBanana** [comment]
@jaebaek your PR will definitely not work with our tessellation shaders, because it uses a function local array again just like before, i.e. `hullMainOutputPatch` is allocated with `spvBuilder.addFnVar`. Your idea to use Workgroup memory was not a bad one though. I had the same idea for our older DXC fork which doesn't include your change. Then I figured out that Workgroup memory is not supported in that shader stage. According to some feedback from the Khronos Group, this restriction in SPIR-V was adopted from GLSL.

My workaround was to declare the intermediate variable, i.e. `hullMainOutputPatch`, as another output attribute with the highest output slot (i.e. after all other output attributes). I create this variable with a custom implementation of the `createStageOutputVar` function and ignore a few validations such as structure flattening which is only required to determine the number of output slots required. Since that output attribute is the last one, we don't need that information.

You can take a look at [`createSpirvIntermediateOutputStageVar`](https://github.com/EpicGames/UnrealEngine/blob/4.26/Engine/Source/ThirdParty/ShaderConductor/ShaderConductor/External/DirectXShaderCompiler/tools/clang/lib/SPIRV/DeclResultIdMapper.cpp#L2653) in the UE 4.26 branch.

**Comment by jaebaek** [comment]
@LukasBanana Could you please check this branch: https://github.com/jaebaek/DirectXShaderCompiler/tree/hull_shader?
I do not have good shaders to test my code.
Could you please provide me with a shader and briefly desribe what the expected result is? it would be very helpful for me to understand the requirement clearly.
I tried to test [SaschaWillems tessllation shaders](https://github.com/SaschaWillems/Vulkan/tree/master/data/shaders/hlsl/tessellation), but I am not sure it is a proper example for this issue.

**Comment by LukasBanana** [comment]
@jaebaek It seems that Sascha's tessellation shaders compute the patch constant data redundantly in every tess.-control invocation. In UE4, we do that in only one invocation using the `[patchconstantfunc(string)]` attribute. It is hard to tell which approach has a better performance, but the patch constant function's sole purpose is to compute everything that is constant throughout an entire patch.

Here is a small example shader:
```hlsl

struct HSControlPoint {
	float4 ControlPoint : CONTROLPOINT;
};

struct HSPatchConstantData {
	float Edges[3] : SV_TessFactor;
	float Inner[1] : SV_InsideTessFactor;
	float4 Data : CONSTANTDATA;
};

HSPatchConstantData HSPatchConstantFunc(const OutputPatch<HSControlPoint, 3> I) {
	HSPatchConstantData O;
	O.Data = I[0].ControlPoint + I[1].ControlPoint + I[2].ControlPoint; // <-- This is the crucial part
	O.Edges[0] = 3.0;
	O.Edges[1] = 3.0;
	O.Edges[2] = 3.0;
	O.Inner[0] = 3.0;
	return O;
}

[domain("tri")]
[partitioning("fractional_odd")]
[outputtopology("triangle_cw")]
[outputcontrolpoints(3)]
[patchconstantfunc("HSPatchConstantFunc")]
[maxtessfactor(15)]
HSControlPoint HSMain(InputPatch<HSControlPoint, 3> I, uint ControlPointID : SV_OutputControlPointID) {
	HSControlPoint O;
	O.ControlPoint = I[ControlPointID].ControlPoint;
	return O;
}
```
And this is what the output with our internal fixes looks like (using ShaderConductor `-E HSMain -S hs -T glsl`):
```glsl
#version 450
layout(vertices = 3) out;

struct HSControlPoint
{
    vec4 ControlPoint;
};

layout(location = 0) in vec4 in_var_CONTROLPOINT[];
layout(location = 1) out vec4 out_var_CONTROLPOINT[3];
layout(location = 2) out HSControlPoint temp_var_hullMainRetVal[3];
layout(location = 0) patch out vec4 out_var_CONSTANTDATA;

void main()
{
    vec4 _42_unrolled[3];
    for (int i = 0; i < int(3); i++)
    {
        _42_unrolled[i] = in_var_CONTROLPOINT[i];
    }
    HSControlPoint param_var_I[3] = HSControlPoint[](HSControlPoint(_42_unrolled[0]), HSControlPoint(_42_unrolled[1]), HSControlPoint(_42_unrolled[2]));
    out_var_CONTROLPOINT[gl_InvocationID] = param_var_I[gl_InvocationID].ControlPoint;
    temp_var_hullMainRetVal[gl_InvocationID] = HSControlPoint(param_var_I[gl_InvocationID].ControlPoint);
    barrier();
    if (gl_InvocationID == 0u)
    {
        gl_TessLevelOuter[0u] = 3.0;
        gl_TessLevelOuter[1u] = 3.0;
        gl_TessLevelOuter[2u] = 3.0;
        gl_TessLevelInner[0u] = 3.0;
        out_var_CONSTANTDATA = (temp_var_hullMainRetVal[0u].ControlPoint + temp_var_hullMainRetVal[1u].ControlPoint) + temp_var_hullMainRetVal[2u].ControlPoint;
    }
}
```
Your branch looks fine as it's almost identical to the fixes I send you.

**Comment by jaebaek** [comment]
@LukasBanana Thanks. Let me send a PR after testing your example and adding an unit test to the branch.
