### ISSUE TITLE
DXC crashes with incorrect sampler register setup

### ISSUE THREAD

**Issue by dozone27** [microsoft/DirectXShaderCompiler#3249]
Hi team, due to a bug in our engine, we ran into a case that would cause dxc.exe to crash.

**Sample code:**

```
SamplerState sampler0 : register ( s0 ) ; 
SamplerState badSampler : register ( s0 ) ; 
Texture2D texture : register ( t0 ) ; 

float4 main () 
{ 
    float4 temp0;
    float4 temp1;

    temp1 = texture.Sample(sampler0, temp0.xyzw.xy);
    return texture.Sample(badSampler, temp1.xyzw.xy);
}
```

The above code crashes with executable using either dxcompiler_x.dll and dxcompiler_xs.dll.

The crash also repros with using both dxc.exe for xbox and scarlett.
          

> dxc.exe test.hlsl -T ps_6_0

The dxc.exe for PC, on the other hand, correctly outputs an error message:
          

> error: resource badSampler at register 0 overlaps with resource sampler0 at register 0, space 0

**Comment by vcsharma** [comment]
Thanks for reporting this issue. This issue no longer repro. This generates an error message.

```
Function: main: error: Semantic must be defined for all parameters of an entry function or patch constant function Use /Zi for source location.
Function: main: error: resource badSampler at register 0 overlaps with resource sampler0 at register 0, space 0 Use /Zi for source location.
```
