### ISSUE TITLE
Crash by iterator checking on visual studio debug configuration

### ISSUE THREAD

**Issue by hamwj1991** [microsoft/DirectXShaderCompiler#3266]
branch: refs/remotes/origin/release-1.5.2010
file: DxilContainerReflection.cpp : 2323
env: visual stduio 2019, debug
problem: iterator was compared with iterator from another container, which triggered a iterator safe checking assert "map/set iterators incompatible"

**Comment by tex3d** [comment]
Fixed by #3160
