### ISSUE TITLE
No default typedef for FLOAT

### ISSUE THREAD

**Issue by magcius** [microsoft/DirectXShaderCompiler#3269]
FXC: http://shader-playground.timjones.io/0f5483563cb5ac0a4c79a4addc8df028
DXC: http://shader-playground.timjones.io/6e3a6cdb16fd9a3e880864f499d48318

This isn't a big issue in practice, except D3DX_DXGIFormatConvert.inl seems to use FLOAT rather than float, leading to it failing to compile properly under DXC.

**Comment by llvm-beanz** [comment]
I think we've gone about as far as we're planning to with making DXC and FXC syntax compatible.
