### ISSUE TITLE
Can't pass derived structs to DispatchMesh (with -Od)

### ISSUE THREAD

**Issue by jeffnn** [microsoft/DirectXShaderCompiler#3274]
Repro:

Compile the following, (I used as_6_5, /Zi -Od -enable-16bit-types /Qembed_debug )

```
struct Base
{
    float floatValue;
};

struct Derived : Base
{
	int intValue;
};

[numthreads(1, 1, 1)]
void main()
{
    Derived p;
    p.floatValue = 1.;
    p.intValue = 2;
    DispatchMesh(1, 1, 1, p);
}
```
Produces this error text:

error: validation errors
source.hlsl:16:5: error: Pointer type bitcast must be have same size.
note: at '%2 = bitcast %struct.Derived* %1 to %struct.Base*' in block '#0' of function 'main'.
Validation failed.

Compilation succeeds if you add a cast to Base like so:
    DispatchMesh(1, 1, 1, (Base)p);

**Comment by pow2clk** [comment]
No longer repros. I think it may have been fixed by #3713
