### ISSUE TITLE
CMake fails to generate build files, missing the AMDGPU LLVM target

### ISSUE THREAD

**Issue by expipiplus1** [microsoft/DirectXShaderCompiler#3275]
I've encountered this with `HEAD` and `v1.5.2010` on Linux

To reproduce:

- Install python3 and CMake
- Clone this repository and its submodules and navigate to it
- mkdir build && cd build
- cmake ../
- Observe this error:

    ```
    -- Constructing LLVMBuild project information
    CMake Error at CMakeLists.txt:464 (message):
      Unexpected failure executing llvm-build: Usage: llvm-build [options]



      llvm-build: error: invalid target to enable: 'AMDGPU' (not in project)


    -- Configuring incomplete, errors occurred!
```

CMake's error and output logs are here, although there's probably not anything enlightening there: https://gist.github.com/554cbeca1cc741d43e1f81f13b845802

Given that this is quite a fundamental problem, I suspect that there's something else going on.

Removing `AMDGPU` from [`LLVM_ALL_TARGETS`](https://github.com/microsoft/DirectXShaderCompiler/blob/11e04d8d2b421d52946374e4f60e615ddaa3df1e/CMakeLists.txt#L231) leads to an identical error for `NVPTX`

Getting `utils/llvm-build/llvmbuild/main.py` to print the list of available target shows that there are none available.

**Comment by expipiplus1** [comment]
And the solution is to pass the contents of `../utils/cmake-predefined-config-params` to cmake as instructed to in the build script.

**Comment by v4vendeta** [comment]
> 

Can you describe it in more detail? I met the same problem too and don't know how to fix that.

**Comment by expipiplus1** [comment]
> Can you describe it in more detail? I met the same problem too and don't know how to fix that.

The build instructions are here: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DxcOnUnix.rst

**Comment by v4vendeta** [comment]
thanks.
