### ISSUE TITLE
Remove voice from build script

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/DirectXShaderCompiler#3277]
Please, please, remove the voice from the build scripts.

**Comment by Jasper-Bekkers** [comment]
While we're on the subject of improving the build system, please also don't add shortcuts to my desktop.

**Comment by expipiplus1** [comment]
What is "the voice"?

**Comment by Jasper-Bekkers** [comment]
By default the build scripts that are in the documentation call into hctspeak.js; https://github.com/microsoft/DirectXShaderCompiler/blob/master/utils/hct/hctspeak.js and announce that build has been completed (or has failed). Typically at whatever volume it thinks is acceptable; something that's scared me on multiple occasions. It would be really nice if this feature is default-off / opt-in by default.

**Comment by hekota** [comment]
Hello Jasper, there is -dont-speak option on the hctbuild script, would that work for you?

**Comment by Jasper-Bekkers** [comment]
If that option exists, should it be the default?
