### ISSUE TITLE
[SPIR-V] Support KHR Ray tracing's OpTerminateRayKHR and OpIgnoreIntersectionKHR

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/DirectXShaderCompiler#3285]
These instructions have a different opcode than their `NV` counterpart, apparently for a reason: both are now terminal instructions.

There is already code in place to emit returns after the `NV` variant and reorder writes before it, would that be enough to support these functions normally without enforcing `AcceptHitAndEndSearch`/`IgnoreHit` to be placed at the end of a shader?

CC @jiaolu for submitting the intial changes.

**Comment by jiaolu** [comment]
okay. i will take a look.

**Comment by jiaolu** [comment]
a quick look here. new OpIgnoreIntersectionKHR/OpTerminateRayKHR  are block terminator. so it  is little more complicated than inserting a instruction.

**Comment by MarijnS95** [comment]
@jiaolu Correct. I attempted to [make a head-start](https://github.com/microsoft/DirectXShaderCompiler/compare/master...MarijnS95:rt) with a test and adding a new "group" for these two terminals, but am still missing a `TerminatorInst`. Better if someone else looks into it, I'm not familiar with this codebase at all.

**Comment by jiaolu** [comment]
made a quick pull-request, though the internal spirv validator would mis-report one validation error "OpLabel inside basic block"
though the generated spv can pass the tool spirv-val check.

**Comment by MarijnS95** [comment]
@jiolu Thanks! The code is pretty much identical to my attempt, goes to show that I ended up understanding it after all, but also ran into the same `OpLabel inside basic block` error which I assume is the internal validator not knowing that the block ends with that ray tracing terminal?

**Comment by ehsannas** [comment]
The SPIRV-Tools fix has been picked up by DXC, and that should fix the issue

**Comment by MarijnS95** [comment]
Thanks @ehsannas and @jiaolu for quickly picking this up and resolving this issue! We've immediately applied the SPIRV-Tools fixes to our Rust equivalents as well :+1: 

Did https://github.com/KhronosGroup/SPIRV-Tools/pull/4049 make it in as well? The same DCE fix but for `SPV_KHR_shader_clock` which was recently introduced to DXC.
