### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by 44DA133A8B** [microsoft/DirectXShaderCompiler#3286]
The latest build from Downloads does not work on Win7.
The latest WinSDK (10.0.19041.0) can be installed on Win7 but it does not contain DXC.

This is a little bit weird, since there's D3D12On7 (https://microsoft.github.io/DirectX-Specs/d3d/D3D12onWin7.html).

**Comment by hekota** [comment]
Hello,

the latest download works on Windows 7 as long as [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) and 2019 is installed, which is the same as for the previous 2 downloads.

We'll look into why dxc.exe is not included in WinSDK.

**Comment by llvm-beanz** [comment]
Since the user hasn't responded in several years I'm going to close this issue. Please file a new issue if you're still encountering issues.
