### ISSUE TITLE
Relative includes are handled differently from FXC - directories of previously included source files get searched

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#3294]
### Title
Relative includes are handled differently from FXC - directories of previously included source files get searched

### Functional impact
DXC searches relative `#include` paths oddly - it looks for them not only relative the directory of the file which is doing the include but also relative to the directories in the sequence of the include stack that lead to the current one. This means that it is more permissive and includes files which other compilers wouldn't (e.g. FXC doesn't do this), this can cause problems when trying to compile shaders written with DXC with other compilers and might potentially cause errors and confusion when the source folder structure contains identically named files

### Minimal repro steps
1. Create the following file structure:

```
include_repro/first.txt
include_repro/nested/second.txt
include_repro/third.txt
```
The files used are as follows:
[first.txt](https://github.com/microsoft/DirectXShaderCompiler/files/5634711/first.txt): `#include "nested/second.txt"`
[second.txt](https://github.com/microsoft/DirectXShaderCompiler/files/5634712/second.txt): `#include "third.txt"`
[third.txt](https://github.com/microsoft/DirectXShaderCompiler/files/5634917/third.txt): `float4 PSMain(float4 color : COLOR) : SV_TARGET{ return color; }`

2. Run DXC with the following command line `dxc.exe -T ps_6_0 -E PSMain include_repro\first.txt` from the directory containing the `include_repro` folder and observe that it compiles correctly (produces the same output as `dxc.exe -T ps_6_0 -E PSMain include_repro\third.txt` would)
3. Run DXC compiling `include_repro/nested/second.txt` with `dxc.exe -T ps_6_0 -E PSMain include_repro/nested/second.txt` and observe the compiler error.
```
include_repro\nested\second.txt:1:10: fatal error: 'third.txt' file not found
#include "third.txt"
         ^
```
### Expected result
Step 2 produces the compiler error seen in step 3. Meaning that DXC only searches for `three.txt` relative to the directory of `second.txt` which would result in looking for `include_repro/nested/` + `three.txt`, which does not exist

### Actual result
Step 2 produces no compiler error and unexpectedly includes `third.txt` even though it should not have searched for it inside of `include_repro/`

### Further technical details

- FXC behaves differently, running `fxc.exe /T ps_5_0 /E PSMain include_repro\first.txt` produces the error:
```
C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\include_repro\nested\second.txt(1,10-20): error X1507: failed to open source file: 'third.txt'

compilation failed; no code produced
```

DXC used to generate the outputs was built from 22dc78f4c3f745c82710fd69f5069e02b5131cae (Nov 16 2020)

**Comment by llvm-beanz** [comment]
The complaint here seems to be that DXC includes the current working directory of the compiler in the include paths. That's extremely standard in C compilers. FXC has the incorrect behavior here, not DXC.
