### ISSUE TITLE
DXC crashes when compiling HLSL with overlapping buffers.

### ISSUE THREAD

**Issue by VZout** [microsoft/DirectXShaderCompiler#3316]
If you use 2 overlapping buffers (same register, same space) DXC crashes. Occurs for any buffer type and the used shader model doesn't matter.

```hlsl
ByteAddressBuffer a : register(t0, space0);
ByteAddressBuffer b : register(t0, space0);

float2 main(float4 color : COLOR) : SV_TARGET
{
	return float2(a.Load(0), b.Load(0));
}
```

results in dxc.exe returning with exit code `-1073741819`

expected behavior is emitting a warning I suppose.

**Comment by pow2clk** [comment]
I tried with the latest code using `dxc.exe -T ps_6_0 3316.hlsl` and got this error:

`error: resource b at register 0 overlaps with resource a at register 0, space 0 Use /Zi for source location.`

Closing. If I missed some part of the repro, reopen and let us know.
