### ISSUE TITLE
[SPIRV] Replacing HitTNV by RayTmaxNV

### ISSUE THREAD

**Issue by apayen** [microsoft/DirectXShaderCompiler#3322]
Hello,

Currently, shaders using RayTCurrent() will fail spirv validation and must be build with -Vd to bypass this. Below are my findings:

https://github.com/microsoft/DirectXShaderCompiler/blob/906cdbcdf277dc198e8f80599b61f0591335d24e/tools/clang/lib/SPIRV/SpirvEmitter.cpp#L9828

Equivalent HitTKHR was removed from final KHR specification, and thus using HitTNV produces spirv only valid for the NV extension.

From [GLSL_NV_ray_tracing](https://github.com/KhronosGroup/GLSL/blob/master/extensions/nv/GLSL_NV_ray_tracing.txt) specification:

> gl_HitTNV is available only in the any-hit and closest-hit shaders. This is an alias of gl_RayTmaxNV added to closest-hit and any-hit shaders for convenience.

Looking at [SPIRV-Headers](https://github.com/KhronosGroup/SPIRV-Headers/blob/f027d53ded7e230e008d37c8b47ede7cd308e19d/include/spirv/unified1/spirv.hpp11#L607-L610), RayTmaxNV would be portable with RayTmaxKHR
```
    RayTmaxKHR = 5326,
    RayTmaxNV = 5326,
```

**Comment by TheMostDiligent** [comment]
We are having the same issue

**Comment by ehsannas** [comment]
Thanks for reporting @apayen @TheMostDiligent .

**Comment by ehsannas** [comment]
Would either of you be able to make a pull-request that we can review? If not, we'll make the fix in January. Thanks

**Comment by ehsannas** [comment]
Oh! It looks like @MarijnS95 has made a pull-request to fix this issue: https://github.com/microsoft/DirectXShaderCompiler/pull/3320

isn't open-source great? ;)

Thanks @MarijnS95

**Comment by MarijnS95** [comment]
> isn't open-source great? ;)

Yeah, except that GitHub has seemingly broken/disabled the "related issues/PRs" view when creating an issue, this title should have surely surfaced mine if it did :grimacing:
