### ISSUE TITLE
Raytracing shader compilation failure without output

### ISSUE THREAD

**Issue by turanszkij** [microsoft/DirectXShaderCompiler#3324]
Dear DXC team,

I started to use the newest DXC compiler, but now my raytracing shaders stopped compiling. There is no error written to the console output from dxc.exe. I am providing a repro case attached. The ZIP file contains repro.bat, which will attempt to compile rtreflectionLIB.hlsl and output rtreflectionLIB.cso. 

Problem: The file is never output, but no error is given. (DXC version **1.6 - 1.6.0.2902 (906cdbcd)** )
Expected result: The file compiles successfully, or error message is given to the output (it compiled in a previous DXC version:  **1.6 - 1.5.0.2786 (a730e27a)** )

Best regards,
Janos

[repro.zip](https://github.com/microsoft/DirectXShaderCompiler/files/5711790/repro.zip)

**Comment by ehsannas** [comment]
Are you trying to compile to SPIR-V or DXIL ?

**Comment by turanszkij** [comment]
The problem appears when compiling DXIL

**Comment by pow2clk** [comment]
I have tried this with the latest DXC build and I find it doesn't repro. Please let us know if you find differently. Thanks!

**Comment by turanszkij** [comment]
All good, thanks!
