### ISSUE TITLE
[SPIR-V] StructuredBuffer and RWStructuredBuffer can't be used as function parameters in HLSL of ray tracing shaders

### ISSUE THREAD

**Issue by chenxq12138** [microsoft/DirectXShaderCompiler#3340]
Here is the example:

[[vk::binding(0,0)]] StructuredBuffer<float4> gSBuffer;
[[vk::binding(1,0)]] RWStructuredBuffer<float4> gRWSBuffer;

void foo(StructuredBuffer<float4> pSBuffer)
{
}

[shader("raygeneration")]
void main()
{
    foo(gSBuffer);
}

The compilation of this shader is failed. But SPIRV-Cookbook.rst tells that StructuredBuffer and RWStructuredBuffer can be used as  
function parameters.

**Comment by kuhar** [comment]
Thanks for reporting, @chenxq12138. I'll loop in some spir-v folks.

Would it be possible to for you to also include the exact error message you see when the compilation fails and/or the dxc commend used to compile this file? Things like this make it easier to triage bug reports.

**Comment by kuhar** [comment]
@ehsannas can you take a look?

**Comment by chenxq12138** [comment]
Thanks for your reply, @kuhar. 
The command is: dxc -T lib_6_4 test.hlsl -spirv -Fh test.spv.h -fvk-use-scalar-layout -fspv-target-env=vulkan1.2 -Vn test
And, there are no error message, it just cannot generate the output file.
By the way, the dxc version which I used is the latest release version.
