### ISSUE TITLE
Some compile time const expressions can't be used to specify const array lengths (works with FXC)

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#3355]
### Title
Some compile time const expressions can't be used to specify const array lengths (works with FXC)

### Functional impact
Certain shaders which use expressions using arithmetic operations and intrinsics involving constants that compile with FXC cannot be compiled with DXC. Lack of support for the `min` intrinsic while `max` works seem like an obvious oversight.

### Minimal repro steps

1. Compile the following shader with `dxc.exe -T ps_6_0 -E PSMain issue_shader.txt`:
```
float4 BrokenTestArray0[int(.3*12)];
float4 BrokenTestArray1[min(2, 3)];
float4 WorkingTestArray0[max(2, 3)];

float4 PSMain(float4 color : COLOR) : SV_TARGET
{
    return BrokenTestArray0[int(color.x)] +
           BrokenTestArray1[int(color.y)] +
           WorkingTestArray0[int(color.z)];
}
```
2. Observe the compiler errors:
```
C:\issue_shader.txt:1:24: error: variable length arrays are not supported in HLSL
float4 BrokenTestArray0[int(.3*12)];
                       ^
C:\issue_shader.txt:2:24: error: variable length arrays are not supported in HLSL
float4 BrokenTestArray1[min(2, 3)];
                       ^
```
### Expected result
Casting to int and also the `min()` intrinsic with constant arguments are allowed when used in describing const array lengths as these operations work with FXC and since the `max()` intrinsic already works with DXC.

### Actual result
Casting to int and the `min()` intrinsic with constant arguments produce compiler errors when used to define const array lengths.

### Further technical details
There are likely other untested/unsupported operations which I haven't noticed yet. The use of `min` was an actual use case from our Unity shader codebase and I found the casting issue with some quick testing. It seems that `mad` and other intrinsics don't work as well but I didn't list them as some of them also fail with FXC, though it would be nice if all const expressions could be supported when describing array lengths.

**Comment by pow2clk** [comment]
Hi @Dredhog!

We're looking into this issue, but it looks unlikely for the next release. What is the priority for you?

**Comment by Dredhog** [comment]
Hi @pow2clk, thanks for taking it on!

It is not a critiacal/blocking issue for us ATM as I've only noticed it affect one shader in our SriptableRenderPipeline shader codebase, I was able to work around the issue from the shader using a macro.

But it will get more relevant going forward after we expose DXC to our users possibly sometime this year.

**Comment by Keenuts** [comment]
Hi!

As of today, I cannot reproduce this issue.

DXIL: the errors are not showing anymore, and the 3 arrays do seem to be correctly generated.
SPIR-V: The arrays are also correctly generated.

Feel free to reopen if needed 😊
