### ISSUE TITLE
DXC crashes on undeclared identifiers

### ISSUE THREAD

**Issue by h3r2tic** [microsoft/DirectXShaderCompiler#3357]
When undeclared identifiers are used in certain positions, DXC crashes. For example:

```hlsl
float4 main(float4 color: COLOR): SV_TARGET {
    return lerp(0.0.xxxx, 1.0.xxxx, foobar);
}
```

```
> dxc -T ps_6_3 test.hlsl
> echo %ERRORLEVEL%
-1073741819
```

On the other hand, this correctly results in an error:

```hlsl
float4 main(float4 color: COLOR): SV_TARGET {
    return lerp(foobar, 1.0.xxxx, foobar);
}
```

```
> dxc -T ps_6_3 test.hlsl
test.hlsl:2:17: error: use of undeclared identifier 'foobar'
    return lerp(foobar, 1.0.xxxx, foobar);
                ^
test.hlsl:2:35: error: use of undeclared identifier 'foobar'
    return lerp(foobar, 1.0.xxxx, foobar);
                                  ^
```

Tested with the DXC shipping in Vulkan SDK 1.2.162.0:
dxcompiler.dll: 1.6 - 1.5.0.2891 (cc43bc82)

Also tested with the today's AppVeyor build:
dxcompiler.dll: 1.6 - 1.6.0.2920 (50981cde)

Thanks!

**Comment by jaebaek** [comment]
@h3r2tic thank you for reporting this issue. Do you mean it crashes with the DXC shipping in Vulkan SDK 1.2.162.0 and it works fine with the up-to-date one?

I am sorry about the situation but if it is true, I think the next Vulkan SDK release will fix this issue.

**Comment by h3r2tic** [comment]
Sorry, I wasn't being precise about that. I meant that it crashed with both of the listed versions.

**Comment by h3r2tic** [comment]
Awesome, thank you! :)
