### ISSUE TITLE
WaveActive* and WavePrefix* ops emitted as 64-bit for constant int

### ISSUE THREAD

**Issue by hekota** [microsoft/DirectXShaderCompiler#3380]
WaveActive* and WavePrefix* ops are being emitted as 64-bit DXIL instructions on constant int.

```
[numthreads(3,1,1)]
void main() {
    WaveActiveMax(10);
    WavePrefixSum(5);
}
````

```
define void @main() {
  %1 = call i64 @dx.op.waveActiveOp.i64(i32 119, i64 10, i8 3, i8 0)  ; WaveActiveOp(value,op,sop)
  %2 = call i64 @dx.op.wavePrefixOp.i64(i32 121, i64 5, i8 0, i8 0)  ; WavePrefixOp(value,op,sop)
  ret void
}
```

We should be defaulting to 32-bits for literal values.

**Comment by llvm-beanz** [comment]
Related language change that would address this: https://github.com/microsoft/hlsl-specs/blob/main/proposals/0017-conforming-literals.md

**Comment by llvm-beanz** [comment]
This will be fixed in HLSL 202x with the integration of this feature: 
https://github.com/microsoft/hlsl-specs/blob/main/proposals/0017-conforming-literals.md
