### ISSUE TITLE
Missing docs on dx.viewIdState

### ISSUE THREAD

**Issue by seanbaxter** [microsoft/DirectXShaderCompiler#3383]

**Comment by lmnx90** [comment]
I have the same as above,  there is no docs about !dx.viewIdState in https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst .

**Comment by damyanp** [comment]
We are planning to improve documentation all up for HLSL and DXIL as we implement features in clang. For now, we have no plans to address this issue in the docs in this repo.
