### ISSUE TITLE
[SPIR-V] mesh shader should support point output topology.

### ISSUE THREAD

**Issue by seanbaxter** [microsoft/DirectXShaderCompiler#3387]
It's in GLSL_NV_mesh_shader.

**Comment by ehsannas** [comment]
Hi @seanbaxter , Thanks for reporting. This is a bit vague. Would you add more information?

**Comment by seanbaxter** [comment]
https://microsoft.github.io/DirectX-Specs/d3d/MeshShader.html#outputtopology

I'm actually translating from SPIR-V into DXIL, but the issue is the same. HLSL/DirectX doesn't support outputtopology("point") from mesh shaders. Was just confused by the lack of this, since PrimitiveTopology out of the GS includes points, as expected.

**Comment by sudonatalie** [comment]
I believe that spec is out of date. Both the DXIL and SPIR-V backends support `[outputtopology("point")]` and I think they did at the time this issue was filed, judging by the age of the tests verifying it. Sorry this went without a response for so long!
