### ISSUE TITLE
Set constants to IntrinsicOp enums

### ISSUE THREAD

**Issue by seanbaxter** [microsoft/DirectXShaderCompiler#3398]
Please set proper constants to these enums, as they are ordered lexicographically which seems right unstable. These are the true DXIL opcodes.

For motivation, I currently implement all GLSL library by attributing all function overloads with `spirv::opcode` or `spirv::GLSLstd450` C++ attributes, as appropriate:
https://github.com/seanbaxter/shaders/blob/master/spirv.cxx

This file is injected into the compiler when -shader is specified. The obvious way to slot in DXIL codegen is to add a `dxil::intrinsic` C++ attribute alongside the spirv ones. I'd encode a "dxil" spirv `ExtInstImport` and use `ExtInst` to encode those HLSL intrinsics.  The CFG->LLVM code would then invoke `callHLFunction` using the first parameter in the ExtInst.

But for that I need a number that doesn't shift around with each commit.

I imagine a header like this:
https://github.com/KhronosGroup/SPIRV-Headers/blob/master/include/spirv/unified1/GLSL.std.450.h

And a table like this:
https://www.khronos.org/registry/spir-v/specs/unified1/GLSL.std.450.html

**Comment by jaebaek** [comment]
I do not clearly understand what you mean. May I ask some examples of "proper constants" to be added to [IntrinsicOp](https://github.com/microsoft/DirectXShaderCompiler/blob/master/include/dxc/HlslIntrinsicOp.h#L16)?

**Comment by seanbaxter** [comment]
Numeric literals to prevent the values from changing every commit. Like you have for DXIL::OpCode.

**Comment by sudonatalie** [comment]
Sorry for the very late reply on this. This request doesn't actually appear to be specific to the SPIR-V backend though so I'll mark it to be re-triaged, although I wouldn't expect that this is a use case that is intended to be supported.

**Comment by llvm-beanz** [comment]
Yea, this isn't something we are going to fix. The "high level" intrinsics are unstable by design. Ultimately in clang we're moving away from this model. Our goal in clang is to use proper LLVM intrinsics instead of generic functions with "opcode" parameters. We'll lower to proper DXIL late so that we can generate the `dx.op` calls at the end, but we don't want them carried around throughout the middle of the compiler.
