### ISSUE TITLE
Doubts about int64 DXIL support?

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectXShaderCompiler#34]
Hi,
don't know if it's correct place to ask, but anyway seeing compiler supports int64 in addition to expected wave ops in shader model 6, I'm asking about expected ETA for support for int64?
it's a Shader model 6.0 feature or will be part of Shader model 6.1,6.5,7 or whatever comes nexts..
also will be in creators update coming this spring or will be later shipping like Redstone 3 toward end of the year?
thanks..

**Comment by marcelolr** [comment]
int64 is supported by shader model 6.0. It's not required of drivers to support this, however - the app should check for feature support before using a shader that uses int64 to create a PSO.

You can see an implementation of the check in the [DoesDeviceSupportInt64](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/unittests/HLSL/ExecutionTest.cpp#L541) function in [ExecutionTest.cpp](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/unittests/HLSL/ExecutionTest.cpp).

OS support is already available in the current previews - you need to be in the Insiders Fast ring to get the build we're currently recommending for running SM6 shaders.

**Comment by oscarbg** [comment]
Many thanks for pointing the code snippet!
seems Anniv. headers lack this feature option..

Ok so will install new Insiders build coming this week with new game mode announced today (build 15019).. are later builds (like 15019) than the recommended one (15007) ok for testing DXIL&SM6.0?

Also about drivers:
seems Nvidia new 378.49 driver advertises wave ops even on anniversary edition altough showing only SM5.x on Aniversary edition..
do you know if 378.49 supports DXIL and advertises SM6.0 on Insiders builds and is a recommended one for testing DXIL? seems AMD, Intel current public drivers doesn't support SM6.0& DXIL, correct?

Also possibly unrelated question.. seems Creators update brings new driver model WDDM 2.2 is that new driver model needed for support of DXIL& Shader model 6.0 features like Int64 support in drivers or brings graphics improvements unrelated to DXIL..
Thanks..

**Comment by alessiot89** [comment]
Hopefully there will be a cap-bit available in the next d3d12 runtime update...

**Comment by jholewinski** [comment]
@oscarbg, Nvidia 378.xx drivers support DXIL in experimental mode (OS in Developer Mode / call D3D12EnableExperimentalFeatures) on Win10 Insider builds.

**Comment by marcelolr** [comment]
We'll be keeping notes on which driver versions are suitable for bring-up for different features.

One last thing to close this issue out (please open another one if you still have questions). While more recent flights of Windows are still suitable for compiler development, running shaders on WARP may not work correctly - as the code transition from 0.7 to 1.0 support, some things may be broken. We'll update the recommended flight version once 1.0 support is available in WARP (if you don't care for that, feel free to pick any more recent version).
