### ISSUE TITLE
Pass manager modifications make it impossible to program the DXIL interface. Only the HLModule/DXIR path is viable.

### ISSUE THREAD

**Issue by seanbaxter** [microsoft/DirectXShaderCompiler#3402]
I'm trying to lower CFG to Dxil. I'm inside the passes.

Consider how populateModulePassManager has been hacked to run HL passes:

https://github.com/microsoft/DirectXShaderCompiler/blob/797d4b8adc2af6a96f3b0c989dee61bfcd05f3b9/lib/Transforms/IPO/PassManagerBuilder.cpp#L214
Here the HLEmitMetadataPass is created if HLSLHighLevel is true.

https://github.com/microsoft/DirectXShaderCompiler/blob/797d4b8adc2af6a96f3b0c989dee61bfcd05f3b9/lib/Transforms/IPO/PassManagerBuilder.cpp#L395
Here the HLEnsureMetadataPass is created if HLSLHighLevel is false.

https://github.com/microsoft/DirectXShaderCompiler/blob/master/lib/HLSL/HLModule.cpp#L514
When the passes are run, HLEnsureMetadataPass is invoked and there is a segfault on this line, because getNamedMetadata two lines above returns nullptr, because the HLEmitMetadataPass never emitted that metadata.

Since this is hard-coded into populateModulePassManager, it forces you to opt into using HLModule. I can initialize HLModule with basic stuff (shader model, entry point). Setting that stuff satisfies HLEnsureMetadataPass. But this also locks you out of DxilModule, because that gets initialized inside the pass manager with DxilGenerationPass, which was also scheduled by populateModulePassManager.

HLModule doesn't support input/output signature creation.. That is put in HLSignatureLower, called from DxilGenerationPass, which coerces the signature out of the function's arguments.

I have a full SPIR-V pipeline already built, and I already have the input/out arguments appended into DxilModule's signatures. How do I directly generate DXIL code? There are traps everywhere coercing one to use the DXIR interface, which you've been steering people away from. The way createHLEnsureMetadataPass is queued, when !HLSLHighLevel, makes it especially clear than straight-up DXIL cannot be generated.

I should have a mostly working backend at this point. But the validator always fails, because I can't run basic legalization passes like de-vectorization and SROA because the pass manager requires going through DXIR.

**Comment by seanbaxter** [comment]
I managed to comment out a number of passes from passManagerBuilder and compile simple vertex shaders. But callHLfunctions don't get translated when createDxilGenerationPass isn't in.

So I put it back in, initialize a trivial HLModule, and get a bunch of runtime errors. So I try to migrate everything from DxilModule to HLModule, putting input/output signatures aside. I Use HLModule's OP to provide callHLFunction support. Now there's another failure... Inside hlsl::CanConstantFoldCallTo in the CanSimplify callback, there's this line:

578├─> const bool found = F->getParent()->GetDxilModule().GetOP()->GetOpCodeClass(F, opClass);

This leads to a hard error in GetOpCodeClass because my dx.op.loadInput.f32, which I allocated with HLModule's OP, isn't found in DxilModule's OP, which is an entirely separate object. The whole infrastructure here apparently only works if you buy into the parameter system and let DxilGenerationPass or whatever initialize a DxilModule from HLModule and lower mysterious higher-level instructions down to dx.op.loadInput.f32, using that DxilModule created in the passes.

All I'm trying to do is use callHLFunctions from a DxilModule that I built from hand.

**Comment by seanbaxter** [comment]
https://gist.github.com/seanbaxter/27c5eb9356275cd1f5b5071a9725160b

I need to run this through the legalizer. This is the code that's causing all the pain described above. I just used callHLFunction to get vectorized sin. I don't know what combination of hacks to put in the pass manager builder to get this through the legalizer. AS it is now, everything is going through DxilModule.

**Comment by llvm-beanz** [comment]
Hey @seanbaxter, the changes to DXC's LLVM are a bit intrusive and supporting using that LLVM from another frontend has not been one of the design goals.

Supporting DXIL generation from generic LLVM constructs _is_ a primary design goal of our efforts in the upstream llvm-project's experimental DirectX target (although that effort is just barely started).

The DXC engineering team is not going to invest effort supporting this use case for DXC since we're instead prioritizing this use case with upstream LLVM. I can see the value that this support would provide, so we would certainly review and accept pull requests.

I'm going to close this issue since we're not going to actively work on it.
