### ISSUE TITLE
DXIL RemoveResourcesWithUnusedSymbols segfault

### ISSUE THREAD

**Issue by seanbaxter** [microsoft/DirectXShaderCompiler#3407]
https://github.com/microsoft/DirectXShaderCompiler/blob/master/lib/Transforms/IPO/GlobalDCE.cpp#L181
This line removes the parent pointer from a GlobalVariable with no uses. It's part of the Dead Global Elimination pass.

https://github.com/microsoft/DirectXShaderCompiler/blob/master/lib/DXIL/DxilModule.cpp#L1063
This line encounters the same GlobalVariable and calls eraseFromParent on it, but the parent was already nulled out by the dce pass, so it segfaults. It's used from the "DXIL Lower createHandleForLib" pass, and called by RemoveResourcesWithUnusedSymbols. I wouldn't know what to replace that eraseFromParent with. Probably just ignore it? The GV was already unlinked from the module by DGE.

More fundamentally, I don't know why DGE is killing my cbuffer in this code:
https://gist.github.com/seanbaxter/40e4bda072fcb2b06942dbfd2cf682e4

You can see in this pre-legalizer module dump that the cbuffer variable is referenced by a signature element which is included by !dx.resources. However, GV->use_empty() evaluates true after DxilModule::EmitDxilMetadata is called and before the passes begin, so DGE kills it. How do I prevent?

**Comment by seanbaxter** [comment]
Here is a much worse related case:
https://github.com/microsoft/DirectXShaderCompiler/blob/master/lib/DXIL/DxilModule.cpp#L1053

This is invoked from the "DXIL Lower createHandleForLib" pass.
https://github.com/microsoft/DirectXShaderCompiler/blob/master/lib/HLSL/DxilCondenseResources.cpp#L526

Here is my shader LLVM before and after the HLSL legalization passes:
https://gist.github.com/seanbaxter/f4cf0cd8e64c9d3eb0dffe57b5338e2e

I have well formed createHandle calls. There is metadata for the texture and sampler objects. But createHandle doesn't explicitly use them (it simply takes resource kind and index arguments), so the HLSL pass kills these resources, then later errors when the dx.op.sample intrinsic makes an out-of-bounds access.

The metadata I emit to the DxilModule gets killed by "HLSL DXIL Metadata Emit", which tries to overwrite the metadata. But at this point, the SRV and Sampler objects have already been culled by the previous pass.

How do I emit DXIL code when your passes keep eliminating the code I emit.

**Comment by llvm-beanz** [comment]
This issue doesn't have a repro case from HLSL or LLVM IR, so it isn't tractable for us to investigate. I also suspect this is coming from Circle generated IR, which is not something we're explicitly going to support from DXC. Supporting DXIL generation from non-DXC frontends is a goal of the DirectX backend in LLVM, but not a goal of the DXC project.
