### ISSUE TITLE
Size of bound StructuredBuffer returned in reflection clarification

### ISSUE THREAD

**Issue by xander890** [microsoft/DirectXShaderCompiler#3413]
Hello, 

I need a clarification on `D3D12_SHADER_INPUT_BIND_DESC` returned by  `ID3D12ShaderReflection::GetResourceBindingDesc`. 

If I bind a structured buffer in HLSL as such:

```
struct Test 
{
     float4 a;
     float4 b;
}
RWStructuredBuffer<Test> uavTest : register(u0);
```

I noticed that the NumSamples field returned by the binding reflection contains the size in bytes of the bound struct (32 in the example above). This seems to be confirmed in the implementation:

https://github.com/microsoft/DirectXShaderCompiler/blob/65155d95bd0a3fa34f15364c56a5bef9a8adce0d/lib/HLSL/DxilContainerReflection.cpp#L1633

How much is it possible to rely on this behavior in the future? It would be very useful for some stuff I am doing, but I am not sure if this behavior will be removed in future versions. It does not seem to be mentioned explicitly [in the API](https://docs.microsoft.com/en-us/windows/win32/api/d3d12shader/ns-d3d12shader-d3d12_shader_input_bind_desc).  

Thanks in advance for the answer!
-Alessandro

**Comment by damyanp** [comment]
Reviewing older issues - sorry we didn't address this sooner.  As this is over 3 years old I'm going to close this now. Please feel free to reopen it if you still need us to investigate and answer your question.

**Comment by xander890** [comment]
We now rely on this behavior heavily, so it would be nice to know if this will continue to be supported in the future.

**Comment by damyanp** [comment]
@xander890 - I see this test that I think covers this behavior: https://github.com/microsoft/DirectXShaderCompiler/blob/3546bde202e4bb5bc1185b6b4b9d066a68a64298/tools/clang/test/HLSLFileCheck/d3dreflect/lib_exports1.hlsl#L178

This means we won't accidentally change it and it should be safe to rely on it in DXC.

@coopp - when you're looking at the reflection APIs, can you be sure that this scenario is covered please? It's surprising that this value is written there, and it doesn't match what the documentation says, but it is something people have started taking a dependency on and we have tests in place validating that it behaves this way.

**Comment by xander890** [comment]
Ok, thanks, I remember 3 years ago I definitely could not find it in the docs, so it must have been added since then. All good, nice to know we can safely rely on it :)
