### ISSUE TITLE
[spirv] external/effcee branch master->main

### ISSUE THREAD

**Issue by ChemistAion** [microsoft/DirectXShaderCompiler#3430]
It seems that submodule `external/effcee` follows now https://github.com/github/renaming scheme...

Please update `external/effcee` branch name to `main`, it will easier git-mumbling when `DirectXShaderCompiler` itself is a submodule.

**Comment by ChemistAion** [comment]
ofc... but I will leave these here for surprised:
* https://stackoverflow.com/questions/1777854/how-can-i-specify-a-branch-tag-when-adding-a-git-submodule/18799234#18799234
* https://stackoverflow.com/questions/9189575/git-submodule-tracking-latest

**Comment by jaebaek** [comment]
@ChemistAion Thank you for reporting this issue. We will handle it soon.

**Comment by ChemistAion** [comment]
OK, I will leave it open for now...
