### ISSUE TITLE
[SPIR-V] Support SPV_KHR_physical_storage_buffer for buffers

### ISSUE THREAD

**Issue by john-h-k** [microsoft/DirectXShaderCompiler#3442]
Support an attribute to indicate a buffer will be bound via a pushconstant provided GPUVA. This allows frameworks to emulate root descriptors on VK, but given there is currently no way to access GPUVAs in HLSL even when targeting SPIRV, it is not currently possible

**Comment by sudonatalie** [comment]
The [RawBufferLoad and RawBufferStore](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst#id175) intrinsics now support loading and storing from GPU accessible memory at a given address. If this doesn't satisfy your use case please comment with some additional detail and we can reopen this issue.
