### ISSUE TITLE
[SPIR-V] Assigning SV_DispatchThreadID to a float argument causes validation errors (does not happen with DXIL backend)

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#3443]
### Title
[SPIR-V] Assigning SV_DispatchThreadID to a floating point type argument causes validation errors (does not happen with DXIL backend)

### Functional impact
When trying to decorate a `float`/`float2`/`float3`/`float4` compute shader entry point argument with `SV_DispatchThreadID` compilation fails without a clear message and a validation error is printed

### Minimal repro steps

1. Compile the following shader with `dxc.exe -T cs_6_0 -E CSMain -spirv issue_shader.txt`:
```
RWStructuredBuffer<float4> rwTexture;

[numthreads(1, 1, 1)]
void CSMain(float2 id : SV_DispatchThreadID)
{
	rwTexture[3] = id.xxxx;
}
```
### Expected result
No validation errors and floating point SV_DispatchThreadID variables are allowed

### Actual result
Validation errors in output:
```
fatal error: generated SPIR-V is invalid: [VUID-GlobalInvocationId-GlobalInvocationId-04238] According to the Vulkan spec BuiltIn GlobalInvocationId variable needs to be a 3-component 32-bit int vector. ID <2> (OpVariable) is not an int vector.
  %gl_GlobalInvocationID = OpVariable %_ptr_Input_v3float Input

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

### Further technical details
Ran this on [shader playground](http://shader-playground.timjones.io/2f67087a276be87b2b54a50bb7e10094) with DXC from 2020 12 16

**Comment by jaebaek** [comment]
As discussed in https://github.com/microsoft/DirectXShaderCompiler/pull/3481#issuecomment-782388916, DXIL backend will also deny non-integer type `SV_DispatchThreadId`. See #3043. Let me close this issue because it will be a correct behavior after the PR is merged.
