### ISSUE TITLE
[SPIR-V] Writing to a read only Buffer<> resource produces validation errors (asks to report a bug)

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#3465]
### Title
[SPIR-V] Writing to a read only Buffer<> resource produces validation errors (asks to report a bug)

### Functional impact
The shader fails to compile without a clear error message which would indicate the issue. The generated message asks to report a bug.

### Minimal repro steps
1. Compile the following shader with `dxc.exe -T cs_6_0 -E CSMain -spirv issue_shader.txt`:
```
Buffer<uint> MyBuffer;

[numthreads(1, 1, 1)]
void CSMain (int3 id : SV_DispatchThreadID)
{
    MyBuffer[id.x] = id.y;
};
```
### Expected result
The shader compilation fails with a clear error message indicating where in the source code the invalid write is.

### Actual result
```
fatal error: generated SPIR-V is invalid: Expected Image 'Sampled' parameter to be 0 or 2
  OpImageWrite %18 %17 %15 None

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

### Further technical details
Ran this on [shader playground](http://shader-playground.timjones.io/0638e81a62c3c3c89b100df8a4d41631) with DXC from 2020 12 16 

NOTE: the same happens with the DXIL backend but it does not ask to report a bug:
```
error: validation errors
Function: CSMain: error: store should be on uav resource. Use /Zi for source location.
note: at 'call void @dx.op.bufferStore.i32(i32 69, %dx.types.Handle %1, i32 %2, i32 undef, i32 %3, i32 %3, i32 %3, i32 %3, i8 15)' in block '#0' of function 'CSMain'.
Validation failed.
```
 [shader playground](http://shader-playground.timjones.io/1bf6572dd4315e439c6c5ad40d3911c4)

**Comment by jaebaek** [comment]
@Dredhog Thank you for reporting the issue. We will take a look.

**Comment by jaebaek** [comment]
I tested it with the current tot 9972b664a34e98e99906a1c3e851be64f3cbb926 build and confirmed it is fixed.

```
a.hlsl:6:20: error: cannot assign to return value because function 'operator[]<const unsigned int &>' returns a const value
    MyBuffer[id.x] = id.y;
    ~~~~~~~~~~~~~~ ^
note: function 'operator[]<const unsigned int &>' which returns const-qualified type 'const unsigned int &' declared here
```

The new error message clearly pinpoints the code location causing the error.
