### ISSUE TITLE
[SPIR-V] allow users to access `gl_InstanceIndex`

### ISSUE THREAD

**Issue by jaebaek** [microsoft/DirectXShaderCompiler#3479]
This issue is from https://github.com/microsoft/DirectXShaderCompiler/issues/3361#issuecomment-774485134

> Could the `gl_InstanceIndex` be exposed directly as a built in (`[[vk::builtin("InstanceIndex")]]`)?
I'm using DXC to generate Vulkan shaders for PC where I want the functionality of `gl_InstanceIndex` with a non-zero BaseInstance. A built-in would allow SV_InstanceID to continue to work as is, while also allowing a shader access to the built-in SPIR-V `BaseInstance` and `InstanceIndex` variables. The [SPIR-V DXC documentation](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst) is currently incorrect, because it states `SV_InstanceID` maps to the `InstanceIndex` built-in, with no mention of the "correction" applied to align it with DX12 semantics.

**Comment by sudonatalie** [comment]
Requests for new language features (including Vulkan-specific attributes) now fall under the scope of the [microsoft/hlsl-specs](https://github.com/microsoft/hlsl-specs) repository, and access to arbitrary SPIR-V builtin inputs is being considered as part of the [Update to inline SPIR-V](https://github.com/microsoft/hlsl-specs/pull/59/) proposal.
