### ISSUE TITLE
Add an option to abort compilation when generating errors

### ISSUE THREAD

**Issue by vcsharma** [microsoft/DirectXShaderCompiler#3496]
It came up during review of #3043 that when generating compilation errors, it is desirable in most cases to stop further compilation and exit. It seems the current mechanism doesn't support that. 

Here is a relevant comment from @tex3d

> Currently, it seems the only way to abort the pipeline is with a report_fatal_error, which currently raises a structured exception - which is way too harsh for something like this, and we should likely change report_fatal_error to throw a C++ exception, since we still have a chance of emitting a useful error message then.

**Comment by bob80905** [comment]
This issue was completed with:
https://github.com/microsoft/DirectXShaderCompiler/pull/4427
