### ISSUE TITLE
Local array as an inout parameter generates inefficient microcode

### ISSUE THREAD

**Issue by ohlenbg** [microsoft/DirectXShaderCompiler#3501]
Currently we’re using UAV buffers to store and read closure data to avoid data unrolling. Is there a way to pass large arrays as inout parameter without having it unrolled in the compiled Fc code?

Please find attached the HLSL shader array_test. Uncomment line 10 #define USE_ARRAY_CASE as reproducer of the unrolling.
[array_test.txt](https://github.com/microsoft/DirectXShaderCompiler/files/6035031/array_test.txt)

Also attached the resulting microcodes for both versions. 
[Microcode_when_using_UAV.txt](https://github.com/microsoft/DirectXShaderCompiler/files/6035033/Microcode_when_using_UAV.txt)
[Microcode_when_using_array.txt](https://github.com/microsoft/DirectXShaderCompiler/files/6035034/Microcode_when_using_array.txt)

**Comment by damyanp** [comment]
Unfortunately, this is how HLSL is currently designed to work - inout parameters are copy-in/copy-out.  We are investigating language features (such as references) that could address this.
