### ISSUE TITLE
When using in games, OSD softwares such as RTSS cannot work

### ISSUE THREAD

**Issue by qinlili23333** [microsoft/DirectXShaderCompiler#3503]
I renamed `d3dcompiler_dxc_bridge.dll`  to `d3dcompiler_42.dll` or `d3dcompiler_47.dll` and copy with `dxcompiler.dll` to games' bin path. According to ProcessExplorer, these dll are finely loaded and the games run well. However, any OSD softwares such as Riva Tuner Statistics Server cannot display information on screen. 
(While Steam overlay works fine, and FPS meter by GFE works fine too)

**Comment by pow2clk** [comment]
It's difficult to tell exactly what's happening here. As interesting an experiment as it is, I'm afraid renaming the DLLs and loading them when a program is expecting something else is not supported behavior. Closing.

**Comment by pow2clk** [comment]
To give a little more clarity, the bridge DLL was meant to be used by developers to help transition their games to the new compiler DLL. It was never meant for these kind of scenarios. 

Without knowing a lot of details about library search paths, D3D versions expected etc, it would be difficult to speculate what exactly is happening to your games/OSD, but I can say it's not something we actively support. To use the new compiler, an application needs to be made to use it by the developer
