### ISSUE TITLE
_GetConstantBufferByName exception in debug mode with DXIL

### ISSUE THREAD

**Issue by CallumCVM** [microsoft/DirectXShaderCompiler#3511]
_GetConstantBufferByName causes an exception in debug mode because the CRT thinks m_CBsByName and m_StructuredBufferCBsByName are of different types, so a type mismatch exception is thrown.

If DXIL is not used as a target, no problem. No problem in Release mode too.

**Comment by CallumCVM** [comment]
After further testing, it seems this is caused by reflection and does not occur if no constant buffer (or an empty constant buffer) is in the shader.

**Comment by damyanp** [comment]
Can you provide a repro case on the most recent DXC please?  Otherwise there's not much we can do at this point.
