### ISSUE TITLE
[SPIR-V] Generic (and potentially unsafe) Support To Use Any SPIR-V Extension

### ISSUE THREAD

**Issue by AquaGeneral** [microsoft/DirectXShaderCompiler#3519]
Currently we are at the mercy of the DXC developers to support the shiny-new SPIR-V extensions (which is actually a good thing for robustness). However it would be nice if there was some way to emit code for all unsupported extensions, potentially in a way might not have all language safety checks (hopefully a better version of emitting assembly instructions in C++).

Consider the following code ([Shader Playground](http://shader-playground.timjones.io/344813cbb3576b8ed552999b7e4fe03e)):
```
#version 450
#extension GL_ARB_shader_group_vote: enable

void main() {
    bool iEqual22 = gl_LocalInvocationIndex == 22;
    anyInvocationARB(iEqual22);
}
```

Note I may be incredibly naive here, but to me it looks like as long as the signature would match in the equivalent HLSL code, the final compile SPIR-V should be valid (at least for these simpler cases I think).

Potentially a new language feature would have to be added to desginate the intention of the unknown-to-HLSL call:
```
RWBuffer<int> buf;
void Main(int id : SV_DispatchThreadID) {
    bool iEqual22 = id == 22;
    buf[id] = SPIRV_EXT_FUNCTION("OpSubgroupAnyKHR", iEqual22);
}
```

**Comment by jaebaek** [comment]
@AquaGeneral Thank you for reporting this issue. We will take a look.

**Comment by AquaGeneral** [comment]
Wow, here it is! https://github.com/microsoft/DirectXShaderCompiler/wiki/GL_EXT_spirv_intrinsics-for-SPIR-V-code-gen
