### ISSUE TITLE
Rendering problem when used in Chromium programs

### ISSUE THREAD

**Issue by qinlili23333** [microsoft/DirectXShaderCompiler#3527]
rename `d3dcompiler_dxc_bridge.dll` to `d3dcompiler_47.dll` and copy with `dxcompiler.dll` to Chromium program's bin path
then program cannot render weg pages well: all text disappear, all SVG disappear,some CSS styles broken,images work well
Google Chrome, nw.js, Electron, and other programs with Chromium all have this problem.

**Comment by pow2clk** [comment]
Please see my comments on #3503 for why this behavior is not intended nor supported
