### ISSUE TITLE
[templates] fatal error using static member var

### ISSUE THREAD

**Issue by pow2clk** [microsoft/DirectXShaderCompiler#3557]
This this simple vs_6_0 example causes a fatal error in DXC:
```hlsl
template <typename T>
struct Foo {
    static const int bar = 0;
};
void main() {
    Foo<int>::bar;
}
```
Produces this error:
```
.\Specialization.hlsl:4:22: fatal error: found unregistered decl
    static const int bar = 0;
```

**Comment by tcorringham** [comment]
I'm not seeing the fatal error with this example - are there some steps to recreate it that I'm missing? What command line was used?

**Comment by pow2clk** [comment]
@jaebaek @ehsannas , Turns out this one is a spirv backend issue with templates

**Comment by jaebaek** [comment]
Sure, I will take a look

**Comment by jaebaek** [comment]
It is weird .. I got errors when I generate DXIL
```
$ ./bin/dxc -Tvs_6_0 -Emain template.hlsl
template.hlsl:1:1: error: 'template' is a reserved keyword in HLSL
template <typename T>
^
template.hlsl:6:5: error: use of undeclared identifier 'Foo'
    Foo<int>::bar;
    ^
template.hlsl:6:12: error: expected '(' for function-style cast or type construction
    Foo<int>::bar;
        ~~~^
template.hlsl:6:15: error: no member named 'bar' in the global namespace
    Foo<int>::bar;
            ~~^
```

I used commit 3857ceedf192fb18fb9b5f9b2d3450c8af732257 of hlsl-2021 branch https://github.com/microsoft/DirectXShaderCompiler/tree/hlsl-2021. Could you please let me know what commit or branch I should use to successfully generate DXIL for it?

**Comment by tcorringham** [comment]
I think you just need the -enable-templates option.

**Comment by jaebaek** [comment]
#3687 fixes this issue. Can we close it?

**Comment by pow2clk** [comment]
Looks good to me! I'm willing to trust you if you want to close these yourself in future.

**Comment by jaebaek** [comment]
Thanks!
