### ISSUE TITLE
DXC supports 64-bit bfe but only 32-bit bfi.

### ISSUE THREAD

**Issue by seanbaxter** [microsoft/DirectXShaderCompiler#3565]
Missing 64-bit bfi overload here
https://github.com/microsoft/DirectXShaderCompiler/blob/master/lib/DXIL/DxilOperations.cpp#L134

**Comment by damyanp** [comment]
These DXIL operations only exist to facilitate DXBC->DXIL translation, we don't generate them when compiling from HLSL.
