### ISSUE TITLE
Missing compile error

### ISSUE THREAD

**Issue by Nielsbishere** [microsoft/DirectXShaderCompiler#3572]
Write access into a Texture2D is allowed, until the DXIL validation stage happens. This is not ideal, as DXIL validation errors are quite unreadable. I'd suggest detecting assignment to a Texture2D's value and popping a compile error if that happens; but allowing it with a RWTexture2D.

**Comment by tex3d** [comment]
Funny you should point this out.  I had a fix on the back burner, but needed to finish updating some tests that were out of date.

Fix in PR: #3580
