### ISSUE TITLE
SM6.6: -Od breaks dynamic samplers (inlined initializer not right?)

### ISSUE THREAD

**Issue by jeffnn** [microsoft/DirectXShaderCompiler#3573]
With the appended HLSL

>dxc.exe -E GeometryPS -T ps_6_6 test.hlsl

Works great. But:

>dxc.exe -E GeometryPS -T ps_6_6 -Od test.hlsl

error: validation errors
Function: GeometryPS: error: I8 can only be used as immediate value for intrinsic or as i8* via bitcast by lifetime intrinsics. Use /Zi for source location.
note: at '%11 = extractvalue %dx.types.Handle %9, 0' in block '#0' of function 'GeometryPS'.
Function: GeometryPS: error: Instructions must be of an allowed type. Use /Zi for source location.
note: at '%12 = insertvalue %dx.types.Handle undef, i8* %11, 0' in block '#0' of function 'GeometryPS'.
Validation failed.

struct VS_OUTPUT_GEO
{
    float4 Pos        : SV_Position;
    float2 Tex0        : TEXCOORD0;
    float2 Tex1        : TEXCOORD1;
}; 

static sampler sampler0 = SamplerDescriptorHeap[0];
Texture2D txDiffuse : register(t0);
Texture2D txBump: register(t1);
Texture2D txEnv: register(t2);

float4 GeometryPS(VS_OUTPUT_GEO input) : SV_Target
{
    float4 Diffuse = txDiffuse.Sample(sampler0, input.Tex1);
    float2 Bump = txBump.Sample(sampler0, input.Tex1).xy;
    float2 BumpOffset;

    BumpOffset.x = Bump.x * 0.5f;
    BumpOffset.y = Bump.y * 0.5f;

    float2 EnvTexCrd = input.Tex0 + BumpOffset;
    float4 Env = txEnv.Sample(sampler0, EnvTexCrd);

    return Diffuse + 0.25 * Env;
}

**Comment by tex3d** [comment]
This was fixed with #3499.
