### ISSUE TITLE
[spirv] Use constant value for offset (SPIR-V spec does not accept a variable offset for OpImage* instructions other than OpImage*Gather)

### ISSUE THREAD

**Issue by xxxbxxx** [microsoft/DirectXShaderCompiler#3575]
hi,

I've updated to the latest dxc.exe and I get a new error on shaders that previously compiled and worked fine:
`Use constant value for offset (SPIR-V spec does not accept a variable offset for OpImage* instructions other than OpImage*Gather)`

see https://github.com/microsoft/DirectXShaderCompiler/pull/3456

However when I look at the code I see two cases:
 * function calls: 
```hlsl
float4 FxaaTexOff(FxaaTex tex, float2 pos,  int2 off, float2 rcpFrame) {
 // [...]
  return tex.tex.SampleLevel(tex.smpl, pos.xy, 0.0, off.xy);
}
// called with constant offsets
    float3 rgbN = FxaaTexOff(tex, pos.xy, FxaaInt2( 0,-1), rcpFrame).xyz;
    float3 rgbW = FxaaTexOff(tex, pos.xy, FxaaInt2(-1, 0), rcpFrame).xyz;
```

* unrolled loops:
```hlsl
 [unroll] for (int i=-3; i<=+3, i++)	{
		int2	i2LoadOffset= int2(i, 0);	
		float4	TapColor0	= TMapInput0		.Load(int3(i2Pixel,0), i2LoadOffset);
```

So I guess the code was previously legalized after the optimisation passes.

Any advice on how to fix the errors (short of manually unrolling and inlining the functions)?

**Comment by jaebaek** [comment]
Based on the new SPIR-V validation rule (https://github.com/KhronosGroup/SPIRV-Tools/pull/4118), we cannot use variable for `OpImage*` instruction. You have to use constant values.

In your code
```
  return tex.tex.SampleLevel(tex.smpl, pos.xy, 0.0, off.xy);  // <-- off.xy is not allowed because it's variable. Use constant e.g., int2(0,2)
```

Note that FXC also has the same behavior: http://shader-playground.timjones.io/1942ffec1099ced43f3932d678903882. I guess GPU drivers cannot support variables for it.

**Comment by xxxbxxx** [comment]
I'm not saying the error is wrong.
I'm saying that it would be nice to have the check done after inlining / unrolling, like 'fxc' and 'dxc dxil'.  
(ot that there may be some other way or option I don't know?)

This example seems fine with both fxc and the older dxc, both dxil and spirv (when looking at the output).  
http://shader-playground.timjones.io/2d0395e3311262453e25b0ca3b06769a

But with newer `dxc -spirv`, it no longer compiles.

**Comment by xxxbxxx** [comment]
and if I change [unroll] to [loop] to force the error, 
http://shader-playground.timjones.io/ba22303a17c59a31d1fc23fe45f1c9b4

dxc helpfully suggests unrolling to fix the error:
`error: Offsets for Sample* must be immediated value. Consider unrolling the loop manually and use -O3, it may help in some cases. Use /Zi for source location.`

**Comment by GregSlazinski** [comment]
Hello,

I have the exact same problem.

Example code:
```
      [unroll] for(Int y=-1; y<=1; y++)
      [unroll] for(Int x=-1; x<=1; x++)
           image.SampleLevel(SamplerPoint, uv, 0, int2(x, y))
```

This code compiled and worked fine in a previous release.
Now it fails to compile.

As you see the x,y for are unrolled so they expand to constants.

Can you please fix this? Because it's breaking my work.

**Comment by jaebaek** [comment]
The main issue is that DXC SPIR-V backend does not conduct loop-unrolling and relies on the spirv-opt passes for the optimization. We have to check why the loop-unrolling does not work before the validation check. Let me take some time for the investigation.
