### ISSUE TITLE
[SPIR-V] Return a "void" in a void function causes crash

### ISSUE THREAD

**Issue by Evil-Ryu** [microsoft/DirectXShaderCompiler#3596]
```cpp
void A(out float a)
{
    a = 1.;
}

void B()
{
    float a;
    return A(a);
}

[shader("raygeneration")]
void MainRG() 
{
	B();
}
```

This is the shader to reproduce the issue, it causes the dxc to crash in spirvtools::opt

compile arguments as below:
`dxc.exe  -T lib_6_5 E:\test.txt -exports MainRG-spirv -fspv-target-env=vulkan1.2`

Tested on dxc of VulkanSDK 1.2.154.1, 1.2.170.0,  and revision: 259ce00a7868fc1f4585d95c305aa3fb71c6b964

Chaning the "return A(a);" to "A(a); return;" would fix the issue.

**Comment by jaebaek** [comment]
@Evil-Ryu Thank you for reporting this issue.
