### ISSUE TITLE
How to download the nightly build of `dxcompiler.dll`

### ISSUE THREAD

**Issue by ghostplant** [microsoft/DirectXShaderCompiler#3619]
The last release was over half year ago. Is there a repo to download the nightly build of latest `dxcompiler.dll`?

**Comment by ehsannas** [comment]
It is linked in the Downloads section (Windows): https://github.com/microsoft/DirectXShaderCompiler#downloads

**Comment by ghostplant** [comment]
Thanks, the nightly headers are easily conflict with standard `dxcapi.h` from Windows Kit 10.
Is there any good solutions to avoid that?
