### ISSUE TITLE
[SPIR-V] Support EvaluateAttribute* intrinsics

### ISSUE THREAD

**Issue by jaebaek** [microsoft/DirectXShaderCompiler#3649]
Currently, SPIR-V backend does not support `EvaluateAttribute*` intrinsics.

According to the discussion in https://github.com/KhronosGroup/glslang/issues/2584, `OpInterpolate*` needs a pointer operand rather than `OpLoad`. Based on the offline discussion with @greg-lunarg we need a spirv-opt pass to replace `OpLoad` operand of `OpInterpolate*` to the pointer loaded by the `OpLoad`.

When a spirv-opt pass is prepared, we can simply let DXC emit `OpInterpolate*` for `EvaluateAttribute*`. Since it will just follow typical code generation routine, it will use `OpLoad` for its operand. We can rely on the spirv-opt pass to make it correct (as a part of the legalization pass).

**Comment by jaebaek** [comment]
https://github.com/KhronosGroup/SPIRV-Tools/pull/4220 is the spirv-opt PR.

**Comment by jaebaek** [comment]
We have two use three instructions `InterpolateAtCentroid`, `InterpolateAtSample`, and `InterpolateAtOffset` of [GLSL.std.450 extended instruction set](https://www.khronos.org/registry/spir-v/specs/unified1/GLSL.std.450.html) for corresponding `EvaluateAttribute*`.

**Comment by gjaegy** [comment]
We are also relying on EvaluateAttributeAtSample() HLSL instruction in our code. This is now the only thing we haven't been able to port to Vulkan. Not dramatic, but our tree shadows looked better in D3D11, what is a bit frustrating.

Is there any update on that issue ?

Thanks a lot !

**Comment by pdoane** [comment]
I'm also interested in this.  I tried using the SPIR-V intrinsics but not sure how to get the interpolant into the Input storage class.  Here is what I tried:

```
[[vk::ext_capability(/* InterpolationFunction */ 52)]]
[[vk::ext_instruction(/* InterpolateAtSample */ 77, "GLSL.std.450")]]
float2 InterpolateAtSample([[vk::ext_reference]] float2 x, uint);
```

which outputs:

```
fatal error: generated SPIR-V is invalid: GLSL.std.450 InterpolateAtSample: expected Interpolant storage class to be Input
  %76 = OpExtInst %v2float %1 InterpolateAtSample %75 %70
```
