### ISSUE TITLE
float for ShadingRate is fine when we generate DXIL. Is it intended?

### ISSUE THREAD

**Issue by jaebaek** [microsoft/DirectXShaderCompiler#3676]
Using `float` for `SV_ShadingRate` is not allowed, but using `float` for `ShadingRate` is fine when we generate DXIL.

```
struct VS_OUT {
  float4 pos : SV_Position;
  uint rate : SV_ShadingRate;
};

VS_OUT main(float4 pos : Pos, float rate : ShadingRate) {
  VS_OUT Out;
  Out.pos = pos;
  Out.rate = rate;
  return Out;
}
```

See http://shader-playground.timjones.io/49d8da73a15ce0a3f8ba79eb659edd50.

Is it intended?

**Comment by pow2clk** [comment]
Without the SV_ prefix, the semantic is arbitrary without any specific meaning or validation. So it can be any type. The example you have above cannot take an SV_ShadingRate input because it's a vertex shader. Fragment shaders do and have special treatment for parameters with SV_ShadingRate.
