### ISSUE TITLE
[SPIR-V]  Reached non-composite type while indexes still remain to be traversed

### ISSUE THREAD

**Issue by Evil-Ryu** [microsoft/DirectXShaderCompiler#3681]
I got error:

`fatal error: generated SPIR-V is invalid: Reached non-composite type while indexes still remain to be traversed.
  %16 = OpCompositeExtract %float %AA 0
note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible`

The code to reproduce: 
`
struct A
{
	float  a;
	uint  b;
	float  GetA()
	{
		return a;
	}
};
ConstantBuffer<A> AA :  register( b0 , space2 ) ;
void Main(out float4 col : SV_Target0)
{
    col.x = AA.GetA();
}
`

Tested on latest commit:  6775e94ef17d26449413d2074f837fb739e0f16c

**Comment by jaebaek** [comment]
Thank you for reporting this issue. We will take a look.
