### ISSUE TITLE
D3D12 ERROR: ID3D12Device::CreateStateObject: Hash check failed for DXILibrary.pShaderBytecode: 0x0000026A3771F630.

### ISSUE THREAD

**Issue by ganluo960214** [microsoft/DirectXShaderCompiler#3692]
I upload simple code https://github.com/ganluo960214/DXILibrary.pShaderBytecode.git

'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Users\gl\Documents\source\dx\DXILibrary.pShaderBytecode\Buildout\x64\Debug\DXILibrary.pShaderBytecode.exe'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\D3D12.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Users\gl\Documents\source\dx\DXILibrary.pShaderBytecode\Buildout\x64\Debug\dxcompiler.dll'. 
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\rpcrt4.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140_1.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Users\gl\Documents\source\dx\DXILibrary.pShaderBytecode\Buildout\x64\Debug\dxil.dll'. 
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\D3D12Core.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\DXGIDebug.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\d3d12SDKLayers.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\DXGIDebug.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\d3d12SDKLayers.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\DXGIDebug.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\ResourcePolicyClient.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\ResourcePolicyClient.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\DXCore.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\nvldumdx.dll'. 
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\cryptnet.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\imagehlp.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\rsaenh.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\nvwgf2umx.dll'. 
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. Symbols loaded.
The thread 0xa150 has exited with code 0 (0x0).
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\NvCamera\NvCameraAllowlisting64.dll'. 
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\wldp.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\shlwapi.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\wldp.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\windows.storage.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\shell32.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\NvCamera\NvCameraAllowlisting64.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\wldp.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\d3d12SDKLayers.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\d3d12SDKLayers.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\winmm.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\nvwgf2umx.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\version.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\nvldumdx.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\nvldumdx.dll'. 
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\nvwgf2umx.dll'. 
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. Symbols loaded.
The thread 0xbb28 has exited with code 0 (0x0).
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\NvCamera\NvCameraAllowlisting64.dll'. 
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\NvCamera\NvCameraAllowlisting64.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\d3d12SDKLayers.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\dxilconv.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\D3DSCache.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\userenv.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\twinapi.appcore.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\dxilconv.dll'
The thread 0x326c has exited with code 0 (0x0).
The thread 0x8dbc has exited with code 0 (0x0).
The thread 0x8824 has exited with code 0 (0x0).
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\winmm.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\nvwgf2umx.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\version.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\nvldumdx.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\nvldumdx.dll'. 
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\nvwgf2umx.dll'. 
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. Symbols loaded.
The thread 0xb3b0 has exited with code 0 (0x0).
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\NvCamera\NvCameraAllowlisting64.dll'. 
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_48f43c6897115490\NvCamera\NvCameraAllowlisting64.dll'
'DXILibrary.pShaderBytecode.exe' (Win32): Loaded 'C:\Windows\System32\dxilconv.dll'. Symbols loaded.
'DXILibrary.pShaderBytecode.exe' (Win32): Unloaded 'C:\Windows\System32\dxilconv.dll'
D3D12 ERROR: ID3D12Device::CreateStateObject: Hash check failed for DXILibrary.pShaderBytecode: 0x000001968A60DF80. A typical cause of this is unsigned bytecode. To enable signing by the compiler, ensure DXIL.dll is next to DxCompiler.dll. [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]
Exception thrown at 0x00007FFF8B694B59 in DXILibrary.pShaderBytecode.exe: Microsoft C++ exception: _com_error at memory location 0x000000043472E9D8.
Exception thrown at 0x00007FFF8B694B59 in DXILibrary.pShaderBytecode.exe: Microsoft C++ exception: _com_error at memory location 0x000000043472E9F8.
Exception thrown at 0x00007FFF8B694B59 in DXILibrary.pShaderBytecode.exe: Microsoft C++ exception: char at memory location 0x000000043472ED98.
Unhandled exception at 0x00007FFF8B694B59 in DXILibrary.pShaderBytecode.exe: Microsoft C++ exception: char at memory location 0x000000043472ED98.

**Comment by ganluo960214** [comment]
is a bug? Exception thrown at 0x00007FFF8B694B59

**Comment by golikeri** [comment]
Hi, I am getting same error. How did you resolve it?
