### ISSUE TITLE
MIT license still referenced in repo

### ISSUE THREAD

**Issue by mgetzbw** [Microsoft/DirectXShaderCompiler#37]
The MIT license is still in the repo root and referenced in the readme. For consistency sake that should be removed unless the MIT license is compatible with the existing LLVM license. It would be better overall if it was using a single license though.

**Comment by marcelolr** [comment]
Michael, I currently believe this is OK but I'm getting additional confirmation. Stay tuned, and thanks for bringing up your concerns.

**Comment by marcelolr** [comment]
Quick update - still on this. No intention to let this languish.
