### ISSUE TITLE
[SPIR-V] Assertion in DescriptorScalarReplacement::CreateReplacementVariable

### ISSUE THREAD

**Issue by nickyc95** [microsoft/DirectXShaderCompiler#3705]
Hi,

When running some shaders through the latest release of DXC (April 2021 v1.6.2104) I am hitting an assert inside of `DescriptorScalarReplacement::CreateReplacementVariable` during the optimization pass.

(This may be a SpirvTools issue rather than DXC..)

Running the following simplified shader through DXC.exe or the library using this command arg:

`dxc.exe -E main -T ps_6_0 -spirv -fspv-reflect -fspv-flatten-resource-arrays test_ps.hlsl`

```
Texture2D g_testTextures[2];

float4 main( float4 vPixelPos : SV_Position ) : SV_Target
{
	const float4 sample1 = g_testTextures[ 0 ].Load( uint3( vPixelPos.xy, 0 ) );
	float4 result = sample1;
	
	return result;
}
```

Results in the following assertion:
![image](https://user-images.githubusercontent.com/7304264/115690633-25ffc980-a355-11eb-8ab4-3c2aed87b083.png)

It appears to be being caused by using the combination of `-fspv-reflect`, `-fspv-flatten-resource-arrays` and texture arrays, using them separately allows it to compile fine.

Thanks

**Comment by kuhar** [comment]
Thanks for a detailed bug report, @nickyc95. I'm looping in SPIR-V folks.
