### ISSUE TITLE
SM6.6 Payload Access Qualifiers not reporting certain reads/writes

### ISSUE THREAD

**Issue by simco50** [microsoft/DirectXShaderCompiler#3707]
When using PAQ, initializing the payload data with an initializer list is not seen as a 'write'.
```
Payload p = { 0 }; // doesn't count as write

Payload p;
p.Foo = 0; // counts as write
```

Also when doing "+=" on a member, it's not seen as a 'read'
```
int a = 0;
a += p.Foo; // not seen as a read -> Compile error

int a = 0;
int b = p.Foo; // seen as read - good :) 
int a += b;
```

Unless I misunderstand the documentation, this seems like a bug?

Also reported in the DX Discord. For reference: https://discord.com/channels/590611987420020747/590965930658496690/835181942650437653

Thanks,
Simon

**Comment by pacxx** [comment]
Thanks for the report. This is indeed a bug, working on a fix. 

--Michael

**Comment by pacxx** [comment]
Opend https://github.com/microsoft/DirectXShaderCompiler/pull/3755

**Comment by simco50** [comment]
Excellent, thank you!
