### ISSUE TITLE
[SPIR-V] Compile error when using asuint on StructuredBuffer's Load function

### ISSUE THREAD

**Issue by lukaszlipski** [microsoft/DirectXShaderCompiler#3717]
### Title
[SPIR-V] Compile error when using asuint on StructuredBuffer's Load function

### Functional impact
When using asuint on StructuredBuffer<float4> Load's result, the dxc fails to compile the shader.
The same example works fine when StructuredBuffer<float4> is replaced with Buffer<float4>.
When generating DXIL instead of SPIR-V, there is no issue.

### Minimal repro steps
```
StructuredBuffer<float4> input;
[numthreads(64,1,1)]
void main(uint3 dtID : SV_DispatchThreadID)
{
	uint4 val = asuint(input.Load(dtID.x));
}
```
### Expected result
The shader should compile and bits should be reinterpreted to uint4, similarly to how it works for Buffer<float4>

### Actual result
_fatal error: generated SPIR-V is invalid: Pointer can only be converted to another pointer or int scalar: Bitcast
  %34 = OpBitcast %v4uint %33_

_note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible_

### Further technical details
http://shader-playground.timjones.io/8567033107b88276c94b2e7bd05f6662

**Comment by jaebaek** [comment]
@lukaszlipski Thank you for report this issue. We will take a look!
