### ISSUE TITLE
Shader compiler errors on japanese/korean/russian OS

### ISSUE THREAD

**Issue by vanessaschueller** [microsoft/DirectXShaderCompiler#3720]
It looks like compiling shaders produces issues on OSs with languages containing special characters, like japanese/korean/russian,... 
Some of our customers get shader compiling errors when using japanese/korean/russian... settings.

This is the resulting message they get:
"Viewport: Shader compile error occurred. Using fallback rendering for object: Hip
Error 0x80070459: Unicode 文字のマッピングがターゲットのマルチバイト コード ページにありません。 [win_com.h(40)]"

Usually the shader should not contain any special characters.

This is the way our shader code is encoded:

ComPtr\<IDxcBlobEncoding\> pSource;
pUtils->CreateBlob(code, (UINT32)value, CP_UTF8, pSource.GetAddressOf());

**Comment by gracejennings** [comment]
Thanks for the report! Previously released versions of the compiler have an issue where it may interpret files without BOMs using the application codepage. 

In PR #4109 we made UTF-8 the default for source and included files, so it should no longer default to a different encoding for files without BOMs. We also made a change to the `-encoding` option to set a default encoding for all files without BOMs.  These changes are not included in the most recent release, but they are in the latest build of dxcompiler.dll from the artifacts zip file on AppVeyor here:

- https://ci.appveyor.com/project/dnovillo/directxshadercompiler/builds/43047800/job/1coka50fub498jhx/artifacts

Please try with the latest build and let us know if the error resolves.
