### ISSUE TITLE
[SPIR-V] [outputcontrolpoints(0)] or missing outputcontrolpoints Hull stage attribute crash the compiler (works with DXIL backend)

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#3733]
### Title
[SPIR-V] [outputcontrolpoints(0)] or missing outputcontrolpoints Hull stage attribute crash the compiler (works with DXIL backend)

### Functional impact
Cannot produce hull shaders that don't have any control point output (e.g. when only patch data is needed for the domain stage)

### Minimal repro steps
1. Compile the following shader with `dxc.exe -T hs_6_0 -E Hull -spirv repro_shader.txt`:
[repro_shader.txt](https://github.com/microsoft/DirectXShaderCompiler/files/6414759/repro_shader.txt)
or do `dxc.exe -T hs_6_0 -E Hull -spirv repro_shader_no_attribute.txt`
[repro_shader_no_attribute.txt](https://github.com/microsoft/DirectXShaderCompiler/files/6414789/repro_shader_no_attribute.txt)

### Expected result
Compilation succeeds with control point output count being zero

### Actual result
Compiler crashes with output:
`Internal compiler error: access violation. Attempted to read from address 0x0000000000000020`

### Further technical details
Used DXC release v1.6.2104 (e09a454)

**Comment by jaebaek** [comment]
@Dredhog, Thank you for reporting this issue. We will take a look.

**Comment by sudonatalie** [comment]
@Dredhog Do you happen to have any additional context on how you intend to use zero control points in hull shaders, or is this simply an issue to report a crash (never correct) and mismatch with the DXIL backend (undesirable)?

Given that Vulkan doesn't allow zero as the number of output vertices (https://docs.vulkan.org/spec/latest/chapters/pipelines.html#VUID-VkPipelineShaderStageCreateInfo-stage-00713) and it looks like the D3D docs might also suggest it's invalid (https://learn.microsoft.com/en-us/windows/win32/direct3d11/direct3d-11-advanced-stages-tessellation#hull-shader-stage) I'm thinking the correct solution might be to fail gracefully for both backends.
