### ISSUE TITLE
[SPIR-V] Zero as control point template argument for InputPatch Hull input fails validation and asks to report a bug

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#3734]
### Title
Zero as control point template argument for InputPatch Hull input fails validation and asks to report a bug

### Functional impact
Compilation fails with DXC asking to file a bug

### Minimal repro steps
1. Compile the following shader with `dxc.exe -T hs_6_0 -E Hull -spirv repro_shader.txt`
2. Compile the same shader for the DXIL backend `dxc.exe -T hs_6_0 -E Hull repro_shader.txt`
[repro_shader.txt](https://github.com/microsoft/DirectXShaderCompiler/files/6414845/repro_shader.txt)

### Expected result
DXC catches the error before validation and produces a user-friendly error message (with line numbers etc.)

### Actual result
SPIR-V backend fails validation and asks to report a bug:
```
fatal error: generated SPIR-V is invalid: OpTypeArray Length <id> '11[%uint_0]' default value must be at least 1: found 0
  %_arr_ControlPoint_uint_0 = OpTypeArray %ControlPoint %uint_0

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```
DXIL backend fails validation:
```
error: validation errors
repro_shader_no_attribute.txt:15: error: When HS input control point count is 0, no input signature should exist.
Validation failed.
```

### Further technical details
Used DXC release v1.6.2104 (e09a454)

**Comment by jaebaek** [comment]
@Dredhog, Thank you for reporting this issue. So .. it is a SPIR-V issue, right? We will take a look.

**Comment by Dredhog** [comment]
I saw it as an issue with both backends, but I guess only the SPIR-V backend asks to report a bug 🤷
