### ISSUE TITLE
[SPIR-V] Using very large vert/hull/domain IO produce a silent compiler crash (works with DXIL backend)

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#3735]
### Title
[SPIR-V] Using very large vert/hull/domain IO produce a silent compiler crash (works with DXIL backend)

### Functional impact
Accidentally having too much data in stage IO will crash the compiler without a clear indication of what happened.

### Minimal repro steps

1. Compile the following shader with either of:
 `dxc.exe -T vs_6_0 -E Vert-spirv repro_shader.txt`
 `dxc.exe -T hs_6_0 -E Hull -spirv repro_shader.txt`
 `dxc.exe -T ds_6_0 -E Domain -spirv repro_shader.txt` 
[repro_shader.txt](https://github.com/microsoft/DirectXShaderCompiler/files/6414941/repro_shader.txt)

### Expected result
The SPIR-V backend should produce user facing errors like the DXIL backend does:
```
repro_shader.txt:21:1: error: Failed to allocate all input signature elements in available space.
ControlPoint Hull (InputPatch<ControlPoint,13> v, uint id : SV_OutputControlPointID) { return v[id]; }
^
repro_shader.txt:21:1: error: Failed to allocate all output signature elements in available space.
```

### Actual result
The SPIR-V backend crashes silently

### Further technical details
Used DXC release v1.6.2104 (e09a454)

**Comment by jaebaek** [comment]
@Dredhog, Thank you for reporting this issue. We will take a look.

**Comment by Keenuts** [comment]
Hello!

Taking a look at this issue.

The root cause if quite funny:
```
1805   /// Maximum number of locations supported
1806   // Typically we won't have that many stage input or output variables.
1807   // Using 64 should be fine here.
1808   const static uint32_t kMaxLoc = 64;
```

I'll see how to make this variable depending on the actual number of input params.
