### ISSUE TITLE
[SPIR-V] Declaring SV_POSITION not as float4 produces validation errors and asks to report a bug

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#3736]
### Title
Declaring SV_POSITION not as float4 results in validation errors and asks to report a bug

### Functional impact
Accidentally declaring `SV_POSITION` as something other than `float4` (e.g. `float3`, `uint4` etc.) produces a validation error asking to report a bug instead of producing a user-facing error message with line information. This affects the last stage of the vertex pipeline, so vertex/domain and possibly geometry shaders (didn't actually test geometry shaders).

### Minimal repro steps

1. Compile the following shader with `dxc.exe -T vs_6_0 -E Vert repro_shader.txt` (or with `dxc.exe -T vs_6_0 -E Vert -spirv repro_shader.txt` for the SPIR-V backend)

```
float3  Vert () : SV_Position
{
    return 1;
}
```

### Expected result
Compiler produces a user-facing error message with line information before going on to validation

### Actual result
Compiler produces validation errors.
For the DXIL backend:
```
error: validation errors
error: SV_Position must be float4.
repro_shader.txt:1: error: Not all elements of SV_Position were written.
Validation failed.
```
for the SPIR-V backend:
```
fatal error: generated SPIR-V is invalid: [VUID-Position-Position-04321] According to the Vulkan spec BuiltIn Position variable needs to be a 4-component 32-bit float vector. ID <2> (OpVariable) has 3 components.
  OpStore %gl_Position %6

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

### Further technical details
Used DXC release v1.6.2104 (e09a454)

**Comment by jaebaek** [comment]
@Dredhog, Thank you for reporting this issue. We will take a look.
