### ISSUE TITLE
Texture gather offsets must be immediate values

### ISSUE THREAD

**Issue by Joshua-Ashton** [microsoft/DirectXShaderCompiler#3738]
There are currently titles shipping with shaders which contain non-constant texture gather offsets, such as Horizon Zero Dawn.

As of 3468e549d85ac51f39cccc1f7ce8a4c7568d1fd7, DXC has regressed to no longer allowing non-constant offsets for texture gather operations which stops some shaders in some games from compiling.

I don't think this is intentional, I think the intent was to keep this functionality but to prepare for the new Imm constant offset variants in the future.

```
error: Offsets to texture access operations must be immediate values. 
        res += Tex2D.GatherCmp(Samp, UV.xy, UV.z, off);
```

All D3D12 capable hardware supports non-constant offsets for texture gather operations as this was a feature in D3D11. (see Gather4PO)

Below is a hlsl shader to reproduce the issue, and the DXIL I'd expect to see.

[texture-gather-cmp.zip](https://github.com/microsoft/DirectXShaderCompiler/files/6415056/texture-gather-cmp.zip)

The same issue also happens with GatherRed.

Tested with latest release and master, both are borked.

**Comment by pow2clk** [comment]
Hi @Joshua-Ashton,

Thanks for bringing up the shaders that make use of variable offsets. Let me clarify a few things.

The result you are experiencing is not an unintended effect of a forthcoming variant. It is the intended behavior. The use of an internal immediate only opcode was a convenience to adapt it to existing code that previously made no distinction and the DXIL format which didn't acknowledge any difference.

The intent of this change was to bring the existing single offset intrinsic in line with its documentation, which disallows variable offsets. The 4 offset intrinsics continue to allow variable offsets as it ever did. As a workaround, these operations could be converted to the [4  offset equivalents](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/t2d-gatherred-s-float-int2-int2-int2-int2-).

Therein lies the rub. There's little benefit to sticking to the docs to inconvenience authors and break existing shaders. After pushback here and elsewhere and some internal discussion, we've decided to revert the change.

**Comment by Joshua-Ashton** [comment]
Cool, thanks for the info.

I was not aware of the 4 offset equivalents at all actually.
FXC did not require this in D3D11 for Gather4PO output either.
