### ISSUE TITLE
DXC does not emit CheckAccessFullyMapped for Tiled Resources

### ISSUE THREAD

**Issue by jholewinski** [Microsoft/DirectXShaderCompiler#377]
Take for example the following shader:

```c++
RWBuffer<float4> g_buffer;
RWBuffer<uint> g_result;

[numthreads(1, 1, 1)]
void cs_main()
{
    uint res;
    
    float4 data = g_buffer.Load(0, res);

    g_result[0] = res;
}
```

When I compile this shader, the result of dx.op.bufferLoad is fed directly into dx.op.bufferStore without a dx.op.checkAccessFullyMapped:

```llvm
define void @cs_main() {
entry:
  %g_result_UAV_buf = call %dx.types.Handle @dx.op.createHandle(i32 57, i8 1, i32 1, i32 1, i1 false)  ; CreateHandle(resourceClass,rangeId,index,nonUniformIndex)
  %g_buffer_UAV_buf = call %dx.types.Handle @dx.op.createHandle(i32 57, i8 1, i32 0, i32 0, i1 false)  ; CreateHandle(resourceClass,rangeId,index,nonUniformIndex)
  %BufferLoad = call %dx.types.ResRet.f32 @dx.op.bufferLoad.f32(i32 68, %dx.types.Handle %g_buffer_UAV_buf, i32 0, i32 undef)  ; BufferLoad(srv,index,wot)
  %0 = extractvalue %dx.types.ResRet.f32 %BufferLoad, 4
  call void @dx.op.bufferStore.i32(i32 69, %dx.types.Handle %g_result_UAV_buf, i32 0, i32 undef, i32 %0, i32 %0, i32 %0, i32 %0, i8 15)  ; BufferStore(uav,coord0,coord1,value0,value1,value2,value3,mask)
  ret void
}
```

If I compile with FXC, I get the expected check_access_fully_mapped:

```
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_uav_typed_buffer (float,float,float,float) u0
dcl_uav_typed_buffer (uint,uint,uint,uint) u1
dcl_temps 1
dcl_thread_group 1, 1, 1
ld_uav_typed_s_indexable(buffer)(float,float,float,float) null, r0.x, l(0, 0, 0, 0), u0.xyzw
check_access_fully_mapped r0.x, r0.x
store_uav_typed u1.xyzw, l(0,0,0,0), r0.xxxx
ret
```

**Comment by tex3d** [comment]
This HLSL usage is supposed to be illegal IIRC.  You should be calling CheckAccessFullyMapped() before using or storing the value.  That said, it appears that fxc will call this for you in this situation, though I don't know if it works for every situation.

We should fix DXIL validation to make sure the value is always used in the dx.op.checkAccessFullyMapped, and possibly mimic fxc's behavior for compatibility.

Do you have any idea how common this high level usage without the intrinsic is?

**Comment by jholewinski** [comment]
> Do you have any idea how common this high level usage without the intrinsic is?

I really couldn't say. This was found by some directed testing I was doing, so I can't even point to a real-world shader.

**Comment by python3kgae** [comment]
Fixed with https://github.com/Microsoft/DirectXShaderCompiler/commit/d8cefeb1ba79feaf6dbfeb2deaade73a46d9b6a2
