### ISSUE TITLE
[SPIR-V] Device Buffer Address- feature

### ISSUE THREAD

**Issue by Eichenherz** [microsoft/DirectXShaderCompiler#3772]
Hello ! 
In Vulkan it's possible to query the gpu address of a buffer and pass that as a uint64_t, pretty much like a pointer in C/C++.
```cpp
inline u64 VkGetBufferDeviceAddress( VkDevice vkDevice, VkBuffer hndl )
{
	VkBufferDeviceAddressInfo deviceAddrInfo = {};
	deviceAddrInfo.sType = VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO;
	deviceAddrInfo.buffer = hndl;

	return vkGetBufferDeviceAddress( vkDevice, &deviceAddrInfo );
```
```glsl
layout( buffer_reference, scalar, buffer_reference_align = 4 ) readonly buffer mtl_ref{
	material_data materials[];
};
layout( buffer_reference, scalar, buffer_reference_align = 4 ) readonly buffer light_ref{
	light_data lights[];
};

.....................

void main()
{
	material_data mtl = mtl_ref( g.addr + g.materialsOffset ).materials[ mtlIdx ];

	vec4 baseCol = texture( sampler2D( sampledImages[ nonuniformEXT( mtl.baseColIdx ) ], samplers[ nonuniformEXT( 0 ) ] ), uv );
	...................
}
```

As far as I know, DX12 doesn't have this kind of capabilities, but Vulkan does, and since compiling HLSL to SPIR-V is possible, even used in the game industry, it would be very nice to have this. ( Maybe even in DX12, why not ? )  
Thanks !

**Comment by StarsX** [comment]
I think the key point is HLSL hasn’t supported 64-bit indexing for raw buffer yet.

**Comment by sudonatalie** [comment]
This is now supported by [`vk::RawBufferLoad`](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst#rawbufferload-and-rawbufferstore) when targeting SPIR-V from HLSL!
