### ISSUE TITLE
Unused resource bindings removed with optimization off.

### ISSUE THREAD

**Issue by Slagh** [microsoft/DirectXShaderCompiler#3792]
Hi there, we have a toolchain that uses the reflection information from a DXIL compile of a shader in combination with a SPIR-V compile. This helps us bridge the DirectX style register spaces (buffer/texture/sampler/unordered) and their independent indices, with SPIR-V, which does not have register spaces (and so needs new indices, etc.).

At some point, we have noticed that DXC began removing unused resources from the reflection information available from the DXIL compile, even when we have optimizations off (-O0). Due to various differences in how DXIL and SPIR-V are produced, sometimes we find that (for example) SPIR-V does not remove a resource that is not referenced, and if the DXIL _does_, then our toolchain gets upset.

* Is there a way to prevent unused resources from being removed from the reflection data?
* Should we be relying on DXC to produce this reflection data in the future? (I wouldn't want to maintain another parser)
* Technically we don't care about the DXIL at all, only the reflection data - so would it be viable to have a mode of DXC "optimized" to produce the reflection data, while skipping any steps that don't contribute to it?

Cheers!

**Comment by chaoticbob** [comment]
Hi,

The reflection information between DXIL and SPIR-V will most likely different in a sucfficiently complex shader and there is not a straight forward way to align them. IIRC, unused resource removal happens for DXIL using the LLVM facilities whereas this happens for SPIR-V using SPIRV-Tools. Optimization is handled differently for both and may occur at different phases of the code gen. There's also some history on the SPIR-V side on what does/doesn't get removed as far as resources go. The net result is that it's not really likely for either to guarantee that the reflection data will perfectly match the other.

Cheers,
Hai

**Comment by Slagh** [comment]
Thanks Hai for your reply,

We understand that we can't align the results of the DXIL and SPIR-V compiles.

Could you speak to the feasibility of adding an option that prevents stripping anything from reflection data, even if it is unreferenced by the final DXIL?

Thanks,
Alex Lindsay

**Comment by chaoticbob** [comment]
Hi Alex,

Sorry for the delay in reply again. Someone from the Microsoft team can better answer your question since the DXIL and SPIR-V teams work indepdendent of each other. 

@tex3d Can you point us to the right person?

Cheers,
Hai

**Comment by s-perron** [comment]
Does the `-fcgl` option help you? The issue is that the code will not even be "legalized", so the resulting spir-v will likely fail validation. If all you want is the reflection info you might be able to do `-fcgl -Vd`.

**Comment by Slagh** [comment]
Thanks for your reply @s-perron,

After finding the [docs](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst#legalization-optimization-validation) on `-fcgl` (which is not printed by `dxc.exe /?` (1.7 - 1.7.0.3921 (58d305353))) it looks like that also applies only while generating SPIR-V.

The original issue is that the DXIL generation is eliminating reflection information, since we are seeking the DirectX register space + index resource bindings, and so unfortunately none of these flags will help.

An option much like `-fspv-preserve-bindings` for the DXIL compile would be great!

Cheers, Alex

**Comment by s-perron** [comment]
@llvm-beanz Chris, I'll leave it to you to decide what to do.  They want something on the dxil side.
