### ISSUE TITLE
Cannot initialize AppendStructuredBuffer from ResourceDescriptorHeap 

### ISSUE THREAD

**Issue by Cheaterdev** [microsoft/DirectXShaderCompiler#3813]
Hi! There is an issue with initializing AppendStructuredBuffer from ResourceDescriptorHeap:

```
[numthreads(1, 1, 1)]
void CS()
{
    AppendStructuredBuffer<uint3> buf = ResourceDescriptorHeap[0];
    buf.Append(uint3(1, 2, 3));
}
```
> test.hlsl:5:5: error: cannot map resource to handle.
>     buf.Append(uint3(1, 2, 3));
>     ^
> 
While other resources initialization works fine(RWStructuredBuffer, Texture2D... etc)

DXIL version 1.6, no additional arguments, "cs_6_6" target

**Comment by pow2clk** [comment]
Can't repro anymore. Please refile if you find otherwise
