### ISSUE TITLE
Cannot initialize member array from ResourceDescriptorHeap

### ISSUE THREAD

**Issue by Cheaterdev** [microsoft/DirectXShaderCompiler#3814]
Hi! There is an isse with initializing array of resources from ResourceDescriptorHeap:
```
struct A
{
    RWTexture2D<float4> tex_array[3];
};

A create()
{
    A a;
    a.tex_array[0] = ResourceDescriptorHeap[0];
    a.tex_array[1] = ResourceDescriptorHeap[1];
    a.tex_array[2] = ResourceDescriptorHeap[2];

    return a;
}

static const A a = create();

[numthreads(64, 1, 1)]
void CS(
    uint3 groupID       : SV_GroupID,
    uint3 dispatchID : SV_DispatchThreadID,
    uint3 groupThreadID : SV_GroupThreadID,
    uint  groupIndex : SV_GroupIndex
)
{
    a.tex_array[0][groupThreadID.xy] = 1;
}
```

> test.hlsl:27:5: error: opcode 'CreateHandleForLib' should only be used in 'Library'.
> note: at '%5 = call %dx.types.Handle @dx.op.createHandleForLib.dx.types.Handle(i32 160, %dx.types.Handle %4)' in block '#0' of function 'CS'.
> Function: dx.hl.cast.handleToRes.%"class.RWTexture2D<vector<float, 4> >" (i32, %dx.types.Handle): error: External function 'dx.hl.cast.handleToRes.%"class.RWTexture2D<vector<float, 4> >" (i32, %dx.types.Handle)' is not a DXIL function.
> Function: dx.hl.cast.handleToRes.%"class.RWTexture2D<vector<float, 4> >" (i32, %dx.types.Handle): error: Function 'dx.hl.cast.handleToRes.%"class.RWTexture2D<vector<float, 4> >" (i32, %dx.types.Handle)' uses resource in function signature.
> Validation failed.

While this one works:

```
struct A
{
    RWTexture2D<float4> tex_array0;
    RWTexture2D<float4> tex_array1;
    RWTexture2D<float4> tex_array2;
};

A create()
{
    A a;
    a.tex_array0 = ResourceDescriptorHeap[0];
    a.tex_array1 = ResourceDescriptorHeap[1];
    a.tex_array2 = ResourceDescriptorHeap[2];

    return a;
}

static const A a = create();

[numthreads(64, 1, 1)]
void CS(
    uint3 groupID       : SV_GroupID,
    uint3 dispatchID : SV_DispatchThreadID,
    uint3 groupThreadID : SV_GroupThreadID,
    uint  groupIndex : SV_GroupIndex
)
{
    a.tex_array0[groupThreadID.xy] = 1;
}
```
DXIL version 1.6, no additional arguments, "cs_6_6" target

**Comment by pow2clk** [comment]
I cannot reproduce this with the latest source. Please reopen if you can.
