### ISSUE TITLE
The texture of metal and gl is upside down

### ISSUE THREAD

**Issue by jellychen** [microsoft/DirectXShaderCompiler#3815]
I am developing a cross-platform renderer, using hlsl and hope to support gles and metal and vulkan. I have a little problem now.

Use a texture uploaded by an image. In metal and gl, the same pixels can be obtained with the same texture coordinates, but if the texture is the fbo texture, it seems to be upside down?

How should I deal with this situation.

I see that there are other people here who have raised this question, but I still don’t understand the principle

**Comment by MarkIngramUK** [comment]
This is not a compiler issue. See https://stackoverflow.com/a/17779593/986.

**Comment by pow2clk** [comment]
@MarkIngramUK is correct. This is a long-standing discrepancy between the APIs. I swear we are trying our best to get on the same page, but the gravity of legacy is strong in both directions 😅
