### ISSUE TITLE
Assertion when calling atan2() with vector

### ISSUE THREAD

**Issue by ben-clayton** [microsoft/DirectXShaderCompiler#3824]
[According to the HLSL documentation](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-isnan) `atan2()` should accept parameters of type scalar or a vector:

Name | Template Type | Component Type | Size
-- | -- | -- | --
y | same as input&nbsp;x | float | same dimension(s) as input&nbsp;x
x | scalar,&nbsp;vector, or&nbsp;matrix | float | any
ret | same as input&nbsp;x | float | same dimension(s) as input&nbsp;x

However attempting to call `atan2()` with a vector produces the following ICE:

```hlsl
void main() {
  float3 _ = atan2(float3(0.0f, 0.0f, 0.0f), float3(0.0f, 0.0f, 0.0f));
}
```

```bash
> ./dxc test.hlsl -Tps_6_0
Internal Compiler error: cast<X>() argument of incompatible type!
```

This might be a regression, as the version of DXC used by shader compiler [appears to handle this](http://shader-playground.timjones.io/fe1cc117f9207abdfeba4617e320a297) (`Updated from trunk on 2020-12-16`).

**Comment by jaebaek** [comment]
Fixed by #3908
