### ISSUE TITLE
[SPIR-V] DXC 1.6 SpirV complains about dynamic offset passed to SampleLevel

### ISSUE THREAD

**Issue by manas-kulkarni** [microsoft/DirectXShaderCompiler#3826]
After updating to the 1.6 release, we get a compiler error when generating the SpirV about dynamic offset passed to SampleLevel even though all code calling that function pass compile-time constants for offset.
Not sure if this was something missing from previous DXC versions or regression.

Code
```
float2 SampleMap(float2 tc, const int2 offset)
{
    return map.SampleLevel(tc, offset);
}

void main()
{
    float2 uvs = CalculateUVs();
    float2 mapNegX = SampleMap(uvs, int2(-1, 0));
    float2 mapPosX = SampleMap(uvs, int2(1, 0));
}
```

**Comment by jaebaek** [comment]
@manas-kulkarni Thank you for reporting this issue. It is a known issue for the last official release version of DXC. We fixed it and it should work correctly with the latest tot build i.e., https://github.com/microsoft/DirectXShaderCompiler#downloads.
Please let me know if the tot verion of DXC does not work.

**Comment by manas-kulkarni** [comment]
Works with the latest tot build. Thanks
