### ISSUE TITLE
[SPIR-V] DXC SpirV crashing for this shader

### ISSUE THREAD

**Issue by manas-kulkarni** [microsoft/DirectXShaderCompiler#3831]
Getting an access violation when compiling the attached pixel shader to spirv. Getting the crash with the latest build artifact as well as the latest release (1.6)
The problem is related to the conditional initialization of a sampler.

```
SamplerState samplerArray[8];
Texture2D<float2> heightmap;
static SamplerState materialSampler = ( ( 1 ) ? samplerArray[2] : samplerArray[3] ) ; 

float2 SampleMap(float2 tc)
{
	return heightmap.SampleLevel(materialSampler, tc, 0.0f);
}

float4 main(float2 tc : TEXCOORD0) : SV_Target0
{
	return float4(tc.xy, SampleMap(tc));
}
```

Compiled using
```dxc.exe -spirv /T ps_6_0 .\test.hlsl```

**Comment by jaebaek** [comment]
@manas-kulkarni Thank you for reporting this issue. We will take a look.

**Comment by manas-kulkarni** [comment]
Any update here?

**Comment by sudonatalie** [comment]
This is now fixed. Thanks for reporting @manas-kulkarni !
