### ISSUE TITLE
Missing information when reading a shader pdb with the DIA interface.

### ISSUE THREAD

**Issue by DeChambord** [microsoft/DirectXShaderCompiler#3834]
When I try to extract some info through DIA from a shader PDB, the DIA structures seem ok but I get some empty values, including the source code and the compilation arguments. I can see them when opening the pdb with a hex editor.

It works when I use older dxcompiler.dll (v 1.04.1907) to compile. The dxcompiler.dll used for extraction doesn't seem to matter, so I think the difference is introduced by the compilation.

Here is the shader :
```
float4 main() : SV_Target {
  return float4(0,0,0,0);
}
```
compiled with :  `dxc.exe /Zi /Qstrip_debug /Fd test.pdb /Tps_6_1 shader.hlsl`

When loading test.pdb :
In the "Symbols" DIA table "hlslArguments" is empty, but "hlslEntry" and "hlslTarget" are correct. The "InjectedSource" DIA table have entries but get_source returns empty strings.

Working dxcompiler.dll versions:
        v1.04.1907

Non working:
	v1.06.2104.52
	v1.06.0.3175

**Comment by jkrebbers** [comment]
Hi,
Could we get some information on this if possible?
It appears PIX is able to extract the source code.

**Comment by jlaumon** [comment]
Yes, just basic things like source, arguments, etc. Getting the sources with DIA always gives an empty string now 🤷‍♂️
We switched to IDxcPdbUtils and that works.

**Comment by damyanp** [comment]
Customer has a workaround.
