### ISSUE TITLE
DXC should statically link in the CRT.

### ISSUE THREAD

**Issue by ScatteredRay** [microsoft/DirectXShaderCompiler#3842]
Statically linking in the CRT in the distributed binaries would help with build environments and distribution.

Specifically, while running dxc.exe from [here](https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.6.2104) on a fresh install of Windows (reproduces also in Windows Sandbox) the executable terminates and returns "-1073741515" or "0xc0000135" which appears to correspond to "STATUS_DLL_NOT_FOUND" then installing the VC redist from [here](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) solves the issue.

**Comment by pow2clk** [comment]
I'm afraid we are sensitive to disk size and other concerns that make this undesirable. If you want to suggest a build option that enables this, we'll happily consider it.
