### ISSUE TITLE
[SPIR-V] Auto-packing of outputs using "Component" decoration

### ISSUE THREAD

**Issue by scottkircher** [microsoft/DirectXShaderCompiler#3870]
I had posted this issue awhile ago:

https://github.com/microsoft/DirectXShaderCompiler/issues/2618

About the fact that the SPIR-V backend for DXC does not pack outputs/interpolators the way that the DXIL backend does, so Vulkan shaders end up using more outputs/interpolators and may exceed hardware limits where DX12 shaders do not. We are, in particular, hitting this issue with complex tessellation shaders that have many outputs between hull (tessellation control) and domain (tessellation evaluation) shaders.

In that thread, it was suggested that the issue could be fixed by use of the SPIR-V "Component" decoration, but as far as I'm aware, no action has been taken to that effect.

I attempted to revive the original issue, but received no response, so I'm posting a new issue. This is becoming more important to us to have fixed now so I am hoping someone can take a look. Thanks!

**Comment by jaebaek** [comment]
Sorry for being late to handle this issue. After carefully reading what happened, I have questions about packing the signature supported by the DXIL code gen:
1. Are `-pack_optimized` and `-pack_prefix_stable` (or `-pack-optimized` / `-pack-prefix-stable`) the flags to enable the packing?
2. I am not versed on the rule of packing the signature in DXIL. I checked a few unittests like [tools/clang/test/HLSLFileCheck/hlsl/compile_options/pack_optimized/optimized.hlsl](https://github.com/microsoft/DirectXShaderCompiler/tree/master/tools/clang/test/HLSLFileCheck/hlsl/compile_options/pack_optimized/optimized.hlsl), but the packing rule is not clear to me. I want to just use [the existing functions in DXIL code gen](https://github.com/microsoft/DirectXShaderCompiler/blob/master/include/dxc/HLSL/DxilSignatureAllocator.inl#L279). I want to ask you whether following the DXIL's packing rule would have some issues or not.

**Comment by scottkircher** [comment]
1. I believe those are the related flags, however the DXIL backend appears to pack by default without any options specified. We are currently not using those options, so I don't actually know which packing behavior we're getting. But, the interpolators are definitely getting packed. Hopefully you can find in the code where the default is specified.
2. I think following DXIL's packing rule (i.e. reusing the existing packing functionality) would be ideal. We'd like to have consistent behavior between DXIL and SPIR-V, here.

**Comment by jaebaek** [comment]
I will get back here after digging into it more.

**Comment by jaebaek** [comment]
After digging into this issue more, I realized that SPIR-V code gen has a `Location` decoration assignment rule different from the register assignment rule for DXIL code gen, which makes it impossible to reuse the DXIL signature packing.

Since only signatures used between shader stages matter (like the output of VS and the input of PS), I think we can design our own packing rule for SPIR-V code gen. I will prepare a PR with it, but please let me know if you have any concerns.

By the way, I am sorry for taking a little bit long time for this issue. I first checked what DXIL backend does and it was not trivial. (and I now realize that we should create our own .. )

**Comment by scottkircher** [comment]
Thanks for the update. Your plan sounds good.

**Comment by sudonatalie** [comment]
This issue was fixed by #4361.
