### ISSUE TITLE
[SPIR-V] Support for `GL_EXT_buffer_reference` and `GLSL_EXT_spirv_intrinsics` extensions? 

### ISSUE THREAD

**Issue by ghost** [microsoft/DirectXShaderCompiler#3874]
#### About GLSL extensions

I would like to ask for HLSL of these support for extensions from the GLSL. 
- `GL_EXT_buffer_reference`
- `GLSL_EXT_spirv_intrinsics`
These extensions actually cannot be implemented within Shader Model. 

#### About `GL_EXT_buffer_reference`

```hlsl
uint64_t deviceAddress = constants.someDeviceAddress;
SomeStruct structured = RWStructuredBuffer<SomeStruct> ( deviceAddress )[0];
```

Allow conversion from 64-bit number only: 
- `RWByteAddressBuffer`
- `RWStructuredBuffer<T>`

**Comment by jaebaek** [comment]
@helixd-2k18 Thank you for reporting this issue.

**Comment by Eichenherz** [comment]
[https://github.com/microsoft/DirectXShaderCompiler/issues/3772](url)
I also mentioned something similar here. 
Cheers !

**Comment by jiaolu** [comment]
i am intended to work on the "GL_EXT_spirv_intrinsics".

here is the first draft of spec . https://github.com/KhronosGroup/GLSL/pull/157
but the code is already merged in the khronos glslang repo: 

"
commit 65a7fb70547a65410e7372e62f4b22ff389d8f6d
Author: Rex Xu <rex.xu@amd.com>
Date:   Sun Apr 25 16:52:35 2021 +0800
"

**Comment by jiaolu** [comment]
Hi, @jaebaek,
glsl use rather expressive attribute definitions for  "GL_EXT_spirv_intrinsics".

e.g.
**spirv_instruction (extensions = ["SPV_KHR_ray_query"], capabilities = [4471,4478], id = 4473)**
, the "square bracket" in attributes is list item.

hlsl use rather simple , c++ style attribute (https://en.cppreference.com/w/cpp/language/attributes) 

can the hlsl attribute expand its expression, use something like this??

**[[vk::spirv_instruction (extensions = ["SPV_KHR_ray_query"], capabilities = [4471,4478], id = 4473)]]**

**Comment by jaebaek** [comment]
I talked to some people who work on the GL_EXT_spirv_intrinsics spec.
Just personally, I want to review the spec in depth and design the corresponding HLSL intrinsics, but I had other urgent issues at the moment.
Let me take a few days to consider it and get back.

**Comment by jiaolu** [comment]
right, GL_EXT_spirv_intrinsics is a disruptive extension to enable hlsl capabilities of mapping spirv directly.
i figure a lot of current vk attributes ,e.g. vk::binding, vk::builtin can be replaced by the this extension.

**Comment by sudonatalie** [comment]
These extensions are now both supported in DXC when targetting SPIR-V. See [vk::RawBufferLoad and RawBufferStore](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst#rawbufferload-and-rawbufferstore) and [GL_EXT_spirv_intrinsics for SPIR V code gen](https://github.com/microsoft/DirectXShaderCompiler/wiki/GL_EXT_spirv_intrinsics-for-SPIR-V-code-gen) for more details.
