### ISSUE TITLE
dxcompiler.dll crash on startup

### ISSUE THREAD

**Issue by LBeernaert** [microsoft/DirectXShaderCompiler#3886]
Hello, 

I'm trying to compile the latest release ( v1.6.2106) of the dxcompiler with spirv support locally and I keep getting a crash in the code below since `DxcGetThreadMallocNoRef()` returns null.

```C++
// DXCompiler.cpp:30
#ifdef LLVM_ON_WIN32
// operator new and friends.
void *  __CRTDECL operator new(std::size_t size) throw(std::bad_alloc) {
  void * ptr = DxcGetThreadMallocNoRef()->Alloc(size);
  if (ptr == nullptr)
    throw std::bad_alloc();
  return ptr;
}
```
The above crash also happens with the provided binaries. E.g:`dxc --help`

I have configured the build using the following steps:

- utils\hct\hctstart.cmd -x64 <SRC_DIR> <BUILD_DIR>
- utils\hct\hctbuild.cmd  -x64 -s -vs2019 -spirv -Release
- cmake --build <BUILD_DIR> --config Release 

I'm using Visual Studio 2019 v16.10.4.

Is there anything I may have missed or any thoughts on what may be going wrong? 

Kind Regards, 

Leander

**Comment by LBeernaert** [comment]
Sorry for the spam. It seems I may have corrupted my local source copy. Performing a clean clone and build seems to have solved the problem.

**Comment by LBeernaert** [comment]
Reopening as this also happens when I try to use /MT instead of /MD on a clean checkout. Is this perhaps not supported?

**Comment by damyanp** [comment]
Given the age of this we're not going to look further in to it.  Please let us know if this is still impacting you.
