### ISSUE TITLE
[SPIR-V]: issue with shader input parameter capturing in structures

### ISSUE THREAD

**Issue by tiago-rodrigues** [microsoft/DirectXShaderCompiler#3889]
Hi,

we have a large number of shaders in our engine written HLSL, which is used across a number of different platforms.
In order to cope with platforms differences, we have a shader input parameter generator that abstracts how these shader parameters are passed to and accessed in shaders.
The solution we have is based on packing these parameters in global structures that get filled by auto-generated headers and passed around in the shader.
For example the auto-generated shaders would look like something like this:

```
//----
//----
// Header1.hlsl
struct InstancingParams_Constants
{
    int4 offset1;
};
struct InstancingParams_Resources
{
    Buffer<float4> buffer1;
};
struct InstancingParams
{
    InstancingParams_Constants constants;
    InstancingParams_Resources resources;

    Buffer<float4> GetBuffer1() { return resources.buffer1; }
    int4 GetOffset1(){ return constants.offset1; }
};

InstancingParams CreateInstancingParams(InstancingParams_Constants constants, InstancingParams_Resources resources)
{
    InstancingParams i;
    i.constants = constants;
    i.resources = resources;
    return i;
}

//----
// Header2.hlsl
//#include "header1.hlsl"

struct MaterialInstancing_Constants
{
    int4 offset0;
    InstancingParams_Constants params;
};
struct MaterialInstancing_Resources
{
    Buffer<float4> buffer0;

    InstancingParams_Resources params;
};
struct MaterialInstancing
{
    MaterialInstancing_Constants constants;
    MaterialInstancing_Resources resources;

    int4 GetOffset0(){ return constants.offset0; }
    Buffer<float4> GetBuffer0() { return resources.buffer0; }

    InstancingParams GetParams() { return CreateInstancingParams(constants.params, resources.params); }
};

//----
// auto generated global resource bindings
[[vk::binding(0, 6)]] cbuffer MaterialInstancing_cbuffer : register(b0 , space6 ) { MaterialInstancing_Constants MaterialInstancing_constants; }; 
[[vk::binding(1, 6)]] Buffer<float4> MaterialInstancing_Params_buffer1 : register(t1, space6 ); 
[[vk::binding(2, 6)]] Buffer<float4> MaterialInstancing_buffer0 : register(t2, space6 ); 

MaterialInstancing CreateMaterialInstancing()
{
    MaterialInstancing i;
    i.constants =  MaterialInstancing_constants;
    i.resources.buffer0 = MaterialInstancing_buffer0;
    i.resources.params.buffer1 = MaterialInstancing_Params_buffer1;
    return i;
}
```

And then in user code, they only have to instantiate the type of parameters they require and use it as any other structures, ex:

```
static const MaterialInstancing g_MaterialInstancing = CreateMaterialInstancing();

float4 func(InstancingParams params)
{
    return params.GetBuffer1()[params.GetOffset1().x];
}

float4 main() : SV_Target0
{
    float4 val0 = g_MaterialInstancing.GetBuffer0()[g_MaterialInstancing.GetOffset0().x];
    return val0 + func(g_MaterialInstancing.GetParams());
}
```

This ‘capturing’ of the global resources into structures has worked fine on PC platforms for a number of years now (as well as on Stadia and other Vulkan platforms), but we've hit issues with drivers on mobile platforms which appear to not support all of the features of the SPRIV generated by DXC in this case.
Specifically, when we use something like : "g_MaterialInstancing.GetParams().GetOffset1().x", the driver fails to compile SPIRV that looks like:
     
```
       %_ptr_Uniform_MaterialInstancing_Constants = OpTypePointer Uniform %MaterialInstancing_Constants
       %39 = OpAccessChain %_ptr_Uniform_MaterialInstancing_Constants %MaterialInstancing_cbuffer %int_0
       %40 = OpLoad %MaterialInstancing_Constants %39
       %41 = OpCompositeExtract %InstancingParams_Constants %40 0
       %42 = OpCompositeExtract %int %41 0
```

instead of what gets generated (by the seemingly equivalent code) when we use the global parameters directly, like:

```
float4 main() : SV_Target0
{
        float4 val0 = MaterialInstancing_buffer0[MaterialInstancing_constants.offset0.x];;
	return val0 + MaterialInstancing_Params_buffer1[MaterialInstancing_constants.params.offset1.x];   
```

which generates this:
```
       %48 = OpAccessChain %_ptr_Uniform_v4int %MaterialInstancing_cbuffer %int_0 %int_0 %int_2
       %49 = OpLoad %int %48
```

It would be impractical to rewrite the whole user code to use the direct access as above, not to mention the loss of the functionality of being able to capturing a subset of parameters into structures to pass it to other functions (which we use extensively in our shader code base). Also getting mobile driver feature support is hard proposition.
We would like to inquire if there is any functionality in the DXC SPIRV generator (or suggest how to implement it), or even if you suggest using/augmenting external tooling (like spirv-opt) that would automatically flatten the accesses to the global input parameters in order to produce simpler SPIRV that the more restricted drivers would consume?

Sorry is this is a bit of a generic request but we would like to use the output of DXC with minimal transformations as possible in our pipeline across all platforms as past experience of modifying the spirv has proven hard to maintain.

Thanks,
Tiago

**Comment by jaebaek** [comment]
@tiago-rodrigues Thank you for reporting this issue. We will take a look.

**Comment by jaebaek** [comment]
It worries me that we do not have clear rules/conditions to avoid the mobile driver issue.
Is "flattening the accesses to the global input parameters in order to produce simpler SPIRV" an actual solution for the issue?

If it is, we can create a spirv-opt pass and let DXC run the spirv-opt pass when we enable a special flag e.g., `-fspv-flatten-global-input-access`.

**Comment by tiago-rodrigues** [comment]
Hi, we think the 'flattening' would solve a lot of the initial issues we've hit so far, so adding the DXC opt pass to do it would help.

Obtaining concrete information from the vendors regarding these restrictions would definitely be good, for at least one of the major ones we are tying to get more concrete info what could potentially be fixed in the shader compiler driver for future updates, but there is always the case of older phones which wouldn't be able to be updated.

**Comment by jaebaek** [comment]
Ok. The owner of spirv-opt suggested me to try `--reduce-load-size` spirv-opt pass. I want to check the pass with your shader, but I cannot compile yours. Could you please provide me with a minimal reproducible shader that does not report DXC compile errors?

**Comment by tiago-rodrigues** [comment]
Sorry about that, I've updated the original comment with code that actually compiles, I've also attached the same code in a single file here:
[test_shader.hlsl.txt](https://github.com/microsoft/DirectXShaderCompiler/files/7086979/test_shader.hlsl.txt)

**Comment by jaebaek** [comment]
@tiago-rodrigues Could you please check whether https://github.com/microsoft/DirectXShaderCompiler/pull/3931 fixes your issue or not?

**Comment by tiago-rodrigues** [comment]
Hi @jaebaek, it does indeed solve our issues, the newly generated SPIRV now compiles at run-time on drivers where it failed before.
thanks a lot.

**Comment by jaebaek** [comment]
Nice. We can get the code review and submit it next week.
