### ISSUE TITLE
[SPIR-V] Compiler crash when converting between float4x1 and float4

### ISSUE THREAD

**Issue by Devaniti** [microsoft/DirectXShaderCompiler#3893]
### Title
[SPIR-V] Compiler crash when converting between float4x1 and float4

### Functional impact
If your code uses float4x1 it will crash compiler when trying to emit SPIR-V bytecode

### Minimal repro steps
1. Compile the following shader with `dxc.exe -spirv -T cs_6_0 test.hlsl`:

```
[numthreads(1,1,1)]
void main()
{
	float4 var1 = float4(1,2,3,4);
	float4x1 var2 = var1;
}
```

2. Observe output 
```
Internal compiler error: access violation. Attempted to read from address 0x0000000000000000
```

### Expected result
Compiler shouldn't crash and shoud emit valid SPIR-V

### Actual result
Compiler crashes

**Comment by jaebaek** [comment]
Thank you for reporting this issue. We will take a look.
