### ISSUE TITLE
[SPIR-V] how to get cbuffer layout offset info?

### ISSUE THREAD

**Issue by LuciferSweety** [microsoft/DirectXShaderCompiler#3907]
![image](https://user-images.githubusercontent.com/18320190/129527936-c7889670-cb4b-4848-bed6-0175f10743d9.png)
1. Has some interface or function?
2. I used that rules for this devices:
vulkan default;
dx11,12 -fvk-use-dx-layout;
glsl,gles -fvk-use-gl-lalyout;
metal choose ?

**Comment by jaebaek** [comment]
1. SPIR-V delivers the member's Offset information using [OpDecorate](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpDecorate) or `OpMemberDecorate`. You can disassemble your SPIR-V code.
2. If I understand what you mean correctly, "metal" means [MoltenVK](https://github.com/KhronosGroup/MoltenVK), right? I cannot find a document about its memory layout rule .. I would ask them the memory layout rule.

**Comment by LuciferSweety** [comment]
Thank you.
1. I get it;
2. No, I means Mac/IOS shader language 'metal' that spirv code used to transfer target lanuage.(hlsl->spirv[set layout rule]->metal)

**Comment by LuciferSweety** [comment]
There are four layout rules in document.
![image](https://user-images.githubusercontent.com/18320190/129695888-d43dfba9-e911-4da8-8236-5b9c8328a900.png)
rule 1 & 4 for vulkan. rule 2 for dx.  rule 3 for gl.  but can't find for metal.

**Comment by seppala2** [comment]
I think at least SPIRV-Cross keeps the same layout when compiling from SPIR-V to Metal Shading Language, so the rules 1-4 still apply if you use SPIRV-Cross. At least this works for std140 layout, but I would assume it works for the others as well

**Comment by LuciferSweety** [comment]
There are four different offset in document.
![image](https://user-images.githubusercontent.com/18320190/129738864-a5a1a45f-b4ad-43b8-be05-f2e2cb151646.png)
If i want get this offset datas,  what is the rules for mapping?
I guess VK = default,  DX = -fvk-use-dx-layout, GL = -fvk-use-gl-lalyout, Scalar = -fvk-use-scalar-layout.
emm, so Metal = default(relaxed std140) can be works well ?  I'll try.
