### ISSUE TITLE
Internal compiler error with DXC version 1.6.2106.3

### ISSUE THREAD

**Issue by PaoloBaerlocher** [microsoft/DirectXShaderCompiler#3916]
Hello,
when compiling the attached HLSL shader with **DXC version 1.6.2106.3**, I get an internal compiler error.

```
OVERVIEW: HLSL Compiler for Windows
Version: dxcompiler.dll: 1.6 - 1.6.2106.3 (dad1cfc30); dxil.dll: 1.6(101.6.2106.2)

Command line: dxc.exe -T ps_6_0 bugShader.hlsl.txt
Output:
  Internal Compiler error: Invalid OpCode!
  UNREACHABLE executed at D:\agent\_work\8\s\lib\HLSL\HLOperations.cpp:222!
```

**DXC version 1.6.2104.52** also produces a similar error: `"Internal compiler error: LLVM Unreachable"`
But with **DXC version 1.5.2010.6 (b640fa4ba)**, no error was generated, and a valid binary output was produced.

FYI, the attached HLSL shader is the outcome of `spirv_cross` compilation (SPV -> HLSL), which is working fine on
our huge set of shaders, except for this compiler issue. The shader has been manually edited to reduce its length, to ease debugging.

According to my tests, the issue in `bugShader.hlsl.txt` is related to the `float2x2` variable _13331 at line 357.
For example, removing the "_13331 = _13524;"  copy at line 365 avoids the "internal compiler error".

[bugShader.hlsl.txt](https://github.com/microsoft/DirectXShaderCompiler/files/7057058/bugShader.hlsl.txt)

**Comment by pow2clk** [comment]
Hi @PaoloBaerlocher!

Thanks for the report. This internal compiler error report didn't exist in the earlier version of the compiler. As a result, sometimes these errors were hit and the compiler trudged on erroneously. It's likely that the bug that cause this error existed there, but just went unreported.

Regarding the specific error, the binary operator that the compiler is failing to find an opcode for is the comma operator. It's possible that what makes this shader unusual is the use of it with matrix variables, which are a special case in the compiler. Not sure if that helps you work around it at all though.

**Comment by pow2clk** [comment]
For reference, here is a minimalist repro:

```hlsl
float4 main(uint ct : C, float2x2 pmat : M, float2 pvec : V) {
  float2 vec;
  float2x2 mat;
  
  mat = pmat, vec = pvec;

  return 0.0;
}
```
