### ISSUE TITLE
[SPIR-V] How to set bindings like dx type?

### ISSUE THREAD

**Issue by LuciferSweety** [microsoft/DirectXShaderCompiler#3928]
At the function DeclResultIdMapper::decorateResourceBindings() m3(no 'vk::binding' and no ':register' assignment);
Uses the next available binding number in |set|.
The binding number is applied for all resources type. The rules looks like match with the vulkan's rules.
eg: Original hlsl code : Texture  Sampler -> spirv Texture binding is 0;  Sampler binding is 1; 
My target language is hlsl shading model 5.0. The final code like this " Texture : Register(t0, sapce0) ; Sampler : Register(s1, space0) "
I would expect the result like that " Texture : Register(t0, sapce0) ; Sampler : Register(s0, space0) "
What can i do ?
Thanks.

**Comment by sudonatalie** [comment]
Thanks for reporting @LuciferSweety , we'll take a look.

**Comment by sudonatalie** [comment]
To specify a Texture and Sampler with the same descriptor set and binding numbers, use the `[[vk::combinedImageSampler]]` attribute: [Vulkan combined image sampler type](https://github.com/microsoft/DirectXShaderCompiler/wiki/Vulkan-combined-image-sampler-type).
