### ISSUE TITLE
Any DirectX interface to query the maximum groupshared size per `GroupID`?

### ISSUE THREAD

**Issue by ghostplant** [microsoft/DirectXShaderCompiler#3934]
Is the maximum groupshared size per `GroupID` always fixed? Or depending on different graphic cards?

**Comment by pow2clk** [comment]
I'm afraid it's always fixed. It is set to 32Kb for DX11 and above https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-variable-syntax

That's what the validator checks for:
https://github.com/microsoft/DirectXShaderCompiler/blob/7914122a97cc50daecc8bafa5d99fda506a0439c/include/dxc/DXIL/DxilConstants.h#L94
https://github.com/microsoft/DirectXShaderCompiler/blob/7914122a97cc50daecc8bafa5d99fda506a0439c/lib/HLSL/DxilValidation.cpp#L3867

The only exception is when dealing with a mesh shader in which a portion of the groupshared memory is allocated for meshy purposes.

Please reopen if you have further questions
