### ISSUE TITLE
[SPIR-V] Specialization constant - unsupported specialization constant initializer

### ISSUE THREAD

**Issue by manas-kulkarni** [microsoft/DirectXShaderCompiler#3951]
Error happens with latest release and latest build artifact as well

Test Shader
```
[[vk::constant_id( 0 )]] const uint test = ( 4350 * 1024 );

StructuredBuffer<uint3> ro;
RWStructuredBuffer<uint3> rw;

[numthreads(8, 8, 1)]
void main(uint2 dtid : SV_DispatchThreadID)
{
	if (test)
		return;
	rw[dtid.x] = ro[dtid.x];
}
```

Error: unsupported specialization constant initializer

Verified that it compiles fine with glslangValidator

**Comment by jaebaek** [comment]
@manas-kulkarni Thank you for reporting this issue. We will take a look.

**Comment by manas-kulkarni** [comment]
Any update?

**Comment by s-perron** [comment]
This works now: https://godbolt.org/z/Pqbbexcv9.
