### ISSUE TITLE
Shader reflection variable type with D3D12, SM 6.5

### ISSUE THREAD

**Issue by Aotner** [microsoft/DirectXShaderCompiler#3969]
Hello,
I've noticed a difference between the behaviour of the reflection result in 12 compared to 11.
It looks like that the type name reflection now ignores the typedefs declared in the shader.
For example:
```
typedef float scalar;
cbuffer buffer: register(b0) {
	scalar A;
}
```
The type name in D3D12 (SM 6.5 /O0) is **float**, while with 11 is **scalar**.

Is it expected? 
Regards

**Comment by damyanp** [comment]
Given the age of this issue this is not behavior that we're going to change.
