### ISSUE TITLE
"sample" is a reserved word and cannot be used as a variable name

### ISSUE THREAD

**Issue by aluedke** [Microsoft/DirectXShaderCompiler#397]
I'm working on porting a large shader library to compile with this project.  One thing that was valid under the old compiler is as such:

`float4 sample = tex1.Sample(samp1, uv);`

This gives several compile errors under the new compiler:
`error: modifiers must appear before type`
`error: expected unqualified-id`
and `error: expected expression` wherever the variable is used.

**Comment by marcelolr** [comment]
@aluedke, I'll provide a more thorough response next week, but I wanted to at least say for now that this is something we've run into before. Unfortunately 'sample' wasn't treated consistently in the prior compiler implementation, and so thought best to try to avoid reimplementing those quirks.
