### ISSUE TITLE
Type coercion into scalar fails with internal compiler error

### ISSUE THREAD

**Issue by sndels** [microsoft/DirectXShaderCompiler#3973]
Implicit narrowing conversions into a scalar type seem to cause `Internal Compiler error: llvm::cast<X>() argument of incompatible type!`. Doesn't appear to happen when coercing into a vector type.

Minimal example, reproduces with dndxc.exe from de6a8ed4's AppVeyor build
Fails: `-enable-templates -DFAILURE_CASE`
Compiles: `-enable-templates`
```
#ifdef FAILURE_CASE
template<typename T>
T Fn(T input)
{
    T ret = input - 1.f;

    return ret;
}

#else

template<typename T>
T Fn(T input)
{
    T ret = input - (T)1.f;

    return ret;
}

#endif

void main()
{
    Fn(1.0);
}
```

**Comment by llvm-beanz** [comment]
This is also respond by PR #3991
