### ISSUE TITLE
Redundant uav load store when only part of struct is touched.

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#3980]
struct S {
 float a[10];
 float4 b;
};

RWStructuredBuffer< S > u;

float4 main(uint i:I) : SV_Target {
S s = u[i];
s.b += sin(s.b);
u[i] = s;
  return u[i].b;
}

s.a is not updated, don't need to load and store the whole struct.
There's should be only 1 buffer load and 1 buffer store in final dxil.

**Comment by damyanp** [comment]
We're not going to investigate this further at this point.
