### ISSUE TITLE
Better error reporting for error "Instructions should not read uninitialized memory"

### ISSUE THREAD

**Issue by Nielsbishere** [microsoft/DirectXShaderCompiler#3986]
Currently it requires the validator to tell that some DXIL locations include instructions that read uninitialized memory, but it's quite hard to find what it references to in a large shader. Would this be possible to be added into the regular compiler (e.g. with more clear errors) or could there be a way to obtain function name/line for each instruction?

**Comment by pow2clk** [comment]
Hi @Nielsbishere!

There are certain issues that are difficult to catch before validation. This one has an Instruction associated with it and so it often has good line number information. In fact, the simple test case found here: 
https://github.com/microsoft/DirectXShaderCompiler/blob/9b281d0de6b248423701208ec9ee248c0e47aa43/tools/clang/test/HLSLFileCheck/validation/UndefValue.hlsl#L3 produces line numbers with a release build and no `-Zi` flag.  Granted, the source line printed in the note is not the original HLSL source

Can you give an example where the line numbers are missing?

**Comment by Nielsbishere** [comment]
Perhaps I am using the Zi flag then, I will have to check tomorrow. I encountered it when I passed a payload from raygen to other shaders that was only partially initialized. This shouldn't have mattered since I don't read any other data in hit shaders, but I'm guessing since the raygen shader doesn't know that, it fully validates everything (which is a good thing in 99.9% of the cases)

**Comment by pow2clk** [comment]
The Zi flag would only give you more debug information. I mentioned it to emphasize that even without it, the information is there

**Comment by Nielsbishere** [comment]
Ah yeah fair, I only get dxil line afaik. But I'll repro tomorrow to see for sure

**Comment by Nielsbishere** [comment]
I was unable to repro this with latest dxc. It could've also been changes I made to the shader (I don't have the erroring version anymore) but removing initialization to zero doesn't cause it to fail anymore. I'll keep this error in mind if I ever encounter it again

**Comment by pow2clk** [comment]
Thanks for the confirmation! Please create a new issue if this comes up again.
