### ISSUE TITLE
[Feature request] Expose number of interpolants

### ISSUE THREAD

**Issue by nachocpol** [microsoft/DirectXShaderCompiler#4002]
To strip un-used interpolants from our pixel shaders, we perform a dummy compilation with all the interpolants enabled, and then parse the shader information to actually know which ones are used.

This works great but we are reaching the limit of interpolants during that dummy stage, getting the following error:

**error: Failed to allocate all input signature elements in available space.**

Would it be possible to expose a way to either disable the limit or perhaps specify a value? 

Thanks.

**Comment by damyanp** [comment]
We're unlikely to implement this request exactly as specified. If this is still a scenario you're interested in then we could maybe have a conversation about what exactly you're trying to achieve and see if we can come up with some way of enabling that.
