### ISSUE TITLE
Modf instruction compile error

### ISSUE THREAD

**Issue by aluedke** [Microsoft/DirectXShaderCompiler#401]
I'm adapting existing shaders to work with the DXC compiler, and have encountered an error with the modf() HLSL instruction.  It is declared as "ret modf(x, out ip)" with x being the floating point value to operate upon, ip being the integer portion of that value, and the return value being the floating-point component.  There was a shader that contained this code:
```
float stage = ...some calculation...;
modf(stage, stage);
outValue = stage * scale;

```
The modf() instruction should remove the floating point component of the stage variable, but I'm getting a compile error on the outValue line that stage is uninitialized.

**Comment by python3kgae** [comment]
I tried to reproduce with
   float scale; 
    float main(float a : A) : SV_TARGET
    {
        float stage = a * 1.6;
        modf(stage, stage);
        float outValue = stage * scale;
        return outValue;
    }
But it compiled without error.
Could you give more detail of your shader?

Thanks
Xiang

**Comment by aluedke** [comment]
It looks like it's related to the way my shader nests calls into functions with outputs.  This code fails to compile the "main2" entrypoint if the modf line is present, but always succeeds to compile the "main" entrypoint.  Here's code I was able to reproduce the issue with:

```
float scale;
void main(in float a : A, out float outVal : SV_Target)
{
	float stage = a * 1.6;
	modf(stage, stage);
	outVal = stage * scale;
}

void main2(in float a : A, out float outVal : SV_Target)
{
	main(a, outVal);
}
```

**Comment by aluedke** [comment]
Distilling it further, try this code:
```
float main(float a : A) : SV_Target
{
	float stage;
	modf(a, stage);
	return stage;
}

float main2(float a : A) : SV_Target
{
	return main(a);
}
```

If the main entrypoint is compiled, the compiler output appears to have the correct code generated in the @main() function.  If the main2 entrypoint is compiled, the @main2() function simply contains 'ret void' and nothing else.

**Comment by python3kgae** [comment]
Fixed with https://github.com/Microsoft/DirectXShaderCompiler/pull/403

Thanks
Xiang

**Comment by marcelolr** [comment]
@aluedke please reopen or file a new issue if this is still failing - thanks for your report!
