### ISSUE TITLE
numthreads(X,Y,Z) does not support static const constants.

### ISSUE THREAD

**Issue by shangjiaxuan** [microsoft/DirectXShaderCompiler#4032]
Attribute [numthreads(X,Y,Z)] does not support static const constant that can be deduced in compile time.

Also SPIRV generation of specialized constants as X, Y, Z, is not supported.

Compiler emits error message and rejects input.

**Comment by pow2clk** [comment]
Hi @shangjiaxuan!

This has been reported before in #2191. We will continue to work the issue from there, but it would be considered a new language feature. 

In the meantime, you can use a `#define` constant to get similar named behavior
