### ISSUE TITLE
[SPIR-V] Missing RelaxedPrecision decoration on Texture2D<min16float4> and other min precision resources when used inside structs

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#4047]
### Title
[SPIR-V] Missing RelaxedPrecision decoration on Texture2D<min16float4> and other min precision resources when used inside structs

### Functional impact
Textures declared inside structs don't receive the `RelaxedPrecision` decoration which can meaningfully affect performance on mobile (either with Vulkan on when transpiling the SPIR-V to essl down the line). This use case is important for us at Unity as we emulate `sampler2D` and other legacy combined texture/sampler types with structs (see the related fix which allowed the initial emulation to work with the SPIR-V backend https://github.com/microsoft/DirectXShaderCompiler/issues/2695)

### Minimal repro steps

1. Compile [repro_shader.txt](https://github.com/microsoft/DirectXShaderCompiler/files/7440458/repro_shader.txt) (see below) with `dxc.exe -T ps_6_0 -E PSMain -spirv repro_shader.txt`:
```
struct sampler2D_h {Texture2D < min16float4 > t; SamplerState s;};
min16float4 tex2D (sampler2D_h x, float2 v) {return x . t . Sample (x . s, v);}

sampler2D_h _MainTex;

min16float4 PSMain (float2 uv : TEXCOORD) : SV_Target
{
    min16float4 col = tex2D(_MainTex, uv);
    return col;
}
```

### Expected result
The resource `_MainTex.t`, which has the template type `<min16float4>` should have the relaxed precision decoration set in the generated SPIR-V i.e. `OpDecorate %_MainTex_t RelaxedPrecision`, as if it were declared in the global scope (here's an [example on shader playground](https://shader-playground.timjones.io/efd421055aa3768cf526215b1c58504b))

### Actual result
`_MainTex.t` has no relaxed precision decoration in the generated SPIR-V

```
; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 24
; Schema: 0
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %PSMain "PSMain" %in_var_TEXCOORD %out_var_SV_Target
               OpExecutionMode %PSMain OriginUpperLeft
               OpSource HLSL 600
               OpName %type_2d_image "type.2d.image"
               OpName %type_sampler "type.sampler"
               OpName %in_var_TEXCOORD "in.var.TEXCOORD"
               OpName %out_var_SV_Target "out.var.SV_Target"
               OpName %PSMain "PSMain"
               OpName %type_sampled_image "type.sampled.image"
               OpName %_MainTex_t "_MainTex.t"
               OpName %_MainTex_s "_MainTex.s"
               OpDecorate %in_var_TEXCOORD Location 0
               OpDecorate %out_var_SV_Target Location 0
               OpDecorate %out_var_SV_Target RelaxedPrecision
               OpDecorate %9 RelaxedPrecision
               OpDecorate %_MainTex_t DescriptorSet 0
               OpDecorate %_MainTex_t Binding 0
               OpDecorate %_MainTex_s DescriptorSet 0
               OpDecorate %_MainTex_s Binding 1
      %float = OpTypeFloat 32
%type_2d_image = OpTypeImage %float 2D 2 0 0 1 Unknown
%type_sampler = OpTypeSampler
    %v2float = OpTypeVector %float 2
%_ptr_Input_v2float = OpTypePointer Input %v2float
    %v4float = OpTypeVector %float 4
%_ptr_Output_v4float = OpTypePointer Output %v4float
       %void = OpTypeVoid
         %16 = OpTypeFunction %void
%type_sampled_image = OpTypeSampledImage %type_2d_image
%in_var_TEXCOORD = OpVariable %_ptr_Input_v2float Input
%out_var_SV_Target = OpVariable %_ptr_Output_v4float Output
%_ptr_UniformConstant_type_2d_image = OpTypePointer UniformConstant %type_2d_image
 %_MainTex_t = OpVariable %_ptr_UniformConstant_type_2d_image UniformConstant
%_ptr_UniformConstant_type_sampler = OpTypePointer UniformConstant %type_sampler
 %_MainTex_s = OpVariable %_ptr_UniformConstant_type_sampler UniformConstant
     %PSMain = OpFunction %void None %16
         %19 = OpLabel
         %20 = OpLoad %v2float %in_var_TEXCOORD
         %21 = OpLoad %type_2d_image %_MainTex_t
         %22 = OpLoad %type_sampler %_MainTex_s
         %23 = OpSampledImage %type_sampled_image %21 %22
          %9 = OpImageSampleImplicitLod %v4float %23 %20 None
               OpStore %out_var_SV_Target %9
               OpReturn
               OpFunctionEnd
```

### Further technical details
Here's the above example for convenience on [shader playground](https://shader-playground.timjones.io/9966644a297e12c88c07542b02e51de6)

* In practice, this is a perf issue for us when translating to essl, as the missing decoration results in less 16-bit floating-point utilization which is a very important performance factor on mobile (switch the `USE_EMULATED_SAMPLER2D` define from `1` to `0` to see `16-bit arithmetic: 0%` go to `16-bit arithmetic: 33%` in the Mali Offline Compiler performance report [on shader playground](https://shader-playground.timjones.io/91abee26623bb5640deadcb40b789760))

**Comment by jaebaek** [comment]
@Dredhog Thank you for reporting this issue. I will take a look.
