### ISSUE TITLE
Survey for compiler versions to build DXC

### ISSUE THREAD

**Issue by jaebaek** [microsoft/DirectXShaderCompiler#4050]
In order to properly test different compilers for CI tests, we want to check compilers that developers use to build DXC. Please let us know **one or more compilers** you use, or please add a comment if you use different versions of GCC or Clang.

Note that you can click multiple entries and you cannot undo your votes (sorry for that).

[![](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-Clang-12)](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-Clang-12/vote)
[![](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-Clang-11)](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-Clang-11/vote)
[![](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-Clang-10)](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-Clang-10/vote)
[![](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-Clang-9)](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-Clang-9/vote)
[![](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-Clang-6)](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-Clang-6/vote)
[![](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-GCC-10)](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-GCC-10/vote)
[![](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-GCC-9)](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-GCC-9/vote)
[![](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-GCC-7)](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-GCC-7/vote)
[![](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-GCC-5)](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Linux-GCC-5/vote)
[![](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/MacOS-Clang-13)](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/MacOS-Clang-13/vote)
[![](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/MacOS-Clang-12)](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/MacOS-Clang-12/vote)
[![](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Windows-VS-19)](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Windows-VS-19/vote)
[![](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Windows-VS-17)](https://api.gh-polls.com/poll/01FK6PKZ3MMNJW78Z70GN7R308/Windows-VS-17/vote)

**Comment by seppala2** [comment]
Not sure if there are any planned tests for Android specifically (at least running the tests could be problematic), but anyways I'd like to mention that we have also used Android NDK 21 to build it for Android. I can see support of at least the latest Android NDK very useful. iOS compilation would be probably also useful for some cross-platform apps, although we haven't used it.

**Comment by llvm-beanz** [comment]
@seppala2 Building for iOS is pretty straightforward, but not explicitly supported the LLVM-documentation should more or less work: https://llvm.org/docs/GettingStarted.html#cross-compiling-llvm
