### ISSUE TITLE
[SPIR-V] Generated SPIR-V invalid for universal1.5 under dxcompiler.dll 1.6.0.2974

### ISSUE THREAD

**Issue by jzm-intel** [microsoft/DirectXShaderCompiler#4051]
When I compile the example shader from [issue:2500](https://github.com/microsoft/DirectXShaderCompiler/issues/2500), which is
```
struct CBData
{
    half4 Color;
};

ConstantBuffer<CBData> CB;

float4 PSMain() : SV_Target0
{
    return pow(CB.Color, 2.2h);
}
```
under parameters `-T ps_6_2 -E PSMain -enable-16bit-types -spirv -fspv-target-env="vulkan1.1"` I can get the correct result, but with `-T ps_6_2 -E PSMain -enable-16bit-types -spirv -fspv-target-env="universal1.5"` I get the following error:
```
fatal error: generated SPIR-V is invalid: Interface variable id <5> is used by entry point 'PSMain' id <2>, but is not listed as an interface
  %CB = OpVariable %_ptr_Uniform_type_ConstantBuffer_CBData Uniform

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

My dxc version is `dxcompiler.dll: 1.6 - 1.6.0.2974 (f5f4b1aa)`.

**Comment by jaebaek** [comment]
@jzm-intel Thank you for reporting this issue. We will take a look.

**Comment by sudonatalie** [comment]
Sorry for the very late follow up on this issue.

I'm unable to reproduce the error on a current DXC build. The shader compiles and validates successfully with either set of flags, so whatever bug caused this has probably been fixed.
