### ISSUE TITLE
Support `#pragma once`

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/DirectXShaderCompiler#4093]
This is a small thing of course (at least as a feature), but it's a very nice thing to be able to use. Now that the function overloading and loop scoping are getting fixed, maybe it's time to support `#pragma once`?

**Comment by llvm-beanz** [comment]
HLSL does support `#pragma once`. Do you have a specific reproduction case where it isn't working?

**Comment by pow2clk** [comment]
#pragma once is supported. If you know of a scenario where it isn't, please reopen
