### ISSUE TITLE
dx.op.textureStore for RWTexture2D<uint> uses mask 15

### ISSUE THREAD

**Issue by cblifeform** [microsoft/DirectXShaderCompiler#4098]
Consider this simple compute shader:

```hlsl
RWTexture2D<uint> outTexture : register(u0);

[numthreads(8, 8, 1)]
void main(uint3 dtid : SV_DispatchThreadId)
{
	outTexture[dtid.xy] = 0x88005553;
}
```

This is DXIL:

```llvm
%dx.types.Handle = type { i8* }
%"class.RWTexture2D<unsigned int>" = type { i32 }

define void @main() {
  %1 = call %dx.types.Handle @dx.op.createHandle(i32 57, i8 1, i32 0, i32 0, i1 false)  ; CreateHandle(resourceClass,rangeId,index,nonUniformIndex)
  %2 = call i32 @dx.op.threadId.i32(i32 93, i32 0)  ; ThreadId(component)
  %3 = call i32 @dx.op.threadId.i32(i32 93, i32 1)  ; ThreadId(component)
  call void @dx.op.textureStore.i32(i32 67, %dx.types.Handle %1, i32 %2, i32 %3, i32 undef, i32 -2013244077, i32 -2013244077, i32 -2013244077, i32 -2013244077, i8 15)  ; TextureStore(srv,coord0,coord1,coord2,value0,value1,value2,value3,mask)
  ret void
}
```

Despite writing only to .x component of RWTexture2D<uint> the mask is still 15, but I'd assume it would be 1. Is it a bug or expected behavior?

Thanks.

**Comment by vcsharma** [comment]
@cblifeform This is by-design to be compliant with the [D3D specification](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#:~:text=dstUAV%20always%20has%20a%20.xyzw%20write%20mask.%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20All%20components%20must%20be%20written.) (relevant excerpt below). Specifically, we need to store all four channels of type UAV resources.

> dstUAV always has a .xyzw write mask.
> All components must be written.
