### ISSUE TITLE
'Pipeline State Validation' error on Windows compiling compute shader

### ISSUE THREAD

**Issue by amaiorano** [microsoft/DirectXShaderCompiler#4104]
Downloaded the latest artifact build, and am getting the following error when compiling a specific compute shader:
```
error: validation errors
error: Container part 'Pipeline State Validation' does not match expected for module. Use /Zi for source location.
Validation failed.
```

The following is taken directly from my cmd.exe:
```
C:\src\tint>C:\dxc\dxc-artifacts\bin\dxc --version
dxcompiler.dll: 1.7 - 1.6.0.3355 (676fe64dd); dxil.dll: 1.6(101.5.2005.60)

C:\src\tint>C:\dxc\dxc-artifacts\bin\dxc -T cs_5_1 test.hlsl -E compute_main
error: validation errors
error: Container part 'Pipeline State Validation' does not match expected for module. Use /Zi for source location.
Validation failed.

C:\src\tint>type test.hlsl
    void atan2_57fb13() {
      float2 res = atan2(float2(0.0f, 0.0f), float2(0.0f, 0.0f));
    }

    struct tint_symbol {
      float4 value : SV_Position;
    };

    float4 vertex_main_inner() {
      atan2_57fb13();
      return float4(0.0f, 0.0f, 0.0f, 0.0f);
    }

    tint_symbol vertex_main() {
      const float4 inner_result = vertex_main_inner();
      tint_symbol wrapper_result = (tint_symbol)0;
      wrapper_result.value = inner_result;
      return wrapper_result;
    }

    void fragment_main() {
      atan2_57fb13();
      return;
    }

    [numthreads(1, 1, 1)]
    void compute_main() {
      atan2_57fb13();
      return;
    }
```

**Comment by pow2clk** [comment]
I am not able to reproduce this issue even using the same compiler version. Given that it's a validation error, and I don't see the warning about unsigned DXIL output, I think your compile run is finding a dxil.dll that doesn't support the PSV version that the compiler is creating.

If you remove dxil.dll from the path, I expect the compile will be successful. FWIW, we will very shortly have an official release with a new dxil.dll

**Comment by amaiorano** [comment]
Thank you for looking into this, @pow2clk. I'm going to validate this and respond here soon. Looking for which dxil.dll is being picked up is a great lead.

**Comment by amaiorano** [comment]
Just took a look, and yeah, the artifact build that we can download from the main readme page [here](https://github.com/microsoft/DirectXShaderCompiler#downloads) does **not** include dxil.dll. As dxc.exe needs it, shouldn't that file be packaged in that artifact build? The [releases](https://github.com/microsoft/DirectXShaderCompiler/wiki/Releases) do include dxil.dll.

Otherwise, what's the process to make use of the artifact build correctly? Should we be first downloading the latest release, and then patching the artifact files on top of that?

**Comment by pow2clk** [comment]
dxil.dll is not strictly needed for compiling. Artifact builds do not include them by design because they are required for signing, but not for validating. dxcompiler.dll includes a validator, but until it is shipped in a release with dxil.dll, it can't be used to sign because it's not finalized. 

If compiling for shipping products, we strongly recommend using a release compiler. If you want to experiment with new features or need a fix, usually the latest dxil.dll will work with the artifact compiler.

**Comment by amaiorano** [comment]
> If compiling for shipping products, we strongly recommend using a release compiler. If you want to experiment with new features or need a fix, usually the latest dxil.dll will work with the artifact compiler.

Thank you!
