### ISSUE TITLE
Requires Python 3.6+?

### ISSUE THREAD

**Issue by gongminmin** [microsoft/DirectXShaderCompiler#4138]
Happen to find a building failure on an old computer with Python 3.5 installed. The problem is in HLSLOptions.td. The order of shader profiles from hctgen is different than the hand written one. Traced more on this, the issue is in utils/hct/hctdb_instrhelp.py:

```
 def getShaderProfiles():
    # order match DXIL::ShaderKind.
    profiles = {"ps":"4_0", "vs":"4_0", "gs":"4_0", "hs":"5_0", "ds":"5_0", "cs":"4_0", "lib":"6_1", "ms":"6_5", "as":"6_5"}
    return profiles;
```

Starting from Python 3.6, dict preserves the order of insertion. But not on 3.5. In README, the requirement of Python is 3.x, makes it not accurate.

Of course, another fix is change the dict here to OrderedDict. But still, OrderedDict was added in 3.1, not 3.0. Change the README to 3.6+ may be the easiest way.

**Comment by tex3d** [comment]
We should just change this to return a list of tuples (like: `[("ps", "4_0"), ...]`).  This function is only used to get and iterate these key/value pairs, not for dictionary lookup.
