### ISSUE TITLE
__HLSL_VERSION is defined to 2018 even if the flag "-HV 2021" is passed to the compiler

### ISSUE THREAD

**Issue by zigguratvertigo** [microsoft/DirectXShaderCompiler#4146]
Hi,

We are compiling shaders with `-HV 2021`. Checking the value of `__HLSL_VERSION` in shaders, the value seems to be still 2018 instead of 2021 [as per the documentation](https://github.com/microsoft/DirectXShaderCompiler/wiki/Predefined-Version-Macros#hlsl-language-version-define). 

This issue can be verified by simply writing the define in a shader and letting the compiler output its value as an error.

In HLSL:
```
__HLSL_VERSION
```

Compilation: 
```
error: expected unqualified-id
  2018
  ^
```

**Comment by zigguratvertigo** [comment]
In the event where someone uses both the preprocessor and the compiler, the issue can be resolved by making sure "-HV 2021" is passed to both.

**Comment by zigguratvertigo** [comment]
Is this expected behaviour @tex3d ?

**Comment by llvm-beanz** [comment]
This doesn't sound like a bug to me. `__HLSL_VERSION` is a preprocessor define, so it is only set by the preprocessor stage. If you don't set `-HV 2021` for the preprocessor call, the preprocessor runs in the 2018 language mode (which is the default language mode). By the time you get to the compile all the places that you used `__HLSL_VERSION` are already expanded, so there is nothing the compiler can do to alter that.
