### ISSUE TITLE
[SPIR-V] select intrinsic function unimplemented

### ISSUE THREAD

**Issue by dBagrat** [microsoft/DirectXShaderCompiler#4148]
As mentioned [here](https://devblogs.microsoft.com/directx/announcing-hlsl-2021/#logical-operator-short-circuiting) short circuiting prevents usage of logical operators with non-scalar type values.
The alternative is to use new `and`, `or` and `select` intrinsics.
However using `select` produces "select intrinsic function unimplemented" error, thus there is no way to actually get the old behavior to work.

**Comment by jaebaek** [comment]
Thank you for reporting this issue, @dBagrat. Yeah, SPIR-V code gen's support of HLSL 2021 is incomplete. We will add the support soon.

**Comment by dBagrat** [comment]
> Thank you for reporting this issue, @dBagrat. Yeah, SPIR-V code gen's support of HLSL 2021 is incomplete. We will add the support soon.

Hi, just wondering if there are any updates on this?
