### ISSUE TITLE
[SPIR-V] Compiling Directx9 Shaders to SPIR-V

### ISSUE THREAD

**Issue by sparkskapil** [microsoft/DirectXShaderCompiler#4150]
I have a old Directx9 project. I am trying to convert shaders from .fx to .spv with dxc. 

The shaders compile without any error with D3DCompiler.
I am getting an error  `error: unknown type name 'sampler2D'`  with DXC.

The command used:
`dxc.exe -Od -Zi -Qembed_debug -T vs_5_0 -E MainVS Shader.fx -Fo Shader_VS.spv `

Is it possible to convert Direct9 shaders to SPIR-V?

**Comment by jaebaek** [comment]
I guess it is related to the HLSL type `sampler2D`. I guess the SPIR-V code gen does not have some code to translate the type into a SPIR-V type. Could you please give us a minimal reproducible shader?

**Comment by sudonatalie** [comment]
I'm not sure what the current state of support is for this particular legacy type on the SPIR-V backend or DXIL backend. The error looks like a frontend message, so if this isn't currently supported by the DXIL backend we're unlikely to add support for SPIR-V to DXC. If you'd like us to re-evaluate this request, please comment/re-open with a reproducible shader.
