### ISSUE TITLE
DXR automatic resource bindings with -T "lib_6_3" looks wrong in DXIL asm

### ISSUE THREAD

**Issue by aik6980** [microsoft/DirectXShaderCompiler#4164]
I got an error when i'm creating this object 
```
DBG::throw_hr(device->CreateStateObject(raytrace_pso, IID_PPV_ARGS(&m_dxr_state_object)));
```
From my investigation, this is because 
in my simple raytracing shaders, I got this DXIL output when using auto resource bindings 
The output looks fine when I manually bind with register(xx)

```
; Resource Bindings:
;
; Name                                 Type  Format         Dim      ID      HLSL Bind  Count
; ------------------------------ ---------- ------- ----------- ------- -------------- ------
; Output                                UAV     f32          2d      U0u4294967295,space4294967295     1
;
```
```
RaytracingAccelerationStructure Scene;
RWTexture2D<float4> Output;

cbuffer Raygen_cb
{
    float4 Main_vp;
    float4 Stencil_vp;
};

//RaytracingAccelerationStructure Scene : register(t0);
//RWTexture2D<float4> Output : register(u0);
//
//cbuffer Raygen_cb : register(b0)
//{
//	float4 Main_vp;
//	float4 Stencil_vp;
//};
```
```
; Resource Bindings:
;
; Name                                 Type  Format         Dim      ID      HLSL Bind  Count
; ------------------------------ ---------- ------- ----------- ------- -------------- ------
; Output                                UAV     f32          2d      U0             u0     1
;
```

This behaviour only happens with "lib_6_x". My other shaders "vs_6_0" "ps_6_0" "cs_6_0" is working fine with auto resource bindings, so I think this might be a bug? 
I'm using the latest DXC build.

[simple_raytracing.ray.hlsl.zip](https://github.com/microsoft/DirectXShaderCompiler/files/7786699/simple_raytracing.ray.hlsl.zip)

**Comment by tex3d** [comment]
We need to point out/clarify that automatic register binding only occurs with normal shader targets (not lib targets), or on lib targets when you use the `-auto-binding-space <space>` argument to specify the space into which automatic register binding should occur.  The UINT32_MAX number you see in binding information indicate that the resource is not bound to any register yet.  This allows you to separately compile libraries and defer automatic register binding until linking the final shader, basing final bindings on the resources used by that shader.
