### ISSUE TITLE
[SPIRV] Access violation inside of `Expr::IgnoreParens` when a function template has default arguments.

### ISSUE THREAD

**Issue by d44m1n** [microsoft/DirectXShaderCompiler#4169]
Hi,
DXC crashes inside of `Expr::IgnoreParens` when a function template has default arguments(one or more), but only while generating SPIR-V.
DXIL codegen works just fine.

Tested on `master` (36764f6b96b00b35c517ccb8169aa2146fa004b8) and latest release(v1.6.2112).

```hlsl
template <typename T>
void test(const uint a, const uint b = 0)
{
}

float4 main(uint vertex_id : SV_VertexID) : SV_Position
{
    test<uint>(0, 1); // works
    test<uint>(0); // crashes
    return (float4)0;
}
```
Compiled with:
`dxc -HV 2021 -T vs_6_5 -O3 -Zi -spirv -E main -fvk-invert-y -fspv-target-env="vulkan1.1" -Zpr .\crash_test.vert.hlsl`
Result:
`Internal compiler error: access violation. Attempted to read from address 0x0000000000000000`

**Comment by pow2clk** [comment]
Tagging @jaebaek for visibility. SPIRV issue

**Comment by jaebaek** [comment]
@pow2clk Thanks!
