### ISSUE TITLE
[SPIR-V] refactoring tools/clang/lib/SPIRV/DeclResultIdMapper.cpp

### ISSUE THREAD

**Issue by jaebaek** [microsoft/DirectXShaderCompiler#4173]
`DeclResultIdMapper` has become complicated. It includes the code for Resource variables, stage variables, `vk` attributes, ... Engineering it takes long time because it is not readable and it contains large amount of logic. In addition, many functions are too long and handle so many cases. We have to seriously refactor the code for its readability.

TODO:
- [ ] Split functions into small functions
- [ ] Change function names with more clear ones
- [ ] Add comments to clearly describe each case e.g., `vk` attributes
- [ ] Change variable names

**Comment by s-perron** [comment]
This looks like a work list for Jaebaek, who is no longer working on this project. I don't think we will follow up with a major refactor in DXC at this point.
