### ISSUE TITLE
[Bug Report][Need Help] release-1.6.2110 Dxc Crash at DeleteDeadAllocas

### ISSUE THREAD

**Issue by JayceLai** [microsoft/DirectXShaderCompiler#4176]
## Intro
Hi，I have encountered a crash phenomenon(It's broken somewhere around DeleteDeadAllocas), but I don't know how to solve it, so I hope to get your help!

And I have added some relevant information below in the hope that it will be helpful for you to find the problem

Any help would be appreciated!

## The Commit I use
[release-1.6.2110 + some fix](https://github.com/JayceLai/DirectXShaderCompiler/tree/release-1.6.2110)

## Compile args
![image](https://user-images.githubusercontent.com/23555101/148351107-ecf91701-b9b6-45dd-84c8-e0848afd77fa.png)

## Minimize reproduced
```hlsl
#pragma pixel PSMain

struct psInput 
{
    float4 position: SV_POSITION;
    int4 lightIndex: TEXCOORD6;
};

float4 PSMain(psInput psIn): SV_TARGET 
{
    for (int i = 0; i < 3; i++) {
        int index = psIn.lightIndex[i]; // Comment out this line to avoid a crash
    }

    return psIn.position;
}
```

**Compile the hlsl source with args: "-E PSMain -T ps_6_2 -Zpc -Od“**

## Call Stack
![image](https://user-images.githubusercontent.com/23555101/148352479-511dbee2-a514-4922-b7ea-fe68e4de66d0.png)

**Comment by bob80905** [comment]
I ran dxc.exe on the min repro shader, with these arguments:-E PSMain -T ps_6_2 -Zpc -Od. I ran it on the snapshot you provided.
I got this error:
Internal compiler error: access violation. Attempted to read from address 0x0000000000000030

I did the exact same thing on the latest snapshot, and there were no errors.
I'll close this for now, feel free to open a new bug if you run into this behaviour again.
