### ISSUE TITLE
[SPIR-V] Default layout rules can not create Shader for Vulkan.

### ISSUE THREAD

**Issue by LuciferSweety** [microsoft/DirectXShaderCompiler#4184]
Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x1f549568fa0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Structure id 5 decorated as Block for variable in Uniform storage class must follow standard uniform buffer layout rules: member 4 at offset 20 is not aligned to 16
  %type_cbPerMaterial = OpTypeStruct %v2float %float %float %float %v3float %v3int %v4float %_arr_float_uint_2 %v3float %float %v3float %mat2v3float %mat3v2float %v2float %v2float %mat4v4float %mat4v3float %mat3v4float %mat2v3float %_arr_int_uint_3 %_arr_v2float_uint_2

Reflection data:
    "types" : {
        "_5" : {
            "name" : "type.cbPerMaterial",
            "members" : [
                {
                    "name" : "xx",
                    "type" : "vec2",
                    "offset" : 0
                },
                {
                    "name" : "yy",
                    "type" : "float",
                    "offset" : 8
                },
                {
                    "name" : "zz",
                    "type" : "float",
                    "offset" : 12
                },
                {
                    "name" : "kk",
                    "type" : "float",
                    "offset" : 16
                },
                {
                    "name" : "ss",
                    "type" : "vec3",
                    "offset" : 20
                },
                {
                    "name" : "int3a",
                    "type" : "ivec3",
                    "offset" : 32
                },
                {
                    "name" : "float4a",
                    "type" : "vec4",
                    "offset" : 48
                },
                {
                    "name" : "XXX",
                    "type" : "float",
                    "array" : [
                        2
                    ],
                    "array_size_is_literal" : [
                        true
                    ],
                    "offset" : 64,
                    "array_stride" : 16
                },
                {
                    "name" : "BaseColor",
                    "type" : "vec3",
                    "offset" : 96
                },
                {
                    "name" : "a_float",
                    "type" : "float",
                    "offset" : 108
                },
                {
                    "name" : "b_float3",
                    "type" : "vec3",
                    "offset" : 112
                },
                {
                    "name" : "d_float2x3",
                    "type" : "mat2x3",
                    "offset" : 128,
                    "matrix_stride" : 16
                },
                {
                    "name" : "d_float3x2",
                    "type" : "mat3x2",
                    "offset" : 160,
                    "matrix_stride" : 16
                },
                {
                    "name" : "d_float1x2",
                    "type" : "vec2",
                    "offset" : 208
                },
                {
                    "name" : "d_float2x1",
                    "type" : "vec2",
                    "offset" : 216
                },
                {
                    "name" : "d_float4x4",
                    "type" : "mat4",
                    "offset" : 224,
                    "matrix_stride" : 16
                },
                {
                    "name" : "d_float4x3",
                    "type" : "mat4x3",
                    "offset" : 288,
                    "matrix_stride" : 16
                },
                {
                    "name" : "d_float3x4",
                    "type" : "mat3x4",
                    "offset" : 352,
                    "matrix_stride" : 16
                },
                {
                    "name" : "e_float2x3",
                    "type" : "mat2x3",
                    "offset" : 400,
                    "matrix_stride" : 16
                },
                {
                    "name" : "f_int_3",
                    "type" : "int",
                    "array" : [
                        3
                    ],
                    "array_size_is_literal" : [
                        true
                    ],
                    "offset" : 432,
                    "array_stride" : 16
                },
                {
                    "name" : "g_float2_2",
                    "type" : "vec2",
                    "array" : [
                        2
                    ],
                    "array_size_is_literal" : [
                        true
                    ],
                    "offset" : 480,
                    "array_stride" : 16
                }
            ],
            "block_size" : 512
        }
    },

HLSL code cb:
cbuffer cbPerMaterial
{
    float2 xx;
    float yy;
    float zz;
    float kk;
    float3 ss;
    int3   int3a;
    float4 float4a;

    float XXX[2];
	float3 BaseColor;
    float    a_float;
    float3   b_float3;
    float2x3 d_float2x3;
    float3x2 d_float3x2;
    float1x2 d_float1x2;
    float2x1 d_float2x1;
    float4x4 d_float4x4;
    float4x3 d_float4x3;
    float3x4 d_float3x4;
    row_major float2x3 e_float2x3;
    int      f_int_3[3];
    float2   g_float2_2[2];
}

It's look like 32 offset for the 'ss'. Actually, it's 20.
Should be using Strict OpenGL std140 for vulkan?

**Comment by jaebaek** [comment]
@pow2clk, thank you for tagging the spirv label for it!

**Comment by LuciferSweety** [comment]
It's look like the "vector-relaxed OpenGL" rules worked on vulkan 1.1 & later. This error report on vulkan 1.0;  But nothing description on the "SPIR-V.rst".

**Comment by jaebaek** [comment]
Since the Vulkan spec or validation layer is out of our control, we try to provide the memory rules introduced in the SPIR-V.rst. We know for many memory layouts and many cases e.g., struct/array/matrix/vector our memory layout rules can have lots of Vulkan validation errors, but we have to provide the rules matching most popular layout rules e.g., DX/std140/std430/relaxed. It is developer's choice and avoiding the Vulkan validation errors is out of our control.

In particular, we cannot easily (randomly) change the memory layout rules. They are popular rules and they are already used by many HLSL shaders in the industry. The only cases we changed the layout rule so far were that our implementation for the layout rules is actually wrong.

If you break down your bug and pinpoint the implementation issue that does not follow the memory layout rule, we will try to fix it. However, without solid evidences, we cannot easily change the implementation because it will affect all existing shaders.

**Comment by LuciferSweety** [comment]
Thanks, I find an annotation in the spirv-tools. relaxed memory layout rules worked on vulkan 1.1 & later. 
![image](https://user-images.githubusercontent.com/18320190/152994969-5a0d9712-51d7-47eb-b6d7-d9a062ee1278.png)
 Close it.
