### ISSUE TITLE
[SPIR-V] Data queried from arrays with indices known at compile time is considered dynamic

### ISSUE THREAD

**Issue by OrangeeZ** [microsoft/DirectXShaderCompiler#4283]
Hi! We've been recently using DXC to compile our HLSL codebase to SPIR-V. We've encountered an issue with arrays in our code. We use `dxccompiler.dll v. 1.6.2104.52` but the issue persists even on latest `dxccompiler.dll v. 1.6.2112.12`.

Here are two examples.

1. Using texture arrays with compile-time indices.
```
Texture2D<float4> textures[ 6 ] = {
		g_faceTexturePX,
		g_faceTextureNX,
		g_faceTexturePY,
		g_faceTextureNY,
		g_faceTexturePZ,
		g_faceTextureNZ
	};

	if ( leftLine( int2( uv * g_faceSize ) ) )
		return float4( textures[id0].SampleLevel( g_faceTexturePOINTSampler, xy0, g_readMipLevel ).xyz, alpha.x );
	else if ( rightLine( int2( uv * g_faceSize ), g_faceSize ) )
		return float4( textures[id1].SampleLevel( g_faceTexturePOINTSampler, xy1, g_readMipLevel ).xyz, alpha.y );
	else if ( downLine( int2( uv * g_faceSize ), g_faceSize ) )
		return float4( textures[id2].SampleLevel( g_faceTexturePOINTSampler, xy2, g_readMipLevel ).xyz, alpha.z );
	else if ( upLine( int2( uv * g_faceSize ) ) )
		return float4( textures[id3].SampleLevel( g_faceTexturePOINTSampler, xy3, g_readMipLevel ).xyz, alpha.w );
	else
		return 0;
```
All of the array indices are known at compile time, but DXC reports 

```
1>EXEC : fatal error : generated SPIR-V is invalid: The Base <id> '85[%85]' in OpAccessChain instruction must be a pointer.
1>  %86 = OpAccessChain %_ptr_Function_type_2d_image %85 %int_0
1>
1>note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```
When declaring the array as `static const` inside the function, call to DXC results in `Access violation reading location 0x000000000000004C`.
When declaring the array as `static const` outside the function, our compiler crashes, it forbids such declarations.

2. Using Gather offset arrays with compile-time indices.
```
float4 box4( uniform Texture2D tex, in float2 tc )
{
    int2 offsets[NUM_SAMPLES] =
	{
		int2(-1.0, -1.0),
		int2(1.0, 1.0),
		int2(1.0, -1.0),
		int2(-1.0, 1.0)
	};

	float4 color = (float4)0;
	[unroll]
	for ( int j = 0; j < NUM_SAMPLES; j++ )
	{
		// VKTODO: causes compilation error when accessing offsets[j].
		color += tex.SampleLevel( g_RTLinearSampler, tc, 0, offsets[j] );
	}

	color *= 0.25;

	return color;
}
```
Again, the loop uses `static const int NUM_SAMPLES = 4;` as an upper bound so it should unroll and inline the calls with no problem.  The error is
`error GA6F53288: Use constant value for offset (SPIR-V spec does not accept a variable offset for OpImage* instructions other than OpImage*Gather)`
Declaring offsets as `const static` does not crash the compiler, but does not fix the issue either.

It seems that when compiling HLSL -> SPIR-V, DXC does not run any potential optimizations on HLSL code, and SPIR-V does not inline such calls. We compile with
`-spirv -fspv-target-env=vulkan1.0 -fvk-use-dx-layout -Zpr -HV 2018 -enable-16bit-types -O3`

Rewriting the code is an option, but it generally results in a more verbose and less readable code. Interestingly, adding `-Vd`  does not do anything and the code still produces errors.

So the questions are:
1. Does DXC optimize the input HLSL in any way before forwarding it into SPIR-V toolchain? If yes, is there any way to make it perform an inline pass before the SPIR-V translation? If no, is there any way we can manually use DXC to optimize our HLSL before forwarding it for translation?
2. If none of the options above are viable, what are our options here outside of rewriting all of the problematic pieces of code?

**Comment by s-perron** [comment]
A full test case was not provided, so I cannot properly check if this is still an issue.  However, I wrote something similar, and it seems to be passing now: https://godbolt.org/z/6a1nx3jK9.
