### ISSUE TITLE
[SPIR-V] SPIRV missing certain #includes

### ISSUE THREAD

**Issue by phradsky** [microsoft/DirectXShaderCompiler#4284]
Hi!

Not all #include directives are reflected into "OpSource" in SPIRV,
which prevents recompilation/edit with tools such as RenderDoc.

Attached is a minimal repro:
[spirv_includes_minimal_repro.zip](https://github.com/microsoft/DirectXShaderCompiler/files/8117884/spirv_includes_minimal_repro.zip)

Compiled with "dxc.exe -spirv -Zi -T ps_6_0 main.hlsl", it produces the attached "spirv.txt".
Note that it correctly contains the "inc_a.hlsl" source code, but lacks "inc_common.hlsl".

When recompiling such a shader in RenderDoc capture replay, for example,
it cannot possibly succeed as one of the original files, "inc_common.hlsl", is missing altogether from SPIRV.

**Comment by SteveUrquhart** [comment]
This was fixed by https://github.com/microsoft/DirectXShaderCompiler/pull/6094
