### ISSUE TITLE
[SPIR-V] Add `void vk::RawBufferLoadInto(out T output, in uint2 address, in uint alignment = 4)` and `T vk::RawBufferLoad<T, alignment>(in uint2 address)`

### ISSUE THREAD

**Issue by jaebaek** [microsoft/DirectXShaderCompiler#4288]
See the discussion in #4226

**Comment by natevm** [comment]
I'm finding that Intel Arc doesn't support 64-bit integers at the moment. So I might try implementing this if no one else has the cycles...

**Comment by natevm** [comment]
We also might want to break up this issue, since RawBufferLoadInto is a separate feature from supporting uint2 addresses.

**Comment by natevm** [comment]
w.r.t the uint2 address, I'm unfortunately running into an issue with dxc casting the uint2 address into a single uint64_t address value and emitting a warning. I use this in the gen_intrin_main.txt but I guess overloading doesn't work here?

```
$funcT [[ro]] RawBufferLoad(in u64 addr);
$funcT [[ro]] RawBufferLoad(in u64 addr, in uint alignment);
$funcT [[ro]] RawBufferLoad(in uint<2> addr);
$funcT [[ro]] RawBufferLoad(in uint<2> addr, in uint alignment);
void [[]] RawBufferStore(in u64 addr, in $funcT value);
void [[]] RawBufferStore(in u64 addr, in $funcT value, in uint alignment);
void [[]] RawBufferStore(in uint<2> addr, in $funcT value);
void [[]] RawBufferStore(in uint<2> addr, in $funcT value, in uint alignment);
```

So for the moment, I'm thinking I'll name the uint2 address variants `RawBufferI2Load` and `RawBufferI2Store`

**Comment by devshgraphicsprogramming** [comment]
> I'm finding that Intel Arc doesn't support 64-bit integers at the moment. So I might try implementing this if no one else has the cycles...

after the release of 1.3.250 drivers, all Intel GPUs finally support uint64_t in shaders

**Comment by natevm** [comment]
I ultimately discovered the same thing. Even before 250, if you ignored the validation errors, on Intel ARC, 64 bit integers would work.

the only thing I really see this being helpful for then are some mobile platforms. Personally though, I wouldn’t find this feature very useful.

**Comment by s-perron** [comment]
We will not be changing the raw buffer feature. We will implement the vk::BufferPointer proposal, and expect that to meet people's needs.

**Comment by natevm** [comment]
@s-perron this is the second time over the past three years where Microsoft has swept a massive number of our issues under the rug as if they never existed. 

If this company actually cared about these issues, they would be adding them as targets for unit tests, and not just closing them all in one day.

To anyone out there running into these issues, I cannot recommend switching to slang enough. Get the latest version of the compiler here! :  https://github.com/shader-slang/slang/releases

**Comment by devshgraphicsprogramming** [comment]
> @s-perron this is the second time over the past three years where Microsoft has swept a massive number of our issues under the rug as if they never existed.
> 
> If this company actually cared about these issues, they would be adding them as targets for unit tests, and not just closing them all in one day.
> 
> To anyone out there running into these issues, I cannot recommend switching to slang enough. Get the latest version of the compiler here! : https://github.com/shader-slang/slang/releases

This issue is closed for a good reason, no desktop HW really exists with BDA and without uint64_T support.

**Comment by natevm** [comment]
@devshgraphicsprogramming 

Here I agree. But this should have been the reason to close this issue, and it wasn’t. I had three other issues hastily closed today for similar reasons. At this point I don’t see any purpose in these GitHub issues.

**Comment by natevm** [comment]
> I'm sorry I was too terse in my explanation for closing the issues. We are taking a number of things into consideration like the future direction of HLSL, the life span of DXC, and the amount of time my team has.

I understand time’s short. Our time is short too. It takes time to report issues and create minimal reproducers. It’s frustrating when that time seemingly goes to waste when issues close without resolution.

Perhaps your team could implement a small checklist or procedure when closing issues? To demonstrate that your team’s exercising their “due diligence” if that makes sense? I think that would help a lot in avoiding unintentional “terse” closures.

For example:
1: Demonstrate that the issue is correctly understood, and whether or not it can be reproduced.
2: Give a concrete explanation for how the proposed solution addresses the issue understood in 1.
3: Ensure any outstanding bugs are being tracked somewhere, and list them in the comment leading to issue closure.

**Comment by natevm** [comment]
> I cannot think of what we would add for tests for any of these issues. We do not have infrassture to do a unit test for an internal issue like https://github.com/microsoft/DirectXShaderCompiler/issues/4737.

Microsoft is a big company. It is so big that it owns this very platform itself, GitHub, which has extensive infrastructure for autonomous and continuous unit testing. This is a company that this year alone made $245.1 billion this fiscal year. 

Any constraints imposed on infrastructure for testing purposes is solely a matter of prioritization by MSFT management.

In many cases, a simple GitHub runner can at least verify that a given reproducer generates valid SPIR-V. Perhaps that’s the “due diligence” line here. 

Anything that passes SPIR-V validation but still crashes on any particular device is arguably more the burden of a vendor to correct, or on Khronos to improve validation used for unit testing.

**Comment by s-perron** [comment]
FYI: My team and I work for Google. 

I was referring to sowfware infrastructure. We inherited testing from LLVM, which does not a type of test that will check the problem identified in #4737. The tests generally look at things the user will be able to observe.

**Comment by SamCZ** [comment]
Adreno 740 and 630 on the Quest 3 and 2 need the BDA from uint2 feature

**Comment by devshgraphicsprogramming** [comment]
It already works with Inline SPIR-V 
https://godbolt.org/z/oY68cG77Y

But as always blocked by #4288
