### ISSUE TITLE
Provide built-in that expands to the amount of LDS usage declared (up to the point of built-in usage)

### ISSUE THREAD

**Issue by jeremyong-az** [microsoft/DirectXShaderCompiler#4290]
It would be useful to detect or even fail compilation in cases where group shared memory exceeds a user specified amount.

Example:

```hlsl
groupshared float data[N];

#if GroupSharedSize >= SOME_NUMBER
    #error "Group shared usage exceeds some arbitrary size of our choosing"
#endif
```

There are a few possible uses which may include emitting a compiler error as above, or possibly modifying the shader itself depending. The primary usage (I am guessing) would be to detect situations where a shader's LDS-usage is inadvertently changed to affect occupancy in a meaningful way.

Note that the meaning of `GroupSharedSize` should probably be the size allocated in shared memory _up to the point of usage_ in order to avoid needing multiple (additional) passes to compile the shader itself. That is:

```hlsl
groupshared float datum1;

// GroupSharedSize == 4

groupshared float datum2[2];

// GroupSharedSize = 12
```

**Comment by llvm-beanz** [comment]
Exposing driver-level constants like this is basically an add-on to specialization constants. I think we would address this as part of the language feature request over in [hlsl-specs/16](https://github.com/microsoft/hlsl-specs/issues/16).
