### ISSUE TITLE
[SPIR-V] Failed shader compile

### ISSUE THREAD

**Issue by jbright282** [microsoft/DirectXShaderCompiler#4318]
Hello - we have a shader failing SPIRV compilation with the error

```
Error: generated SPIR-V is invalid: In Logical addressing, variables may not allocate a pointer type
  %38 = OpVariable %_ptr_Function__ptr_Uniform_type_ByteAddressBuffer Function
note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

Shader is attached. It uses a lot of composition via structures and member functions. I've reduced it by hand as much as possible. Reproduced with current nightly. Compiles correctly to DXIL. Compilation is using flags:

```
-O0 -spirv -fvk-use-dx-layout -fspv-reflect -fspv-target-env=vulkan1.1 -T ps_6_0 -E ShaderDomain_Ps
```

thx! -j

[badShader.txt](https://github.com/microsoft/DirectXShaderCompiler/files/8203515/badShader.txt)

**Comment by jaebaek** [comment]
In terms of the pointer or type issues, we rely on the legalization provided by spirv-opt.
Therefore, `-O0` can cause the type related issues.
Could you please try it without `-O0`?

**Comment by jbright282** [comment]
Still fails.  Different error:

```
fatal error: generated SPIR-V is invalid: Reached non-composite type while indexes still remain to be traversed.
  %36 = OpCompositeExtract %_ptr_Uniform_type_ByteAddressBuffer %PerDispatchSrv2 0 3
```

**Comment by jbright282** [comment]
This issue can be closed.  I've got a much tighter repro case that I will log.
