### ISSUE TITLE
Not called function of hit second ray in DXR, when I have used latest compiler

### ISSUE THREAD

**Issue by KawaharaKiyohara** [microsoft/DirectXShaderCompiler#4327]
Thanks response( https://github.com/microsoft/DirectXShaderCompiler/issues/4314#issuecomment-1061292523 ).
I have used the compiler is included WindowsSDK(C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64).
I have try changed the version of compiler to latest,  the error of encoding was fixed.

But it happned new error in algorithm of shadowing in DXR.
Its algorithm is raytracing to light source.
Its algorithm is If the ray hits geometry, the lighting don't calculate.
Please see code of raytracing to light source.

```cpp
// raytracing to light source.
void TraceLightRay(inout RayPayload raypayload, float3 normal)
{
    float hitT = RayTCurrent();
    float3 rayDirW = WorldRayDirection();
    float3 rayOriginW = WorldRayOrigin();

    // Find the world-space hit position
    float3 posW = rayOriginW + hitT * rayDirW;

    RayDesc ray;
    ray.Origin = posW;
    ray.Direction = normalize(float3(0.5, 0.5, 0.2));
    ray.TMin = 0.01f;
    ray.TMax = 100;

    TraceRay(
        g_raytracingWorld,
        0,
        0xFF,
        1,	// No of hit group
        0,
        1,	// No of miss shader
        ray,
        raypayload
    );
}

[shader("closesthit")]
void shadowChs(inout RayPayload payload, in BuiltInTriangleIntersectionAttributes attribs)
{
    // set hit flag
    payload.hit = 1;
}

[shader("miss")]
void shadowMiss(inout RayPayload payload)
{
   // unset hit flag
   payload.hit = 0;
}
```
Look at the picture that was executed by shader that was builded by old compiler.The shadowing has been successful.
![shadow_old_version](https://user-images.githubusercontent.com/17634197/157169678-8d762a94-1735-4b1f-b591-abcf16b96b90.png)
But the shadowing which was executed by shader that was builded by latest compiler has been failed.
![shadow_latest_version](https://user-images.githubusercontent.com/17634197/157169695-23fa4522-af04-4032-8b9f-8691d09658f0.png)
I think shadowMiss and shadowChs function has not called by TraceRay function. Maybe this error was about invoked by no setting payload.hit to value.

(Numper of hitgroup is zero and numper of miss shader is zero has called.)

**Comment by tex3d** [comment]
Does this repro across multiple hardware implementations (AMD and Nvidia for instance)?

Can you make sure you have the latest driver?  There was an issue with earlier NVidia driver versions in handling some valid IR differences in DXIL from an updated compiler, which could explain this.  This is my best guess for a culprit at the moment.

If it appears to be a stable repro across implementations (AMD/NV), then:

Can you identify a problem (or something suspicious) in the DXIL produced by DxCompiler?

The provided shader seems quite trivial, and incomplete.  It would be best if you could provide HLSL source that produces DXIL that looks correct (and works) with the old version of the compiler, then produces different DXIL (potentially wrong, and doesn't work) with the newer version of the compiler.

Thanks!

**Comment by tex3d** [comment]
Closing.

We haven't heard confirmation that this is a compiler issue and not a driver bug.  Please re-open if you have a repro on latest driver and/or across multiple HW implementations.
