### ISSUE TITLE
[Feature Request] Would it be possible to get a command line argument for template expansion?

### ISSUE THREAD

**Issue by hadalhw17** [microsoft/DirectXShaderCompiler#4331]
DXC has a great option to output preprocessed HLSL code with -P flag. As we are getting template support, would it be possible to add a similar option to output HLSL with them expanded?

This is a sample with preprocessor 
![image](https://user-images.githubusercontent.com/23213307/158585846-0f202bc6-47d3-4506-aaa5-969c041e2ebf.png)

Would be nice to get same output with templates
![Templated](https://user-images.githubusercontent.com/23213307/158585898-0d6e4de6-653a-47c1-a6fe-a9e213ff34a9.png)

**Comment by tex3d** [comment]
I'm not seeing what you mean here, since the image on the bottom looks the same as the top.  Did the wrong image link get pasted for the bottom?

Do you mean an expansion of each instantiated template written as code?  Like:
```hlsl
template<>
float4 Test<float4>(in float4 a)
{
 return a + a;
}
```

**Comment by hadalhw17** [comment]
Gosh, my bad, I wanted to post macro version of what this is trying to achieve in the first screenshot, sorry. Yes, I mean pretty much what you have described, perhaps even completely without the template syntax, so something like this:
```HLSL
float4 Test(in float4 a)
{
  return a + a;
}
```
Although I can imagine that this could only be achieved for a fairly constrained set of functions (i.e. return type would not be declarable with a dedicated template), so yes, what you have suggested would be pretty much exactly what we need.
Thanks for the response)

**Comment by jshopf** [comment]
This issue is poorly titled, but I also would love to have the ability to get the preprocessed HLSL out with -P

**Comment by llvm-beanz** [comment]
Templates aren't a preprocessing step. Due to template resolution rules like SFINAE, template substitution has to occur on the AST. It is probably possible to write an AST dumper that would generate source for instantiations, but it wouldn't be clean and it definitely isn't in scope for the HLSL 2021 tooling.

**Comment by tex3d** [comment]
> I also would love to have the ability to get the preprocessed HLSL out with -P

I'm not sure what you mean, I think we already do that.
`-P` already takes a file argument for the output, though it's poorly named as `<value>` in options help:
```
-P <value>            Preprocess to file (must be used alone)
```

**Comment by llvm-beanz** [comment]
@Tex, I think the request there is no to preprocess, but to expand templates (as the issue is requesting).

Template expansion is not part of the C preprocessor, so that isn't really an actionable approach.

**Comment by llvm-beanz** [comment]
After further discussion within the team. Supporting generating source from template instantiations would be a significant amount of tooling effort and is not consistent with how C++ templates are defined. If this is a use case you need, I suspect templates are not the right approach for your use case.

**Comment by tex** [comment]
@llvm-beanz Pinging the tex you wanted :) @tex3d
