### ISSUE TITLE
[SPIR-V] Next step of SPIR-V intrinsics for HLSL

### ISSUE THREAD

**Issue by unit-a-user** [microsoft/DirectXShaderCompiler#4339]
I would to request SPIR-V extension packages for HLSL, alike `#extension` definition, but in more modern form, alike `std` or STL.

**Comment by jaebaek** [comment]
Sorry I do not clearly understand what it means.
We added the [inline SPIR-V](https://github.com/microsoft/DirectXShaderCompiler/issues/3919). Could you please check whether it supports what you need or not?

**Comment by unit-a-user** [comment]
I mean based on intrinsics pre-defined headers, libraries.

**Comment by sudonatalie** [comment]
The SPIR-V backend supports a number of Vulkan-specific functions, enums, etc. via [The Implicit vk Namespace](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#id167), and as @jaebaek mentioned, allows arbitrary "inline SPIR-V" instructions through [vk::ext_*](https://github.com/microsoft/DirectXShaderCompiler/wiki/GL_EXT_spirv_intrinsics-for-SPIR-V-code-gen) attributes. If there are other missing intrinsics, extensions or features not covered that you're interested in, feel free to open new issues for those specifically and they'll be evaluated on a case-by-case basis.

As of right now, we don't have any plans to create an extension package for these types of features though, so if there's some reason the existing mechanism doesn't work for your use case feel free to include that in your request.
