### ISSUE TITLE
[SPIR-V] StructuredBuffer in function arguments produces invalid SPIR-V when used with printf

### ISSUE THREAD

**Issue by heph-dtu** [microsoft/DirectXShaderCompiler#4346]
Hi,

Compiling this code:
```
void unpackIndex(in StructuredBuffer<uint> indices, uint primId, out uint a)
{
    a = indices[primId];
}

StructuredBuffer<uint> g_indexArray : register(t0, space0);

[numthreads(8, 8, 1)]
void main()
{  
    uint a;
    unpackIndex(g_indexArray, 0, a);
    printf("");
}
```
with:
`.\dxc.exe -spirv -T cs_6_4 -fspv-target-env="vulkan1.2" -fspv-extension="SPV_KHR_non_semantic_info" test.hlsl -Fo test.hlsl.spv`
Fails with:
```
fatal error: generated SPIR-V is invalid: In Logical addressing, variables may not allocate a pointer type
  %20 = OpVariable %_ptr_Function__ptr_StorageBuffer_type_StructuredBuffer_uint Function

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

Commenting out either the print statement or removing the StructuredBuffer from the function arguments fixes the issue.

Best Regards,
Henrik

**Comment by Clothoid1** [comment]
I just run also into this issue and arrived at the following trivial reproducer

```
StructuredBuffer<float4> myBuffer : register(t0);

float4 test(StructuredBuffer<float4> aBuffer_in)
{
    return myBuffer[0];
}

[numthreads(8, 8, 1)]
void main()
{
    float4 myRgba = test(myBuffer);
    printf("Test");
}
```

compiled with options
-spirv -T cs_6_4 -fspv-target-env="vulkan1.2"

I just wanted to file a bugreport before i noticed that this issue was already reported.

**Comment by Clothoid1** [comment]
As expected from the error message, it disappears, when using a
vk::RawBufferLoad(address);
call somewhere in your code.

**Comment by s-perron** [comment]
This is a dup of #5136. This seems to work with the fix I have for that issue.
