### ISSUE TITLE
Missing preprocessor defines causes rewriter to incorrectly remove types

### ISSUE THREAD

**Issue by tomjohnstone** [microsoft/DirectXShaderCompiler#4357]
In the following example, TestStruct is stripped and the variable declaration causes the shader to fail to compile.

```
// dxr -E CSMain -remove-unused-globals test.hlsl
struct TestStruct
{
	uint Value;
};

TestStruct DoSomething()
{
	TestStruct value = (TestStruct)0;
	return value;
}

[numthreads(1,1,1)]
void CSMain()
{
	TestStruct orNot;
#if ENABLED
	orNot = DoSomething();
#endif
}

**Comment by llvm-beanz** [comment]
The rewriter can't see permutations of preprocess or defines. That is a limitation of the AST design that isn't solvable without a huge architectural revamp. We're not going to dedicate resources to that scale of project in the DXC codebase as we are working to move to Clang for HLSL.
