### ISSUE TITLE
Support IDxcContainerReflection on Linux

### ISSUE THREAD

**Issue by manon-traverse** [microsoft/DirectXShaderCompiler#4358]
IDxcContainerReflection is currently only implemented on the Windows build, since the headers `d3d11shader.h` and `d3d12shader.h` are included. These headers could be added to this repo for Linux support. (We have already done this for `d3d12shader.h` in Rust.)

The use case for this feature is that I would like to run reflection during offline shader compilation on a Linux server.

I am willing to open a PR for this, but would like to know if this is something that the maintainers would like to support or not.

https://github.com/microsoft/DirectXShaderCompiler/blob/2dc067b561f17d09d8012a1ded05bf0f6253fea5/lib/HLSL/DxilContainerReflection.cpp#L39

**Comment by gongminmin** [comment]
Or, take the open-sourced version of d3d12shader.h from DirectX 12 Agility SDK?
