### ISSUE TITLE
Make "error: Loop must have break." a warning that can be disabled instead

### ISSUE THREAD

**Issue by amaiorano** [microsoft/DirectXShaderCompiler#4369]
I'm a developer on [Tint](https://dawn.googlesource.com/tint/), the WebGPU WGSL transpiler in Chrome, and one of the issues we've hit is that when users write infinite loops in WGSL, we cannot easily detect this and produce HLSL that fails to compile with DXC. Please see [this issue](https://bugs.chromium.org/p/tint/issues/detail?id=1038).

Would it be possible to change "error: Loop must have break." to a warning that can be disabled instead?

**Comment by llvm-beanz** [comment]
I don't think we should make HLSL less safe to support generating HLSL from other toolchains. That seems like a net loss for our users.
