### ISSUE TITLE
[SPIR-V] SPV_KHR_ray_query not permitted to use when compling RayGen Shaders

### ISSUE THREAD

**Issue by Chaphlagical** [microsoft/DirectXShaderCompiler#4385]
I try to use dxc to compile hlsl ray tracing shader, but got issue:
```
error: SPIR-V extension 'SPV_KHR_ray_query' required for SPV_KHR_ray_query but not permitted to use
```
It seems the error only occurs when compiling raygen shaders. And my another rtx3060 pc has no such issue.

Current Platform:
* Windows 10, VS2019
* CPU AMD Ryzen 5 3500X 6-Core Processor 
* GPU NVIDIA GeForce RTX 2060 SUPER

Example shader:

``` hlsl
RaytracingAccelerationStructure rs : register(t0);
RWTexture2D<float4> image : register(u1);

struct CameraProperties
{
	float4x4 viewInverse;
	float4x4 projInverse;
};
cbuffer cam : register(b2) { CameraProperties cam; };

struct Payload
{
[[vk::location(0)]] float3 hitValue;
};

[shader("raygeneration")]
void main()
{
	uint3 LaunchID = DispatchRaysIndex();
	uint3 LaunchSize = DispatchRaysDimensions();

	const float2 pixelCenter = float2(LaunchID.xy) + float2(0.5, 0.5);
	const float2 inUV = pixelCenter/float2(LaunchSize.xy);
	float2 d = inUV * 2.0 - 1.0;
	float4 target = mul(cam.projInverse, float4(d.x, d.y, 1, 1));

	RayDesc rayDesc;
	rayDesc.Origin = mul(cam.viewInverse, float4(0,0,0,1)).xyz;
	rayDesc.Direction = mul(cam.viewInverse, float4(normalize(target.xyz), 0)).xyz;
	rayDesc.TMin = 0.001;
	rayDesc.TMax = 10000.0;

	Payload payload;
	TraceRay(rs, RAY_FLAG_FORCE_OPAQUE, 0xff, 0, 0, 0, rayDesc, payload);

	image[int2(LaunchID.xy)] = float4(payload.hitValue, 0.0);
}
```

**Comment by sudonatalie** [comment]
Can you provide the command line arguments used to compile the shader and the result of `dxc --version`? It looks like it's working as intended (I'm able to compile the above shader successfully), but this failure is dependent on the target SPIR-V environment and the version of DXC you're running since recent changes have been made to relax the ray query requirements where possible.

**Comment by Chaphlagical** [comment]
> Can you provide the command line arguments used to compile the shader and the result of `dxc --version`? It looks like it's working as intended (I'm able to compile the above shader successfully), but this failure is dependent on the target SPIR-V environment and the version of DXC you're running since recent changes have been made to relax the ray query requirements where possible.

dxc version: dxcompiler.dll: 1.7 - 1.6.0.3405
arguments:
	-E
	main
	filename
	-T
	lib_6_6
	-H
	-spirv
	-fspv-target-env=vulkan1.2
	-fspv-extension=SPV_KHR_ray_tracing
	-fspv-extension=SPV_KHR_shader_draw_parameters
	-fspv-extension=SPV_EXT_descriptor_indexing
	-fspv-extension=SPV_EXT_shader_viewport_index_layer
	-fspv-extension=SPV_NV_mesh_shader

**Comment by Chaphlagical** [comment]
Thanks

**Comment by natevm** [comment]
@sudonatalie Can we open this issue again? I am running into an issue where NVIDIA's A100 architecture does not support ray queries, but does support ray_tracing. Because DXC assumes both are always available together, DXC fails to generate valid SPIRV for A100 systems.

**Comment by sudonatalie** [comment]
@natevm Thanks for reporting and sorry for the delay acknowledging. Reopened.

**Comment by sudonatalie** [comment]
@Keenuts is working on a SPIR-V opt capability trimming pass that should be able to be extended to handle this case once it's fully integrated with DXC.

**Comment by natevm** [comment]
Once implemented, I'd be happy to test the pass out. Thanks for the update.
