### ISSUE TITLE
[SPIR-V] Compile error with struct inheritance

### ISSUE THREAD

**Issue by jbright282** [microsoft/DirectXShaderCompiler#4391]
Shader (attached) uses struct inheritance.  Compiles fine to DXIL.  Fails SPIRV.  
Removing inheritance (combining DataBuffer & DataBufferBase into one struct) succeeds.

Cmd line

```
dxc -spirv -fvk-use-dx-layout -fspv-reflect -fspv-target-env=vulkan1.1 -T ps_6_0 -E ShaderDomain_Ps -Fo spirv_bad.out badShader.hlsl
```
[badShader.txt](https://github.com/microsoft/DirectXShaderCompiler/files/8478821/badShader.txt)

Error:
```
fatal error: generated SPIR-V is invalid: Reached non-composite type while indexes still remain to be traversed.
  %23 = OpCompositeExtract %_ptr_Uniform_type_ByteAddressBuffer %PerDispatchSrv2 0 3

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

**Comment by jaebaek** [comment]
@jbright282 thank you for reporting this issue. We will take a look.
