### ISSUE TITLE
Boolean swizzle not working

### ISSUE THREAD

**Issue by teoxoy** [microsoft/DirectXShaderCompiler#4393]
Trying to swizzle a boolean returns the error below. This seems to work properly with FXC.

```hlsl
[numthreads(1, 1, 1)]
void main()
{
    bool3 b = true.xxx; // error: expected ';' at end of declaration
    //            ^
    //            ;
    bool3 b2 = (true).xxx; // works
}
```

https://shader-playground.timjones.io/92aa0a8564591f041ac11093ca070738

**Comment by damyanp** [comment]
Although FXC and DXC disagree here, we believe that the way that DXC handles this is how we want it to work going forward, and as we write the HLSL spec we'll make this more clear.
