### ISSUE TITLE
Crash when compilling with -Zi option

### ISSUE THREAD

**Issue by Try** [microsoft/DirectXShaderCompiler#4394]
Stumbled across a few issues, when porting my home project to new compiler. 
command line;
```
.\dxc.exe -E main -T vs_6_0 -Qstrip_reflect -Zi .\tst.vert
```
dxc version: v1.6.2112
with old compiler(`D3DCompile`) works fine.  

shader: https://pastebin.com/FptHSLG5
Hopefully you can fix it, Thanks!

**Comment by damyanp** [comment]
https://godbolt.org/z/s1TsscGn8

This seems to be fixed in latest DXC.
