### ISSUE TITLE
[SPIR-V] About `GL_EXT_buffer_reference` writing... (`RawBufferStore`)?

### ISSUE THREAD

**Issue by unit-a-user** [microsoft/DirectXShaderCompiler#4408]
I seen `RawBufferLoad`, but how about method, alike `RawBufferStore`?

**Comment by jaebaek** [comment]
@unit-a-user Thank you for reporting this issue. We will add it to our TODO list.

**Comment by unit-a-user** [comment]
Currently, it released?

**Comment by natevm** [comment]
This should be addressed with PR #4573. I think this issue can be closed.
