### ISSUE TITLE
[SPIR-V] Resource Shift doesn't work on non-zero spaces

### ISSUE THREAD

**Issue by nickyc95** [microsoft/DirectXShaderCompiler#4411]
Hi,

I am running into an issue where resources that are bound to space1 in a shader are not being shifted correctly. If I set them to space0 then the shift applies correctly..

ShaderPlayground Example:
https://shader-playground.timjones.io/f86af4193eb000111e230659db41ea3e

```
RWStructuredBuffer<int> correct : register(u0, space0);
RWStructuredBuffer<int> incorrect : register(u0, space1);

struct PSInput
{
	float4 color : COLOR;
};

float4 PSMain(PSInput input) : SV_TARGET
{
	return input.color;
}
```
Running DXC with command `-fvk-u-shift 1000 0`  results in the following OpDecorates in SPIR-V

```
 OpDecorate %correct DescriptorSet 0
 OpDecorate %correct Binding 1000
 OpDecorate %incorrect DescriptorSet 1
 OpDecorate %incorrect Binding 0
```

Expected:
correct -- Descriptor Set 0, Binding 1000
incorrect -- Descriptor Set 1, Binding 1000

Tested on Latest Git Release, Latest AppVeyor Artifact and on ShaderPlayground = Same Results.

Thanks!

**Comment by sudonatalie** [comment]
This is working as intended. `-fvk-u-shift N M` shifts by `N` the inferred binding numbers for all resources in `u`-type registers **of space `M`**. If you need to shift the inferred binding numbers for more than one space, provide more than one such option. If you need to shift the inferred binding numbers for all sets, use `all` as `M`. See [HLSL register and Vulkan binding](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#hlsl-register-and-vulkan-binding) for explanation and examples.
