### ISSUE TITLE
Trouble building arm64

### ISSUE THREAD

**Issue by jeikabu** [microsoft/DirectXShaderCompiler#4435]
Trying to target arm64, but it looks like I've done something wrong because there's numerous errors like:
```
DirectXShaderCompiler/include/llvm/IR/Intrinsics.td(481,1): error G2CA03994: Record `int_adjust_trampoline' does n
ot have a field named `IntrProperties'! [DirectXShaderCompiler\hlsl.bin\include\llvm\IR\intrinsics_gen.vcxproj]

DirectXShaderCompiler/include\llvm/Option/OptParser.td(129,1): error GB330E9B5: Record `INPUT' does not have a fie
ld named `Values'! [DirectXShaderCompiler\hlsl.bin\include\dxc\Support\TablegenHLSLOptions.vcxproj]
```

I've built llvm-tblgen and clang-tblgen from LLVM 6.0 since it's the last version that still has `-gen-intrinsics`.

Then build DirectXShaderCompiler with:
```
utils\hct\hctstart.cmd ..\DirectXShaderCompiler hlsl.bin
hctbuild -arm64 -vs2019 -tblgen <llvm-project>\build\Release\bin\
```

There's [this issue](https://github.com/microsoft/DirectXShaderCompiler/issues/2890) that makes me wonder if arm64 is actually supported.

**Comment by hekota** [comment]
Hello jeikabu,

Building the compiler for arm64 is supported. Could you please try building -x64 first (in a bin separate directory) and then use the tblgen from there for the -arm64 build?

**Comment by jeikabu** [comment]
Yes, stumbled upon that.  Something like this works:
```
utils\hct\hctstart.cmd . hlsl.bin\x64
hctbuild -x64 -vs2019 -release
utils\hct\hctstart.cmd . hlsl.bin\arm64
hctbuild -arm64 -vs2019 -release -tblgen <absolute path>\hlsl.bin\x64\Release\bin\
```
But, DXIL.dll is missing.  It's in the release packages, but can't see where it's generated here.

**Comment by jeikabu** [comment]
I see DXIL.dll isn’t in the build artifacts, it’s just in the releases.  Looks like I’ve got x86/x64 dlls in the Windows SDKs.  But that begs the question, where does an arm64 DXIL.dll come from?

**Comment by hekota** [comment]
Arm64 dlls are not getting officially released. We are working on improving our test infrastructure, it should be included in the next release.

**Comment by MarkIngramUK** [comment]
> Yes, ARM64 binaries should be included in our next public GitHub release, and eventually in the Windows SDK as well.

Amazing news. Thanks!

**Comment by jph7669** [comment]
> Arm64 dlls are not getting officially released. We are working on improving our test infrastructure, it should be included in the next release.

Hi, I have tried to build arm64 and the .dll files are built except the dxil.dll file.
Could we build dxil.dll now with the latest codebase? Thanks.
