### ISSUE TITLE
[SPIR-V] use LocalSizeId for VK1.3 instead of WorkgroupSize (check if we have to use LocalSizeId or LocalSize)

### ISSUE THREAD

**Issue by jaebaek** [microsoft/DirectXShaderCompiler#4438]
[SPIR-V spec](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html) says "**WorkgroupSize**
[Deprecated](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#Deprecation) (use **LocalSizeId** [Execution Mode](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#Execution_Mode) instead)."

We currently do not use `LocalSizeId` even when it is VK1.3. We have to doublecheck if it is fine to use `LocalSize` instead of `LocalSizeId`.

Note that similar to  https://github.com/KhronosGroup/glslang/issues/2934, we have to generate LocalSize Execution Mode when possible (all local size components are literal constants) and LocalSizeId Execution Mode otherwise because LocalSizeId Execution Mode requires additional hardware support.

**Comment by sudonatalie** [comment]
DXC is already correctly generating `LocalSize`, which is not deprecated, and we haven't come across a case as far as I know where we can't use literal constants and `LocalSizeId` is needed. Until/unless a functional need arises to implement the latter, the former has been sufficient for DXC, so no change is needed for VK1.3 support, and the issue in https://github.com/KhronosGroup/glslang/issues/2934 doesn't affect us until we do need `LocalSizeId`.

(I looked into this in January as part of our "VK1.3/SPIRV1.6 support in DXC" audit.)
