### ISSUE TITLE
Disassembly feature request: Annotations for entrypoint properties

### ISSUE THREAD

**Issue by jenatali** [microsoft/DirectXShaderCompiler#4447]
Looking at HLSL source for a compute shader, the annotation for thread group size is pretty prominent, e.g.:
```hlsl
[numthreads(32, 1, 1)]
```

But looking at the disassembly of the generated DXIL, it can be really difficult to find that same information, since it just ends up as unlabeled metadata, e.g.:
```
!16 = !{i32 32, i32 1, i32 1}
```

It'd be great if metadata that contributes to entrypoint properties could be surfaced more explicitly, like the signature or resource information is in comments before the actual shader code.

**Comment by bob80905** [comment]
The other entry point properties were added and tested with:
https://github.com/microsoft/DirectXShaderCompiler/pull/4491
