### ISSUE TITLE
[Regression] Internal terminal error when assigning member of typed buf struct

### ISSUE THREAD

**Issue by pow2clk** [microsoft/DirectXShaderCompiler#4448]
An assert and internal error are hit when compiling the following simple, invalid shader:

```hlsl
// RUN: dxc -T cs_6_0 %s
struct TexCoords {  uint s, t, r, q; };

RWBuffer<TexCoords> g_buf;

[numthreads(8,8,1)]
void main( ) {
  g_buf[0].q = 1;
}
```
The assert fires in TranslateHLSubscript because a rawbufferstore operation is found to a typed buffer and there is no case statement for it.

Passed on the Dec 2021 release, though it produced validation errors including "store on typed uav must write to all four components of the UAV." So we need an earlier error for this invalid usage rather than a crash

**Comment by llvm-beanz** [comment]
Looks like we get a validation error now [see godbolt](https://godbolt.org/z/8n6EWEqTh). Do we want to do something to improve this error?

**Comment by pow2clk** [comment]
The error we get now is "buffer load/store only works on Raw/Typed/StructuredBuffer." That's not as helpful as the older error. Further, I was hoping this could get detected before validation.
