### ISSUE TITLE
Compiler crash on ternary operator

### ISSUE THREAD

**Issue by charles-epic** [microsoft/DirectXShaderCompiler#4463]
Hi,

We are getting crash when a function return result with a ternary operator with matrix constructor. The output of the compiler is:

`Internal compiler error: access violation. Attempted to read from address 0x0000000000000018`

Here is the repro snippet:

```
struct FData
{
	float3 WorldNormal;
	float Anisotropy;
	float3x3 TangentBasis;
};

float3x3 GetTangentBasis(FData In)
{
	// This works
//	if (In.Anisotropy != 0) { return In.TangentBasis; } else { return float3x3(In.WorldNormal,In.WorldNormal,In.WorldNormal);}

	// This does not work
	return In.Anisotropy != 0 ? In.TangentBasis : float3x3(In.WorldNormal,In.WorldNormal,In.WorldNormal);
}


[numthreads( 64 , 1, 1)]
void MainCS(uint GroupThreadId : SV_GroupThreadID)
{
	const FData Data = (FData)0;
	const float3x3 TangentBasis = GetTangentBasis(Data);
}
```

This is compiled with SM6.6 and the compiler flags /Zpr /O3 /Zsb /Qembed_debug /Zi /Fd

Let me know if you need more details

**Comment by charles-epic** [comment]
I should have look more closely at the existing ticket, as it seems to already been reported and now fixed: https://github.com/microsoft/DirectXShaderCompiler/issues/4434

**Comment by llvm-beanz** [comment]
Yep, looks like this should be resolved. 😄
