### ISSUE TITLE
[D3D12] Support buffer reference for DirectX 12? 

### ISSUE THREAD

**Issue by ghost** [microsoft/DirectXShaderCompiler#4469]
I would like Device Buffer Address or reference in shaders to appear in Shader Model 6.8. In the Vulkan API, for example, this was brought together with rays tracing. I want a similar function to appear in DirectX 12 after a few years (and this time has come). And no, this is not Dynamic Resource, I mean something else. This is what you can shift the address.

**Comment by StarsX** [comment]
I just imagined this before. If a raw buffer index could be uint64, and root uav virtual address setting could be 0, this would be just a memory address pointer.

**Comment by Tobski** [comment]
Ack I missed this but I just raised https://github.com/microsoft/DirectXShaderCompiler/issues/4732 which attacks this problem same problem, so this may actually be kind of a duplicate sorry 😬

If a repo maintainer wants me to merge that issue into here please let me know...

**Comment by damyanp** [comment]
This is being tracked in the hlsl-specs repo https://github.com/microsoft/hlsl-specs/issues/17.
