### ISSUE TITLE
WaveBallot compilation error

### ISSUE THREAD

**Issue by ghost** [Microsoft/DirectXShaderCompiler#449]
Hello. When I try to do 
```
uint64_t ballot(
    in uint3 WorkGroupID, 
    in uint3 LocalInvocationID, 
    in bool val) {
    uint64_t result = WaveBallot(val);
    return result;
}
```
I getting many errors, such as a not defined identifier (bool typed value).

**Comment by dmpots** [comment]
It looks like the function was renamed to [WaveActiveBallot](https://github.com/Microsoft/DirectXShaderCompiler/wiki/Wave-Intrinsics#uint4-waveactiveballot-bool-expr-) in the final version. Using `WaveActiveBallot` compiles successfully for me.

**Comment by capitalknew** [comment]
I just porting my GLSL code to SM5.0-6.0 "as is". Yes, with ARB_gpu_shader_ballot

**Comment by marcelolr** [comment]
Also, those docs _lie._ Updating them in a minute. WaveActiveBallot returns a uint4, not a uint64_t.

I do wonder about your use case though. Can't you use some of the other wave intrinsic operations? They provide higher-level operations that can in principle be easier to optimize, and are less sensitive to actual wave size.

**Comment by marcelolr** [comment]
Actually, the docs are right - they already declare the return type as uint4. Nothing to see here (although you'll probably want to update the type in your sources to account for that).

**Comment by capitalknew** [comment]
Sorry, HLSL have no bits extract function? Also, my shaders compilation crashes.

**Comment by marcelolr** [comment]
In HLSL, there are a few intrinsics to deal with high/low bits or reverse them efficiently, but generally you can use bitwise operators for this kind of work.

Do you have a repro you can share for the crash?

**Comment by capitalknew** [comment]
I lost my crash cases, bug reported 4 months ago, and get make new tests only when I begin development of DirectX 12 version of my ray tracer.

**Comment by marcelolr** [comment]
If you run into any crashes again, please let us know - a repro is needed to make it actionable on our end. Sorry I should have called this out earlier.
