### ISSUE TITLE
[SPIR-V] Compile and generate reflection information for shader in a single command.

### ISSUE THREAD

**Issue by wookie41** [microsoft/DirectXShaderCompiler#4496]
Hello.

I've been trying to get `dxc` to compile to SPIRV, stripping reflection infro from the shader and generate reflection info for SPIRV-reflect using a single command like this:

```
dxc -Qstrip_reflect -spirv -fspv-reflect -fspv-target-env=vulkan1.3 -HV 2021 -T ps_6_7 -Fre reflect/base.frag.ref -Fo bin/base.frag.spv base.frag.hlsl
```

But instead of two files - one `.ref` and `.spv`, I only get the `.spv` one, with (what it looks like) reflection info in it, as SPIRV-Reflect is able to read the reflection info from it.
I've been trying to do it according to the description in [this issue](https://github.com/microsoft/DirectXShaderCompiler/issues/2749), but wasn't able to and this issue was closed, as the OP was using the SDK and I have to use the commandline.

Any suggestions?

**Comment by sudonatalie** [comment]
The `-Qstrip_reflect` and `-Fre` options are not currently supported by the SPIR-V backend and we don't have any current plans to implement them, although PR contributions are welcome and will be reviewed.

As a workaround, you can follow up your compilation with `-fspv-reflect` by running `spirv-opt --strip-nonsemantic` on the results to output a SPIR-V module with all reflection information removed. `spirv-opt` is distributed as part of the Vulkan SDK and at [KhronosGroup/SPIRV-Tools](https://github.com/KhronosGroup/SPIRV-Tools).

**Comment by s-perron** [comment]
Considering this complete because there is a working solution using spirv-opt as a post processor to remove the reflection information. We do not intend to support the other options.
