### ISSUE TITLE
[SPIRV] When using a texture as an input argument for a method, the generated binary looses information

### ISSUE THREAD

**Issue by BobTailor** [microsoft/DirectXShaderCompiler#4502]
When using DXC to generate Spir-v binaries, we noticed that a small change in the code can dramatically change the generated binaries.

Lets say you have a working HLSL compute shader, it compiles fine to Spir-v and you can nicely debug these generated shaders and nicely cross compile them to another Shader language, e.g. Metal Shaders.

Lets say you have a texture
`Texture3D<float> myTexture : register(t0);`

and you are accessing this texture somewhere in your code
`float aValue = myTexture[uint3(aIndex)];`

When now making a small change in your code by adding a method 

```
float testMethod(Texture3D<float> aTexture_in, uint3 aIndex_in)
{
	float aValue = aTexture_in[aIndex_in];
	return aValue;
}
```

and accessing your texture using this method
`float aValue = testMethod(myTexture, uint3(aIndex));`

the genarated Spir-v binary looses a lot of information - not just at those place where you call this method, but everywhere in your shader!

Suddenly e.g. all your local variable names have vanished in the Spir-V file and when debugging or cross compiling you get shaders that are functionally still correct, but have lost all local variable names and many methods you have called.

Here is an example:
```

Texture3D<float> myTexture : register(t0);
RWStructuredBuffer<int> myResultBuffer : register(u1);

float testMethod(Texture3D<float> aTexture_in, uint3 aIndex_in)
{
	float aValue = aTexture_in[aIndex_in];
	return aValue;
}

uint3 Compute(uint3 aIndex_in, int aScalar_in)
{
	uint3 aResult = aIndex_in;
	aResult[0] += aScalar_in;
	return aResult;
}

[numthreads(8, 8, 1)]
void main(uint3 aDispatchThreadID : SV_DispatchThreadID)
{
    uint3 aIndex = aDispatchThreadID;
    aIndex = Compute(aIndex, 10);
    
    //float aValue = testMethod(myTexture, uint3(aIndex));
    float aValue = myTexture[uint3(aIndex)];
    myResultBuffer[aValue] = 1;
}
```

when compiling this to Spir-v and then using spriv-cross to compile this back to HLSL one gets
```

RWByteAddressBuffer myResultBuffer : register(u1, space0);
RWByteAddressBuffer counter_var_myResultBuffer : register(u2, space0);
Texture3D<float4> myTexture : register(t0, space0);

static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

uint3 Compute(uint3 aIndex_in, int aScalar_in)
{
    uint3 aResult = aIndex_in;
    aResult.x += uint(aScalar_in);
    return aResult;
}

void src_main(uint3 aDispatchThreadID)
{
    uint3 aIndex = aDispatchThreadID;
    uint3 param_var_aIndex_in = aIndex;
    int param_var_aScalar_in = 10;
    aIndex = Compute(param_var_aIndex_in, param_var_aScalar_in);
    float aValue = myTexture.Load(int4(aIndex, 0u)).x;
    myResultBuffer.Store(uint(aValue) * 4 + 0, uint(1));
}

void comp_main()
{
    uint3 param_var_aDispatchThreadID = gl_GlobalInvocationID;
    src_main(param_var_aDispatchThreadID);
}

[numthreads(8, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
```

when making a change in your shader:
```
    float aValue = testMethod(myTexture, uint3(aIndex));
    //float aValue = myTexture[uint3(aIndex)];
```

and cross compiling again, once receives:
```

RWByteAddressBuffer myResultBuffer : register(u1, space0);
Texture3D<float4> myTexture : register(t0, space0);

static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    uint3 _26 = gl_GlobalInvocationID;
    _26.x += uint(10);
    myResultBuffer.Store(uint(myTexture.Load(int4(_26, 0u)).x) * 4 + 0, uint(1));
}

[numthreads(8, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
```

In the generated Spir-v file one can see that now all entries on local variables like
```
OpName %aValue "aValue"
OpName %Compute "Compute"
```
are missing.

This can also very nicely be reproduced using the shader-playground.
Compile options used:
Format Output: SPIR-V
Optimization Level: 0
Target Profile: CS_6_6

**Comment by PanosK92** [comment]
Came here to report the same thing after my shader reflection system failed on multiple shaders.

**Comment by pow2clk** [comment]
Hi @kuhar and @sudonatalie! SPIRV issue

**Comment by sudonatalie** [comment]
Hi @BobTailor, thanks for reporting!

While the compiler does generate some `OpName` instructions for debugging purposes, we don't make any guarantees about how and when they are generated, and they're subject to change without notice. For information on the decorations that can be safely used for this purpose, please refer to the documentation on [Reflection](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst#reflection). If you have a specific use case that isn't currently satisfied, then we'd be happy to consider a feature request for additional reflection needs or review PR contributions, but there isn't enough information in this issue to understand the larger context of the problem, so for that reason I'm going to close this issue.

(If you're wondering why this happens for a "small change" in the code: In this particular case, it looks like the source code variable names are preserved through the initial stages of compilation, but the use of a method call makes additional [legalization](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst#legalization) steps necessary to generate valid SPIR-V, and the spirv-opt legalization passes that are necessary to generate correct SPIR-V happen to remove some non-semantic information in the process.)
