### ISSUE TITLE
compile fails when using clang-cl in visual studio

### ISSUE THREAD

**Issue by MarkaRagnos0815** [microsoft/DirectXShaderCompiler#4511]
I am trying to compile the project using clang 13 (and 14)
I used clang 14 standalone through a custom make file and switched compiler toolchain from v143 to clang-cl

- I created a visual studio solution using hctbuild
- I opend the solution
- switched toolset to clang (llvm 13)

the following error appears when compiling clang libraries

`
Build started...
1>------ Build started: Project: clangAnalysis, Configuration: Debug x64 ------
1>In file included from C:\Projects\private\tools\DirectXShaderCompiler\tools\clang\lib\Analysis\AnalysisDeclContext.cpp:15:
1>In file included from C:\Projects\private\tools\DirectXShaderCompiler\tools\clang\include\clang/Analysis/AnalysisContext.h:18:
1>In file included from C:\Projects\private\tools\DirectXShaderCompiler\tools\clang\include\clang/AST/Decl.h:17:
1>In file included from C:\Projects\private\tools\DirectXShaderCompiler\tools\clang\include\clang/AST/APValue.h:17:
1>In file included from C:\Projects\private\tools\DirectXShaderCompiler\tools\clang\include\clang/Basic/LLVM.h:22:
1>In file included from C:\Projects\private\tools\DirectXShaderCompiler\include\llvm/Support/Casting.h:19:
1>In file included from C:\Projects\private\tools\DirectXShaderCompiler\include\llvm/Support/ErrorHandling.h:18:
1>In file included from C:\Projects\private\tools\DirectXShaderCompiler\include\llvm/ADT/StringRef.h:13:
1>In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\algorithm:11:
1>In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\xmemory:14:
1>In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\new:11:
1>In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\exception:12:
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\type_traits(1101,63): error : incomplete type 'clang::DeclContext::udir_iterator' used in type trait expression
1>C:\Projects\private\tools\DirectXShaderCompiler\include\llvm/ADT/iterator.h(159,17): message : in instantiation of template class 'std::is_base_of<llvm::iterator_adaptor_base<clang::DeclContext::udir_iterator, clang::DeclContextLookupResult::iterator, std::random_access_iterator_tag, clang::UsingDirectiveDecl *, long long>, clang::DeclContext::udir_iterator>' requested here
1>C:\Projects\private\tools\DirectXShaderCompiler\include\llvm/ADT/iterator.h(145,7): message : while substituting deduced template arguments into function template 'iterator_adaptor_base' [with U = const llvm::iterator_adaptor_base<clang::DeclContext::udir_iterator, clang::DeclContextLookupResult::iterator, std::random_access_iterator_tag, clang::UsingDirectiveDecl *, long long> &]
1>C:\Projects\private\tools\DirectXShaderCompiler\tools\clang\include\clang/AST/DeclBase.h(1678,10): message : while declaring the implicit copy constructor for 'udir_iterator'
1>C:\Projects\private\tools\DirectXShaderCompiler\tools\clang\include\clang/AST/DeclBase.h(1678,10): message : definition of 'clang::DeclContext::udir_iterator' is not complete until the closing '}'
1>Done building project "clangAnalysis.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by gongminmin** [comment]
I happened to work on this last week. After fix a dozen places, it compiles and runs well. This is the draft commit https://github.com/gongminmin/DirectXShaderCompiler/commit/a81d69571e9136a9b6301a2dd77917e21c9605f3 . I'm now decomposing changes to several PRs. 

For this particular one, in include/llvm/ADT/iterator.h, you need to replace 
```
explicit iterator_adaptor_base(
      U &&u,
      typename std::enable_if<
          !std::is_base_of<typename std::remove_cv<
                               typename std::remove_reference<U>::type>::type,
                           DerivedT>::value,
          int>::type = 0)
```
to

```
explicit iterator_adaptor_base(
      U &&u,
      typename std::enable_if<
          !std::is_convertible<DerivedT*, 
              typename std::remove_cv<
                  typename std::remove_reference<U>::type>::type*>::value,
          int>::type = 0)](url)
```

At that moment, iterator_adaptor is not a complete type. It can't be used in std::is_base_of. But its pointer is completed. That makes std::is_convertible work.

**Comment by MarkaRagnos0815** [comment]
thanks and works

**Comment by pow2clk** [comment]
Thanks @gongminmin!
