### ISSUE TITLE
Feature Request: GatherLevel()

### ISSUE THREAD

**Issue by MrDomS** [microsoft/DirectXShaderCompiler#4523]
Recently saw the HLSL 6.7 spec, and I am very happy to see SampleCmpLevel being exposed. 
Would it be possible to get access to a GatherLevel() system? Even if it is integer mip levels it would be very useful for example, accessing quads of HZB data in a compute shader.

**Comment by StarsX** [comment]
Me too. Gather() is useful for customized bilateral filters. Furthermore, if there could be a method to collect the bilinear weights for the gathered samples, it would be v”much more convenient.

**Comment by llvm-beanz** [comment]
@StarsX filed this issue on HLSL-specs, we'll use that to track the feature request:

https://github.com/microsoft/hlsl-specs/issues/35
