### ISSUE TITLE
Is for loop variable hoisting a bug or a feature?

### ISSUE THREAD

**Issue by Nielsbishere** [microsoft/DirectXShaderCompiler#4548]
```hlsl
struct PSInput
{
    float4 color : COLOR;
};

float4 PSMain(PSInput input) : SV_TARGET
{
    
    for(int i = 0; i < 9; ++i)
        input.color += i;
    
    return input.color * float(i == 9);
}
```
The example above compiles to input.color += 36 (nth triangle number of 9). C-like languages generally don't hoist for loop variables like this, so is this a specific HLSL feature or a bug? If I multiply by i == 8 it will optimize to store 0, meaning that the compiler knows that i comes from the for loop and knows its value.

**Comment by llvm-beanz** [comment]
These optimizations are valid both in C and HLSL, you can see this example here where Clang-14 does the same optimization:

https://godbolt.org/z/4nn4fTsTc

**Comment by Nielsbishere** [comment]
Interesting, though it's non standard there I think or MSVC ignores the standard again

**Comment by llvm-beanz** [comment]
The language standard doesn't dictate required optimizations, it only dictates the rules around final behavior. Any optimization that preserves those rules is valid to perform or not. Both Clang by performing the optimization and MSVC by not performing it are conforming to the C standard.
