### ISSUE TITLE
dxc should report error when mix packoffset elements with nonpackoffset elements in a cbuffer

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#4561]
cbuffer CB {
  float a;
  float b:packoffset(c1.y);
}

float main() : SV_Target {
  return a + b;
}

FXC will report error " cannot mix packoffset elements with nonpackoffset elements in a cbuffer"

**Comment by damyanp** [comment]
This is a breaking change that we shouldn't make in DXC.  We should consider what the right thing to do in Clang is.
