### ISSUE TITLE
[CWE-78] Command Injection ()subprocess

### ISSUE THREAD

**Issue by imhunterand** [microsoft/DirectXShaderCompiler#4564]
## About issue 
Unsanitized input from a command line argument flows into subprocess.Popen, where it is used as a shell command. This may result in a Command Injection vulnerability.

## Endpoint a vulnerable:
```python
    output_file_orig = get_output_file(arguments_a)
    if output_file_orig is None:
        output_file_orig = derive_output_file(arguments_a)

    p = subprocess.Popen(arguments_a, env=my_env, shell=is_windows())
```
Another a vulnerable code:
```python
        print "Error: Project directory is missing: %s" % Dir
        sys.exit(-1)
        
    # Build the project.
    SATestBuild.testProject(ID, BuildMode, IsReferenceBuild=True, Dir=Dir)
```

[9e56b51775d817f0eabc524faad84d2943dc22eb/tools/clang/utils/check_cfc/check_cfc.py](https://github.com/EpicGames/DirectXShaderCompiler/tree/9e56b51775d817f0eabc524faad84d2943dc22eb/tools/clang/utils/check_cfc/check_cfc.py#L351)

[Reported💜 by imhunterand (Pwn2Own)](https://github.com/imhunterand)

**Comment by pow2clk** [comment]
These are not files that are used by this project, nor will they ever be. They were inherited from LLVM and even though we don't use them, we kept them around with the idea that they would make merging from upstream easier. Even though that's no longer the plan, we're not going to remove them.

The first check_cfc.py instance seems unaltered in https://github.com/llvm/llvm-project. You might report it there if you're interested. This code is in use there AFAIK
