### ISSUE TITLE
xml.etree.ElementTree is considered insecure

### ISSUE THREAD

**Issue by imhunterand** [microsoft/DirectXShaderCompiler#4565]
## About issue vulnerabilities:
xml.etree.ElementTree.fromstring is considered insecure. Use an analog from the defusedxml package.

## Endpoint of vulnerable
```python
    global xmlheader
    text = text.replace('xmlns=', 'xmlns_commented=')
    xmlheader = text[:text.find('\n')+1]
    # TODO: read xml and return xml root
    return ET.fromstring(text)
```
another code is vulnerable:
```python
  for dumpfile in args.dumpfiles:
    if args.verbose:
      print >>sys.stderr, 'Scanning for dxcompiler events in dumpfile: %s' % (dumpfile,)
    tree = ET.parse(dumpfile)
```

Reported💜 by imhunterand

**Comment by llvm-beanz** [comment]
@tex3d do we even use the hcttest-samples.py script? I can't find any use of it in the repo (but might be missing something).

My inclination is to close this issue because the code isn't really production code, but if we can delete the file I'm in favor of that too.

**Comment by tex3d** [comment]
`hcttest-samples.py` is an old script manually used to test using DXC with DirectX sample projects that originally used FXC for compilation.  It's not production code or used in any production environment, it's not run as part of any automated process, and it's not used to process untrusted XML.  We could delete it, but I'm not sure what value that has either.

The second snippet is from `hcttracei.py`, which is similarly a manual development-time tool for analyzing a trace report from made by running the compiler and using the Microsoft Windows `TraceRpt.exe` tool, by using the hcttrace.cmd script.

`defusedxml` is not part of the default Python installation, meaning these scripts would require an additional package installation to run if we switched to it, even though these are one-off manual developer tools.  There's no processing of untrusted XML, and certainly not in a production environment.  I really don't see the value in keeping this issue open.

**Comment by llvm-beanz** [comment]
Okay, based on @tex3d's explanation of the use of these scripts for local development purposes only, I see no security risk and no real driver to change this code.
