### ISSUE TITLE
[SPIR-V] How to keep unused variable

### ISSUE THREAD

**Issue by SJTU-Lucy** [microsoft/DirectXShaderCompiler#4567]
For some reason, I want to reserve all the variables of a struct although some of them is not used.
The hlsl code is like:
```
 struct PS_INPUT 
{
 float4 final_position : SV_Position;
 float4 texcoord0 : TEXCOORD0;
 float4 texcoord1 : TEXCOORD1;
 float4 world_position : TEXCOORD2;
 float4 world_normal : TEXCOORD3;
 half4 vertex_light : TEXCOORD6;
 half4 fog_info : TEXCOORD8;
 float3 world_tangent : TEXCOORD4;
 float3 world_binormal : TEXCOORD5;
 float4 pos_light : TEXCOORD9;
 half4 point_light : TEXCOORD7;
 half4 env_light : TEXCOORD10;
 float3 parallax : TEXCOORD11;
 };
```
The current output is like:
```
struct SPIRV_Cross_Input
{
    float4 in_var_TEXCOORD0 : TEXCOORD0;
    float4 in_var_TEXCOORD2 : TEXCOORD2;
    float4 in_var_TEXCOORD3 : TEXCOORD3;
    float4 in_var_TEXCOORD6 : TEXCOORD4;
    float4 in_var_TEXCOORD8 : TEXCOORD5;
    float4 in_var_TEXCOORD9 : TEXCOORD8;
    float4 in_var_TEXCOORD7 : TEXCOORD9;
    float4 in_var_TEXCOORD10 : TEXCOORD10;
};
```
I wonder if there is a way to keep TEXCOORD1, 4, 5, 11.

**Comment by pow2clk** [comment]
Hi @SJTU-Lucy!

From the output you provide, it looks like you are using https://github.com/KhronosGroup/SPIRV-Cross? If so, perhaps the bug should be filed there unless you can identify that the spirv backend of DXC is what is removing the unused inputs.

Regardless, I'm tagging this as SPIRV. @vettoreldaniele for visibility

**Comment by SJTU-Lucy** [comment]
Hi @pow2clk!
From the .spv file that DXC generates, it could be seen that the variables are already removed.
```
in.var.TEXCOORD0
in.var.TEXCOORD2
in.var.TEXCOORD3
in.var.TEXCOORD6
in.var.TEXCOORD8
in.var.TEXCOORD9
in.var.TEXCOORD7
in.var.TEXCOORD10
out.var.SV_Target0
```

**Comment by vettoreldaniele** [comment]
Hi @SJTU-Lucy!

As suggested by @pow2clk, can you check whether the DXIL backend also removes the unused variables? If that's the case, the SPIR-V backend is likely not the culprit here. If you can, please provide a minimal input shader that we can use to reproduce.

**Comment by SJTU-Lucy** [comment]
Hi @vettoreldaniele!
I have tested it in DXIL, and it's true that DXIL didn't remove the unused variables. So I think maybe that happens in SPIR-V backend.

**Comment by SJTU-Lucy** [comment]
A brief example can be like this:
```
struct VS_INPUT 
{
 float4 texcoord0 : TEXCOORD0;
 float4 texcoord1 : TEXCOORD1;
 };
struct PS_INPUT 
{
 float texcoord0 : TEXCOORD0;
 float texcoord1 : TEXCOORD1;
 };

PS_INPUT vs_main(VS_INPUT input) 
{
 PS_INPUT output = (PS_INPUT) 0;
 output.texcoord0 = 0.0;
 output.texcoord1 = 1.0;
 return output;
}
float4 ps_main(PS_INPUT input) : SV_Target0 
{
 PS_INPUT output = (PS_INPUT) 0;
 output.texcoord0 = input.texcoord0;
 return float4(output.texcoord0, output.texcoord0, output.texcoord0, output.texcoord0);
 }
```
When using ps as entry:
```
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %ps_main "ps_main" %in_var_TEXCOORD0 %out_var_SV_Target0
               OpExecutionMode %ps_main OriginUpperLeft
               OpSource HLSL 600
               OpName %in_var_TEXCOORD0 "in.var.TEXCOORD0"
               OpName %out_var_SV_Target0 "out.var.SV_Target0"
               OpName %ps_main "ps_main"
               OpDecorate %in_var_TEXCOORD0 Location 0
               OpDecorate %out_var_SV_Target0 Location 0
``` 
While for vs:
```
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %vs_main "vs_main" %out_var_TEXCOORD0 %out_var_TEXCOORD1
               OpSource HLSL 600
               OpName %out_var_TEXCOORD0 "out.var.TEXCOORD0"
               OpName %out_var_TEXCOORD1 "out.var.TEXCOORD1"
               OpName %vs_main "vs_main"
               OpDecorate %out_var_TEXCOORD0 Location 0
               OpDecorate %out_var_TEXCOORD1 Location 1
```

**Comment by s-perron** [comment]
The dead code elimination pass already has an options to[ preserve the interface variables](https://github.com/KhronosGroup/SPIRV-Tools/blob/54cd5e1963b399e6c6d3c5b70da45583d9f9fed8/source/opt/aggressive_dead_code_elim_pass.h#L47-L48).  However, that options is not exposed in the legalization and optimization passes.  If we want to do this we would:

- [ ] Create a new interface to register the [legalization passes](https://github.com/KhronosGroup/SPIRV-Tools/blob/54cd5e1963b399e6c6d3c5b70da45583d9f9fed8/source/opt/optimizer.cpp#L111) and [optimization passes](https://github.com/KhronosGroup/SPIRV-Tools/blob/54cd5e1963b399e6c6d3c5b70da45583d9f9fed8/source/opt/optimizer.cpp#L162) that takes an options to preserve the interface variables, which will be passed on to the DCE.
- [ ] Create a CLI option in DXC saying whether or not the interface variables should be preserved.  That should be passed to the new calls to register passes in spirv-opt.

**Comment by s-perron** [comment]
@SJTU-Lucy I will not be able to implement this myself, but I can review code if you want to contribute it.

**Comment by SJTU-Lucy** [comment]
omg thank you very much @s-perron ! This really helps!

**Comment by kirill146** [comment]
I also have the same issue when I try to convert compiled SIPR-V back to HLSL. Recently the option for preserving interface [was added](https://github.com/KhronosGroup/SPIRV-Tools/commit/b4f352e54f63a07b3a1338abd22e6ef69106f4ca) to SPIRV-Tools, so now it's only a matter of creating a CLI option in DXC.
I think I can make a PR for this.
