### ISSUE TITLE
DXIL/HLSL SM6.x  vs SPIRV features (for spvcl)..

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectXShaderCompiler#459]
are you aware of https://github.com/google/clspv effort I say that because now seem very easy to translate OpenCL kernels to Spir-V Vulkan compute shaders (before that OpenCL kernels translated to SPIR-V via Khronos tool but where only usable from OpenCL SPIR-V capable implelentations only no Vulkan graphic drivers)..

I say that because feeding clspv SPIRV output to SPIRV-Cross project which now has patches for generating HLSL compute shaders from SPIR-V compute shaders (https://github.com/KhronosGroup/SPIRV-Cross/pull/220)..
could generate HSLS compute shaders from OpenCL kernels which would be nice!

sad is that the SPIRV code generated by that tool can require new SPIR-V extensions and optional caps like:

*SPV_KHR_variable_pointers which seems the most important..
*SPV_KHR_16bit_storage & shaderInt16 for int16 computations and storage..
 *For image access: shaderStorageImageReadWithoutFormat shaderStorageImageWriteWithoutFormat

so should be interesting to know if DXIL & HLSL compute shaders support similar features to those used by SPIRV code generated by that tool..

(note I asked MoltenVK developer a Vulkan over Metal wrapper if Metal is rich enough for that and he answered it could add this functionality over Metal)
 
For example with this tool I get for a simple kernel like:

```
void kernel __attribute__((reqd_work_group_size(1, 1, 1))) foo(sampler_t s, read_only image2d_t i, float2 c, global float4* a)
{
  *a = read_imagef(i, s, c);
}
```

SPIRV output like:

```
; SPIR-V
; Version: 1.0
; Generator: Codeplay; 0
; Bound: 34        
; Schema: 0
	OpCapability Shader
	OpCapability StorageImageReadWithoutFormat
	OpCapability VariablePointers
	OpExtension "SPV_KHR_variable_pointers"
	OpMemoryModel Logical GLSL450
	OpEntryPoint GLCompute %25 "foo"
	OpExecutionMode %25 LocalSize 1 1 1
	OpSource OpenCL_C 120
	OpMemberDecorate %7 0 Offset 0
	OpDecorate %7 BufferBlock
	OpDecorate %12 ArrayStride 16
	OpMemberDecorate %13 0 Offset 0
	OpDecorate %13 BufferBlock
	OpDecorate %21 DescriptorSet 0
	OpDecorate %21 Binding 0
	OpDecorate %22 DescriptorSet 0
	OpDecorate %22 Binding 1
	OpDecorate %22 NonWritable
	OpDecorate %23 DescriptorSet 0
	OpDecorate %23 Binding 2
	OpDecorate %24 DescriptorSet 0
	OpDecorate %24 Binding 3
%1 = 	OpTypeFloat 32
%2 = 	OpTypeSampler
%3 = 	OpTypePointer UniformConstant %2
%4 = 	OpTypeImage %1 2D 0 0 0 1 Unknown
%5 = 	OpTypePointer UniformConstant %4
%6 = 	OpTypeVector %1 2
%7 = 	OpTypeStruct %6
%8 = 	OpTypePointer StorageBuffer %7
%9 = 	OpTypePointer StorageBuffer %6
%10 = 	OpTypeVector %1 4
%11 = 	OpTypePointer StorageBuffer %10
%12 = 	OpTypeRuntimeArray %10
%13 = 	OpTypeStruct %12
%14 = 	OpTypePointer StorageBuffer %13
%15 = 	OpTypeInt 32 0
%16 = 	OpTypeVoid
%17 = 	OpTypeFunction %16
%18 = 	OpTypeSampledImage %4
%19 = 	OpConstant %1 0
%20 = 	OpConstant %15 0
%21 = 	OpVariable %3 UniformConstant
%22 = 	OpVariable %5 UniformConstant
%23 = 	OpVariable %8 StorageBuffer
%24 = 	OpVariable %14 StorageBuffer
%25 = 	OpFunction %16 None %17
%26 = 	OpLabel
%27 = 	OpLoad %2 %21
%28 = 	OpLoad %4 %22
%29 = 	OpAccessChain %9 %23 %20
%30 = 	OpLoad %6 %29
%31 = 	OpAccessChain %11 %24 %20 %20
%32 = 	OpSampledImage %18 %28 %27
%33 = 	OpImageSampleExplicitLod %10 %32 %30 Lod %19
	OpStore %31 %33
	OpReturn
	OpFunctionEnd

```

so finally briefly can this SPIR-V code translated to DXIL? or DXIL isn't rich enough right now to have "OpenCL" like compute kernels?

thanks..
PS: thanks to @Kangz for pointing me to ask help to DXIL devs..

**Comment by marcelolr** [comment]
@oscarbg I don't know enough about SPIR-V to interpret it definitely, but it seems like you could map the OpenCL code you mention above to HLSL/DXIL.

A quick read of the overview for variable pointers however would imply that some of these things are not expressible in DXIL at the moment (although some of those capabilities seem to be similar to what we envision for some future iterations).

**Comment by capitalknew** [comment]
Shader Model 6.0 can be interpreted by OpenGL extensions (subgroup vote available in OpenGL 4.6)

**Comment by oscarbg** [comment]
@marcelolr thanks.. nice, and I'm afraid asking for "future iterations" altough hoping they are in the pipeline rather earlier than later.. other interesting feature for example is dynamic parallelism (in CUDA speaking launch kernels from compute kernels without CPU intervention) seems 5 years old since introduction in CUDA and shipping in OpenCL 2.0 implementations almost three years.. it's in SPIR-V for OpenCL 2.1 altough still not supported in compute shaders from graphics APIs.. why?
also all PC (desktop) IHVs latest GPUs support it juding from Intel and AMD OCL 2.0 drivers and NV CUDA support..

@capitalknew interesting you talk about.. shader vote ok yes.. but SM6.0 supports "thread shuffles" @marcelolr? for this case not so fast as even OpenGL 4.6 hasn't thread group shuffles support.. "only" there are NV and AMD extensions supporting it.. in AMD is in AMD_shader_ballot (called here swizzleInvocationsAMD seems)..
also for this same reason we can't use new OpenGL 4.6 GL_ARB_spirv_extensions as even with this only there is ARB variant of shader ballot.. needless to say also OpenCL 2.1 with SPIR-V suffers from this problem as seems only extension to support it is cl_intel_subgroups (here is sub_group_shuffle function) maybe Nvidia using his inline PTX support can hack something similar..
so for me thread shuffles are also one of "less loved" features by graphics vendors and in OpenCL..
despite all major HW having it currently..
nice news is @Siggraph Vulkan talk shows future Vulkan will have thread group shuffles (next year Vulkan 1.1?) so would be in SPIR-V -> so possibly support in OpenCL 2.x -> so possibly exposed also in OpenGL via GL_ARB_spirv_extensions support so basically everywhere Khronos based..

**Comment by capitalknew** [comment]
Thread shuffles have in AMD extensions

**Comment by antiagainst** [comment]
Closing this since the original question was replied. I see there were some followup questions regarding thread shuffle, but with Vulkan 1.1 and advances in tools and drivers, the landscape of Vulkan ecosystem is vastly different. Please feel free to open new issues if that's still an issue.
