### ISSUE TITLE
How to remove TAEF dependency to build only the DXC Compiler

### ISSUE THREAD

**Issue by shakti-hub** [microsoft/DirectXShaderCompiler#4596]
Couldn't find a way to remove TAEF dependency to compile the project, but not the unit tests.
Only the unit tests are based on TAEF, and if we are interested in only compiling the DXCCompiler, there should be a way to remove the TAEF dependency.

**Comment by hekota** [comment]
The tests are included when HLSL_INCLUDE_TESTS cmake option is set to ON, which is the default. We do not surface this option in hctbuild.cmd though. You can try disabling the tests by setting HLSL_INCLUDE_TESTS to OFF. 

Find this line line utils\hct\hctbuild.cmd and replace ON with OFF:
`set CMAKE_OPTS=%CMAKE_OPTS% -DHLSL_INCLUDE_TESTS:BOOL=ON`

Let me know if it works!

**Comment by llvm-beanz** [comment]
@shakti-hub, since I believe @hekota's comment should point you in the right direction. Please file a new issue if you need additional support.
