### ISSUE TITLE
[SPIRV] How to generate global variables independently in SPIR-V

### ISSUE THREAD

**Issue by SJTU-Lucy** [microsoft/DirectXShaderCompiler#4608]
Are there any way to generate global variables independently, instead of putting them together in type.$Globals.
I have tried to use the following code:
```
const auto name = var->getName();
SpirvVariable *varInstr = spvBuilder.addModuleVar(type, storageClass, var->hasAttr<HLSLPreciseAttr>(), name, llvm::None, loc);
varInstr->setLayoutRule(rule);
astDecls[var] = createDeclSpirvInfo(varInstr);
```
To replace this code in `createExternVar`
```
if (astDecls.count(var) == 0)
    createGlobalsCBuffer(var);
auto *varInstr = astDecls[var].instr;
```
But an error occurs:
```
fatal error: generated SPIR-V is invalid: [VUID-StandaloneSpirv-UniformConstant-04655] UniformConstant OpVariable <id> '111[%MACRO_AHD_TEX_ENABLE_MACRO]' has illegal type
Variables identified with the UniformConstant storage class are used only as handles to refer to opaque resources. Such variables must be typed as OpTypeImage, OpTypeSampler, OpTypeSampledImage, OpTypeAccelerationStructureKHR, or an array of one of these types.
%MACRO_AHD_TEX_ENABLE_MACRO = OpVariable %_ptr_UniformConstant_int UniformConstant
```
I don't really know how to solve it. So I wonder what's the right way to do so. Thanks!

**Comment by pow2clk** [comment]
Marking as a SPIRV issue since that's the thrust of it. Tagging @keenuts and @cassiebeckley for visibility.

In HLSL, constants (uniforms in GLSL speak), have to be part of a constant buffer. If you don't provide one, you get $Globals, the default. If you want to create your own, you are perfectly free to do so. For example:

```hlsl
uint2 globix; // Doomed to be herded into $Globals like a commoner

cbuffer mine {
  uint2 myix; // Treated to a luxurious experience in the "mine" cbuffer
};

Texture2D<float4> g_tex;
SamplerState g_samp;

float4 main() :SV_Target {
  return g_tex.Sample(g_samp, globix) + g_tex.Sample(g_samp, myix);
}
```

If you want constants outside of cbuffers, that is not allowed. So sorry. Perhaps if you describe why it is you don't want your variables to all be in $Globals, we might be able to suggest an alternative solution.

**Comment by SJTU-Lucy** [comment]
Hi @pow2clk !
What I have tried to do is to generate uniform variables in target code. 
For example `uint2 globix` would be transformed to `uniform uint2 globix`. So since DXC generates all the global variables in `$Globals`, I should try to extract them in `SPIRV->target code` process?

**Comment by pow2clk** [comment]
Those are the kind of questions that are better for the SPRIV developers I tagged above. I don't really do SPIRV, but I thought I'd try to help out with suggestions on how to get the existing compiler to do what you want. Good luck!
