### ISSUE TITLE
Constant buffer with T[2] unbounded buffer size compiles and runs, but is undefined behavior

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/DirectXShaderCompiler#4627]
> **Note**:
> Follow up from a conversation with Brian Favela over at the DX Discord server

Consider this HLSL shader:

```hlsl
#define __GroupSize__get_X 8
#define __GroupSize__get_Y 1
#define __GroupSize__get_Z 1

cbuffer _ : register(b0)
{
    uint __x;
    uint __y;
    uint __z;
}

cbuffer _source : register(b1)
{
    int source[2];
}

RWStructuredBuffer<int> destination : register(u0);

[NumThreads(__GroupSize__get_X, __GroupSize__get_Y, __GroupSize__get_Z)]
void Execute(uint3 ThreadIds : SV_DispatchThreadID)
{
    if (ThreadIds.x < __x && ThreadIds.y < __y && ThreadIds.z < __z)
    {
        destination[ThreadIds.x] = source[ThreadIds.x];
    }
}
```

This compiles just fine with DXC, and it's using that `T[2]` field to effectively specify a dynamically sized constant buffer. I'm currently loading this with a constant buffer (`D3D12_HEAP_TYPE_UPLOAD`, `D3D12_RESOURCE_FLAG_NONE`, `D3D12_RESOURCE_STATE_GENERIC_READ`) which I then create a constant buffer view for. I'm binding it to the shader root signature normally and then indexing it dynamically in the shader, which seems to work fine for me (tried on multiple GPUs, on WARP, on a few VMs, etc.). I understand this is not really well defined behavior though so opening this for tracking in case support for this should be disabled and a new build error should be added when trying to compile this or something 🙂

**Comment by llvm-beanz** [comment]
Marking this as "shader-linking" even though it doesn't directly relate to shader linking on the surface. The underlying problem is how we do or don't decay arrays to pointers and where things go sideways. We likely need to consider some language changes to provide safety to array bounds.

**Comment by damyanp** [comment]
I think that the request here is for some diagnostics to report the potential out-of-bounds access on the array.  In general, though dynamically accessing arrays like this is something that we can't detect - especially in cases where the actual range comes from the parameters passed to Dispatch().
