### ISSUE TITLE
How to export the ast information

### ISSUE THREAD

**Issue by Jason-YJ** [microsoft/DirectXShaderCompiler#4632]
I'm new to complier.
I want get the ast of shader and I've succeed in using dxc.exe to output the ast in the command window, but the "-Fo" parameter seems doesn't work while I wrote command like 
![image](https://user-images.githubusercontent.com/71368398/187836252-9f457b67-bef6-46e6-9737-ec3c8b130320.png)
I wonder how to output the ast information.

In fact, my core aim is to do somthing to the ast in the D12 pipeline. I've find some notes briefly explains how to use dxc in a d3d12 pipeline, but all of them seems not totally right to me (or maybe just because me lacking knowledge in this field).I tried like:
![image](https://user-images.githubusercontent.com/71368398/187836776-d695e25a-6c56-4431-b79d-2ff0eaa40080.png)
![image](https://user-images.githubusercontent.com/71368398/187836814-b7cf1c9c-8065-4dee-a34a-1e1c440739e3.png)
But I didn't find information in "ComPtr<IDxcResult> pCompileResult" and also not fully understand the "Getoutput" function. 
Please help me how to get the ast information like showed in the cmd window instead manually copy to a txt file.

**Comment by cassiebeckley** [comment]
I'm not sure if there is an option to dump the AST to a file, but, as a general rule, you can redirect standard output on the command line to a file using the `>` symbol. For example, you can run

```Batchfile
dxc.exe -T ps_6_0 -ast-dump shaders.hlsl -E PSMain > a.txt
```

**Comment by Jason-YJ** [comment]
> I'm not sure if there is an option to dump the AST to a file, but, as a general rule, you can redirect standard output on the command line to a file using the `>` symbol. For example, you can run
> 
> ```batchfile
> dxc.exe -T ps_6_0 -ast-dump shaders.hlsl -E PSMain > a.txt
> ```

Emm...You recommand help me avoid the manual ctrl +c/v operation, but it will be better if I can get the ast information in the pipeline.
I tried to write code it the "LoadAssets()" funciton of the d3d12 official sample project "hellotriangle"  like this,
![image](https://user-images.githubusercontent.com/71368398/188071960-d5173a21-4b74-437c-bbd8-57c2a183d1f5.png)
 It works at least, but I can only get the first line of the ast information from `static_cast<char*>(shader_object->GetBufferPointer())`. I tried a lot and tried to read the original code behind it. Maybe the recursive function "QueryInterface" causes it ?
Sad to find it dosen't work when using "> a.txt"  (push_back in the arguments) in the pipeline.

**Comment by Jason-YJ** [comment]
Besides, is there any way to transform the ast info back to the compiler to get the SPIR-V so that I can do the rendering on the new ast info.

**Comment by cassiebeckley** [comment]
I'm a bit new to dxc so I don't know for sure, but from looking at the documentation I can find for the COM interfaces you're using (https://github.com/microsoft/DirectXShaderCompiler/wiki/Using-dxc.exe-and-dxcompiler.dll) I suspect you won't be able to use it to get the AST. Instead, you'll probably have to link directly to the parser library. I think others have used Clang for source-to-source transformation before, so if you can find examples of that you might be able to modify it to DXC.

**Comment by Jason-YJ** [comment]
Luckily, I found the problem while output the ast in the d3d12 sample pipeline. I used the wrong initial function to load the hlsl file.....
Now, the question is how to convert the ast back to the compile process to get the corresponding bytecode....
