### ISSUE TITLE
Rewriter does not remove unused templates

### ISSUE THREAD

**Issue by LukasBanana** [microsoft/DirectXShaderCompiler#4649]
UE5 relies on the DXC rewriter for several shader backends and we recently discovered that the rewriter does not remove unused templates as shown in the following example:
```hlsl
groupshared uint Foo;

template<class T>
uint X() {
  Foo += 1;
  return Foo;
}

RWStructuredBuffer<float4> Bar;

[numthreads(1, 1, 1)]
void CSMain() {
  Bar[0] = 3.0f;
}
```
The rewriter generates the following code:
```hlsl
template <class T>
uint X() {
  Foo += 1;
  return Foo;
}

;
;
RWStructuredBuffer<float4> Bar;
[numthreads(1, 1, 1)]
void InitArgs() {
  Bar[0] = 3.F;
}
```
This results in an undefined identifier `Foo` because that global variable has been removed but not the template. MSVC evaluates templates differently but since DXC is based on Clang, the templates have to be removed alongside unused global declarations.

I tried to address that in `CollectRewriteHelper` (i.e. [dxcrewriteunused.cpp:716](https://github.com/microsoft/DirectXShaderCompiler/blob/79856c4a74b7aa1bd1c865518778246e33849371/tools/clang/tools/libclang/dxcrewriteunused.cpp#L716)) by forwarding the templated declaration like this:
```c++
if (TemplateDecl *tmplDecl = dyn_cast<TemplateDecl>(tuDecl)) {
  tuDecl = tmplDecl->getTemplatedDecl();
}
```
But that doesn't work because of how Clang builds up the AST for templates. I hope someone can assist with this.

Thank you and kind regards
Laura

**Comment by damyanp** [comment]
@LukasBanana - we've triaged this as dormant, which means that we're not currently planning on investing any more time into addressing this.  Please let us know if you think we should re-triage this.

**Comment by LukasBanana** [comment]
Hi @damyanp, thanks for the update. UE does no longer use the DXC rewriter, so we can close this ticket from our side. We only needed the rewriter to optimize the packing of the `$Globals` cbuffer but we recently added a SPIRV-Tools pass that re-assigns all offset decorations to a tightly packed `std140` layout.
