### ISSUE TITLE
[HLSL 2021] Raytracing: Bitfields in payload structs with payload access qualifiers

### ISSUE THREAD

**Issue by jasilvanus** [microsoft/DirectXShaderCompiler#4686]
HLSL 2021 introduces bitfields in structs, for example as in 

```
struct BitfieldStruct {
  int x: 8;
  int : 8;
  int y : 16;
};
```

Independently, from shader model 6.6 on, ray tracing payloads can be access-qualified to restrict payload field lifetime and reduce register pressure: https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html#payload-access-qualifiers

It is however not clear whether bitfields in payload structs are allowed.
It seems the currently used DXIL metadata format for payload access qualifiers does not support bitfields. 

However, `dxc -T lib_6_7 -HV2021` allows bitfields in access-qualified payloads, but the emitted DXIL metadata lacks access flags (`i32 0`) for the bitfield elements of the payload. For example, for this input

```
struct [raypayload] Payload {
    int a : 1  : write(caller) : read(anyhit);
    int b : 17 : write(miss)   : read(caller);
    int c      : write(miss)   : read(caller);
};

[shader("miss")] void Miss(inout Payload payload) {}
```

`dxc -T lib_6_7 -HV2021` emits this DXIL output:

```
target datalayout = "e-m:e-p:32:32-i1:32-i8:32-i16:32-i32:32-i64:64-f16:32-f32:32-f64:64-n8:16:32:64"
target triple = "dxil-ms-dx"

%struct.Payload = type { i32, i32 }

; Function Attrs: nounwind
define void @"\01?Miss@@YAXUPayload@@@Z"(%struct.Payload* noalias nocapture %payload) #0 {
  ret void
}

attributes #0 = { nounwind }

!llvm.ident = !{!0}
!dx.version = !{!1}
!dx.valver = !{!1}
!dx.shaderModel = !{!2}
!dx.typeAnnotations = !{!3}
!dx.dxrPayloadAnnotations = !{!8}
!dx.entryPoints = !{!12, !13}

!0 = !{!"dxc(private) 1.7.0.13662 (main, ecf4e0a5c)"}
!1 = !{i32 1, i32 7}
!2 = !{!"lib", i32 6, i32 7}
!3 = !{i32 1, void (%struct.Payload*)* @"\01?Miss@@YAXUPayload@@@Z", !4}
!4 = !{!5, !7}
!5 = !{i32 1, !6, !6}
!6 = !{}
!7 = !{i32 2, !6, !6}
!8 = !{i32 0, %struct.Payload undef, !9}
!9 = !{!10, !11}
!10 = !{i32 0, i32 0}
!11 = !{i32 0, i32 513}
!12 = !{null, !"", null, null, null}
!13 = !{void (%struct.Payload*)* @"\01?Miss@@YAXUPayload@@@Z", !"\01?Miss@@YAXUPayload@@@Z", null, null, !14}
!14 = !{i32 8, i32 11, i32 6, i32 8, i32 5, !15}
!15 = !{i32 0}
```

The relevant parts are:

```
%struct.Payload = type { i32, i32 }
!dx.dxrPayloadAnnotations = !{!8}
!8 = !{i32 0, %struct.Payload undef, !9}
!9 = !{!10, !11}
!10 = !{i32 0, i32 0}
!11 = !{i32 0, i32 513}
```

Note the `!10 = !{i32 0, i32 0}` -- the second `i32` is supposed to contain the access bitmask.

**Comment by pow2clk** [comment]
Hi @jasilvanus!

Thanks for the very clear bug report!

We've shied away from combining bitfields with HLSL-style colon annotations such as these and semantics for HLSL2021. We recognize that these could be useful in cases such as these, but it's outside the scope of HLSL2021.

We would like to introduce a new way of denoting those annotations that will be compatible with bitfields in a future language version. For now, I'm afraid the right solution is to make this usage an error, which is how we'll address this bug for now.

**Comment by jasilvanus** [comment]
Hi @pow2clk,

explicitly forbidding access-qualified bitfields and thus erroring out is completely fine from my side. I had no intention to use the combination; rather, I was worried about the unclear specification status.

Thanks!
