### ISSUE TITLE
Is InterlockedCompareExchange only support int32 instead of int64?

### ISSUE THREAD

**Issue by ghostplant** [microsoft/DirectXShaderCompiler#4693]
I tried using InterlockedCompareExchange() on int64_t data, but only low 32 bit values are changed. The compute shader version is cs_6_2.

**Comment by Keenuts** [comment]
Hi @ghostplant!

Thanks for the report!
Would you have some steps to reproduce? Like a sample shader + command line used?

**Comment by ghostplant** [comment]
```cpp
RWStructuredBuffer<int64_t> hstep: register(u0);

[numthreads(1, 1, 1)]
void CSMain(uint3 threadIdx: SV_GroupThreadID, uint3 blockIdx: SV_GroupID) {
  InterlockedMax(hstep[0], 1);
  // InterlockedCompareExchange, InterlockedAdd, .. have the same problem
}
```
Firstly, I set all values in hstep to be (int64_t)-1LL, then execute this shader with 1 block and 1 thread.
The value `hstep[0]` I got finally is supported to be 1, but I actually get 0xFFFFFFFF00000001.

**Comment by Keenuts** [comment]
Thanks! From this article (https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_6_Int64_and_Float_Atomics.html), it seems atomic operations on 64 bits are only supported starting 6_6.

Are you able to compile this? At HEAD, I cannot compile this code to cs_6_2:
```
 ./build/bin/dxc -T cs_6_2 /tmp/repro.hlsl -E CSMain
```

```
error: validation errors
/tmp/repro.hlsl:5:3: error: opcode '64-bit atomic operations' should only be used in 'Shader Model 6.6+'.
note: at '%2 = call i64 @dx.op.atomicBinOp.i64(i32 78, %dx.types.Handle %1, i32 5, i32 0, i32 0, i32 undef, i64 1)' in block '#0' of function 'CSMain'.
Validation failed.
```

Building with CS_6_6, generated SPIR-V looks OK (using 64 bits integers), and for DXIL, I'm not super familiar yet, but looks like they are using the proper 64 bit atomic operation.

**Comment by ghostplant** [comment]
OK, is cs_6_6 stable enough to be synchronized into vistual studio plugin? The dxcompiler.dll version I use doesn't support cs_6_6 but cs_6_2.

**Comment by Keenuts** [comment]
Support for shader model 6.6 was implemented almost 2 years ago (https://github.com/microsoft/DirectXShaderCompiler/pull/3293) and official release was announced 1 year ago (https://devblogs.microsoft.com/directx/hlsl-shader-model-6-6/) so if you use a recent release, it should be stable.

**Comment by Keenuts** [comment]
If you can reproduce this bad behavior on the last release, please let us know! But so far it doesn't look like a bug :slightly_smiling_face:

**Comment by Clothoid1** [comment]
I just tested InterlockedCompareExchange with cs_6_7 - compiling to SPIR-V.
I noticed that this only works correctly with 32 bit cases - but not for int64_t or uint64_t cases.
The HLSL shader compiles fine, but the result when running the shader is incorrect.
Here the upper 32 Bit of the result after a 64 atomic operation always seems to be 0.

**Comment by pow2clk** [comment]
@ghostplant, I can confirm that 6.6 is required for 64-bit atomic operations. You may need to use the compiler releases from github to get access to a 6.6 capable compiler.

@Clothoid1, using the latest compiler and the provided sample code, I see the proper SPIRV output for 64-bit atomics. It's possible that your driver has a bug which would require a fix from the appropriate hardware vendor.

**Comment by Clothoid1** [comment]
I just checked again and noticed a bug in my test shader - after fixing that i can confirm that 64 bit atomics are working fine with SPIR-V output and using those in Vulkan!

**Comment by pow2clk** [comment]
@Clothoid1 thanks for letting us know!

**Comment by ghostplant** [comment]
@Clothoid1 Is there a binary release for cs_6_6 / cs_6_7? I just checkout the current latest release which is from July 2022, and seems like it just supports up to cs_6_5 on all of my Windows nodes, while working with cs_6_6 will result in error execution.

**Comment by pow2clk** [comment]
@ghostplant, The July compiler release supports both 6.6 and 6.7. Does the error occur when you try to run the shader? That would depend on the runtime you are using, which comes from the SDK and also the hardware and driver you have.

**Comment by ghostplant** [comment]
@pow2clk I uses Intel HD graph, AMDGPU and NVIDIA GTX, non of them runs when setting version to cs_6_6.

**Comment by ghostplant** [comment]
VS2019

**Comment by ghostplant** [comment]
@Keenuts @pow2clk  I found that atomic add for fp64 numbers also failed the shader compilation:

calling `InterlockedAdd([out] double , [in] double)`:

```sh
Compilation Error:
ShaderFile:43:3: error: no matching function for call to 'InterlockedAdd'
  InterlockedAdd(compute14[0], __shared_output[N0]);
  ^~~~~~~~~~~~~~
ShaderFile:43:3: note: candidate function not viable: no known conversion from 'double' to 'unsigned long long &' for 1st argument
  InterlockedAdd(compute14[0], __shared_output[N0]);
  ^              ~~~~~~~~~~~~
ShaderFile:43:3: note: candidate function not viable: no known conversion from 'double' to 'int &' for 1st argument
  InterlockedAdd(compute14[0], __shared_output[N0]);
```

I tried both cs_6_6 and cs_6_7.

**Comment by Keenuts** [comment]
Hello @ghostplant 

From https://devblogs.microsoft.com/directx/in-the-works-hlsl-shader-model-6-6/ and  https://learn.microsoft.com/fr-fr/windows/win32/direct3dhlsl/interlockedadd we can see InterlockedAdd does only support integer types. SM6.6 adds support for 64-bit integers, but not floats. So this looks like the expected behavior.

If it's a feature request, I'm not sure how shader model decides what to implement, but feel free to open a proper feature request.

As for the previous comment, I can build the given shader (https://github.com/microsoft/DirectXShaderCompiler/issues/4693#issuecomment-1261866113) using the December 2022 release.
As for the last question, don't think HLSL supports some kind of inline asm, but you can still write SPIR-V 😊

**Comment by ghostplant** [comment]
Sure, maybe supporting any types (fp32/fp64) for InterlockedCompareStore would be enough since any other InterlockedAdd/Max/.. operations can be implemented based on it. I'll create an FR for InterlockedCompareStore then.
