### ISSUE TITLE
[SPIR-V] compiler crash when casting types

### ISSUE THREAD

**Issue by hannes-vernooij** [microsoft/DirectXShaderCompiler#4698]
Casting types with an identical size causes a segmentation fault.
https://shader-playground.timjones.io/03295c7334e11b732d4218543ebf47a4

```hlsl
struct A {
    uint data;
};

struct B {
    uint internalData0;
    uint internalData1;
    uint internalData2;
    uint internalData3;
};

struct C {
    A internalPackedAlbedo;
    uint internalData1;
    uint internalData2;
    uint internalData3;
};

[numthreads(8, 8, 1)] void main() {
    C diffuseLobe = (C)0;
    B lobe = (B)diffuseLobe;
}
```
It does compile successfully when A in struct C was defined as an `uint` instead of `A`.

**Comment by hannes-vernooij** [comment]
It seems to work when casting the other way around:

**Comment by pow2clk** [comment]
In spite of the fact that shader playground still has a compiler that reproduces this, I find this no longer repros with spirv or dxil generation on my own builds and the most recent godbolt compilers: 

https://godbolt.org/z/PG3cfsE8T

Please re-open if you find a repro in the latest compiler
