### ISSUE TITLE
Compile dxcompiler on windows only targeting spirv

### ISSUE THREAD

**Issue by BeastLe9enD** [microsoft/DirectXShaderCompiler#4699]
Is there a way to compile dxcompiler on Windows without dxil codegen (only for spirv)?
This could shrink down the binary size if only spirv support is desired.

**Comment by llvm-beanz** [comment]
DXIL isn't really a separable part of DXC. DXIL is just the LLVM IR generation (and some specialized optimization passes). While it is _possible_ to mark up clang with enough `#ifdef` blocks to compile it without the code generation layers, this would be an invasive configuration and a support burden we're unlikely to take on.

Long term the Clang-based upstream compiler will support conditionally removing targets, but we're not going to support this for DXC.
