### ISSUE TITLE
Can i get the AST using the interface provided by the Pre-built Releases?

### ISSUE THREAD

**Issue by cx-zzz** [microsoft/DirectXShaderCompiler#4700]
I am a newer about compile and i'd like to get AST tree from a hlsl file. Can i use the .lib  in vs2019 to get it and how to do this, can someone give a example code?  
Thank you!

**Comment by tex3d** [comment]
You can use the `-ast-dump` option when compiling through `dxc.exe` or the `IDxcCompiler::Compile` interface for a text dump of the AST tree as output.  For a programmatic interface to inspect HLSL AST, you can use the `IDxcIntelliSense` interface defined in https://github.com/microsoft/DirectXShaderCompiler/blob/main/include/dxc/dxcisense.h.

Interfaces are created by using the DxcCreateInstance function defined in dxcapi.h and supplying the appropriate CLSID, interface IID, and an output pointer.  There are example uses in test code.  These objects are implemented by the dxcompiler.dll built from this project.

**Comment by cx-zzz** [comment]
> 

Thank you for your reply so quickly.  But i cant find the test code, can you tell me where it is?
 Thank you very much.

**Comment by cx-zzz** [comment]
oh, i found some examples in DXIsenseTest.cpp, is it right?
