### ISSUE TITLE
How to traverse AST using IDxcCursor?

### ISSUE THREAD

**Issue by cx-zzz** [microsoft/DirectXShaderCompiler#4705]
I'm puzzled about how to use IDxcCursor to traverse AST, i have read the Wiki and i didn't find anything about CompilationResult which uses IDxcCursor to traverse the AST(perhaps i missed). Can someone show me how to do this begin from loading .hlsl file?
Thank you!

**Comment by cx-zzz** [comment]
I know how to do this, but all the examples begin from text and create unsaved file using CreateUnsavedFile function in DXIsenseTest.cpp. Can i just read the .hlsl file by its name?

**Comment by damyanp** [comment]
We're not planning to investigate this further.  If this is still something you're struggling with please let us know.
