### ISSUE TITLE
SPIR-V degradation 1.7.2207.10069 compare to 1.7.2207.10036

### ISSUE THREAD

**Issue by Goshido** [microsoft/DirectXShaderCompiler#4714]
After upgrading from _1.7.2207.10036_ to _1.7.2207.10069_ I got pixel shader compilation error:

```txt
C:\Users\Goshido\Desktop\1>"D:\Development\DXC-builds\Release-2022-10-09\bin\dxc.exe" -HV 2021 -spirv -fvk-use-dx-layout -fspv-reduce-load-size -fspv-target-env=vulkan1.1 -enable-16bit-types -WX -O3 -T ps_6_7 -E PS -Fo mandelbrot-lut-color-ps.spv mandelbrot-lut-color.ps
fatal error: generated SPIR-V is invalid: Back-edges (35[%35] -> 32[%32]) can only be formed between a block and a loop header.
  %35 = OpLabel

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible


C:\Users\Goshido\Desktop\1>"D:\Development\DXC-builds\Release-2022-10-09\bin\dxc.exe" -HV 2021 -spirv -fvk-use-dx-layout -fspv-reduce-load-size -fspv-target-env=vulkan1.1 -enable-16bit-types -WX -O3 -T ps_6_7 -E PS -Fo mandelbrot-analytic-color-ps.spv mandelbrot-analytic-color.ps
fatal error: generated SPIR-V is invalid: Back-edges (37[%37] -> 34[%34]) can only be formed between a block and a loop header.
  %37 = OpLabel

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

Compilation to _SPIR-V_ worked previously in version _1.7.2207.10036_.

### Minimal repro steps

I attached minimal reproducible example with pixel shader sources and `bat` script with all compilation parameters. You need to change `DXC_LOCATION` variable inside the `build-test.bat` to _dxc.exe v1.7.2207.10069_ executable.

[Direct link to issue-001.zip](https://github.com/microsoft/DirectXShaderCompiler/files/9741870/issue-001.zip)

### Expected result

Compilation success. _DXC_ produces _SPIR-V_ binaries.

### Actual result

Compilation error:

```txt
C:\Users\Goshido\Desktop\1>"D:\Development\DXC-builds\Release-2022-10-09\bin\dxc.exe" -HV 2021 -spirv -fvk-use-dx-layout -fspv-reduce-load-size -fspv-target-env=vulkan1.1 -enable-16bit-types -WX -O3 -T ps_6_7 -E PS -Fo mandelbrot-lut-color-ps.spv mandelbrot-lut-color.ps
fatal error: generated SPIR-V is invalid: Back-edges (35[%35] -> 32[%32]) can only be formed between a block and a loop header.
  %35 = OpLabel

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible


C:\Users\Goshido\Desktop\1>"D:\Development\DXC-builds\Release-2022-10-09\bin\dxc.exe" -HV 2021 -spirv -fvk-use-dx-layout -fspv-reduce-load-size -fspv-target-env=vulkan1.1 -enable-16bit-types -WX -O3 -T ps_6_7 -E PS -Fo mandelbrot-analytic-color-ps.spv mandelbrot-analytic-color.ps
fatal error: generated SPIR-V is invalid: Back-edges (37[%37] -> 34[%34]) can only be formed between a block and a loop header.
  %37 = OpLabel

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

No _SPIR-V binaries._

### Further technical details

- Commit _SHA-1_: `81ef064a47a191c9fc68a43adca4706244c3687b`
- `git submodule update --init` has been invoked before build
- `hctbuild` build parameters: `-official -rel -x64 -vs2022 -speak-up -no-dxilconv -spirv`
- _Visual Studio 2022 Community_ components were up to date [2022/10/09].
- _Windows 11 Pro 64-bit (10.0 Build 22000, Version 21H2)_

Would you kindly help?

**Comment by MarijnS95** [comment]
We're running into the same issue. @Goshido would you mind boiling your example down to a simple text snippet and minimum commandline that is included directly in your report, so that others don't have to download zip and go through levels of `#include`? That makes this issue more digestible and in turn more likely to get picked up :wink:

**Comment by MarijnS95** [comment]
As I could not easily boil down our own shaders to a repro, here's a git bisect instead:

```
42eb79311e1c7f4ce6e110ec631243708664133b is the first bad commit
commit 42eb79311e1c7f4ce6e110ec631243708664133b
Author: Daniele Vettorel <dvet@google.com>
Date:   Fri Sep 16 11:38:26 2022 -0400

    [SPIR-V] Add short-circuiting logical operators for HLSL 2021 (#4658)

 tools/clang/lib/SPIRV/SpirvEmitter.cpp             | 65 +++++++++++++++++++++-
 .../binary-op.short-circuited-logical-and.hlsl     | 20 +++++++
 .../binary-op.short-circuited-logical-or.hlsl      | 22 ++++++++
 tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp   |  8 +++
 4 files changed, 114 insertions(+), 1 deletion(-)
 create mode 100644 tools/clang/test/CodeGenSPIRV/binary-op.short-circuited-logical-and.hlsl
 create mode 100644 tools/clang/test/CodeGenSPIRV/binary-op.short-circuited-logical-or.hlsl
```

CC @vettoreldaniele @cassiebeckley from #4658.

**Comment by vettoreldaniele** [comment]
Thanks for the report. I'll take a look to see if I can get to a minimal repro

**Comment by vettoreldaniele** [comment]
I was able to find a minimal repro case, that is confirmed to only produce invalid SPIR-V with HLSL 2021 due to the short-circuited operator change:
```
// RUN: %dxc -T ps_6_0 -E main -HV 2021

void main(int t : CUSTOM) {
  int z = 0;

  for (int i = 0; i < t && i < t; ++i) {
    z += 1;
  }
}
```

I will look into what's going wrong.

**Comment by Goshido** [comment]
@vettoreldaniele let me clarify. Did you check attached shader source with compilation flags to dxc.exe? Do i need to reupload source + flags as snippet?

**Comment by vettoreldaniele** [comment]
> @vettoreldaniele let me clarify. Did you check attached shader source with compilation flags to dxc.exe? Do i need to reupload source + flags as snippet?

No need. I was able to reproduce and identify the problem. We'll be working on a fix.

**Comment by Goshido** [comment]
Roger that. Thank you 👍! I hope this nasty bug will be squashed.

**Comment by vettoreldaniele** [comment]
Adding more context around this bug. The problem lies in the fact that short-circuited operators introduce control flow. Basically, `a && b` becomes equivalent to `bool result = false; if (a) result = b;`. 

This creates a problem when such a construct is used as a loop condition. When generating the loop in SPIR-V, we take the basic block that performs the condition check and reuse it as a loop header block instead of having a bespoke header block. This shortcut only works when the condition can be expressed in a single basic block, which for short-circuited conditions, it can't.

Therefore, as a fix, we should rework how we generate loop conditions and headers (both for `for` and `while` loops). We want to move the condition check within the loop, basically transforming a loop 
```
for (int i = 0; i < x && i < y; ++i) {
   // loop body
}
```
into
```
for (int i = 0; /* always true */; ++i) {
   if (!(i < x && i < y)) {
       break;
   }
   // loop body
}
```

We could do this only when the need arises, but I don't see a drawback in always performing this transformation. I have a prototype fix that performs this transformation and fixes the problem, will test and submit for review soon.

**Comment by MarijnS95** [comment]
@vettoreldaniele Thanks, this works for us!

**Comment by Goshido** [comment]
The issue has been fixed. Thanks 👍
