### ISSUE TITLE
Not know how using API(Megascans/Quixel) use JSON/syntax codes

### ISSUE THREAD

**Issue by theyWhoes** [microsoft/DirectXShaderCompiler#4728]
[https://quixel.github.io/megascans-api-docs/asset-downloads/ ](url)
How do I use it and why is the explanation as simple to were to find or simplified form of downloading?

**Comment by pow2clk** [comment]
Hi @theyWhoes,

I'm afraid we can't help you there. This is the HLSL compiler project. We have no connection with quixel nor familiarity with how it works.

Good luck!
