### ISSUE TITLE
Mark WaveGetLaneCount as constexpr

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/DirectXShaderCompiler#4731]
Currently one can't easily do this; instead you'd have to create a new shader permutation for every supported wave size.

```hlsl
groupshared uint stuff[WaveGetLaneCount()];
```

**Comment by simondeschenes** [comment]
I would also like to see this supported.

**Comment by llvm-beanz** [comment]
`WaveGetLaneCount` can't be a `constexpr`. It isn't a compile-time known value. It should be known in the driver compiler but it isn't in the frontend so it can't be `constexpr`.

The use case of being able to construct a wave-width array could potentially be addressed another way, but `constexpr` isn't the answer here.

**Comment by MarijnS95** [comment]
@llvm-beanz perhaps leave this open for that "other way"?

**Comment by llvm-beanz** [comment]
@MarijnS95, I think the correct approach for this is to add some sort of support for specialization constants to DXIL which we have tracked in the hlsl-specs repo issue [#16](https://github.com/microsoft/hlsl-specs/issues/16).

While at first glance these may seem slightly orthogonal, both require runtime & driver initialized constants, which is what this is too. We have the same challenge with #4290.

So, I think the TL;DR here is that this will all be rolled into specialization constant support, and we don't really need multiple issues tracking it.

**Comment by MarijnS95** [comment]
@llvm-beanz that sounds like the perfect match for specialization constants, as long as it is tracked somewhere that `WaveGetLaneCount()` should be treated as such?
