### ISSUE TITLE
Spelling error on .gitignore file.

### ISSUE THREAD

**Issue by JX-Master** [microsoft/DirectXShaderCompiler#4733]
On .gitignore line 55, I see:

`build*`

This causes all files that begins with "build" being excluded from the git repository, including:

- DirectXShaderCompiler/include/llvm/Transforms/Utils/BuildLibCalls.h
- DirectXShaderCompiler/lib/Transforms/Utils/BuildLibCalls.cop
- DirectXShaderCompiler/tools/clang/include/clang-c/BuildSystem.h
- DirectXShaderCompiler/tools/clang/tools/libclang/BuildSystem.cpp
- DirectXShaderCompiler/tools/clang/utils/ABITest/build-and-summarize-all.sh
- DirectXShaderCompiler/tools/clang/utils/ABITest/build-and-summarize.sh
- DirectXShaderCompiler/tools/clang/utils/ABITest/build.sh
- DirectXShaderCompiler/tools/llvm-config/BuildVariables.inc.in
- DirectXShaderCompiler/utils/buildit/GNUmakefile
- DirectXShaderCompiler/utils/buildit/build_ivm
- DirectXShaderCompiler/utils/crosstool/ARM/build-install-linux.sh

which causes CMake configuration failing (missing file "tools/llvm-config/BuildVariables.inc.in") if you clone the project and commit it as part of your own repository. I wonder if `build*` is a spelling error for `build/*`, which gives the correct behavior.

**Comment by llvm-beanz** [comment]
The intent is to allow multiple build directories. We could change this to `/build*` which would accomplish the same goal.

That said, I do worry that there is a root usage issue here we don't understand. Why are you copying to a new repository and dropping the history? The normal git workflow would be to fork the repository, or if you needed it embedded into a different repository, a sub-tree merge.
