### ISSUE TITLE
[SPIR-V] vk::RawBufferLoad is not an intrinsic

### ISSUE THREAD

**Issue by natevm** [microsoft/DirectXShaderCompiler#4737]
I'm trying to add support for an overload of the vk::RawBufferLoad intrinsic to support a `uint2 address` in addition to a `uint64_t` address. I'm running into some weird and unexplainable behavior by dxc / llvm though...

In particular, this section of code is odd to me. `vk::RawBufferLoad` fails the hlsl::IsIntrinsicOp check here, even though it very clearly _is_ an intrinsic...

https://github.com/microsoft/DirectXShaderCompiler/blob/977bed27b9cbf54768e0627f26f11390078e1734/tools/clang/lib/SPIRV/SpirvEmitter.cpp#L2493-L2504

This is particularly weird, because `processRawBufferLoad` is found in `processIntrinsicCallExpr`, as if it were meant to be processed as an intrinsic. And yet, this line here is never called when using rawbufferload

https://github.com/microsoft/DirectXShaderCompiler/blob/977bed27b9cbf54768e0627f26f11390078e1734/tools/clang/lib/SPIRV/SpirvEmitter.cpp#L8035

So, the above code is misleading, because it's technically a dead codepath at the moment...

Now, when I added `vk::RawBufferStore` in PR #4573, for some reason _that_ is interpreted to be an intrinsic, and so I don't need to process that intrinsic outside of processIntrinsicCallExpr. But I have no idea why the same isn't true for the load call.

Coincidentally (I think related, but I can't explain why...) when I go to overload vk::RawBufferStore to support a uint2 address, I receive that uint2 properly in the call to `processRawBufferStore`. However! vk::RawBufferLoad for some reason forcibly casts my uint2 address into a single uint64_t and dropping half the address's bits, and I am unable to handle the overload in `processRawBufferLoad`.

**Comment by natevm** [comment]
Tagging @jaebaek, since they added the original vk::rawbufferload intrinsic.

Not really sure who to talk to about this... 

The primary motivator here is that Intel's Arc Alchemist GPUs appear to not support the int64 arithmetic extension in SPIRV, so I need to use uint2 for my addresses...

**Comment by natevm** [comment]
Ok, some updates... It appears that this "intrinsic" attribute is added in "SemaHLSL.cpp", and at least during parsing, the vk::RawBufferLoad function declaration is considered as an "intrinsic". We just seem to lose these attributes somehow when we go to emit SPIRV for that call...

**Comment by natevm** [comment]
Oddly, I run into the same issue if I make my own intrinsic called "vk::RawBufferLoad2".

**Comment by natevm** [comment]
I guess this is some sort of bug with gen_intrin_main.txt...

If I use this pattern, the resulting declaration is an "intrinsic" and my address type is allowed to be a uint2

`void [[]] RawBufferLoad(in uint<2> addr, out $funcT value);`

But if I instead use this syntax, then the address is incorrectly transformed into a single uint, and is _not_ an "intrinsic".

`$funcT [[]] RawBufferLoad(in uint<2> addr); `

**Comment by natevm** [comment]
Although I wasn't able to solve this issue, I've since discovered that Intel ARC does support 64 bit integers, just unofficially. So a RawBufferLoad taking uint2's isn't necessary.

Leaving open for now, since this might be an issue down the road.

**Comment by s-perron** [comment]
This looks like an internal clean up issue. We have no intention of trying to fix this up as we will be moving most development work to clang.

**Comment by natevm** [comment]
@s-perron this is the second time over the past three years where Microsoft has swept a massive number of our issues under the rug as if they never existed. 

If this company actually cared about these issues, they would be adding them as targets for unit tests, and not just closing them all in one day.

To anyone out there running into these issues, I cannot recommend switching to slang enough. Get the latest version of the compiler here! :  https://github.com/shader-slang/slang/releases
