### ISSUE TITLE
[SPIR-V] ByteAddressBuffer::Load<float4x4> is broken

### ISSUE THREAD

**Issue by turanszkij** [microsoft/DirectXShaderCompiler#4738]
Hello, since the July 2022 compoiler release the `Load<float4x4>` of `ByteAddressBuffer` is not working correctly. The behaviour changed and no longer matches what HLSL compiler is doing. The result is a transposed matrix compared to HLSL, so a workaround is to simply transpose the resulting matrix when using the SPIR-V compiler. But this workaround didn't need to be performed in the compiler release earlier than July 2022, so I think this is a regression.

Best regards,
Janos

**Comment by cassiebeckley** [comment]
I believe this is intentional (see #4526); you should be able to enable `-fspv-use-legacy-buffer-matrix-order` in order to use the old behavior.

**Comment by turanszkij** [comment]
Thank you.
