### ISSUE TITLE
Cannot download prebuilt versions

### ISSUE THREAD

**Issue by otanter-at-ubi** [microsoft/DirectXShaderCompiler#4746]
Hi,
It looks like we can no more download the latest compiled windows builds from [here](https://ci.appveyor.com/api/projects/dnovillo/directxshadercompiler/artifacts/build%2FRelease%2Fdxc-artifacts.zip?branch=main&pr=false&job=image%3A%20Visual%20Studio%202019):

{"message":"Build job with specified name not found or access denied."}

The Ubuntu build can be downloaded just fine.

Cheers,
Olivier

**Comment by andrejnau** [comment]
Faced the same problem. Replacing `Visual Studio 2019` in the url with `Visual Studio 2022` helped. Try this [link](https://ci.appveyor.com/api/projects/dnovillo/directxshadercompiler/artifacts/build%2FRelease%2Fdxc-artifacts.zip?branch=main&pr=false&job=image%3A%20Visual%20Studio%202022).

**Comment by cassiebeckley** [comment]
Thanks for reporting this issue. I'll update the documentation to use the correct link.
