### ISSUE TITLE
[DXIL] Chunks can become misaligned after signature chunks

### ISSUE THREAD

**Issue by conor42** [microsoft/DirectXShaderCompiler#4755]
After emitting a signature chunk in the DXBC container, the position is not aligned to 32 bits, so later chunks don't begin on a 32-bit boundary if the signature element names are not a multiple of 4 bytes.

**Comment by tex3d** [comment]
This should be fixed in the latest released compiler+validator.
See: https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.7.2207
