### ISSUE TITLE
Is there a plan/experimental way to use true int8 data type?

### ISSUE THREAD

**Issue by ghostplant** [microsoft/DirectXShaderCompiler#4778]
No 8bit data type is found in the latest HLSL version. Bool type seems to work as same as int32 in data layout.

**Comment by llvm-beanz** [comment]
HLSL does not support 8-bit types. Please direct feature requests to our [specs repo](https://github.com/microsoft/hlsl-specs)

**Comment by devshgraphicsprogramming** [comment]
Also this is a duplicate of #4637 which has a really long discussion on the topic
