### ISSUE TITLE
ExecutionTest::DerivativesTest has invalid logic for 2D mesh shader thread groups

### ISSUE THREAD

**Issue by jenatali** [microsoft/DirectXShaderCompiler#4787]
For compute, the validation uses:
```c++
    if (D.height == 1) {
      centerIndex = (((UINT64)(D.width * D.height * D.depth) / 2) & ~0xF) + 10;
    } else {
      // To find roughly the center for compute, divide the height and width in half,
      // truncate to the previous multiple of 4 to get to the start of the repeating pattern
      // and then add 2 rows to get to the second row of quads and 2 to get to the first texel
      // of the second row of that quad row
      UINT centerRow = ((D.height/2UL) & ~0x3) + 2;
      UINT centerCol = ((D.width/2UL) & ~0x3) + 2;
      centerIndex = centerRow * D.width + centerCol;
    }
```

For mesh and amplification, the validation uses:
```c++
    UINT centerIndex = (((UINT64)(D.width * D.height * D.depth)/2) & ~0xF) + 10;
```

The shader code for writing the derivative data is the same between compute and mesh, so I'd expect to have the same logic on the host side for looking up where the data should live.

**Comment by hekota** [comment]
Few notes: 
- this test is failing on Microsoft Basic Render Driver
- it is passing on AMD and NVidia
- see also internal ADO bug #42507640.

**Comment by hekota** [comment]
The test is failing for Microsoft Basic Render Driver on the mesh shader case. The NVidia and AMD runs did not execute this part because the GPUs we have do not support derivatives in mesh and amplification shaders, and that's why it is passing on those.

**Comment by jenatali** [comment]
That's consistent with what I remember from when I investigated. This test had not successfully been run on any driver until WARP support came along.
