### ISSUE TITLE
[SPIR-V] Shader model 6.4 DP4a intrinsics aren't implemented

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/DirectXShaderCompiler#4819]
It looks like the "new" DP4a intrinsics aren't supported in SPIR-V mode even though these op's should be widely available.

Relevant SPIR-V specification: https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_integer_dot_product.html

Repro case: https://godbolt.org/z/Gzh4dxbhq

**Comment by sudonatalie** [comment]
Closing as duplicate of #4528
