### ISSUE TITLE
[SPIR-V] Why relaxed precision can't coexist with explicit 16bit types? 

### ISSUE THREAD

**Issue by godlikepanos** [microsoft/DirectXShaderCompiler#4820]
By looking at the `SPIR-V.rst` documentation when `-enable-16bit-types` is used the `min16float` types become explicit float16. Is there a reason why explicit 16bit types do not coexist with RelaxedPrecision? Why can't `min16float` stay as RelaxedPrecision float32 irrespective of `-enable-16bit-types`?

**Comment by s-perron** [comment]
> Why can't min16float stay as RelaxedPrecision float32 irrespective of -enable-16bit-types?

They can, but we chose not to. I was not part of the original decision, but I can guess why. The documentation for the minimum precision types is that they should use 16-bits if possible. When the `-enable-16bit-types` option is used, were are guarenteed to have 16-bit available, so we use it.

This is consistent with DXIL.  The resulting DXIL when using `-enable-16bit-types` with `half` or `min16float` is the same. See an example with [half](https://godbolt.org/z/Tnn93cvcP) and [min16float](https://godbolt.org/z/oqcdrK8zE). In the `min16float` case, you is even a compiler warning:

```
<source>:6:5: warning: 'min16float' is promoted to 'half' [-Wconversion]
    min16float b = 1.0;
    ^
warning: DXIL signing library (dxil.dll,libdxil.so) not found.  Resulting DXIL will not be signed for use in release environments.


Compiler returned: 0
```

I hope that answers your question.
