### ISSUE TITLE
Crash when swizzling group shared memory

### ISSUE THREAD

**Issue by harshpg** [microsoft/DirectXShaderCompiler#4856]
```
groupshared float ldsValues[16][16];

float4 loadGroupShared(uint x, uint y) { return ldsValues[x][y].xxxx; }
```

Using `.xxxx` will cause an exception to be thrown. Using `.x` or nothing at all fixes the issue.
This bug did not occur in the July 2022 release. I am testing with latest changes from master.

**Comment by Keenuts** [comment]
Hi!

Thanks for the report. Could you provide a bit more context on how to reproduce the bug?
- command line
- a shader as input to reproduce it.

Tried to feed a compute shader with those lines (and boilerplate around) to dxc at head (7ad9c9c0328ec53b26955142f2ce83d1673351a1) and I cannot reproduce.

**Comment by harshpg** [comment]
@Keenuts 

Thank you for investigating the issue. I tried reproducing the crash locally, but I am also unable to do so any longer. I'm not sure what changed though. Anyways, the code in question is here:

https://github.com/GPUOpen-Effects/FidelityFX-SSSR/blob/master/sample/src/Shaders/DepthDownsample.hlsl


```
groupshared float g_group_shared_depth_values[16][16];
groupshared uint g_group_shared_counter;

#define DS_FALLBACK

// Define fetch and store functions
AF4 SpdLoadSourceImage(ASU2 index, AU1 slice) { return g_depth_buffer[index].xxxx; }
AF4 SpdLoad(ASU2 index, AU1 slice) { return g_downsampled_depth_buffer[6][index].xxxx; } // 5 -> 6 as we store a copy of the depth buffer at index 0
void SpdStore(ASU2 pix, AF4 outValue, AU1 index, AU1 slice) { g_downsampled_depth_buffer[index + 1][pix] = outValue.x; } // + 1 as we store a copy of the depth buffer at index 0
void SpdResetAtomicCounter(AU1 slice) { g_global_atomic[0] = 0; }
void SpdIncreaseAtomicCounter(AU1 slice) { InterlockedAdd(g_global_atomic[0], 1, g_group_shared_counter); }
AU1 SpdGetAtomicCounter() { return g_group_shared_counter; }
AF4 SpdLoadIntermediate(AU1 x, AU1 y) {
	float f = g_group_shared_depth_values[x][y];
	return f.xxxx; 
}
```
