### ISSUE TITLE
Ray generation shader fails to build with latest dxc that was working fine before

### ISSUE THREAD

**Issue by Clothoid1** [microsoft/DirectXShaderCompiler#4862]
We are using dxc to generate spir-v binary code for our raytracing HLSL shaders.

When switching to the latest dxc build we noticed that some ray generation shaders fail to build, which were working fine with the dxc versions we used before.

The following error message is generated:
fatal error : generated SPIR - V is invalid : In Logical addressing, variables may not allocate a pointer type
% 50 = OpVariable % _ptr_Function__ptr_StorageBuffer_type_StructuredBuffer_v4float Function
note: please file a bug report on https ://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible

The parameters we used to build:
dxc.exe -spirv -T lib_6_4 -fspv-target-env=vulkan1.2 -E main %(FullPath) -Fo %(Filename).spv

I was able to generate a very simple reproducer:

```hlsl
RaytracingAccelerationStructure myAccelerationStructure : register(t0);
StructuredBuffer<float4> myBuffer : register(t1);

struct Payload
{
       float t;
};

static void doRayTracing()
{
       RayDesc aRayDesc;
       aRayDesc.Origin = float3(0.0, 0.0, 0.0);
       aRayDesc.Direction = float3(1.0, 0.0, 0.0);
       aRayDesc.TMin = 0;
       aRayDesc.TMax = 100;
       {
              Payload payload;
              TraceRay(myAccelerationStructure, RAY_FLAG_FORCE_OPAQUE, 0xff, 0, 0, 0, aRayDesc, payload);
       }
}

static float4 computeColour(const StructuredBuffer<float4> aBuffer_in)
{
       return float4(1.0, 1.0, 1.0, 1.0);
}

static float4 doCompute()
{
       return computeColour(myBuffer);
}

[shader("raygeneration")]
void main()
{
       doRayTracing();

       doCompute();
}

```

It seems that the combination of using TraceRay() and using a method that has a StructuredBuffer as input argument in the same shader is causing the problem.

**Comment by Keenuts** [comment]
(added color highlight to your code block)

Hi! Thanks for the report!
I tried to reproduce at head (7ad9c9c0328ec53b26955142f2ce83d1673351a1) with the given code and this command:
```
./build/bin/dxc -spirv -T lib_6_4 -fspv-target-env=vulkan1.2 -E main repro.hlsl
```
It outputs code, without myBuffer usage, since it's optimized-out. Tried to add a RWStructuredBuffer as output, read from myBuffer and output to it, still no bug.

Do you have a repro working at head? Or which version of DXC are you using?

**Comment by Clothoid1** [comment]
Thanks for looking into this issue!

I can reproduce this bug using this reproducer with your command line and a dxc of version
dxcompiler.dll: 1.7 - 1.7.0.3745 (4d66ec8a9)
(i am using Windows 10 as OS)

However, when downloading the latest build
dxcompiler.dll: 1.7 - 1.7.0.3756 (2c3d965b2)
i can no longer reproduce this bug!

Using this latest build also all our raytracing shaders compile fine again.
So it seems someone has already made a change recently that fixed this issue.

**Comment by Clothoid1** [comment]
Can be closed since it was already fixed in latest build.
