### ISSUE TITLE
[SPIR-V] Expected Constituent type to be equal to the corresponding member type of Result Type struct

### ISSUE THREAD

**Issue by turanszkij** [microsoft/DirectXShaderCompiler#4865]
Hello, I'm getting compile error when trying to compile mesh shader to spirv:

```
fatal error: generated SPIR-V is invalid: Expected Constituent type to be equal to the corresponding member type of Result Type struct
  %2953 = OpCompositeConstruct %ShaderMeshInstance_0 %2743 %2746 %2749 %2752 %2755 %2758 %2761 %2765 %2768 %2772 %2775 %2778 %2792 %2795 %2848 %2900 %2952

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

Repro:
run the `compile.bat` in the attached `dxc_bug.zip` file.
[dxc_bug.zip](https://github.com/microsoft/DirectXShaderCompiler/files/10202429/dxc_bug.zip)

Commit: https://github.com/microsoft/DirectXShaderCompiler/commit/ae87945a3c07e7088f525ea034767f175a682167

PS. sorry for the lot of files, but ripping out source is not very straight forward because of lot of header include dependencies.

**Comment by Keenuts** [comment]
Hi!

Thanks for the report! After some manual cleanup, I was able to reproduce on a small sample.

FYI, for your future reports:
 - include can be inlined by running the preprocesing step, then you can remove unnecessary code by hand.
 - avoid sending binaries, we won't run them anyway. Please provide a commit revision, or release version 😊
 
Steps to reproduce:

```hlsl
struct input_struct { float4 pos : SV_POSITION; };

struct A {
  int something;
};

struct B {
 uint some_field;
 A field_a;
};

ByteAddressBuffer bindless_buffers[];

[outputtopology("triangle")]
[numthreads(1, 1, 1)]
void main(
    in uint tid : SV_DispatchThreadID,
    in uint tig : SV_GroupIndex,
    in uint gid : SV_GroupID,
    out vertices input_struct verts[1],
    out indices uint3 triangles[1])
{
  B instance = bindless_buffers[0].Load<B>(0);
}
```

```
./build/bin/dxc -T ms_6_6 -spirv -fspv-target-env=vulkan1.2 repro.hlsl
fatal error: generated SPIR-V is invalid: Expected Constituent type to be equal to the corresponding member type of Result Type struct
  %62 = OpCompositeConstruct %B_0 %57 %61

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

**Comment by s-perron** [comment]
Looks like this is passing now: https://godbolt.org/z/1dKdaYWc4. I do know now what would have fixed it. Reopen if there is still an issue.
