### ISSUE TITLE
Linux: libdxcompiler.so dependency on libncurses5 library

### ISSUE THREAD

**Issue by turanszkij** [microsoft/DirectXShaderCompiler#4892]
Hello, when I updated the libdxcompiler.so recently, I got this error when trying to load the dynamic library:
```
libtinfo.so.5: cannot open shared object file: No such file or directory
```
`dlopen()` was used to load the libdxcompiler.so, and the error was retrieved by `dlerror()`. I'm not sure when this was introduced, because I updated a quite old version to this commit: 2c3d965b2fc734c09e76631de65f8ffbe4e3e68b

The error can be resolved by installing the `libncurses5` library, but this was not required by an older version of the compiler. 

Best regards,
Janos

**Comment by vettoreldaniele** [comment]
The library is brought in by LLVM here: https://github.com/microsoft/DirectXShaderCompiler/blob/main/lib/Support/CMakeLists.txt#L14. You can try setting `-DLLVM_ENABLE_TERMINFO=0` in the CMake command to disable it.

I quickly tried it and I can confirm this works:
```console
$ ldd lib/libdxcompiler.so
        linux-vdso.so.1 (0x00007ffed65f8000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb9a0400000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb9a2001000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb9a1fe1000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb9a0000000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb9a2101000)
```

**Comment by turanszkij** [comment]
Thank you, but I am not building DXC myself, but using the downloadable binaries, so I was hoping that this could be fixed inside the official repo.

**Comment by Jasper-Bekkers** [comment]
> I don't know that we get much (or any) benefit from linking terminfo at the moment because of how DXC manages output. The feature in LLVM that is driven with it is colorized error messages (which would be awesome to get working).

I'm not sure if the .so needs colorized output support though 😉

**Comment by llvm-beanz** [comment]
> I'm not sure if the .so needs colorized output support though 😉

The architecture of DXC requires that for the dxc executable to support colorized output the `.so` needs to supply that support since dxc is just a thin wrapper around the library.

That said, making dxc provide colorized output is likely a non-trivial amount of work since DXC's output writing system is... complicated. It is probably reasonable to set `LLVM_ENABLE_TERMINFO` to `Off` in the PredefinedParams.cmake file so that we don't bring in the curses dependency.
