### ISSUE TITLE
HLSL feature: Support for inout/out like C# ref

### ISSUE THREAD

**Issue by Nielsbishere** [microsoft/DirectXShaderCompiler#4907]
It would be very nice for code clarity to allow the following:
```hlsl
void ourFunc(inout float x) {
  x = 123;
}

float v;
ourFunc(inout v);
```
This would indicate that the function will write to v, instead of quietly hiding it like it does now. C# enforces the same, but of course HLSL could give a warning instead to allow backwards compatibility. The same could be applied for the out keyword as well.

**Comment by Keenuts** [comment]
Hi! Thanks for the report! If I'm not mistaken, this should be an issue submitted to https://github.com/microsoft/hlsl-specs

**Comment by Nielsbishere** [comment]
Thanks, added it there too.

**Comment by Keenuts** [comment]
Thanks! I believe this issue can now be closed. AFAIK process will be to review this feature, and if the HLSL language folks accepts this, then DXC will implement it when working on the new the HLSL version support 😊
