### ISSUE TITLE
Compile time const variable can't be used to specify const array lengths. ( Works with FXC )

### ISSUE THREAD

**Issue by hellokenlee** [microsoft/DirectXShaderCompiler#4915]
### Summary
Compile time const struct instanace can't be used to specify const array lengths. It worked with FXC then.

### Reproduce Steps
The following codes compiled with `dxc.exe -T ps_6_0 -E PSMain test.hlsl`. 
1. If we define an array using a const static int, it would compile:
```hlsl
static const int Len = 32;

float4 PSMain() : SV_TARGET
{
    float values[Len];
    return float4(values[0], 0.0, 0.0, 0.0);
}
```

2. But if we define an array using an int member variable of a const static instance, it wouldn't compile:
```hlsl
struct FInfo
{
    int Len0;
    int Len1;
};

static const FInfo Info0 = {2, 3};

float4 PSMain() : SV_TARGET
{
        float values[Info0.Len1];
        //          ^ error: variable length arrays are not supported in HLSL
	return float4(values[0], 0.0, 0.0, 0.0);
}
```
However, these codes got compiled with FXC.

### Expected Result
From a user perspective, a static const int should behave as same as a int member of a static const struct.

### Further More
It would be perfect if HLSL could provide a semantic like `constexpr` in C++.

**Comment by hellokenlee** [comment]
#3355

**Comment by hellokenlee** [comment]
Looks similar to #3355

**Comment by simondeschenes** [comment]
Also related to #4731

**Comment by llvm-beanz** [comment]
We have an [issue on hlsl-specs tracking constexpr](https://github.com/microsoft/hlsl-specs/issues/21), and #3355 for compile-time constants in array lengths, so I'm going to close this as a duplicate.

**Comment by devshgraphicsprogramming** [comment]
btw it works for me with `uint` but as soon as you launder it through a function it breaks.

https://github.com/microsoft/hlsl-specs/issues/74
