### ISSUE TITLE
DXCAPI.H makes hard-coded path assumptions on Linux

### ISSUE THREAD

**Issue by walbourn** [microsoft/DirectXShaderCompiler#4918]
The DXCAPI.H header has:

```
#include "dxc/Support/WinAdapter.h"
```

while the DXCISENSE.H header has:

```
#include "Support/WinAdapter.h"
```

Which both make explicit (and mismatched) assumptions about the layout that doesn't match the contents of the ZIP. This can be worked around, but in a future update it would be best to make both of these:

```
#include "WinAdapter.h"
```

**Comment by Keenuts** [comment]
HI,

Thanks for the report! We'll add that to the cleanup list we have in queue on DXC codebase. (If the change is as simple are changing an include path, PRs are always welcome 😊)
