### ISSUE TITLE
struct declared with [raypayload] can't have member function

### ISSUE THREAD

**Issue by guoxx** [microsoft/DirectXShaderCompiler#4933]
The below code failed to compile with shader model 6.7, the error messages are "Internal Compiler error: llvm::cast<X>() argument of incompatible type!"
If I remove the member function MyRayPayload::isPrimaryHit, it succeeds in compiling. Is it a bug for the compiler?

```
struct [raypayload] MyRayPayload
{
    uint pathLength : read(caller, anyhit, closesthit, miss) : write(caller, anyhit, closesthit, miss);

    bool isPrimaryHit()
    {
        return pathLength == 1;
    }  
}
```

**Comment by Keenuts** [comment]
Hi! Thanks for the report!

In order for us to work on this issue, could you provide us with the following things:

A build command, example:
```
dxc -T cs_6_6 -E main ./my_file.hlsl
```

A shader reproducing the issue we can copy/paste and try as is (important).

Thanks!

**Comment by sudonatalie** [comment]
Unfortunately there isn't enough information here for us to reproduce any error. If the above additional information is added we would be happy to re-open this issue in future.
