### ISSUE TITLE
Error: invalid application of 'sizeof' to non-numeric type

### ISSUE THREAD

**Issue by jeremyong** [microsoft/DirectXShaderCompiler#4938]
See the following snippet: https://godbolt.org/z/o1Tean3xr

The `sizeof` operator appears to work provided template structs are not used as struct fields.

**Comment by Keenuts** [comment]
Hi!
Thanks for the report! The issue does appear in goldbolt, but not at head (57512154fa3e48133f667f022528bce16251bc72).
The version in use here is quite old, and we fixed a lot of issues in HLSL2021 with the latest release (december).

Feel free to reopen if you can reproduce at head!

**Comment by jeremyong** [comment]
Thanks, it looks like the trunk build for CE is a commit from August 2022, I'll follow up to see if that can be updated!

**Comment by jeremyong** [comment]
FYI https://godbolt.org/z/Phs179W4e This issue has been fixed up stream with the help from the Compiler Explorer team (thanks @partouf! https://github.com/compiler-explorer/infra/commit/1274b1bae5afcca9b0a67d808ca4fba491f9ab4f)
