### ISSUE TITLE
[SPIR-V] Stop guessing image format if not specified

### ISSUE THREAD

**Issue by Keenuts** [microsoft/DirectXShaderCompiler#4941]
This issue originates from #4868.
When the image format is not specified, the SPIR-V backend tries to guess the correct format. This led to some issues like this one. Maybe we should just stop guessing format in those cases.

See also:
https://github.com/microsoft/DirectXShaderCompiler/issues/4868#issuecomment-1381992530_

**Comment by vettoreldaniele** [comment]
Another consideration for this discussion: some users may rely on reflecting the image format (see https://github.com/KhronosGroup/SPIRV-Reflect/blob/master/spirv_reflect.c#L93).

**Comment by godlikepanos** [comment]
It seems that the problem with image formats has started to annoy the Vulkan validation layers now. 

I have this:
```
RWTexture2D<float3> uav;
...
uav[uint2(0, 0)] = float3(1, 1, 1);
``` 

DXC incorrectly decorates the `uav` as Rgba32 and the Vulkan validation layers complain that you can't store 3 component data to 4 component image format:
```
Validation Error: [ VUID-RuntimeSpirv-OpImageWrite-07112 ] Object 0: handle = 0x1b960b7af30, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7fcb0409 | VkShaderModule 0x202f660000000fca[]: OpImageWrite Texel operand only contains 3 components, but the OpImage format mapping to VK_FORMAT_R32G32B32A32_SFLOAT has 4 components.
OpImageWrite 36 132 54 0
%11 = OpTypeImage 56 1 2 0 0 2 1 The Vulkan spec states: OpImageWrite to any Image whose Image Format is not Unknown must have the Texel operand contain at least as many components as the corresponding VkFormat as given in the SPIR-V Image Format compatibility table (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-RuntimeSpirv-OpImageWrite-07112)
```

For some bizarre reason this is validated by the Vulkan validation layers and not the spirv-val. 

@Keenuts It's probably a good idea to remove this image format guessing once and for all.

**Comment by Keenuts** [comment]
Hello! Yes might be. Adding that to my task list so I don't forget about this. Will circle back to this issue once I'm done with other stuff.

**Comment by Keenuts** [comment]
@godlikepanos Do you have a use-case today that would still require `Unknown` for image format we use? (Since the repro steps above are now working as intended)

One benefit of this guess is some kind of DirectX/Vulkan compat: HLSL shaders written for DXC should roughly work for Vulkan, and in some cases, without any change.

The issues we had so far were bugs in this guess, but from the spec point of view, it doesn't seem like we have any actual conflict:
 - atomic require a single-channel format, that's working as intended today.
 - subpass data require Unknown format, that's working today.
 - additional formats can be specified using `[[vk::image_format()]]`.
 - 'unknown' can be specified as a format if need to.

So unless there is an actual use-case that's impossible with what we have today, we might want to keep the format guessing.

**Comment by godlikepanos** [comment]
I remember I had some issues with Intel hardware with the format guessing. But I can't remember which format was problematic (the Intel I was testing was not sensitive to all formats but to some).

I think the best thing is to leave things as is as you suggested and when (and if) I bump into this issue again I'll create a new ticket with a proper use-case and justification.

**Comment by Keenuts** [comment]
Thanks! Closing this for now then 😊
