### ISSUE TITLE
[SPIR-V] Difficulties with NMin/NMax and lack of `-ffinite-math-only`

### ISSUE THREAD

**Issue by LukasBanana** [microsoft/DirectXShaderCompiler#4954]
Commit 2a0833a (@sudonatalie for visibility) introduced `OpNMin` and `OpNMax` to translate HLSL's `min`/`max` according to the specification. I generally appreciate compiler correctness over performance but in this case it not only introduces a lot of extra dynamic branching in the GLSL backend of SPIRV-Cross but it also exposed a bug in one of our third-party platform compilers which we don't have source access to.

With this ticket I merely want to ask if we can consider resurrecting Clang compiler options like `-ffinite-math-only` to have an option to prefer performance and stability over correctness. I'm sure there are cases were the correct behavior of `min`/`max` with `NaN` are necessary, but in our case, it also causes stability issues.

My proposal for the intrinsics in question at [SpirvEmitter.cpp#L8613](https://github.com/microsoft/DirectXShaderCompiler/blob/bef540d360d5b737c83678ffde572820d1e12ec4/tools/clang/lib/SPIRV/SpirvEmitter.cpp#L8613) would look like this:
```cpp
  case hlsl::IntrinsicOp::IOP_min: {
    glslOpcode = isFloatType
                     ? (getCompilerInstance().getLangOpts().FiniteMathOnly // FMin if '-ffinite-math-only'
                            ? GLSLstd450::GLSLstd450FMin
                            : GLSLstd450::GLSLstd450NMin)
                 : isSintType ? GLSLstd450::GLSLstd450SMin
                              : GLSLstd450::GLSLstd450UMin;
    retVal = processIntrinsicUsingGLSLInst(callExpr, glslOpcode, true, srcLoc,
                                           srcRange);
    break;
  }
// same for IOP_Max
```
Thanks for considering and kind regards

Laura

**Comment by Keenuts** [comment]
Hi @LukasBanana!


I see no reason not to enable this option, as it clearly states it enabled unsafe options. Sent out a PR implementing this. Thanks for the snippet 😊

**Comment by LukasBanana** [comment]
Thanks @Keenuts I appreciate your effort to get that into main stream.
