### ISSUE TITLE
[SPIR-V] Ternary Assignment of `half`s from float literals in HLSL 2021 mode produces invalid SPIR-V

### ISSUE THREAD

**Issue by troughton** [microsoft/DirectXShaderCompiler#4961]
Code of the form:

```
half result = condition ? 1.0 : 0.0;
```

results in invalid SPIR-V of the form:

```
  %half = OpTypeFloat 16  
  %float = OpTypeFloat 32
  %_ptr_Function_float = OpTypePointer Function %float
  %temp_var_ternary = OpVariable %_ptr_Function_float Function
  %445 = OpLoad %half %temp_var_ternary
```

which errors in `spirv-opt` with "OpLoad Result Type <id> '58[%half]' does not match Pointer <id> '249[%temp_var_ternary]'s type."

when compiling to SPIR-V with the flags `-enable-16bit-types`, `-HV 2021`, `-fspv-target-env=vulkan1.1`, `-fspv-reflect`, `-spirv`, `-fcgl`.

**Comment by Keenuts** [comment]
Hi! Thanks for the report!

This seems related to https://github.com/microsoft/DirectXShaderCompiler/issues/4727 , but this time it's not a sign issue, but a literal float to half issue:

```python
  | |-DeclStmt 0x55bae16fd040 <line:5:5, col:45>
  | | `-VarDecl 0x55bae16fce80 <col:5, col:42> col:10 result 'half':'half' cinit
  | |   `-ImplicitCastExpr 0x55bae16fd028 <col:19, col:42> 'half':'half' <FloatingCast>
  | |     `-ConditionalOperator 0x55bae16fcff8 <col:19, col:42> 'literal float'
```

We might have some logic into the spirv generation to ignore cast from literal float to float, which is wrong.
Looking into that.

**Comment by Keenuts** [comment]
Hello! Sorry, haven't had time to look back at this. The fix for uint/int doesn't fixes this, so this is still an issue.

**Comment by s-perron** [comment]
I believe this is fixed by https://github.com/microsoft/DirectXShaderCompiler/pull/5324.
