### ISSUE TITLE
Support  SPIRV -> DXIL

### ISSUE THREAD

**Issue by iwubcode** [microsoft/DirectXShaderCompiler#4969]
Apologies if I missed this, I looked around and didn't see this already.

Would like to request converting from SPIRV -> DXIL .  From what I understand there is already functionality that supports the opposite.

Currently working on a project that takes GLSL and converts to SPIRV then generates HLSL off of that so that it can then compile that HLSL into formats that DX11 and DX12 can leverage.  This happens in _realtime_ due to how our software works.  It would be much more efficient to go directly from SPIRV to DXIL but no systems seem to support this (we currently use SPIRV-Cross).

**Comment by Keenuts** [comment]
Hello!

This won't be the goal of this compiler, since we really focus on HLSL -> some IR translation, but you might want to look into mesa, apparently they have a SPIRV->DXIL library which receives patches, just unsure of the support level:
- https://cgit.freedesktop.org/mesa/mesa/
- mesa/src/microsoft/spirv_to_dxil
- https://www.phoronix.com/news/Microsoft-SPIRV-DXIL-Mesa-Lib

**Comment by iwubcode** [comment]
@Keenuts - thank you.  Can this be raised internally that there is at least some interest to do this work?  The Godot game engine used Mesa https://github.com/godotengine/godot/pull/70315 and they said that was better than the alternative (Spirv-cross) but it still uses an intermediate layer "NIR".

Given that SPIRV and DXIL are the two main modern solutions, surely other teams are also running into this hurdle.  But seems like there isn't much interest from projects that work on this sort of work (see https://github.com/HansKristian-Work/dxil-spirv/issues/103 ).

I will look into Mesa as an option.  Thank you for your time!

**Comment by Keenuts** [comment]
Hello again!
Not speaking for Microsoft, but AFAIK, from our team point-of-view, we have no immediate interest in building/maintaining this at the moment, sorry 😊

**Comment by Keenuts** [comment]
Hi,

> * there are < 500 commands/constructs/instructions/whatever on both sides; DXIL and SPIRV

Not sure what you are referring to with the `500` commands. Translating DXIL to SPIR-V is not just a matter of mapping one instructions to another. It would require modifying the control flow, understanding SPV-VK extensions and transform those to DX equivalent, and modifying resource access as both language handle those differently.

> * a compiler knows how to go from IR -> either sides

DXC does not uses the same path for both DXIL and SPIR-V.
SPIR-V is lowered directly from the AST, skipping LLVM IR, while DXIL goes through a more normal path. Hence only common points we have between the 2 paths is either HLSL or the AST, and both are very high-level, and completely lost once we have SPIR-V. Hence, adding a path converting SPIR-V to DXIL would be a whole new thing, hence reusing DXC for this matter is not helping.


And last bit, VirtioGPU on Windows is not just a matter of translating DXIL to SPIR-V, but also translating a guest Win32 app 3D call (Possibly DX9, DX12, Vk or even OpenGL) into virgl commands so it can be translated again into something the host can support (maybe the host only supports OpenGL).

**Comment by xen2** [comment]
The Sep 2024 MS blog post https://devblogs.microsoft.com/directx/directx-adopting-spir-v/ specifically states:

> In addition to providing a compiler for HLSL to Direct3D’s SPIR-V, we will also be building and providing translation tools to translate SPIR-V to DXIL and DXIL to SPIR-V. Those tools will allow and driver developers to gradually transition and gracefully adapt tooling and drivers.

Is this still planned? (or maybe already being developed somewhere?)
Will it be in this repo or a separate project?
