### ISSUE TITLE
Missing constant buffer default values from shader reflection

### ISSUE THREAD

**Issue by turanszkij** [microsoft/DirectXShaderCompiler#4981]
Hello, constant buffer parameters can have default values in HLSL, but I cannot get to see them in the shader reflection. This is important when porting old shaders from DX11 renderer that relied on initializing default values. The `D3D12_SHADER_VARIABLE_DESC::DefaultValue` is always `nullptr`, when it should be a valid pointer if a default value was specified for a member of constant buffer.

I can see a related issue that should be a non-issue, because default values are correct in HLSL syntax: https://github.com/microsoft/DirectXShaderCompiler/issues/2384

**Comment by mcbouterse** [comment]
+1

**Comment by MohitSethi99** [comment]
+1

**Comment by pow2clk** [comment]
I realize that the explanation in #2380 (which spawned #2384) didn't make clear that while this behavior was supported in FXC, we made the decision to remove it from dxc. As such, we should produce a warning that the value is completely ignored. While we regret this has some impact on previous approaches, we haven't changed the decision to remove this behavior.
