### ISSUE TITLE
[Linux] dlopen("libdxcompiler.so") dlopen error /usr/lib/libtinfo.so.5: version `NCURSES_TINFO_5.0.19991023' not found (required 

### ISSUE THREAD

**Issue by Andreyogld3d** [microsoft/DirectXShaderCompiler#4990]
Hi, I'm trying to use DXC compiler on Linux. I got error on Linux Manjaro:

[andreyvkd3d@andreyvkd3d Release]$ ./dxc_test
**dlopen error /usr/lib/libtinfo.so.5: version `NCURSES_TINFO_5.0.19991023' not found (required by ./libdxcompiler.so)**
[andreyvkd3d@andreyvkd3d Release]$

The similar error: https://vulkan.lunarg.com/issue/view/63181d6e5df1129602e806f8

**Comment by vettoreldaniele** [comment]
Currently the dxc library that is released relies on the ncurses library. You can solve your problem by installing the ncurses library using your favorite package manager.

**Comment by Andreyogld3d** [comment]
[vettoreldaniele](https://github.com/vettoreldaniele) Thanks, It works,  after installing ncurses.
