### ISSUE TITLE
Investigate fail in AppVeyor when enable lit by default

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#4997]
When enable lit by default, AppVeyor will fail while azure pipeline pass.

The log does not tell much information except an error code.
> Success - files are available at c:\projects\DirectXShaderCompiler\build\Release\bin
> utils\appveyor\appveyor_test.ps1
> Running taef tests
> Parsing taef tests
> Uploading results to AppVeyor
> Done
> Command exited with code 83886080

Here's link to a fail run
https://ci.appveyor.com/project/dnovillo/directxshadercompiler/builds/46133692/job/ogaqh97tfeefv5l5

**Comment by llvm-beanz** [comment]
The build is failing running utils\appveyor\appveyor_test.ps1

**Comment by llvm-beanz** [comment]
Closing this since we've already worked around the issue.
