### ISSUE TITLE
Investigate the HLSL change code in scalarizer

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#5008]
We have code in Scalarizer::visitShuffleVectorInst which clones extract element instruction.

It might not be neccessary.

**Comment by pow2clk** [comment]
@python3kgae, can you give more details? Why do you think this is unnecessary? @tex3d introduced this with #1128. It looks like upstream has no such changes and there isn't a bug associated with any more information 😒 

https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/Scalar/Scalarizer.cpp#L868

**Comment by damyanp** [comment]
Closing as not planned unless someone can come back with more information.
