### ISSUE TITLE
[SPIR-V] Access Violation When Passing Multiple Unbounded Resource Arrays Into Function

### ISSUE THREAD

**Issue by lukedan** [microsoft/DirectXShaderCompiler#5015]
## test.i
```
float4 func(Texture2D<float4> textures[], StructuredBuffer<float3> positions[]) {
 return (float4)0;
}

Texture2D<float4> textures[] : register(t0, space1);
StructuredBuffer<float3> positions[] : register(t0, space2);

[numthreads(8, 8, 1)]
void main_cs(uint2 dispatch_thread_id : SV_DispatchThreadID) {
 float4 x = func(textures, positions);
}
```

SPIR-V: `dxc test.i -Ges -Zi -Zpr -spirv -fspv-reflect -fspv-target-env=vulkan1.2 -fvk-use-dx-layout -no-legacy-cbuf-layout -E main_cs -T cs_6_6 -HV 2021 -Zi -enable-16bit-types -Fo test.vk.o`

DXIL: `dxc test.i -Ges -Zi -Zpr -no-legacy-cbuf-layout -E main_cs -T cs_6_6 -HV 2021 -Zi -enable-16bit-types -Fo test.dx.o`

The second one compiles fine while the first one fails with
```
Internal compiler error: access violation. Attempted to read from address 0x000000000000002C
```

If the second parameter of `func()` is removed, the program compiles fine in both modes.

I'm using the version of DXC bundled with Vulkan SDK 1.3.236.0.
```
dxcompiler.dll: 1.7 - 1.7.0.3738 (cafbbed4d)
```

**Comment by s-perron** [comment]
This was fixed by Handle local arrays of RWStructrued buffers (#5523), and should be in the next version of the vulkan sdk.
