### ISSUE TITLE
Invalid SPIR-V generated with type-mismatch in ternary operator expression

### ISSUE THREAD

**Issue by jkoenen** [microsoft/DirectXShaderCompiler#5025]
The following code snipped creates invalid SPIR-V using a recent version of the compiler.

Version info: dxcompiler.dll: 1.7(dev;1-349a0e57)

Expected output: The compiler should ideally emit a warning about the type-mismatch and (depending on the warning level) do an implicit cast.

~~~
RWStructuredBuffer<uint> g_data;

[numthreads( 8, 1, 1 )]
void cs_main( uint3 invocationId : SV_DispatchThreadID )
{
    bool isFirst = invocationId.x == 0;
	
    g_data[ 0 ] = isFirst ? 1 : 0;
}
~~~

Compiler output:
~~~
fatal error: generated SPIR-V is invalid: OpStore Pointer <id> '24[%24]'s type does not match Object <id> '23[%23]'s type.
  OpStore %24 %23

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible

Compiler returned: 5
~~~

**Comment by Keenuts** [comment]
Hi @jkoenen!

Thanks for the report. This has indeed been fixed with c524f5e1752c529ffbdec319aa8db18b206d312d.
At least I cannot repro at HEAD.
(Thanks for pinging Daniele! 😊)
