### ISSUE TITLE
Type annotation size wrong for matrix types in UAV

### ISSUE THREAD

**Issue by baldurk** [microsoft/DirectXShaderCompiler#5030]
This might be an easy one to close, I'm not sure if `dx.typeAnnotations` is still used/maintained? If not then this issue is a no-op.

If I compile a shader with a structured buffer containing a matrix the type annotation reports the wrong byte size. I originally reproduced this on [`tools/clang/test/HLSLFileCheck/hlsl/objects/AppendStructuredBuffer/append_mat_row_major.hlsl`](https://github.com/microsoft/DirectXShaderCompiler/blob/main/tools/clang/test/HLSLFileCheck/hlsl/objects/AppendStructuredBuffer/append_mat_row_major.hlsl) but on looking closely it seems to also apply on regular float matrices in a different way. Take this shader `repro.hlsl`:

```c
#ifdef HALF
AppendStructuredBuffer<float16_t3x3> halfbuf;

void main() {
	float16_t3x3 m = float16_t3x3(1, 2, 3, 4, 5, 6, 7, 8, 9);
	halfbuf.Append(m);
}
#else
AppendStructuredBuffer<float3x3> floatbuf;

void main(){
	float3x3 m = float3x3(1, 2, 3, 4, 5, 6, 7, 8, 9);
	floatbuf.Append(m);
}
#endif
```

Compile with `dxc repro.hlsl -T vs_6_0 -Zi` from `dxcompiler.dll: 1.7 - 1.7.2212.12 (8c9d92be7); dxil.dll: 1.7(101.7.2212.14)` I get (snipped) output like this:

```
!dx.typeAnnotations = !{!44, !48}
!44 = !{i32 0, %"hostlayout.class.AppendStructuredBuffer<matrix<float, 3, 3> >" undef, !45}
!45 = !{i32 44, !46}
!46 = !{i32 6, !"h", i32 2, !47, i32 3, i32 0, i32 7, i32 9}
!47 = !{i32 3, i32 3, i32 2}
```

which indicates that the structured buffer is 44 bytes (first entry in the structure annotation metadata). I believe it should be 36 bytes for 9 tightly packed floats. I think 44 bytes = 3 rows of 16-byte aligned float4, plus a row of float3.

Notably (the original bug I noticed) if you compile with `-DHALF=1` you'll get the same byte size reported, which is even more wrong.

----

Looking into the code it seems to use the cbuffer size to output the byte size, which explains the float4 alignment - and I'm guessing cbuffers don't support 16-bit types so it's also getting upconverted half -> float in the half case?:

https://github.com/microsoft/DirectXShaderCompiler/blob/4d7b69c81dabdf9cbe113913850b9736b4bbf43a/lib/DXIL/DxilMetadataHelper.cpp#L1033-L1043

**Comment by damyanp** [comment]
We think that this is by design - surprisingly, the size in this metadata describes the size that the struct would be in if it were in a constant buffer.
