### ISSUE TITLE
DXC crashing on while(true)-loop

### ISSUE THREAD

**Issue by jasilvanus** [microsoft/DirectXShaderCompiler#5035]
# Summary
`DXC` crashes when compiling the following example with `-T lib_6_7`, apparently during a PAQ analysis that is not enabled with earlier shader models:

```HLSL
[shader("raygeneration")] void RayGen() {
   while (true) {
      break;
   }
}
```

# Fix
In `Support/GenericDomTreeConstruction.h:94`, it seems we should check for `Succ` being non-null, which can be caused by optimized-out successor nodes.

(I cannot contribute the fix myself due to the CLA).

**Comment by pow2clk** [comment]
Thanks @jasilvanus!

@dmpots thinks that this is the same issue he filed here #4920

The suggested fix is very much appreciated. I'm a bit wary that it's in so fundamental a location. What does the PAQ analysis do that introduces the possibility of the successor node being null?

**Comment by jasilvanus** [comment]
I am not an expert on that code, but my understanding is that the DFS in question here (which has been replaced by now in upstream LLVM) in general has the issue of not working correctly with `nullptr` successor nodes, and the PAQ analysis just happens to run that DFS on a CFG graph containing nullptr successors.

The graph uses `clang::CFGBlock` nodes, whose documentation says:

```
/// Successors: the order in the set of successors is NOT arbitrary.  We
///  currently have the following orderings based on the terminator:
///
///     Terminator       Successor Ordering
///  -----------------------------------------------------
///       if            Then Block;  Else Block
///     ? operator      LHS expression;  RHS expression
///     &&, ||          expression that uses result of && or ||, RHS
///
/// But note that any of that may be NULL in case of optimized-out edges.
```

This matches the behavior of crashing on `if (true)`, where an (empty) else block being optimized out would be expected.
