### ISSUE TITLE
Binaries in Linux release package don't have executable permissions

### ISSUE THREAD

**Issue by hekota** [microsoft/DirectXShaderCompiler#5075]
Binaries in Linux release package don't have executable permissions which is necessary for using the compiler. The permissions are probably set correctly by the Linux build pipeline, but the package creation is running on Windows and that's likely where the permissions bits are getting dropped.

**Comment by llvm-beanz** [comment]
To confirm, this is still a problem on the latest releases:
```shell
> curl -fsSL -o dxc.tar.gz https://github.com/microsoft/DirectXShaderCompil
er/releases/download/v1.7.2308/linux_dxc_2023_08_14.x86_64.tar.gz
> tar xvzf dxc.tar.gz
./LICENSE-LLVM.txt
./LICENSE-MS.txt
./README.md
./bin/dxc
./include/dxc/WinAdapter.h
./include/dxc/dxcerrors.h
./include/dxc/dxcapi.h
./include/dxc/dxcisense.h
./lib/libdxil.so
./lib/libdxcompiler.so
> ls -la ./bin/*
-rw-r--r-- 1 cbieneman cbieneman 895976 Aug 14 14:27 ./bin/dxc
```

**Comment by hekota** [comment]
This is fixed and will show in the next release.
