### ISSUE TITLE
[SPIR-V] Combined image sampler with descriptor indexing?

### ISSUE THREAD

**Issue by coffeenotfound** [microsoft/DirectXShaderCompiler#5076]
I'm having a hard time figuring out how to use descriptor indexing with a COMBINED_IMAGE_SAMPLER descriptor type.

I have tried
```
// Set 1, binding 0 is a variable descriptor size binding
[[vk::binding(0, 1), vk::combinedImageSampler]] Texture2D<float4> indexedTexs[];
[[vk::binding(0, 1), vk::combinedImageSampler]] SamplerState indexedTexSamplers[];
```
but then dxc complains with
```
foobar_shader.hlsl:27:22: error: 'combinedImageSampler' attribute only applies to Textures (e.g., Texture2D) and SamplerState
[[vk::binding(0, 1), vk::combinedImageSampler]] Texture2D<float4> indexedTexs[];
                     ^
foobar_shader.hlsl:28:22: error: 'combinedImageSampler' attribute only applies to Textures (e.g., Texture2D) and SamplerState
[[vk::binding(0, 1), vk::combinedImageSampler]] SamplerState indexedTexSamplers[];
```

Removing the vk::combinedImageSampler attribute makes dxc compile the shader without warning but makes the vulkan validation layers very unhappy:

```
VUID-VkComputePipelineCreateInfo-layout-00703(ERROR / SPEC): msgNum: -432263797 - Validation Error: [ VUID-VkComputePipelineCreateInfo-layout-00703 ] Object 0: handle = 0x1dfae200530, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xe63c2d8b | Shader uses descriptor slot 1.0 (expected `VK_DESCRIPTOR_TYPE_SAMPLER, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER`) but not declared in pipeline layout The Vulkan spec states: layout must be consistent with the layout of the compute shader specified in stage (https://vulkan.lunarg.com/doc/view/1.3.224.1/windows/1.3-extensions/vkspec.html#VUID-VkComputePipelineCreateInfo-layout-00703)
    Objects: 1
```
(The pipeline layout *does* declare COMBINED_IMAGE_SAMPLER for set 1 binding 0, which is a variable descriptor count binding)

**Comment by Keenuts** [comment]
Hello!

I'm not 100% sure, but it seems that we simply don't support the vk::combinedImageSampler for arrays of textures.
@cassiebeckley do you know more about this?

**Comment by coffeenotfound** [comment]
Sorry for not keeping you updated on this!

Without the vk::combinedImageSampler attribute it does seem to work now with the two separate arrays as written in the original post.

It's still a bit weird though. The valiation layers at one point talked about the descriptor as being of type "(VK_DESCRIPTOR_TYPE_SAMPLER, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE)" (paraphrased since I don't have the exact message anymore, sorry!) instead of VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER.
Unfortunately, I am not too well versed in spir-v to know whether dxc compiles this all just fine or if it's the Nvidia drivers fudging it a bit and making it work even though it really shouldn't (they do do that quite often)

If it helps I can provide a spir-v file, but the repro is really just the first two lines of code from the original issue minus the vk::combinedImageSampler attribute

**Comment by Keenuts** [comment]
Hi!

No worries!
Yes, without arrays of texture are allowed, it's really about the actual attribute to declare it as combinedImageSampler. This one doesn't support arrays, but unsure if that's because at the time, we didn't required it, or if there is a real reason behind.

As for layers complaining if you don't put it, it's because if the attribute is not set on a texture/sampler, then the type will become sampler/texture. So it is expected of the layer to complain 🙂

**Comment by coffeenotfound** [comment]
Funnily enough the validation layers don't even complain about it without the attribute and it works just fine! :D

Since it works I guess the issue can be closed for now, but from what I can tell the attribute *would* actually be necessary on arrays to get correct spir-v output:

Indexed descriptor without vk::combinedImageSampler:
```
// [[vk::binding(0, 1)]] Texture2D<float4> indexedTexs[];
// [[vk::binding(0, 1)]] SamplerState indexedTexSamplers[];

%type_2d_image_3 = OpTypeImage %float 2D 2 0 0 1 Unknown
%_ptr_UniformConstant_type_2d_image_3 = OpTypePointer UniformConstant %type_2d_image_3
%indexedTexs = OpVariable %_ptr_UniformConstant__runtimearr_type_2d_image_3 UniformConstant
%indexedTexSamplers = OpVariable %_ptr_UniformConstant__runtimearr_type_sampler UniformConstant
```

Normal combined image sampler descriptor:
```
// [[vk::binding(2, 0), vk::combinedImageSampler]] VisbufferTexture<uint> texVisId;
// [[vk::binding(2, 0), vk::combinedImageSampler]] SamplerState samplerVisId;

%162 = OpTypeSampledImage %type_2d_image
%_ptr_UniformConstant_162 = OpTypePointer UniformConstant %162
%texVisId = OpVariable %_ptr_UniformConstant_162 UniformConstant
```

Notice how texVisId is a `OpTypeSampledImage` (image+sampler) while indexedTexs is only a `OpTypeImage`

**Comment by Keenuts** [comment]
> Funnily enough the validation layers don't even complain about it without the attribute and it works just fine! :D

Not sure I follow, I probably misunderstood your previous comment around the validation error message then. Important point is it works for you!



> %type_2d_image_3 = OpTypeImage %float 2D 2 0 0 1 Unknown
> %162 = OpTypeSampledImage %type_2d_image
> Notice how texVisId is a `OpTypeSampledImage` (image+sampler) while indexedTexs is only a `OpTypeImage`

Right, as expected no?
OpTypeImage -> image
OpTypeSampler -> sampler
OpTypeImageSampler -> combined image sampler.

If you set the attribute, OpTypeImageSampler should be generated, otherwise, OpTypeImage & OpTypeSampler.

Happy it works for you in the end then 😊 Closing this.

**Comment by coffeenotfound** [comment]
> Right, as expected no?

Well, the problem is that indexedTexs should really be a OpTypeImageSampler, but setting the attribute on arrays isn't possible, which is a bug/issue. I honestly don't know why it works despite that, but oh well!
