### ISSUE TITLE
[[vk::PointSize]] isn't enough for point sprites

### ISSUE THREAD

**Issue by alecazam** [microsoft/DirectXShaderCompiler#5099]
I will never understand why DX10 forced out the use of PSIZE which could specify 2 dimensions for the sprite vs. PointSize which requires them all square.  I know the Geometry Shaders were critical to adopt back then, but became a performance choakpoint for all that used them.

I see that DXC will pass along vk::PointSize, but what about PointCoord in the fragment shader?  That is equally important, or is the caller expected to convert SV_Position?

**Comment by s-perron** [comment]
You can get access to the PointCoord builtin by using inline spir-v. Here is an example: https://github.com/microsoft/DirectXShaderCompiler/blob/815055bb018dd70187236b9272a473f87d6be076/tools/clang/test/CodeGenSPIRV/spv.intrinsicDecorate.hlsl.

Note that this mechanism has some limitations. Hopefully https://github.com/microsoft/hlsl-specs/pull/59 will improve on it, but that might take a while.
