### ISSUE TITLE
16-bit rcp should be done in 32-bit precision

### ISSUE THREAD

**Issue by dmpots** [microsoft/DirectXShaderCompiler#5100]
I am seeing something unexpected when using rcp on a float value that is converted to half. The rcp is done with 16-bit precision instead of 32-bit followed by a conversion to 16-bit.

Is there something that allows the compiler to use 16-bits for the div here instead of using the full 32-bit value? I also tried adding precise, but that did not make a difference.

Note that other operations (e.g. `rsqrt, sin, cos`) will do the operation in the full 32-bit value.

### Repro shader
```
// dxc /Tcs_6_2 -enable-16bit-types rcp.hlsl
Texture1D<half> I0 : register(t0);
Texture1D<half> I1 : register(t1);
Texture1D<half> I2 : register(t2);
Texture1D<half> I3 : register(t3);
RWTexture1D<half> O0 : register(u0);
RWTexture1D<half> O1 : register(u1);
RWTexture1D<half> O2 : register(u2);
RWTexture1D<half> O3 : register(u3);


[RootSignature("DescriptorTable(SRV(t0,numDescriptors=4),UAV(u0,numDescriptors=4))")]
[numthreads(64, 1, 1)]
void main(uint id : SV_DispatchThreadId)
{
    O0[id] = half(  rcp(float(I0[id])));
//    O1[id] = half(rsqrt(float(I1[id])));
//    O2[id] = half(  sin(float(I2[id])));
//    O3[id] = half(  cos(float(I3[id])));
}
```

### Expected Output
The dxil should have a float div followed by a fptrunc to half.

### Actual Output
The div is done in 16-bit precision.

```
define void @main() {
  %1 = call %dx.types.Handle @dx.op.createHandle(i32 57, i8 1, i32 0, i32 0, i1 false)  ; CreateHandle(resourceClass,rangeId,index,nonUniformIndex)
  %2 = call %dx.types.Handle @dx.op.createHandle(i32 57, i8 0, i32 0, i32 0, i1 false)  ; CreateHandle(resourceClass,rangeId,index,nonUniformIndex)
  %3 = call i32 @dx.op.threadId.i32(i32 93, i32 0)  ; ThreadId(component)
  %4 = call %dx.types.ResRet.f16 @dx.op.textureLoad.f16(i32 66, %dx.types.Handle %2, i32 0, i32 %3, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef)  ; TextureLoad(srv,mipLevelOrSampleCount,coord0,coord1,coord2,offset0,offset1,offset2)
  %5 = extractvalue %dx.types.ResRet.f16 %4, 0
  %6 = fdiv fast half 0xH3C00, %5
  call void @dx.op.textureStore.f16(i32 67, %dx.types.Handle %1, i32 %3, i32 undef, i32 undef, half %6, half %6, half %6, half %6, i8 15)  ; TextureStore(srv,coord0,coord1,coord2,value0,value1,value2,value3,mask)
  ret void
}
```

**Comment by llvm-beanz** [comment]
This is the expected behavior. We do generate the `rcp` as 32-bit, and you can [see that at `-O0`](https://godbolt.org/z/cW6KrEzEd).

The issue is that `rcp` is just an instruction sequence, so LLVM recognizes the pattern for `fpext` -> `fdiv` -> `fptrunc` and it folds that to just performing the `fdiv` on half. 

The optimizer can't do that for `rsqrt`, `sin` or `cos` because those translate to DXIL operations that only exist for `f32`.

@dmpots, is there a specific need for a fix here, or was this just a behavior you didn't expect?

**Comment by dmpots** [comment]
I was confused by the difference in behavior between the rcp and the others, but your explanation has helped. Note that we do actually have `f16` overloads for `rsqrt`, `sin`, and `cos` in dxil. But I believe we should not convert these to use the 16-bit overloads here.

The difference between `rcp` and the others is that `rcp` is a *single* operation. And the transformation of

```
fptrunc.f16(fpext.f32(h0) op.f32 fpext.f32(h1)) 
==> 
h0 op.f16 h1 
```
is valid and will not result in a loss of precision. The difference with `rsqrt`, `sin`, and `cos` is that those will become complex sequences of instructions where the intermediate precision matters. So even though we do have `f16` overloads for them we should not use them here.


And just as a little experiment we can see that a single op will be transformed by the compiler to lower precision
```
half(float (h0) + float (h1))
==>
h0 + h1
```

but a chain of operations like this will be left alone.
```
float(h0) + float(h1) + float(h2)
```
It leaves the computation in f32 because the intermediate value (`float(h0) + float(h1)` ) does not come from an `fpext` so it cannot be safely transformed.

So it looks like this was just be being confused and there is nothing to fix here.

Thanks!
