### ISSUE TITLE
Endian swap function outputs "llvm.bswap.i32' is not a DXIL function" as an error

### ISSUE THREAD

**Issue by DarioSamo** [microsoft/DirectXShaderCompiler#5104]
I only tested on commit 51777bd2b04a2d32d0d816b0dfe2145b770c2d6a with the `-HV 2021` flag. Using`-Od` eliminates the issue.

Using the following code results in this error

```
uint EndianSwapUINT32(uint i) {
    return ((i << 24) & 0xFF000000) | ((i << 8) & 0xFF0000) | ((i >> 8) & 0xFF00) | ((i >> 24) & 0xFF);
}
```

It seems LLVM is recognizing this particular pattern and generating an instruction not recognized by DXIL.

I'm not sure if more code is necessary, but the function is merely used to swap an uint loaded from an SRV.

Apologies in advance if this has been fixed in a more recent version.

**Comment by DarioSamo** [comment]
I've been able to work around this with the following code:
```
[noinline]
uint EndianSwapUINT32A(uint i) {
    return ((i << 24) & 0xFF000000) | ((i >> 24) & 0xFF);
}

uint EndianSwapUINT32B(uint i) {
    return ((i << 8) & 0xFF0000) | ((i >> 8) & 0xFF00);
}

uint EndianSwapUINT32(uint i) {
    return EndianSwapUINT32A(i) | EndianSwapUINT32B(i);
}
```

**Comment by llvm-beanz** [comment]
This is probably caused by `InstCombiner::MatchBSwap`

**Comment by DarioSamo** [comment]
Can confirm this still happens as of the latest release. I currently need to work around this by disabling shader optimizations in the affected files. Is there any possibility of it being fixed soon or should I find some other way to work around it?

**Comment by Mr-Wiseguy** [comment]
This issue still seems to happen as tested on godbolt dxc trunk, which is currently a56078a. Here's a minimal godbolt example that reproduces it: https://godbolt.org/z/bT8zdvTjb

**Comment by DarioSamo** [comment]
Thanks!
