### ISSUE TITLE
[validator] need a way to resolve error message in dxil.dll

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#5108]
In case validation fail, the error message will be in an IDxcBlobEncoding ptr.

If only use dxil.dll to validate a container,
there's no GetBLobAsUtf8 exported in dxil.dll to translate the data.

**Comment by llvm-beanz** [comment]
This is related to #5109, and also needed for Clang, so I'm adding it to the Roadmap.

**Comment by damyanp** [comment]
As more of the validator is open-sourced we need to plan how we're going to make that work with what we're doing in clang, so this issue doesn't serve any purpose.
