### ISSUE TITLE
[dxv] a mode to only use dxil.dll

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#5109]
Now dxv is dependent on dxcompiler to validate the container.

If release dxv as an external tool, it should be able to validate a container with only dxil.dll.

**Comment by llvm-beanz** [comment]
Putting this into the Roadmap board as this is an enhancement we will want to support Clang development.

**Comment by damyanp** [comment]
Now that we've open-sourced dxil.dll the calculus around this issue has changed. We're tracking work needed for clang separately as well, so this issue isn't needed.
