### ISSUE TITLE
[SPIR-V] Raytracing anyhit shader generating invalid spir-v (expected operands to be scalar or vector int: INotEqual)

### ISSUE THREAD

**Issue by danginsburg** [microsoft/DirectXShaderCompiler#5123]
I am getting the following validation error from spirv-val with the attached raytracing shader:

```
fatal error: generated SPIR-V is invalid: Expected operands to be scalar or vector int: INotEqual
  %118 = OpINotEqual %bool %113 %uint_0
```

I compile the file with the following command line:

```
dxc.exe -spirv -T lib_6_5 -E AnyHit1 -fspv-target-env=vulkan1.3 -Wno-effects-syntax  test.hlsl
```

Interestingly, in the process of stripping this shader down into something I could share, I found a workaround to the bug.  There is an element in this struct that is bool:

```
struct __RTX_MATERIAL_DATA__ 
{
	SamplerStateIndex_t g_sAniso  ;
	Texture2DIndex_t g_tColor  ;
	bool g_bNoEnvMapOcclusion  ;	// <--- REMOVE THIS TO MAKE THE BUG GO AWAY!!!!
	float g_flAlphaTestReference  ;
};
```

If you remove that member variable (or change its type from bool -> int), the spirv-val error goes away.  Interestingly, that member variable is never referenced in the shader.

Shader code attached.

[test.zip](https://github.com/microsoft/DirectXShaderCompiler/files/11115895/test.zip)

**Comment by Keenuts** [comment]
Hi!
Thanks for the report! Minimal repro:

```hlsl
struct DataStruct
{
  uint  unused_field;
  float bad_field;
  bool  last_field;
};

static DataStruct static_data;

ByteAddressBuffer address_buffer : register(t4, space3);

[shader("anyhit")]
void AnyHit0(inout float3 payload)
{ }

[shader("anyhit")]
void AnyHit1(inout float payload)
{
  static_data = address_buffer.Load<DataStruct>(InstanceIndex());
  payload = static_data.bad_field;
}
```

```
dxc -Od -spirv -T lib_6_5 -E AnyHit0 -fspv-target-env=vulkan1.3 -Wno-effects-syntax repro.hlsl
```

**Comment by s-perron** [comment]
I reduced the test case by turning off optimizations. In many case, the optimizer is able to hide the mistake be removing the offending code.

The smallest reproducer I could get is

```
struct DataType
{
  uint u;
  bool b;
};

static DataType data;

ByteAddressBuffer buffer : register ( t4 , space3 )  ;

struct PayloadShadow_t
{
    float m_flVisibility ;
} ;

[ shader ( "anyhit" ) ]
void AnyHit1 ( inout PayloadShadow_t payload , in BuiltInTriangleIntersectionAttributes attrs )
{
  data = buffer.Load<DataType>( 0 );
}
```

The compile command is

```
dxc -spirv -T lib_6_5 -E AnyHit1 -fspv-target-env=vulkan1.3 -Wno-effects-syntax  test.hlsl -fcgl
```

**Comment by s-perron** [comment]
What is odd, is that if I change the type of `DataType.u` to `float` instead of `uint`, DXC generate good code.
