### ISSUE TITLE
[SPIR-V] Trivial use of printf() breaks legalizing optimizations

### ISSUE THREAD

**Issue by nhaehnle** [microsoft/DirectXShaderCompiler#5136]
The shader below rather surprisingly fails to compile with a validation error, when commenting out the call to `printf` allows it to compile successfully:
```hlsl
// dxc -spirv -T cs_6_6 -E main -enable-16bit-types -fspv-target-env=vulkan1.3 bug.hlsl
//
// Error:
// fatal error: generated SPIR-V is invalid: In Logical addressing, variables may not allocate a pointer type
//   %21 = OpVariable %_ptr_Function__ptr_StorageBuffer_type_RWByteAddressBuffer Function

RWByteAddressBuffer output;

void foo(RWByteAddressBuffer buffer) {
    buffer.Store<float>(0, 1.0);
}

[numthreads(8, 8, 1)]
void main() {
    printf("Bug?!");
    foo(output);
}
```

**Comment by Keenuts** [comment]
Hi @nhaehnle,

Thanks for the report. Able to reproduce, will take a look tomorrow if I have some time.

Thanks!

**Comment by s-perron** [comment]
The problem is that some of the optimizations in spirv-opt are not doing what they should. I'm guess that an extension or the extended instruction set are stopping DCE from fulling working.

**Comment by Clothoid1** [comment]
I would assume this issue is related to:
[SPIR-V] StructuredBuffer in function arguments produces invalid SPIR-V when used with printf #4346
