### ISSUE TITLE
[SPIR-V] Crash when field using SV_ClipDistance is inherited

### ISSUE THREAD

**Issue by joeriedel** [microsoft/DirectXShaderCompiler#5138]
DXC Version: `1.7.2212.1`
Minimal Repro:
```
// crash.hlsl
struct PSIn {
 float clipdistance : SV_ClipDistance;
};

struct VSOut : PSIn {};

VSOut vs_main() {
 VSOut z = (VSOut)0;
 return z;
}
```

Command: `dxc.exe -spirv -E vs_main -T vs_6_0  crash.hlsl`
`Internal compiler error: access violation. Attempted to read from address 0x0000000000000004`

Fix: Move field into child structure:

```
// fixed.hlsl
struct PSIn {
};

struct VSOut : PSIn {
 float clipdistance : SV_ClipDistance;
};

VSOut vs_main() {
 VSOut z = (VSOut)0;
 return z;
}
```

**Comment by Keenuts** [comment]
Hi @joeriedel 

Thanks for the report! Was able to reproduce at head, seems like we overlooked the inheritance case for semantics.
Sent a PR to address this.

Thanks!
