### ISSUE TITLE
dxil.dll: Use Hybrid CRT linkage or static CRT in releases

### ISSUE THREAD

**Issue by driver1998** [microsoft/DirectXShaderCompiler#5163]
Currently the dxc releases links to the MSVC runtime dynamically, which requires MSVC Redist packages installed in order to work.

We (MSYS2) have been building and publishing Mesa3D with GLon12 for a while and found out that dxil.dll is required for it to function. 

We plan to package and redistribute dxil.dll ourselves (https://github.com/msys2/MINGW-packages/pull/16643). But the releases here requires MSVC redistributable DLLs and that would be problematic.

The one provided Windows SDK is static linked so it may be used, but that requires us to manually copy the DLLs from somebody's computer with the SDK installed, and manually manage updates. Not an ideal solution either.

So I would want to have releases here to link statically to CRT as well. 

If binary sizes are a concern, you may try [Hybrid CRT linkage](https://github.com/microsoft/WindowsAppSDK/blob/main/docs/Coding-Guidelines/HybridCRT.md) introduced by Windows App SDK, that way only the C++ runtime is linked statically, and UCRT is still linked dynamically, and uses the one built-in to the OS.

**Comment by hekota** [comment]
Fixed in internal build system.
