### ISSUE TITLE
CheckAccessFullyMapped used in a vertex shader does not emit an error

### ISSUE THREAD

**Issue by nadavgevaAMD** [microsoft/DirectXShaderCompiler#5168]
The HLSL intrinsic `CheckAccessFullyMapped` can only be used in Pixel or Compute shaders. (see https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/checkaccessfullymapped). However when used in a different shader stage (for example, a Vertex shader) no error is emitted. On AMD, this results in a crash (internal ticket filed), but DXC should also catch that so it can be caught at byte code compile time instead of runtime. Minimal repro:
https://godbolt.org/z/q9a4a9Mdb

**Comment by damyanp** [comment]
This is by design: this instruction is supported in all shader stages.  See https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#inst_CHECKACCESSMAPPED
