### ISSUE TITLE
Missing __VA_ARGS__ support

### ISSUE THREAD

**Issue by mrsaturnsan** [microsoft/DirectXShaderCompiler#5174]
The HLSL preprocessor does not seem to support `__VA_ARGS__`. Is this a bug?

**Comment by tomjohnstone** [comment]
Seems to work fine for me, for defines passed via the command line:

`dxc -D"NOT_MESHSHADER(...)=__VA_ARGS__" ...`

**Comment by mrsaturnsan** [comment]
https://colinbarrebrisebois.com/2021/11/01/working-around-constructors-in-hlsl-or-lack-thereof/

I'm trying to get this example to compile, but it doesn't work.

**Comment by mrsaturnsan** [comment]
`#define MyClass(...) static MyClass ctor(__VA_ARGS__)
class MyClass
{
    // Default Constructor
    MyClass() 
    { 
        return (MyClass)0; 
    }
 
    // Constructor with a single parameter
    MyClass(const float x) 
    { 
        MyClass a = MyClass();
        a.x = x;
        return a;
    }
 
    // Constructor with multiple parameters
    MyClass(const float x, const bool b, const int i)
    {
        MyClass a;
        a.x = x;
        a.b = b;
        a.i = i;
        return a;
    }
 
    // Member variables
    float x;
    bool  b;
    int   i; 
};
#undef MyClass
#define MyClass(...) MyClass::ctor(__VA_ARGS__)

#define MyClass(...) static MyClass ctor(__VA_ARGS__)
class MyClass
{
    // Default Constructor
    MyClass() 
    { 
        return (MyClass)0; 
    }
 
    // Constructor with a single parameter
    MyClass(const float x) 
    { 
        MyClass a = MyClass();
        a.x = x;
        return a;
    }
 
    // Constructor with multiple parameters
    MyClass(const float x, const bool b, const int i)
    {
        MyClass a;
        a.x = x;
        a.b = b;
        a.i = i;
        return a;
    }
 
    // Member variables
    float x;
    bool  b;
    int   i; 
};
#undef MyClass
#define MyClass(...) MyClass::ctor(__VA_ARGS__)`

**Comment by tomjohnstone** [comment]
There's a typo in the "Constructor with a single parameter". Change it to:

```
    MyClass(const float x) 
    { 
        MyClass a = ctor();
        a.x = x;
        return a;
    }
```

**Comment by mrsaturnsan** [comment]
Ah, thanks! Yes, that fixed the error.
