### ISSUE TITLE
Dynamically linked CRT breaks deployment

### ISSUE THREAD

**Issue by sherief** [microsoft/DirectXShaderCompiler#5178]
It's generally expected to be able to ship non-C++ applications on Windows, and the dxcompiler.dll bundled in the Windows SDK kit doesn't rely on third-party components or C++ runtime DLLs: 
![image](https://user-images.githubusercontent.com/1711646/234519177-ffd95452-a5cd-49f0-b73b-d4181d71e825.png)

At a certain point, this contract has been broken, and if you want to ship an app using a newer dxcompiler.dll or dxil.dll from this repository's releases you are required to also redistribute VC++ runtime libraries: 
![image](https://user-images.githubusercontent.com/1711646/234519757-a5027269-79b8-40a4-9cbc-bf0172cecdff.png)

This poses a few issues and has broken some deployment scenarios:
- Non-C++ apps are now required to distribute VC++ runtime DLLs. The COM interfaces exported by the dxcompiler and dxil DLLs are perfectly accessible from other languages, and apps using these languages run against the Windows SDK versions of these DLLs just fine.
- Standalone apps are now impossible. I discovered this issue while updating an application used to visualize data where the end-user writes simple visualization code that gets compiled to shaders and applied to images at runtime. The app is shipped as a single executable, and loads the dxil and dxcompiler DLLs from embedded resources. Suddenly it started failing on some machines, and it turned out that these machines never had the redist installed. In some deployment environments, it's not easy to just ship and install these due to legal or ops limitations. 
- On deployments where the VC++ redist was installed by some other app, we cannot guarantee which version of the DLL we'll end with. In certain deployment scenario, we require certain integrity checking of the runtime environment and all loaded DLLs, and we even manage loading everything involved with D3D Agility SDK and DX shader compiler manually from known versions that carry their own out-of-band signature for whitelisting. 

I'm not sure what the wins are from moving to a dynamically linked CRT, but I can see some issues and contract breaks. The top support issue by a ratio of 4:1 has now become related to the new DLL requirements. Can we have the artifacts from the latest shader compiler here match the Windows SDK versions when it comes to external requirements?

**Comment by sherief** [comment]
Looks like #5163 is also running into this.

**Comment by hekota** [comment]
Fixed in internal build system. Next DXC release will ship with hybrid CRT linking.
