### ISSUE TITLE
Minor inaccuracy on the "Using dxc.exe and dxcompiler.dll" wiki page.

### ISSUE THREAD

**Issue by LaG1924** [microsoft/DirectXShaderCompiler#5182]
The example from "DXCompiler DLL interface" fails to compile due to "error C2065: 'pPdb': undeclared identifier".

I believe you should change the line

> if (SUCCEEDED(pUtils->GetPDBContents(**pPdb**, &pHashDigestBlob, &pDebugDxilContainer)))

to

> if (SUCCEEDED(pUtils->GetPDBContents(**pPDB**, &pHashDigestBlob, &pDebugDxilContainer)))

**Comment by bob80905** [comment]
Thanks for the pointer, fixed.
