### ISSUE TITLE
GV not mutated to handle for lib_6_6+

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#5202]
A global variable is supposed to be mutated into handle type.

But it doesn't in
[tools/clang/test/HLSLFileCheck/hlsl/linker/resources/preserve_sb_types.hlsl](https://github.com/microsoft/DirectXShaderCompiler/blob/main/tools/clang/test/HLSLFileCheck/hlsl/linker/resources/preserve_sb_types.hlsl)
[tools/clang/test/HLSLFileCheck/hlsl/linker/resources/preserve_cb_types.hlsl](https://github.com/microsoft/DirectXShaderCompiler/blob/main/tools/clang/test/HLSLFileCheck/hlsl/linker/resources/preserve_cb_types.hlsl)

**Comment by damyanp** [comment]
No plans to address this in DXC, label added so we can find it again when thinking about similar things in clang.
