### ISSUE TITLE
[DXIL] Build succussed but no dxil.dll file found 

### ISSUE THREAD

**Issue by jph7669** [microsoft/DirectXShaderCompiler#5206]
Hi,
I'm trying to build dxil with the latest codebase, and the build was success. However, dxil.dll is not generated while other .dll files such as dxcompiler.dll can be found. Is dxil.dll open for local build now? Thanks.

**Comment by sykuang** [comment]
Got the same issue here. I am not able to find dxil.dll after building successfully.

**Comment by igaspard** [comment]
I have encountered a similar problem. The dxil.dll file is missing from the output directory even though the build process completed without errors.

I would appreciate some guidance on how to fix this issue.

**Comment by llvm-beanz** [comment]
`dxil.dll` is not produced from the open source code base, it is only part of the official releases.

It contains some proprietary code that is involved in the dxil signing process (apologies, I hate every part of this sentence).

If you need `dxil.dll` to sign shaders you need to pull the binary out of the release package and bundle it with your local built compiler.
