### ISSUE TITLE
Compilation error on templated struct when struct A decides a type T for struct Z used in struct B

### ISSUE THREAD

**Issue by kpentaris** [microsoft/DirectXShaderCompiler#5207]
The description is a little convoluted so here is a minimal code sample:

```
template<typename T>
struct Operation {};

template<typename T, class Op>
struct Secondary {

};

/**
 * Primary does some stuff that requires use of Secondary.
 * However, Primary is the one that decides what Operation 
 * Secondary will use.
 * A decides C for B to use.
 */
template<typename T>
struct Primary {
    void operator()() {
        Secondary<T, Operation<T> > a;
    }
};

[numthreads(32,1,1)]
void main() {
    Primary<uint> a;
}
```
There might be workarounds using struct inheritance but it is not equivalent behavior.
Tested on C++ with gcc, clang and msvc and they support it.

Test Link [here](https://godbolt.org/z/3Gs8c6144)

Thanks!

**Comment by pow2clk** [comment]
No longer repros with main trunk: https://godbolt.org/z/o34r8zror

I spent a few minutes trying to identify the fix, but there have been a lot of template fixes since then
