### ISSUE TITLE
default template arguments for a function template are a C++11 extension

### ISSUE THREAD

**Issue by BartSiwek** [microsoft/DirectXShaderCompiler#5221]
When trying to compile HLSL like this:
```
template<typename TextureType, typename MixerType = TrivialMixer>
vec4	textureMaterial( TextureType tex, UVProjector p, MixerType m = MixerType() )
{
    return textureWithSampler( tex, sMaterialSampler, p.uv.xy );
}
```
With arguments:
```
-T vs_6_5 -H 2021 -O shader_0.hls
```

I get the following warning:
```
warning: default template arguments for a function template are a C++11 extension [-Wc++11-extensions]
```

It seems I can silence it with either `-no-warnings` or `-Wno-c++11-extensions`.

Additionally it seems specifying the C++ version with `-std=c++11` does work:
```
Unknown argument: '-std=c++11'
```

It feels like this should either:
- be not be allowed
- possible to disable a warning for this specific extension not all of them
- possible to be able to specify c++ version

In addition - is HLSL 2021 compliant with any actual version of C++? If not this is a strange warning to get altogether,

**Comment by Keenuts** [comment]
DXC being based on clang, it might just be this part not being handled, and C++ flags leaking.
Now, are template default parameters allowed? seems like no as it's not said here (https://github.com/microsoft/DirectXShaderCompiler/wiki/HLSL-2021). But @llvm-beanz .

So it's probably just a matter or cleaning some flags, and fixing diag errors.
Now, the behavior does seem to be correct, at least comparing C++ result and SPIRV result with the following code:

```cpp
#ifdef __cplusplus
// compilation: clang++ -shared main.cc -O0 -Wextra -Wall -Werror
#include <stdint.h>
using uint = uint32_t;

extern int input[];
extern uint output[];
#else
// compilation: dxc -spirv -T cs_6_6 -Od -E compute -HV 2021 main.cc
RWStructuredBuffer<int> input;
RWStructuredBuffer<uint> output;
#endif

template<typename A, typename B, typename C = float>
A sum(B lhs, B rhs) {
    C tmp = (C) (lhs + rhs);
    return (A) tmp;
}

#ifdef __cplusplus
void compute()
#else
[numthreads(1, 1, 1)]
void compute(uint tidx : SV_DispatchThreadId)
#endif
{
    output[0] = sum<uint, int, uint>(0, 1);
}
```
