### ISSUE TITLE
Assert on `static const`  in `template` functions

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/DirectXShaderCompiler#5273]
Compiling some HLSL code with `static const` in templates seems to be fine in the release builds, but when asserts are turned on in a debug build the following appears:

```
DirectXShaderCompiler/tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:4104: clang::QualType clang::spirv::DeclResultIdMapper::getTypeAndCreateCounterForPotentialAliasVar(const clang::DeclaratorDecl *, bool *): Assertion `!varDecl->isExternallyVisible() || varDecl->isStaticDataMember()' failed.
```

Repro with:

```hlsl
template <typename R> R test(R x) {
    static const R v = 20;
    return v * x;
}

[numthreads(32, 32, 1)] void main(uint2 threadId: SV_DispatchThreadID) {
    float x = test(10);
}
```

Should this be turned into an `emitError()` to disallow the case globally, with a fitting error message? I haven't checked if the code generates and runs as expected, but it seems so.

**Comment by s-perron** [comment]
This test case should pass. The code that is generated when the assert is disabled is correct. We just need to fix the assert. It seems too restrictive.
