### ISSUE TITLE
[Spir-v?] GetAttributeAtVertex intrinsic function unimplemented

### ISSUE THREAD

**Issue by coffeenotfound** [microsoft/DirectXShaderCompiler#5308]
When compiling HLSL to spirv, using the GetAttributeAtVertex intrinsic results in `error: GetAttributeAtVertex intrinsic function unimplemented`

I'm not sure if it is only unimplemented for SPV or if the DXIL backend also has this problem

Would be great if this could get implemented!

**Comment by coffeenotfound** [comment]
Oops, seems like this is alreay being tracked by #3930 and #5270

**Comment by s-perron** [comment]
https://github.com/microsoft/DirectXShaderCompiler/pull/4638 was merged 3 weeks ago. It should be implemented now.

As you noticed, there is a bug in it that is getting fixed (https://github.com/microsoft/DirectXShaderCompiler/issues/5270). I will consider this closed.
