### ISSUE TITLE
[SM 6.8] Review intrinsic op availability for node shaders

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5345]
hctdb.py checks which ops can be in which stages. We need to make sure nothing that shouldn't be in node shaders can be and those that can't are disallowed.

**Comment by pow2clk** [comment]
Investigation revealed missing wave matrix ops in node shaders that is to be fixed as #6400. As this task was to perform the investigation, it is complete.
