### ISSUE TITLE
Provide early, friendly error reporting for invalid record use after OutputComplete

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5347]
Evaluate the ability to provide earlier (AST-level) diagnostics for invalid record use after OutputComplete. This could be modeled after clang diagnostics for use after `std::move`.

**Comment by pow2clk** [comment]
Error already exists in validation. It would be nice to have it earlier, but there might be more important tasks for 6.8

**Comment by damyanp** [comment]
Plan is to address this in clang.
