### ISSUE TITLE
DXIL Validation for input record type compatibility with launch mode

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5348]
DXIL validation needs to produce errors for invalid combinations of input records and launch modes.

* Thread launch mode entries must use ThreadNodeInputRecord inputs.
* Broadcasting launch mode entries must use DispatchNodeInputRecord inputs.
* Coalescing launch mode entries must use GroupNodeInputRecord inputs.

This should be verified both at the source (AST) level and in the resulting DXIL through the validator.

**Comment by llvm-beanz** [comment]
cc @tcorringham

**Comment by bob80905** [comment]
Closed with #5589
