### ISSUE TITLE
ExecutionTest::OutOfBoundsTest fails because of a bug in the test.

### ISSUE THREAD

**Issue by markherdeg** [Microsoft/DirectXShaderCompiler#535]
This test is failing on my AMD GPU because g_t1d is created as a Texture1D<float> but the HLSL declares it as a Buffer<float> (in tools/clang/test/HLSL/ShaderOpArith.xml). Using the correct matching declaration (it is already there but commented out?), the test passes.

**Comment by youngkim93** [comment]
Hi Mark, Thanks for the report. The fix is at #552. Let me know if you still find an issue with this test. Thanks!

**Comment by markherdeg** [comment]
Good. Thank you.
