### ISSUE TITLE
SPIR-V issue with GetAttributeAtVertex

### ISSUE THREAD

**Issue by Schrottiy** [microsoft/DirectXShaderCompiler#5354]
according to https://github.com/microsoft/DirectXShaderCompiler/issues/3930 this shouldn't be a issue but appears to be still present

when compiling a pixelshader with ```-spirv``` that uses the intrinsic function ```GetAttributeAtVertex```, it will fail with error 
```GetAttributeAtVertex intrinsic function unimplemented```

Using the latest build: from 29.6.2023
https://github.com/microsoft/DirectXShaderCompiler#downloads

Visual Studio project that demonstates the issue:
[Issue.zip](https://github.com/microsoft/DirectXShaderCompiler/files/11900147/Issue.zip)

**Comment by llvm-beanz** [comment]
@Schrottiy, can you confirm which specific version of DXC you're using. The latest release is from December 2022 which does not include the fix for this issue as the fix was only merged 4 weeks ago.

I believe the fix was included in the 1.8 preview build that was posted in June. If you're experiencing this issue on the preview we will need to investigate.

cc @s-perron

**Comment by Schrottiy** [comment]
Downloaded precompiled preview 1.8 from:
https://github.com/microsoft/DirectXShaderCompiler/releases

replaced dxcapi.h and dxcompiler.lib with the new ones in my Issue project, rebuilt it and then ran it, issue persits!

**Comment by s-perron** [comment]
I just tried the example in the sample using the command line, and it worked for me:

```
Downloads/dxc/bin » ./dxc --version
libdxcompiler.so: 1.8(dev;3944-3e105849)
```

```
Downloads/dxc/bin » cat t.hlsl
float4 main(nointerpolation float test : Test) : SV_TARGET
{
    float result = GetAttributeAtVertex(test, 1);
    return result.xxxx;
}
```

```
Downloads/dxc/bin » ./dxc -T ps_6_6 -E main -spirv -fspv-target-env=vulkan1.1 -HV 2021 t.hlsl
; SPIR-V
; Version: 1.3
; Generator: Google spiregg; 0
; Bound: 19
; Schema: 0
               OpCapability Shader
               OpCapability FragmentBarycentricKHR
               OpExtension "SPV_KHR_fragment_shader_barycentric"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %in_var_Test %out_var_SV_TARGET
               OpExecutionMode %main OriginUpperLeft
               OpSource HLSL 660
               OpName %in_var_Test "in.var.Test"
               OpName %out_var_SV_TARGET "out.var.SV_TARGET"
               OpName %main "main"
               OpDecorate %in_var_Test Flat
               OpDecorate %in_var_Test PerVertexKHR
               OpDecorate %in_var_Test Location 0
               OpDecorate %out_var_SV_TARGET Location 0
       %uint = OpTypeInt 32 0
     %uint_3 = OpConstant %uint 3
      %float = OpTypeFloat 32
%_arr_float_uint_3 = OpTypeArray %float %uint_3
%_ptr_Input__arr_float_uint_3 = OpTypePointer Input %_arr_float_uint_3
    %v4float = OpTypeVector %float 4
%_ptr_Output_v4float = OpTypePointer Output %v4float
       %void = OpTypeVoid
         %12 = OpTypeFunction %void
%in_var_Test = OpVariable %_ptr_Input__arr_float_uint_3 Input
%out_var_SV_TARGET = OpVariable %_ptr_Output_v4float Output
%_ptr_Input_float = OpTypePointer Input %float
     %uint_0 = OpConstant %uint 0
       %main = OpFunction %void None %12
         %15 = OpLabel
         %16 = OpAccessChain %_ptr_Input_float %in_var_Test %uint_0
         %17 = OpLoad %float %16
         %18 = OpCompositeConstruct %v4float %17 %17 %17 %17
               OpStore %out_var_SV_TARGET %18
               OpReturn
               OpFunctionEnd
```

This was on linux. I will try the Windows build later.

**Comment by s-perron** [comment]
@Schrottiy Could you double check that you are in fact picking up the correct version of the library? I do not use Windows much, so I cannot offer an suggestions on how to do that.

**Comment by s-perron** [comment]
@Schrottiy Could you try printing the version string using https://learn.microsoft.com/en-us/windows/win32/api/dxcapi/ns-dxcapi-idxcversioninfo3 (or something like it). That should let you know if you are using the correct version.

**Comment by Schrottiy** [comment]
i can confirm that using the dxc.exe from the preview 1.8 in command line actually works, but when using c++ dxc.lib and dxcapi.h,
right now i am trying to retrieve the version via cpp but i have some trouble obtaining an instance of IDxcVersionInfo

**Comment by llvm-beanz** [comment]
Godbolt link to confirm fix in trunk:
https://godbolt.org/z/Gh86zYxKa

**Comment by Schrottiy** [comment]
@s-perron, compiling using cmd with dxc.exe works for 1.8 preview and 1.7.0.3956, but for both versions using corresponding dxcapi.h and dxcompiler.lib in order to compile using cpp, it seems to not work, unfortunetally i cannot retrieve the version in cpp because IDxcPdbUtils::GetVersionInfo returns E_FAIL. ( dxc --version in cmd works and returns according version)
```c++
DxcCreateInstance(CLSID_DxcPdbUtils, IID_PPV_ARGS(&UtilsInstance));
UtilsInstance->GetVersionInfo(&version);
```

**Comment by Schrottiy** [comment]
i just noticed that dxcompiler.lib is only 2kb, and dxc.exe about 2mb ... i guess that 2kb is not big enough for a compiler, so it reqruies some dependencies, and maby it uses the WindowsSDK ones, which probably are deprecated...

**Comment by llvm-beanz** [comment]
> i just noticed that dxcompiler.lib is only 2kb, and dxc.exe about 2mb ... i guess that 2kb is not big enough for a compiler, so it reqruies some dependencies, and maby it uses the WindowsSDK ones, which probably are deprecated...

Yea, you need `dxcompiler.dll` as well, the core of the compiler is shipped as a dll, not a static library or in the executable.

**Comment by Schrottiy** [comment]
> > i just noticed that dxcompiler.lib is only 2kb, and dxc.exe about 2mb ... i guess that 2kb is not big enough for a compiler, so it reqruies some dependencies, and maby it uses the WindowsSDK ones, which probably are deprecated...
> 
> Yea, you need `dxcompiler.dll` as well, the core of the compiler is shipped as a dll, not a static library or in the executable.

That was the issue thanks!

**Comment by s-perron** [comment]
@Schrottiy FYI: https://github.com/microsoft/DirectXShaderCompiler/pull/5384.
