### ISSUE TITLE
Work Graphs: Validate null or undef handle usage

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5356]
The verify_output_complete.hlsl has a TBD regarding preventing the null handle usage that this test case introduces.  This test can be evolved/adapted as pieces are implemented.

There are several things we can do in priority order:
1. Update validation to prevent null (or undef) handle usage in any intrinsic other than OutputComplete, where it's defined to be a no-op.
2. Fail earlier in the compilation pipeline when null (or undef) handle usage is detected.
3. If possible detect these early through AST analysis for the best diagnostic quality.

**Comment by bob80905** [comment]
Fixed by #5399
