### ISSUE TITLE
Work Graphs: [Empty]NodeOutputArray subscript operator should not return reference type

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5358]
The subscript operator for NodeOutputArray and EmptyNodeOutputArray return a reference type to the NodeOutput or EmptyNodeOutput object.  This should not be a reference, but a value instead.  This interacts with #5357, because it prevents the type annotation from being created for the NodeOutput or EmptyNodeOutput type.

**Comment by llvm-beanz** [comment]
It looks like [Empty]NodeOutputArray's AST is correct and does not return references from the subscript operator. We don't have tests for [Empty]NodeOutputArray's AST, so we should add those, but otherwise there is nothing to do here.

**Comment by pow2clk** [comment]
It seems this got fixed along the way without referencing this bug. I've created #6199 for the tests Chris requested. As such, there's nothing left here. Closing.
