### ISSUE TITLE
Diagnostics for native NodeOutput or EmptyNodeOutput array declaration

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5359]
The Work Graphs spec added NodeOutputArray and EmptyNodeOutputArray in place of native NodeOutput and EmptyNodeOutput array declarations.
However, it is still possible to declare native NodeOutput or EmptyNodeOutput arrays, which can lead to one of several compiler asserts.
In order to avoid the inadvertent use of native arrays (and improve the user experience) error diagnostics should be generated for their use.

**Comment by llvm-beanz** [comment]
cc @tcorringham

**Comment by pow2clk** [comment]
Fixed by #5588
