### ISSUE TITLE
Use 'ref' for in/out groupshared params of WaveMatrix Load/Store methods

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5360]
Need to determine how to handle 'in ref' and 'out ref' such that 'in ref' maps to a const reference, and 'out ref' somehow indicates that nothing is read from the argument.

Need to check potential interactions with 'ref' and revise the `ParamModsFromIntrinsicArg` function in SemaHLSL.cpp.

**Comment by llvm-beanz** [comment]
Since WaveMatrix is moving out to SM 6.8, we have more time to address this.

**Comment by damyanp** [comment]
As we've removed the current form of wavematrix from the codebase closing this issue.
