### ISSUE TITLE
Break out -select-validator changes for main

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5362]
The DXC 1.8 preview branch contains changes to add a new `-select-validator` flag. Those changes are not dependent on the SM 6.8 changes and should be introduced to `main` separately.

**Comment by pow2clk** [comment]
See ecc3d35c5d28c7d9cee107efc767481bc88a5062

**Comment by llvm-beanz** [comment]
The merge is done, this issue isn't meaningful anymore.
