### ISSUE TITLE
Review issues with redundant OutputComplete elimination change

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5363]
Redundant OutputComplete elilmination doesn't look like it's quite in the right place.

Moving the DxilMod init code was unnecessary, hlsl::OP can be retrieved from the m_pHLModule instead, as the others do.

See https://github.com/microsoft/DirectXShaderCompiler/blob/040e4078b3525bccef0b53464b17e0b49d518c1b/lib/HLSL/DxilGenerationPass.cpp#L281

I don't think this code should have been moved up here, above the comment that related to this step: // High-level metadata should now be turned into low-level metadata.
I think the code that gets rid of OutputComplete calls with zeroinit handle should probably be moved to some other (DCE-like) pass, later (since further optimization may produce this as well).

**Comment by pow2clk** [comment]
Fixed by #5620
