### ISSUE TITLE
Improvements needed in work graphs object handling and lowering

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5365]
There's opportunity to improve the way we are generating code for work graph objects and lowering them to IR in CGHLSLMS.cpp.

https://github.com/microsoft/DirectXShaderCompiler/blob/040e4078b3525bccef0b53464b17e0b49d518c1b/tools/clang/lib/CodeGen/CGHLSLMSHelper.h#L169
Might we need to add to DxilObjectProperties to capture node object within structures?

https://github.com/microsoft/DirectXShaderCompiler/blob/040e4078b3525bccef0b53464b17e0b49d518c1b/tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp#L2939
There has to be a better way. This doesn't handle ordinary inlined functions either.

https://github.com/microsoft/DirectXShaderCompiler/blob/040e4078b3525bccef0b53464b17e0b49d518c1b/tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp#L2911
There has to be a better way. This doesn't handle ordinary inlined functions either.

https://github.com/microsoft/DirectXShaderCompiler/blob/040e4078b3525bccef0b53464b17e0b49d518c1b/tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp#L770
All this handle translation and casting at this point is ugly and fragile. It doesn't belong in this function, and I'm not entirely sure it's necessary at this stage. I think a different approach might be better.

https://github.com/microsoft/DirectXShaderCompiler/blob/040e4078b3525bccef0b53464b17e0b49d518c1b/tools/clang/lib/CodeGen/CGHLSLMS.cpp#L97
I think we might need to incorporate this info into DxilObjectProperties instead to handle more cases.

For more details see internal work item 126.

**Comment by pow2clk** [comment]
@tex3d could you add some detail to these comments?

**Comment by pow2clk** [comment]
Tex will create an issue to create some additional testing to verify that these implementations are currently correct. We'll revisit this after 6.8 release otherwise.

**Comment by llvm-beanz** [comment]
Closing since this doesn't have a specific reproducible issue.
