### ISSUE TITLE
Node launch types should be case-sensitive and lowercase

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5370]
As per the spec, NodeLanuch string arguments should be interpreted as case-sensitive and lowercase matching other string arguments to attributes:

https://github.com/microsoft/hlsl-specs/pull/62/files#diff-f13bec8f0222a19e56d6433159f69368dd5b5fb9f7b1e0ef0a87058ced354bf9R85

**Comment by pow2clk** [comment]
Fixed by #5622
