### ISSUE TITLE
WaveMatrix test could use some minor code cleanups

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5371]
The WaveMatrix tests have a "PlaceholderScalarMultiplyAccumulator", which is probably not appropriate naming because it is used to calculate the expected result.

 There is also an unused debugging function `PrintMat` left in place that should at least be compiled out in release builds.

**Comment by pow2clk** [comment]
Placeholder is what we usually use to describe functions that implement the behavior without the driver support allowing us to develop the tests without them. I do see in a few cases that these functions are used to calculate expected results though and that does make it confusing.

**Comment by pow2clk** [comment]
Maybe keep printmat for debugging purposes, but hide it within an `#ifdef`

**Comment by pow2clk** [comment]
Fixed by #5724
