### ISSUE TITLE
Cleanup HLSLCheckForModifiableLValue

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5372]
The SM 6.8 preview branch has changes to `HLSLCheckForModifiableLValue`. I'm unsure if we actually need any of these changes or if they are vestiges from earlier iterations of the change. Regardless we should clean this up or remove the change.

**Comment by tcorringham** [comment]
You are correct in suspecting some of these changes are from earlier iterations - I know at least some are no longer required, so I'll take a more detailed look and minimise the changes.

**Comment by pow2clk** [comment]
Not sure why #5458 didn't close this, but it should have
