### ISSUE TITLE
Remove implicit record types generated by compiler

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5375]
Implicit input record types generated by the compiler are problematic, and a weird special case.  We can't differentiate an explicit record vs. implicit one at the DXIL level, which complicates DXIL validation.

It seems like the runtime and driver should be able to handle this case fine without a compiler generated implicit input record.  I think we should revisit this.

**Comment by pow2clk** [comment]
Part of the effort to disallow entries that are both node and compute

**Comment by tex3d** [comment]
This is the related issue for disallowing both node and compute: #5601

**Comment by pow2clk** [comment]
Fixed by #5722
