### ISSUE TITLE
Simple float4x4 passthrough function fails to compile with optimizations disabled

### ISSUE THREAD

**Issue by ppenenko** [microsoft/DirectXShaderCompiler#5409]
**Description**

I was investigating some validation issues in our shaders and compiled them with `-Zi -O0` in an attempt to track down the offending lines of code. However, `-O0` triggers additional validation issues on trivial code like this snippet. `-O1` makes the issue go away.

https://godbolt.org/z/8czEq7711

**Steps to Reproduce**

```HLSL
export float4x4 mat_passthru(float4x4 mat)
{
    return mat;
}
```

compiled with `-T lib_6_7 -O0`

**Actual Behavior**
`error: Instruction does not dominate all uses!`

**Environment**
- DXC version: 1.7.2207
- Host Operating System: Win 10

**Comment by damyanp** [comment]
This no longer repros in recent DXC.
