### ISSUE TITLE
WaveActiveAllEqual and vector parameters

### ISSUE THREAD

**Issue by s-perron** [microsoft/DirectXShaderCompiler#5410]
**Description**

The behaviour of `WaveActiveAllEqual` does not seem to match the documentation when the parameter is a vector.

The [documentation](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/waveactiveallequal) says that `WaveActiveAllEqual` always returns a bool.  However, DXC will treats the function as returning a vector.

**Steps to Reproduce**

```
// RUN: dxc -T cs_6_0 -HV 2018 -E main -fspv-target-env=vulkan1.1 t.hlsl -ast-dump

struct S {
    float4 val1;
    uint val2;
    bool res;
};

RWStructuredBuffer<S> values;

[numthreads(32, 1, 1)]
void main(uint3 id: SV_DispatchThreadID) {
    values[id.x].res = WaveActiveAllEqual(values[id.x].val1);
}
```

**Actual Behavior**

When run the compiler emits the following warning:

```
t.hlsl:13:22: warning: implicit truncation of vector type [-Wconversion]
    values[id.x].res = WaveActiveAllEqual(values[id.x].val1);
```

The ast that is dumped shows:

```
  |       `-CallExpr 0x55e01375b760 <col:24, col:60> 'vector<bool, 4>':'vector<bool, 4>'
  |         |-ImplicitCastExpr 0x55e01375b748 <col:24> 'vector<bool, 4> (*)(vector<float, 4>)' <FunctionToPointerDecay>
  |         | `-DeclRefExpr 0x55e01375b6b0 <col:24> 'vector<bool, 4> (vector<float, 4>)' lvalue Function 0x55e01375b510 'WaveActiveAllEqual' 'vector<bool, 4> (vector<float, 4>)'
  |         `-ImplicitCastExpr 0x55e01375b7a8 <col:43, col:56> 'float4':'vector<float, 4>' <LValueToRValue>
```

**Environment**
- DXC version  Using Top of tree
- Host Operating System  Linux, but but should be reproducible everywhere.

**Comment by python3kgae** [comment]
Hi Steven,
This might be a bug in the doc.
In github wiki WaveActiveAllEqual is like this
https://github.com/microsoft/DirectXShaderCompiler/wiki/Wave-Intrinsics#booln-waveactiveallequaltype-expr-

values[id.x].res = all(WaveActiveAllEqual(values[id.x].val1)); should get the result in https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/waveactiveallequal

**Comment by llvm-beanz** [comment]
@tex3d thoughts here?

**Comment by tex3d** [comment]
The behavior is by-design.  The documentation is not good, in that it doesn't address vector/matrix overload behavior for these scalar operations.  Typically, scalar operations have vector and matrix overloads which produce results with the same dimensionality, performing the same scalar operation on each component of the input(s).  This is the case for basic math operations as well as the Wave intrinsics.  We need to address this in the documentation.

**Comment by tex3d** [comment]
I submitted a doc PR to fix this case here:
https://github.com/MicrosoftDocs/win32/pull/1640

**Comment by tex3d** [comment]
The patch was accepted, so this update should appear in the docs at some point when they get updated/published.
