### ISSUE TITLE
Error MSB8066 when trying to build compiler

### ISSUE THREAD

**Issue by KyleBernelle** [microsoft/DirectXShaderCompiler#5420]
Attempting to build the compiler so that I can make use of the D3DCompiler DXC Bridge, but when I attempt to run `hctbuild`, every project exits with code 1. I've downloaded what should be all the necessary components (WDK, .NET 4.8, Python, CMake, etc). Any suggestions on what I'm doing incorrectly?

```
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5
): error MSB8066: Custom build for 'C:\Users\<MyUsername>\Documents\hlsl.bin\CMakeFiles\bf7533ac810f16440a7e2b1b18629be9\Dxi
lConstants.rule' exited with code 1. [C:\Users\<MyUsername>\Documents\hlsl.bin\include\dxc\DXIL\DxilConstants.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5
): error MSB8066: Custom build for 'C:\Users\<MyUsername>\Documents\hlsl.bin\CMakeFiles\73ad01c3c6834ff07b57d4642e5699b3\Dxi
lDocs.rule' exited with code 1. [C:\Users\<MyUsername>\Documents\hlsl.bin\DxilDocs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5
): error MSB8066: Custom build for 'C:\Users\<MyUsername>\Documents\hlsl.bin\CMakeFiles\bf7533ac810f16440a7e2b1b18629be9\Dxi
lCounters.rule' exited with code 1. [C:\Users\<MyUsername>\Documents\hlsl.bin\include\dxc\DXIL\DxilCounters.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5
): error MSB8066: Custom build for 'C:\Users\<MyUsername>\Documents\hlsl.bin\CMakeFiles\b3acfa2a5d6281950f3ed4cfc3d68787\Dxi
lMetadata.rule' exited with code 1. [C:\Users\<MyUsername>\Documents\hlsl.bin\lib\DXIL\DxilMetadata.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5
): error MSB8066: Custom build for 'C:\Users\<MyUsername>\Documents\hlsl.bin\CMakeFiles\b3acfa2a5d6281950f3ed4cfc3d68787\Dxi
lOperations.rule' exited with code 1. [C:\Users\<MyUsername>\Documents\hlsl.bin\lib\DXIL\DxilOperations.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5
): error MSB8066: Custom build for 'C:\Users\<MyUsername>\Documents\hlsl.bin\CMakeFiles\bf7533ac810f16440a7e2b1b18629be9\Dxi
lSigPoint.rule' exited with code 1. [C:\Users\<MyUsername>\Documents\hlsl.bin\include\dxc\DXIL\DxilSigPoint.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5
): error MSB8066: Custom build for 'C:\Users\<MyUsername>\Documents\hlsl.bin\CMakeFiles\bf7533ac810f16440a7e2b1b18629be9\Dxi
lShaderModelInc.rule' exited with code 1. [C:\Users\<MyUsername>\Documents\hlsl.bin\include\dxc\DXIL\DxilShaderModelInc.vcxp
roj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5
): error MSB8066: Custom build for 'C:\Users\<MyUsername>\Documents\hlsl.bin\CMakeFiles\bf7533ac810f16440a7e2b1b18629be9\Dxi
lInstructions.rule' exited with code 1. [C:\Users\<MyUsername>\Documents\hlsl.bin\include\dxc\DXIL\DxilInstructions.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5
): error MSB8066: Custom build for 'C:\Users\<MyUsername>\Documents\hlsl.bin\CMakeFiles\b3acfa2a5d6281950f3ed4cfc3d68787\Dxi
lShaderModel.rule' exited with code 1. [C:\Users\<MyUsername>\Documents\hlsl.bin\lib\DXIL\DxilShaderModel.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5
): error MSB8066: Custom build for 'C:\Users\<MyUsername>\Documents\hlsl.bin\CMakeFiles\70739283dcb4587d48ea9b75d508ed49\HLS
LIntrinsicOp.rule' exited with code 1. [C:\Users\<MyUsername>\Documents\hlsl.bin\include\dxc\HLSLIntrinsicOp.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5
): error MSB8066: Custom build for 'C:\Users\<MyUsername>\Documents\hlsl.bin\CMakeFiles\64b29c52facd54742ba3fe38e4f73a39\RDA
T_LibraryTypes.rule' exited with code 1. [C:\Users\<MyUsername>\Documents\hlsl.bin\include\dxc\DxilContainer\RDAT_LibraryTyp
es.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5
): error MSB8066: Custom build for 'C:\Users\<MyUsername>\Documents\hlsl.bin\CMakeFiles\765a88c8eac3640c0713c12d0d457669\HLS
LOptions.rule' exited with code 1. [C:\Users\<MyUsername>\Documents\hlsl.bin\include\dxc\Support\HLSLOptions.vcxproj]

  LLVMTableGen.vcxproj -> C:\Users\<MyUsername>\Documents\hlsl.bin\Debug\lib\LLVMTableGen.lib
  LLVMMSSupport.vcxproj -> C:\Users\<MyUsername>\Documents\hlsl.bin\Debug\lib\LLVMMSSupport.lib
  Touch GetCommitInfo.py to trigger rebuild  (<- I'VE DONE THIS)
  dndxc -> C:\Users\<MyUsername>\Documents\hlsl.bin\Debug\bin\dndxc.exe
  LLVMSupport.vcxproj -> C:\Users\<MyUsername>\Documents\hlsl.bin\Debug\lib\LLVMSupport.lib
  llvm-tblgen.vcxproj -> C:\Users\<MyUsername>\Documents\hlsl.bin\Debug\bin\llvm-tblgen.exe
Failed to build projects.
After fixing, run 'cmake --build --config Debug .' in x64
```

**Comment by KyleBernelle** [comment]
> Hello, I also encountered this problem these two days. Later, I used the code pulled by git instead of the directly downloaded package to solve the problem, and I used the hctbuild -vs2019 directive. I don't know if it helped you.

It did try to run this time, without errors, however it still complains that my version of CMake is too new. I'm running it again to resolve the other things it's complaining about (didn't have VS2019), so not sure that this actually a hindrance, but I keep saying that I need CMake 3.4 when that's what I currently have installed.

**Comment by keyi4541** [comment]
> > Hello, I also encountered this problem these two days. Later, I used the code pulled by git instead of the directly downloaded package to solve the problem, and I used the hctbuild -vs2019 directive. I don't know if it helped you.
> 
> It did try to run this time, without errors, however it still complains that my version of CMake is too new. I'm running it again to resolve the other things it's complaining about (didn't have VS2019), so not sure that this actually a hindrance, but I keep saying that I need CMake 3.4 when that's what I currently have installed.

The version of cmake should not have much impact, my cmake version is 3.24, there will still be warnings, but it will not affect the success of hctbuild.

**Comment by KyleBernelle** [comment]
> 

Are you using the trunk when building, or should I be using one of the release branches?

**Comment by KyleBernelle** [comment]
> > > Hello, I also encountered this problem these two days. Later, I used the code pulled by git instead of the directly downloaded package to solve the problem, and I used the hctbuild -vs2019 directive. I don't know if it helped you.
> > 
> > 
> > It did try to run this time, without errors, however it still complains that my version of CMake is too new. I'm running it again to resolve the other things it's complaining about (didn't have VS2019), so not sure that this actually a hindrance, but I keep saying that I need CMake 3.4 when that's what I currently have installed.
> 
> The version of cmake should not have much impact, my cmake version is 3.24, there will still be warnings, but it will not affect the success of hctbuild.

Are you using the trunk when building, or should I be using one of the release branches?

**Comment by keyi4541** [comment]
It is recommended not to use the main branch, which is prone to problems. I'm using the release-1.7.2212 branch, which should be a bit more stable.  At the same time, you can check whether the relevant environment on VS2022 is installed, my previous VS2022 did not install the ATL tool, resulting in hctbuild will display the error that "atls.lib" cannot be opened.

**Comment by keyi4541** [comment]
> It is recommended not to use the main branch, which is prone to problems. I'm using the release-1.7.2212 branch, which should be a bit more stable. At the same time, you can check whether the relevant environment on VS2022 is installed, my previous VS2022 did not install the ATL tool, resulting in hctbuild will display the error that "atls.lib" cannot be opened.

It is recommended not to use the main branch, which is prone to problems. I'm using the release-1.7.2212 branch, which should be a bit more stable. At the same time, you can check whether the relevant environment on VS2022 is installed, my previous VS2022 did not install the ATL tool, resulting in hctbuild will display the error that "atls.lib" cannot be opened.

**Comment by KyleBernelle** [comment]
> > It is recommended not to use the main branch, which is prone to problems. I'm using the release-1.7.2212 branch, which should be a bit more stable. At the same time, you can check whether the relevant environment on VS2022 is installed, my previous VS2022 did not install the ATL tool, resulting in hctbuild will display the error that "atls.lib" cannot be opened.
> 
> It is recommended not to use the main branch, which is prone to problems. I'm using the release-1.7.2212 branch, which should be a bit more stable. At the same time, you can check whether the relevant environment on VS2022 is installed, my previous VS2022 did not install the ATL tool, resulting in hctbuild will display the error that "atls.lib" cannot be opened.

Got it opening in Visual Studio 2022, now it's just giving me the same errors but in the build output. All of the errors are within hlsl.bin\CMakeFiles.

`Error	MSB8066	Custom build for hlsl.bin\CMakeFiles`

**Comment by KyleBernelle** [comment]
This is the line the build is failing on. Line 248 in Microsoft.CppCommon.targets
  
  C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets
  
   ``` <CustomBuild Condition ="'@(_CustomBuild)' != ''"
      Sources                     ="@(_CustomBuild)"
      BuildSuffix                 ="$(_BuildSuffix)"```

**Comment by hekota** [comment]
Try building the project that failed individually and check for error messages in the output:

`msbuild C:\Users\<MyUsername>\Documents\hlsl.bin\include\dxc\DXIL\DxilConstants.vcxproj`

**Comment by hekota** [comment]
Checkout the the Usage section in here, that should help: https://github.com/microsoft/DirectXShaderCompiler/wiki/D3DCompiler-DXC-Bridge

**Comment by KyleBernelle** [comment]
> Checkout the the Usage section in here, that should help: https://github.com/microsoft/DirectXShaderCompiler/wiki/D3DCompiler-DXC-Bridge

Yes that was the article I was referencing that I saw posted, but it doesn't give any info other than "copy it next to the app"

**Comment by hekota** [comment]
It says to copy d3dcompiler_dxc_bridge.dll next to the app and rename it d3dcompiler_47.dll, and that you should also copy dxcompiler.dll and dxil.dll next to the app, so the compiler and validator can be found.

**Comment by KyleBernelle** [comment]
> It says to copy d3dcompiler_dxc_bridge.dll next to the app and rename it d3dcompiler_47.dll, and that you should also copy dxcompiler.dll and dxil.dll next to the app, so the compiler and validator can be found.

Yeah and I've complete those steps but doesn't say the proper way to include the dlls in the project or what header files to reference, that's mainly what I was wondering about. Thanks for your replies btw!

**Comment by hekota** [comment]
The d3dcompiler_dxc_bridge.dll is a dll that will forward D3DCompiler API calls to DirectX Shader Compiler (dxcompiler.dll). So there should no be any headers needed, just use the D3DCompiler API and it will redirect it to DXC.
