### ISSUE TITLE
[SPIR-V] IsHelperLane intrinsic function unimplemented

### ISSUE THREAD

**Issue by danginsburg** [microsoft/DirectXShaderCompiler#5427]
I am trying to use IsHelperLane() intrinsic in Vulkan/SPIR-V (https://microsoft.github.io/DirectX-Specs/d3d/HLSL_ShaderModel6_6.html) and getting the following error from DXC:

```
IsHelperLane intrinsic function unimplemented
```

This should be implementable, I believe using SPIR-V HelperInvocation built-in as is done with gl_HelperInvocation in GLSL.

**Comment by s-perron** [comment]
Yes, this could be implemented by generating a volatile load of the `HelperInvocation` builtin.

**Comment by jeremy-lunarg** [comment]
> @jeremy-lunarg Can you take a look at this issue?

Yes, thanks!
