### ISSUE TITLE
[lit] Support both lit FileCheck test and taef FileCheck test in hcttest file-check

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#5429]
To unblock adding lit FileCheck test, we need hcttest file-check to support both lit FileCheck test and taef FileCheck test.

https://github.com/microsoft/DirectXShaderCompiler/pull/5393 will fix this.

**Comment by llvm-beanz** [comment]
@python3kgae is this done?

**Comment by python3kgae** [comment]
Fixed.
