### ISSUE TITLE
[lib] fallback to taef for taef only filter options

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#5430]
It is not easy to pass through the quoted /p options thru python. And these options are mainly for local debug filter, not for taef FileCheck tests. Just fall back to taef for these options and treat them like taef helper.

This is help to allow lit FileCheck shell test.

https://github.com/microsoft/DirectXShaderCompiler/pull/5404 is for this issue.

**Comment by llvm-beanz** [comment]
@python3kgae is this done?

**Comment by python3kgae** [comment]
Fixed.
