### ISSUE TITLE
[lit] allow to add lit FileCheck shell test

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#5431]
Taef FileCheck test is like lit FileCheck test, but not all Taef FileCheck test can run as lit FileCheck test directly.

This work item is allow change Taef FileCheck tests to lit FileCheck test in small batches so we can use these tests for upstream work.

**Comment by llvm-beanz** [comment]
@python3kgae what needs to be done here?

**Comment by python3kgae** [comment]
> @python3kgae what needs to be done here?

Is there any document needs to mention this change?

**Comment by python3kgae** [comment]
lit is the only test suites now.
It is OK to add lit FileCheck shell test.
