### ISSUE TITLE
[SPIRV] Handle arrays of RWStructuredBuffers, AppendStructuredBuffers, and ConsumeStructuredBuffers

### ISSUE THREAD

**Issue by s-perron** [microsoft/DirectXShaderCompiler#5440]
# Summary

Many individuals have [requested an array of RWStructuredBuffers](https://github.com/microsoft/DirectXShaderCompiler/issues/3281). The main design consideration is how to handle the counter buffer and how to assign the sets and bindings.

The solution will be to handle a RWStructuredBuffer as if it were two arrays of resources: one for the buffer and one for the counter. We can assign set and binding in the same way we do other resource arrays, such as arrays of images and samplers.

# Design difficulties

As [Ehsan noted](https://github.com/microsoft/DirectXShaderCompiler/issues/3281#issuecomment-741846195), there are some design decisions that need to be made regarding the bindings and how to flatten the arrays. I believe that this comment was interpreted in the most pessimistic way, which led to [an early design where we attempted to add arrays of RWStructuredBuffers, but only in the case where counters are not needed](https://github.com/microsoft/DirectXShaderCompiler/pull/4663). This is not an ideal solution because it creates a special case in the compiler: There could be a counter for the RWStructuredBuffer, but not always. This also limits what users will be able to do.

A better solution would be to permit arrays of RWStructuredBuffers, regardless of whether or not counters are required. This would simplify the compiler and give users more flexibility. When I read Ehsan's comment, I do not believe the issues raised are insurmountable. Rather, they are issues that must be addressed. In general, we already have the tools and precedent to solve them.

# Step to implement

The code to implement each of these case will be guarded by a command line option until the feature is complete

- [x] Add option `-fvk-allow-rwstructuredbuffer-arrays` to enable arrays of RWStructuredBuffers and the like. (#5405)
- [x] Fix sized arrays with no counter (#5405)
- [x] Fix sized arrays with a counter (https://github.com/microsoft/DirectXShaderCompiler/pull/5415)
- [x] Passing an element of the array to a function without a counter (https://github.com/microsoft/DirectXShaderCompiler/pull/5447)
- [x] Passing an element of the array to a function with a counter (https://github.com/microsoft/DirectXShaderCompiler/pull/5447)
- [x] Creating a local alias to the global array without a counter (https://github.com/microsoft/DirectXShaderCompiler/pull/5523)
- [x] Creating a local alias to the global array with a counter (https://github.com/microsoft/DirectXShaderCompiler/pull/5523)
- [x] Unbounded arrays with a counter (https://github.com/microsoft/DirectXShaderCompiler/pull/5532)
- [ ] Multidimensional arrays (https://github.com/microsoft/DirectXShaderCompiler/pull/5532)
- [ ] Arrays with a counter defined in a struct
- [x] Allow attributes to set bindings (https://github.com/microsoft/DirectXShaderCompiler/pull/5456)

# Proposed solution

The solution will be to treat arrays of RWStructuredBuffer, AppendStructuredBuffer, and ConsumeStructuredBuffer as if they have an implicit second resource that is an array of counters. Assigning a set and binding will follow the same algorithm as arrays of other resource types.

Since RWStructuredBuffer, AppendStructuredBuffer, and ConsumeStructuredBuffer are essentially the same as far as SPIR-V is concerned, the examples below will only discuss RWStructuredBuffers.

## Bounded array with no counter

```
struct PSInput
{
	uint idx : COLOR;
};

RWStructuredBuffer<uint> g_rwbuffer[5] : register(u0, space2);

float4 PSMain(PSInput input) : SV_TARGET
{
	return g_rwbuffer[input.idx][0];
}
```

When this is compiled without `-fspv-flatten-resource-arrays`, I would expect the spir-v to contain

```
OpDecorate %g_rwbuffer DescriptorSet 2
OpDecorate %g_rwbuffer Binding 0

%_runtimearr_uint = OpTypeRuntimeArray %uint
%type_RWStructuredBuffer_uint = OpTypeStruct %_runtimearr_uint
%_arr_type_RWStructuredBuffer_uint_uint_5 = OpTypeArray %type_RWStructuredBuffer_uint %uint_5
%_ptr_Uniform__arr_type_RWStructuredBuffer_uint_uint_5 = OpTypePointer Uniform %_arr_type_RWStructuredBuffer_uint_uint_5
%g_rwbuffer = OpVariable %_ptr_Uniform__arr_type_RWStructuredBuffer_uint_uint_5 Uniform
```

*   This follows the code generated for [an array of structured buffers](https://godbolt.org/z/K7WbnbY5z), except that the NonWritable decoration is removed.
*   The counter buffer is eliminated after optimization, even a `-O0`.
*   The resource uses a single binding following the space and register.

If it is compiled with -fspv-flatten-resource-arrays, then I should no longer see the array of resources, but five RWStructuredBuffers instead. They should all be in descriptor set 2 with bindings 0 to 4.

## Bounded array with counter

There are cases where the counter will be necessary. This is one example.

```
struct PSInput
{
	uint idx : COLOR;
};

RWStructuredBuffer<uint> g_rwbuffer[5] : register(u0, space2);

float4 PSMain(PSInput input) : SV_TARGET
{
    g_rwbuffer[input.idx].IncrementCounter();
    return g_rwbuffer[input.idx][0];
}
```

When this is compiled without `-fspv-flatten-resource-arrays`, I would expect the spir-v to represent the buffer as it did in the previous case. However, I would now expect it to also contain: \

```
OpDecorate %counter_var_g_rwbuffer DescriptorSet 2
OpDecorate %counter_var_g_rwbuffer Binding 1

%type_ACSBuffer_counter = OpTypeStruct %int
%_arr_type_ACSBuffer_counter_uint_5 = OpTypeArray %type_ACSBuffer_counter %uint_5
%_ptr__arr_type_ACSBuffer_counter_uint_5 = OpTypePointer Uniform %_arr_type_ACSBuffer_counter_uint_5
%counter_var_g_rwbuffer = OpVariable %_ptr__arr_type_ACSBuffer_counter_uint_5 Uniform
```

*   The counter buffer is assigned the next available binding in the same descriptor set. See the [HLSL register and Vulkan binding documentation](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst#hlsl-register-and-vulkan-binding) for details.

If it is compiled with -fspv-flatten-resource-arrays, then I should no longer see the array of counter variables, but five individual counter buffers instead. They should all be in descriptor set 2 with bindings 5 to 9. They take the next 5 bindings that are available after the 5 bindings for the buffer.

## Counter used indirectly

It is possible for the counter variable to be used indirectly as in this example:

```
struct PSInput
{
	uint idx : COLOR;
};

RWStructuredBuffer<uint> g_rwbuffer[5] : register(u0, space2);

void func(RWStructuredBuffer<uint> local) {
      local.IncrementCounter();
}

float4 PSMain(PSInput input) : SV_TARGET
{
    func(g_rwbuffer[input.idx]);
    return g_rwbuffer[input.idx][0];
}

```

The generated code should be the same as the case above.

## Bounded array with counter and binding attributes

```
struct PSInput
{
	uint idx : COLOR;
};

[[vk::binding(3,4), vk::counter_binding(4)]] RWStructuredBuffer<uint> g_rwbuffer[5] : register(u0, space2);

float4 PSMain(PSInput input) : SV_TARGET
{
    g_rwbuffer[input.idx].IncrementCounter();
    return g_rwbuffer[input.idx][0];
}
```

This is the same as the previous case except that the descriptor set for the buffer and counter should now be 4. The binding for the buffer should be 3, and the binding for the counter should be 4.

If `-fspv-flatten-resource-arrays` is used, then there should be an error or warning because there will be overlap between the buffers and the counters. To work when flattening the arrays, the `vk::counter_binding` would have to be at least 9.

## Unbounded array with counter

```
struct PSInput
{
	uint idx : COLOR;
};

RWStructuredBuffer<uint> g_rwbuffer[] : register(u0, space2);

float4 PSMain(PSInput input) : SV_TARGET
{
    g_rwbuffer[input.idx].IncrementCounter();
    return g_rwbuffer[input.idx][0];
}
```

The final feature to consider are unbounded arrays:

In this case, there is no size to the array of RWStructuredBuffers. This should end up being the same as the bounded array with a counter case except that instead of having arrays of size 5 for the buffer and counter, they should be runtime arrays.

The other difference is that the `-fspv-flatten-resource-arrays` option no longer makes sense, and should have no effect.

## Multidimensional arrays

```
struct PSInput
{
	uint idx : COLOR;
};

RWStructuredBuffer<uint> g_rwbuffer[2][2] : register(u0, space2);

float4 PSMain(PSInput input) : SV_TARGET
{
    return g_rwbuffer[input.idx][1][0];
}
```

These will be difficult to handle. Vulkan does not allow multi dimensional arrays of resources. See 

- https://gitlab.khronos.org/spirv/SPIR-V/-/issues/743
- https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#interfaces-resources-setandbinding

For now, we will issue an error for multi dimensional arrays. This matches the behaviour of multi-dimensional arrays of Textures and Samplers.

**Comment by Ipotrick** [comment]
Any updates on this?

**Comment by Keenuts** [comment]
Steven is out of office, but yes this bug is in his pipeline ☺️

**Comment by devshgraphicsprogramming** [comment]
I have another example possibly not covered (no `:register`)
```cpp
[[vk::binding(1, 0)]] RWStructuredBuffer<Output<> > output[8];
```

**Comment by s-perron** [comment]
We have done all of the work that we will do on this. I will try to get PR out that will turn on the option by default, and will issue error for the cases that we do not handle yet.
