### ISSUE TITLE
DXC adds SPIR-V capability MeshShadingNV instead of MeshShadingEXT

### ISSUE THREAD

**Issue by jmoguill** [microsoft/DirectXShaderCompiler#5474]
**Description**
When compiling a mesh shader in HLSL, DXC declares the SPIRV-Capability MeshShadingNV but I told DXC to use MeshShadingEXT (platform-independent):
-fspv-extension=SPV_EXT_mesh_shader

Can you confirm : please don't enable vendor-specific extensions unless the user requests it?
Otherwise the shader code will only work on one GPU vendor....
Even if the shader is compiled on a PC with Nvidia GPU, it shouldn't enable vendor-specific extensions because the shaders need to work on multiple GPUs

**Steps to Reproduce**
I can't share the shader code but it's an HLSL Meshlet shader, there's nothing vendor-specific declared in the shader?
When trying to load the shader:
The SPIR-V Capability (MeshShadingNV) was declared, but none of the requirements were met to use it

We enable MeshShadingEXT not MeshShadingNV because we want our engine to work on all GPU vendors, not just one...

**Actual Behavior**

**Environment**
- using dxc version: 1.7 - 1.7.0.3795 (bef540d36)

- Host Operating System Windows 10 22H2

**Comment by sudonatalie** [comment]
In general, if the EXT MeshShading extension is enabled then I would expect the EXT Capability to be added, not NV, and we have some tests that verify this for simple cases. Without a sample or repro shader I don't think we can debug this issue further.

Can you create a minimal shareable sample from your shader code and provide the full compilation command that would allow us to investigate further?

**Comment by jmoguill** [comment]
sorry you're right it was a bug on my side....
Thanks
