### ISSUE TITLE
[SPIR-V] Generation of 16-bit load from ByteAddressBuffer incorrect

### ISSUE THREAD

**Issue by nyorain** [microsoft/DirectXShaderCompiler#5475]
**Description**
The [ByteAddressBuffer typed load/store functionality](https://github.com/microsoft/DirectXShaderCompiler/wiki/ByteAddressBuffer-Load-Store-Additions) wiki page states `The byteOffset should be aligned by size of the largest component that the type contains`. Does that mean loading 16-bit floats from a ByteAddressBuffer only requires an alignment of 2? The generated code looks good for DXIL but is incorrect for SPIR-V.

**Steps to Reproduce**
[Shader Playground](https://shader-playground.timjones.io/c04f1a1bae3f0c71bd5a81aca1233cdd), note how we pass the `-enable-16bit-types` flag.
```hlsl
RWStructuredBuffer<float> DstBuf;
ByteAddressBuffer SrcBuf;

struct HalfStruct
{
    half a;
    half b;
};

[numthreads(8, 8, 1)]
void CSMain()
{
    // This doesn't work with SPIR-V, will load the same values in both instsructions
    DstBuf[0] = SrcBuf.Load<half>(0u);
    DstBuf[1] = SrcBuf.Load<half>(2u);
    
    // This works in SPIR-V generation
    HalfStruct hs = SrcBuf.Load<HalfStruct>(4u);
    DstBuf[2] = hs.a;
    DstBuf[3] = hs.b;
}
```

 I would expect this to correctly load the halfs from the respective offsets, given the documentation mentioned above

**Actual Behavior**
The generated SPIR-V for the first two lines in `CSMain` looks like this:
```spir-v
         %26 = OpAccessChain %_ptr_StorageBuffer_uint %SrcBuf %uint_0 %uint_0
         %27 = OpLoad %uint %26
         %28 = OpUConvert %ushort %27
         %29 = OpBitcast %half %28
         %30 = OpFConvert %float %29
         %31 = OpAccessChain %_ptr_StorageBuffer_float %DstBuf %int_0 %uint_0
               OpStore %31 %30
         %32 = OpLoad %uint %26
         %33 = OpUConvert %ushort %32
         %34 = OpBitcast %half %33
         %35 = OpFConvert %float %34
         %36 = OpAccessChain %_ptr_StorageBuffer_float %DstBuf %int_0 %uint_1
               OpStore %36 %35
```
In both cases, the same value is loaded, looks like the generation just assumes all loads are 4-byte aligned. The second case (loading a struct with halfs) looks correct (includes a `OpShiftRightLogical` of the loaded uint). The DXIL output also looks correct.

**Environment**
- dxcompiler.dll: 1.7 - 1.7.0.3939 (5e080a772)

**Comment by sudonatalie** [comment]
Triage note: By disabling optimizations we can see that the bug is introduced here, where shifting right instead of left brings both indices to 0:

```
         %23 = OpShiftRightLogical %uint %uint_0 %uint_2
         %25 = OpAccessChain %_ptr_StorageBuffer_uint %SrcBuf %uint_0 %23
...
         %34 = OpShiftRightLogical %uint %uint_2 %uint_2
         %35 = OpAccessChain %_ptr_StorageBuffer_uint %SrcBuf %uint_0 %34
```

**Comment by s-perron** [comment]
@cassiebeckley Can you take a look at this bug? Hopefully it is not a big fix.
