### ISSUE TITLE
[Build] Compile with clang-cl on windows

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#5480]
To be able to use clang Source Based Code Coverage tool https://clang.llvm.org/docs/SourceBasedCodeCoverage.html on windows, need to compile with clang-cl first.

Now hit a lot of error/warning when compile with clang-cl.

Goal:
Build and pass all test with clang-cl on windows.

**Comment by pow2clk** [comment]
Fixed by #6084
