### ISSUE TITLE
Clean up DXC test directories

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5490]
**Is your feature request related to a problem? Please describe.**
DXC’s tests are extremely disorganized which makes it difficult to look through the tests.

**Describe the solution you'd like**
Clang organizes tests by what they are testing. Tests that test semantic analysis go under the `test/Sema` directory, tests that test code generation go under the `test/CodeGen` directory.

We should move the non-LIT driven tests out of the `test` directory so that we can create clean directory layouts for the LIT tests.

We should stop adding new directories that have LIT or FileCheck in the name as that is redundant and unnecessary.

We should sort new tests by what they test rather than by how they are tested. “Validation” tests might be parsing or sema tests, so we shouldn’t lump them together. Our existing “FileCheck” tests are wildly disorganized and have become a dumping ground.

**Describe alternatives you've considered**
Maintaining the status quo is harmful.

**Comment by hekota** [comment]
We should also cleanup the lit test enumeration. Currently hcttest clang ends like this:
```
 -- Testing: 7416 tests, 64 threads --

  Testing Time: 146.03s
    Expected Passes    : 817
    Unsupported Tests  : 6599
```
It seems wrong to have 6599 unsupported tests by default.

**Comment by llvm-beanz** [comment]
I think changing the lit config to only search for `.hlsl` and `.test` files as tests would likely remove most of the unsupported tests.
