### ISSUE TITLE
Linux libdxil.so does not export DxcCreateInstance as dynamic symbol

### ISSUE THREAD

**Issue by wshallum** [microsoft/DirectXShaderCompiler#5500]
**Description**

The `libdxil.so` does not export `DxcCreateInstance` or `DxcCreateInstance2` as dynamic symbols leading to errors like:

```
warning: DXIL signing library (dxil.dll,libdxil.so) not found.  Resulting DXIL will not be signed for use in release environments.
```

**Steps to Reproduce**

To prove:

```
$ readelf -W -s libdxil.so  | grep DxcCreateInstance
  4229: 0000000000028410   192 FUNC    LOCAL  DEFAULT   12 DxcCreateInstance2
  6980: 0000000000028360   175 FUNC    LOCAL  DEFAULT   12 DxcCreateInstance
$ readelf -W --dyn-syms libdxil.so  | grep DxcCreateInstance
```

Compare to:

```
$ readelf -W -s libdxcompiler.so  | grep DxcCreateInstance
   359: 000000000011abe0    96 FUNC    GLOBAL DEFAULT   12 DxcCreateInstance2
   605: 000000000011a930    95 FUNC    GLOBAL DEFAULT   12 DxcCreateInstance
  2336: 000000000011a990   591 FUNC    LOCAL  DEFAULT   12 _ZL29ThreadMallocDxcCreateInstanceRK5_GUIDS1_PPv
 51498: 000000000011a930    95 FUNC    GLOBAL DEFAULT   12 DxcCreateInstance
 51589: 000000000011abe0    96 FUNC    GLOBAL DEFAULT   12 DxcCreateInstance2
$ readelf -W --dyn-syms libdxcompiler.so  | grep DxcCreateInstance
   359: 000000000011abe0    96 FUNC    GLOBAL DEFAULT   12 DxcCreateInstance2
   605: 000000000011a930    95 FUNC    GLOBAL DEFAULT   12 DxcCreateInstance
```

**Actual Behavior**

Since they are not dynamic symbols, using `dlsym` on them fails and `dxc` will complain with the above error (libdxil not found).

**Environment**
- DXC version `libdxcompiler.so: 1.7(dev;3787-e043f4a1)`
- Host Operating System Ubuntu 22.04 / WSL2 ; kernel `Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023`

**Comment by shawnhatori** [comment]
I'm also running into this issue. Seems like an issue was previously created here: https://github.com/microsoft/DirectXShaderCompiler/issues/5107

**Comment by wshallum** [comment]
I missed that when searching, will close this as duplicate then.
