### ISSUE TITLE
opt.exe -help doesn't do anything except recommend you use opt.exe -help

### ISSUE THREAD

**Issue by jeffnn** [microsoft/DirectXShaderCompiler#5514]
**Description**
opt.exe -help doesn't do anything except recommend you use opt.exe -help. 

**Steps to Reproduce**
 opt.exe -help 

**Actual Behavior**
 opt.EXE: Unknown command line argument '-help'.  Try: 'D:/hlsl.bin/Debug/bin\opt.EXE -help'. 

**Environment**
- Host Operating System any?

**Comment by llvm-beanz** [comment]
@jeffnn look, I get that the bug is pretty obvious, but we do have an issue template for a reason. Please fill it out.

**Comment by jeffnn** [comment]
> @jeffnn look, I get that the bug is pretty obvious, but we do have an issue template for a reason. Please fill it out.

I totally did fill it out! But now I realize that I left the data inside comment blocks. I'll edit them out.

**Comment by jeffnn** [comment]
Oops accidentally closed.

**Comment by jeffnn** [comment]
> @jeffnn look, I get that the bug is pretty obvious, but we do have an issue template for a reason. Please fill it out.

Ah, now I realize that the template is markdown.
