### ISSUE TITLE
fail to build can not find -lHLSLTestLib

### ISSUE THREAD

**Issue by adcdam** [microsoft/DirectXShaderCompiler#5539]
[100%] Built target dxc
[100%] Linking CXX executable ../../../../bin/dxa
/usr/bin/ld: cannot find -lHLSLTestLib: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [tools/clang/tools/dxa/CMakeFiles/dxa.dir/build.make:124: bin/dxa-3.7] Error 1
make[1]: *** [CMakeFiles/Makefile2:9533: tools/clang/tools/dxa/CMakeFiles/dxa.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

how can i fix this?

**Comment by llvm-beanz** [comment]
Hi @adcdam, can you please provide more information. This issue does not occur for me. The things we need to know are:

1) What CMake command did you run to configure your build?
2) What is your host OS?

**Comment by llvm-beanz** [comment]
With no response from @adcdam I'm going to close this issue. If you're still having trouble, please reach out with additional information about your configuration.
