### ISSUE TITLE
Invalid SPIR-V: Entry-point has conflicting input location assignment 

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [microsoft/DirectXShaderCompiler#5540]
**Description**
Using a mix of **BDA/RawBufferLoad** and **double4** as pixel shader input location generates invalid spir-v.
If you remove usage of either one the compilation succeeds. (change double4 to double2 or instead of RawBufferLoad to normal SRV load)

**Steps to Reproduce**

Compiler Options:
```
-spirv -T ps_6_0 -E PSMain
```

Code:
```
struct Test {
    float4 mem1;
    float mem2;
    int mem3;
};

StructuredBuffer<Test> mytests : register(t0, space0);

uint64_t address;

struct PSInput
{
    float4 position : SV_Position;
    [[vk::location(0)]] float4 data0 : COLOR;
    [[vk::location(1)]] nointerpolation uint4 data1 : COLOR1;
    [[vk::location(2)]] nointerpolation double4 data2 : COLOR2;
    [[vk::location(3)]] nointerpolation double4 data3 : COLOR3;
};

float4 PSMain(PSInput input) : SV_TARGET
{
	return input.data0 + vk::RawBufferLoad<Test>(address).mem1;
}
```

You can also see this in Compiler Explorer: https://godbolt.org/z/eYzrbfG4z

**Actual Behavior**

```
fatal error: generated SPIR-V is invalid: [VUID-StandaloneSpirv-OpEntryPoint-08721] Entry-point has conflicting input location assignment at location 3, component 0
  OpEntryPoint Fragment %PSMain "PSMain" %gl_FragCoord %in_var_COLOR %in_var_COLOR1 %in_var_COLOR2 %in_var_COLOR3 %out_var_SV_TARGET

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible

Compiler returned: 5
```

**Environment**
- DXC (trunk)

I can't provide any further help as I'm not SPIR-V expert.

**Comment by sudonatalie** [comment]
A `double4` consumes 2 Locations, so in this case both `data2` and `data3` are using `Location 3`. You could explicitly move `data3` to start at `[[vk::location(4)]]` or use the implicit Location number assignment (just remove all `vk::location` attributes) and this will be calculated correctly by default.

I'm leaving this issue open since the compiler should ideally fail earlier rather than produce invalid SPIR-V. However, since this only occurs if the conflicting Locations are explicitly assigned, this is a low-priority improvement.

**Comment by sudonatalie** [comment]
Looks like we do already have this logic for most cases of overlapping Locations, so it should actually be a really quick fix.

**Comment by Erfan-Ahmadi** [comment]
Thank you @sudonatalie for the enlightenment on the issue
I was unaware that each location is 4 dwords. And it got confusing because there is some kind of conflict with the usage of BDA. (Removing that will compile a correct spirv and not complain about anything)

**Comment by sudonatalie** [comment]
Removing the buffer usage just happens to make the code simple enough that the compiler can eliminate all of the inputs other than `data0`, so the problematic variables no longer exists in optimized code.
