### ISSUE TITLE
DXC test run not showing which tests were run and contains many unsupported tests

### ISSUE THREAD

**Issue by hekota** [microsoft/DirectXShaderCompiler#5550]
**Description**
DXC test run for several minutes and are not showing any progres, like which tests were run. Plus it contains many unsupported tests. It would be nice to see the list of tests that were run.

**Steps to Reproduce**
hcttest

**Actual Behavior**
Only shows number of tests passed and the number of unsupported tests:

```
  -- Testing: 12719 tests, 64 threads --

  Testing Time: 148.16s
    Expected Passes    : 2266
    Expected Failures  : 1
    Unsupported Tests  : 10452
```
** Desired Behavior **
```
  -- Testing: <2000-ish number here> tests, 64 threads --
...
list tests that were run
...

  Testing Time: *s
    Expected Passes    : 2266
    Expected Failures  : 1
    Unsupported Tests  : <low number here>
```

**Environment**
DXC main as of 8/15/23
Windows

**Comment by hekota** [comment]
Some people prefer not to have all the tests listed because it fills up the console cache, so we should at least add an option to show the list.

**Comment by llvm-beanz** [comment]
@hekota IIRC you were working on this. Can you please update the issue as appropriate?
