### ISSUE TITLE
Enable CETCOMPAT (CET shadow stack) when building DXC

### ISSUE THREAD

**Issue by amaiorano** [microsoft/DirectXShaderCompiler#5578]
Please enable [CETCOMPAT](https://learn.microsoft.com/en-us/cpp/build/reference/cetcompat?view=msvc-170) when building DXC.

We require this flag for DLLs that ship in Chrome, as it is an important safeguard against ROP/JOP attacks.

Although closed-source, please also add this flag when building `dxil.dll`.

**Comment by hekota** [comment]
The is a good thing to do and the performance should be minimal since it is implemented in HW. All native x64 Windows libraries are compiled with this flag.

**Comment by hekota** [comment]
Yes, I have done this to for `dxil.dll` as well. It will be shipped with this flag in the next release.
