### ISSUE TITLE
Disallow multiple different HLSLShader attributes on the same function

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5601]
**Description**
The work graphs spec has been updated to disallow marking shaders as both `compute` and `node`:
https://github.com/microsoft/hlsl-specs/pull/62/commits/48c683ee09da2451e1d551c1777f2ed7c6f00ef8

This will allow us to simplify aspects of our diagnostic implementation.

**Environment**
- DXC version https://github.com/microsoft/DirectXShaderCompiler/tree/staging-sm-6.8

**Comment by pow2clk** [comment]
Previous behavior disallowed conflicting shader attributes for the same entry function. This was relaxed for work graphs to allow compute and node which we have reconsidered.

**Comment by bob80905** [comment]
Closed by #5679
