### ISSUE TITLE
Clarify templated `ByteAddressBuffer` load/store alignment requirement for `byteOffset`

### ISSUE THREAD

**Issue by jeremyong** [microsoft/DirectXShaderCompiler#5604]
I am struggling a bit to understand the exact rules governing the alignment restriction of the `byteOffset` argument to templated `[RW]ByteAddressBuffer` `Load` and `Store` methods.

The only documentation I could find is in this repo's [wiki](https://github.com/microsoft/DirectXShaderCompiler/wiki/ByteAddressBuffer-Load-Store-Additions) where you can find this:

> The layout of the type mapped into the buffer matches the layout used for StructuredBuffer. The byteOffset should be aligned by size of the largest component that the type contains.

The bit about the layout of the template argument is unambiguous. The next statement is somewhat confusing however. When I read `component`, normally I think of a component in the sense that `x`, `y`, `z`, and `w` are components of a `float4`. However, there's no HLSL `Vector` or `Matrix` for which a "largest component size" is distinct from just the "component size". In addition, there isn't any information I can glean about what restrictions (if any) there are on user-defined structs or arrays. Is the implication that the alignment restriction is the size of the largest component of any field or element in the template argument? Possibly extending to nested structs also? Under what circumstances does the alignment restriction relax to be 2-bytes when compiling with 16 bit types enabled?

Any clarity would be appreciated, thanks!

**Comment by tex3d** [comment]
In this document, "component" is a term used to refer to a scalar element, such as a float or uint16_t.  So, if you take the type, which can be a user-defined-type and break it down into all the scalar elements it contains, the required alignment is the size in bytes of the largest scalar element, such as 4 for float/uint, 8 for double/uint64_t, or 2 for float16_t/uint16_t.

I have attempted to clarify the language on the wiki page.

Thanks!
