### ISSUE TITLE
Problem with mad intrinsic

### ISSUE THREAD

**Issue by Goshido** [microsoft/DirectXShaderCompiler#5608]
The following minimal snippet can't be compiled with _DirectX Shader Compiler 1.7.2308.10004_ `a5b0488bc5b20659662bdfdad134c13cb376189b`.

```hlsl
#define THREAD_X        256
#define THREAD_Y        1
#define THREAD_Z        1

struct ExposureInfo
{
    float                           _eyeAdaptation;
    float                           _maxLuma;
    float                           _minLuma;
    float                           _exposureCompensation;
};

[[vk::push_constant]]
ExposureInfo                        g_ExposureInfo;

[[vk::binding ( 0, 0 )]]
RWStructuredBuffer<float32_t>       g_Brightness:       register ( u2 );

[[vk::binding ( 1, 0 )]]
RWStructuredBuffer<float32_t>       g_Exposure:         register ( u3 );

[numthreads ( THREAD_X, THREAD_Y, THREAD_Z )]
void CS ()
{
    float16_t const prevLuma = (float16_t)g_Brightness[ 0U ];
    float16_t const deltaLuma = 0.42H - prevLuma;
    float16_t const eyeLuma = mad ( deltaLuma, (float16_t)g_ExposureInfo._eyeAdaptation, prevLuma );
    g_Brightness[ 0U ] = (float32_t)eyeLuma;

    float16_t const keyValue = 1.03H + ( -2.0H / ( log10 ( eyeLuma + 1.0H ) + 2.0H ) );
    float16_t const luma = clamp ( eyeLuma, (float16_t)g_ExposureInfo._minLuma, (float16_t)g_ExposureInfo._maxLuma );
    g_Exposure[ 0U ] = (float32_t)( keyValue / ( luma - (float16_t)g_ExposureInfo._exposureCompensation ) );
}
```

### Expected result

Compilation success. _DXC_ produces _SPIR-V_ binaries.

### Actual result

Compilation error:

```PowerShell
dxc.exe
  -HV 2021
  -spirv
  -fvk-use-dx-layout
  -fspv-reduce-load-size
  -fspv-target-env=vulkan1.1
  -enable-16bit-types
  -WX
  -O3
  -E
  CS
  -T
  cs_6_7
  -Fo test.cs

fatal error: generated SPIR-V is invalid: GLSL.std.450 Fma: expected types of all operands to be equal to Result Type
  %42 = OpExtInst %half %1 Fma %41 %float_0_30103001 %half_0x1p_1

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

No _SPIR-V_ binaries.

### Further technical details

- `git submodule update --init` has been invoked before build
- `hctbuild` build parameters: `-official -rel -x64 -vs2022 -speak-up -no-dxilconv -spirv`
- _Visual Studio 2022 Community_ components were up to date.
- _Windows 11 Pro 64-bit (22621.1992, Version 22H2)_
- `dxc.exe` 1.7.2308.10004 executable, commit SHA-1 `a5b0488bc5b20659662bdfdad134c13cb376189b`

Would you kindly help?

## Investigation

The issue disappears after changing all types to `float32_t` .

**Comment by s-perron** [comment]
The problem is when you use `log10` with a float16_t. The code that DXC is generating contains a multiple between a half and a float, which is wrong.

The reduced test case is:

```
[numthreads ( 1, 1, 1 )]
void CS ()
{
    float16_t const keyValue = log10 ( (float16_t)2.0);
}
```

Compile using `-fcgl` instead of `-O3`, so that optimization does not remove the bad multiple during dead code elimination.

**Comment by Goshido** [comment]
Roger that. So is it a bug or feature? Do I need to wait a fix in the future, @s-perron ?

**Comment by s-perron** [comment]
I got half way through a fix before my day ended yesterday. It is a bug.

**Comment by Goshido** [comment]
I checked _DirectX Shader Compiler 1.7.2308.10075_ `087773779c923d01408920605ed867686d3a9d5e`. The issue has been fixed. Thank you! 👍
