### ISSUE TITLE
Wavesize attribute errors don't include node shaders and are not tested

### ISSUE THREAD

**Issue by pow2clk** [microsoft/DirectXShaderCompiler#5610]
**Description**
The error "attribute WaveSize only valid for CS" is inaccurate because it should also be valid for node shaders

**Steps to Reproduce**
apply the WaveSize attribute to a non-compute and non-node shader and the error should be produced

Though no tests exist for this just yet.

**Actual Behavior**
The error message is "attribute WaveSize only valid for CS.", which is misleading

**Environment**
- DXC version 1.8.2306-preview
- Host Operating System win11

**Comment by bob80905** [comment]
Closed with #5758
