### ISSUE TITLE
[SPIR-V] Bracket `{}` initialization of struct with a member array generates invalid SPIR-V

### ISSUE THREAD

**Issue by Przemog1** [microsoft/DirectXShaderCompiler#5625]
**Description**

SPIR-V generation fails with
```
fatal error: generated SPIR-V is invalid: Result type (OpTypeArray) does not match the type that results from indexing into the composite (OpTypeArray).
  %460 = OpCompositeExtract %_arr_float_uint_14_0 %454 5
```
this might be because we're trying to `{}` initialize with a  struct that has a `float[14]` member.

However we only need to change one line with `={}` initialization to a static factory method for it to compile and work:
```cpp
        LineStyleClipper<float> clipper = LineStyleClipper<float>::construct( lineStyles[mainObjects[currentMainObjectIdx].styleIdx] );
```
it might be that we are trying something syntatically invalid, but we should have gotten an error in the parser, not deep in SPIR-V.

**Steps to Reproduce**
https://godbolt.org/z/xTarrc4fx

**Actual Behavior**
Error from the compiler before SPIR-V generation and validation/legalization or successful codegen.

**Environment**
- DXC version `2168dcb4fb0ac7841624228f8e186cc28f4cca91` and `libdxcompiler.so: 1.7(dev;1-843019ab)`
- Host Operating System: Windows but DXC as a lib and Godbolt (so Linux

**Comment by sudonatalie** [comment]
Here is an isolated repro sample:

```
// RUN: %dxc -spirv -T ps_6_7 -fcgl

struct LineStyle
{
    float stipplePattern[14];
};

StructuredBuffer<LineStyle> lineStyles : register(t1);

template<typename float_t>
struct LineStyleClipper
{
    static LineStyleClipper<float_t> construct(LineStyle style)
    {
        LineStyleClipper<float_t> ret = { style };
        return ret;
    }
  
    LineStyle style;
};

void main() : SV_TARGET
{
    uint32_t styleIdx;
    // BAD:
    LineStyleClipper<float> clipper = { lineStyles[styleIdx] };
    // GOOD:
    // LineStyleClipper<float> clipper = LineStyleClipper<float>::construct( lineStyles[styleIdx] );

}
```
