### ISSUE TITLE
[Feature Request] Target profiles should be automatically added as HLSL Shader attributes to entry function declarations.

### ISSUE THREAD

**Issue by bob80905** [microsoft/DirectXShaderCompiler#5626]
**Is your feature request related to a problem? Please describe.**
On typical compilation, the target profile and entry point is provided. There are cases where the actual entry point declaration in the source lacks an HLSLShader attribute. This PR allows for function declarations that match the entry point name specified in the compilation arguments (that is, the entry point function) to automatically obtain an HLSL Shader attribute matching the target profile that was also specified in the compilation arguments. 

**Describe the solution you'd like**
The attribute should be inferable from the target profile specified on the compilation command line. 
This should mean that shaders like:

```
DXC -T cs_6_6 -E mymain

[numthreads(1,1,1)]
void mymain(){}
```

should, at the AST level, have the `compute` shader attribute attached to the `mymain` function declaration, even though the attribute wasn't specified.

**Comment by pow2clk** [comment]
Fixed by #5627
