### ISSUE TITLE
Apply ArgsMemOnly attrib and mangling to most WaveMatrix intrinsics

### ISSUE THREAD

**Issue by pow2clk** [microsoft/DirectXShaderCompiler#5636]
**Description**
ArgsMemOnly specified in hctdb.py using the "amo" string are not getting applied to any of the intrinsics. The only intrinsic that receives this is WaveMatrix_Annotate because it is explicitly added. The reason for this is that there is no notion of this attribute in clang that I can discern, so it is not applied during codegen like readnone and readonly are. 

Currently, none of these intrinsics are at risk of being mistaken for another without this attribute, but they should be mangled coming out of codegen anyway in case that ever changes.

**Steps to Reproduce**
The existing WaveMatrix tests in tools/clang/test/HLSLFileCheck/hlsl/objects/WaveMatrix/ all use intrinsics that should have this attribute. 

**Actual Behavior**
It's not obvious from the output that these tests don't have this attribute, but it will be when mangling is applied. 

**Environment**
- DXC version 1.8.2308
- Host Operating System win11

**Comment by damyanp** [comment]
WaveMatrix in the form it was when this issue was filed is no longer a thing.
