### ISSUE TITLE
[SPIR-V] Usage of `vk::RawBuffer` seems to prevent deadcode elimination and very large SPIR-V sizes

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/DirectXShaderCompiler#5641]
**Description**

I've made some code with helper structs for pointer arithmetic, this code computes a whole bunch of addresses from a single `uint64_t` but only a few results actually get used.

If I then use `RWByteAddressedBuffer` to load my POD types in the struct then DXC outputs SPIR-V with only about 40 opcodes with `O3` and 200 with `O0`
https://godbolt.org/z/vrna4xWrM

Whereas if I replace the `RWByteAddressedBuffer.Load` with `vk::RawBufferLoad` I get outputs on the order of 900 opcodes and 25kb no matter if I compile with `O0` or `O3`
https://godbolt.org/z/e3YEdGdqq

Note that for now I'm only loading `uint32_t`, `uint64_t` and `float` from such buffers.

**Steps to Reproduce**

ByteAddressBuffer:
https://godbolt.org/z/vrna4xWrM

RawBuffer:
https://godbolt.org/z/e3YEdGdqq

**Actual Behavior**

Here's the spir-v produced by the `RawBufferLoad` and `RawBufferStore`
[test.zip](https://github.com/microsoft/DirectXShaderCompiler/files/12498365/test.zip)

I tried passing it through `spirv-opt` with various options and no optimization pass is able to make **any** change to the SPIR-V emitted by DXC.

Its extremely unnerving that dead code and variable elimination doesn't seem to work in the presence of PhysicalBufferStorage class pointer types and/or aligned loads/stores, because that should really be the only difference in my uneducated opinion.

**Environment**
- DXC version latest trunk on Godbolt
- Host Operating System Linux/Godbolt

**Comment by cassiebeckley** [comment]
This is because `RawBufferLoad` and `RawBufferStore` use the extension `SPV_KHR_physical_storage_buffer`, which is not present in the extension allow lists for DCE and a couple other passes. See https://github.com/KhronosGroup/SPIRV-Tools/pull/5348 for an example of adding an extension to the allow lists.

**Comment by devshgraphicsprogramming** [comment]
ok we'll try with our own SPIRV-Tools fork.

**Comment by sudonatalie** [comment]
Closing in favor of https://github.com/KhronosGroup/SPIRV-Tools/issues/4896
