### ISSUE TITLE
[SPIR-V] Wrong value for ArrayStride decoration when it involves bitfields

### ISSUE THREAD

**Issue by Keenuts** [microsoft/DirectXShaderCompiler#5648]
**Description**

The `ArrayStride` decoration is incorrectly generated if the buffer contains squashed bitfields.

**Steps to Reproduce**

```hlsl
struct PTE {
  uint valid : 1;
  uint dirty : 1;
};

struct Good {
  uint value;
};

RWStructuredBuffer<PTE>  bad;
RWStructuredBuffer<Good> good;

[numthreads(1, 1, 1)]
void main() {
  if (bad[1].dirty == 1) {
    good[1].value = 0;
  }
}
```

`dxc -T cs_6_6 -E main -spirv ~/repro.hlsl`

**Actual Behavior**

The `ArrayStride` decoration for the `bad` `RWStructuredBuffer` is set to `8` instead of `4`.
This leads to wrong indices being computed (at least different indices that what the host computes when using bitfields.

The root cause seem to be that we compute the `ArrayStride` decoration using the AST nodes, and not the lowered representation. The AST nodes has 2 int, marked as bitfields. SPIR-V representation squashes those 2 bitfields into a single int.

The `good` buffer has the correct stride (4).

**Environment**
- DXC version: HEAD (0f282ccabaf21c88e7dbfe0c866422842b639bc3)
- Host Operating System: linux

**Comment by s-perron** [comment]
This seems to be similar to https://github.com/microsoft/DirectXShaderCompiler/issues/5688. Decisions are made based on the AST, where the bitfields look like separate ints. Later, they are merged into a single int.
