### ISSUE TITLE
Test common input parameters (like SV_DispatchThreadID) lowering for Node Shaders

### ISSUE THREAD

**Issue by pow2clk** [microsoft/DirectXShaderCompiler#5692]
**Is your feature request related to a problem? Please describe.**
There are no tests that verify that common input parameters introduced before Shader Model 6.8 are correctly lowered 

**Describe the solution you'd like**
We need a test that verifies at least some common parameters that are processed the same way when applied to node shaders. Not only that they are accepted, but that the generated output is correct.

**Additional context**
See this untested for node shader code location: 
https://github.com/microsoft/DirectXShaderCompiler/blob/7f6d946c4bcddf1aca604e16ee6d0c0108e2d2b1/lib/HLSL/HLSignatureLower.cpp#L1744

See internal commit 2920

**Comment by tex3d** [comment]
I updated the link above to a permalink for the untested node shader code location, since it didn't take me to the right place anymore.
