### ISSUE TITLE
Resolve PRERELEASE-TODOs for shader model 6.8

### ISSUE THREAD

**Issue by pow2clk** [microsoft/DirectXShaderCompiler#5699]
**Is your feature request related to a problem? Please describe.**
A number of punted changes are annotated in the code in staging-sm-6.8 with the `PRERELEASE-TODO` comment.

Here they are:

https://github.com/microsoft/DirectXShaderCompiler/blob/58a9ac3522c899ee52f091de4fd033e12a710afc/include/dxc/DxilContainer/DxilRuntimeReflection.h#L62
https://github.com/microsoft/DirectXShaderCompiler/blob/58a9ac3522c899ee52f091de4fd033e12a710afc/include/dxc/DxilContainer/DxilRuntimeReflection.h#L79
https://github.com/microsoft/DirectXShaderCompiler/blob/58a9ac3522c899ee52f091de4fd033e12a710afc/include/dxc/DxilContainer/DxilRuntimeReflection.inl#L164
https://github.com/microsoft/DirectXShaderCompiler/blob/58a9ac3522c899ee52f091de4fd033e12a710afc/include/dxc/DxilContainer/DxilRuntimeReflection.inl#L166
https://github.com/microsoft/DirectXShaderCompiler/blob/58a9ac3522c899ee52f091de4fd033e12a710afc/include/dxc/DxilContainer/RDAT_Macros.inl#L33

**Describe the solution you'd like**
We should evaluate them and either decide not to do them and delete the comment, or complete the task and delete the comment.

**Describe alternatives you've considered**
Disregarding all of the en masse is tempting but reckless.

**Comment by hekota** [comment]
Additionally, we should also resolve these `TODO:`s in shader model 6.8. code:

https://github.com/microsoft/DirectXShaderCompiler/blob/d5ddb1e9dff6fdd5f8f0f6e874970b4ad9a63c58/tools/clang/lib/Sema/SemaHLSL.cpp#L14321

https://github.com/microsoft/DirectXShaderCompiler/blob/d5ddb1e9dff6fdd5f8f0f6e874970b4ad9a63c58/include/dxc/HLSL/HLOperations.h#L44
