### ISSUE TITLE
[SPIR-V] Crash if ReportHit's 3rd param uses the return value of a function directly

### ISSUE THREAD

**Issue by EpicJeanNoeMorissette** [microsoft/DirectXShaderCompiler#5709]
**Description**
Crash found in intersection shaders calling the builtin [ReportHit](https://learn.microsoft.com/en-us/windows/win32/direct3d12/reporthit-function) with a function's return value directly in the third param.  Workaround is simply to create a variable with the result beforehand, but if the fix is simple too it might be worth it.

**Steps to Reproduce**

Calling ReportHit with a function in third param crashes:
```
ReportHit(HitT.x, HitKind, CreateAttributes(HitT));
```

This can be worked around simply by creating a variable:
```
FIntersectionAttributes IntersectionAttributes = CreateAttributes(HitT);
ReportHit(HitT.x, HitKind, IntersectionAttributes);
```

**Actual Behavior**

Crash in SpirvEmitter::processReportHit of SpirvEmitter.cpp where both hitAttributeStageVar and hitAttributeArg are null.

**Comment by s-perron** [comment]
@EpicJeanNoeMorissette Could you please provide a sample hlsl file with the exact command line (or options) you are using to compile it?

**Comment by sudonatalie** [comment]
I was able to create a full repro case:

```
// RUN: %dxc -T lib_6_3 -fspv-extension=SPV_NV_ray_tracing -spirv

struct Attribute
{
  float2 bary;
};

Attribute CreateAttribute() {
    return Attribute(float2(0.0f,0.0f));
}

[shader("intersection")]
void main() {
  Attribute myHitAttribute = CreateAttribute();
  ReportHit(0.0f, 0U, myHitAttribute); // WORKS
  ReportHit(0.0f, 0U, CreateAttribute()); // CRASHES
}
```
