### ISSUE TITLE
Node record should allow templated struct/class types

### ISSUE THREAD

**Issue by tcorringham** [microsoft/DirectXShaderCompiler#5729]
**Description**
It should be possible to use a suitable templated struct/class as a node input/output record type.
Currently any templated struct/class is errored as having zero size.

**Steps to Reproduce**
Simple example attached (as a .gz file as .hlsl is not accepted)
[node_record_template.hlsl.gz](https://github.com/microsoft/DirectXShaderCompiler/files/12618948/node_record_template.hlsl.gz)

**Actual Behavior**
The semantic check for a zero size record fails to handle templated types, and reports a zero sized record.
If that check is disabled, then asserts are hit during CodeGen, so bugs are present in both Sema and CodeGen.

**Environment**
- DXC version staging-sm-6.8 branch 
- Host Operating System any

**Comment by tcorringham** [comment]
This issue was caused by the templated type not always being instantiated correctly if it was only used in node record parameter declarations. The fix is to always force specialization when the node record declaration is seen.

**Comment by pow2clk** [comment]
Fixed by #5712
