### ISSUE TITLE
[SPIR-V] `_Static_assert` triggers error not present when emitting DXIL

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/DirectXShaderCompiler#5750]
**Description**
`_Static_assert` works fine in DXIL generation mode, and not when emitting SPIR-V.

**Steps to Reproduce**
https://godbolt.org/z/8rYW71jqd

**Actual Behavior**
Adding `-spirv` to the commandline introduces compilation errors.

**Environment**
- DXC version: Godbolt's trunk
- Host Operating System Linux

**Comment by sudonatalie** [comment]
Related: https://github.com/microsoft/hlsl-specs/issues/33

Given that it's a bit of an odd happenstance that this is working in the DXIL backend (I don't think this is a feature documented anywhere?), we'll keep this bug open to track but it's not likely to be implemented in the near future.

**Comment by devshgraphicsprogramming** [comment]
I see it moved to "Done" does this mean it works now ?

**Comment by s-perron** [comment]
We will not be implementing static assert. We reconsider when implementing in clang.
