### ISSUE TITLE
[SPIR-V] Variable Templates and `using` in global scope not implemented

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/DirectXShaderCompiler#5751]
**Description**
DXIL emission implements there just fine:
https://godbolt.org/z/638TrrhWe
obviously emitting warnings

**Steps to Reproduce**
Adding `-spirv` to the commandline breaks both template using aliases
```cpp
template <bool val>
using bool_constant = integral_constant<bool, val>;
```
and variable templates
```cpp
template <class, class>
static const bool is_same_v = false;

template <class T>
static const bool is_same_v<T, T> = true;
```
https://godbolt.org/z/5ooerq9bY

**Actual Behavior**
Compiler emits errors

**Environment**
- DXC version: Latest Godbolt trunk
- Host Operating System: Linux

**Comment by devshgraphicsprogramming** [comment]
@sudonatalie is this already in current `master` ?

**Comment by sudonatalie** [comment]
No, this issue hasn't been addressed and we can't provide an estimate for when it will be looked at unfortunately.

**Comment by devshgraphicsprogramming** [comment]
> No, this issue hasn't been addressed and we can't provide an estimate for when it will be looked at unfortunately.

thx, I think you told me on another issue that `Done` in HLSL Triage means triaged, not resolved or fixed.

**Comment by cassiebeckley** [comment]
I'll likely be looking at this as part of https://github.com/microsoft/hlsl-specs/blob/main/proposals/0011-inline-spirv.md#types.

**Comment by devshgraphicsprogramming** [comment]
> I'll likely be looking at this as part of https://github.com/microsoft/hlsl-specs/blob/main/proposals/0011-inline-spirv.md#types.

already using the new builtin syntax, looking forward to this next improvement for the types
