### ISSUE TITLE
[Feature Request] Precompiled Headers

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/DirectXShaderCompiler#5771]
**Is your feature request related to a problem? Please describe.**

We are developing a very big (code size, not popularity) HLSL library and `lib_6_x` targets are not an options because:
1. we target SPIR-V
2. we make heavy use of templates

**Describe the solution you'd like**

Be able to create precompiled headers like in Clang 3.7 and then `-include` them.

**Describe alternatives you've considered**

I already resolve all my includes.

I guess I could also preprocess with Boost.Wave but its not as much of a win as having the AST already serialized.

**Additional context**

Clang 3.7 from which DXC forked used to support PCH
https://releases.llvm.org/3.7.0/tools/clang/docs/UsersManual.html#precompiled-headers

One thing I'm not clear on is that in GCC I cannot change any preprocessor definitions which would alter the behaviour of the PCH, is this also the case for Clang? If its the same, its not a big deal, I just wont be able to include certain headers in the PCH.

**Comment by llvm-beanz** [comment]
DXC's changes to the clang AST structures broke the way that ASTs are serialized for precompiled headers and modules. While we would accept changes to fix these issues and support this feature our team isn't going to prioritize this work ever in DXC.

Our resources are focusing more on getting SM 6.8 done and implementing HLSL support in Clang. Clang's HLSL implementation will support precompiled headers and modules from day 1. We've already done work to ensure that precompiled headers work with HLSL in Clang today.
