### ISSUE TITLE
[Feature Request] Make DXC emit VulkanMemoryModel instead of Logical GLSL450

### ISSUE THREAD

**Issue by kpentaris** [microsoft/DirectXShaderCompiler#5784]
**Is your feature request related to a problem? Please describe.**
We would like to take advantage of the Vulkan Memory Model, for consistency and sanity reasons.

**Describe the solution you'd like**
A compilation flag that would enable the [Vulkan memory model](https://www.khronos.org/blog/vulkan-has-just-become-the-worlds-first-graphics-api-with-a-formal-memory-model.-so-what-is-a-memory-model-and-why-should-i-care)

**Describe alternatives you've considered**
Use GLSL450 but we'd like to be able to reason about the memory ordering of our operations.
There is also the flag `-0config=--upgrade-memory-model` but this would require writing operations in glsl450 and rely on spirv-opt to upgrade them, whereas we'd like to use the proper VMM opcodes which are not necessarily expressible in glsl450.

**Additional context**
N/A

**Comment by sudonatalie** [comment]
Thanks for submitting this issue! This feature isn't likely to be prioritized in the near future, however, if you are able to provide any examples of HLSL that is sub-optimally expressed when going through `OpMemoryModel Logical GLSL450`->`--upgrade-memory-model` that would be helpful to better understand your use case.

**Comment by devshgraphicsprogramming** [comment]
The problem is that we can't use VMM (like atomics, OpLoad and OpStore with acquire/release operands) while DXC still emits GLSL450 for all the rest of the code

**Comment by devshgraphicsprogramming** [comment]
> The problem is that we can't use VMM (like atomics, OpLoad and OpStore with acquire/release operands) while DXC still emits GLSL450 for all the rest of the code

@sudonatalie I have an example! (with BDA and prop 0011 syntax)
https://godbolt.org/z/a9sx4ss68

and still we can't use acquire/release etc  on atomics

**Comment by sudonatalie** [comment]
Thanks for the additional info @devshgraphicsprogramming. We'll keep this on our radar but it's unlikely to be a near future priority.

**Comment by devshgraphicsprogramming** [comment]
> Thanks for the additional info @devshgraphicsprogramming. We'll keep this on our radar but it's unlikely to be a near future priority.

Actually turned out I didn't need this to declare my `OpLoad` for BDA was missing a `[[vk::ext_literal]]` on the intrinsic declaration
