### ISSUE TITLE
Global (non-member) operator overload declarations are allowed but fail to be resolved in HLSL 2021.

### ISSUE THREAD

**Issue by jamiehayes** [microsoft/DirectXShaderCompiler#5792]
**Description**
There is no error when trying to declare a global (non-member) operator overload in HLSL 2021.

**Steps to Reproduce**
Minimal reproduction: https://shader-playground.timjones.io/43640441be664659ae88414a8ad057ff

**Actual Behavior**
Both operator overloads compile, but the global operator only fails and produces an error at the callsite.

**Environment**
- DXC version - 1.7.2308.7
- Host Operating System - Windows 10 21H2

**Comment by llvm-beanz** [comment]
Shader playground took _minutes_ to load for me this morning, so here's an equivalent godbolt link: https://godbolt.org/z/8zPKqjxo5

**Comment by llvm-beanz** [comment]
I think this is a really quick fix, so I'm going to take a stab at it this morning. If it turns out to be bigger than I think I may need to throw it into our backlog.
