### ISSUE TITLE
[SM 6.8] `[NodeArraySize()]` and `[AllowSparseNodes]` should only apply to some record types

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#5810]
**Description**
The `[NodeArraySize()]` and attribute should error if it is applied to non-array node record types, and the `[AllowSparseNodes]` attributes should error if it is applied to array node record types.

See the comment from @tex3d here:
https://github.com/microsoft/DirectXShaderCompiler/pull/5588#discussion_r1341723232

**Steps to Reproduce**
Apply `[NodeArraySize()]` to a `NodeOutput` and observe no error reported.
Apply `[AllowSparseNodes()]` to a `NodeOutputArray` and observe no error reported.

**Environment**
- DXC version: SM 6.8 staging branch
- Host Operating System: Any

**Comment by bob80905** [comment]
Fixed by #5817
