### ISSUE TITLE
Support [UnboundedSparseNodes] on [Empty]NodeOutputArray

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#5811]
**Description**
Support `[UnboundedSparseNodes]` on `[Empty]NodeOutputArray` to update compiler to recent Work Graph spec updates.
This attribute is shorthand for specifying `[AllowSparseNodes]` and `[NodeArraySize((uint)-1)]`.

**Comment by pow2clk** [comment]
Fixed by #5817
