### ISSUE TITLE
[SPIR-V] `-Wundefined-internal` SIGSEGVs the compiler when `-spirv` output

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/DirectXShaderCompiler#5821]
**Description**
When we make an "intentional" mistake of not defining a static member variable we get a SIGSEGV instead of a diagnostic.

DXIL output works just fine

**Steps to Reproduce**
Try to compile this shader, with and without `-spirv`
https://godbolt.org/z/zhEfeqr6d

The example is derived from #5821

**Actual Behavior**
SIGSEGV

**Environment**
- DXC version Whatever trunk godbolt has
- Host Operating System Linux I guess?

**Comment by s-perron** [comment]
This is not good. This seems to work well when the static member is a scalar value (https://godbolt.org/z/91n9dbsbK). That is the behaviour that will be implemented for arrays as well. Inspite of the earlier warnings, we will ultimately fail.

**Comment by s-perron** [comment]
I think this should have been fixed by #5872. Reopen if it is not.
