### ISSUE TITLE
[DX][WHQL] convert fail from dxbc->dxil

### ISSUE THREAD

**Issue by chunhuahong** [microsoft/DirectXShaderCompiler#5836]
**Description**
Converting dxbc to dxil fails when running whql test.
The case is: WGF11Shader5x.exe Index\ConstantBuffers:1
Shader is:
  
![image](https://github.com/microsoft/DirectXShaderCompiler/assets/95601381/89733473-e9b4-4806-bf9a-1909f2549247)

**Steps to Reproduce**
Run above whql testcase and dump dxbc binary or use dxbc disassemble for input, and convert dxbc->dxil using dxilconv.dll.

**Actual Behavior**
crash when converting.

**Environment**
- DXC version: 1.7 - 1.7.0.14006 (main, 69e54e290-dirty)
- Host Operating System: win10

**Comment by pow2clk** [comment]
Probably related to #5897

**Comment by damyanp** [comment]
There's an offline email thread about this, if this reaches more of a conclusion then we can reopen this.
