### ISSUE TITLE
Error when writing to groupshared payload from amplification shader using SV_GroupThreadID

### ISSUE THREAD

**Issue by nathanday98** [microsoft/DirectXShaderCompiler#5838]
**Description**
I'm hitting a compilation error when trying to write to a groupshared payload in an amplification shader when using SV_GroupThreadID to index it. It only errors when using `-Od`. Using `-O1` or above fixes it.

**Steps to Reproduce**
```hlsl
#define AS_THREAD_NUM 5

struct PayloadData
{
    float4 verts[AS_THREAD_NUM][8];
    float4 color[AS_THREAD_NUM];
};

groupshared PayloadData s_payload_data;

[NumThreads(AS_THREAD_NUM, 1, 1)]
void ASMain(in uint3 group_id : SV_GroupID, in uint3 group_thread_id : SV_GroupThreadID)
{
    s_payload_data.verts[group_thread_id.x][0] = float4(0.0, 0.0, 0.0, 1.0);
       
    DispatchMesh(1, 1, 1, s_payload_data);
}
```
`-E ASMain -T as_6_6 -HV 2021 -Od -Zi -Qstrip_reflect`
https://godbolt.org/z/WjKsfs3jr

**Actual Behavior**
Passes compilation (shown with `-O1`): https://godbolt.org/z/qfn33anP3

**Environment**
- DXC version dxcompiler.dll: 1.7 - 1.7.2308.7 (69e54e290); dxil.dll: 1.7(101.7.2308.12)
- Host Operating System Windows 11 Home, 10.0.22621 Build 22621

**Comment by jenatali** [comment]
For the record, I disagree. In the HLSL, the usage is unambiguous. In the DXIL, the usage is also unambiguous if you follow the full GEP chain across multiple instructions. The problem is only that the validator doesn't do that, it sees that there's a group shared GEP from an instruction that isn't a variable.
