### ISSUE TITLE
Some definitions in ExecutionTest.cpp conflict with latest D3D headers

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#5841]
**Description**
ExecutionTest.cpp has some local definitions for WaveMatrix related D3D definitions not yet available in the latest released Windows SDK.  However, these definitions conflict with newer D3D headers which include these definitions.

Either these need to be guarded by some version define logic based on included headers, or they need to be removed, and we need to set up the project to consume headers more directly from [DirectX-Headers](https://github.com/microsoft/DirectX-Headers) or an AgilitySDK nuget package.

The duplicate definitions are:
`D3D12_WAVE_MMA_INPUT_DATATYPE`, `D3D12_WAVE_MMA_DIMENSION`, `D3D12_WAVE_MMA_ACCUM_DATATYPE`, and `D3D12_FEATURE_DATA_WAVE_MMA`.

**Steps to Reproduce**
Try building with newest D3D12 headers from the latest preview AgilitySDK.

**Actual Behavior**
Build break due to multiple definitions.

**Environment**
- DXC version: staging-sm-6.8 branch
- Host Operating System: any Win32

**Comment by damyanp** [comment]
This is moot now as we removed the old wave matrix implementation from main.
