### ISSUE TITLE
[SPIR-V] Creating `lib_6_x` targets don't compile 

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/DirectXShaderCompiler#5854]
**Description**
When creating a linkable shader, such as the following, a compiler error is generated rather then a linkable shader.

```hlsl
RWTexture2D<float4> g_output : register(u0, space0);

int valueTwo();

[numthreads(8, 8, 1)]
[shader("compute")]
void copyCs(uint3 dispatchThreadId : SV_DispatchThreadID)
{
	g_output[dispatchThreadId.xy] = valueTwo();
}
```

**Steps to Reproduce**

Notice the only difference are the command-line arguments

SPIR-V: https://godbolt.org/z/zbzdP4ne1 (doesn't work)
DXIL: https://godbolt.org/z/1q61rErsE (does work)

**Expected behavior**

I'd expect one entrypoint (OpEntryPoint for `copyCs`), and I'd expect one function (`valueTwo`) decorated with `LinkageAttributes` `Import`.

Notice that it's already possible to create an export library as follows: https://godbolt.org/z/9Gbov5W46

**Use-case**

This would be extremely useful for us to deal with at least one of the problems with shader permuations: compilation time of the massive generated shaders.

**Comment by devshgraphicsprogramming** [comment]
> **Description** When creating a linkable shader, such as the following, a compiler error is generated rather then a linkable shader.
> 
> ```hlsl
> RWTexture2D<float4> g_output : register(u0, space0);
> 
> int valueTwo();
> 
> [numthreads(8, 8, 1)]
> [shader("compute")]
> void copyCs(uint3 dispatchThreadId : SV_DispatchThreadID)
> {
> 	g_output[dispatchThreadId.xy] = valueTwo();
> }
> ```
> 
> **Steps to Reproduce**
> 
> Notice the only difference are the command-line arguments
> 
> SPIR-V: https://godbolt.org/z/zbzdP4ne1 (doesn't work) DXIL: https://godbolt.org/z/1q61rErsE (does work)
> 
> **Expected behavior**
> 
> I'd expect one entrypoint (OpEntryPoint for `copyCs`), and I'd expect one function (`valueTwo`) decorated with `LinkageAttributes` `Import`.
> 
> Notice that it's already possible to create an export library as follows: https://godbolt.org/z/9Gbov5W46
> 
> **Use-case**
> 
> This would be extremely useful for us to deal with at least one of the problems with shader permuations: compilation time of the massive generated shaders.

Does SPIR-V linking work all of the sudden?

**Comment by Jasper-Bekkers** [comment]
> Does SPIR-V linking work all of the sudden? (within SPIR-V Tools)

I assume the spirv linker in spirv tools just works, but we have a custom one.

**Comment by devshgraphicsprogramming** [comment]
> > Does SPIR-V linking work all of the sudden? (within SPIR-V Tools)
> 
> I assume the spirv linker in spirv tools just works, but we have a custom one.

I thought that was only for OpenCL, although last I checked was like 3 or 4 years ago.

**Comment by cassiebeckley** [comment]
>                OpCapability MinLod
>                OpCapability FragmentShaderSampleInterlockEXT
>                OpCapability FragmentShaderPixelInterlockEXT
>                OpCapability FragmentShaderShadingRateInterlockEXT
>                OpCapability RayQueryKHR
>                OpCapability Shader
>                OpCapability Linkage
> ```
> 
> overdeclaring for later strip?

@devshgraphicsprogramming Now that SPIRV-Tools opt has a capability trimming pass (so that capabilities which are unneeded after optimization are removed), rather than duplicating the logic for determining which instructions require which capabilities in `dxc` and in `spirv-opt`, we are adding capabilities by default and then removing them `spirv-opt` if they are unneeded.

I believe these should only appear when you pass `-fcgl` to `dxc`; in all other cases the capability trimming pass should be run.

**Comment by sudonatalie** [comment]
Unfortunately the SPIR-V backend in DXC does not currently support linking, and the `lib_*` targets are only really used for raytracing shaders.

**Comment by sudonatalie** [comment]
We do have an old bug open tracking this actually (#2633), so closing this as a duplicate, but there are not currently any plans for implementing this support.

**Comment by Jasper-Bekkers** [comment]
> Unfortunately the SPIR-V backend in DXC does not currently support linking, and the `lib_*` targets are only really used for raytracing shaders.

Yeah, this isn't so much about implementing a linker or using the linker in spirv-tools though that would be needed for feature parity. This is an issue specific to generating `Import` directives for files using lib files. Note shaders with `Export` already work.

**Comment by Jasper-Bekkers** [comment]
> We do have an old bug open tracking this actually (https://github.com/microsoft/DirectXShaderCompiler/issues/2633), so closing this as a duplicate, but there are not currently any plans for implementing this support.

It's unfortunate that this isn't planned at the moment, because it's one of the ways with which to make shader permutation hell quite a bit more bearable for game developers (during production).

**Comment by sudonatalie** [comment]
Thanks for the additional info! We'll take this into account when prioritizing future enhancements, but we just don't want to give any unrealistic expectations about when it's likely to be implemented.
