### ISSUE TITLE
Constexpr functions

### ISSUE THREAD

**Issue by atkurtul** [microsoft/DirectXShaderCompiler#5868]
**Is your feature request related to a problem? Please describe.**
We would like to have builtin bitcasts tagged as constexpr.

**Describe the solution you'd like**
Simply tag `as[u]int[16], asfloat, asdouble` as constexpr so that following is possible
```cpp
template<> 
struct num_traits<float32_t>
{
    static const float32_t QUIET_NAN = asfloat(0x7FC00000);
    static const float32_t SIGNALING_NAN = asfloat(0x7FC00001);
};

template<> 
struct num_traits<float64_t>
{
    static const float64_t QUIET_NAN = asdouble(0, 0x7FF80000);
    static const float64_t SIGNALING_NAN = asdouble(1, 0x7FF00000);
};
```

**Describe alternatives you've considered**
I dont think it's possible have alternatives to bitcast other than the intrinsics compiler give us.

**Additional context**
This feature is needed to implement a constexpr numeric_limits

**Comment by llvm-beanz** [comment]
There are two relevant language features currently being tracked:

* constexpr/consteval - https://github.com/microsoft/hlsl-specs/issues/74
* modern numeric constants - https://github.com/microsoft/hlsl-specs/blob/main/proposals/0003-numeric-constants.md

Until we address the first request we can't really support this as written, although the second request (which is likely to happen sooner) is probably what you actually want.
