### ISSUE TITLE
Nuget Package does not integrate with VS 2022 ?

### ISSUE THREAD

**Issue by weltkante** [microsoft/DirectXShaderCompiler#5869]
**Description**
I've added the nuget package to my VS 2022 C++ project and I can see it having added a new property page to the solution settings, but I cannot figure out how to compile my build-time HLSL code with shader model 6.6 - the dropdowns are not updated and if I add the corresponding command line switch manually in the property page it seems to be still calling the dxc from the sdk not from the nuget package.

I looked at what the nuget package provides and its targets file does provide VS integration and updates the search path, so I believe the VS integration of the nuget package is broken and does not work with VS 2022 ?

**Steps to Reproduce**
* create a C++ project with HLSL files using shader model 6.6 features
* add the nuget package to the project
* try to compile the HLSL files

**Actual Behavior**
* property pages do not offer entries for newer shader models
* wrong compiler exe is used and fails to compile the HLSL code

**Environment**
- DXC version: `dxcompiler.dll: 1.7 - 1.7.2308.7 (69e54e290); dxil.dll: 1.7(101.7.2308.12)`
- NuGet Package: `Microsoft.Direct3D.DXC` version `1.7.2308.12`
- Host Operating System: `win10 22H2 19045.3570`
- Visual Studio: 2022 preview 3 (17.8.0)

**Comment by hekota** [comment]
Hello,

I have Visual Studio version 17.7.5 and I see shader model 6.6 in the dropdown list:

![image](https://github.com/microsoft/DirectXShaderCompiler/assets/22403107/da29cec6-2ab8-4405-89ec-aee143afaeea)

Did you mean shader model 6.7? If so, there is an issue filed for this here: 
https://developercommunity.visualstudio.com/t/HLSL-FXCDXC-dialog-should-expose-Shader/10147895

I will try to reach the VS team for an update.

**Comment by hekota** [comment]
Adding @jgoshi

**Comment by weltkante** [comment]
> Did you mean shader model 6.7? If so, there is an issue filed for this here:

nope, trying to use 6.6 for the pack/unpack instruction support (but of course ideally the nuget package should support selecting any of the newer shader models it supports)

With or without the nuget package I only get shader model up to 6.5 with VS 17.8, and even with that it doesn't use the DXC supplied by the nuget package when compiling, so something definitely is wrong.

<details><summary>screenshot</summary>

![grafik](https://github.com/microsoft/DirectXShaderCompiler/assets/5845814/6e573b42-463c-4a4f-be82-f7946eec8970)

</details>

**Comment by hekota** [comment]
Sorry, I can't repro this on on my end. I have created a new C++ console application, installed Microsoft.Direct3D.DXC nuget package version 1.7.2308.12 via Manage NuGet Packages menu option on the project, added a shader file, and in its properies under HLSL Compiler/General I have Shader Model 6.6 (/6_6) option in the drop down list.

**Comment by weltkante** [comment]
> Sorry, I can't repro this on on my end. I have created a new C++ console application, installed Microsoft.Direct3D.DXC nuget package version 1.7.2308.12 via Manage NuGet Packages menu option on the project, added a shader file, and in its properies under HLSL Compiler/General I have Shader Model 6.6 (/6_6) option in the drop down list.

Did you verify that you are actually using the DXC from the nuget package though?

Expanding on what I said above, if you use "10.0 (latest)" as target version while having the Windows 11 SDK installed (I didn't when first reporting) it shows up 6.6 because you are actually using the Windows 11 DXC which does have 6.6 shader support (but not newer). Its still not using the binaries from the nuget package when building and if you target any specific Windows 10 SDK it stops being available in the dropdown and will fail to compile the HLSL.

While I can use this as a workaround for my specific problem of getting access to pack/unpack instructions (by just using the Win11 DXC), the issue remains that VS 2022 doesn't use the nuget package during the build process and in the property dialog, even though there's corresponding targets files included in the package they don't seem to work properly.

**Comment by hekota** [comment]
Yes, the shader that I included in my VS solution is using `pack_u8` intrinsics and `uint8_t4_packed` datatype. VS compiles with no errors when building the whole solution.

I suggest you try the same. Create a new simple app, install the nuget package via Manage NuGet Packages, add your shader to the solution, set the shader model in its properties and see if it compiles. Then compare to your original solution and try to see if you can find where is the problem.

**Comment by hekota** [comment]
Compiling the shader from code also works for me:

```
#include <iostream>
#include <vector>

#include <windows.h>
#include <atlbase.h>

#include "dxcapi.h"

std::string shaderText = std::string("\r\n\
[NumThreads(4,4,1)]\r\n\
void main() {\r\n\
  uint32_t4 a = {1,2,3,4};\r\n\
  uint8_t4_packed b = pack_u8(a);\r\n\
}");

int main()
{
    CComPtr<IDxcUtils> pUtils;
    DxcCreateInstance(CLSID_DxcUtils, IID_PPV_ARGS(&pUtils));
    
    CComPtr<IDxcBlobEncoding> pSource;
    pUtils->CreateBlob(shaderText.data(), (UINT32)shaderText.size(), CP_UTF8, &pSource);

    std::vector<LPCWSTR> arguments;
    arguments.push_back(L"-E");
    arguments.push_back(L"main");

    arguments.push_back(L"-T");
    arguments.push_back(L"cs_6_6");

    DxcBuffer sourceBuffer;
    sourceBuffer.Ptr = pSource->GetBufferPointer();
    sourceBuffer.Size = pSource->GetBufferSize();
    sourceBuffer.Encoding = 0;

    CComPtr<IDxcCompiler3> pCompiler = nullptr;
    DxcCreateInstance(CLSID_DxcCompiler, IID_PPV_ARGS(&pCompiler));

    CComPtr<IDxcResult> pCompileResult;
    HRESULT hr = pCompiler->Compile(&sourceBuffer, arguments.data(), (UINT32)arguments.size(), nullptr, IID_PPV_ARGS(&pCompileResult));

    CComPtr<IDxcBlobUtf8> pErrors;
    pCompileResult->GetOutput(DXC_OUT_ERRORS, IID_PPV_ARGS(&pErrors), nullptr);
    if (pErrors && pErrors->GetStringLength() > 0) {
      std::cout << (char*)pErrors->GetBufferPointer();
    }
    else {
      std::cout << "Compilation completed.";
    }
}

```

**Comment by weltkante** [comment]
Yes, compiling from code does work, the VS integration does not.

**Comment by hekota** [comment]
I still can't repro this on my end. I see 6.6 in the drop down in shader properties when using the latest nuget package. I have the shader code above in separate `shader.hlsl` file, added the solution, and the shader compiles when the whole solution is built.I  made an intentional syntax error in the code to verify it and I see it reported in the build output:

```
Build started...
1>------ Build started: Project: ConsoleApplication1, Configuration: Debug x64 ------
1>shader.hlsl(4,35): error G65037BDE: expected ';' at end of declaration
1>    uint8_t4_packed b = pack_u8(a)
1>                                  ^
1>                                  ;
1>
1>Done building project "ConsoleApplication1.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by weltkante** [comment]
Ok, so I don't know what I did that fixed the problem of VS not using the DXC from the nuget package, it does now. I still don't see 6.6 in the dropdown on machines that don't have the Win11 SDK installed (or build against a Win10 SDK), but I now can enter 6.6 manually and it is using the nuget package DXC. **Previously when I did that I was getting an error from the Win10 SDK DXC that it didn't understand shader model 6.6** (the path to the exe was in the error output but I can't repro that anymore). No idea why it started working now, I had changed my VS configuration a few times in between, since when you said you were seeing the entry I tried to figure out what I was missing in my setup.

The following screenshot is how it looks without a Win11 SDK or when you pick a Win10 SDK to build against.

![grafik](https://github.com/microsoft/DirectXShaderCompiler/assets/5845814/5baf01b3-cce9-4780-800d-296494cbb0c1)

If you have a Win11 SDK installed and use the default "Windows SDK Version = 10.0 (latest installed version)" on the general project settings tab then it will pick the Win11 SDK (Win11 still uses 10 as version number, anything above 22000 is Win11). If you explicitly pick a Win10 SDK version or no SDK >22000 is installed the 6.6 entry is missing. (You have to close and reopen the property settings dialog when you change the SDK.)

![grafik](https://github.com/microsoft/DirectXShaderCompiler/assets/5845814/07ad6bad-e7a3-4ed9-8fea-cccdf85a67ea)

Its a bit unfortunate that I can't figure out what I did to fix the problem of the wrong DXC getting picked up by VS, so feel free to close the issue if adding dropdown entries can't be done from the nuget package props/targets file. **Manually specifying the 6.6 is certainly acceptable when it works.**

**Comment by hekota** [comment]
I am glad to hear the issue is fixed. The VS is determining the drop-down values from the version of the dxcompiler.dll, and yes, most likely they are using the dll from Windows SDK to do so. The nuget package target/props file copies the dxcompiler.dll right next to the built binaries, so the compiler from nuget package is used in runtime.
