### ISSUE TITLE
[SM 6.8] Array of WaveMatrix trips assert

### ISSUE THREAD

**Issue by VladM1076** [microsoft/DirectXShaderCompiler#5892]
**Description**
When I try to use an array of WaveMatrix objects in my shader, I hit an assert.
The issue is preset at the top of staging-sm-6.8 branch and in the June DXC preview release.

**Steps to Reproduce**
[WaveMatrix-Array-Bug-Repro.hlsl.txt](https://github.com/microsoft/DirectXShaderCompiler/files/13034558/WaveMatrix-Array-Bug-Repro.hlsl.txt)
1) Download attached file and remove the .txt file extension (wouldn't let me upload an HLSL file)
2) Build DXC out of staging-sm-6.8
3) Do “dxc.exe -T cs_6_8 -E cs_main -enable-16bit-types WaveMatrix-Array-Bug-Repro.hlsl” to compile and you should hit an Internal compiler error
4) Run DXC with debugger to see the assert.

**Actual Behavior**
Assert at DxilWaveMatrix.cpp:47: DXASSERT_NOMSG(isa\<AllocaInst\>(waveMatPtr));

**Environment**
- DXC version 1.8 - 1.8.2306.4 (3e105849c) | 1.8 - 1.7.0.4222 (staging-sm-6.8, e071aae0a)
- Windows 11

**Comment by pow2clk** [comment]
Hi @VladM1076!

Thanks for pointing this out. We're not supporting arrays of wave matrices for now. If there is an interesting use case you have in mind for this, please create a feature request. To resolve this issue, we're going to produce an error when arrays of wave matrices are used.

**Comment by pow2clk** [comment]
Fixed by #5920. Will discuss future possibilities in the other bug
