### ISSUE TITLE
SM 6.8 RDAT has unused shader data that should be removed

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#5900]
**Description**
Shader data in `RuntimeDataFunctionInfo2` ended up being unused and needs to be removed before release.

Not only is this info not completely filled in (ViewID/Dependency maps, and more), but it doesn't contain everything that would be required to replace PSV0, I/O signature, and root signature parts for ordinary shader stages either.

It should not be left in for SM 6.8 release, otherwise it will have to be supported going forward.

We need to retain `MinimumExpectedWaveLaneCount`, `MaximumExpectedWaveLaneCount`, and `ShaderFlags`.  However, `DxilShaderFlags` needs to be reduced to the one flag that's still used: `NodeProgramEntry`.

**Comment by tex3d** [comment]
This comment is just to capture some related thoughts for future reference.

One thought was that perhaps `DxilShaderFlags` could be replaced with a new `NodeShaderFuncAttrib` kind for `NodeShaderFlags` starting with this one flag `NodeProgramEntry`.

However, `ShaderFlags` currently occupies the 2-byte gap between `(Minimum/Maximum)ExpectedWaveLaneCount` and the `NodeShaderInfo`, so unless something changes about those as well, there's nothing to gain by moving node shader flags to a new attribute.

Another thought: if valid values for `(Minimum/Maximum)ExpectedWaveLaneCount` were enum-encoded and stuffed into a smaller set of bits (3 bits each would be enough), they could leave even more room for shader flags, if combined with that field.  However, the `ShaderFlags` can always be extended with a `ShaderFlags2` field in a newer version of the `RuntimeDataFunctionInfo` record if necessary.

**Comment by pow2clk** [comment]
Fixed by #5943. Closing as discussed
