### ISSUE TITLE
[SPIR-V] Internal shader compilation error with ResourceDescriptorHeap

### ISSUE THREAD

**Issue by DanilAndreev** [microsoft/DirectXShaderCompiler#5913]
**Description**
DXC Shader Compiler crashes with internal error when compiling shader code with ResourceDescriptorHeap to SPIR-V.

**Steps to Reproduce**
_bindlessCompute.hlsl_
```hlsl
[numthreads(256,1,1)]
void main(uint3 DTid: SV_DispatchThreadID) {
    StructuredBuffer<uint> src = ResourceDescriptorHeap[0];
    RWStructuredBuffer<uint> dst = ResourceDescriptorHeap[1];
    dst[DTid.x] = src[DTid.x];
}
```
_Command:_
```powershell
dxc.exe -spirv -T cs_6_7 -E main -O0 bindlessCompute.hlsl -Fo compiled.spirv
```
_Error:_
```
Internal compiler error: access violation. Attempted to read from address 0x0000000000000000
```

**Actual Behavior**
As I know SPIR-V does not support ```ResourceDescriptorHeap``` and dynamic descriptor casting for now. But compiler crashes trying to compile code that contains ```ResourceDescriptorHeap``` instead of printing validation error message.

**Environment**
- DXC version  1.7 - 1.7.0.4004
- Host Operating System Windows 11

**Comment by llvm-beanz** [comment]
[Godbolt link](https://godbolt.org/z/5M4dv6K6j)

**Comment by sudonatalie** [comment]
PR #5956 is up for fixing the crash, but I wanted to mention that we are currently working on prioritizing the SPIR-V backend's missing Shader Model 6.6 features. We can't make any guarantees about timeline, but this is on our roadmap.
