### ISSUE TITLE
[SPIR-V] Using Namespace not implemented

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/DirectXShaderCompiler#5938]
**Description**
When compiling with SPIR-V output we cannot use namespaces.

This is probably connected to https://github.com/microsoft/DirectXShaderCompiler/issues/5751

**Steps to Reproduce**
Switch between DXIL out and SPIR-V with ` -spirv`
https://godbolt.org/z/6q9vq7Yhb

**Actual Behavior**
```
<source>:23:25: error: decl type UsingDirective unimplemented
using namespace custom::v1;
```

**Environment**
- DXC version: https://github.com/microsoft/DirectXShaderCompiler/commit/3ac44bc1ffaaaa45784d57e59a6ce8fe89f87298
- Host Operating System: Windows, Linux, doesn't matter

**Comment by sudonatalie** [comment]
Thanks for reporting. Yes, namespace using directives are are not yet supported by the SPIR-V backend.
