### ISSUE TITLE
[SPIR-V] template argument not recognized as a constant

### ISSUE THREAD

**Issue by atkurtul** [microsoft/DirectXShaderCompiler#5947]
**Description**
Declaring an vk::ext_execution_mode with a template argument fails

**Steps to Reproduce**
https://godbolt.org/z/x6hsKvTof

**Actual Behavior**
```
<source>:19:9: error: argument should be constant integer
        vk::ext_execution_mode(4460, width);
        ^

Compiler returned: 5
```
**Environment**
- DXC version: libdxcompiler.so: 1.7(dev;1-df0287c2)
- Host Operating System: godbolt

**Comment by sudonatalie** [comment]
@cassiebeckley I think you were just investigating a similar issue, can you take a look?

**Comment by cassiebeckley** [comment]
I've created a PR to fix this issue. Just so you're aware, we've added new syntax for execution modes, documented in https://github.com/microsoft/hlsl-specs/blob/main/proposals/0011-inline-spirv.md#execution-modes.

You can see an example of usage in https://github.com/microsoft/DirectXShaderCompiler/blob/main/tools/clang/test/CodeGenSPIRV/spv.inline.executionmode.hlsl.
