### ISSUE TITLE
[SPIR-V] Declaring a `static const` inside a struct used as a Push Constant creates OpLoad codegen errors

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/DirectXShaderCompiler#6006]
**Description**
```cpp
struct PushConstantData
{
	const static uint32_t MaxPossibleElementCount = 1 << 20;

	uint64_t inputAddress;
	uint64_t outputAddress;
	uint32_t dataElementCount;
};

[[vk::push_constant]] PushConstantData pushConstants;
```

**Steps to Reproduce**
I had to add a side effect (`RawBufferStore`) so the call tree wouldn't be optimized out before SPIR-V codegen.

[Here's my Godbolt](https://godbolt.devsh.eu/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AJaC2qSX1kBPAMqN0AYVS0AriwYhJXUg4AyeAyYAHLuAEaYxCAAbADspAAOqAqEtgzObh5ePkkpNgIBQaEsEVFxFphW%2BQxCBEzEBBnunt4VVWm19QSFIeGRMfEKdQ1NWa1DXT3FpQMAlBaorsTI7BwA9GsA1GgsCXSY6JsA7oRImwC0CnvEAG4XABIAapsATBovqhcAKtsKAPrRP6xC4ALQSxAujCYYXo5y40TChHOBAAnglMAoLlQbgBrc6uJSXUQGYjnAwoxYEC4AdQYqHOyAApC8AELMllcLjnTCqAiMFICTHnWn0pms9lcABe3N5/LSQpF52ADFclzqNmQ5yotFQTAI50ChCxVxuyPqwEw%2BsYN0ZAGYACI3Vy0HGGLgAOltxoSpqwYVcwDt9oUi2WmG9vsw/sDDqILkZGgAggnE8w2FcmCtNgwYSnGbE2Um0xiEpnwyYzHmC3mXl7ogBOTbMl452hrf10GwMNYVtvIBIJP47UsEd295tV%2B2TmterhNl4tmHt1ydwI90x9gdD1C7PVrQIEYiBFLIBRjidJ5mz%2BeLtsd2hd9dmNb9wfDvcsPVH1RjjcX5O1psc7Nq2y6rt2vYvlu74EGsNyYNYJC/pWC4zpskjRDeoH3o%2BkGvtuu6wfBiHEMhtD/sWGZZq2VaFqmrAlmWmzjpe1ZJqi6JYFQzFiNx2q6gQ8J/AQdp0RxByYHxOp6ps/F6raLzCaJKbiVxmzoIsMLhnJBDRJISm2nRKlohJ3HEUQxB2o4YSoC4pCSHa2CbDZLgOYZqmSZs5kkFZLnmLajnObZtABe5Jlqd5lm2tZwWkC8gV%2BfFYWcZ5kW%2BbFXAJcFmWGXm7HhalCEWVZB5CQQ9mBaVgIEG5LIeWZRU%2BdFVXCaQoVOS1BChXVBUNSRJWCGVcWVYN1VJT1KV9cVzWja1OUdbNgnKflk1eY1UWOAeCmtW5C1dYpNWifVa39TN%2B2te1mxbQd3XHWlZ3beVSV7Y9413etA3neV81XYIj05WJvUndNm2CHpO0jbp%2BmHclpnA01oNQxdkPg11R1A/diOo8Ntp7ajb0Yx9Z3Yz9B6owDeWJu9p2OCui0Vbjmx04J1W1dTIPM0Nl2c9Vt2EzTPOtc9TOdQTq2Y4L32BZLFMrXDEvXRDjPM49bP8xzivldzmt8%2BLRO05rONOSrB1i/L%2Bsm3N0ua7LVPqwjzPY7tItg9Dat6wLZPQ211uu8Juvm57ftPb7SMEGbEUW17VvK9HS25ZecuRzTOlDc7qes%2BjHsgxnyOM7naOw8nOfSSzQuBQXEeFSnpdDT9Be2%2BzCM6Y9DNOS3B3u4HJcCa3l0d/7Wfd83pet8LA/h0Pxcj73B2kPXo8HY39sbTpTsV6XqNd9Pq%2Bb97/d74PRfVz3erY%2BPh%2BT8fU0z2f3sLwJ5PLcmrFTq/aFcI2IFLjha54dBO4RxrE/IePAP5xyoUTvRdMpZqK5lYnRSisDyx/gQWhAAHBoLCP8VwPj/huKCb5AEfi/GAsi/5jogO/OlOy6FSDoSyq5VQ29PJULATQ8wdDNiXT8pIVQAc1JsNUBw%2Bh0hXiMNoHw8amxKGkOEdFPy9DbSiIkbaZhU9WFyJEdwpRqj%2BEaO4kI7RyjxGMz8mo6RsjQHyJirQl4KizHBQ%2BCwwxWiFGxVeLoxxLgPgCM0dY7R9jTFOUSqocaz8rHULOkNLhztOp8JcZsIx0TqqiK8XtMqfC/GuICSk1qXDhbxLCaJGRQNkmIxiSYuJi01GJPKZ1JR6Tfply6vo6%2BSS3EVNSTo4JzSyoWJKZE9heTyqeIYYzUW6j2n1PpmMy6kzskdNyV0/JQTCmLQ%2BOEhOdtVozK%2Bmk8ZL1O5TImnDPZrcuHzL%2BscxZ5y54FMhqrYphlSm7M6YbHp1Svq1IMUsqJiMLkmKud8tppzBHvOufkkx6yQWWLKRC/ZYyvmvROUMmxHygnApRbchFFy1mPNNs8tk2y0WfWxrElGbtUXwuWXHA5wKt6gtJcTb2DyJnBykYMml/y6WfMpf7albzaXB0adw/lrScXCrDqKmFqMBkvOZVjVlQSvn40FWchF5LMXit8b8vZWr6Gyuhps5SJLuXDINrMsRztJYJL1Z0yW9LQ6ZKZeamxjq2XGyKXCoV/yPVVOdbzdV4Lln%2BqaZLNRkq/UNJ6cLCNRLXkatDTGlVgbhLOPtcm2Z2rY4bNdb6i1Hr8W5paSa3KZqC3uo%2Bda0OTy6kOureGzWWTM3RshaMsRcbm0JsVZbUZAaS2PR%2BdMht7bRXa3bZG1thaPnQtrTdHtbqrJ9sNQ4r17aM0jqzYinN66vq6q3W2ndhr53pqJREpd0VHasprSWxl9bt3krEROsOLbD0zpFZ6l2r7F2VuXbygde65XBv8Ue8lQLQ7AajR%2B6VsbIPQ3lSyRNIawPKrXd%2BtVD7UOrKbcHA9YLQMwYNb069Z6tmAz/dFAuBz0611ZiBnJ/zqOXI3gJF10GbHMc7axvULqfVJqY3RqF6GC7DoI4xi1zGIP5yExK6dnHZMyp4y0xDyHCMKbY901NMnNNnqw5JxTczlNlXw4q5jxb26ybLcSijAmDOz3ybeyzDmaoMb%2BfZ%2BS9zn3KaeRxqyE8DkXxc5yhVl7HABb5TpzzAr9Maei/2ppE8p3vri4iudUXYVcso%2BFxeOHDmyVy%2BHNz5SIu7oKy50zYXSsnoyyi8jxlstrxvSJy%2BdqUv%2Bcvk6jLjK/NUc61%2BprwkQtIbM/1wD5W74xfkx1x%2BrLpPOcm3J9rfXZvCd6YN1p/GUMedg9phbYdN3ifc6l4jB9VtFd6zl87q71uX2s8/ac79LyATeNgu8uDcIEPwjBfcggjwMBPGeBA/4rybHQZhb%2B73wJPk3EQwi5DIEAS9C8G8TAtzEAxKGFYChGQAFZHB48cDsFgAgEfxSgcdVsIAQC9mp0l36CRXAEAMrZtSVOacbjp4VzYlJGfM5EtslMQxiCuGsJsZQBIEDOAB3UQQ9o9RMFoimbYgoqQTA1N%2Bx6mwACyTBVDKGSCkLS2B6BsEEM4VwggmwOiAlZKybwHtJgw9DBnTPEzoHQBjhQOPtnO%2BEjzpnfP3ee4xD7uimuDrqQVybzAZvGiLEEA92IU5BdJjQDLzY6u8DIAj/76kJAcTAGIIsBIQg8CSnDEGV4uPoiO%2BTLjtkDfcTU8ZwoBA24ZeGBErjqcPfxeS%2BlxMOXCvNit6l6rrvYfKZ45ZCqFgBAEAY6YOgBQEB8/EEL8X1wpfy%2BYHnvPWYeO36JhuKgPAhxPyBAgH2r0ABJe0mwQCbCEI8P49o8AZgIMgBAXxF%2BYGX/fofmgonPWHgNxBAPfu6DYmPoPrLgQGeOgNHqbowPHpbgQEAS/PWAmPWBjgQEsAwHXtgc3iAAAEpMBHAsiuBUBUCRC1AkCYD/rtqOQQAaCqBYDL4RCSQsiJj2iOAaAABi/B2Arg9kuOh%2BguyeHA8wtAnAuOvAngHAWgpAqAnA9wfgQgfgmeWOletYPApABAmgUh8wOIIAtotonoZhlhVhVh0Q%2BgnAkg8hhhyhnAvACgIAGg%2Bhhh8wcAsASAw4%2BwZAFAEA/h9AUQ6AqgyAfw2%2Bwu/%2BLApAWANw2emAjweAmARwAA8uiAoXoTQA%2BJEG4RAGEE4YiMwMQCiJwHoSUfUCiOkWENoEVBUbwMTigekQwLQOUYobwH6AGI4GIKYI0fEbHoYMAOIJ0fEXgBjtYHgPBG4WMTyAhEzqsHoQeJUE4bQHgGEMQNUc4FgE4aAiwI0fMNqEwMAAoCkWkZkYwAMfwIICIGIOwFIDIIIIoCoOoGMboD4AYEYBzmYPoBsW4ZAPMKgAkNULMZcNcHcOcE8K8O8J8OcD8KeACECKCOCJCMwFpHCAiEiOJEKNiHiASJgESGIPUGSEwBSEzjSHSAyOyBKFyDyHyADvKJSaKDSayFKDKAyQKADsyUqCqGqHqNnlqKXAaAwEaFqCaGaMQBaFaAwDaA6E6C6G6J6BGOcN0TGMGNoSqWqUGHGLQLwKgPBMQEeFgACRAPMJYEVGkPYAwE4C4M0HoP4IEL0CUP0DkMkKkAIKMJ4G6XkGkFMH0FED4BaVMQIJ0CMHaVkEGZUJaaGcMN0E6dMK6RYHGV6XoBMA0P6S6YGeadoRINIbIY4WMSoRwJsPaAABqOCyTF4sBMwJAxGsCbAQC4CEAkDzi2hcCzC8AGGdGzDGGmHmHWGDmWG2EyEcAOGkAKFKHFmuHuGeE9mkA%2BGIAgC85M7kCUAhGRDBAMScDlmVlUDVm1n1ksC8AHAtnGl6A3HCDEgPHSCXkvFqBOEfGkBHBbEJCHF2EcByETlOHFnpGB4UmoDcS7lVk7iHmHixGNnOC7ABFtkdldleF9lmEWFDnWEfnjmTn6kuEWCzndlaC9kfkvCFlTlYW4VGGkCGlcleBAA%3D%3D%3D)

**Actual Behavior**
The presence of a `const static` member inside a struct causes crashes during SPIR-V compilation.

**Environment**
- DXC version Latest
- Host Operating System Windows

**Comment by sudonatalie** [comment]
@keenuts Can you take a look into this?
