### ISSUE TITLE
[SPIR-V] Compiler error thrown when variable decorated SV_CullPrimitive is bool

### ISSUE THREAD

**Issue by godlikepanos** [microsoft/DirectXShaderCompiler#6042]
**Description**
In mesh shaders variables decorated with SV_CullPrimitive are supposed to be of bool type. Unfortunately the SPIR-V backend doesn't compile when it's bool but compiles if it's int. HLSL mandates that this SV_CullPrimitive should be bool. An example error thrown by DXC:

```
fatal error: generated SPIR-V is invalid: OpAccessChain result type (OpTypeBool) does not match the type that results from indexing into the base <id> (OpTypeInt).
  %62 = OpAccessChain %_ptr_Output_bool %5 %53
```

**Steps to Reproduce**
Simple mesh shader reproducer: 

```
struct MeshletPrimitiveOut
{
	bool m_cullPrimitive : SV_CULLPRIMITIVE; // Compiles if it's int
};

struct VertOut
{
    float4 m_svPosition : SV_POSITION;
};

StructuredBuffer<float4> g_pos;
StructuredBuffer<uint3> g_indices;

[numthreads(64, 1, 1)] [outputtopology("triangle")]
void main(uint svGroupIndex : SV_GROUPINDEX, 
    out vertices VertOut verts[64], 
    out indices uint3 indices[64], 
    out primitives MeshletPrimitiveOut primitives[64])
{
    SetMeshOutputCounts(64, 64);

    verts[svGroupIndex].m_svPosition = g_pos[svGroupIndex];
    indices[svGroupIndex] = g_indices[svGroupIndex];
    primitives[svGroupIndex].m_cullPrimitive = (svGroupIndex & 1u);
}
```

Compiled using: `-T ms_6_6 -E main -spirv -fspv-target-env=universal1.5`

**Actual Behavior**
No compiler failures if SV_CullPrimitive variables are bool.

**Environment**
- DXC version: Trunk 92e96cc3c74a7d0839c0af236883a43b1c939f12
- Host Operating System: Windows 11 and Linux

**Comment by sudonatalie** [comment]
@s-perron Can you take a look at this?
