### ISSUE TITLE
Slow PCF shader performance with dxc vs. fxc

### ISSUE THREAD

**Issue by TheRealMJP** [Microsoft/DirectXShaderCompiler#607]
Hello,

Now that I have the shader from issue #604 compiling, I've noticed that the performance of the DXIL version is much worse than when the same shader is compiled to DXBC. When testing with the experimental branch of [this project](https://github.com/TheRealMJP/DeferredTexturing), I'm getting about 20.40 milliseconds to complete the forward path, vs about 3.20ms when running the DXBC version. This was measured on an Nvidia GTX 1070 running driver 384.94.

You can compile and run the project yourself if you'd like, or if you'd like to look at the compiler output I've attached the pre-processed code, compiled DXBC, and compiled DXIL for the main pixel shader:

[Mesh_PP.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/1262512/Mesh_PP.txt)
[Mesh_DXBC.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/1262513/Mesh_DXBC.txt)
[Mesh_DXIL.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/1262514/Mesh_DXIL.txt)

I had a quick look myself through the DXIL, and I didn't see anything immediately bad. I was initially concerned that perhaps the looks in the PCF kernel hadn't been unrolled, but it looks like that was handled properly.

Thanks in advance, and please let me know if I can provide any additional information (such as PIX captures, or pre-compiled binaries).

**Comment by python3kgae** [comment]
Thanks for the feedback.
We'll look into this.

**Comment by python3kgae** [comment]
Looks like some dynamic indexing failed to propagate to cbuffer indexing.
Trying to find fix for it.

**Comment by python3kgae** [comment]
Could you try https://github.com/Microsoft/DirectXShaderCompiler/pull/611
It removed some dynamic indexing, but not all of them.

Thanks
Xiang

**Comment by TheRealMJP** [comment]
Hi Xiang,

Thank you for looking into this! With your change + the latest Nvidia driver (385.41), I'm now seeing the DXIL version take 3.12ms, while the DXBC version takes 3.05ms. On an unrelated node, dxc also compiles the shader much more quickly than fxc, which is great!

Thank you again for the assistance!

-Matt

**Comment by python3kgae** [comment]
You're welcome. Your feedback is very important to making dxc better.

Xiang
