### ISSUE TITLE
[SPIR-V] Add test coverage of SPIR-V gen via API

### ISSUE THREAD

**Issue by sudonatalie** [microsoft/DirectXShaderCompiler#6076]
We should consider adding specific test coverage for compiling to SPIR-V using the library API in addition to the command line interface.

**Comment by Keenuts** [comment]
There are 2 unit tests using the DXC API to build SPIR-V in `tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp`.
This can be closed.
