### ISSUE TITLE
Conversion operators do not work

### ISSUE THREAD

**Issue by KStocky** [microsoft/DirectXShaderCompiler#6081]
**Description**

Conversion operators will compile. However they are never invoked. Trying to cast an object of struct type will just result in casting the first member of that struct object to the type requested. This is likely the true root cause of this other bug I logged recently https://github.com/microsoft/DirectXShaderCompiler/issues/6063. Empty structs with conversion operators likely do not compile because when you try to invoke the cast, it tries to cast the first member and of course there are no members to cast.

**Steps to Reproduce**
https://shader-playground.timjones.io/0ae2aa20572d93ac03ab1952921863e2
This shows that even though my conversion operator is defined to return the result of 2 + 2, at O3, the compiler will instead see that the first member of my object is 0 and will therefore optimize away the write to the buffer

https://shader-playground.timjones.io/e88df0cc3580b18d58a39ab7e4ffb2b0
In this link I have set the first member of my object to be 4, and now the code to write to the buffer is generated

https://shader-playground.timjones.io/a0add4ceefbc5da3d9412a29e88d0356
Changing my conversion operator to now return 5, still continues to generate the code for writing to the buffer, even though it should only do that if the conversion operator returns 4.

**Actual Behavior**
Conversion operators compile but do not actually work. Casting simply casts the first member of the object.

**Expected Behavior**
I would expect conversion operators to either not compile or to actually work. I would prefer the latter.

**Environment**
- DXC version 1.7.2308.12
- Host Operating System Windows 10 Pro 22H2

**Comment by llvm-beanz** [comment]
This code pattern is correct C++, but we're crashing in. A compiler explorer repro is here: https://cpp.godbolt.org/z/E5Yxj5qYv

The issue is likely caused by the way HLSL overrides the code generation for `static` and global variables. We can probably fix this instance, but I think we're going to need to think about changing the language in the future to avoid these kinds of collisions.
