### ISSUE TITLE
push constant will be packed into $Globals Variable depend on write order

### ISSUE THREAD

**Issue by yangfengzzz** [microsoft/DirectXShaderCompiler#6098]
<img width="388" alt="截屏2023-12-07 16 34 40" src="https://github.com/microsoft/DirectXShaderCompiler/assets/5378042/963772c6-ed7f-48cc-9076-9478631ec33d">

will only have Globals Varibable but no Push constant

<img width="410" alt="截屏2023-12-07 16 34 28" src="https://github.com/microsoft/DirectXShaderCompiler/assets/5378042/b446395c-3c3c-41f4-af23-cda41f5d8f45">

 Push constant sitll will be packed into $Global but still can use push constant to upload data

**Comment by sudonatalie** [comment]
If possible, please provide detailed steps to reproduce this issue, including complete sample shader code, the command used to compile, and the expected vs. actual results. You may also consider using the following issue template:

```
**Description**
<!--- Please provide a few sentences describing the issue you encountered. --->

**Steps to Reproduce**
<!--- Provide a description of how to reproduce the error. If possible please 
provide source and tool command line options. If the issue reproduces on
Compiler Explorer (https://godbolt.org/) or Shader Playground
(https://shader-playground.timjones.io/) please provide a link. If the source is
split across multiple files, please preprocess into a single file using DXC's 
command line `-P -Fi <path>`. --->


**Actual Behavior**
<!--- Please provide error output or a description of the observed issue. --->

**Environment**
- DXC version <!-- replace with the output of 'dxc --version' -->
- Host Operating System <!--- Host operating system and version --->
```

**Comment by s-perron** [comment]
I can't know for sure, but I believe we have fixed this with https://github.com/microsoft/DirectXShaderCompiler/pull/6832.
