### ISSUE TITLE
[SPIR-V] Crash when accessing buffer from array of buffers

### ISSUE THREAD

**Issue by jaoel** [microsoft/DirectXShaderCompiler#6110]
**Description**
The SPIR-V optimizer crashes when accessing a buffer from an array of buffers which has been assigned to a variable.

**Steps to Reproduce**
Minimal example derived from a real world shader that suffers from the crash:
```hlsl
ByteAddressBuffer inputBuffers[16] : register(t0);

struct MyStruct
{
	ByteAddressBuffer myBuffers[16];
};

[numthreads(32, 1, 1)]
void main()
{
	MyStruct ms;
	ms.myBuffers = inputBuffers;
	ByteAddressBuffer buffer = ms.myBuffers[0]; // < This line causes crash
}
```

I managed to strip the example even more to just these two lines, but the location of the crash is slightly different so I'll include both examples for completeness:
```hlsl
[numthreads(32, 1, 1)]
void main()
{
	ByteAddressBuffer buffers[16];
	ByteAddressBuffer buffer = buffers[0]; // < This line causes crash
}
```

Everything is compiled with command line options: `-E "main" -T cs_6_0 -spirv`

**Actual Behavior**
Both examples causes a crash in SPIRV-Tools `Pass::GenerateCopy()`
The first example produces an assert `"Don't know how to copy this type.  Code is likely illegal."`
The second example attempts to read nullptr.

**Environment**
- DXC version `dxcompiler.dll: 1.8 - 1.7.0.14383 (main, ad3958c2d)`
- Host Operating System Windows 10 64-bit

**Comment by s-perron** [comment]
The is a bug in the SPIR-V code generation in DXC. Local `ByteAddressBuffer`s are suppose to be treated as pointers to the `ByteAddressBuffer`s in the uniform storage class. This is how `buffers` and `buffer` are declared:

```
    %buffers = OpVariable %_ptr_Function__ptr_Uniform__arr_type_ByteAddressBuffer_uint_16 Function
     %buffer = OpVariable %_ptr_Function__ptr_Uniform_type_ByteAddressBuffer Function
```

However, when implement the copy of the array element into `buffer` we try to copy the `ByteAddressBuffer` itself, and not a pointer to it.

```
         %21 = OpLoad %_ptr_Uniform__arr_type_ByteAddressBuffer_uint_16 %buffers
         %22 = OpAccessChain %_ptr_Uniform_type_ByteAddressBuffer %21 %int_0
         %23 = OpLoad %type_ByteAddressBuffer %22  ; <-- We load the entire ByteAddressBuffer
               OpStore %buffer %23 ; <-- And we try to store it.
```

**Comment by jaoel** [comment]
Thanks for looking into this! Unfortunately this fix does not solve the issues in the first example I gave.
Storing an array of buffers in a struct and later accessing those buffers still produces a read access violation.

**Comment by s-perron** [comment]
Sorry that was bad on my part. I should have checked both test cases. When the local copy is in a structure it goes to a different part of the code. I probably need a similar fix somewhere else.

**Comment by s-perron** [comment]
https://github.com/microsoft/DirectXShaderCompiler/pull/6255 should fix the specific example, but I want to try some more. There are still some cases that may not work.

**Comment by s-perron** [comment]
The examples I was thinking of will currently issues an error because RWStructuredBuffers cannot be in an array of resources. It produces an error. Implementing that is part of https://github.com/microsoft/DirectXShaderCompiler/issues/5440. I will close this issue when #6255 is committed.
