### ISSUE TITLE
[SPIR-V] Bad codegen for inout attribute passthrough

### ISSUE THREAD

**Issue by Svenny** [microsoft/DirectXShaderCompiler#6113]
**Description**
A trivial vertex shader which passes attributes unchanged by declaring them `inout`:

```hlsl
void main(inout float4 pos : SV_Position, inout float2 uv : TEXCOORD0) {}
```

gets compiled to invalid SPIR-V with empty function:

```
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main" %gl_Position %out_var_TEXCOORD0
               OpDecorate %gl_Position BuiltIn Position
               OpDecorate %out_var_TEXCOORD0 Location 0
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
    %v2float = OpTypeVector %float 2
%_ptr_Output_v4float = OpTypePointer Output %v4float
%_ptr_Output_v2float = OpTypePointer Output %v2float
       %void = OpTypeVoid
         %11 = OpTypeFunction %void
%gl_Position = OpVariable %_ptr_Output_v4float Output
%out_var_TEXCOORD0 = OpVariable %_ptr_Output_v2float Output
       %main = OpFunction %void None %11
         %12 = OpLabel
               OpReturn
               OpFunctionEnd
```

Changing it to

```hlsl
void main(inout float4 pos : SV_Position, inout float2 uv : TEXCOORD0) { pos = pos; uv = uv; }
```

yields the correct result which does forward attributes:

```
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main" %in_var_SV_Position %in_var_TEXCOORD0 %gl_Position %out_var_TEXCOORD0
               OpDecorate %gl_Position BuiltIn Position
               OpDecorate %in_var_SV_Position Location 0
               OpDecorate %in_var_TEXCOORD0 Location 1
               OpDecorate %out_var_TEXCOORD0 Location 0
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
%_ptr_Input_v4float = OpTypePointer Input %v4float
    %v2float = OpTypeVector %float 2
%_ptr_Input_v2float = OpTypePointer Input %v2float
%_ptr_Output_v4float = OpTypePointer Output %v4float
%_ptr_Output_v2float = OpTypePointer Output %v2float
       %void = OpTypeVoid
         %15 = OpTypeFunction %void
%in_var_SV_Position = OpVariable %_ptr_Input_v4float Input
%in_var_TEXCOORD0 = OpVariable %_ptr_Input_v2float Input
%gl_Position = OpVariable %_ptr_Output_v4float Output
%out_var_TEXCOORD0 = OpVariable %_ptr_Output_v2float Output
       %main = OpFunction %void None %15
         %16 = OpLabel
         %17 = OpLoad %v4float %in_var_SV_Position
         %18 = OpLoad %v2float %in_var_TEXCOORD0
               OpStore %gl_Position %17
               OpStore %out_var_TEXCOORD0 %18
               OpReturn
               OpFunctionEnd
```

**Steps to Reproduce**
[Compiler Explorer](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:hlsl,selection:(endColumn:75,endLineNumber:1,positionColumn:75,positionLineNumber:1,selectionStartColumn:75,selectionStartLineNumber:1,startColumn:75,startLineNumber:1),source:'void+main(inout+float4+pos+:+SV_Position,+inout+float2+uv+:+TEXCOORD0)+%7B++%7D%0A'),l:'5',n:'0',o:'HLSL+source+%231',t:'0')),k:50.49558284852404,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:dxc_trunk,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:hlsl,libs:!(),options:'-T+vs_5_0+-E+main+-spirv',overrides:!(),selection:(endColumn:29,endLineNumber:18,positionColumn:29,positionLineNumber:18,selectionStartColumn:29,selectionStartLineNumber:18,startColumn:29,startLineNumber:18),source:1),l:'5',n:'0',o:'+DXC+(trunk)+(Editor+%231)',t:'0')),k:49.50441715147599,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

**Environment**
- DXC version: `DXC (trunk)` and `DXC 1.7.2207` from Compiler Explorer
- Host Operating System: N/A

**Comment by s-perron** [comment]
This is a bug. We would need to create an output variable for inout parameters and add the copy out from the call to `%src_main`. See https://godbolt.org/z/9oeoEoq68 for the code that is currently generated.
