### ISSUE TITLE
I can't configure the build on Ubuntu arm64

### ISSUE THREAD

**Issue by ArtemS2** [microsoft/DirectXShaderCompiler#6132]
I decided to try to compile shaders on an orange pi5 B single board computer, but I encountered the following error. Is it possible to somehow overcome this?
file:///home/artem/config.log

**Comment by ArtemS2** [comment]
[config.log](https://github.com/microsoft/DirectXShaderCompiler/files/13854035/config.log)

**Comment by ArtemS2** [comment]
[CMakeOutput.log](https://github.com/microsoft/DirectXShaderCompiler/files/13854037/CMakeOutput.log)
[CMakeError.log](https://github.com/microsoft/DirectXShaderCompiler/files/13854038/CMakeError.log)

**Comment by s-perron** [comment]
What is the cmake command that you were trying? Did you follow the steps in https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/BuildingAndTestingDXC.rst?

**Comment by llvm-beanz** [comment]
The error reported here indicates that you're not passing the correct CMake options. DXC's build is a bit odd and complex. See the link @s-perron posted with the instructions for building DXC. If you continue to have issues please re-open this bug with more information.
