### ISSUE TITLE
[SPIR-V] Can't define `BuiltInWorkgroupSize` using new Proposal 0011 syntax

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/DirectXShaderCompiler#6144]
**Description**
I changed from a weird workaround I was using for `gl_WorkGroupID` etc, to the SPIR-V builtins.
```cpp
[[vk::ext_builtin_input(spv::BuiltInWorkgroupSize)]]
static const uint32_t3 WorkgroupSize;
```
I include the SPIR-V Headers into my shaders, the `spv::BuiltInWorkgroupSize` is just a global enum.

**Steps to Reproduce**
This godbolt
https://godbolt.org/z/Pqs4q89ov

**Actual Behavior**
I get this
```
fatal error: generated SPIR-V is invalid: BuiltIn decoration on target <id> '3[%gl_WorkGroupSize]' must be a constant for WorkgroupSize
  OpDecorate %gl_WorkGroupSize BuiltIn WorkgroupSize

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible

Compiler returned: 5
```

**Environment**
- DXC version Latest Godbolt as of Jan 07 2024
- Host Operating System: Windows and Linux

**Comment by sudonatalie** [comment]
Thanks for reporting. @s-perron Can you take a look at this one?

**Comment by s-perron** [comment]
We are not going to support this use with the inline spir-v. It is the only builtin that is suppose to decorate a constant, [which is now deprecated](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#:~:text=Deprecated%3A%20a%20constant%20instruction%2C%20when%20the%20built%2Din%20is%20a%20constant.). For Vulkan, the builtin is superseded by the LocalSizeId execution mode.

It is also unclear how this should interact with the `numthreads` attribute that HLSL requires. It is hard to tell what you want to do with your code. If you need to do anything special with the work group size, I would suggest try to work with the numthreads attribute. There have been some useful suggestions for that already. However, implementing them are not on our list of priorities at this time.

**Comment by devshgraphicsprogramming** [comment]
> It is hard to tell what you want to do with your code.

I want to have a global in my shader equivalent to `gl_WorkGroupSize` ?

**Comment by s-perron** [comment]
I don't think you want to define the WorkGroupSize builtin in the spir-v then. Even though you can read the variable, its main purpose is to define the WorkGroupSize, and it will interfere with NumThreads. I would suggestion you define a contant name gl_WorkGroupSize, and initialize it with the same values you provide to NumThreads. There is not need for it to be associated with the builtin in the spir-v. See https://godbolt.org/z/5eP3xzYeY for an example.

**Comment by devshgraphicsprogramming** [comment]
> I don't think you want to define the WorkGroupSize builtin in the spir-v then. Even though you can read the variable, its main purpose is to define the WorkGroupSize, and it will interfere with NumThreads. I would suggestion you define a contant name gl_WorkGroupSize, and initialize it with the same values you provide to NumThreads. There is not need for it to be associated with the builtin in the spir-v. See https://godbolt.org/z/5eP3xzYeY for an example.

not what I'm looking for and already using that, its just slightly annoying because I actually need to define and initialize it somewhere while compiling the shader.

**Comment by devshgraphicsprogramming** [comment]
@s-perron, this works nicely after the latest commits to `master` which consteval the `numthreads`
https://godbolt.org/z/rvqvfz6j4

the problem is that neither a `static const uint32_t3` or a `static const uint32_t[3]` register as constexpr when you do `operator[]()` or `.x`/`.y` on the vector, I think @Dolkar complained about this in another issue
