### ISSUE TITLE
Build failure on macOS and some Linux distros

### ISSUE THREAD

**Issue by richard-lunarg** [microsoft/DirectXShaderCompiler#6151]
Description
DXC is failing to build from source on the latest macOS and XCode versions, and at least one Linux distro. This is happening even for old commits, so it is likely either a compiler "bug", or a DXC bug that has "gotten past" previous compilers.

Steps to Reproduce
Download source or clone from main branch.
Extract.
Create a new folder for building and build:
mkdir dxc-build-dir
cd dxc-build-dir
cmake .. -DCMAKE_BUIILD_TYPE=Release -C ../cmake/caches/PredefinedParams.cmake
make 

(Note, same results from Ninja generator)

Actual Behavior
The following failure occurs:
[372/1514] cd /home/marky/Downloads/vulkansdk/1.3.275.0_backup/source/DirectXShaderCompiler/build/lib/D...me/marky/Downloads/vulkansdk/1.3.275.0_backup/source/DirectXShaderCompiler/lib/DXIL/DxilShaderModel.cpp
FAILED: lib/DXIL/CMakeFiles/DxilShaderModel /home/marky/Downloads/vulkansdk/1.3.275.0_backup/source/DirectXShaderCompiler/build/lib/DXIL/CMakeFiles/DxilShaderModel 
cd /home/marky/Downloads/vulkansdk/1.3.275.0_backup/source/DirectXShaderCompiler/build/lib/DXIL && /usr/bin/cmake -E compare_files /home/marky/Downloads/vulkansdk/1.3.275.0_backup/source/DirectXShaderCompiler/build/lib/DXIL/tmp/DxilShaderModel.cpp /home/marky/Downloads/vulkansdk/1.3.275.0_backup/source/DirectXShaderCompiler/lib/DXIL/DxilShaderModel.cpp

Environment
macOS 14.2.1
XCode 15.1 (and 15.2)
CMake 3.28.1 (also tried 3.28.0)
- DXC version <main or any recent commit>

It's also failing on "a" linux distro (reported to me internally). I'll have to amend this later when I can get those details. The failure on macOS is easy enough to reproduce however and might be more immediately useful.

On an older machine, running an older version of XCode (15.01) it works.

**Comment by llvm-beanz** [comment]
@richard-lunarg, do you have local changes? This failure means that there is a difference between the locally generated versions of source files and the versions in the source tree.

If you're making changes that alter generated code you need to (1) have clang-format installed and (2) pass `-DHLSL_COPY_GENERATED_SOURCES=On` to the CMake configuration step.

**Comment by richard-lunarg** [comment]
Thanks! I am not making any local changes, but it "could" be a clang-format issue. The above suggestion worked fine on macOS.
