### ISSUE TITLE
[SPIR-V] HLSL Texture.Load translate type to unknown, then vulkan image fetch failed on some drivers

### ISSUE THREAD

**Issue by 000ddd00dd0d** [microsoft/DirectXShaderCompiler#6153]
Hi,

We recently update dxc from 1.6.2012 to 1.7.2308, and our shader compile chain is HLSL -> SPIRV -> Vulkan. There comes some effect error on some drivers after update.

There is **Texture2D.Load** and **Texture2DMS.Load** in pixel shader, image type passed in is RGBA16_UINT. Sample code looks like this:
```
Texture2DMS<uint4, 8> MSAA_texture;
Texture2D<uint4> texture;

void ps_main(PSInput input,
            out float4 OutColor : SV_TARGET)
{
    const uint2 PixelCoord;
    // some prepare code
    // PixelCoord = ...
    
    // load texture value
    uint4 value = texture.Load(uint3(PixelCoord, 0));

    // load msaa value
    uint4 value2 = MSAA_texture.Load(PixelCoord, 2);

    // ...
}
```
Our tests list below:
1. We test a lot on D3D11 & HLSL on windows (RTX3070 with driver 535.98). It fetchs value correctly. Renderdoc D3D11 works fine too.
2.  Before update dxc, it works fine on our test machine (Ubuntu 22.04, RTX4070ti with driver 535.86.05) with vulkan (api version 1.1).
3.  After update dxc., it failed on our test machine  with vulkan. We captured using renderdoc vulkan, and it just returns uint4(0, 0, 0, 0).
4. We use old dxc (1.6.2012), find it renders fine when rendering, but  renderdoc captured still return 0. We guess it **might be a driver problem** ? Maybe it just worked luckily ?

We checked the dxc generated code, and the key point is **StorageImageReadWithoutFormat**.
The two texture types are generated as Unknown, so we guess different drivers may handle Unknown.ImageFetch differently.

Of course, according to https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst#id71, we can change `Texture2D<uint4>` to `[[vk::image_format("rgbaui16")]] RWTexture2D<uint4>` to solve this (though a little non-easy and dirty for us). **What about Texture2DMS<uint4>** ?
PS: we also notis that `Texture2D<uint4>.Load` is translate to `ImageFetch`, while` [[vk::image_format("rgbaui16")]] RWTexture2D<uint4>.Load` is translated to **`ImageRead`**

**Is there any common way to solve this** ? Actually we wouldn't like to use  [[vk::image_format("rgbaui16")]] RWTexture2D<uint4>, the input texture may be just RGBA32_UINT for us on some platform.

And we would have to update to 1.7, cause it solves some bugs.

Thanks a lot!

**Comment by sudonatalie** [comment]
I compiled your sample shader (with minor modification to add a definition of `PSInput`) with dxc release-1.6.2012 and release-1.7.2308 and the following flags:
```
dxc -T ps_6_6 -spirv -O0 -E ps_main issue.hlsl
```

```issue.hlsl
Texture2DMS<uint4, 8> MSAA_texture;
Texture2D<uint4> texture;

struct PSInput
{
	uint idx : COLOR;
};

void ps_main(PSInput input,
            out float4 OutColor : SV_TARGET)
{
    const uint2 PixelCoord;
    // some prepare code
    // PixelCoord = ...
    
    // load texture value
    uint4 value = texture.Load(uint3(PixelCoord, 0));

    // load msaa value
    uint4 value2 = MSAA_texture.Load(PixelCoord, 2);
}
```

and the only difference in output is the addition of `OpCapability StorageImageReadWithoutFormat`. We did have a bug where this capability was added in cases where it was not needed and could have been incorrect, and this has now been fixed (#5906). Indeed, compiling the sample shader with a tip-of-tree build of DXC has the same output as the 1.6.2012 release, so I think this issue has been fixed. Are you able test a build of DXC from source, or with the release of DXC in the latest [Vulkan SDK (1.3.275.0)](https://vulkan.lunarg.com/sdk/home)?
