### ISSUE TITLE
Incorrect dbg.value emitted for HLSL bitfields

### ISSUE THREAD

**Issue by jeffnn** [microsoft/DirectXShaderCompiler#6159]
**Description**
The "bit piece" fields for dbg.value refer to the underlying (typically 32-bit) basic type in which bitfields are stored, rather than the bit-piece that the source HLSL implies.

**Steps to Reproduce**
In the following, I've shown some simple HLSL and pulled out the dbg.value that are generated, and the meta-data they point to that describe the relevant bit-piece:

// dxc -Tcs_6_0 -Emain
```
struct Bitfields
{
    uint first : 7;
    uint second : 3;
    uint third;
};
RWStructuredBuffer<int> UAV: register(u0);
[numthreads(1, 1, 1)]
void main()
{
  Bitfields bf;
  bf.first = UAV[0];
  bf.second = UAV[1];
  bf.third = UAV[2];
  UAV[16] = bf.first + bf.second + bf.third;
}
```

A snippet of the dbg.value and metadata
```
call void @llvm.dbg.value(metadata i32 %bf.set, i64 0, metadata !40, metadata !48), !dbg !49
call void @llvm.dbg.value(metadata i32 %bf.set5, i64 0, metadata !40, metadata !48), !dbg !49
call void @llvm.dbg.value(metadata i32 %4, i64 0, metadata !40, metadata !54), !dbg !49
!40 = !DILocalVariable(tag: DW_TAG_auto_variable, name: "bf", scope: !4, file: !1, line: 15, type: !41)
!48 = !DIExpression(DW_OP_bit_piece, 0, 32)
!54 = !DIExpression(DW_OP_bit_piece, 32, 32)
```

Note how the first two dbg.value both point to the same !48. In other words, the new values for the first two fields (the bitfield ones) are assigned to the 32-bit int that contains the bitfelds, not the bitfelds themselves.
 
Contrast this to the min16 case (when min16 is enabled, of course):
 
``` 
struct Struct
{
    min12int first;
    min16float second;
    unsigned int lastField;
};
!51 = !DIExpression(DW_OP_bit_piece, 0, 16)
!55 = !DIExpression(DW_OP_bit_piece, 16, 16)
!58 = !DIExpression(DW_OP_bit_piece, 32, 32)
```

...note how the bit-pieces make sense for  fully-packed 16-bit float values. 
 
So in the first case, a reader of the dbg.value can't know which bitfield is being referred to by the first two dbg.value. 

**Actual Behavior**
I expect to see, in the first case above:
!48 = !DIExpression(DW_OP_bit_piece, 0, 7)
!54 = !DIExpression(DW_OP_bit_piece, 7, 3)

**Environment**
- DXC version dxcompiler.dll: 1.8 - 1.7.0.3847
- Host Operating System Win11

**Comment by llvm-beanz** [comment]
@jeffnn, given your example here it looks to me like we are generating correct annotations. The `DIExpression` value covers the full 32-bit storage of the underlying data. The bitfield sizes and offsets are stored in the `DIDerivedType` annotations. See `!43` and `!46` below:

```llvm
!38 = !DILocation(line: 12, column: 14, scope: !4)
!39 = !DILocation(line: 12, column: 12, scope: !4)
!40 = !DILocalVariable(tag: DW_TAG_auto_variable, name: "bf", scope: !4, file: !1, line: 11, type: !41)
!41 = !DICompositeType(tag: DW_TAG_structure_type, name: "Bitfields", file: !1, line: 1, size: 64, align: 32, elements: !42)
!42 = !{!43, !46, !47}
!43 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !41, file: !1, line: 3, baseType: !44, size: 7, align: 32)
!44 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint", file: !1, line: 11, baseType: !45)
!45 = !DIBasicType(name: "unsigned int", size: 32, align: 32, encoding: DW_ATE_unsigned)
!46 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !41, file: !1, line: 4, baseType: !44, size: 3, align: 32, offset: 7)
!47 = !DIDerivedType(tag: DW_TAG_member, name: "third", scope: !41, file: !1, line: 5, baseType: !44, size: 32, align: 32, offset: 32)
!48 = !DIExpression(DW_OP_bit_piece, 0, 32)
!52 = !DIExpression(DW_OP_bit_piece, 32, 32)
```

This is represented this way because generally bitfield members can't really be stored in isolation they are packed within the same memory storage.

**Comment by jeffnn** [comment]
@llvm-beanz Thanks for taking a look. The difficulty for winpix is that there's no way to tell which struct member (!43 or !46) is being referred to by each individual dbg.value statement. If the dbg.value were to denote the bitpiece as I expect, then yes, PIX would be able to descend the struct type and find the intended bitfield. PIX would then have enough knowledge to extract the right bits from the value denoted by the dbg.value in order to show the PIX user that value during debugging.

**Comment by llvm-beanz** [comment]
@jefnn, sure but for bitfields the value doesn't refer to just one field. A bitfield assigns a name to a range of bits within a structure member. The value is actually all the elements of the bitfield that are packed within that structure member not just one element.

You can see the debug information generated for similar C++ code:

https://godbolt.org/z/Kh7jvE3fj

The debugger needs to look at the derived type information but the value being tracked in the IR is the packed bitfield not an individual field of the bitfield.

**Comment by jeffnn** [comment]
@llvm-beanz. Thanks again for the explanation. I'll close the bug. 
That makes sense. I was expecting the debug data to denote a single field within the containing aggregate, but of course that would require any write to the containing basic type to promise to change only one bitfield at a time, or you'd end up with an incorrect debug.value for neighboring fields. Therefore PIX has to treat any write as potentially affecting all of the fields that share the same (basic-typed) storage.

**Comment by jeffnn** [comment]
Forgot to close!
