### ISSUE TITLE
[SPIR-V] Invalid SPIR-V when using ByteAddressBuffer as separate variable in mesh shader

### ISSUE THREAD

**Issue by Huntlier** [microsoft/DirectXShaderCompiler#6173]
**Description**
Creating ByteAddressBuffer type variable in mesh shader and loading data from it leads to generation of invalid SPIR-V. 
In other shader types this works fine. 

**Steps to Reproduce**
```hlsl
[[vk::binding(0, 0)]] ByteAddressBuffer byteBuffers[];

struct Output
{
    float4 v : SV_POSITION;
};

template <typename T>
T bufferLoad(uint bufferIndex, uint elementIndex, uint byteOffset = 0)
{
#if 1
    // Error! Leads to invalid SPIR-V
    ByteAddressBuffer buffer = byteBuffers[bufferIndex];
    return buffer.Load<T>(byteOffset + sizeof(T) * elementIndex);
#else
    // Ok!
    return byteBuffers[bufferIndex].Load<T>(byteOffset + sizeof(T) * elementIndex);
#endif
}

[outputtopology("triangle")]
[numthreads(1, 1, 1)]
void main(out indices uint3 triangle_indices[64], out vertices Output triangle_vertices[64])
{
   uint testValue = bufferLoad<uint>(0, 0);
}
```
Reproduced in [Compiler Explorer](https://godbolt.org/z/r8n969Y8x) with DXC (trunk) version. 
Params: -HV 2021 -spirv -T ms_6_6 -E main -fspv-target-env=vulkan1.3
Switch _if_ preprocessor directive in function _bufferLoad_ to change between invalid and working versions.

**Actual Behavior**
Compilation failed with output:
`fatal error: generated SPIR-V is invalid: In Logical addressing, variables may not allocate a pointer type
  %37 = OpVariable %_ptr_Function__ptr_StorageBuffer_type_ByteAddressBuffer Function
Compiler returned: 5`

**Environment**
- DXC (trunk) and DXC from VulkanSDK 1.3.275
- Windows 10

**Comment by s-perron** [comment]
From some reason an unused function scope variable is not be removed. Someone will have to look into which optimization passes are being run, and why it is not removed.

**Comment by Jasper-Bekkers** [comment]
Oof we just ran head-first into this, all other shader stages we're using are fine (pixel shader, compute shader, ray tracing etc).

**Comment by manon-traverse** [comment]
This bug can also be reproduced using `RWByteAddressBuffer` and `StructuredBuffer` types.
Texture types don't seem to be an issue.

Finally, returning one of these types from a function generates the same error.

```
[[vk::binding(0, 0)]] StructuredBuffer<uint> buffers[];

struct Output
{
    float4 v : SV_POSITION;
};

StructuredBuffer<uint> test(uint index) {
    return buffers[index];
}

[outputtopology("triangle")]
[numthreads(1, 1, 1)]
void main(out indices uint3 triangle_indices[64], out vertices Output triangle_vertices[64])
{
    uint testValue = test(0).Load(0);
}
```

**Comment by sudonatalie** [comment]
@keenuts Can you look into this?

**Comment by Huntlier** [comment]
I think this issue is similar to #6087, especially considering @manon-traverse repro case.
