### ISSUE TITLE
[SPIR-V] Uniform buffer block names are not preserved

### ISSUE THREAD

**Issue by Calestian** [microsoft/DirectXShaderCompiler#6174]
**Description**
When writing a cbuffer block in HLSL the name of the block is not preserved when translated to spirv.
In my case, the translated spirv from DXC goes through spirv_cross for reflection, and the block name is needed by the application later on.

**Steps to Reproduce**
`cbuffer ViewMatricesUniformBuffer  
{  
  float4x4 RandomMatrix;  
};  `

**Actual Behavior**
`layout(set, binding, std140) uniform type_ViewMatricesUniformBuffer  
{  
  mat4 RandomMatrix;  
} ViewMatricesUniformBuffer;  `

**Environment**
- DXC version <v1.7.2308>
- Host Operating System <Windows 11 Build22631>

**Comment by s-perron** [comment]
Here is what we currently generate: https://godbolt.org/z/W9ebGPbsa. We need to add an OpName for the variable `%ViewMatricesUniformBuffer`.

**Comment by sudonatalie** [comment]
@s-perron Can you look into this?

**Comment by s-perron** [comment]
I looked at this closer. It seems link compiler explorer removes `OpName` instructions before. If I take that example and compile it locally, there is an `OpName` instruction for the variable.

When I run `spirv-cross --reflect` on the shader, I can see what you are talking about:

```
    "ubos" : [
        {
            "type" : "_3",
            "name" : "type.ViewMatricesUniformBuffer",
            "block_size" : 64,
            "set" : 0,
            "binding" : 0
        }
    ]

```

The "name" is the name of the type, not the variable. However, this seems more like a bug in spirv-cross. The information is in the spir-v.

I will close this issue, and suggestion you open a bug in spirv-cross. If they are able to tell you what specifically is missing from the spir-v, you can open a new issue with the specific details. For now, I do not have anything to go on.
