### ISSUE TITLE
DXC 1.8.2403 Release

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#6203]
The proposed schedule for this release is below:

![DXC 1.8.2403 Schedule](https://github.com/microsoft/DirectXShaderCompiler/assets/15788759/d5bae1ec-061d-4011-b1d8-b1ce2ad1ae60)

* 1/26/2024 - Create the release branch from `main`
* 2/12/2024 - Release Candidate 1 (begin Ask Mode[^1] for release branch)
* 3/4/2024 - Final Release Candidate
* 3/11/2024 - Final Release Date

Tasks: 
* [x] 1/25/2024 - Create release branch from `main` (@hekota)
* [x] 1/27/2024 - Update README.md (@pow2clk)
* [x] 3/1/2024 - Create draft of Release post on GitHub (@pow2clk)
* [x] 3/11/2024 - Tag final release and post binaries. (@hekota)

Quality Sign-off
* [x] 3/3/2024 - Microsoft Testing Sign-off (@pow2clk)
* [x] 3/3/2024 - Google Testing Sign-off (@sudonatalie)

[^1]: [Ask Mode](https://devblogs.microsoft.com/oldnewthing/20140722-00/?p=433) is a Microsoft-ism to denote when changes require approval before accepting merges. For DXC this will require approval from @microsoft/hlsl-release

**Comment by sudonatalie** [comment]
Internal Google testing passed on the `release-1.8.2403` branch. Feel free to ping me if/when re-testing is necessary assuming more changes come in before the final release candidate.

**Comment by sudonatalie** [comment]
Signing off that `v1.8.2403` has passed internal testing.
