### ISSUE TITLE
frexp for vector/matrix causes crash in dxc

### ISSUE THREAD

**Issue by ehsannas** [Microsoft/DirectXShaderCompiler#623]
According to the [reference](https://msdn.microsoft.com/en-us/library/windows/desktop/bb509604(v=vs.85).aspx), the `frexp` should operate on scalars, vectors, and matrices, but the following will crash dxc.

```
// -*- mode: hlsl; hlsl-entry: main; hlsl-target: ps_6_0; hlsl-args: /Zi; -*-

void main() {
  float    a, exp_a, mantissa_a;
  float4   b, exp_b, mantissa_b;
  float2x3 c, exp_c, mantissa_c;

  mantissa_a = frexp(a, exp_a);
  mantissa_b = frexp(b, exp_b);
  mantissa_c = frexp(c, exp_c);
}
```

[fyi, @antiagainst]

**Comment by python3kgae** [comment]
Fixed with https://github.com/Microsoft/DirectXShaderCompiler/pull/624

**Comment by marcelolr** [comment]
@ehsannas are we good to close this one?

**Comment by antiagainst** [comment]
I think this is fixed and we can close it.
