### ISSUE TITLE
Enable spirv codegen support on future Windows SDKs?

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectXShaderCompiler#630]
Hi,
today just testing new binary dxc compiler included in Windows SDK Insider 16288 which should be Fall Creators SDK and accepts -spirv argument.. dxc in creators update (15063) didn't.. 
altough says "SPIR-V codegen not configured via ENABLE_SPIRV_CODEGEN"
as SPIR-V may be mature enough for next 2018 Windows reléase (RS4?) hope by then the dxc compiler in SDK has SPIR-V codegen enabled..
if not devs will be required to build from source to test SPIRV output even in large part of 2018..
thanks..

**Comment by marcelolr** [comment]
SPIR-V work is still ongoing, true. But really we'd like to do releases on GitHub as well, which is where this will likely light up. When exactly we do this is a matter of release management - I've got some notes on how we're handling this that I'll publish & formalize on the Wiki once we have it a bit more buttoned down.

The version we ship in the SDK will almost certainly not have SPIR-V output enabled, but I imagine that's probably OK - the GitHub project has been designed so you can replace the SDK compiler with it, and by the time the SDK comes out, the GitHub version is typically ahead in terms of fixes & functionality. The main benefit you get with the SDK release is a well-tested, well-understood bundle of compiler, tools and validation, aligned to a specific D3D point in time - but if you're interested in SPIR-V, again, I don't think that's a big concern.

**Comment by antiagainst** [comment]
@Zingam: you can always download the release build of the latest master branch by Appveyor: https://ci.appveyor.com/project/antiagainst/directxshadercompiler/branch/master/artifacts. You can also find the link in the [Building Sources](https://github.com/Microsoft/DirectXShaderCompiler#building-sources) section of the README.
