### ISSUE TITLE
Deprecate/remove -not_use_legacy_cbuf_load

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#6306]
**Description**
This flag does not work and has never worked. We've got bugs on it, but the correct fix requires a shader model change and significant design and implementation work. We should deprecate and remove the flag in the meantime to not confuse our users further.

**Steps to Reproduce**
Compile any shader that uses cbuffer data with and without the flag and notice nothing changes...

**Environment**
- DXC version: All
- Host Operating System: All

**Comment by pow2clk** [comment]
I think the first step should be a warning that this doesn't actually do anything. Whether we end up removing it in DXC or not we should discuss.

**Comment by damyanp** [comment]
@tex3d to file an issue to also do this in the validator and link it here.
