### ISSUE TITLE
Allow lib_6_1 profile in dxc binary

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectXShaderCompiler#631]
Hi,
more testing of new SM 6.1 features..
I see in doc
```
Experimental library generation is added in DXIL1.1. 
A library could be created by compile with lib_6_1 profile.
```
so trying (with 10288 SDK) something as:

> dxc -E main -T lib_6_1 barycentrics1.hlsl
I get error:
error: invalid profile lib_6_1

shouldn't be supported on this compiler?
if not can add support to dxc of creating linking libraries..
thanks..

**Comment by marcelolr** [comment]
The binary in the SDK is tracking the https://github.com/Microsoft/DirectXShaderCompiler/tree/dxil-2017-06 branch. We let master move ahead, with the understanding that it's less stable and more things are subject to broader change.

That said, I understand we can help out by providing binaries more regularly, out of cadence from the SDK releases. We're working on that - stay tuned.
