### ISSUE TITLE
[SPIR-V] REGRESSION: Getting lots of `warning: attribute `ext_instruction` must have a uint literal argument [-Wattribute-type]` when using enums

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/DirectXShaderCompiler#6337]
**Description**
I recently merged some upstream commits to my DXC branch

**Steps to Reproduce**
We use the SPIR-V Headers (the enums) to keep our SPIR-V Intrinsic headers legible like so
```cpp
[[vk::ext_builtin_input(spv::BuiltInHelperInvocation)]]
static const bool HelperInvocation;
```
where
```cpp
namespace spv
{

enum BuiltIn {
    BuiltInPosition = 0,
    BuiltInPointSize = 1,
    BuiltInClipDistance = 3,
    BuiltInCullDistance = 4,
    BuiltInVertexId = 5,
    BuiltInInstanceId = 6,
    BuiltInPrimitiveId = 7,
    BuiltInInvocationId = 8,
    BuiltInLayer = 9,
    BuiltInViewportIndex = 10,
    BuiltInTessLevelOuter = 11,
    BuiltInTessLevelInner = 12,
    BuiltInTessCoord = 13,
    BuiltInPatchVertices = 14,
    BuiltInFragCoord = 15,
    BuiltInPointCoord = 16,
    BuiltInFrontFacing = 17,
    BuiltInSampleId = 18,
    BuiltInSamplePosition = 19,
    BuiltInSampleMask = 20,
    BuiltInFragDepth = 22,
    BuiltInHelperInvocation = 23,
```

We can obviously fix by doing the following
```cpp
[[vk::ext_builtin_input(uint(spv::BuiltInHelperInvocation))]]
static const bool HelperInvocation;
```

but it would be nice for the compiler not to moan when the value can be converted to `uint` without any narrowing etc.

I tried using but DXC doesn't understand clang pragmas
```
#pragma clang diagnostic ignored "-Wattribute-type"
```

**Actual Behavior**

Lots of `-Wattribute-type` spam that wasn't there before we merged that commit range.

**Environment**
- DXC version trunk/main as of 21st of February 2024
- Host Operating System Windows

**Comment by cassiebeckley** [comment]
Minimal reproducible example:

```
enum BuiltIn {
  BuiltInHelperInvocation = 23
};

[[vk::ext_builtin_input(BuiltInHelperInvocation)]]
static const bool HelperInvocation;

void main() {}
```

Flags: `-T ps_6_0 -spirv`

**Comment by cassiebeckley** [comment]
Running `git bisect` yields this PR as when this warning was first introduced: https://github.com/microsoft/DirectXShaderCompiler/pull/6202.
