### ISSUE TITLE
[SPIR-V] Dxc crashes when compiling erroneous code

### ISSUE THREAD

**Issue by Eichenherz** [microsoft/DirectXShaderCompiler#6345]
**Description**
Dxc crashes with an assert in attempting to compile to SPIRV. 

**Steps to Reproduce**
https://godbolt.org/z/fffsdKvYb

**Actual Behavior**
As seen in godbolt, it should return with error not crash.

**Environment**
- DXC version from commit ID: 22bb078
- Win10 

[dxc_crash.dmp](https://github.com/microsoft/DirectXShaderCompiler/files/14375700/dxc_crash.dmp)

**Comment by cassiebeckley** [comment]
Is this a debug build you built yourself? Debug builds have asserts in them to help us diagnose mistaken assumptions in compiler code when investigating bugs. If you want friendlier error messages, you should use a release build.

**Comment by Eichenherz** [comment]
Thank you for the suggestion. I switched to a release build and so far I got no assertion fails.
