### ISSUE TITLE
[SPIR-V] Invalid use of a combined image sampler fails at legalization

### ISSUE THREAD

**Issue by sudonatalie** [microsoft/DirectXShaderCompiler#6346]
**Description**
When a Texture and Sampler with the same descriptor set and binding numbers are linked using `[[vk::combinedImageSampler]]`, the Sampler can no longer be used with other Textures because there is no way in SPIR-V to extract a sampler from a combined image sampler. This is documented in the [Vulkan combined image sampler type](https://github.com/microsoft/DirectXShaderCompiler/wiki/Vulkan-combined-image-sampler-type) wiki. However, there's no helpful error messaging when this mistake is made. Instead the SPIR-V module fails legalization.

**Steps to Reproduce**
Compile command: `dxc -T ps_6_0 -E main -O0  -spirv`

```
[[vk::combinedImageSampler]]
SamplerState sam0 : register(s0);
[[vk::combinedImageSampler]]
Texture2D<float4> tex0 : register(t0);

Texture2D<float4> tex1 : register(t1);

float4 main(int3 offset: A) : SV_Target {
  return tex1.SampleLevel(sam0, float2(1, 2), 10, 2);
}
```

**Expected Behavior**
A helpful error message.

**Actual Behavior**
```
fatal error: failed to legalize SPIR-V: 
note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

**Environment**
- DXC version: `libdxcompiler.so: 1.8(dev;4449-ba0705ec)`
- Host Operating System: linux

**Comment by s-perron** [comment]
We are planning on deprecating the attribute, and we will not put effort into improving the error message.
