### ISSUE TITLE
[Feature Request] Release binary built with clang-cl

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#6376]
**Is your feature request related to a problem? Please describe.**
Shader compilation is slow.

**Describe the solution you'd like**
Offer preview release binary built with clang-cl.

**Describe alternatives you've considered**
Build with clang-cl doesn't conflict with other alternatives to speedup compilation.

**Additional context**
In local test, clang-cl build of dxc is about 5%~10% faster compared to msvc build.

**Comment by pow2clk** [comment]
We will want to consider what role clang-cl will have in future releases. Ultimately, it will either replace MSVC or else be dropped itself depending on feedback, but this issue has been resolved by the latest release: https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.8.2405
