### ISSUE TITLE
[SPIR-V] GetAttributeAtVertex(0,0) fails validation

### ISSUE THREAD

**Issue by sudonatalie** [microsoft/DirectXShaderCompiler#6382]
**Description**
Follow-up from https://github.com/microsoft/DirectXShaderCompiler/pull/6041#issuecomment-1829775849

This invalid usage of `GetAttributeAtVertex` fails at validation rather than providing a useful error message.

**Steps to Reproduce**
```
dxc -T ps_6_0 -spirv
```

```
float main() : SV_Target
{
  return GetAttributeAtVertex(0, 0);
}
```

**Actual Behavior**
SPIR-V compilation fails with a validation error message:

```
fatal error: generated SPIR-V is invalid: The Base <id> '7[%int_0]' in OpAccessChain instruction must be a pointer.
  %14 = OpAccessChain %_ptr_Function_int %int_0 %uint_0
```

DXIL fails with:

```
<source>:6:10: error: attribute evaluation can only be done on values taken directly from inputs.
  return GetAttributeAtVertex(0, 0);
         ^
``` 

The SPIR-V backend should produce a similarly helpful error message.

**Comment by sudonatalie** [comment]
Related: https://github.com/microsoft/hlsl-specs/issues/181

**Comment by Keenuts** [comment]
This is now fixed:

```
./build/bin/dxc -T ps_6_0 -spirv ./test.hlsl
./test.hlsl:3:31: error: parameter 0 of GetAttributeAtVertex must have a 'nointerpolation' attribute
  return GetAttributeAtVertex(0, 0);
                              ^
```
