### ISSUE TITLE
[Feature Request] WaveMatrix ops should be allowed in node shaders

### ISSUE THREAD

**Issue by pow2clk** [microsoft/DirectXShaderCompiler#6400]
**Is your feature request related to a problem? Please describe.**
WaveMatrix operations are not allowed in node shaders due to their stage limits set in https://github.com/microsoft/DirectXShaderCompiler/blob/1f162e2230158e8b3d6c70ea31817c1a90a2de22/utils/hct/hctdb.py#L650

**Describe the solution you'd like**
WaveMatrix operations should be allowed in node shaders and tested.

**Describe alternatives you've considered**
We aren't currently aware of a specific requirement for wave matrices in node shaders, so we have no definitive reason why leaving them out would impact anyone. However, these operations are intended for compute stages and node stages are compute stages in most respects. To omit them would be to leave out functionality that is expected in similar stages.

**Additional context**
Uncovered as the result of #5345 investigation.

**Comment by pow2clk** [comment]
This is a dupe of #6165. Closing, but I may add some of these details to that issue

**Comment by oscarbg** [comment]
@pow2clk can you clarify why closed with not "not planned"? in the issue you mention:
"However, these operations are intended for compute stages and node stages are compute stages in most respects. To omit them would be to leave out functionality that is expected in similar stages."
so seems you planned to fix that omission at least once WaveMatrix were "stable"..
thanks..
