### ISSUE TITLE
DXC mesh node preview release

### ISSUE THREAD

**Issue by pow2clk** [microsoft/DirectXShaderCompiler#6406]
The proposed schedule for this release with no dates as of yet:

* Release will be from the release-preview-mesh-nodes branch
* Release Candidate 1 (begin Ask Mode[^1] for release branch)
* Final Release Candidate
* Final Release Date

Tasks: 
* [x]  Update README.md 
* [x]  Create draft of Release post on GitHub
* [x]  Tag final release and post binaries.
* [x] Create dxc vpack for runtime-relevant metadata
* [x] Ensure the release zip file has the correct name

Quality Sign-off
* [x]  Microsoft Testing Sign-off (@pow2clk)
* [x]  Google Testing Sign-off (@sudonatalie)

[^1]: [Ask Mode](https://devblogs.microsoft.com/oldnewthing/20140722-00/?p=433) is a Microsoft-ism to denote when changes require approval before accepting merges. For DXC this will require approval from @microsoft/hlsl-release

**Comment by pow2clk** [comment]
@sudonatalie not sure if this is a release you're particularly interested in vetting. If you like, we can remove your sign-off above.

**Comment by sudonatalie** [comment]
Once the release branch is created it's really just one button click on my side, so might as well.

**Comment by pow2clk** [comment]
It's out! https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.8.2405-mesh-nodes-preview

**Comment by damyanp** [comment]
[celebrate]     Damyan Pepper reacted to your message:
________________________________
