### ISSUE TITLE
[SPIR-V] Incorrect SPIR-V for bitfields

### ISSUE THREAD

**Issue by Eichenherz** [microsoft/DirectXShaderCompiler#6409]
**Description**
Using bitfields in HLSL structs generates the same SPV as in the "no-bitfield" case. But surprisingly, it works correctly on my machine.

`[07.03.2024 15:58:50:745888][ERROR]: Validation Error: [ VUID-VkComputePipelineCreateInfo-layout-07987 ] Object 0: handle = 0xcad092000000000d, type = VK_OBJECT_TYPE_SHADER_MODULE; Object 1: handle = 0xe7e6d0000000000f, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; | MessageID = 0x92cd2576 | vkCreateComputePipelines(): pCreateInfos[0].stage SPIR-V (VK_SHADER_STAGE_COMPUTE_BIT) has a push constant buffer Block with range [0, 20] which outside the pipeline layout range of [0, 8]. The Vulkan spec states: If a push constant block is declared in a shader, a push constant range in layout must match both the shader stage and range (https://vulkan.lunarg.com/doc/view/1.3.275.0/windows/1.3-extensions/vkspec.html#VUID-VkComputePipelineCreateInfo-layout-07987)`

**Steps to Reproduce**
Compile the below struct with these flags
`-HV 202x -T cs_6_7 -spirv -Zpr -enable-16bit-types -fvk-use-scalar-layout -Wno-c++11-extensions -Wno-c++1z-extensions -Wno-gnu-static-float-init -fspv-target-env=vulkan1.3 -fspv-debug=source -fspv-debug=tool`
```cpp
struct BoxBlurParams
{
	float32_t radius;
	uint32_t direction : 2;
	uint32_t channelCount : 3;
	uint32_t wrapMode : 2;
	uint32_t borderColorType : 3;
};
```

**Actual Behavior**
Should result in no validation layer error.

**Environment**
- DXC version from commit ID: https://github.com/microsoft/DirectXShaderCompiler/commit/22bb0786b68e38f21cd16e98f97aad8ed1a0a058
- Host Operating System Win10

**Comment by Keenuts** [comment]
Hi,

Thanks for the report.
I believe this only happens with push_constants, but that's a real issue yes.

Short repro:
```hlsl
struct S {
  uint32_t a : 1;
  uint32_t b : 1;
};

[[vk::push_constant]] S buffer;

[numthreads(1, 1, 1)]
void main() {
  uint32_t v = buffer.b;
}
```

`dxc -T cs_6_0 -E main -spirv -fcgl`

**Comment by Keenuts** [comment]
The PR I sent solves the struct layout issue, which is OK for the push_constant case.
However, if you deal with a RWStructuredBuffer or this kind of arrayed buffer, the stride won't be computed correctly (see https://github.com/microsoft/DirectXShaderCompiler/issues/5648)
