### ISSUE TITLE
[Feature Request] Drop the requirement for semantic strings when emitting `-spirv`

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/DirectXShaderCompiler#6413]
**Is your feature request related to a problem? Please describe.**
I made myself an output struct and using it like this
```cpp
struct VertexAttributes
{
    [[vk::location(0)]] float32_t2 uv;
};

VertexAttributes vertex_main()
```

but I get this error
```
nbl\builtin\hlsl/ext/FullScreenTriangle/SVertexAttributes.hlsl:18:36: error: semantic string missing for shader output variable 'uv'
    [[vk::location(0)]] float32_t2 uv;
```

**Describe the solution you'd like**

I'd like to be able just declare the variable as
```cpp
    [[vk::location(0)]] float32_t2 uv;
```
instead of
```cpp
    [[vk::location(0)]] float32_t2 uv : TEXCOORD0;
```

**Describe alternatives you've considered**

Just using HLSL semantics, but then there's no reasonable way to auto-assign them.

**Additional context**

**Comment by sudonatalie** [comment]
This is a requirement of HLSL -- semantics must be defined for all outputs of an entry function. In general, requests for language spec changes should be directed to the [hlsl-specs](https://github.com/microsoft/hlsl-specs) repo, but we want to avoid divergent behavior between the DXIL and SPIR-V backends, so this isn't a change that could reasonably be considered.
