### ISSUE TITLE
Ternary texture sampling produces illegal / crashing DXIL

### ISSUE THREAD

**Issue by Nielsbishere** [microsoft/DirectXShaderCompiler#6415]
**Description**
When using the following code: `float3 N = normalTexture ? normalize(_textures[NonUniformResourceIndex(normalTexture - 1)].SampleLevel(_linearSampler, input.uv, 0).xyz * 2 - 1) : float3(0, 0, 1);` a GPUBV error is produced (or a crash, depending on the driver); the problem is that it produces a DXIL 'select' op rather than a branch. Which in this case means it will try to access the texture anyways; generating -1 = U32_MAX array of texture access.

**Steps to Reproduce**
```
struct PSInput
{
    float4 color : COLOR;
    float2 uv : UV;
    nointerpolation uint testTexture : TEST;
};

Texture2D _textures[128];
SamplerState _linearSampler;

float4 PSMain(PSInput input) : SV_TARGET
{
    uint normalTexture = input.testTexture;
    float3 N = normalTexture ? normalize(_textures[NonUniformResourceIndex(normalTexture - 1)].SampleLevel(_linearSampler, input.uv, 0).xyz * 2 - 1) : float3(0, 0, 1);
    return float4(N, 1);
}
```
I ran this on shader-playground and I saw that it uses a DXIL 'select' instead of an expected branch. I know that this is how ternary works in shading languages, but it does produce very annoying behavior in this case. Not everyone is aware of these limitations too, so some shader artists might be stumped. 

**Actual Behavior**
GPUBV shouldn't see an unexpected access out of bounds and there shouldn't be invalid DXIL generated. Vendor specific behavior applies here, because some vendors fix it for you apparently while some (such as WARP) don't. On those vendors this will cause crashes, even though it doesn't seem that weird at first glance.

**Environment**
- DXC version: shader-playground (2023-11-10)
- Host Operating System: N/A

**Comment by Keenuts** [comment]
Hi,

Thanks for the report.

> this is how ternary works in shading languages, but it does produce very annoying behavior in this case

Well, yes, both sides of the ternary are executed, and that's

**Comment by chrisbieneman** [comment]
The ternary behavior in HLSL changed with HLSL 2021. You can see the difference here:

https://godbolt.org/z/GPWErvx5j

In HLSL 2021 the behavior matches C, so you should get a branch as you prefer.

I also don't see invalid DXIL being generated for the example provided. It is invalid in DXBC, but should be valid DXIL.

If you have further questions please let me know.

**Comment by Nielsbishere** [comment]
Cool, I didn't realize that things like that changed towards HLSL 2021. Guess I'll have to switch over the compiler to use it then (wasn't used for legacy reasons). Thanks 👍
