### ISSUE TITLE
Support for Evaluate*() intrinsic functions

### ISSUE THREAD

**Issue by ehsannas** [microsoft/DirectXShaderCompiler#642]
Looking through the repo, I wasn't able to find handling for the following intrinsic functions:
```hlsl
numeric EvaluateAttributeAtCentroid(
  in attrib numeric value
);

numeric EvaluateAttributeAtSample(
  in attrib numeric value,
  in uint sampleindex
);

numeric EvaluateAttributeSnapped(
  in attrib numeric value,
  in int2 offset
);
```

Are these going to be supported in dxc?

**Comment by ehsannas** [comment]
fyi, @antiagainst

**Comment by oscarbg** [comment]
Shader Model 6.1 has also new:
 GetAttributeAtVertex

**Comment by pow2clk** [comment]
These are all tested regularly as part of unit tests. I think this can be closed.

**Comment by pow2clk** [comment]
Fixed!
