### ISSUE TITLE
[SPIR-V] Can't construct an enum class value from an unsigned integer

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/DirectXShaderCompiler#6421]
**Description**
Since there's no static_cast, I guess the correct syntax is
```cpp
(ENUM_TYPE)0x1
```

**Steps to Reproduce**
https://godbolt.org/z/saM4MPjdP

**Actual Behavior**
I get an error
```
error: APValue of type 1 unimplemented
error: APValue of type 1 unimplemented

Compiler returned: 5
```

**Environment**
- DXC version Latest Godbolt trunk
- Host Operating System: Whatever  Linux they have on Godbolt

**Comment by damyanp** [comment]
Looks like this is only happening when `-spirv` is on the command line.
