### ISSUE TITLE
Support SM6.1 ViewID and barycentrics in SPIR-V

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectXShaderCompiler#644]
testing new appveyor build with SPIR-V support to check SM6.1 support...
I know I know.. wasn't expecting to work just pointing out..

*Barycentrics:

```
dxc -E main -T ps_6_1 barycentrics1.hlsl -spirv

error: semantic SV_Barycentrics unimplemented yet

```
should be mappable onlty to Vulkan SPIR-V using SPV_AMD_shader_explicit_vertex_parameter perhaps
(https://www.khronos.org/registry/spir-v/extensions/AMD/SPV_AMD_shader_explicit_vertex_parameter.html)

*ViewID: similar story
```
dxc -E main -T ps_6_1 viewid01.hlsl -spirv
error: semantic SV_ViewID unimplemented yet
```
should be mappable to ViewIndex using SPIR-V SPV_KHR_multiview ext: (https://www.khronos.org/registry/spir-v/extensions/KHR/SPV_KHR_multiview.html)
support much better here on desktop (AMD,Intel on Mesa and Nvidia binary drivers Win &Lin)
even there are traces of it on Qualcomm Oreo drivers so should be soon here..

**Comment by antiagainst** [comment]
Thanks for reporting @oscarbg!

We'll certainly do SM6.1 features, but it may take a while to come since right now we are still working on implementing SM5 features. You can check the [mapping doc](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst) to get a sense of what are implemented right now. What are documented there are what are implemented now basically. (We try to keep the doc updated as we go but please forgive us for mismatches sometimes. Some of the features implemented lack their explanations in the doc.)

**Comment by antiagainst** [comment]
Hey @oscarbg, I've uploaded #836 for supporting SV_ViewID.

**Comment by antiagainst** [comment]
Okay, #837 for SV_Barycentrics

**Comment by oscarbg** [comment]
Great!
Will try soon..
Many thanks..

**Comment by antiagainst** [comment]
I'll close this issue since both #836 and #837 are merged.

**Comment by oscarbg** [comment]
@ehsannas just pointing that now that NV Turing GPUs support barycentrics too (VK_NV_fragment_shader_barycentric and associated SPV) it's possible for DXC SPIR-V backend to add support for this extension in addition to SPV_AMD_shader_explicit_vertex_parameter and add some way( option?) to select which vendor extension to use when using barycentrics on HLSL.. maybe of use for other cases like VRS which currently translates to SPV_EXT_fragment_invocation_density but could use also SPV_NV_shading_rate..

**Comment by Wunkolo** [comment]
Bumping in hopes that this AMD/NVidia discrepancy gets addressed somehow.
Current looks like https://github.com/microsoft/DirectXShaderCompiler/pull/2963 has been sitting in the pipeline for a while

**Comment by Pursche** [comment]
I'll bump it as well, being able to map it to either vendor extension would be great.

**Comment by oscarbg** [comment]
+1 for KHR variant.. @jaebaek @jiaolu ?
