### ISSUE TITLE
Mesh node output parameters

### ISSUE THREAD

**Issue by pow2clk** [microsoft/DirectXShaderCompiler#6475]
Need to be allowed for this launch mode and no others. SROA components.

**Is your feature request related to a problem? Please describe.**
Mesh nodes require mesh shader type outputs to pass along the results to the usual mesh shader interface.

**Describe the solution you'd like**
Leverage existing code paths in the compiler to allow output indices, vertices, and primitives to be output just as they are in mesh shaders. 

ensure that assigning of these outputs forces the inclusion of `SetMeshOutputCounts()` just as it does in mesh shaders

**Additional context**
subtask of #6404

**Comment by bob80905** [comment]
This task was finished with the completion of #6482.
Although #6495 has an extra detail that this issue didn't address, this issue can be closed, and #6495 can take the place of the things that are missing.
