### ISSUE TITLE
Disallow prohibited node elements from mesh nodes

### ISSUE THREAD

**Issue by pow2clk** [microsoft/DirectXShaderCompiler#6479]
**Is your feature request related to a problem? Please describe.**
Mesh nodes were based on broadcasting shaders. As such, they initially had all the features that broadcasting shaders did. We need to verify through testing that nothing is allowed where it shouldn't be. 

**Describe the solution you'd like**
Features include: no node outputs, and no node recursion. This may not be a complete list. Testing should verify that they cannot be used in mesh nodes and that helpful errors are produced.

**Alternatives Considered**
I'm far less concerned about mesh-node-specific features leaking into other node types, but if they come up in the process and missing testing is identified, it might be added as part of this.

**Comment by bob80905** [comment]
Closed with #6517
