### ISSUE TITLE
[Mesh Nodes] Ensure derivatives are allowed in mesh nodes

### ISSUE THREAD

**Issue by pow2clk** [microsoft/DirectXShaderCompiler#6480]
**Is your feature request related to a problem? Please describe.**
Derivatives are allowed in broadcasting and mesh shaders. They should be allowed in mesh nodes as well at least on platforms that support it. 

**Describe the solution you'd like**
At least where derivatives in mesh shaders are allowed, derivatives should be available in mesh nodes. Testing should confirm this and possibly the mesh derivative feature flag should be set accordingly. 

**Describe alternatives you've considered**
I'm unsure if the mesh derivatives flag should be required here as broadcasting node derivatives are already available wherever work graphs are

**Comment by pow2clk** [comment]
Seeing as I don't expect to do this myself at this point, I'm leaving this untriaged so it will be noticed and possibly assigned while I'm gone.

**Comment by bob80905** [comment]
Fixed by #6507
