### ISSUE TITLE
"Read uninitialized value" validation error does not respect `#line` directives

### ISSUE THREAD

**Issue by april-roszkowski** [microsoft/DirectXShaderCompiler#6481]
**Description**
The error reported when using an uninitialized variable takes its location directly from the source code, ignoring any previous `#line` directives.

**Steps to Reproduce**

Reproducible via Shader Playground: https://shader-playground.timjones.io/9f0fcc446cdbd217c06fd752ba2abb1e

**Actual Behavior**

Actual error: `C:\local\Temp\00ffbcd9-a2b0-4822-90e9-27388dc70a9b.hlsl:11:13: error: Instructions should not read uninitialized value.`
Expected error: `C:\local\Temp\00ffbcd9-a2b0-4822-90e9-27388dc70a9b.hlsl:101:13: error: Instructions should not read uninitialized value.` (reported on line 101 instead of line 11)

**Environment**
- DXC version: `dxcompiler.dll: 1.7 - 1.7.0.3939 (5e080a772)`

**Comment by damyanp** [comment]
Thank you for the report.  Although it would be great if the validator preserved line number information in this way, it unfortunately does not and to make it do so would be a very large undertaking with limited value (especially as we move towards a clang-based compiler where errors like this would be caught before the validator).

**Comment by llvm-beanz** [comment]
As an additional note, you do get correct line information for the corresponding warning if you pass `-Wuninitialized` to DXC:

https://shader-playground.timjones.io/e1701da9d9a285b2b8826847f36addb7

**Comment by april-roszkowski** [comment]
Got it -- thanks for clarifying!
