### ISSUE TITLE
[SPIR-V] Casting float to int16_t looses precision in unexpected way

### ISSUE THREAD

**Issue by ChristianReinbold** [microsoft/DirectXShaderCompiler#6501]
**Description**

When casting a `float` value to `int16_t`, generated SPIR-V code is equivalent to first casting to `half`, and then casting to `int16_t`. This breaks the assumption that casting to an integral type always floors the float value, because the mantissa of the `half` type has less precision than `int16_t`. For instance, `int16_t(0.999855876f)` results in `1`, whereas `int16_t(int(0.999855876f))` maps to `0`.

**Steps to Reproduce**

See https://godbolt.org/z/7YWfWeGM3

Compile the following hlsl shader with `-T lib_6_4 -spirv -fspv-target-env=vulkan1.2 -enable-16bit-types -HV 2021`

```
RWStructuredBuffer<int> a;

[shader("raygeneration")]
void main() {
    float fvalue = 0.99985586;
    int16_t ivalue1 = int16_t(fvalue);
    int16_t ivalue2 = int16_t(int(fvalue));
    int16_t ivalue3 = int16_t(half(fvalue));
    a[0] = ivalue1;
    a[1] = ivalue2;
    a[2] = ivalue3;
}
```

**Actual Behavior**

Generated code is

```
%21 = OpFConvert %half %float_0_999855876
%22 = OpConvertFToS %short %21
%23 = OpSConvert %int %22
%24 = OpAccessChain %_ptr_StorageBuffer_int %a %int_0 %uint_0
           OpStore %24 %23
%25 = OpAccessChain %_ptr_StorageBuffer_int %a %int_0 %uint_1
           OpStore %25 %int_0
%26 = OpAccessChain %_ptr_StorageBuffer_int %a %int_0 %uint_2
           OpStore %26 %23
```

Note how in %22 and %23 the float value first is converted to `half` before doing the `int16_t` conversion. Note how `int16_t(int(fvalue));` is correctly propagated to a `0`.

I think the issue is lurking at [SpirvEmitter.cpp:8222](https://github.com/microsoft/DirectXShaderCompiler/blob/14ec4b49d419195b787d41464d4a4489bba87bb2/tools/clang/lib/SPIRV/SpirvEmitter.cpp#L8222). The `convertBitwidth` seems to first convert the source type to the bitwidth of the destination type, and only after `OpConvertFToS` is generated.

**Environment**

- DXC version: libdxcompiler.so: 1.8(dev;1-aa4d3746)
- Host Operating System: Compiler Explorer

**Comment by sudonatalie** [comment]
Thanks for reporting this @ChristianReinbold. At first glance, it seems like we should just remove the bitwidth conversion step for float->int but we'll have to do some further investigation to make sure it wasn't added for a reason and doesn't break anything unexpected.
