### ISSUE TITLE
[SPIR-V] Crash with `-fspv-debug=vulkan-with-source` and `-fvk-use-dx-layout` arguments

### ISSUE THREAD

**Issue by septag** [microsoft/DirectXShaderCompiler#6511]
Hi,

I wanted to generate debug information with source for RenderDoc.
But getting a crash with dxc compiler trying to generate spirv (version: 2024 - Patch 2). If I remove `-fvk-use-dx-layout` , it works and outputs the spirv.

**Steps to Reproduce**

Command:
```
dxc -T vs_6_2 -spirv -fvk-use-dx-layout -fvk-use-dx-position-w -enable-16bit-types -fspv-target-env=vulkan1.3  -fspv-extension=SPV_KHR_non_semantic_info -fspv-debug=vulkan-with-source test-vs.hlsl
```

test-vs.hlsl file listing:
```hlsl
struct VS_INPUT
{
    float2 pos : POSITION;
    float2 uv  : TEXCOORD0;
    float4 col : COLOR0;
};

struct PS_INPUT
{
    float4 pos : SV_POSITION;
    float4 col : COLOR0;
    float2 uv  : TEXCOORD0;
};

cbuffer TransformUbo
{
    float4x4 ProjMat; 
};

PS_INPUT main(VS_INPUT input)
{
    PS_INPUT output;
    output.pos = mul(ProjMat, float4(input.pos.xy, 0.f, 1.f));
    output.uv  = input.uv;
    output.col = input.col;
    return output;
}
```

**Actual Behavior**
```Internal compiler error: access violation. Attempted to read from address 0x0000000000000000```

Unfortunately, although I'm putting the pdb in the binaries folder, but I'm not getting anything in the callstack.

**Environment**
- DXC version: dxcompiler.dll: 1.8 - 1.8.2403.37 (11e1318c3); dxil.dll: 1.8(101.8.2403.24) 
- Host Operating System: Windows 10 - 21H2

**Comment by sudonatalie** [comment]
Thanks for reporting @septag!

@Keenuts Can you take a look?

**Comment by Keenuts** [comment]
https://github.com/microsoft/DirectXShaderCompiler/pull/6531 has been merged. Fixing this.
