### ISSUE TITLE
Calling global functions increases the compile-time high compare to calling member functions

### ISSUE THREAD

**Issue by jkwak-work** [microsoft/DirectXShaderCompiler#6518]
**Description**
Compare to calling member functions, the compile-time is much higher when calling global functions.
The repro-steps described below shows **10 times longer compile time** for one line difference.

A tricky part of the issue is that the issue doesn't always occur for calling a global function.
It appears that there are other conditions required to reproduce the problem.
The exact nature of the condition is unclear, but it appears to be related to meaningless code changes that could trigger any optimization process.

It is understandable that any optimization process may add extra compile time.
But the amount of the increase seems unusually high.

**Steps to Reproduce**
I have a simplified repro example that is originally from UnrealEngine TemporalSuperResolution.
```
#ifndef SIMD_SIZE
#define SIMD_SIZE 64
#endif

struct TLaneVector
{
    float3  RegisterArray[SIMD_SIZE];

    float3 GetElement(const uint SimdIndex)
    {
        return RegisterArray[SimdIndex];
    }

    void SetElement(const uint SimdIndex, float3 Element)
    {
        RegisterArray[SimdIndex] = Element;
    }
};

void TLaneVector_SetElement(inout TLaneVector this_0, uint SimdIndex, float3 Element)
{
    this_0.RegisterArray[SimdIndex] = Element;
}

float3 TLaneVector_GetElement(TLaneVector this_3, uint SimdIndex)
{
    return this_3.RegisterArray[SimdIndex];
}

TLaneVector min_0(TLaneVector A, TLaneVector B)
{
    TLaneVector R_11;

    [unroll]
    for(uint SimdIndex = 0U; SimdIndex < SIMD_SIZE; ++SimdIndex)
    {
#ifdef USE_MEMBER
        float3 lhs = A.GetElement(SimdIndex);
#else
        float3 lhs = TLaneVector_GetElement(A, SimdIndex);
#endif

        float3 rhs = TLaneVector_GetElement(B, SimdIndex);
        TLaneVector_SetElement(R_11, SimdIndex, min(lhs, rhs));
    }
    return R_11;
}

[numthreads(4, 1, 1)]
void MainCS(uint2 GroupId_0 : SV_GroupID, uint GroupThreadIndex_20 : SV_GroupIndex)
{
    TLaneVector AccumulatorData;
    TLaneVector Sample0;
    TLaneVector Sample1;

    //[unroll]
    for (uint SimdIndex = 0U; SimdIndex < SIMD_SIZE; ++SimdIndex)
    {
        TLaneVector_SetElement(Sample0, SimdIndex, 0);
        TLaneVector_SetElement(Sample1, SimdIndex, 1);
    }

#ifdef USE_MEANINGLESS_COPY
    // For some reason, this copy is required to reproduce the issue.
    // Probably this line triggers some kind of extra optimization that
    // increases the compile-time.
    AccumulatorData = Sample0;
#endif

    AccumulatorData = min_0(Sample0, Sample1);
}
```
Assuming that the shader code above is saved as "extra_compile_time.hlsl", it can be compiled in four following ways:
```
/usr/bin/time -f "%e" dxc.exe -E MainCS -T cs_6_6 extra_compile_time.hlsl -Fo a.out -DSIMD_SIZE=64
/usr/bin/time -f "%e" dxc.exe -E MainCS -T cs_6_6 extra_compile_time.hlsl -Fo a.out -DSIMD_SIZE=64 -DUSE_MEMBER
/usr/bin/time -f "%e" dxc.exe -E MainCS -T cs_6_6 extra_compile_time.hlsl -Fo a.out -DSIMD_SIZE=64 -DUSE_MEANINGLESS_COPY
/usr/bin/time -f "%e" dxc.exe -E MainCS -T cs_6_6 extra_compile_time.hlsl -Fo a.out -DSIMD_SIZE=64 -DUSE_MEANINGLESS_COPY -DUSE_MEMBER
```

**Actual Behavior**
Each command above took following amount of time to compile on my machine,
```
0.11 second
0.20 second
2.68 second
0.18 second.
```
Note that only the 3rd case has increased compile-time while the others show smaller compile-time.
Also note that the generated DXIL binary files are all identical.
You can make the difference more obvious by using a bigger number for SIMD_SIZE such as 128 or 256.

**Environment**
- DXC version: dxcompiler.dll: 1.8 - 1.8.0.14549 (main, 0781ded87)
- Host Operating System: Windows11

**Comment by llvm-beanz** [comment]
This is the same issue you previously filed as #6512
