### ISSUE TITLE
Globals cbuffer is not compiled if all variables are unused. 

### ISSUE THREAD

**Issue by gdianaty** [microsoft/DirectXShaderCompiler#6530]
**What is the issue you're encountering?**
My shaders rely on the `$Globals` cbuffer. However, sometimes during the course of debugging all references to the aforementioned are commented out and appears to be optimized away. This leads to there being no entries in the `$Globals` cbuffer when performing reflection on the compiled shader.

**Steps to Reproduce (if applicable)**
Write a shader that mixes both manually bound cbuffers and the `$Globals`. Comment out all instances of use of variables that are placed into $Globals, and attempt to perform reflection on the `$Globals` cbuffer. You will find that the `$Globals` cbuffer has zero elements.

**Environment**
- DXC version: `dxcompiler.dll: 1.7 - 1.7.2308.7 (69e54e290); dxil.dll: 1.7(101.7.2308.12)`
- Host Operating System `Windows 11 23H2`

**Comment by llvm-beanz** [comment]
By design we strip automatically bound resources that are unused, so this is behaving as expected.

Is there a particular reason why you need the resource to not be removed?

**Comment by gdianaty** [comment]
My engine uses $Globals and a small amount of preprocessing to extrapolate material parameters. Syntax looks like this:

```hlsl
[[MaterialParameter("Tint", float4(1, 1, 1, 1))]]
extern const float4 g_vTint;
```

If I am not using any of the material parameters (e.g. `g_vTint` is the only example, and it is commented out), this creates inconsistency in binding between shaders.

Although I can account for this behavior in my code, a way of having the DXC always generate the `$Globals` cbuffer would be optimal.

**Comment by llvm-beanz** [comment]
I think the regression potential for other codebases that don't expect that change in behavior is significant, so without a really strong justification we're not going to make this behavior change.
