### ISSUE TITLE
[Feature Request] [SPIR-V] WMMA support via VK_KHR_cooperative_matrix..

### ISSUE THREAD

**Issue by oscarbg** [microsoft/DirectXShaderCompiler#6585]
Title says it all..

**Comment by devshgraphicsprogramming** [comment]
You should be able to get it working via Proposal 0011 Inline SPIR-V's `vk::SpirvType<>` or `SpirvTypeOpaque` to declare a cooperative matrix type and the old regular `[vk::ext_instruction]` as outlined in the original Inline SPIR-V wiki (which is slightly out of date #6412 )

Try it in Godbolt.

**Comment by sudonatalie** [comment]
Wave Matrix support has not yet been added to HLSL but the [proposal](https://github.com/microsoft/hlsl-specs/pull/61) is in progress. Once cooperative matrices are a language feature, we'll work on an implementation in the SPIR-V backend. In the meantime, using Inline SPIR-V is the correct way to access Vulkan-specific features that are not yet surfaced in the high-level language.
