### ISSUE TITLE
[SPIR-V] DXC crash - make [[vk::ext_literal]] be able to take const static as a well as a literal.

### ISSUE THREAD

**Issue by AlexSabourinDev** [microsoft/DirectXShaderCompiler#6586]
**Description**
Hello,

DXC crashes when compiling a shader that uses inline SPIRV to expose `OpGroupNonUniformBallotBitCount`.

Specifically, the use of a `static const uint` for the Group Operation.

**Steps to Reproduce**

This simple shader will reproduce the issue:

```
static uint const ReduceOperation = 0;

[[vk::ext_instruction(/* OpGroupNonUniformBallotBitCount */ 342)]]
uint OpGroupNonUniformBallotBitCount(uint scope, [[vk::ext_literal]] uint groupOperation, uint4 ballot);

[numthreads(1, 1, 1)]
void CS()
{
	OpGroupNonUniformBallotBitCount(vk::SubgroupScope, ReduceOperation, 0);
}
```

Issue does not occur when using either an enum or a macro for the ReduceOperation constant.

Godbolt link: https://godbolt.org/z/vcWzGeEG9

Command line: `-T cs_6_6 -E CS -spirv -fspv-target-env=vulkan1.3`

**Actual Behavior**

Using the DXC C++ API, I get this crash with no output log from DXC:

> Exception thrown at 0x00007FFC468C6552 (dxcompiler.dll) in Samples.exe: 0xC0000005: Access violation writing location 0x0000000000000070.

Compiler explorer simply outputs:

> Program terminated with signal: SIGSEGV

**Environment**
- DXC versions:
    - libdxcompiler.so: 1.8(dev;1-af955d60)
    - dxcompiler.dll: 1.7 - 1.7.2308.7 (69e54e290); dxil.dll: 1.7(101.7.2308.12)
- Host Operating System: Windows 10

**Comment by devshgraphicsprogramming** [comment]
This is because its supposed to be a `static const` not `const`, thats the only use that gets interpreted as a compile time constant like C++ constexpr.

Btw you can actually include C++ SPIR-V Headers in your HLSL if you want the nice enums like I do
https://github.com/Devsh-Graphics-Programming/Nabla/blob/master/include/nbl/builtin/hlsl/spirv_intrinsics/subgroup_ballot.hlsl

**Comment by AlexSabourinDev** [comment]
Unfortunately - the error exists as well with `static  const`

And neat! That's really convenient - I didn't know those existed

**Comment by devshgraphicsprogramming** [comment]
Ok your best bet are the non-C++11 headers (just C++ so its not `enum class`)
https://godbolt.org/z/W1P5MoeYh

I think the name for this issue should be "Make `[vk::ext_literal] be able to take `const static` as a well as a literal"

**Comment by AlexSabourinDev** [comment]
That makes sense to me - I'll happily change the name for clarity!

**Comment by AlexSabourinDev** [comment]
I think another reasonable conclusion is also a clearer error message. Currently a segfault isnt ideal

**Comment by sudonatalie** [comment]
Thanks for reporting @AlexSabourinDev, working on a quick fix.
