### ISSUE TITLE
[SPIR-V][Feature Request][SM6.7] Implement texture sample/load with a non-constant offset

### ISSUE THREAD

**Issue by Keenuts** [microsoft/DirectXShaderCompiler#6612]
Starting SM6.7, offsets can be variables in the sample/load texture operations.
Right now, this is not supported in the SPIR-V backend, as we use an sample instruction which cannot use the `Offset` operand, but only the `ConstOffset`.

See [Programmable Offsets](https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_7_Advanced_Texture_Ops.html#programmable-offsets).

Seems like we should be able to implement this using the OpImageGather instruction, but haven't looked into it very carefully.

```hlsl
Texture2D<float> tex;
SamplerState samplerState;
RWStructuredBuffer<uint2> buffer;

float4 main() : SV_Target {
  float tmp = tex.Sample(samplerState, float2(0, 0), buffer[0]);
  return tmp.xxxx;
}
```

```
$ dxc -T ps_6_7 shader.hlsl -spirv -fspv-target-env=vulkan1.3
fatal error: generated SPIR-V is invalid: [VUID-StandaloneSpirv-Offset-04663] Image Operand Offset can only be used with OpImage*Gather operations
  %36 = OpImageSampleImplicitLod %v4float %35 %14 Offset %34

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

**Comment by s-perron** [comment]
The programmable offset cannot be done in Vulkan. As Nathan mentioned, only the `Gather` instructions can use the `Offset` image operand, so most sampling instruction cannot have a variable offset.

In general, the Gather instructions cannot be used to implement the other instructions. The main issue is that `OpImageGather` requires a component number, so it is not possible to load all components of a texel with a single load. It is also more limited in the types of images it supports.

I suggest we close this issue until SPIR-V is extended to implement this feature.

**Comment by s-perron** [comment]
Discussed with @keenuts. I missed the obvious. We will implement this by manually adding the offset to the coordinates when it is variable.

**Comment by s-perron** [comment]
Sorry, that is not possible because the offset and coordinates can be in different units and will have to be converted before adding them together. This conversion is not possible.

**Comment by s-perron** [comment]
Closing this as unimplementable.
