### ISSUE TITLE
[SPIR-V] OpConstantNull Result Type <id> '12[%type_2d_image]' cannot have a null value

### ISSUE THREAD

**Issue by webez** [microsoft/DirectXShaderCompiler#6653]
**Description**
Invalid spirv generated when calling a function that returns a texture depending on a condition

**Steps to Reproduce**

[Shader Playground](https://shader-playground.timjones.io/a43e24ed089045576f91e58eee2fa5f0)

**Actual Behavior**
fatal error: generated SPIR-V is invalid: OpConstantNull Result Type <id> '12[%type_2d_image]' cannot have a null value.
  %13 = OpConstantNull %type_2d_image

**Environment**
DXC Trunk, no optimization

**Comment by Keenuts** [comment]
Hi!

Thanks for the report & nice catch!
For some reasons when the return is not defined for a branch (here the compiler don't know both branches of the if/else returned), we generate an OpConstantNull instead of an OpUndef.
I'll fix that.

**Comment by Keenuts** [comment]
Original addition was https://github.com/microsoft/DirectXShaderCompiler/pull/809
There don't seem to be any mention of why this was done.

As for using `OpConstantNull` instead: I would be against: the OpUndef has the advantage to be clear: it is not a desired value. Meaning we can do static analysis on the SPIR-V, and possibly find cases where there is a bug. If we use OpConstantNull, then we cannot differentiate actual null from bugs.
