### ISSUE TITLE
Question: Texture2D<uint>.Sample not supported?

### ISSUE THREAD

**Issue by chaoticbob** [Microsoft/DirectXShaderCompiler#666]
Hi,

Was curious why Texture2D<uint>.Sample not supported in DXC since the behavior was available in FXC? Seems like there is a specific case for the exclusion of this behavior:
https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/test/CodeGenHLSL/uintSample.hlsl#L3

Thanks!

**Comment by galop1n** [comment]
If you look at the hardware support of formats for filtering (https://msdn.microsoft.com/en-us/library/windows/desktop/ff471325(v=vs.85).aspx), uint/sint are not list as filterable. FXC should have deny the usage of Sample it in the first place.

**Comment by chaoticbob** [comment]
@galop1n fair point, thanks.
