### ISSUE TITLE
[SPIR-V] Unnecessary extension emitted: SPV_NV_shader_subgroup_partitioned

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#6672]
**Description**
DXC 1.8.2504 emits unnecessary required extension `SPV_NV_shader_subgroup_partitioned`.

This regression is introduced with: https://github.com/microsoft/DirectXShaderCompiler/pull/6546

**Steps to Reproduce**
[Comparison of 1.8.2403.2 and 1.8.2405](https://godbolt.org/z/KM5bjExWc)

**Environment**
- DXC version: DXC 1.8.2504
- Host Operating System: All

**Comment by devshgraphicsprogramming** [comment]
I think all that's needed is to add this extension to the capability & extension stripping pass in the SPIR-V Tools repository

**Comment by Keenuts** [comment]
Hi,

That's right, we haven't added support for this extension in the capability trimming pass. Looking as the extension doc, it seems we will be able to solve the issue that way.
