### ISSUE TITLE
VS2022 bots are failing, spuriously?

### ISSUE THREAD

**Issue by dneto0** [microsoft/DirectXShaderCompiler#6674]
**Description**
The VS2022 debug and releases CI bots are failing

**Steps to Reproduce**
* Any PR within the last two days fails.  I think this will happen with a no-change commit.

Example: the latest commit on main is https://github.com/microsoft/DirectXShaderCompiler/commit/8408ae8829c9c5c5e5e5c01ae8603d45538f9339 
It fails the Windows bots using VS2022
https://github.com/microsoft/DirectXShaderCompiler/runs/25879024728

The debug build fails with a compile error:

> 2024-06-06T06:24:48.6665848Z D:\a\1\s\projects\dxilconv\include\ShaderBinary\ShaderBinary.h(381,10): error C2220: the following warning is treated as an error [D:\a\1\projects\dxilconv\lib\ShaderBinary\ShaderBinary.vcxproj]
> 2024-06-06T06:24:48.7758196Z D:\a\1\s\projects\dxilconv\include\ShaderBinary\ShaderBinary.h(381,10): warning C4201: nonstandard extension used: nameless struct/union [D:\a\1\projects\dxilconv\lib\ShaderBinary\ShaderBinary.vcxproj]

That seems wrong because the code is explicitly guarded with a pragma to disable that warning.

The release build has a mysterious error message:

> C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for 'D:\a\1\CMakeFiles\c010341e1c4c2694685d486ffd93ffcb\StmtNodes.inc.tmp.rule;D:\a\1\CMakeFiles\c010341e1c4c2694685d486ffd93ffcb\StmtNodes.inc.rule;D:\a\1\CMakeFiles\e1327880013738d1b2f92ba750fb28de\ClangStmtNodes.rule;D:\a\1\s\tools\clang\include\clang\AST\CMakeLists.txt' exited with code -1073741819. [D:\a\1\tools\clang\include\clang\AST\ClangStmtNodes.vcxproj]

Is it being killed with the debug build fails?

**Comment by llvm-beanz** [comment]
I've filed an issue on the VM image: https://github.com/actions/runner-images/issues/10004

**Comment by devshgraphicsprogramming** [comment]
I'm actually getting this constantly with Cmake 3.29.6 and MSVC 17.10.3 when doing non-Debug builds of DXC

**Comment by llvm-beanz** [comment]
@devshgraphicsprogramming the root bug is an issue in the MSVC runtime. There are workarounds in the related issue:
https://github.com/actions/runner-images/issues/10004

Sadly this is on the C++ team to provide a correct solution for because anything we do will break some users while fixing others.

**Comment by devshgraphicsprogramming** [comment]
I've readded the define/workaround you removed, now it doesn't crash my MSVC during the execution of the cmake custom rule.
