### ISSUE TITLE
SPV_GOOGLE_hlsl_functionality1 is adding by DXC even if user dont need it

### ISSUE THREAD

**Issue by QuantumDeveloper** [microsoft/DirectXShaderCompiler#6681]
**Description**
during compilation of my shaders to SPIRV, I am not using this extension:  `SPV_GOOGLE_hlsl_functionality1`, but Vulkan says, that this extension was declared and because of this I am getting validation errors.
Seems that DXC adding this extension by itself.
Here is my input commands:

![image](https://github.com/microsoft/DirectXShaderCompiler/assets/6085009/66f8b072-71cb-4d4d-afae-3be46c6cb8de)

**Steps to Reproduce**

**Actual Behavior**
`Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-08742 ] | MessageID = 0xfc68be96 | vkCreateShaderModule():  SPIR-V Extension SPV_GOOGLE_hlsl_functionality1 was declared, but one of the following requi
rements is required (VK_GOOGLE_hlsl_functionality1). The Vulkan spec states: If pCode is a pointer to SPIR-V code, and pCode declares any of the SPIR-V extensions listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.3.283.0/windows/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-08742)
[14:28:10 DBG] Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-08742 ] | MessageID = 0xfc68be96 | vkCreateShaderModule():  SPIR-V Extension SPV_GOOGLE_user_type was declared, but one of the following requirements is
 required (VK_GOOGLE_user_type). The Vulkan spec states: If pCode is a pointer to SPIR-V code, and pCode declares any of the SPIR-V extensions listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.3.283.0/windows/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-08742)
`

**Environment**
dxcompiler.dll: 1.8 - 1.8.2405.15
Windows 11

**Comment by s-perron** [comment]
It is added because you are asking for SpvReflect. That extensions adds instructions that make reflection possible. You can look at the output of https://godbolt.org/z/443G8G1fa with and without the ` -fspv-reflect` option. This is the expected behaviour.
