### ISSUE TITLE
"error: pathspec 'external/googletest' did not match any file(s) known to git" when Pulling

### ISSUE THREAD

**Issue by ohmaya** [microsoft/DirectXShaderCompiler#6693]
**Steps to Reproduce**
- I'm using Fork.
- Can Clone the repository.
- Today, I found a new commit: [ExecutionTest::UnaryHalfOpTest#AcosHalf: Update tolerance (#6690)](https://github.com/microsoft/DirectXShaderCompiler/commit/84d39b66cf9955138ee3dd3abfd43b06cda11fe9), then I did a Pull 'origin/main'.

**Actual Behavior**
A dialog saying "error: pathspec 'external/googletest' did not match any file(s) known to git".

**Environment**
- Host Operating System: Windows 11 22631.373

**Comment by ohmaya** [comment]
Looks like the folder external/googletest failed to be add to git along with .gitmodules when:
git submodule add https://github.com/google/googletest external/googletest

**Comment by llvm-beanz** [comment]
we no longer have that submodule in `main`, and we haven't in quite a while. I'm not sure why your git checkout would be pulling that, so I don't think we can do anything to help you here.

**Comment by ohmaya** [comment]
> we no longer have that submodule in `main`, and we haven't in quite a while. I'm not sure why your git checkout would be pulling that, so I don't think we can do anything to help you here.

Then it needs to be deleted from https://github.com/microsoft/DirectXShaderCompiler/blob/56f3c40381591fcc7e9c0c0f43fd6142ff89f937/.gitmodules#L7.

You even didn't try the "Steps to Reproduce"...

**Comment by llvm-beanz** [comment]
> You even didn't try the "Steps to Reproduce"...

"Steps to Reproduce" that depend on using a specific _paid_ third-party tool that people may or may not be willing to install aren't particularly helpful.

Using the git command line this clones just fine and works as expected with no errors encountered even with the stale module reference.

**Comment by llvm-beanz** [comment]
If you would like to submit a PR to remove the module reference we would happily review it 😄
