### ISSUE TITLE
[Feature Request] Run unittests\IRTests

### ISSUE THREAD

**Issue by adam-yang** [microsoft/DirectXShaderCompiler#6702]
There are some important tests in `unittests\IRTests` that are not being regularly run. We should add it to the hcttest.

**Comment by damyanp** [comment]
@adam-yang - assigning this to you.  We're interested in some more details about what tests aren't getting run - in particular if the github CI builds are running them or not.

**Comment by adam-yang** [comment]
I can confirm that this test is actually run for check-all. False alarm.
