### ISSUE TITLE
DXC.exe missing from the folder

### ISSUE THREAD

**Issue by sprawula** [microsoft/DirectXShaderCompiler#6714]
**What is the issue you're encountering?**
Cant install dxc. Dxc.exe missing in the folder. 
Instalation process says that : 
"Compile or download a build of DirectX Shader Compiler: https://github.com/Microsoft/DirectXShaderCompiler.
Add dxc executable to PATH or set hlsl.preview.dxc.executablePath."

But i am lost as to where said dxc.exe is. I ve used search option in the folder but only found different kind of files. Can someone help me install this extension? =\ 
I know probably i am doing something stupidly wrong, but idk what. I m not a programmer, just wanted to get a grasp of hlsl. 

**Steps to Reproduce (if applicable)**
hmm

**Environment**
- DXC version  
- Host Operating System windows 11
- 
![2024-06-20 21_11_49-DirectXShaderCompiler-main](https://github.com/microsoft/DirectXShaderCompiler/assets/172072685/703fab56-e019-40ed-8689-606212001eaf)

**Comment by damyanp** [comment]
Hi - you can download pre-built binaries from the latest release: https://github.com/microsoft/DirectXShaderCompiler/releases/latest
