### ISSUE TITLE
[Feature Request] Distinguish row vs column major matrices in debug info.

### ISSUE THREAD

**Issue by adam-yang** [microsoft/DirectXShaderCompiler#6734]
Currently matrices regardless of major-ness, show up as `typedef matrix<float, 4, 4> float4x4` in the debug info. It would be helpful to have the typedef be something like `row_major float4x4` and `column_major float4x4` if the attribute is specified so debuggers can show the matrices in a nice way.

Looking at how this is implemented currently matrix major is a type attribute. When debug types are generated, `AttributedType` is peeled away, so attributes do not contribute to the debug type. We can:
1. Not peel `AttributedType` in `UnwrapTypeForDebugInfo`
2. In `CGDebugInfo::CreateTypeNode`, check if we want to keep any of the attributes.
3. If Yes, then generate a new `typedef NameOfEquivalentType "<my attribute> NameOfEquivalentType"`
4. Otherwise, just return `CreateTypeNode(cast<AttributedType>(T)->getEquivalentType())`

**Comment by damyanp** [comment]
We don't believe we can do this properly in DXC due to the way matrices are currently implemented. This is something we should make sure works well in clang.
