### ISSUE TITLE
[SPIR-V] Fails to add linkage capability to module

### ISSUE THREAD

**Issue by SiebenCorgie** [microsoft/DirectXShaderCompiler#6738]
**Description**

I'm currently trying to mark a function `Export`  using SPIR-V's [Linkage](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_linkage) capability.

I get to this compilation error:
```
fatal error: generated SPIR-V is invalid: Operand 2 of Decorate requires one of these capabilities: Linkage
  OpDecorate %eval_sdf LinkageAttributes "eval_sdf" Export
```

But I can't find a way to add `[[vk::ext_capability(/* Linkage */ 5)]]` to the right location.

Adding it to the function in question does _nothing_, decorating the entry point does _nothing_ as well. 
Just adding it to the top of my file gives the error `error: an attribute list cannot appear here` which makes sense, given the rules described [here](https://github.com/microsoft/DirectXShaderCompiler/wiki/GL_EXT_spirv_intrinsics-for-SPIR-V-code-gen#spec)

Am I missing something, or is this just not possible at the moment? 

**Steps to Reproduce**

[see this example code](https://shader-playground.timjones.io/7b64af3c2386fbc213cf519f95f6b421). It includes adding the capability to both, the function in question, as well as the entry point. 

**Actual Behavior**

The compiler fails with:
```
fatal error: generated SPIR-V is invalid: Operand 2 of Decorate requires one of these capabilities: Linkage 
  OpDecorate %eval_sdf LinkageAttributes "eval_sdf" Export
```

So the function is already decorated `Export`, but the `Linkage` capability is missing.

**Environment**
- DXC version: libdxcompiler.so: 1.7(dev;4006-69e54e29)
- Host Operating System: (Arch)Linux

**Comment by s-perron** [comment]
You can make this work with the latest top of tree: https://godbolt.org/z/9fzdeoGYT. You can add the attribute to the entry point, and use the universal1.5 target env (-fspv-target-env=universal1.5).

However, the `[[vk::ext_capability(/* Linkage */ 5)]]` attribute is meant to be used when you are using other inline spir-v that requires the extension. The linkage capability would be added automatically by the compiler, but at this time it only adds the capability if there are no entry points in the module. This condition should be updated. This is a bug in the compiler that needs to be fixed.
