### ISSUE TITLE
Access Rights in HLSL Class Inheritance

### ISSUE THREAD

**Issue by ehsannas** [Microsoft/DirectXShaderCompiler#674]
My understanding is that there is no `public` / `private` / `protected` keyword when it comes to HLSL classes. I'm wondering what are the access rights for a derived class object?

It seems that a derived class is able to access members of the base class, but, it is not able to access (call) a function that is defined for the base class.

Example:
```hlsl
class A {
  bool m_a;
  void bar() { m_a = true; }
};
class B : A {
  bool m_b;
  void foo() {
    m_a = false; // Access to the base    class member is allowed.
    m_b = true;  // Access to the derived class member is allowed.
  }
};
void main() {
  B b;
  b.bar();  // Access to the base class method is not allowed.
            // Error: Cannot cast ‘B’ to its private base class ‘A’.
}
```
Is this behavior expected? (Is the error expected)?

**Comment by ehsannas** [comment]
fyi @antiagainst @chaoticbob

**Comment by python3kgae** [comment]
Sorry for later reply.
Since there's no public/private, everything is public.
It's a bug, and we'll fix it.

**Comment by python3kgae** [comment]
Fixed with https://github.com/Microsoft/DirectXShaderCompiler/pull/685

Thanks
Xiang

**Comment by antiagainst** [comment]
Thanks for the clarification, @python3kgae! So that means `class` is exactly the same as `struct` in HLSL then.

**Comment by ehsannas** [comment]
Thanks @python3kgae
