### ISSUE TITLE
[SPIR-V] Global defined struct { Texture2D; SamplerState } causes irrelevant texture array to be compiled incorrectly

### ISSUE THREAD

**Issue by f32by** [microsoft/DirectXShaderCompiler#6745]
**Description**

A global struct that contains a Texture2D and a SamplerState causes texture array to be compiled into N discrete textures, instead of an array of N textures.

**Steps to Reproduce**

Code below is compiled into 4096 OpDecorates from 0 to 4095. Comment out `TexAndSampler _TS;` then it will be compiled into `%_arr_type_2d_image_uint_4096 = OpTypeArray %type_2d_image %uint_4096` correctly.

Minimum repro code:
```hlsl

// compile with -T ps_6_0 -E frag -spirv -O0

Texture2D<float4> _Textures[4096] : register(t0, space0);
int _TextureIndex;
SamplerState _MainSampler;

struct TexAndSampler {
    Texture2D t;
    SamplerState s;
};

TexAndSampler _TS; // <-------- HERE

float4 frag(float4 position : SV_Position) : SV_Target
{
    return _Textures[NonUniformResourceIndex(_TextureIndex)].Sample(_MainSampler, float2(0.5, 0.5));
}
```

Compiler Explorer link: https://godbolt.org/z/s9MM15zMP

**Actual Behavior**

**Environment**
- DXC version  1.8.2405
- Host Operating System  Windows 11

**Comment by Keenuts** [comment]
Nice catch!

Seems like this is a bad interaction between spirv-opt and the struct we need to flatten:
This struct triggers the `--replace-desc-array-access-using-var-index` pass which doesn't differentiate between the array that requires no intervention than the rest.

I see 2 ways to fix that, a simpler option (don't enable this pass if we only need to flatten a struct), and a better option: finding a way to tag which resource needs a fixup, and exclude the others.
Not sure how to implement it yet, will take a look.
