### ISSUE TITLE
[SPIR-V] integral_constant doesn't work with enum values

### ISSUE THREAD

**Issue by nipunG314** [microsoft/DirectXShaderCompiler#6753]
**Description**

`integral_constant` doesn't seem to work with enums. Ints and bools work fine.

**Steps to Reproduce**

[Link to godbolt reproduction](https://godbolt.org/z/EGaesxvE1)

**Actual Behavior**

DXC should be able to compile with enum values in `integral_constant`. Also, the error should be more clear. Right now, it simply segfaults.

**Environment**
- DXC version: DXC (trunk) 
- Host Operating System: Godbolt

**Comment by Keenuts** [comment]
Thanks!

Shorter repro:
```hlsl
// RUN: %dxc -T cs_6_6 %s -E main -spirv -fcgl | FileCheck %s

enum MyEnum { };

template<typename T>
using Bad = MyEnum;

[numthreads(256,1,1)]
void main() {
  Bad<MyEnum> a;
}
```

Seems like we simply didn't implemented `lowerType` in `LowerTypeVisitor.cpp:622` for the following AST type:
```
TemplateSpecializationType 0x555555a65700 'Bad<MyEnum>' sugar alias Bad
|-TemplateArgument type 'MyEnum'
|-EnumType 0x555555a65370 'MyEnum'
| `-Enum 0x555555a652b0 'MyEnum'
`-EnumType 0x555555a65370 'MyEnum'
  `-Enum 0x555555a652b0 'MyEnum'
```
