### ISSUE TITLE
llvm::errs() doesn't do anything in release builds on Linux, in libdxcompiler.so

### ISSUE THREAD

**Issue by dneto0** [microsoft/DirectXShaderCompiler#6774]
**Description**

I generally use Linux to develop DXC.
When I debug issues in the compiler, I often use llvm::errs().
Unfortunately, llvm::errs() doesn't do anything on release builds in Linux, when I use **libdxcompiler.so**

I've tried tracing through but haven't found the reason.

**Steps to Reproduce**

Build libdxcompiler.so on Linux.
(I'll fill in details below)

**Actual Behavior**

doesn't print.

**Environment**

DXC git d91523292e84a9c2c58676246a888e572d3991fe

**Comment by dneto0** [comment]
Seeing as this only affects libdxcompiler.so this might be on our end?

**Comment by dneto0** [comment]
Update.  It affects Linux release builds when:
- using libdxcompiler.so
- or the command line compiler `dxc` when it traps. (ok, that's my fault due to #6764, so I'll take responsibility for that.)

**Comment by llvm-beanz** [comment]
I suspect what you’re seeing here is that dxcompiler reroutes llvm::errs to an output stream that is surfaced through the API as `DXC_OUT_ERRORS`: https://github.com/microsoft/DirectXShaderCompiler/blob/a54abe841e8f637ed8da7e9e94c40c5207a7c590/include/dxc/dxcapi.h#L727

That allows the caller to control where the output gets printed to, and observes the general best practice of not having shared libraries write to stdout or stderr.

**Comment by damyanp** [comment]
@llvm-beanz / @dneto0  - is there work remaining for this issue?

**Comment by damyanp** [comment]
@dneto0 - if we, or you, need to do something here then please feel free to reopen.
