### ISSUE TITLE
[SPIR-V] Invalid SPIR-V with function returning bigger size vector out variable than caller vector/sclar argument variable

### ISSUE THREAD

**Issue by shobomaru** [microsoft/DirectXShaderCompiler#6781]
**Description**
DXC generates an invalid SPIR-V

**Steps to Reproduce**

`dxc -T ps_6_0 -spirv path/to/file.hlsl`

HLSL code:

```
void Get(out float2 foo)
{
	foo = (float2)0;
}

float main() : SV_Target
{
	float bar;
	Get(bar);
	return bar;
}
```

If change the code in one of the following ways, the issue is not occurred.

- Get()'s 1st argument type is changed to `float`
- main()'s returning type is changed to `void`

**Actual Behavior**

> fatal error: generated SPIR-V is invalid: OpStore Pointer <id> '2[%out_var_SV_Target]'s type does not match Object <id> '6[%6]'s type.
  OpStore %out_var_SV_Target %6

Without validation:

```
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %out_var_SV_Target
               OpExecutionMode %main OriginUpperLeft
               OpSource HLSL 600
               OpName %out_var_SV_Target "out.var.SV_Target"
               OpName %main "main"
               OpDecorate %out_var_SV_Target Location 0
      %float = OpTypeFloat 32
    %float_0 = OpConstant %float 0
    %v2float = OpTypeVector %float 2
          %6 = OpConstantComposite %v2float %float_0 %float_0
%_ptr_Output_float = OpTypePointer Output %float
       %void = OpTypeVoid
          %9 = OpTypeFunction %void
%out_var_SV_Target = OpVariable %_ptr_Output_float Output
       %main = OpFunction %void None %9
         %10 = OpLabel
               OpStore %out_var_SV_Target %6
               OpReturn
               OpFunctionEnd
```

**Environment**
- DXC version: libdxcompiler.dylib: 1.8(dev;4661-a54abe84)
- Host Operating System: Windows 11 23H2 and macOS 14.5

**Comment by s-perron** [comment]
This might be fixed by https://github.com/microsoft/DirectXShaderCompiler/pull/6747.

**Comment by s-perron** [comment]
This is now working: https://godbolt.org/z/G9eq5hTa8
