### ISSUE TITLE
[SPIR-V] `found unregistered decl` when using out-of-line static member + member function

### ISSUE THREAD

**Issue by FoggyMist** [microsoft/DirectXShaderCompiler#6787]
**Description**
I am unable to use out-of-line initialized static member of a structure.
Possibly related issues: https://github.com/microsoft/DirectXShaderCompiler/issues/5563 and https://github.com/microsoft/DirectXShaderCompiler/issues/5916

**Steps to Reproduce**
Following code does not compile (https://godbolt.org/z/xza9oobrf):

```hlsl
// compiled with -T ps_6_6 -E PSMain -spirv

struct PSInput
{
    static const uint Val;
    int Func() { return 8 + Val + Bonus(); }
    int Bonus() { return 11; }
};

static const uint PSInput::Val = 3;

float4 PSMain(PSInput input) : SV_Target0
{
    return float4(float(input.Func()), 0.0f, 0.0f, 0.0f);
}
```

**Actual Behavior**
```
<source>:5:23: fatal error: found unregistered decl Val
    static const uint Val;
                      ^
note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible

Compiler returned: 5
```
Val at the end of first line is added in DXC 1.8.x, it is not present in older versions.

**Environment**
- Host Operating System: godbolt.org - Compiler Explorer
  - DXC version: all available as of 2024-07-16:
    - (trunk)
    - 1.8.2405
    - 1.8.2403
    - 1.8.2306-preview
    - 1.8.2403.2
    - 1.8.2403.1
    - 1.7.2308
    - 1.7.2212
    - 1.7.2207
    - 1.6.2112
- Host Operating System: Windows 10
  - DXC version: `dxcompiler.dll: 1.8 - 1.8.2403.37 (11e1318c3); dxil.dll: 1.8(101.8.2403.24)`

**Additional notes**
Doing any of the following makes the code compile:
* removing `-spirv` compilation flag;
* removing `+ Bonus()` from line 6;
* removing `+ Val` from line 6;
* changing out-of-line initialization of `Val` to inline (remove line 10, change line 5 to `static const uint Val = 3;`.

**Comment by damyanp** [comment]
No repro if `-spirv` removed from compiler args.

**Comment by FoggyMist** [comment]
> No repro if `-spirv` removed from compiler args.

What do you mean?
1. Does the code compile after removing `-spirv`? => You cannot reproduce the compilation failure?
2. Does the code fail to compile after removing `-spirv`? => You cannot reproduce what I have noted in **Steps to reproduce**?

Anyway, it would be nice to be able to compile with the flag.

**Comment by s-perron** [comment]
I think he is just doing triage, to see who will need to look at it. If it is only an issue with targeting spir-v, then it will be directed to some on my team. We will take a look at it at some point.
