### ISSUE TITLE
[Feature Request] Support bypassing/preview hash value in Hash Verification

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#6791]
[Hash Values](https://github.com/microsoft/hlsl-specs/blob/main/proposals/infra/INF-0004-validator-hashing.md#reserved-static-hash-values)

**Is your feature request related to a problem? Please describe.**
Enable shaders to run without hash validation, regardless of whether the machine is in developer mode, as long as the shader targets a supported non-experimental shader model.

**Describe the solution you'd like**

Add -bypass-hash and -preview-hash option to dxc.

1. **When `-bypass-hash` is enabled:**
   - Generate a **BYPASS** hash after DXIL validation passes.

2. **When `-preview-hash` is enabled:**
   - Generate a **PREVIEW** hash after DXIL validation passes.

3. **Error handling:**
   - If both `-bypass-hash` and `-preview-hash` are enabled, report an error.

4. **Default behavior:**
   - If neither of these two options is enabled, generate a validation hash.

**Additional context**
https://github.com/microsoft/hlsl-specs/blob/main/proposals/infra/INF-0004-validator-hashing.md#changes-for-d3d

**Comment by llvm-beanz** [comment]
I'm not sure why we would do this, it isn't part of the spec as it was designed. The intent was to never surface this control to users. The PREVIEW hash should get inserted when targeting shader model previews, but DXC should _never_ insert the BYPASS hash. We do not trust DXC's DXIL generator to generate accurate DXIL so that will be rife with bugs.

**Comment by damyanp** [comment]
@python3kgae  / @llvm-beanz  - closing this as not planned.  Let's have a conversation if we think there's something here that we should still do.
