### ISSUE TITLE
[SPIR-V] Assertion failed when assigning non-bool type variable to bool type variable with ternary operator

### ISSUE THREAD

**Issue by shobomaru** [microsoft/DirectXShaderCompiler#6798]
**Description**
LLVM assertion failed.  
(Debug build only?)  

**Steps to Reproduce**
`dxc -T ps_6_0 -spirv path/to/file.hlsl`

HLSL code:

```
void main(float a : A)
{
	bool bar = (a > 0) ? 1 : 0;
}
```

also crashes: `bool bar = (a > 0) ? 1.0 : 0.0;`

If change the code in one of the following ways, the issue is not occurred.

- Make `a` constant
- Change operand 2 or 3 to bool type value (e.g. `bool bar = (a > 0) ? 1 : false;` )

**Actual Behavior**
> Assertion failed: (!isLitTypeOrVecOfLitType(resultType)), function visit, file LiteralTypeVisitor.cpp, line 314.

**Environment**
- DXC version: libdxcompiler.dylib: 1.8(dev;4661-a54abe84)
- Host Operating System: Windows 11 23H2 and macOS 14.5

**Comment by damyanp** [comment]
LiteralTypeVisitor.cpp is a SPIRV only file.

**Comment by damyanp** [comment]
note: since HLSL202x doesn't use literal types, this is extremely unlikely to repro under `-HV 202x`.

**Comment by s-perron** [comment]
Looking at the code, I believe the assert is simply incorrect. I will remove it.
