### ISSUE TITLE
Interest on DXIL<->SPIRV translation..

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectXShaderCompiler#68]
I know DXIL is still in it's infancy but would be nice if we could get DXIL from existing SPIRV shaders and viceversa SPIRV from DXIL shaders..
any interest by Microsoft on writing should a bidirectional shader translator or better to ask Khronos guys?..
thanks..

**Comment by marcelolr** [comment]
@oscarbg, we have no objection to people writing translator tools. Part of our motivation for opening this up is to allow developers to organize and develop around the solutions they care about the most, including porting this around or porting the output around (https://blogs.msdn.microsoft.com/directx/2017/01/23/new-directx-shader-compiler-based-on-clangllvm-now-available-as-open-source/).

That said, right now we're focused on making DXIL & the associated toolset the best we can. But if there are contributions to help people get started on this we can certainly talk about getting those merged.

Does this help understand where we are on this at the moment?

**Comment by oscarbg** [comment]
Yes.. thanks for info..
hope eventually gets done.. maybe to early to ask for it..

**Comment by antiagainst** [comment]
Hi @oscarbg, we will be taking on this. Please see #216 for details. :)

**Comment by oscarbg** [comment]
@marcelolr  I haven't asked Microsoft guys if they are interested in adding DXIL->LLVM IR support.. 
so let's asks it: it's Microsoft interested in open sourcing a DXIL->LLVM IR translator?
this would also allow going indirectly to SPIRV via DXIL->LLVM IR->SPIRV by adding Vulkan support to Khronos LLVM IR<-> SPIRV translator..
thanks..

**Comment by dmpots** [comment]
@oscarbg DXIL is already valid LLVM IR. We represent DirectX-specific things using a combination of external function calls and LLVM metadata. We did not make any changes to the actual representation of LLVM IR so any stock LLVM should be able to load and process DXIL as normal LLVM IR.

Of course to understand the semantics of DXIL you need to teach the compiler the meaning of the external function calls and how to interpret the metadata. So a translator from DXIL -> SPIRV would need to understand the semantics of DXIL, but the translation to LLVM IR should be a nop for DXIL.

**Comment by oscarbg** [comment]
Thanks @dmpots for details..
also good news seems https://github.com/gongminmin/Dilithium is doing just what I asked..
still early days for this project..
anyway hopefully this porject will be successful implementing it..
