### ISSUE TITLE
Allow string table in the PSV0 part to have a different order than DXC during validation

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#6817]
**Is your feature request related to a problem? Please describe.**
Currently, dxil validator will make sure PSV0 part matches the PSV0 part generated from dxc.
That requires all the names in PSV0 string table have same order and cause duplicate names.

**Describe the solution you'd like**
Sort the string table in validation.
This will only affect the validator. All other part of DXC will be the same.

**Describe alternatives you've considered**
Require string table to be sorted in PSV0 part.
    This will require update the Dxil Container builder.

**Additional context**
[Doc about string table in PSV0 part](https://github.com/llvm/llvm-project/blob/main/llvm/docs/DirectX/DXContainer.rst#id13)

**Comment by llvm-beanz** [comment]
This impacts more than just PSV0. All of the container parts except the DXIL bitcode are validated this way. Correcting this will require design work and significant investment.
