### ISSUE TITLE
Get rid of FreeLibrary call after D3D12EnableExperimentalFeatures

### ISSUE THREAD

**Issue by tex3d** [microsoft/DirectXShaderCompiler#684]
https://github.com/Microsoft/DirectXShaderCompiler/blob/32af2dad66e5271da3d605659e013354dd166221/tools/clang/unittests/HLSL/ExecutionTest.cpp#L98

This unit test can serve as an example of how to enable experimental features.  If an application uses delay-load for D3D12.dll and copies this example, FreeLibrary will actually free D3D12.dll, resetting the experimental feature setting, leading to confusion as to why it isn't working.  So we should remove this line, since we really don't want D3D12.dll to ever be unloaded right after setting the experimental feature setting.  A few people have already stumbled over this issue.

**Comment by marcelolr** [comment]
We can do that and then have hRuntime be g_hD3D12Runtime. That way we can inspect in the debugger whether we've already loaded that via this function.

**Comment by pow2clk** [comment]
Fixed for ages
