### ISSUE TITLE
Warn when a conversion operator is implemented (since they aren't supported)

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#6860]
**Description**
In HLSL 2021 operator overloading was enabled, and it allows users to write conversion operators. The problem is they are never called because DXC's overload resolution doesn't handle conversion operators in any context.

We should emit a warning when writing operators that are never callable. (TBD: should this warning default as error)

**Steps to Reproduce**
https://godbolt.org/z/9sKzjqsqT

**Environment**
- DXC version: 1.8.2407
- Host Operating System: All

**Comment by devshgraphicsprogramming** [comment]
> (TBD: should this warning default as error)

Yes please, that code never worked and might help to catch bugs.

**Comment by llvm-beanz** [comment]
This is a duplicate of https://github.com/microsoft/DirectXShaderCompiler/issues/5103
