### ISSUE TITLE
[SPIR-V] Typed Enum Implicit Conversions Fail

### ISSUE THREAD

**Issue by xantos117** [microsoft/DirectXShaderCompiler#6884]
**Description**
When using typed enums in math operations, they can completely fail to resolve to correct values. Casting the enum to its type in-place can resolve the issue.

**Steps to Reproduce**
1. Create a typed enum, in our case an `enum : int { }`. 
2. Use that enum in a floating-point operation. 
3. Observe that the enum value is now only ever compiled to `0`. 

**Actual Behavior**
Shader playground minimal example of failure [here](https://shader-playground.timjones.io/3351f90d39386104eb9abd74c721b6ef).
```
enum : int
{
	//Hottest star is <50000K and the coldest star is >600K
	STAR_MAX_TEMPERATURE = 50000,
	STAR_MIN_TEMPERATURE = 600,
 	STAR_TEMPERATURE_RANGE = (STAR_MAX_TEMPERATURE - STAR_MIN_TEMPERATURE),
};

...

float x = 3.0;
buffer[threadId] = STAR_TEMPERATURE_RANGE * x;
```
compiles to 
```
%int_0 = OpConstant %int 0
```
Instead of the expected 
```
%int_148200 = OpConstant %int 148200
```

Shader playground minimal example of success [here](https://shader-playground.timjones.io/d649974f488af3ce205892b5ae5fd2cd). 

**Environment**
- DXC version `trunk` (I don't see one clearly on shader-playground, but we're targeting `cs_6_6`, and are using 1.8 locally)
- Host Operating System: Ubuntu 22.04 LTS, or whatever shader-playground runs on (also probably linux, but I don't know).

**Comment by s-perron** [comment]
The initial code generated by DXC looks correct: https://godbolt.org/z/onr1n3boP. The optimizer must be doing something wrong.

**Comment by s-perron** [comment]
My last comment is wrong. DXC is generating an invalid instruction:

```
         %51 = OpBitcast %float %50
```

This should be an `OpConvertUToF` and not a bitcast. The bitcast of 49,600 results in subnormal, which can be flushed to 0.

**Comment by Keenuts** [comment]
> This should be an `OpConvertUToF` and not a bitcast. The bitcast of 49,600 results in subnormal, which can be flushed to 0.

Yep, seems like this is the reason. Looking into it.
