### ISSUE TITLE
[Feature Request] [SPIR-V] -fvk-bind-resource-heap

### ISSUE THREAD

**Issue by zhaijialong** [microsoft/DirectXShaderCompiler#6913]
**Is your feature request related to a problem? Please describe.**
As mentioned in https://github.com/microsoft/DirectXShaderCompiler/pull/6650, there will be a follow-up PR to add -fvk-bind-resource-heap and -fvk-bind-sampler-heap.

We have been waiting for months for that PR, and it should not be too much work. Maybe it's forgotten ?

**Comment by s-perron** [comment]
I think you are right, we forgot about this. I'll check with @keenuts to see when we can schedule it.

**Comment by Keenuts** [comment]
Was just forgotten, thanks for opening this issue! Should be done now 😊
