### ISSUE TITLE
Assertion triggered in function FlattenedTypeIterator::pushTrackerForType

### ISSUE THREAD

**Issue by czw831024** [Microsoft/DirectXShaderCompiler#693]
I found that, when compiling the attached shader with the following command

dxc.exe -T vs_5_0 -E MainVertexShader VelocityShader.usf

dxc will assert in function FlattenedTypeIterator::pushTrackerForType

[VelocityShader.zip](https://github.com/Microsoft/DirectXShaderCompiler/files/1377183/VelocityShader.zip)

**Comment by marcelolr** [comment]
Looks fixed - complains about a syntax error but won't assert. @czw831024  please reopen if you find otherwise - thanks!
