### ISSUE TITLE
[SPIR-V] Non semantic shader information issue (-fspv-debug=vulkan-with-source)

### ISSUE THREAD

**Issue by Goshido** [microsoft/DirectXShaderCompiler#6939]
**Description**
I'm using _Vulkan + HLSL_ workflow. After editing shader in _RenderDoc_ and press compile there is a compilation error:

```txt
Running "D:/Development/VulkanSDK/1.3.290.0/Bin/dxc.exe" -T ps_6_0 -E PS -spirv -fspv-target-env=vulkan1.1 -Fo C:/Users/Goshido/AppData/Local/Temp/shader_output C:/Users/Goshido/AppData/Local/Temp/shader_input
error: missing entry point definition


Process crashed with code -2147467259.
Output file is 0 bytes
```

I also noticed that _SPIR-V_ blobs produced by _DXC v1.8.2407.10013_ `a2a220bc616ca28848ec0af77ad33a09f92fa43a` showed exactly the same compilation flag information in _RenderDoc_:

```bash
-T {hlsl_stage2}_6_0 -E {entry_point} -spirv -fspv-target-env={vulkan_ver}  -E PS -T ps_6_8 -HV 2021 -spirv 
-fvk-use-dx-layout -fspv-reduce-load-size -fspv-target-env=vulkan1.1 -enable-16bit-types -WX -I tools\editor\hlsl
-I tools\editor\include -I app\src\main\hlsl -I app\src\main\cpp\include\pbr -Od -fspv-debug=vulkan-with-source
-Fo tools\editor\editor-assets\shaders\blit.ps.spv -Qembed_debug
```

Now _SPIR-V_ blobs compiled by recent _DXC v1.8.2407.10091_ `75ff50caa046a054747ae15b5c1910a4c8aa1917` shows less information:

```bash
-T {hlsl_stage2}_6_0 -E {entry_point} -spirv -fspv-target-env={vulkan_ver}
```

**Steps to Reproduce**
1. Take the following shader code:

`blit_program.ps`:

```cpp
#include "blit_program.inc"
#include "color_space.ps"
#include "srgb_program.inc"


// 1.0H / 2.4H
#define INVERSE_GAMMA           4.16667e-1F

[[vk::constant_id ( CONST_INVERSE_GAMMA )]]
float const                     g_inverseGamma = INVERSE_GAMMA;

[[vk::binding ( BIND_IMAGE, SET_BLIT )]]
Texture2D<float32_t4>           g_image:        register ( t0 );

[[vk::binding ( BIND_SAMPLER, SET_BLIT )]]
SamplerState                    g_sampler:      register ( s0 );

struct InputData
{
    [[vk::location ( ATT_SLOT_UV )]]
    noperspective float32_t2    _uv:            UV;
};

//----------------------------------------------------------------------------------------------------------------------

float32_t4 PS ( in InputData inputData ): SV_Target0
{
    float16_t3 const color = (float16_t3)g_image.SampleLevel ( g_sampler, inputData._uv, 0.0F ).xyz;
    return float32_t4 ( LinearToSRGB ( color, (float16_t)g_inverseGamma ), 1.0F );
}
```

`color_space.ps`:

```cpp
#ifndef COLOR_SPACE_PS
#define COLOR_SPACE_PS


float32_t3 LinearToSRGB ( in float16_t3 ldr, in float16_t inverseGamma )
{
    // See https://entropymine.com/imageworsener/srgbformula/
    float16_t3 const a = ldr * 12.92H;
    float16_t3 const b = 1.055H * pow ( ldr, inverseGamma ) - 0.055H;
    return (float32_t3)lerp ( a, b, (float16_t3)( ldr > 3.1308e-3H ) );
}


#endif // COLOR_SPACE_PS
```

`blit_program.inc`:

```cpp
#ifndef BLIT_PROGRAM_INC
#define BLIT_PROGRAM_INC


#define ATT_SLOT_UV     0

#define SET_BLIT        0
#define BIND_IMAGE      0
#define BIND_SAMPLER    1


#endif // BLIT_PROGRAM_INC
```

`srgb_program.inc`:

```cpp
#ifndef SRGB_PROGRAM_INC
#define SRGB_PROGRAM_INC


#define CONST_INVERSE_GAMMA     0


#endif // SRGB_PROGRAM_INC
```

2. Compile it with the following flags:

```txt
dxc.exe                                                     ^
    -HV 2021                                                ^
    -spirv                                                  ^
    -fvk-use-dx-layout                                      ^
    -fspv-reduce-load-size                                  ^
    -fspv-target-env=vulkan1.1                              ^
    -enable-16bit-types                                     ^
    -WX                                                     ^
    -I tools\editor\hlsl                                    ^
    -I tools\editor\include                                 ^
    -I app\src\main\hlsl                                    ^
    -I app\src\main\cpp\include\pbr                         ^
    -Od                                                     ^
    -fspv-debug=vulkan-with-source                          ^
    -E PS                                                   ^
    -T ps_6_8                                               ^
    -Fo tools\editor\editor-assets\shaders\blit.ps.spv      ^
    tools\editor\hlsl\blit.ps
```

3. Use this program and made capture.
4. Try to edit program `blit_program.ps` by multiplying `color` variable by `0.5H`.

```cpp
...

float32_t4 PS ( in InputData inputData ): SV_Target0
{
    float16_t3 const color = (float16_t3)g_image.SampleLevel ( g_sampler, inputData._uv, 0.0F ).xyz;
    return float32_t4 ( LinearToSRGB ( color * 0.5H, (float16_t)g_inverseGamma ), 1.0F ); <--------------------------
}
```

5. Press apply changes.

**Actual Behavior**
Compilation fails:

```txt
Running "D:/Development/VulkanSDK/1.3.290.0/Bin/dxc.exe" -T ps_6_0 -E PS -spirv
-fspv-target-env=vulkan1.1 -Fo C:/Users/Goshido/AppData/Local/Temp/shader_output
C:/Users/Goshido/AppData/Local/Temp/shader_input
error: missing entry point definition


Process crashed with code -2147467259.
Output file is 0 bytes
```

**Expected:** Compilation success.

Would you kindly help?

**Environment**
- `git submodule update --init` has been invoked before build
- `hctbuild` build parameters: `-official -rel -x64 -vs2022 -speak-up -no-dxilconv -spirv`
- _Visual Studio 2022 Community_ components were up to date.
- _Windows 11 Pro (23H2, Build 22631.4169)_
- `dxc.exe` _v1.8.2407.10091_ executable, commit SHA-1 `75ff50caa046a054747ae15b5c1910a4c8aa1917`
- _RenderDoc v1.35_

## Additional information

Here is blobs from old and new _DXC_: [SPIR-V blobs.zip](https://github.com/user-attachments/files/17177782/SPIR-V.blobs.zip).

The video with problem:

https://github.com/user-attachments/assets/f0ef8f84-19f0-4230-9219-11175e0bf62c

Initially I created issue for _RenderDoc_: [#3448](https://github.com/baldurk/renderdoc/issues/3448). Issue has been closed because it's not _RenderDoc_ issue in the first place.

**Comment by s-perron** [comment]
The main difference between the "good" version and the "bad" version is that the "bad" version now includes the `DebugSource` for two files that were not included before. I personally do not see any problems with the debug instructions. 

It could be that there is a new code pattern that renderdoc is not use to. Without know the details on where renderdoc is failing, I cannot know how the source should be changed. I've asked someone else who know more about the debug instructions to look at it.

**Comment by Goshido** [comment]
Roger.

**Comment by s-perron** [comment]
FYI: @SteveUrquhart

**Comment by s-perron** [comment]
A fix should be coming soon.

**Comment by SteveUrquhart** [comment]
This is fixed by https://github.com/microsoft/DirectXShaderCompiler/pull/6966, sorry for the regression.

**Comment by Goshido** [comment]
I tested the latest _DXC_ version _1.8.2407.10115_, `9b9442cd86c242aa0c030be3beea0fb1d0df7a1f`. The issue with missing shader editing is gone. Thx! 👍

The issue could be closed.
