### ISSUE TITLE
Assertion triggered in function Sema::~Sema()

### ISSUE THREAD

**Issue by czw831024** [Microsoft/DirectXShaderCompiler#694]
dxc.exe min.hlsl -E RadialPixelMain -Zpr -O3 -T ps_5_0 -Ni

dxc will assert in function Sema::~Sema()

source file is attached
[min.zip](https://github.com/Microsoft/DirectXShaderCompiler/files/1377494/min.zip)

**Comment by czw831024** [comment]
[min.zip](https://github.com/Microsoft/DirectXShaderCompiler/files/1377495/min.zip)

**Comment by marcelolr** [comment]
This appears to have been fixed - it simply writes out a compilation error (the sources appear to be mostly a standalone compilation). @czw831024 can you reopen and provide more details if this still isn't working for you? Thanks!
