### ISSUE TITLE
Regression when using SV_Position with a mesh shader

### ISSUE THREAD

**Issue by bfavela** [microsoft/DirectXShaderCompiler#6940]
**Description**

This regression was introduced fairly recently, but unsure when

When using SV_Position as the only output for vertices, it will fail compilation with:
error: validation errors
error: DXIL container mismatch for 'SigOutputElement' between 'PSV0' part:('PSVSignatureElement:

If the output is changed to a struct with SV_Position as one of the members, it works fine.

**Steps to Reproduce**

https://godbolt.org/z/7vEoEjzMf

**Actual Behavior**

Crash in validation

**Environment**
- DXC version (latest)
- Host Operating System (any)

**Comment by damyanp** [comment]
It's extremely unlikely that this was caused by #6924, since that PR is still open.

**Comment by bfavela** [comment]
> It's extremely unlikely that this was caused by #6924, since that PR is still open.

I don't know what you're talking about! (yeah, I totally goofed on that - just removed it)

**Comment by llvm-beanz** [comment]
Likely caused by #6859.
