### ISSUE TITLE
Assertion triggered in function EvalUnaryIntrinsic

### ISSUE THREAD

**Issue by czw831024** [Microsoft/DirectXShaderCompiler#695]
dxc.exe DeferredLightPixelShaders.hlsl -E RadialPixelMain -Zpr -O3 -T ps_5_0 -Ni

dxc will assert in function FlattenedTypeIterator::pushTrackerForType

[DeferredLightPixelShaders.zip](https://github.com/Microsoft/DirectXShaderCompiler/files/1377500/DeferredLightPixelShaders.zip)

**Comment by marcelolr** [comment]
This appears to have been fixed - we had a few fixes for the FlattenedTypeIterator. Please reopen if you still see this or file a new one if we've missed a case - thanks!
