### ISSUE TITLE
[SPIR-V] E_FAIL for Mesh Shader

### ISSUE THREAD

**Issue by Andreyogld3d** [microsoft/DirectXShaderCompiler#6960]
**Description**

Use cmd line:
dxc.exe can't compile mesh shader,  IDxcCompiler3::Compile returns E_FAIL(0x80004005)
`dxc.exe -T ms_6_5 -spirv -E main -fspv-extension=SPV_EXT_mesh_shader -fspv-target-env=vulkan1.3 MeshletMS.hlsl`
or use DXC API directly, in this case 

**Steps to Reproduce**

1) Use dxc compiler tool:
`dxc.exe -T ms_6_5 -spirv -E main -fspv-extension=SPV_EXT_mesh_shader -fspv-target-env=vulkan1.3 MeshletMS.hlsl`
2) Use DXC API:
IDxcCompiler3::Compile returns E_FAIL(0x80004005), errors happens [here](https://github.com/KhronosGroup/SPIRV-Tools/blob/522dfead39eb232b3873f0e7cfe57cde6b9e69c1/source/opt/copy_prop_arrays.cpp#L118)

I attached mesh shader file[MeshletMS.zip](https://github.com/user-attachments/files/17356681/MeshletMS.zip)

I have no problem using dxcompiler.dll: 1.8 - 1.8.0.14728 (main, b400c7281-dirty)

**Actual Behavior**
Correct Compilation

**Environment**

- DXC version dxcompiler.dll: 1.8 - 1.8.0.14728 (main, b400c7281-dirty)
- Host Operating System Windows 11

**Comment by s-perron** [comment]
Regression caused by https://github.com/KhronosGroup/SPIRV-Tools/pull/5827.

**Comment by Andreyogld3d** [comment]
Hi @cassiebeckley ,  Thank you  - I have no problem  on  DXC Version string 1.8.0.14751 , as I know problem was in [Spirv-tools](https://github.com/KhronosGroup/SPIRV-Tools/pull/5853)
