### ISSUE TITLE
Cannot compile project in VS2022, the command line parameters are missing /T

### ISSUE THREAD

**Issue by laultman** [microsoft/DirectXShaderCompiler#6972]
Visual Studio people say this is not their issue. I can compile the hlsl file using the command line but I cannot get Visual Studio properties for hlsl to generate a command line that works.

I have a new project in VS 2024 17.11.5 C++ dll for UWP using the VS template. In the project I added the shader files from an existing working project (it is the Microsoft OpenXR samples for UWP). The original project in that sample solution is called pbr_uwp. I am attempting to port some of the code so I am just trying to get it working in the C++20 as a dll rather than a static output that the sample is.

While the project has two each of pixel shaders and vertex shaders, we will just talk about one of them because they all have the same issues in VS. The first issue is that VS can't find the path to the files and I don't see a way to add a source path to the files. The second issue is the command line that actually works is not generated by VS using the property settings.
The dxc compiler requires a format for the Shader Model to be /T ps_6_7. This is not generated by VS, instead it generates /ps_6_7 leaving out the "T " where that is a T and a space.
As I write this on close inspection of the working command line:
I find that the commands are completely different for dxc and whatever VS is trying to use:
working: dxc -T ps_6_7 -E main -Fo HighlightPixelShader.cso HighlightPixelShader.hlsl
not working: /E"main" /Vn"g_HighlightPixelShader" /ps"_5_0" /Fh"\HighlightPixelShader.h" /nologo

**Comment by damyanp** [comment]
I'm sorry, this isn't something that can be fixed in the shader compiler.  

`/ps"_5_0"` is not a valid command-line parameter to the shader compiler (as you noted it should be something like `/Tps_6_7`. The issue here is somewhere inside the Visual Studio project system.
