### ISSUE TITLE
[SPIR-V] Unhandled Exception "Name is not a simple identifier" and others, but only when running in debugger

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/DirectXShaderCompiler#6973]
**Description**

I was making a shader with the EXE/godbolt of the compiler, but now when I compile at runtime I get unhandled exception after unhandled exception

**Steps to Reproduce**

This godbolt: https://godbolt.org/z/WMsK7sP3d

**Actual Behavior**

Can't run with the debugger attached

**Environment**
- DXC version: trunk as of 17/10/24
- Host Operating System Godbolt

**Comment by devshgraphicsprogramming** [comment]
Made a 50% smaller repro https://godbolt.org/z/qojxv4c5M

**Comment by devshgraphicsprogramming** [comment]
The whole bug seems to be caused by me defining `void WhittedTask::operator()()` outside the struct

**Comment by s-perron** [comment]
I'm able to reproduce when using a debug build of the compiler. I reduced the test to:

```
struct WhittedTask
{
    void operator()();
};

void WhittedTask::operator()()
{
}

[numthreads(8,8,1)]
void main(uint32_t3 gl_GlobalInvocationID : SV_DispatchThreadID)
{
}
```
