### ISSUE TITLE
[SPIR-V] Struct inheritance work when compiling HLSL to SPIRV

### ISSUE THREAD

**Issue by AaronHaganAMD** [microsoft/DirectXShaderCompiler#6986]
Struct inheritance does work when compiling HLSL to SPIRV. 
See following example: [shader-playground](https://shader-playground.timjones.io/85ddb6733f8fb09ee82baa2fa90e349d) and compare the DXIL to SPIRV. 

The DXIL writes all 5 uints in the example, while the SPIRV seems to ignore the inherited parent members and only write to the 3 local members.

**Comment by Keenuts** [comment]
Hello!

So what I understand is from what you observed, inheritance does NOT work when compiling HLSL to SPIR-V.
I do agree on the shader-playground link, seems like the child fields are not stores.
However, I cannot reproduce nor locally at HEAD, nor on goldbolt: https://godbolt.org/z/hn6f9osEc

Seems like shader-playground is using a stale version of DXC, and that this issue has been solved already.
Feel free to reopen if you observe this on a recent version of DXC.
