### ISSUE TITLE
Question about SM 6.0 wave ops

### ISSUE THREAD

**Issue by antiagainst** [Microsoft/DirectXShaderCompiler#699]
It seems at least the following [SM 6.0 wave ops](https://msdn.microsoft.com/en-us/library/windows/desktop/mt733232(v=vs.85).aspx) are not supported right now:

* WaveOnce
* WaveIsHelperLane
* WaveAllSum
* WaveAllProduct

Any timeline for supporting them? Thanks! :)

**Comment by antiagainst** [comment]
Oh, OK, I saw methods with similar names implemented in https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/test/CodeGenHLSL/wave.hlsl:

* WaveActiveSum (I think this corresponds to WaveAllSum?)
* WaveActiveProduct (I think this corresponds to WaveAllProduct?)

And a bunch of others.

So the question is, which set of functions should I follow? The one from https://msdn.microsoft.com/en-us/library/windows/desktop/mt733232(v=vs.85).aspx or the one from https://github.com/Microsoft/DirectXShaderCompiler/wiki/Wave-Intrinsics?

**Comment by antiagainst** [comment]
Aha, there is a note on https://msdn.microsoft.com/en-us/library/windows/desktop/mt733232(v=vs.85).aspx  saying that "The Shader Model 6.0 specifics described is a preview and subject to change, pending the release of supporting tools and drivers."

So I assume I should follow what the compiler implements right now.

**Comment by marcelolr** [comment]
Yes, please go by the implementation. The MSDN docs are behind on this.

**Comment by antiagainst** [comment]
Cool, thanks!
