### ISSUE TITLE
HLSL  can't generate vulkan specialization constants.

### ISSUE THREAD

**Issue by runner0353** [microsoft/DirectXShaderCompiler#7005]
[test.txt](https://github.com/user-attachments/files/17727579/test.txt)
[spirv-dis-dump.txt](https://github.com/user-attachments/files/17727594/spirv-dis-dump.txt)

 dxc.exe --version
dxcompiler.dll: 1.8 - 1.8.0.4739 (d9a5e97d0)

test.txt  is hlsl shader 
spirv--dis-dump.txt is spirv-dis.exe disassembler info.

when i use glsl  compiled a spv , spirv-dis dump info is ok.
but use hlsl compiled a spv  , spirv--dis can't generated OpSpecConstant

**Comment by s-perron** [comment]
The two spec constants are unused, so they are not emitted. This is the expected behavior. If I added uses of `LIGHTING_MODEL` and `PARAM_TOON_DESATURATION` the spec constants are generated.

Reopen if I missed something.
