### ISSUE TITLE
[Feature Request] Include dxv binary and spirv headers in DXC releases

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#7024]
**Is your feature request related to a problem? Please describe.**
Clang needs to be able to invoke dxv to validate and hash

**Describe the solution you'd like**
Include dxv in the DXC release packages
https://github.com/microsoft/DirectXShaderCompiler/tree/main/tools/clang/lib/Headers/hlsl
These header files should also be part of the release packages, presumably for SPIR-V validation.

**Comment by bob80905** [comment]
This has been completed in an internal PR.
Closed.
