### ISSUE TITLE
A wired variable name for library if output header file

### ISSUE THREAD

**Issue by GinShio** [microsoft/DirectXShaderCompiler#7040]
**Description**
If compile an exported function to header file, I got a bad variable name that is `g_lib.no::entry`.
It cannot be used in C or C++ source code:
```C
const unsigned char g_lib.no::entry[] = {
  /* binary code */
};
```

**Steps to Reproduce**
shader:
```hlsl
export uint32_t f(uint32_t input) { return input; }
```
command:
```shell
dxc -O3 -T lib_6_8 -HV 2021 -Fh test.dxil.h test.hlsl
dxc -O3 -T lib_6_8 -HV 2021 -spirv -fspv-target-env=universal1.5 -Fh test.spv.h test.hlsl
```

**Desired behavior**
A good name can be used in C/C++. e.g. `g_lib_no__entry`.

**Environment**
- DXC version: libdxcompiler.so: 1.8(dev;4662-416fab6b); libdxil.so: 1.8
- Host Operating System: openSUSE Linux Tumbleweed

**Comment by llvm-beanz** [comment]
This is a really odd feature that I didn't know existed. I imagine there is a reasonable workaround using `#embed`. This has likely been broken forever so it will be low priority for us to address.

**Comment by llvm-beanz** [comment]
For context what is happening here is that library shaders have no entry, so the entry is getting the name "no::entry", which when munged into the variable is odd.

There is a DXC flag `-Vn` which can be used to specify a specific variable name to use. I would recommend using that flag as a workaround for this issue.

**Comment by GinShio** [comment]
> This is a really odd feature that I didn't know existed. I imagine there is a reasonable workaround using `#embed`.

Yes, `#embed` is a good idea, but we cannot use C23 now...

> There is a DXC flag -Vn which can be used to specify a specific variable name to use. I would recommend using that flag as a workaround for this issue.

Thanks a lot! It woks fine.
