### ISSUE TITLE
export keyword causes builds to fail

### ISSUE THREAD

**Issue by mrvux** [Microsoft/DirectXShaderCompiler#73]
using export keyword in a shader (like this simple vertex shader)

export float4 applySomething(float4 p)
{
	return p * float4(sin(p.x),0,0,1);
}

void VS(float4 p : POSITION, out float4 ps : SV_Position)
{
	ps = applySomething(p);
}

Brings the following error.

>test.hlsl:1:1: error: 'export' is a reserved keyword in HLSL
export float4 applySomething(float4 p)
^
test.hlsl:8:7: error: use of undeclared identifier 'applySomething'
        ps = applySomething(p);
             ^

As far as I know, library is not supported (will it actually be?) at the moment, but that means any shader that was using this feature (or uses a function which is marked as export somewhere in the codebase) will fail compilation.

If there's no plan to support the library feature anymore, should export keyword just be silently ignored (with eventual warning as it is now with legacy annotations) ?

**Comment by python3kgae** [comment]
Yes, library is not supported at this moment.
#82 should make export be silently ignored.

**Comment by mrvux** [comment]
Thanks, checked out and tested, works as expected now.
