### ISSUE TITLE
Crash in IDxcIntelliSense::ParseTranslationUnit

### ISSUE THREAD

**Issue by simontaylor81** [microsoft/DirectXShaderCompiler#741]
I'm not 100% convinced this is a bug and not me doing something wrong, but I think there's a crash bug in ParseTranslationUnit accessing the current-thread's IMalloc. libclang seems to run the operation on a separate thread, which hasn't had its IMalloc set up properly. It then crashes accessing this null IMalloc.

The issue can be worked around by passing DxcTranslationUnitFlags_UseCallerThread to ParseTranslationUnit.

Here's the relevant part of the callstack (although it's not that much help I don't think):

```>	dxcompiler.dll!operator new(unsigned __int64 size) Line 27	C++	Symbols loaded.
 	dxcompiler.dll!clang_parseTranslationUnit_Impl(void * UserData) Line 3063	C++	Symbols loaded.
 	[Inline Frame] dxcompiler.dll!llvm::function_ref<void __cdecl(void)>::operator()() Line 88	C++	Symbols loaded.
 	dxcompiler.dll!llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void __cdecl(void)> Fn) Line 317	C++	Symbols loaded.
 	dxcompiler.dll!RunSafelyOnThread_Dispatch(void * UserData) Line 364	C++	Symbols loaded.
 	dxcompiler.dll!ThreadCallback(void * param) Line 83	C++	Symbols loaded.
 	ucrtbase.dll!00007fffbe470399()	Unknown	No symbols loaded.
 	kernel32.dll!00007fffbf092774()	Unknown	No symbols loaded.
 	ntdll.dll!RtlUserThreadStart()	Unknown	Symbols loaded.
```

Here's the gist of what my code is doing:

```
dxc::DxcDllSupport dllSupport;
dllSupport.Initialize();

CComPtr<IDxcIntelliSense> isense;
dllSupport.CreateInstance(CLSID_DxcIntelliSense, __uuidof(IDxcIntelliSense), (IUnknown**)&isense);

CComPtr<IDxcIndex> index;
isense->CreateIndex(&index);

CComPtr<IDxcTranslationUnit> tu;
auto hr = index->ParseTranslationUnit(R"(C:\some\file.hlsl)", nullptr, 0, nullptr, 0, DxcTranslationUnitFlags_None, &tu);
```

**Comment by marcelolr** [comment]
You're quite right. I don't think we've had callers that *haven't* set DxcTranslationUnitFlags_UseCallerThread; spawning a new thread is the default, but it's a very messy thing to do and so we've always encouraged (successfully) everyone to use it.

In fact, this issue makes me wonder - should we even support separate-thread compilation anymore? Even if we didn't collapse it to be more straightforward (we keep is somewhat diff'able with the original), I just can't think of any case where the caller would want to delegate thread management to the library.

**Comment by simontaylor81** [comment]
No, I have no idea why it spawns a new thread tbh. Now that I know it exists I will always use UseCallerThread, because I don't want/need it spinning up new threads behind my back.

The only thing I really care about is that the default behaviour doesn't crash :). If the easiest way is to just force UseCallerThread (or equivalent) then it's certainly find with me!
