### ISSUE TITLE
Intellisense API does not visit "unusual annotations"

### ISSUE THREAD

**Issue by simontaylor81** [microsoft/DirectXShaderCompiler#742]
The AST representation returned by the intellisense API (`IDxcIntelliSense`) (and libclang, which it wraps), does not contain nodes for "unusual annotations," such as register assignments and semantics. (The "unusual" name comes from `struct UnusualAnnotation` in HlslTypes.h).

Given this simple example shader:

```
Texture2D<float4> tex : register(t0);

float main() : SV_TARGET
{
    return 0.0f;
}
```

If I compile it in dndxc, this is the resulting AST:

```
TranslationUnitDecl 0x1b5d832a6c0 <<invalid sloc>> <invalid sloc>
|-VarDecl 0x1b5d9624e00 <hlsl.hlsl:3:1, col:19> col:19 tex 'Texture2D<float4>':'Texture2D<vector<float, 4> >'
| `-RegisterAssignment 0x1b5d9624eb0 <col:25> register(t0)
`-FunctionDecl 0x1b5d9529528 <line:5:1, line:8:1> line:5:7 main 'float ()'
  |-CompoundStmt 0x1b5d9529660 <line:6:1, line:8:1>
  | `-ReturnStmt 0x1b5d9529648 <line:7:5, col:12>
  |   `-FloatingLiteral 0x1b5d9529620 <col:12> 'float' 0.000000e+00
  `-SemanticDecl 0x1b5d9529600 <line:5:16> "SV_TARGET"
```

Note the RegisterAssignment and SemanticDecl nodes.

However, if I parse the file using `IDxcIntelliSense::ParseTranslationUnit` the traverse the AST using `GetCursor` / `GetChildren` and dump out the visited nodes, I get this:

```
TranslationUnit '<blah>'
  VarDecl 'tex'
    TemplateRef 'Texture2D'
    TypeRef 'float4'
  FunctionDecl 'main()'
    CompoundStmt ''
      ReturnStmt ''
        FloatingLiteral ''
```

Note the lack of any register assignment or semantic nodes.

I'm not sure exactly how to fix this, but it likely involves augmenting the various Visit* functions in CIndex.cpp.

**Comment by marcelolr** [comment]
Good catch. It's likely that Intellisense APIs have fallen a bit behind (Tim Jones provided excellent VS support for that http://timjones.io/blog/archive/2015/10/06/introducing-hlsl-tools-for-visual-studio a while ago), but it's definitely goodness to bring them back up to speed.

**Comment by simontaylor81** [comment]
FWIW, I'm looking at the Intellisense API because I'm investigating the possibility of using it for general parsing, not intellisense per se. It has the advantage over the full AST API of being expose by the dll, so building is relatively straightforward, rather having to work out how to link all the clang libraries directly. I'm not 100% settled on this, though, but figured I should report issues where I found them :).

(Another alternative is using libclang, rather than intellisense wrapper, but that would have the same bug, since the issue is there, not in the intellisense layer).

Anyway, all that's to say: I'm not really sure how important this is right now :).
