### ISSUE TITLE
`DxilContainer` documentation

### ISSUE THREAD

**Issue by grovesNL** [Microsoft/DirectXShaderCompiler#747]
I am wondering if there is any public documentation about `DxilContainer`? I'm particularly interested in what happens during [`SerializeDxilContainerForModule`](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/lib/HLSL/DxilContainerAssembler.cpp#L800). I can try to figure out the format based on the comments/code, but it would be useful if there is any documentation you could point me towards. Thanks!

**Comment by marcelolr** [comment]
@grovesNL we don't have any documentation as such, but https://github.com/Microsoft/DirectXShaderCompiler/blob/master/include/dxc/HLSL/DxilContainer.h should have most (or all) of the structural pieces you need and we've tried to keep it reasonably well commented.

Is there something specific you'd like to be able to do with this?

**Comment by grovesNL** [comment]
@marcelolr No problem, thought I would ask just in case 😃 I'll study the header file. I was wondering what it takes to get from LLVM bitcode to DXIL, basically exploring whether it's feasible to generate DXIL myself from other source languages.
