### ISSUE TITLE
AppVeyor is timing out

### ISSUE THREAD

**Issue by marcelolr** [Microsoft/DirectXShaderCompiler#778]
I've already seen more than one failure because we're hitting the one-hour limit. Opening this issue to make sure we do something to make a dent on that. Yes, the one hour limit is arbitrary, but it's also a good forcing function to make sure the build times don't get out of control.

**Comment by antiagainst** [comment]
+1

I think right now we are using 45-50 min for a fresh build and test. The one hour timeout is Appveyor platform fluctuation? But still good to keep build time under control.

If we can cache taef, it may squeeze a few minutes out.

**Comment by marcelolr** [comment]
ReflectionMatchesDXBC_Full is blindly checking many shaders, and is clocking in at 3 minutes on its own. I'll take a pass at trimming that down.

**Comment by antiagainst** [comment]
https://github.com/Microsoft/DirectXShaderCompiler/pull/862 for stopping installing TAEF. Should save some time.

**Comment by antiagainst** [comment]
#863 is the trial to switch from MSBuild to ninja to see whether we can save some time or not.

For the two runs that successfully build and test, it took

43 min 12 sec: https://ci.appveyor.com/project/marcelolr/directxshadercompiler/build/1.0.1458

46 min 35 sec: https://ci.appveyor.com/project/marcelolr/directxshadercompiler/build/1.0.1456 (failed uploading artifacts)

It typically takes ~50min before. So seems ~5min saving.

**Comment by antiagainst** [comment]
The third run take 42 min 5 sec: https://ci.appveyor.com/project/marcelolr/directxshadercompiler/build/1.0.1461

**Comment by antiagainst** [comment]
Per-job time limit is increased for us.
