### ISSUE TITLE
Empty struct handling

### ISSUE THREAD

**Issue by ehsannas** [Microsoft/DirectXShaderCompiler#780]
The following HLSL code crashes dxc.exe

```hlsl
struct EmptyStruct
{
};

struct OuterStruct
{
  EmptyStruct s;
};

float4 main(float4 pos : POSITION) : SV_POSITION
{
  OuterStruct os;
  return float4(0, 0, 0, 0);
}
```
There is a valid AST generated though. Commenting out `OuterStruct os;` will get rid of the internal error.

**Comment by antiagainst** [comment]
cc @chaoticbob

**Comment by python3kgae** [comment]
Fixed with https://github.com/Microsoft/DirectXShaderCompiler/pull/798

Thanks
Xiang
