### ISSUE TITLE
ConstantBuffer/TextureBuffer bad usage error missing

### ISSUE THREAD

**Issue by ehsannas** [Microsoft/DirectXShaderCompiler#784]
The following usage of ConstantBuffer/TextureBuffer:
```hlsl
ConstantBuffer<float> cb;
```
results in the following error in fxc.exe:
`error X3594: D3D12 constant/texture buffer template element can only be a struct`

This error is missing in dxc.exe

**Comment by antiagainst** [comment]
This is addressed by #1177.
