### ISSUE TITLE
SPIR-V: f16tof32 and f32tof16 not supported

### ISSUE THREAD

**Issue by seppala2** [Microsoft/DirectXShaderCompiler#785]
When using the functions f16tof32 and f32tof16, the compiler gives the following error:

"error: Intrinsic function 'f32tof16' not yet implemented.
error: Intrinsic function 'f16tof32' not yet implemented."

These functions seem to be not yet supported, but they are crucial for packing floats.

**Comment by antiagainst** [comment]
Hey @seppala2,

Thanks for reporting! I've submitted PR #786 to add support for these two intrinsic functions.

Out of curiosity, are you using f16 extensively elsewhere? Just wanted to let you know that right now f16 is not declared as supported in SPIR-V CodeGen. It may work for most cases, but is not tested and may have problems.

**Comment by seppala2** [comment]
Thank you! We are not using f16 in the project I'm working on, only these functions to pack and unpack the 32-bit floats.

**Comment by antiagainst** [comment]
Cool, thanks!
