### ISSUE TITLE
SPIR-V:  GroupMemoryBarrierWithGroupSync not supported

### ISSUE THREAD

**Issue by seppala2** [Microsoft/DirectXShaderCompiler#795]
Compiling a shader with the the intrinsic GroupMemoryBarrierWithGroupSync() produces the following error:
"intrinsic 'GroupMemoryBarrier' function unimplemented"

GroupMemoryBarrier() seems to be also not implemented. Especially the former one would be nice to have as this is needed pretty much anywhere where shared memory is used

**Comment by antiagainst** [comment]
Yep. It will be supported very soon: #790.

**Comment by ehsannas** [comment]
Fixed via #790
