### ISSUE TITLE
DXC crash when casting InterlockedOr's first parameter to uint

### ISSUE THREAD

**Issue by jgavert** [Microsoft/DirectXShaderCompiler#835]
When casting the first parameter to uint, for reasons I'm not sure at the moment, the compiler crashes. This behavior differs from fxc.

### Functional impact
This makes it hard to switch from fxc to dxc when compiling large projects and trying to port them to compile on dxc.

### Minimal repro steps
Try compiling this compute shader.
```
RWBuffer<uint> buffer;

[numthreads(1,1,1)]
void main()
{
	uint unused;
	InterlockedOr((uint)buffer[0], 1, unused);
}
```

### Expected result  
Compiler doesn't crash, as fxc doesn't. It would also be acceptable if there was a error message displayed about this.

### Actual result  
Compiler crashes and burns away.

### Further technical details 
Root cause is that the first parameter "buffer[0]" is cast to uint. Removing the cast will make the shader succeed compilation.

**Comment by python3kgae** [comment]
Thanks for this detailed feedback.
Fixed in https://github.com/Microsoft/DirectXShaderCompiler/pull/843

But only InterlockedOr((uint)buffer[0], 1, unused) works.
Compiler will report error for InterlockedOr((float)buffer[0], 1, unused).
Is this OK for your projects?

Thanks
Xiang

**Comment by jgavert** [comment]
Brilliant!

I agree with the comment in pull request, this should probably be error in future language version.

Thanks!
Juho
