### ISSUE TITLE
SPIR-V: Loading constant buffers to variables produces invalid SPIR-V

### ISSUE THREAD

**Issue by seppala2** [Microsoft/DirectXShaderCompiler#838]
Assuming that a constant buffer is defined as:
`ConstantBuffer<ConstantsStruct> Constants;`

Loading it to a variable (even without using the variable):
`ConstantsStruct c = Constants;`
Produces a validation error in vkCreateShaderModule:
> SPIR-V module not valid: OpLoad Result Type <id> '45' does not match Pointer <id> '5's type.

The same error appears when passing the constant buffer directly into a function, which is a construct that is quite commonly used in the project that I'm working on
```
void SomeFunction(ConstantsStruct c)
{
}
...
SomeFunction(Constants);
...
```

In the basic cases the result seems to be visually still correct, but this seems to be a cause of some problems in more complex shaders as I have been able to workaround some bugs by accessing the constants directly from the global variable when possible. This does not seem to be limited to constant buffers as I have seen similar issues with Buffers and got them "fixed" by accessing them directly instead of passing to a function.

**Comment by antiagainst** [comment]
Hey @seppala2, much appreciated for the bug report!

To actually assign a constant buffer to another one, if they are of different storage class, like `Constants` (`Uniform` storage class) and `c` (`Function` storage class) in the example, we need to assign each field separately and recursively. This is because of Vulkan and SPIR-V validation rules.

However, that's probably not what you want since it copies all the data from the source constant buffer to the destination one. I think you actually want the function scope variable `c` to go away and access the underlying `Constants` directly after some optimizations. So that's what we do in #826. #826 just performs a load and then a store over of whole struct, completely ignoring the storage class. This will surely generate invalid SPIR-V (as the validation error you saw). The hope is to rely on optimizations to remove these loads/stores completely and emit valid SPIR-V in the end. (If we write out each field separately and recursively, it will make it harder for the optimizations to do the elimination work.)

Because SPIR-V CodeGen starts directly from the AST, we cannot reuse the optimization passes for DXIL CodeGen. Instead we leverage [SPIRV-Tools](https://github.com/KhronosGroup/SPIRV-Tools) opt. SPIRV-Tools opt is also under active development right now. It should cover a good portion of workloads, but there surely exist cases it cannot handle. So, the support for complicated cases requiring optimization is kinda shaky right now.

Let me refresh the SPIRV-Tools used and see if it works.

**Comment by antiagainst** [comment]
#839 as an a attempt to remedy the problem.

**Comment by antiagainst** [comment]
Please also note that the support for assigning to structured buffer types are incomplete right now: the associated counters are not written right now.  Will have that fixed soon.

**Comment by seppala2** [comment]
Hi,

This seems to have fixed some issues such as passing Buffers into functions, thanks! Passing constant buffers as structs into functions still doesn't seem to work, but hopefully SPIRV-Tools opt can handle that sometime in the future.

**Comment by antiagainst** [comment]
Hey @seppala2,

Glad to hear at least some of the problems are solved! :)

Regarding loading constant buffers, I did a quick check over the following simple HLSL source code:
```hlsl
struct S {
    float4 f;
};

ConstantBuffer<S> myCBuffer;

float4 doStuff(S buffer) {
    return buffer.f;
}

float4 main(in float4 pos : SV_Position) : SV_Target0
{
    S buffer = myCBuffer;
    return doStuff(buffer);
}
```

The generated optimized code seems fine:
```llvm
       %main = OpFunction %void None %8
         %10 = OpLabel
         %45 = OpLoad %S_0 %myCBuffer
         %46 = OpCompositeExtract %v4float %45 0
               OpStore %out_var_SV_Target0 %46
               OpReturn
               OpFunctionEnd
```
But I think this my be too simple to reflect your use cases.

If it is possible, could you please provide a more complicated case that currently is not working? Thanks!

**Comment by seppala2** [comment]
Hi,

I get a validation error in vkCreateShaderModule

> OpLoad Result Type <id> '44' does not match Pointer <id> '5's type

at least for the following shader, which is pretty much the same as your example.
```
struct S
{
	float3 f;
};

ConstantBuffer<S> ObjectConstants : register(b0);

struct VSOut
{
    float4 pos : SV_Position;
    float3 color : COLOR;
};

float3 doStuff(S buffer)
{
    return buffer.f;
}

VSOut VS(float3 pos : POSITION, float3 color : COLOR)
{
    VSOut result;
    S s = ObjectConstants;
    float3 v = doStuff(s);
    result.pos = float4(v, 1.f);
    result.color = color;
    return result;
}
```

Here are the probably relevant parts of the produced SPIR-V:
```
%type_ConstantBuffer_S = OpTypeStruct %v3float
%_ptr_Uniform_type_ConstantBuffer_S = OpTypePointer Uniform %type_ConstantBuffer_S
%ObjectConstants = OpVariable %_ptr_Uniform_type_ConstantBuffer_S Uniform
...
%S_0 = OpTypeStruct %v3float
...
%77 = OpLoad %S_0 %ObjectConstants
%78 = OpCompositeExtract %v3float %77 0
```

The validation layer clearly complains about the OpLoad instruction above, but I don't know why.
Here is the whole SPIR-V that was passed to vkCreateShaderModule:
```
; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 87
; Schema: 0
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %VS "VS" %gl_PerVertexOut %in_var_POSITION %in_var_COLOR %out_var_COLOR
               OpName %type_ConstantBuffer_S "type.ConstantBuffer.S"
               OpMemberName %type_ConstantBuffer_S 0 "f"
               OpName %ObjectConstants "ObjectConstants"
               OpName %VS "VS"
               OpName %type_gl_PerVertex "type.gl_PerVertex"
               OpName %gl_PerVertexOut "gl_PerVertexOut"
               OpName %in_var_POSITION "in.var.POSITION"
               OpName %in_var_COLOR "in.var.COLOR"
               OpName %VSOut "VSOut"
               OpMemberName %VSOut 0 "pos"
               OpMemberName %VSOut 1 "color"
               OpName %out_var_COLOR "out.var.COLOR"
               OpName %S "S"
               OpMemberName %S 0 "f"
               OpName %S_0 "S"
               OpMemberName %S_0 0 "f"
               OpMemberDecorate %type_ConstantBuffer_S 0 Offset 0
               OpDecorate %type_ConstantBuffer_S Block
               OpMemberDecorate %type_gl_PerVertex 0 BuiltIn Position
               OpMemberDecorate %type_gl_PerVertex 1 BuiltIn PointSize
               OpMemberDecorate %type_gl_PerVertex 2 BuiltIn ClipDistance
               OpMemberDecorate %type_gl_PerVertex 3 BuiltIn CullDistance
               OpDecorate %type_gl_PerVertex Block
               OpMemberDecorate %S_0 0 Offset 0
               OpDecorate %in_var_POSITION Location 0
               OpDecorate %in_var_COLOR Location 1
               OpDecorate %out_var_COLOR Location 0
               OpDecorate %ObjectConstants DescriptorSet 0
               OpDecorate %ObjectConstants Binding 0
       %uint = OpTypeInt 32 0
        %int = OpTypeInt 32 1
      %float = OpTypeFloat 32
    %v3float = OpTypeVector %float 3
%type_ConstantBuffer_S = OpTypeStruct %v3float
%_ptr_Uniform_type_ConstantBuffer_S = OpTypePointer Uniform %type_ConstantBuffer_S
       %void = OpTypeVoid
          %8 = OpTypeFunction %void
    %v4float = OpTypeVector %float 4
     %uint_1 = OpConstant %uint 1
%_arr_float_uint_1 = OpTypeArray %float %uint_1
%type_gl_PerVertex = OpTypeStruct %v4float %float %_arr_float_uint_1 %_arr_float_uint_1
%_ptr_Output_type_gl_PerVertex = OpTypePointer Output %type_gl_PerVertex
%_ptr_Function_v3float = OpTypePointer Function %v3float
%_ptr_Input_v3float = OpTypePointer Input %v3float
      %VSOut = OpTypeStruct %v4float %v3float
%_ptr_Output_v4float = OpTypePointer Output %v4float
%_ptr_Output_v3float = OpTypePointer Output %v3float
         %35 = OpTypeFunction %VSOut %_ptr_Function_v3float %_ptr_Function_v3float
%_ptr_Function_VSOut = OpTypePointer Function %VSOut
          %S = OpTypeStruct %v3float
%_ptr_Function_S = OpTypePointer Function %S
        %S_0 = OpTypeStruct %v3float
%_ptr_Function_v4float = OpTypePointer Function %v4float
         %67 = OpTypeFunction %v3float %_ptr_Function_S
     %uint_0 = OpConstant %uint 0
    %float_1 = OpConstant %float 1
      %int_0 = OpConstant %int 0
      %int_1 = OpConstant %int 1
%ObjectConstants = OpVariable %_ptr_Uniform_type_ConstantBuffer_S Uniform
%gl_PerVertexOut = OpVariable %_ptr_Output_type_gl_PerVertex Output
%in_var_POSITION = OpVariable %_ptr_Input_v3float Input
%in_var_COLOR = OpVariable %_ptr_Input_v3float Input
%out_var_COLOR = OpVariable %_ptr_Output_v3float Output
         %VS = OpFunction %void None %8
         %17 = OpLabel
         %25 = OpLoad %v3float %in_var_COLOR
         %77 = OpLoad %S_0 %ObjectConstants
         %78 = OpCompositeExtract %v3float %77 0
         %83 = OpCompositeExtract %float %78 0
         %84 = OpCompositeExtract %float %78 1
         %85 = OpCompositeExtract %float %78 2
         %86 = OpCompositeConstruct %v4float %83 %84 %85 %float_1
         %31 = OpAccessChain %_ptr_Output_v4float %gl_PerVertexOut %uint_0
               OpStore %31 %86
               OpStore %out_var_COLOR %25
               OpReturn
               OpFunctionEnd


```

**Comment by antiagainst** [comment]
Ouch. Sorry, I lied. It is still a problem, even in my own example.

So for your above example, loading `%ObjectConstants` should result in `%type_ConstantBuffer_S`, not `%S_0`. Note that these are two different `OpTypeStruct` types because they have different layout decorations. 

I've uploaded #874 for solving this type mismatch. Hopefully it will make the optimizer and validator happy for some workloads.

**Comment by antiagainst** [comment]
We have changed the CodeGen pattern to aid legalization. #929, which is a part of the change, is merged right now. It should enabling passing constant buffers around. I've tested the above example, the result looks good and `spirv-val` is happy with it.

There are still some legalization clean up work needed (https://github.com/KhronosGroup/SPIRV-Tools/issues/833), but that's for structured buffers. I'll close this for now. Please feel free to report cases that cannot be handled right now in a new issue.
