### ISSUE TITLE
SPIR-V: NonUniformResourceIndex support

### ISSUE THREAD

**Issue by seppala2** [Microsoft/DirectXShaderCompiler#860]
Are there plans to support NonUniformResourceIndex in SPIR-V CodeGen?

I understand that this could be difficult as long as there is no matching feature in SPIR-V, but also support for wave intrinsics would help avoiding the need to use this function.

**Comment by antiagainst** [comment]
cc @chaoticbob

**Comment by antiagainst** [comment]
There are no Vulkan equivalent for NonUniformResourceIndex right now, so we won't be able to support it. But the support for wave ops is definitely planed and will come.

**Comment by galop1n** [comment]
Is NonUniformResourceIndex not a candy helper to let the driver produce a loop over the waves if needed, something like the code below ? In that case, it could be a DXC option to either ignore or generate the extra control block explicitly in the DXIL. And decide at runtime to use one or the other based on the GPU possible need for it.

```
float4 SampleNonUniformIndex( uint textureIndex,float2 uv )
	for(;;) {
		bool match  =  textureIndex == WaveReadLaneFirst( textureIndex );
		if (match)
		{
			return textures[textureIndex].Sample( sampler, uv);
		}
	}
}
```

**Comment by antiagainst** [comment]
Addressed by https://github.com/Microsoft/DirectXShaderCompiler/pull/1256.
