### ISSUE TITLE
Include fails if file is empty

### ISSUE THREAD

**Issue by chaoticbob** [Microsoft/DirectXShaderCompiler#861]
Seems like DXC is failing to include files within the same directory.  In the attached files, ```basic.hlsl``` includes ```"other.hlsl"```, which is in the same directory and my expectation is that it should find it.

ZIP of example shader is attached. 

Command line:
````
dxc -T vs_6_0 -E vsmain -Fo shader.dxil shader.hlsl
````

Also tried using ```-I.``` and prepending the directory before ```other.hslsl``` as well. Doesn't seem to work either.

[bad_includes.zip](https://github.com/Microsoft/DirectXShaderCompiler/files/1514692/bad_includes.zip)

cc: @antiagainst @ehsannas

**Comment by ehsannas** [comment]
This happens when the file being included (`other.hlsl` in this case) is an empty file.
