### ISSUE TITLE
Some GatherRGBA methods signature is inconsistent with HLSL reference

### ISSUE THREAD

**Issue by ehsannas** [microsoft/DirectXShaderCompiler#871]
The HLSL reference for TextureCube and TextureCubeArray includes member methods:
GatherRed, GatherGreen, GatherBlue, GatherAlpha, etc.
They have a signature such as:
```cpp
TemplateType GatherRed(
  _In_  SamplerState S,
  _In_  float        Location,
  _Out_ uint         Status
);
```
However, the compiler seems to expect the `Location` argument as a `float3` in the case of TextureCube, and expects a `float4` in the case of TextureCubeArray. If the argument that I provide is just a `float` (as shown in the reference), there are VectorSplats injected in the AST to convert it to float3/float4.

I'm wondering which behavior is the correct one.

**Comment by pow2clk** [comment]
Fixed by https://github.com/MicrosoftDocs/win32/pull/1528
