### ISSUE TITLE
Crash when using "a * (b)" expressions

### ISSUE THREAD

**Issue by michalo2882** [Microsoft/DirectXShaderCompiler#88]
The following snippet is crashing the compiler. Issue doesn't occur when we remove the parenthesis from the mul expression.
```c++
RWByteAddressBuffer rawBuffer;

[numthreads(1, 1, 1)]
void main()
{
    rawBuffer.Store(4 * (0), 111);
}
```

**Comment by python3kgae** [comment]
Thanks for the feedback.
Created pull request https://github.com/Microsoft/DirectXShaderCompiler/pull/91 to fix this.
