### ISSUE TITLE
warning: #include resolved using non-portable MSVC search rules as...

### ISSUE THREAD

**Issue by chaoticbob** [Microsoft/DirectXShaderCompiler#881]
Is this warning relevant? I haven't dug in to find the specific behavior of this - was wondering if this is due to the slashes used in the include paths for #include or as apart of -I?

**Comment by chaoticbob** [comment]
@tex3d I know it's not a functional thing, but any chance someone can take a look at this? It's flooding our build logs.

**Comment by antiagainst** [comment]
https://github.com/Microsoft/DirectXShaderCompiler/pull/1266 disables this warning now.
