### ISSUE TITLE
SPIR-V: Add support for manually specifying spirv offsets in push constants

### ISSUE THREAD

**Issue by tafuri** [Microsoft/DirectXShaderCompiler#903]
Since push constant share the same memory space over all stages, it would be very useful to be able to manually specify offsets of push constant member variables.

```hlsl
struct S {
    [[vk::offset(4)]]
    float a;
    [[vk::offset(8)]]
    int b;
};

[[vk::push_constant]]
S s;
```

Q: Should offset be specified for each member or for each struct?
A: Per member. Having offsets per member, while more verbose, is also safer since it allows for validation of all the offsets. It also maps more directly to the generated spir-v code.

Q: Should this functionality be spir-v only?
A: Probably not. This functionality should ideally only map directly to spir-v:s offset decoration.

Q: Should offset be validated?
A: Yes, the requirements of these offset values should be validated against the specification.

```

**Comment by antiagainst** [comment]
Hi @tafuri, thanks for the suggestion!

Right now push constants are using GLSL [std430](https://www.khronos.org/opengl/wiki/Interface_Block_(GLSL)#Memory_layout) layout rules, like all other [structured buffers](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#buffers). I assume manually specifying offsets is for tighter data packing?

**Comment by tafuri** [comment]
Not really, it's more about making it possible to let the push constants obey shader stage visibility.

Lets say I have a parameter `scale` which is only visible to the vertex stage, and another constant called `color` which is only visible to the fragment stage.

So writing this in the shaders:
```hlsl
// Vertex shader
[[vk::push_constant]]
struct {
    float scale;
} v_constants;
// Fragment shader
[[vk::push_constant]]
struct {
    float4 color;
} v_constants;
```
won't work since both shaders will read their constant from offset 0 in the push constant buffer. The only option currently is instead to merge all push constants into a single struct and write the same struct in all stages. This is of course not optimal since it exposes unusable push constants to shader stages which have no specified access to them.

**Comment by antiagainst** [comment]
Oh, I see your use scenario right now. Thanks for the detailed explanation! That is quite reasonable. Will add. But right now we are focusing on getting structured/byte buffer aliasing correct. So it may take a while to get the code landed.

**Comment by tafuri** [comment]
I have actually made an experimental implementation on my fork. Although I have not added any validation checks or tests for it. It seems to work well in my test cases though.

**Comment by antiagainst** [comment]
Awesome! Glad to hear that your cases work. A pull request will definitely be appreciated if possible. :)

**Comment by antiagainst** [comment]
#922, which added initial support for this, is merged.
