### ISSUE TITLE
Piping shader text into the compiler instead of using files

### ISSUE THREAD

**Issue by mmostajab** [Microsoft/DirectXShaderCompiler#915]
Is it possible to pipe the shader text into the compiler instead of reading the shader file from a text file?

**Comment by marcelolr** [comment]
Not at the moment - dxc only deals with files. The DLL doesn't care either way, as it goes through the main file body and an include handler callback. Are you just trying to save writing to a temp file, or is there more to what you'd like to do?

**Comment by mmostajab** [comment]
I am just trying to save writing to a temp file and then compiling that thing. 

I would be even happier if I can try to link to the library and feed the shader code in, and get SPIR-V out. I haven't tried it, yet but I hope that is possible.
