### ISSUE TITLE
CMake 3.10 not currently supported in build process

### ISSUE THREAD

**Issue by CosmicRey** [Microsoft/DirectXShaderCompiler#949]
When trying to build with latest version of CMake, I get this error:

"CMake 3.4.3, 3.7.2, or 3.9.0 are the currently supported versions for VS 2015 and VS 2017 - your installed cmake is not supported"

and 

"CMake 3.4 if the currently supported version - your installed cmake may be out of date"

Edit:
I should have mentioned this is when trying to build with SPIR-V CodeGen

**Comment by marcelolr** [comment]
That's really more of a warning than an error - the build should proceed regardless. Do you have an error log file you could share by any chance? Or perhaps the full output you get? Targeting SPIR-V shouldn't make a difference, if cmake fails like this it's likely before that comes into play. Unless you've tried and it works when you're not targeting SPIR-V?

**Comment by CosmicRey** [comment]
Here are the output files from the most recent attempt. I should actually rename the issue, as I uninstalled CMake 3.10 and installed 3.9 to see if I would still get the same issue, and it seems I do. At this point I'm not entirely sure what I'm doing wrong, any help would he appreciated.

And yea it doesn't work whether or not I target Spir-V, I was just hoping extra information would help.

[cmake-log.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/1589844/cmake-log.txt)

[CMakeError.log](https://github.com/Microsoft/DirectXShaderCompiler/files/1589847/CMakeError.log)

[CMakeOutput.log](https://github.com/Microsoft/DirectXShaderCompiler/files/1589849/CMakeOutput.log)

**Comment by marcelolr** [comment]
Extra information usually helps, so thanks for that!

Looking through the logs, it seems that TAEF libraries aren't installed.

Tests are built using the TAEF framework. Unless you have the Windows Driver Kit installed, you should run the script at utils\hct\hctgettaef.py from your build environment before you start building to download and unzip it as an external dependency. You should only need to do this once.

Can you confirm whether running this script then re-running hctbuild works? If so, I can try automating this diagnostic in hctbuild.

Thanks in advance!

**Comment by CosmicRey** [comment]
Yes that solved the problem, thanks for that!
