### ISSUE TITLE
SPIR-V code generator is generating one additional unused struct in constant buffer, which makes it inconsistent with HLSL code

### ISSUE THREAD

**Issue by Cry-Mory** [Microsoft/DirectXShaderCompiler#952]
### Title
SPIR-V code generator is generating one additional struct in constant buffer

### Functional impact
The additional struct adds an unexpected offset to the actually used struct. Firstly, this makes the SPIR-V code inconsistent with HLSL code. Secondly, the CPU side code expects to fill the constant buffer from offset 0 and it fills the one generated by SPIR-V generator that is not used in the shader.

### Minimal repro steps:

1. Download the following vertex shader:
[AuxGeom@AuxTextVS_AuxTextVS_hlsl.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/1600160/AuxGeom.AuxTextVS_AuxTextVS_hlsl.txt)
                                        `
2. Compile it using dxc by executing: 'dxc.exe -spirv .\AuxGeom@AuxTextVS_AuxTextVS.hlsl -T vs_5_0
-E AuxTextVS' (Generated SPIR-V text can be found here: 
[generate_spirv_code.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/1600194/generate_spirv_code.txt)

### Expected result
The SPIR-V code should be consistent with hlsl code. Therefore, the constant buffer should contain only one struct containing the one used by the shader function body (cbAuxGeom). In other words, I expect to get the following code in SPIR-V:

...
**OpMemberDecorate %type_CB_AuxGeom 0 Offset 0** 
**OpDecorate %type_CB_AuxGeom Block**
...
**%_struct_5 = OpTypeStruct %mat4v4float %v2float**
**%type_CB_AuxGeom = OpTypeStruct %_struct_5**
**%_ptr_Uniform_type_CB_AuxGeom = OpTypePointer Uniform %type_CB_AuxGeom**
...
**%int_0 = OpConstant %int 0 **
**%int_1 = OpConstant %int 1 **
...
**%var_CB_AuxGeom = OpVariable %_ptr_Uniform_type_CB_AuxGeom Uniform**
...
          %71 = OpAccessChain %_ptr_Uniform__struct_5 **%var_CB_AuxGeom** %int_0
....

### Actual result
Check the shader text to see the constant buffer definition:
`cbuffer CB_AuxGeom:register(b0, space1)           `
`{                                                 `
`  struct                                          `
`  {                                               `
`    float4x4 matViewProj;                         `
`    float2 invScreenDim;                          `
`  }                                               `
`  cbAuxGeom;                                      `
`};        
We expect to get the same constant in generated SPIR-V code but an additional struct defined in the constant buffer makes it incosistent with HLSL code. It contains the following lines of code:

...
**OpMemberDecorate %type_CB_AuxGeom 0 Offset 0** 
**OpMemberDecorate %type_CB_AuxGeom 1 Offset 80**
**OpDecorate %type_CB_AuxGeom Block**
...
**%_struct_5 = OpTypeStruct %mat4v4float %v2float**
**%type_CB_AuxGeom = OpTypeStruct %_struct_5 %_struct_5**
**%_ptr_Uniform_type_CB_AuxGeom = OpTypePointer Uniform %type_CB_AuxGeom**
...
**%int_1 = OpConstant %int 1 **
...
**%var_CB_AuxGeom = OpVariable %_ptr_Uniform_type_CB_AuxGeom Uniform**
...
`  %AuxTextVS = OpFunction %void None %11                                                                                          `
`         %19 = OpLabel                                                                                      `
`         %25 = OpLoad %v4float %in_var_POSITION                                                                          `
`         %28 = OpLoad %v2float %in_var_TEXCOORD0                                                      `
`         %30 = OpLoad %v4float %in_var_COLOR0    `
          %71 = OpAccessChain %_ptr_Uniform__struct_5 **%var_CB_AuxGeom** **%int_1**
`         %72 = OpAccessChain %_ptr_Uniform_mat4v4float %71 %int_0             `
`         %73 = OpLoad %mat4v4float %72                                                                     `
`         %76 = OpVectorTimesMatrix %v4float %25 %73                                                      `
`         %36 = OpAccessChain %_ptr_Output_v4float %gl_PerVertexOut %uint_0                                  `
`               OpStore %36 %76                                                                                              `
`               OpStore %out_var_TEXCOORD0 %28                                                                                        `
`               OpStore %out_var_COLOR0 %30                                                                 `
`               OpReturn                                                                                                                                       `
`               OpFunctionEnd   ` 

As, the SPIR-V constant buffer code shows there are two structs defined in the constant buffer and the one used in the shader function body is the one stored in index 1 (offset 80).

**Comment by antiagainst** [comment]
Ah, this is a very interesting case. I bet it's because of the anonymous struct definition in `cbuffer`. We haven't covered such cases thus far. Will have a fix soon. Thanks for reporting! :)

**Comment by Cry-Mory** [comment]
Thanks a lot. Looking forward to it.

**Comment by antiagainst** [comment]
@Cry-Mory: it should be fixed now. Let me know if there are further issues. Thanks!

**Comment by Cry-Mory** [comment]
@antiagainst Thank you very much. It is working on my side.
