### ISSUE TITLE
Feature Request: Inverting the vertex shader's output position's Y component in generated SPIR-V code

### ISSUE THREAD

**Issue by Cry-Mory** [Microsoft/DirectXShaderCompiler#959]
### Title
Feature Request: 
Inverting the vertex shader's output position's Y component in generated SPIR-V code in case user asked for it.

### Reason
As SPIR-V shaders are used in vulkan and Vulkan's Normalized Device Coordinates (NDC) is different from direct3d (see below images), it makes a lot of sense to have an option in the SPIR-V compiler to invert the y-component of vertex shader's output position (the one with SV_Position semantic) in case it is needed.

Vulkan normalized device coordinates (NDC):
![image](https://user-images.githubusercontent.com/31104678/34569205-5a87f1ac-f168-11e7-8254-f1597276f774.png)

DirectX normalized device coordinates (NDC):
![image](https://user-images.githubusercontent.com/31104678/34569088-faa52f34-f167-11e7-93de-7c30efe38341.png)

* This feature is already supported by GLSLLang (https://github.com/KhronosGroup/glslang).
* At the moment, we convert hlsl to glsl and then glsl to spir-v (I am switching to this compiler to support hlsl to spir-v). In there, we fix this issue by adding "gl_Position.y = -gl_Position.y" before all the returns in the vertex shader.

### Functional impact of this feature
It makes it much easier to have a transition from directx application to vulkan ones.

### Actual result
The resulting images when shaders are used are flipped vertically. 

### Expected result
The resulting image is the same as when the shaders are used with directx.

**Comment by antiagainst** [comment]
I'm glad to hear about your switching! :) Yes, this is reasonable and we'll add such an option.

**Comment by Cry-Mory** [comment]
That was a very quick! Awesome 👍 
Thanks a lot.
