### ISSUE TITLE
SPIR-V: Default matrix order not respected for spir-v generation

### ISSUE THREAD

**Issue by tafuri** [Microsoft/DirectXShaderCompiler#960]
Changing the default default matrix order through the commandline with `-Zpr` currently does not have any effect on generate spirv code. The only way to change the order of a matrix is to declare it directly on a matrix.

**Comment by Cry-Mory** [comment]
I think the order of multiplication is not changing but they make the matrix decoration row-major. I had an issue with the change in order which I fixed using (-Zpr).

**Comment by antiagainst** [comment]
Done via #961. Thanks, @tafuri!
